### ISSUE TITLE
Display a blank page on a real iOS device.

### ISSUE THREAD

**Issue by realkimmy** [pichillilorenzo/flutter_inappwebview#1002]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.5.2         |
| Plugin version       |        5.3.2       |
| Android version      |               |
| iOS version          |       15.0.1        |
| Xcode version        |       13.0        |

Device information: 

## Description

**Expected behavior:** 
Display normally on the real iOS device

**Current behavior:** 
A blank page is displayed on the real iOS device, and it is displayed normally on the iOS simulator

## Images   
![IMG_0728](https://user-images.githubusercontent.com/19725091/136298841-5ee90a68-f4c4-4e6d-8fe9-dd9d5b7e4688.jpeg)

**Comment by mo-aro-etailer** [comment]
how did you solve this?

**Comment by mo-aro-etailer** [comment]
@see

**Comment by see** [comment]
Sorry, I forgot how to fix it

**Comment by mo-aro-etailer** [comment]
I know how now

This is how to fix it

 onWebViewCreated: (controller) {

                controller.loadUrl(
                  urlRequest: URLRequest(
                    url: Uri.parse(_currentUrl),
                    headers: {
                ///add basic auth header to url request
                      'Authorization': 'Basic ' +
                          base64Encode(
                            utf8.encode(
                              '$username:$password',
                            ),
                          ),

                      ///edit encoding to fix blank space
                      'Accept-Encoding': 'gzip, deflate, br',
                    },
                  ),
                );
              webViewController = controller;
            },
