### ISSUE TITLE
App crash when i want to uploads file?

### ISSUE THREAD

**Issue by hanafiahtkj** [pichillilorenzo/flutter_inappwebview#1004]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by Sagar-KC-3082** [comment]
Yeah the app crashed when there is a file type request in html page . This happens only when your android version is below 11

**Comment by MajedAlaejem** [comment]
I have the same issues

**Comment by FatihBaycu** [comment]
https://stackoverflow.com/a/71968030/16504129
This worked for me. I used the code as is, I did not make any changes.
