### ISSUE TITLE
When onOverScrolled event will be fired

### ISSUE THREAD

**Issue by winterdl** [pichillilorenzo/flutter_inappwebview#1005]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.5.2       |
| Plugin version       |         5.3.2      |
| Android version      |        10       |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
I'm writing an ebook viewer, each chapter is a webpage and will be display using a webview, each webpage will display horizontal using css column (fixed height and extended width).

I'm catching the onOverScrolled to detemine when user reach the end of chapter and I will load next chapter.

**Expected behavior:** 
When I swipe left or right, if the content reach the end of the page or begining of page, I expected onOverScrolled will be fired

**Current behavior:** 
All webpage have content longer one screen page, the event will be fired, but webpage with short content on one screen page (as image that attached), the event will not be fired. 

** My question **
My question is how to get onOverScrolled to be called regardless of the length of the content?

<img width="383" alt="Screen Shot 2021-10-09 at 6 53 47 PM" src="https://user-images.githubusercontent.com/302480/136657046-7fecf6e4-d655-45bd-a4a3-2b63dd8b67ed.png">

**Comment by winterdl** [comment]
I set size for viewport then the onOverScrolled will be called.

**Comment by siraj-logicvalley** [comment]
@winterdl how to set size for viewport? can u please share sample code?
