### ISSUE TITLE
Webview does not show thumbnail(Preview Image) of videos.

### ISSUE THREAD

**Issue by omerbyrk** [pichillilorenzo/flutter_inappwebview#1011]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.2.3        |
| Plugin version       |        5.3.2       |
| Android version      |      10         |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

On mobile browser, thumbnail of the video works fine. But In the webview, I can't see them all. So It is reducing user experience. I am waiting response from you. 

## Stacktrace/Logcat  

https://user-images.githubusercontent.com/23620744/137576127-f676bb33-469c-4a57-a189-71c604658a2d.mp4

**Comment by chavesgu** [comment]
@omerbyrk Hi,  same issue,  did you solve this problem?

**Comment by omerbyrk** [comment]
Yeah. it was version related problem or simulator based. But not about the plugin.

**Comment by omerbyrk** [comment]
No. I couldn't solve it. But It is not all about the webview. It is about the website not compatible with webview.
