### ISSUE TITLE
Blank page with enabled javascript

### ISSUE THREAD

**Issue by userentity** [pichillilorenzo/flutter_inappwebview#1013]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.6.0       |
| Plugin version       |        5.3.2       |
| Android version      |          31.0.0     |
| iOS version          |        15.2       |
| Xcode version        |          13.0     |

Hello everyone!
When clicking on the links on the site whatsapp.com blank pages open. 
The URL in "onLoadStart" returns an empty string. No errors  in "onLoadError".
If  paste the URL into "initialUrlRequest", then everything works fine.
If disable JavaScript, then everything works fine too. This problem is only with JavaScript enabled.
if open the site and click link in a regular browser, then everything is fine
Thank you for your help!

**Comment by joranmulderij** [comment]
I'm getting the same problem. For me it's appears both when JavaScript is off and when it's on (Android). Hope this gets fixed. Is there a version of this package that we could roll back onto?
