### ISSUE TITLE
Microphone stops working on iOS if the app is minimized

### ISSUE THREAD

**Issue by TheMightyPenguin** [pichillilorenzo/flutter_inappwebview#1016]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.5.2         |
| Plugin version       |       5.3.2        |
| Android version      |      11         |
| iOS version          |      12.0         |
| Xcode version        |   13.0            |

Device information: Testing on a physical iPhone 12 pro (iOS 15.0.2 19A404)

## Description

I'm using flutter_inappwebview to show a webview, that has webrtc capabilities, using both camera and video it works fine until the app is set to the background.

When the app is minimized (goes to background), I can still hear other users on the call but my microphone stops working and others cannot hear me.

This does work fine in Android but does not on iOS.

I'm using flutter_inappwebview version 5.3.2, and has the Audio background mode in my Info.plist file:

```
    <key>UIBackgroundModes</key>
    <array>
        <string>audio</string>
        <string>fetch</string>
        <string>remote-notification</string>
    </array>
```

**Comment by milzamhibatullah** [comment]
hi @pichillilorenzo it happens on me too, When the app is minimized (goes to background), I can still hear other users on the call but my microphone stops working and others cannot hear me.

thanks ^_^
