### ISSUE TITLE
Unable to pull to refresh (nothing happens)

### ISSUE THREAD

**Issue by yoannpicquenot** [pichillilorenzo/flutter_inappwebview#1021]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.5.3        |
| Plugin version       |    ^5.3.2           |
| Android version      |    11        |
| iOS version          |         15.0.2      |
| Xcode version        |        13     |

Device information:
Samsung S21, iPhone 6s (tested on both)

## Description
pullToRefresh does not work (I am sorry I really don't know what to write except this)

**Expected behavior:** 
I expected my onRefresh function to be called on vertical drag up.

**Current behavior:** 
Nothing happens. I don't even see a loading when pulling from the top.

## Steps to reproduce

```
return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: InAppWebView(
                initialOptions: InAppWebViewGroupOptions(
                  crossPlatform: InAppWebViewOptions(
                    javaScriptEnabled: true,
                    useOnDownloadStart: true,
                    mediaPlaybackRequiresUserGesture: false,
                  ),
                  android: AndroidInAppWebViewOptions(
                    useHybridComposition: true,
                  ),
                  ios: IOSInAppWebViewOptions(
                    allowsInlineMediaPlayback: true,
                  ),
                ),
                initialUrlRequest: URLRequest(
                  url: Uri.parse(url),
                  headers: <String, String>{
                    'referer': 'https://app.monpetitplacement.fr',
                  },
                ),
                pullToRefreshController: PullToRefreshController(
                  options: PullToRefreshOptions(
                    color: MppColors.Primary,
                    enabled: true,
                  ),
                  onRefresh: () async {
                    if (Platform.isAndroid) {
                      await _controller.reload();
                    } else if (Platform.isIOS) {
                      await _controller.loadUrl(
                        urlRequest: URLRequest(
                          url: await _controller.getUrl(),
                        ),
                      );
                    }
                  },
                ),
                onWebViewCreated: (InAppWebViewController controller) async {
                  _controller = controller;
                  if (!Platform.isAndroid ||
                      await AndroidWebViewFeature.isFeatureSupported(
                          AndroidWebViewFeature.WEB_MESSAGE_LISTENER)) {
                    // establish flutter channel
                  }
                },
              ),
            ),
          ],
        ),
      ),
    )
```

**Comment by rafaelmaeuer** [comment]
What is the URL you are loading? Is the source at web or in app assets? I experienced something similar when loading local assets.

**Comment by lugael** [comment]
I'm facing the same issue, I can't perform the pull action, do you have any sample code to check?

**Comment by lugael** [comment]
`dasda`

**Comment by lugael** [comment]
@pichillilorenzo  this is code, but no working pull actions

![code](https://user-images.githubusercontent.com/79815839/209571500-cf19594a-f3a4-42e8-9106-083dcc7fdc0b.png)
