### ISSUE TITLE
InAppWebView memory leak on Android

### ISSUE THREAD

**Issue by pangff** [pichillilorenzo/flutter_inappwebview#1023]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.5.0       |
| Plugin version       |       5.3.2        |
| Android version      |      30         |
| iOS version          |        -       |
| Xcode version        |       -          |

Device information: 

HUAWEI P40 ANA-AN00

## Description
Run  the latest example (https://github.com/pichillilorenzo/flutter_inappwebview/tree/master/example) with debug mode on Android mobile ,close  inAppWebView page,  inAppWebView not release. 

**Expected behavior:** 

close  inAppWebView page,  inAppWebView release. 

**Current behavior:** 

close  inAppWebView page,  inAppWebView not release. 

## Steps to reproduce

1. Run  the latest example (https://github.com/pichillilorenzo/flutter_inappwebview/tree/master/example) with debug mode on Android mobile.
2. Start inAppWebView page, and then navigate to other page.
3.  Click GC button in DevTools memoy Tab  to force GC.
4. Click Track button in Allocations View. InAppWebViewExampleScreen instance count > 0.

## Images   

![截屏2021-11-03 下午2 51 13](https://user-images.githubusercontent.com/2368696/140019524-cf656f8e-5d40-41e3-90a6-5c7a86c81ddf.png)

**Comment by Lamda303** [comment]
it still exists.

**Comment by mohammedX6** [comment]
I have the same problem

**Comment by elliotrtd** [comment]
Shocking that a 2 year old bug is still open. 

This seems to be the reason behind a crash for my largest customers. Unfortunately looks like this package has been neglected for too long now...
