### ISSUE TITLE
InAppWebView doesn't work in api level 24

### ISSUE THREAD

**Issue by mehmetsukrumumbucoglu** [pichillilorenzo/flutter_inappwebview#1026]
Hello there,
  I am also using InAppWebView in my android application. The webview part is not visible on an emulator or device with api level 24. The console output on the device with apilevel 24 in the emulator is as follows. What could be the problem?

> D/NetworkSecurityConfig( 6424): No Network Security Config specified, using platform default
I/art     ( 6424): Background sticky concurrent mark sweep GC freed 17606(1459KB) AllocSpace objects, 8(160KB) LOS objects, 42% free, 5MB/8MB, paused 31.813ms total 53.515ms
I/cr_Ime  ( 6424): ImeThread is not enabled.
E/libEGL  ( 6424): validate_display:99 error 3008 (EGL_BAD_DISPLAY)
I/VideoCapabilities( 6424): Unsupported profile 4 for video/mp4v-es
D/        ( 6424): HostConnection::get() New Host Connection established 0x844f1000, tid 6489
I/X509Util( 6424): Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
D/EGL_emulation( 6424): eglCreateContext: 0x8439de60: maj 2 min 0 rcv 2
D/EGL_emulation( 6424): eglMakeCurrent: 0x8439de60: ver 2 0 (tinfo 0x84398c60)
W/cr_BindingManager( 6424): Cannot call determinedVisibility() - never saw a connection for the pid: 6424
D/EGL_emulation( 6424): eglMakeCurrent: 0x9f8a0040: ver 2 0 (tinfo 0x9f8e6400)
D/EGL_emulation( 6424): eglMakeCurrent: 0x9f8a0040: ver 2 0 (tinfo 0x9f8e6400)
D/EGL_emulation( 6424): eglMakeCurrent: 0x9f8a0040: ver 2 0 (tinfo 0x9f8e6400)

**Comment by mehmetsukrumumbucoglu** [comment]
yes, I did enough research. I couldn't find a solution.

**Comment by Colman** [comment]
May be related to this: https://stackoverflow.com/questions/69511057/flutter-on-android-7-certificate-verify-failed-with-letsencrypt-ssl-cert-after-s
