### ISSUE TITLE
Publish failed on Google play: SSL Handler

### ISSUE THREAD

**Issue by thunshell** [pichillilorenzo/flutter_inappwebview#1027]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat   
Hello Google Play Developer,
We reviewed myapp, with package name com.xxx.myapp, and found that your app uses software that contains security vulnerabilities for users. Apps with these vulnerabilities can expose user information or damage a user’s device, and may be considered to be in violation of our Malicious Behavior policy.

Below is the list of issues and the corresponding APK versions that were detected in your recent submission. Please migrate your apps to use the updated software as soon as possible and increment the version number of the upgraded APK.
SSL Error Handler
For more information on how to address WebView SSL Error Handler alerts, please see this [Google Help Center article](https://notifications.google.com/g/p/AD-FnEwPZ-AVz0eZYQh7PG7jSZVNwBddpaMmcEpjB1MRmAwxD0I5L2Brcp2zzTFGNZtRgeBmtuZfJu2SOV1hMG7kgDO7Iy8xYoN2irINi03BgFiO).

**Comment by SungilJung** [comment]
Has anyone found a solution?

**Comment by chaudharydeepanshu** [comment]
I'm also facing the same issue. And I found that there is a method called certificate pinning which compares the certificate received and the certificate already provided in the app. But I don't quite understand how to achieve that as there was no example based on flutter and inappwebview. 

I also have one doubt for @pichillilorenzo (Sorry to disturb) . The [flutter_browser_app] (https://github.com/pichillilorenzo/flutter_browser_app) works with the URLs which have "Missing intermediate certificate" issue. I tried to understand how it works but I didn't find anything related to that and just ended up updating the [project](https://github.com/pichillilorenzo/flutter_browser_app/pull/11). The link I used for testing was [this](https://vtop.vitbhopal.ac.in/vtop) which worked fine in your app but not mine. The flutter_browser_app doesn't even receive a ```onReceivedServerTrustAuthRequest```. So can you tell us how you are handling this situation in your app? As it is available on playstore also so google must not have any issue with your app.

Thank you.
