### ISSUE TITLE
Error on open camera on iOS 12.5.5

### ISSUE THREAD

**Issue by devthlsoft** [pichillilorenzo/flutter_inappwebview#1028]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    2.5.3           |
| Plugin version       |      5.3.2         |
| Android version      |               |
| iOS version          |          12.5.5     |
| Xcode version        |       13.0        |

Device information: 

## Description

 We use this library to call my web and we have request camera permission in my code for scan qrcode using zxing/ngx-scanner , it work well on iOS 14 and 15, but on iOS 12.5 it log the message below. (I have run the url on Safari on iOS 12.5 and it work well)

## Stacktrace/Logcat   
flutter: {message: @zxing/ngx-scanner Can't get user media, this is not supported., messageLevel: 3}

**Comment by vantutrieu97** [comment]
I am facing the same problem, any update bro?
