### ISSUE TITLE
some non-english characters corrupted on previous iOS

### ISSUE THREAD

**Issue by kodol73** [pichillilorenzo/flutter_inappwebview#1039]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.5.3  |
| Plugin version       |  5.3.2  |
| iOS version          |  12.5.5  |
| Xcode version        |  12.2  |

Device information: Apple iPad Air

## Description
Some Chinese characters are corrupted through the webview, flutter_inappwebview, on iPad Air.
For example, 
    '积极乐观的' is corrupted to 'ㅁㅁㅁㅁ的'
    '免费' is corrupted to '免ㅁ'
    '认出' is corrupted to 'ㅁ出'

However, these characters look without corrcuption through Chrome on this device.

And this issue doesn't occur on iOS 14.7.1, iPhone6S.

I set the headers like the following as the parameter of initialUrlRequest of InAppWebView().
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'charset': 'UTF-8',   // prevent characters corruption
          }

And I set like the following on the webpage.
    meta content="IE=9" http-equiv="X-UA-Compatible"
    meta content="text/html; charset=utf-8" http-equiv=Content-Type
    meta charset="UTF-8"
    meta name="viewport" content="width=device-width, initial-scale=1"

Please help me to solve this issue.
Thanks in advance

**Comment by jusuf-el** [comment]
Any updates on this one @kodol73 ?
