### ISSUE TITLE
crash at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView$11.run (InAppWebView.java:1307)

### ISSUE THREAD

**Issue by rsydor** [pichillilorenzo/flutter_inappwebview#1040]
very rarely crash. NullPointerException at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView$11.run(InAppWebView.java:1307)

- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [ ] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.2.3      |
| Plugin version       |         5.3.2      |
| Android version      |         11      |
| iOS version          |              - |
| Xcode version        |            -   |

Device information: XIAOMI POCO X3 Pro

## Description
On 

**Expected behavior: work without crash

**Current behavior:very rarely crash

## Steps to reproduce: at show page with InAppWebView

`
  Widget _buildContent(BuildContext dialogContext, Cubit cubit) {
    return Container(
      child: InAppWebView(
          initialUrlRequest: URLRequest(
              url: Uri.parse(_params.url), headers: {"'Authorization'": "${_credentials}"}),
        onWebViewCreated: (InAppWebViewController controller) {
          controller.addJavaScriptHandler(handlerName:'handler', callback: (args) async {
            final returnValue = await _onConfirm(args, dialogContext, cubit);
            if (null != returnValue) {
              return returnValue;
            }
          });
        },
      ),
    );
  }
`

## Stacktrace/Logcat   
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView$11.run(InAppWebView.java:1307)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8056)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by rsydor** [comment]
I searched but I don't find.

**Comment by daozhishier** [comment]
### Version: 0.4.0,   in iOS:

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.pichillilorenzo/flutter_inappwebview', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:236:5)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:639:44)
<asynchronous suspension>
