### ISSUE TITLE
can't open keyboard on android 12

### ISSUE THREAD

**Issue by TrieuCan** [pichillilorenzo/flutter_inappwebview#1043]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   Channel stable, 1.22.6  |
| Plugin version       |      ^4.0.0+4         |
| Android version      |     12          |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
when i press input keyboard does not show

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by kimalphaville** [comment]
I have the same issue. Have you solve this problem ? @TrieuCan

**Comment by filipmaj1** [comment]
I too am seeing this problem, only on Android 12 on a Pixel 4a.

**Comment by kimalphaville** [comment]
I've fixed this issue by adding useHybridComposition: true on the initial options

https://inappwebview.dev/docs/in-app-webview/basic-usage/

**Comment by Calx-Takeno** [comment]
<html>
<body>


Technology | Version
-- | --
Flutter version | Channel stable, 1.22.6
Plugin version | ^4.0.0+4
Android version | 12


</body>
</html>

pixel 4 same issue.
any one fixed this?

useHybridComposition feature required minimal 5.x version.
I can not upgrade flutter_inappwebview 4.0.0+4 to 5.x version in my project.

**Comment by filipmaj1** [comment]
> I've fixed this issue by adding useHybridComposition: true on the initial options
> 
> https://inappwebview.dev/docs/in-app-webview/basic-usage/

Fixed it for me.

**Comment by Andrushka1012** [comment]
Same problem on pixel 6 
(android 12, flutter version - 2.5.3, flutter_inappwebview: 5.3.2, minSdkVersion 21) 

When I set `useHybridComposition: true` the screen with web view just does not appear.  Strange thing that I had same issue with https://pub.dev/packages/webview_flutter when I set `if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();`
