### ISSUE TITLE
mayLaunchUrl optional parameter in ChromeSafariBrowser

### ISSUE THREAD

**Issue by Navarad** [pichillilorenzo/flutter_inappwebview#1045]
Hello, I have a problem when using Chrome Custom Tabs when opening url that must be opened only once. When I open this url using ChromeSafariBrowser then on some devices was this url opened twice. When I was looking in the code I found out that before actually opening the link, the link is preloaded using mayLaunchUrl() which may cause problem.

Is it possible to add optional flag not to use this call: mayLaunchUrl() ? Something like "useUrlPreload = true".

Thank you

**Comment by YasufumiMuranaka** [comment]
@Navarad Please try this. Thank you,
```
void launchInBrowser(ChromeSafariBrowser chromeSafariBrowser, String uri) async {
  try {
    if (chromeSafariBrowser.isOpened()) await chromeSafariBrowser.close();
    await chromeSafariBrowser.open(
        url: Uri.parse(uri), options: ChromeSafariBrowserClassOptions(android: AndroidChromeCustomTabsOptions(noHistory: true)));
  } catch (e) {
    // An exception is thrown if browser app is not installed on Android device.
    debugPrint(e.toString());
  }
}
```
