### ISSUE TITLE
Listen to url Changes in ChromeSafariBrowser

### ISSUE THREAD

**Issue by jreliberty** [pichillilorenzo/flutter_inappwebview#1047]
## Environment

**Flutter version: Flutter 2.5.3 • channel stable** 
**Plugin version: flutter_inappwebview: ^5.3.2 **  

## Description

Hello,
I am developping an app that needs an authentification via a Webview, everything is handled by the API.
The thing is that they use Google login, Facebook login and Apple login. Plus of course a normal login with username and password.
I first used the InAppBrowser from your package. Everything worked fine until I tried the Google and Facebook Login ...

![image](https://user-images.githubusercontent.com/85485566/144397106-fb24718d-cfa2-4371-a5c8-46ee217fdfaf.png)
![image](https://user-images.githubusercontent.com/85485566/144397177-dcbc787e-cc87-4d57-bfed-b10b1e468446.png)

So I tried to do it with ChromeSafariBrowser and everything works fine but I have one problem, I can't listen to the url changes to know when to cloase the browser and get my jwt token... Is there a way to listen to url changes within a ChromeSafaribrowser? I'm stuck since last week ... I would appreciate some help !

Thanks in advance

**Comment by renanmgs** [comment]
Up

**Comment by FlawLessx** [comment]
for google login you can define user agent first, for the facebook login i also had a problem

**Comment by FlawLessx** [comment]
by someone facing this issue, simply change user agent into 'YourAppNameV1.0.0', worked for me for login facebook & google in disqus webview
