### ISSUE TITLE
Support Windows (desktop) ?

### ISSUE THREAD

**Issue by zhujintao** [pichillilorenzo/flutter_inappwebview#1048]
Support Windows (desktop) ?

**Comment by wilz05** [comment]
same here waiting for macOs and windows Support

**Comment by j0chn1** [comment]
Hey,
I'd also like to see this plugin supporting desktops.
Maybe you can just state if you are going to do so or not?

**Comment by see** [comment]
Desktop support?

**Comment by jaroslawdabrowski** [comment]
I really like the library, but I am also wondering if there will be support for desktop (windows + macOs). There is similar library for react native that has similar functionality and support for both windows and macOS, so it seems that it is somehow doable. I understand that it is not possible for web as iframe has a lot of limitations and strong isolation level.

**Comment by liaoxuewei** [comment]
> same here waiting for macOs and windows Support

Me, too. :)

**Comment by wanjm** [comment]
I also need the support of windows;

**Comment by venky9885** [comment]
Windows support released @zhujintao ,You can close this

**Comment by wanjm** [comment]
cool， 
how can it be implement as platform view is not ready for windows;
