### ISSUE TITLE
I tried to run a webview page needs camera permission but it crashed

### ISSUE THREAD

**Issue by KarimMohamed20** [pichillilorenzo/flutter_inappwebview#1053]
I used this page in "InAppWebView" but it crashed
https://hiukim.github.io/mind-ar-js-doc/samples/basic.html

I use this code
InAppWebView(
            
            
            initialUrlRequest: URLRequest(url:Uri.parse("https://hiukim.github.io/mind-ar-js-doc/samples/basic.html"),),
            
            initialOptions: InAppWebViewGroupOptions(
              
              android: AndroidInAppWebViewOptions(),
              crossPlatform: InAppWebViewOptions(
                
                mediaPlaybackRequiresUserGesture: false,
              ),
            ),
            
            onWebViewCreated: (InAppWebViewController controller) {
              _webViewController = controller;
              
            },
             shouldOverrideUrlLoading: (controller, navigationAction) async {
                          var uri = navigationAction.request.url!;

                          if (![ "http", "https", "file", "chrome",
                            "data", "javascript", "about"].contains(uri.scheme)) {
                            
                          }

                          return NavigationActionPolicy.ALLOW;
                        },
            androidOnPermissionRequest: (InAppWebViewController controller, String origin, List<String> resources) async {
              return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
            },
            
          ),

**Comment by massimilianochiodi** [comment]
Ciao Mohamed

Also, you need to add the following code inside the <application> tag of your AndroidManifest.xml file:

```
<provider
    android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
    android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />
</provider>
```
