### ISSUE TITLE
ThreeJS doesn't work

### ISSUE THREAD

**Issue by KarimMohamed20** [pichillilorenzo/flutter_inappwebview#1057]
This is my example
``` InAppWebView(
              initialUrlRequest: URLRequest(
                url: Uri.parse("https://threejs.org"),
              ),
              initialOptions: InAppWebViewGroupOptions(
                android: AndroidInAppWebViewOptions(),
                crossPlatform: InAppWebViewOptions(
                  mediaPlaybackRequiresUserGesture: false,
                ),
              ),
              onWebViewCreated: (InAppWebViewController controller) {
                _webViewController = controller;
              },
              shouldOverrideUrlLoading: (controller, navigationAction) async {
                var uri = navigationAction.request.url!;

                if (![
                  "http",
                  "https",
                  "file",
                  "chrome",
                  "data",
                  "javascript",
                  "about"
                ].contains(uri.scheme)) {}

                return NavigationActionPolicy.ALLOW;
              },
              
            ),
```

**Comment by apetroaeiandrei** [comment]
I managed to open threejs 3d models. Try to use the following config:
`static get webViewOptions => InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      useShouldOverrideUrlLoading: false,
      mediaPlaybackRequiresUserGesture: false,
      javaScriptEnabled: true,
    ),
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),
    ios: IOSInAppWebViewOptions(
      allowsInlineMediaPlayback: true,
    ),
  );`

**Comment by kaushikcw** [comment]
@apetroaeiandrei I got the basic three JS App running but getting issues with loading gltf, where the texture pngs are not loading. Eg: 

`Fetch API cannot load file:///android_asset/flutter_assets/assets/models/Building_02_Test_04_export_gltf/T_Generic_Colors%201.jpg. URL scheme "file" is not supported.`

Please let me know if there is anyway I can connect?
