### ISSUE TITLE
The method FwfhTextStyle.apply has fewer named arguments than those of overridden method TextStyle.apply

### ISSUE THREAD

**Issue by a-v-ebrahimi** [pichillilorenzo/flutter_inappwebview#1059]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.8.0      |
| Plugin version       |          5.3.2     |
| Android version      |         12      |
| iOS version          |         15      |
| Xcode version        |        13.2       |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 
One of my libraries use flutter_inappwebviwe, and now I can't compile for iOS after upgrading to Flutter 2.8.0
## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat   
../Programming/flutter/.pub-cache/hosted/pub.dartlang.org/fwfh_text_style-2.5.0+1/lib/fwfh_text_style.dart:15:13: Error: The method 'FwfhTextStyle.apply' has fewer
    named arguments than those of overridden method 'TextStyle.apply'.
      TextStyle apply({
                ^
    ../Programming/flutter/packages/flutter/lib/src/painting/text_style.dart:890:13: Context: This is the overridden method ('apply').
      TextStyle apply({
                ^
    ../Programming/flutter/.pub-cache/hosted/pub.dartlang.org/fwfh_text_style-2.5.0+1/lib/fwfh_text_style.dart:15:13: Error: The method 'FwfhTextStyle.apply' doesn't have
    the named parameter 'package' of overridden method 'TextStyle.apply'.
      TextStyle apply({
                ^

**Comment by daohoangson** [comment]
Try running `flutter pub upgrade fwfh_text_style`.

**Comment by a-v-ebrahimi** [comment]
Thanks
`flutter pub upgrade fwfh_text_style `
then
`flutter pub outdated`
solved it!
Thanks again.

**Comment by a-v-ebrahimi** [comment]
@daohoangson
But why does not Flutter upgrade to the latest version of fwfh_text_style, even with cache repair?

**Comment by daohoangson** [comment]
Probably because that package's version constraint is still satisfied.
