### ISSUE TITLE
how to webview using chrome style for android, and safari style for ios

### ISSUE THREAD

**Issue by eggysudianto** [pichillilorenzo/flutter_inappwebview#1060]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.8.1 |
| Plugin version       |  ^5.3.2  |
| Android version      |  9.0.0   |
| iOS version          |    |
| Xcode version        |               |

Device information: 

## Description

I have datepicker in mywebview, if I open in chrome the style like this 
![image](https://user-images.githubusercontent.com/16233241/146865154-6e032b0f-68cc-4835-b063-33d9c2d5e0d4.png)

but if using inappwebview the style like this 
![image](https://user-images.githubusercontent.com/16233241/146865192-18f2b9be-154c-43db-9919-d389c8d1b3f6.png)

```
body: Column(children: <Widget>[
        Container(
            // padding: EdgeInsets.all(10.0),
            child: progress < 1.0
                ? LinearProgressIndicator(value: progress)
                : Container()),
        Expanded(
          child: InAppWebView(
            initialUrlRequest: URLRequest(url: Uri.parse(widget.url)),
            initialOptions: InAppWebViewGroupOptions(
              android: AndroidInAppWebViewOptions(
                useHybridComposition: true,
              ),
              crossPlatform: InAppWebViewOptions(
                useShouldOverrideUrlLoading: true,
              ),
            ),
            onWebViewCreated: (
                InAppWebViewController controller) async {
              _webViewController = controller;
            },
            androidOnPermissionRequest: (controller, origin, resources) async {
              return PermissionRequestResponse(
                  resources: resources,
                  action: PermissionRequestResponseAction.GRANT);
            },
            onProgressChanged: (InAppWebViewController controller,
                int progress) {
              setState(() {
                this.progress = progress / 100;
              });
            },
          ),
        ),
      ]),
```

how to webview can support style like chrome?

**Comment by MartinMacek** [comment]
This is a way how you change it. You need to create AppTheme in styles, where you set theme to device default. Then you just call it from manifest

<img width="671" alt="Screenshot 2022-01-25 at 16 21 24" src="https://user-images.githubusercontent.com/19749268/151005201-400c71be-b12b-42a9-bcd9-0f95ced4f0c7.png">

code here:
styles.xml
`<style name="AppTheme" parent="android:Theme.DeviceDefault.Light">
        
        <item name="android:windowActionBar">false</item>
        <item name="android:windowNoTitle">true</item>
    </style>`
