### ISSUE TITLE
 <input type="file" accept="image/*" capture="camera" > need call camera directly

### ISSUE THREAD

**Issue by acalephx** [pichillilorenzo/flutter_inappwebview#1072]
## Environment

**Flutter version: 2.0.3** 
**Plugin version:5.3.2**    
**Android version:11**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

my html has this input, i Click the input(Camera text), i need to choose camera or file

` <input type="file" accept="image/*;capture=camera" >`

![微信截图_20220106182344](https://user-images.githubusercontent.com/29752506/148368391-87aff491-e83c-4e9b-81d4-0948a5f7cd45.png)

i hope when capture=camera, webview can call camera directly

**Alternatives you've considered:**   

**Images:**

**Comment by acalephx** [comment]
#746

**Comment by acalephx** [comment]
the https://github.com/pichillilorenzo/flutter_inappwebview/issues/846#issuecomment-873542917 method, works on  android version 9.0（API 28)

**Comment by pichillilorenzo** [comment]
Feature added starting from version `5.5.0`
