### ISSUE TITLE
Allow preload / prerender with a HeadlessInappWebView and transform it into an InAppWebView

### ISSUE THREAD

**Issue by jmgeffroy** [pichillilorenzo/flutter_inappwebview#1081]
Hi there, congrats on this great webview integration. We are developing an [epub reader SDK](https://github.com/Mantano/iridium), where each chapter (HTML) is rendered by a webview. Webviews are placed in a [PreloadPageView](https://pub.dev/packages/preload_page_view), which can pre-build as many pages as we specify through a `preloadPageCount`param. 
When using Virtual Displays on Android, offscreen webviews are pre-rendered and everything is OK, except that animations when swiping to turn pages aren't smooth. So we need to use Hybrid Composition, which also happens to be the only option available on iOS, BTW.

I tried both`webview_flutter` and `flutter_inappwebview`, same behavior. 

So I am thinking about the best way to have prerendering working even with hybrid composition. An obvious path would be to use the `HeadlessInappWebView`. We could use it to generate images of each chapter page and place them in a listview. Then, once a chapter becomes visible, we replace this list of images with a real `InAppWebView`.
Of course, this is doable and would work, but it is far from being elegant. So I was wondering if it wouldn't be smarter to provide means to dynamically attach a `HeadlessInAppWebView` to the view tree and transform it into an `InAppWebView`?

**Comment by TheCarpetMerchant** [comment]
@jmgeffroy Did you end up finding a solution to this ?
