### ISSUE TITLE
Inappwebview widget does not enter dark mode on ios

### ISSUE THREAD

**Issue by ederluca** [pichillilorenzo/flutter_inappwebview#1082]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
This documentation has been checked 
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
This documentation has been checked
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
This documentation has been checked
- [x] I have already searched for the same problem
I did a quick search and didn't find any mention of this issue

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.8.1  |
| Plugin version       | 5.3.2  |
| Android version      |               |
| iOS version          | 15.2.1  |
| Xcode version        | 13 |

Device information: 
Iphone 6S
## Description
When enabling dark mode on the physical device on an iphone 6s the Inappwebview widget is not in dark mode, always remaining in Light mode I would like to know if the widget is compatible with dark mode on ios, on android it is normally entering dark mode.

Performing a debug I didn't find any apparent errors in the logs.

**Expected behavior:** 
I would like that when enabling dark mode on the device, the webview would enter dark mode as it does on android.

**Current behavior:** 
Currently in version 5.3.2 it is not going into dark mode, it is always in light mode.

## Steps to reproduce
When opening the application it is already possible to see that the dark mode is not working in the webview.

**Comment by rafaelmaeuer** [comment]
I can maybe help with this one when finding some time. I am already using darkmode with inappwebview in a flutter app.

**Comment by ederluca** [comment]
> Talvez eu possa ajudar com isso quando encontrar algum tempo. Eu já estou usando darkmode com inappwebview em um aplicativo flutter.

how did you make it work on ios? I tried several things but without success.

**Comment by mohabbatta** [comment]
> 

if you find  a solution, please share it with me

**Comment by poshak** [comment]
any luck ?

**Comment by Hilbert2048** [comment]
you need to inject a night mode JS script to implement this, by add UserScript

**Comment by Cedrick-J** [comment]
> you need to inject a night mode JS script to implement this, by add UserScript

Which one did you use
