### ISSUE TITLE
Load client certificate from local storage fails

### ISSUE THREAD

**Issue by stedekay** [pichillilorenzo/flutter_inappwebview#1085]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.10.1           |
| Plugin version       | 5.3.2              |
| Android version      | 11              |
| iOS version          |               |
| Xcode version        |               |

Device information: Pixel 4
## Description
I try to load a client certificate which is stored in the FlutterSecureStorage:

```dart
return InAppWebView(
  initialUrlRequest:
      URLRequest(url: Uri.parse("<URL>")),
  onReceivedClientCertRequest: (InAppWebViewController controller,
      URLAuthenticationChallenge challenge) async {
    return ClientCertResponse(
        certificatePath: certPath,
        certificatePassword: certPassword,
        action: ClientCertResponseAction.PROCEED);
  }
);
```

**Expected behavior:** 
The client certificate is loaded correctly and the website loads as expected.

**Current behavior:** 
I get the following exception:

```
W[/System.err]()( 4107): java.io.FileNotFoundException: flutter_assets//data/user/0/com.example.test/app_flutter/cert/EXAMPLE00004.p12
W[/System.err]()( 4107): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W[/System.err]()( 4107): 	at android.content.res.AssetManager.open(AssetManager.java:874)
W[/System.err]()( 4107): 	at android.content.res.AssetManager.open(AssetManager.java:851)
W[/System.err]()( 4107): 	at com.pichillilorenzo.flutter_inappwebview.Util.getFileAsset(Util.java:83)
W[/System.err]()( 4107): 	at com.pichillilorenzo.flutter_inappwebview.Util.loadPrivateKeyAndCertificate(Util.java:139)
W[/System.err]()( 4107): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewClient$4.success(InAppWebViewClient.java:510)
W[/System.err]()( 4107): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:239)
W[/System.err]()( 4107): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:376)
W[/System.err]()( 4107): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:993)
W[/System.err]()( 4107): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W[/System.err]()( 4107): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W[/System.err]()( 4107): 	at android.os.Looper.loop(Looper.java:183)
W[/System.err]()( 4107): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W[/System.err]()( 4107): 	at java.lang.reflect.Method.invoke(Native Method)
W[/System.err]()( 4107): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W[/System.err]()( 4107): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
The path (variable certPath) is: /data/user/0/com.example.test/app_flutter/cert/EXAMPLE00004.p12

I don't understand why the file path gets this `flutter_assets/` as a prefix? Is it even possible to load the cert from the local storage?

**Comment by akioyamamoto1977** [comment]
Faced to the same issue on Android and made a PR.
https://github.com/pichillilorenzo/flutter_inappwebview/pull/1241

**Comment by pichillilorenzo** [comment]
Merged now
