### ISSUE TITLE
Unable to download files - onDownloadStart callback does not give contentDisposition and contentLength in callback

### ISSUE THREAD

**Issue by ashank96** [pichillilorenzo/flutter_inappwebview#1087]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.10      |
| Plugin version       |      5.3.2     |

Device information: Samsung Galaxy M31

## Description

download file from url 

**Current behavior:** 
Not able to download file from given url as onDownloadStart returns only post url, but not contentDisposition and contentLength `onDownloadStart: (controller, url)`

Whereas in android native implementation you get all the required data in callback : 
` webview.setDownloadListener { url, userAgent, contentDisposition, mimetype, contentLength -> }`

**Comment by Aadesh2003** [comment]
@ashank96 we are trying to download files with onDownloadStartRequest but that not working. maybe i can't find file where actually it's downloaded so can you let me know with this function where file will store and can you share your code for download files from webView ?
