### ISSUE TITLE
Sometime webview make app crashed.

### ISSUE THREAD

**Issue by FiShelly** [pichillilorenzo/flutter_inappwebview#1090]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.10.2         |
| Plugin version       |        5.3.2       |
| Android version      |      10         |
| iOS version          |         -      |
| Xcode version        |       -        |

Device information: HUAWEI MATE 30 Pro

## Description

**Expected behavior:** 

Normal use.

**Current behavior:** 

Sometime will crashed.

## Steps to reproduce

The code like this. (Ps: target url use websocket connection)
```dart
InAppWebView(
              onReceivedServerTrustAuthRequest: (controller, challenge) async {
                return ServerTrustAuthResponse(
                    action: ServerTrustAuthResponseAction.PROCEED);
              },
              initialUrlRequest:
                  URLRequest(url: Uri.parse(webviewMeta.webviewUrl)),
              initialOptions: InAppWebViewGroupOptions(
                  crossPlatform: InAppWebViewOptions(
                      useShouldOverrideUrlLoading: true,
                      mediaPlaybackRequiresUserGesture: false,
                      userAgent: Platform.isIOS
                          ? Constant.APP_WEBVIEW_IOS_USERAGEN
                          : Constant.APP_WEBVIEW_ANDROID_USERAGEN),
                  android: AndroidInAppWebViewOptions(
                      useHybridComposition: true,
                      mixedContentMode:
                          AndroidMixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW),
                  ios: IOSInAppWebViewOptions(
                    allowsBackForwardNavigationGestures: true,
                    allowsInlineMediaPlayback: true,
                  )),
            ));
```

## Stacktrace/Logcat   
[bug3.log](https://github.com/pichillilorenzo/flutter_inappwebview/files/8128950/bug3.log)

**Comment by Super-Bin** [comment]
same

**Comment by 562937459** [comment]
same

**Comment by huangsir0** [comment]
any update? the same
