### ISSUE TITLE
Flash Webview page when jump to a flutter page from the webview page

### ISSUE THREAD

**Issue by debbiefu** [pichillilorenzo/flutter_inappwebview#1098]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    2.8.0           |
| Plugin version       |       5.3.2        |
| Android version      |      Android 11         |
| iOS version          |      N/A         |
| Xcode version        |     N/A          |

Device information: 
Oppo, XiaoMi, Huawei, basically all the Android test devices we have.

## Steps to reproduce
1. Open a fullscreen webview page A
2. Jump to a normal flutter page B

After navigate to the page B, it will quickly flash the content of page A, if you not see this at first try, just repeat the steps several times.

**Comment by ZhangZhiH** [comment]
I also have this problem when I open the WebView and go back to the previous page, there will be a flash screen. Is there a good solution to access

**Comment by meg4cyberc4t** [comment]
I'm catching the same bug now, only on android (everything is fine with ios) and the value of useHybridComposition is set to true.

And I believe that simply shortening the transition time between pages is a bad decision.

Are there any other options?

**Comment by meg4cyberc4t** [comment]
Looks the same: https://github.com/flutter/flutter/issues/95545
