### ISSUE TITLE
Keyboard Stopped working on Samsung S20 android 11 in flutter InAppWebViewPage

### ISSUE THREAD

**Issue by Nooshey** [pichillilorenzo/flutter_inappwebview#1099]
environment:
sdk: ">=2.2.0 <3.0.0"

dependencies:
flutter:
sdk: flutter

cupertino_icons: ^1.0.2
http: ^0.13.1
provider: ^5.0.0
toast: ^0.1.5
shared_preferences: ^2.0.5
hidden_drawer_menu:
path: ./hidden_drawer_menu-1.1.2
connectivity:
get_it:
back_button_interceptor: ^5.0.0
flutter_inappwebview: ^5.3.2
add_2_calendar: ^2.0.2
image_picker: ^0.7.4
image_cropper: ^1.4.0
cached_network_image: ^3.0.0
package_info: ^0.4.0+16
webview_flutter: ^3.0.1

dev_dependencies:
flutter_test:
sdk: flutter

**Comment by Nooshey** [comment]
I/IMM_LC ( 5934): ssi() - flag : 0 view : com.example.chelseamobileflutter reason = SHOW_SOFT_INPUT
I/IMM_LC ( 5934): ssi() view is not EditText
V/InputMethodManager( 5934): b/117267690: Display ID mismatch found. ViewRootImpl displayId=68 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
V/InputMethodManager( 5934): java.lang.Throwable
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:610)
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1721)
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1703)
V/InputMethodManager( 5934): at nJ.c(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:3)
V/InputMethodManager( 5934): at org.chromium.content.browser.input.ImeAdapterImpl.x(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:22)
V/InputMethodManager( 5934): at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:32)
V/InputMethodManager( 5934): at android.os.MessageQueue.nativePollOnce(Native Method)
V/InputMethodManager( 5934): at android.os.MessageQueue.next(MessageQueue.java:335)
V/InputMethodManager( 5934): at android.os.Looper.loopOnce(Looper.java:186)
V/InputMethodManager( 5934): at android.os.Looper.loop(Looper.java:313)
V/InputMethodManager( 5934): at android.app.ActivityThread.main(ActivityThread.java:8641)
V/InputMethodManager( 5934): at java.lang.reflect.Method.invoke(Native Method)
V/InputMethodManager( 5934): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
V/InputMethodManager( 5934): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
I/IMM_LC ( 5934): ssi() - flag : 0 view : com.example.chelseamobileflutter reason = SHOW_SOFT_INPUT
I/IMM_LC ( 5934): ssi() view is not EditText
I/IMM_LC ( 5934): ssi() - cancel : servedView != view : 0 view : com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{4829433 VFEDHVCL. .F...... 0,0-1080,2035}
I/ViewRootImpl@dc26350[PopupWindow:94f354d]( 5934): dispatchDetachedFromWindow
D/InputTransport( 5934): Input channel destroyed: 'd4df33e', fd=184
I/ViewRootImpl@7b28a18[MainActivity]( 5934): ViewPostIme pointer 0
I/ViewRootImpl@7b28a18[MainActivity]( 5934): ViewPostIme pointer 1
I/IMM_LC ( 5934): ssi() - flag : 0 view : com.example.chelseamobileflutter reason = SHOW_SOFT_INPUT
I/IMM_LC ( 5934): ssi() view is not EditText
V/InputMethodManager( 5934): b/117267690: Display ID mismatch found. ViewRootImpl displayId=68 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
V/InputMethodManager( 5934): java.lang.Throwable
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:610)
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1721)
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1703)
V/InputMethodManager( 5934): at nJ.c(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:3)
V/InputMethodManager( 5934): at org.chromium.content.browser.input.ImeAdapterImpl.x(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:22)
V/InputMethodManager( 5934): at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:32)
V/InputMethodManager( 5934): at android.os.MessageQueue.nativePollOnce(Native Method)
V/InputMethodManager( 5934): at android.os.MessageQueue.next(MessageQueue.java:335)
V/InputMethodManager( 5934): at android.os.Looper.loopOnce(Looper.java:186)
V/InputMethodManager( 5934): at android.os.Looper.loop(Looper.java:313)
V/InputMethodManager( 5934): at android.app.ActivityThread.main(ActivityThread.java:8641)
V/InputMethodManager( 5934): at java.lang.reflect.Method.invoke(Native Method)
V/InputMethodManager( 5934): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
V/InputMethodManager( 5934): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
I/IMM_LC ( 5934): ssi() - flag : 0 view : com.example.chelseamobileflutter reason = SHOW_SOFT_INPUT
I/IMM_LC ( 5934): ssi() view is not EditText
I/IMM_LC ( 5934): ssi() - cancel : servedView != view : 0 view : com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{4829433 VFEDHVCL. .F...... 0,0-1080,2035}
I/ViewRootImpl@7b28a18[MainActivity]( 5934): ViewPostIme pointer 0
I/ViewRootImpl@7b28a18[MainActivity]( 5934): ViewPostIme pointer 1
I/IMM_LC ( 5934): ssi() - flag : 0 view : com.example.chelseamobileflutter reason = SHOW_SOFT_INPUT
I/IMM_LC ( 5934): ssi() view is not EditText
V/InputMethodManager( 5934): b/117267690: Display ID mismatch found. ViewRootImpl displayId=68 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
V/InputMethodManager( 5934): java.lang.Throwable
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:610)
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1721)
V/InputMethodManager( 5934): at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1703)
V/InputMethodManager( 5934): at nJ.c(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:3)
V/InputMethodManager( 5934): at org.chromium.content.browser.input.ImeAdapterImpl.x(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:22)
V/InputMethodManager( 5934): at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.aab-stable-475810134:32)
V/InputMethodManager( 5934): at android.os.MessageQueue.nativePollOnce(Native Method)
V/InputMethodManager( 5934): at android.os.MessageQueue.next(MessageQueue.java:335)
V/InputMethodManager( 5934): at android.os.Looper.loopOnce(Looper.java:186)
V/InputMethodManager( 5934): at android.os.Looper.loop(Looper.java:313)
V/InputMethodManager( 5934): at android.app.ActivityThread.main(ActivityThread.java:8641)
V/InputMethodManager( 5934): at java.lang.reflect.Method.invoke(Native Method)
V/InputMethodManager( 5934): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
V/InputMethodManager( 5934): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
I/IMM_LC ( 5934): ssi() - flag : 0 view : com.example.chelseamobileflutter reason = SHOW_SOFT_INPUT
I/IMM_LC ( 5934): ssi() view is not EditText
I/IMM_LC ( 5934): ssi() - cancel : servedView != view : 0 view : com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{4829433 VFEDHVCL. .F...... 0,0-1080,2035}

**Comment by EhabSalah** [comment]
#1083 Duplicate
