### ISSUE TITLE
iOS: Access HTTP  Response Headers

### ISSUE THREAD

**Issue by lauritzh** [pichillilorenzo/flutter_inappwebview#1100]
## Environment

**Flutter version: 2.10.2** 
**Plugin version: 5.3.2**  
**iOS version: 15.2**

## Description

**What you'd like to happen:** 
I would like to have the possibility to access all HTTP *response* headers on iOS.

I am aware that it is possible to access the *request* headers using `useShouldOverrideUrlLoading`, but did not find any possibility to access the corresponding *response* headers.

___

If there is a request like this:
```http
GET /lauritz.html HTTP/1.1
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A403 Safari/602.1
Host: lauritz-holtmann.de
```

And a response like this:
```http
HTTP/2 200 OK
Date: Sun, 20 Feb 2022 21:34:30 GMT
Content-Type: text/html; charset=UTF-8
```

I would like to access all header fields of request and response.

Thank you very much for your feedback in advance! :)

**Comment by limsocheat** [comment]
I have the same issue, did you find the solution request http:// connection

**Comment by lauritzh** [comment]
No, I did not find a solution, yet.

[This issue](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1133) was opened a week ago and would also benefit from a solution here, I think :)

**Comment by AfriwanAhda** [comment]
You can add exceptions for specific domains that still use HTTP in your Info.plist:

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>yourdomain.com</key>
        <dict>
            <key>NSIncludesSubdomains</key>
            <true/>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSExceptionRequiresForwardSecrecy</key>
            <true/>
            <key>NSExceptionMinimumTLSVersion</key>
            <string>TLSv1.2</string>
            <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
            <false/>
            <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
            <true/>
            <key>NSThirdPartyExceptionMinimumTLSVersion</key>
            <string>TLSv1.2</string>
            <key>NSRequiresCertificateTransparency</key>
            <false/>
        </dict>
    </dict>
</dict>
```
