### ISSUE TITLE
Google map is not loading 

### ISSUE THREAD

**Issue by fixail** [pichillilorenzo/flutter_inappwebview#1108]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.10.3         |
| Plugin version       |      ^5.3.2         |
| Android version      |      12         |
| iOS version          |        15.2       |
| Xcode version        |        13.2.1       |

## Stacktrace/Logcat  
Web app is created with vue.js and I am getting a console message while map component loading in flutter app. 
>{message: InvalidValueError: setCenter: not a LatLng or LatLngLiteral with finite coordinates: in property lat: not a number, messageLevel: 3}

>Android Manifest permission: 
`
    <uses-permission android:name="android.permission.INTERNET"/>`
    `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`
   ` <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>`
    `<uses-permission android:name="android.hardware.location.gps"/> `

also added ` 
                  androidOnGeolocationPermissionsShowPrompt:
                      (InAppWebViewController controller, String origin) async {
                    return GeolocationPermissionShowPromptResponse(
                        origin: origin,
                        allow: true,
                        retain: true
                    );
                  }, ` into inAppWebView Widget.

**Comment by JulyWitch** [comment]
Same problem here

**Comment by alexeenko-frontend** [comment]
> Same problem here, Actually For me, Google map is loading but it cannot detect location

Do you also load the map on iOS? My app is crashing(

**Comment by zhuwei** [comment]
Same problem here, Actually For me, Google map is loading but it cannot detect location

**Comment by softplace-io** [comment]
Using OpenStreetView and I can't get my location...

**Comment by reasje** [comment]
I was getting behavior on Android only, The reason is that on Android to get location of user you need to do one more step after getting the permission from the user, And that is to ask the user to start the location service.
To use this functionality, I request to enable this service before user using the webview.
Note: Call this service If you have the location permission.
```
  Future<bool> checkLocationService() async {
    lc.Location location = lc.Location();

    bool _serviceEnabled;

    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
    }
    return _serviceEnabled;
  }
```
Actually I was expecting the webview to notify when ever there is such requests but looks like even the website is not aware of that, So I was unable to detect such request.
