### ISSUE TITLE
how to get the screenshot of the whole web page?how to get the long graph?

### ISSUE THREAD

**Issue by wl1395182472** [pichillilorenzo/flutter_inappwebview#1110]
how to get the screenshot of the whole web page?
how to get the long graph?

**Comment by guotao** [comment]
+1

**Comment by wl1395182472** [comment]
> +1

you can get it from native channel by modify plugin

**Comment by wl1395182472** [comment]
> +1

you can get pdf data from webview on iOS native and android native.it provides functions on these.
