### ISSUE TITLE
Google Sign In disallowed user agent in InAppWebView

### ISSUE THREAD

**Issue by jiayih1212** [pichillilorenzo/flutter_inappwebview#1112]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    2.5.3       |
| Plugin version       |   ^5.3.2     |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
The google login is being prohibited in InAppWebView plugin, it keep promoptiing Error: 403: disallowed_useragent. I have tried to add the user agent field "random", "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Mobile Safari/537.36"

**Expected behavior:** 
Proceed with google login with no problem with InAppWebView plugin

**Current behavior:** 
Unable to proceed google login and showing Error 403: disallowed user agent

## Steps to reproduce
Use google login in InAppWebView

InAppWebView(
          initialUrlRequest:widget.initialUrlRequest,
          shouldOverrideUrlLoading: widget.shouldOverrideUrlLoading,
          initialOptions: InAppWebViewGroupOptions(
            crossPlatform: InAppWebViewOptions(
              userAgent: 'random'
            ),
          ),
          onLoadStart: (InAppWebViewController controller, Uri? url) async{
            if(widget.onLoadStart != null) {
              widget.onLoadStart!.call(controller, url);
            }
          },
        ),

## Images   
![image](https://user-images.githubusercontent.com/56615370/157356151-160822ad-ff5e-45a9-b8ce-3e4c1a553016.png)

**Comment by mostafiz9900** [comment]
initialOptions: InAppWebViewGroupOptions(
                    crossPlatform: InAppWebViewOptions(
                  // debuggingEnabled: true,
                  userAgent: 'random',
                  javaScriptEnabled: true,
                  useShouldOverrideUrlLoading: true,
                  useOnLoadResource: true,
                  cacheEnabled: true,
                )),

**Comment by pichillilorenzo** [comment]
I just tested Google Sign In with the latest version `5.4.3+4` on Android Emulator API Level 31 and a real device and I can login without any problem.
I didn't set a custom user agent, just using the default one.

This is the code I used:
```dart
import 'dart:async';
import 'dart:developer';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (defaultTargetPlatform == TargetPlatform.android) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(kDebugMode);
  }

  runApp(const MaterialApp(
      home: MyApp()
  ));
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController? webViewController;
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text("InAppWebView TEST")),
        body: SafeArea(
            child: Column(children: <Widget>[
              Expanded(
                child: Stack(
                  children: [
                    InAppWebView(
                      key: webViewKey,
                      initialUrlRequest: URLRequest(
                          url: Uri.parse('https://accounts.google.com/servicelogin')),
                      initialOptions: options,
                      onWebViewCreated: (controller) {
                        webViewController = controller;
                      },
                      onLoadStart: (controller, url) {
                        log("onLoadStart $url");
                      },
                      onLoadStop: (controller, url) {
                        log("onLoadStop $url");
                      },
                    ),
                  ],
                ),
              ),
            ]))
    );
  }
}
```

**Comment by juskek** [comment]
I was using `InAppBrowser` when I ran into the problem

**Comment by vorte** [comment]
I got the same error but fixed it by setting the user-agent as suggested by @mostafiz9900. 👍 

Maybe InAppWebview should always set a default user-agent insted of setting it to empty string?

**Comment by VocsyJay** [comment]
I am Using 
flutter_inappwebview: ^5.7.2+3
flutter sdk: 3.10.5

Any of the above solutions didn't work 
I am got stuck

**Comment by Logoutbye** [comment]
i have been around this issue got many orders cancelled please provide solutions for this (facebook and google both doesnot work)

**Comment by PUAJINGYI** [comment]
I faced the same issue here. I had tried the solution above, but both cannot for me

 InAppWebView(
        initialUrlRequest: URLRequest(url: Uri.parse(uri.toString())),
        initialOptions:
        InAppWebViewGroupOptions(
            crossPlatform: InAppWebViewOptions(
// debuggingEnabled: true,
          userAgent: 'random',
          javaScriptEnabled: true,
          useShouldOverrideUrlLoading: true,
          useOnLoadResource: true,
          cacheEnabled: true,
        )),
        //     InAppWebViewGroupOptions(
        //         android: AndroidInAppWebViewOptions(
        //   useHybridComposition: true,
        // )),
        onWebViewCreated: (controller) {
          webViewController = controller;
        },
        onLoadStart: (controller, url) {
          // Handle page load start, if needed
        },
        onLoadStop: (controller, url) {
          // Handle page load stop, if needed
        },
        onProgressChanged: (controller, progress) {
          // Handle loading progress here, if needed
        },
        shouldOverrideUrlLoading: (controller, navigationAction) async {
          final url = navigationAction.request.url;

          if (url?.toString().startsWith('http://localhost') ?? false) {
            // Close the WebView when the redirect is detected
            Navigator.pop(context);
            return NavigationActionPolicy.CANCEL;
          }

          return NavigationActionPolicy.ALLOW;
        },
      );
      
flutter_inappwebview: ^5.7.2+3
flutter SDK: '>=2.19.4 <3.0.0'
      
any other suggestion?

**Comment by Mr-Programmar** [comment]
I just Fixed this issue, very easy to fix it honestly! please give me a like if your issue is resolved.
I am using "flutter_inappwebview: ^5.7.2+3" this package.
just add this inside your userAgent and   applicationNameForUserAgent properties.


(1)userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
(2)applicationNameForUserAgent: "your app name",
![Screenshot_1](https://github.com/pichillilorenzo/flutter_inappwebview/assets/105446618/ec659b9e-b022-41f3-8b60-78abf5d30e4f)
![Screenshot_2](https://github.com/pichillilorenzo/flutter_inappwebview/assets/105446618/8b75968f-249d-427e-8cec-57ad469c978e)

**Comment by Logoutbye** [comment]
hello there brother hope you are doing well i want to ask i have tried but
it could not sorted it out can you please give me any example project in
working condition that would be great help thanks in advance

**Comment by MostafaRamadan1** [comment]
Any updates, nothing works for the solution above for version ^6.0.0-beta.31

**Comment by pichillilorenzo** [comment]
The problem is exactly about the default user agent of the WebView, so it is the right solution.
It depends on the server and how they treat WebView default user-agent.
There is no “official” API to allow Google sign-in or whatever, that’s simply how it works and doesn’t depend on the WebView itself.

**Comment by Sh0tlan** [comment]
String getUserAgent() {
  if (defaultTargetPlatform == TargetPlatform.iOS) {
    return 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36';
  } else if (defaultTargetPlatform == TargetPlatform.android) {
    return 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1';
  } else {
    return 'random';
  }
}
