### ISSUE TITLE
Camera does not work with Android below 9. 

### ISSUE THREAD

**Issue by Franchute13** [pichillilorenzo/flutter_inappwebview#1116]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.8.1       |
| Plugin version       |        5.3.2       |
| Android version      |      8         |
| iOS version          |               |
| Xcode version        |               |

Device information: Emulator

## Description
When trying to use the camera in a webview, using Android less than Android 9, the camera does not work.
The following url is used as an example:
https://www.kirupa.com/html5/accessing_your_webcam_in_html5.htm 

**Expected behavior:** 
Enable the camera. 

**Current behavior:** 
The camera does not work.

## Steps to reproduce

Clone the flutter_inappwebview project
Edit in_app_webiew_example.screen.dart change line 126 of URLRequest(url: Uri.parse("https://github.com/flutter")),
by
URLRequest(url: Uri.parse("https://www.kirupa.com/html5/accessing_your_webcam_in_html5.htm")),

Edit main.dart and enable permission request.

Run the project.
When opening the project, it loads by default the page
https://www.kirupa.com/html5/accessing_your_webcam_in_html5.htm
Which, if you have the proper permissions, opens the camera.
This is not happening for versions lower than Android 9.

**Comment by eggyot** [comment]
same issue! do you have any solution?
