### ISSUE TITLE
loadUrl(urlRequest,iosAllowingReadAccessTo) not working with file loading in iOS

### ISSUE THREAD

**Issue by SaikiranReddy412** [pichillilorenzo/flutter_inappwebview#1122]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Files should be loaded in webview:** 

**loadUrl(urlRequest,iosAllowingReadAccessTo) not working with file loading in iOS** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by Saikiran24** [comment]
Yes I tried everything, but still it is not working

**Comment by sathya4code** [comment]
Hi,

Any solution for this issue?
