### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by hlovingness** [pichillilorenzo/flutter_inappwebview#1129]
![image](https://user-images.githubusercontent.com/16331459/159422905-ec226b5e-8cab-400e-9a9b-b7ca7951d6ee.png)

**Comment by pichillilorenzo** [comment]
Could you give me the full stack trace, please? It shouldn't be possible to have `source` as `null`.
