### ISSUE TITLE
Automatically paste text in website text field from android app

### ISSUE THREAD

**Issue by afzl-wtu** [pichillilorenzo/flutter_inappwebview#1134]
Is there anyway.. If I scan a QR code from my flutter app, When scan finishes it will automatically open WebView inside app and paste the text (obtained from QR Code or any string from app) in website's text field?

Basically I want a communication channel between flutter app and website inside WebView. I want to pass any string from flutter app to website text field.

**Comment by sandys** [comment]
@afzl-wtu did u find a solution to this ? im looking for the same.

**Comment by afzl-wtu** [comment]
> @afzl-wtu did u find a solution to this ? im looking for the same.

I gave up.

**Comment by pichillilorenzo** [comment]
This isn't hard to do. You simply load the website, wait for the `onLoadStop` event and execute javascript code with `InAppWebViewController.evaluateJavascript` method to set the input value with your text value.

For example:
```dart
onLoadStop: (controller, url) async {
  var qrTextValue = "TEXT_FROM_QR_CODE";
  
  // for example, you can use css selector to get the HTML input reference
  await controller.evaluateJavascript(source: """
  const input = document.querySelector('#myInput');
  input.value = "${qrTextValue}";
  """);
},
```
