### ISSUE TITLE
Opening 'file://' URLs

### ISSUE THREAD

**Issue by divan** [pichillilorenzo/flutter_inappwebview#114]
Hi,

first of all, thanks for the fantastic plugin – it's truly the best web browser Flutter plugin out there!

So I need to open both "normal" urls (http://) and local files (file://). Currently I'm testing only on iOS and the problem I see is that opening local file via file:// URL fails on the device (but works in a simulator). Error is `The operation couldn't be completed. Operation not permitted.`

I've [read in docs](https://developer.apple.com/documentation/webkit/wkwebview) that for opening local files we should use [loadHTMLString](https://developer.apple.com/documentation/webkit/wkwebview/1415004-loadhtmlstring):

>  Use the loadHTMLString(_:baseURL:) method to begin loading local HTML files or the load(_:) method to begin loading web content.

This, however, requires a lot of hassle with opening and reading file from FS, figuring out correct MIME type (I need just PDFs and Images, but everything that webkit supports should work ideally) and so on.

I initially tried `initialFile` option, until read that it's actually `initialAsset` (rename, perhapse?). So maybe it's worth implement `initialFile` for local files (not only assets)?

Or maybe there is a better way to load local resources? (I don't have much experience with mobile dev, so may be missing some obvious things)

Thanks in advance!

**Comment by Mar-er** [comment]
You can try to use "jaguar" and "jaguar_flutter_asset"  to open a local service load assets resource

**Comment by micsan13br** [comment]
I can confirm this. I am able to load local files in Android (downloaded from firebase to the application directory on the device) using initialUrl, but the same does not work on iOS.
Error: (1) The operation couldn't be completed. Operation not permitted.

**Comment by raveltan** [comment]
@micsan13br hello, can you show me how to get this working on android? im trying to do this but, it always display the file not found error. thanks

**Comment by shodafl** [comment]
@micsan13br Hi! how do you import local files on android?

**Comment by micsan13br** [comment]
@shodafl my reply to this issue goes back to 2019. I don't know if this still applies to the latest version or what was this about at all.
