### ISSUE TITLE
OrderedSet-Swift.h

### ISSUE THREAD

**Issue by kttary** [pichillilorenzo/flutter_inappwebview#1141]
Today i cant build my project with anappwebview with following error:

> /Users/macos/Library/Developer/Xcode/DerivedData/Runner-fsjsfxksdjramohjctwfeextbmqj/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OrderedSet.build/module.modulemap:9:12: Header 'OrderedSet-Swift.h' not found

any clue?

**Comment by ekansh-code** [comment]
Same Issue when I try to run with X code

**Comment by WallyHale** [comment]
I'm also having this problem running to phone in Xcode. I can run from Flutter without a problem.

Clean, flutter build ios works fine. Open in Xcode and run to device it fails
/Runner-dlznetgjwnpqmzfbuajunhceudly/Build/Intermediates.noindex/Pods.build/Release-iphoneos/OrderedSet.build/module.modulemap:9:12: error: header 'OrderedSet-Swift.h' not found
    header "OrderedSet-Swift.h"
           ^
<unknown>:0: error: could not build Objective-C module 'OrderedSet'

**Comment by WallyHale** [comment]
> I'm also having this problem running to phone in Xcode. I can run from Flutter without a problem.
> 
> Clean, flutter build ios works fine. Open in Xcode and run to device it fails /Runner-dlznetgjwnpqmzfbuajunhceudly/Build/Intermediates.noindex/Pods.build/Release-iphoneos/OrderedSet.build/module.modulemap:9:12: error: header 'OrderedSet-Swift.h' not found header "OrderedSet-Swift.h" ^ :0: error: could not build Objective-C module 'OrderedSet'

After a few hours .. I've got it building for me, hopefully it helps you as well. 

In my case, opening Pods in the Project Navigator and selecting the OrderedSet target, I upped it from iOS 8 to 9 and it started working.
