### ISSUE TITLE
Identify clicks on webview pages

### ISSUE THREAD

**Issue by rodrigonepomuceno** [pichillilorenzo/flutter_inappwebview#1143]
## Environment

**Flutter version:** Flutter 2.10.4 • channel stable 
**Plugin version:**  flutter_inappwebview: ^5.3.2

## Description

I have a webview that loads a sequence of internal pages that have been created. Within these pages I need to get certain clicks to perform certain actions in Flutter and not on the page.

Example
I have this page made with React, I need to know that the user clicked the back button.

```function App() {
  return (
    <div className="App">
      <button name="button" type="button" onClick={() =>window.history.back()}>
        Voltar
      </button>
      <p>Page Test</p>
    </div>
  );
}```

**What you'd like to happen:** 
Identify in flutter that the button was clicked

**Comment by Gabanelli** [comment]
You can create a js file that adds an event listener on your button and, when is triggered, calls flutter method by Javascript Handler, see [Javascript Communication](https://inappwebview.dev/docs/javascript/communication/#JavaScript-Handlers)
