### ISSUE TITLE
WebContentsDelegate::CheckMediaAccessPermission: Not supported.

### ISSUE THREAD

**Issue by stefanicarol** [pichillilorenzo/flutter_inappwebview#1145]
que estou migrando ele pra nullsaf, dentro dele tem uma webview que chama um site de aula virtual... antes funcionava perfeito mas agora não aparece mais o vídeo e áudio falham.
Erro: 
`E/chromium(10923): [ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
`
Estou usando o pub.dev : flutter_inappwebview | Flutter Package
Eu tentei fazer ele mandar p/ navegador e funcionou, só que precisa ser pela webv pq eu seto cookie, de login, o mesmo login que app, pra não precisar logar duas vezes (É requisito).

Permissões no AndroidManifest.xml:
```
   <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" /> 
```

Dentro da página quando chamo pack>:
      
```
 androidOnPermissionRequest: (InAppWebViewController controller,
                String origin, List<String> resources) async {
              return PermissionRequestResponse(
                  resources: resources,
                  action: PermissionRequestResponseAction.GRANT);
            }
```

main.dart
```
  WidgetsFlutterBinding.ensureInitialized();  
  await Permission.camera.request();
  await Permission.microphone.request();
```

Tudo que tem na internet relacionado já pesquisei, e já fiz, eu já não sei mais, alguém passou por algo semelhante agora não sei se é por aqui que te chamo, ou viu alguém aqui da comunidade com esse problema?
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version   |
| -------------------- | --------- |
| Flutter version       |  2.10.4    |
| Plugin version       |  5.3.2      |
| Android version    |  8.1.0      |

**Comment by luqmantuke** [comment]
To anyone who is still struggling. it's because webview doesn't support <file> attribute. So use this package [Flutter WebView Pro](https://pub.dev/packages/flutter_webview_pro)

**Comment by alex27riva** [comment]
Hi everyone, I have the same issue.

**Comment by marcchiu** [comment]
> To anyone who is still struggling. it's because webview doesn't support file attribute. So use this package [Flutter WebView Pro](https://pub.dev/packages/flutter_webview_pro)

**Your recommended package also have this very same error.**

**Comment by stefanicarol** [comment]
Também estou aguardando alguma atualização.

**Comment by lugael** [comment]
Any news about this issue?

**Comment by vantutrieu97** [comment]
I'm still struggling

**Comment by vikivyas** [comment]
> To anyone who is still struggling. it's because webview doesn't support file attribute. So use this package [Flutter WebView Pro](https://pub.dev/packages/flutter_webview_pro)

Flutter WebView Pro does not work...

**Comment by moneosi** [comment]
@stefanicarol conseguiu resolver, estou com a mesma situação aqui
