### ISSUE TITLE
How do I get the open state of the InAppWebView

### ISSUE THREAD

**Issue by au333333** [pichillilorenzo/flutter_inappwebview#1154]
InAppWebView in the flutter_inappwebview from My App，I want to get the InAppWebView is open state or close state? How can I do?

flutter_inappwebview之InAppWebView         当前是已经开启还是关闭的状态怎么获取,我该怎么做？

**Comment by pichillilorenzo** [comment]
What do you mean with "open" and "close" state?
`InAppWebView` is a flutter widget, so it is "opened" when you add it to your flutter widgets tree and it is "closed" when it has been disposed from the flutter widgets tree like any other flutter widget.

**Comment by au333333** [comment]
InAppBrowser().isOpened();

就像以上那样，有没有类似的api
Just like the above, there is no similar API（InAppWebView or InAppWebViewController webViewController）

**Comment by au333333** [comment]
> “打开”和“关闭”状态是什么意思？ `InAppWebView`是一个颤振小部件，所以当你将它添加到你的颤动小部件树时它是“打开的”，当它像任何其他颤动小部件一样从颤动小部件树中释放时它是“关闭”的。

InAppBrowser().isOpened();

就像以上那样，有没有类似的api
Just like the above, there is no similar API（InAppWebView or InAppWebViewController webViewController）

**Comment by au333333** [comment]
> What do you mean with "open" and "close" state? `InAppWebView` is a flutter widget, so it is "opened" when you add it to your flutter widgets tree and it is "closed" when it has been disposed from the flutter widgets tree like any other flutter widget.

InAppBrowser().isOpened();

就像以上那样，有没有类似的api
Just like the above, there is no similar API（InAppWebView or InAppWebViewController webViewController）

**Comment by pichillilorenzo** [comment]
`InAppBrowser` is a native view on top of all Flutter widgets, instead `InAppWebView` is a Flutter widget.
So, if you added `InAppWebView` in the widget tree, then you can think it is in an "open" state, instead if you remove it from the widget tree, then you can think it is in a "close" state.

For example, in your widget:
```dart
  var closed = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("InAppWebView")),
        drawer: myDrawer(context: context),
        body: SafeArea(
            child: Column(children: <Widget>[
              closed ?
                  Container(child: Text('Empty'),) :
                  Expanded(
                    child: Stack(
                      children: [
                        InAppWebView(
                          initialUrlRequest: URLRequest(url: Uri.parse("https://flutter.dev")),
                        ),
                      ],
                    ),
              ),
            ])));
  }
  
  void closeWebView() {
    setState(() {
      this.closed = true;
    });
  }
```

**Comment by au333333** [comment]
> `InAppBrowser` is a native view on top of all Flutter widgets, instead `InAppWebView` is a Flutter widget. So, if you added `InAppWebView` in the widget tree, then you can think it is in an "open" state, instead if you remove it from the widget tree, then you can think it is in a "close" state.
> 
> For example, in your widget:
> 
> ```dart
>   var closed = false;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>         appBar: AppBar(title: Text("InAppWebView")),
>         drawer: myDrawer(context: context),
>         body: SafeArea(
>             child: Column(children: <Widget>[
>               closed ?
>                   Container(child: Text('Empty'),) :
>                   Expanded(
>                     child: Stack(
>                       children: [
>                         InAppWebView(
>                           initialUrlRequest: URLRequest(url: Uri.parse("https://flutter.dev")),
>                         ),
>                       ],
>                     ),
>               ),
>             ])));
>   }
>   
>   void closeWebView() {
>     setState(() {
>       this.closed = true;
>     });
>   }
> ```

Thanks
your mean，I can use closeWebView in the dispose function？？？
I don't find the api,I use the global variable in my app,I have implemented this feature

**Comment by pichillilorenzo** [comment]
No, my code is just an example. You need to implement whatever logic by yourself. `closeWebView` is just an example!
You don't need to close manually the webview, because the `InAppWebView` widget is automatically disposed when the parent widget is disposed!

**Comment by au333333** [comment]
> 可以在dispose函数中使用closeWebView？？？



> No, my code is just an example. You need to implement whatever logic by yourself. `closeWebView` is just an example! You don't need to close manually the webview, because the `InAppWebView` widget is automatically disposed when the parent widget is disposed!

thank you!💐(*^▽^*)
