### ISSUE TITLE
[iOS] shouldOverrideUrlLoading being called before LoadStart() and redirect URL same with initialUrlRequest.

### ISSUE THREAD

**Issue by Doflatango** [pichillilorenzo/flutter_inappwebview#1157]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.10.3      |
| Plugin version       |      5.4.3         |
| iOS version          |      15.2         |
| Xcode version        |       13.2.1        |

```
initialUrlRequest = https://www.cnbeta.com/articles/tech/1263221.htm
```

## Stacktrace/Logcat
```
// while on Android there is only an onLoadStart() event.
flutter: [DEBUG] shouldOverrideUrlLoading, isForMainFrame = true, redirectURL = https://www.cnbeta.com/articles/tech/1263221.htm
flutter: [DEBUG] onLoadStart, URL = https://www.cnbeta.com/articles/tech/1263221.htm
```

**Comment by pichillilorenzo** [comment]
I don't understand, where is the problem? 
I test the URL on both Android and iOS platforms and I can load the URL correctly.
The fact that the `shouldOverrideUrlLoading` event is being called before `onLoadStart` event is something related to the native platform itself.
When I get notified about an event from the native side, I call the event on the flutter side. That's it.

**Comment by Doflatango** [comment]
@pichillilorenzo Thank you for your reply.
This behavior seems is introduced in recently updates, so it should be consider as an expected behavior, right?

**Comment by pichillilorenzo** [comment]
The code related to these events hasn't changed.
As I said, these events are sent by the native platform itself.
So, if you receive the `shouldOverrideUrlLoading` event before the `onLoadStart` event, it means that the native platform is sending them in this order (WKWebView native class on iOS and WebView native class on Android).
The plugin simply propagates these events to the Flutter side when they arrive.
To conclude, just to be clear, this is something that is not decided by my plugin, but by the native WebView engine of the platform.
