### ISSUE TITLE
stripe payment not work in webview  iOS

### ISSUE THREAD

**Issue by alyabbasi93** [pichillilorenzo/flutter_inappwebview#1167]
Stripe payment not work in webview iOS is any solution for that let me know

**Comment by pichillilorenzo** [comment]
Please describe better your issue. Without any details, I cannot understand what could be the problem.
Check logs, console messages from javascript, etc...

**Comment by alyabbasi93** [comment]
like when I want to  submit stipe payment the payment card option stuck and work and also js.stripe.com also not show  any thing android its working

**Comment by alyabbasi93** [comment]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-29 at 00 59 07](https://user-images.githubusercontent.com/27091006/165854797-735f28ac-896b-43f5-aa80-6245d451a13f.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-29 at 00 59 04](https://user-images.githubusercontent.com/27091006/165854804-8c66f536-e8e1-4e20-972d-8650f8c5400a.png)

**Comment by pichillilorenzo** [comment]
Check for any error in the Safari console developer https://webkit.org/web-inspector/enabling-web-inspector/

**Comment by gianni-gulino-eleva** [comment]
Have you found a solution to the problem?
I have the same problem as well.

Thanks
