### ISSUE TITLE
Audio NOT playing in background when device is locked

### ISSUE THREAD

**Issue by pawangjain** [pichillilorenzo/flutter_inappwebview#1171]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.8.1              |
| Plugin version       | 5.3.2              |
| Android version      | 11               |
| iOS version          |               |
| Xcode version        |               |

Device information: [Motorola Moto G9 Plus](https://www.gsmarena.com/motorola_moto_g9_plus-10432.php)

## Description

In version ^4.0.0+4, the audio of a youtube video used to play in background when the device was locked. But in version ^5.3.2 the audio pauses when the device is locked. 

Is there any way we can enable background audio when the device is locked?

**Expected behavior:** 
Background audio of the Youtube video SHOULD continue to play when the device is locked.

**Current behavior:** 
Background audio of the Youtube video pauses when the device is locked.

**Comment by gauravparvadiya** [comment]
I am having the same issue. Any workaround?
