### ISSUE TITLE
iOS flutter_inappwebview/URLRequest.swift:13: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by kotran88** [pichillilorenzo/flutter_inappwebview#1173]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.10.5        |
| Plugin version       |       5.4.1+2        |
| Android version      |               |
| iOS version          |     11          |
| Xcode version        |      latest         |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

when app started, it cause error on Xcode or viscose' debug console 

flutter_inappwebview/URLRequest.swift:13: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2022-05-03 19:02:17.629025+0900 Runner[3860:371793] flutter_inappwebview/URLRequest.swift:13: Fatal error: Unexpectedly found nil while unwrapping an Optional value
(lldb) 

iOS > .symlinks> plugins > flutter_inappwebview > iOS > classes > Types > URLRequest.swift. 13 line is the problem . 

self.init(url: URL(string: url)!)

How can I solve this?

**Comment by kotran88** [comment]
removing ./pub-cache folder or flutter clean, pod clean not working at all
https://github.com/pichillilorenzo/flutter_inappwebview/issues/932

**Comment by pichillilorenzo** [comment]
Fixed with new release `5.4.3+6`. Now if you try to make an URL Request using `null` as URL, it will load `about:blank`.
