### ISSUE TITLE
Simply enabling `useShouldInterceptAjaxRequest` is breaking some functionality on websites

### ISSUE THREAD

**Issue by carman247** [pichillilorenzo/flutter_inappwebview#1175]
I'm not sure if I'm doing something wrong, or not doing something that I should be doing. However, when enabling `useShouldInterceptAjaxRequest` it is preventing videos from loading on https://www.10play.com.au.

It doesn't seem to break other requests, none that I've found anyway. 

If someone could double check this problem for me it would be great. I would love to know if it's possible to fix easily in the app.

P.S. you'll need to use a VPN to use the website.

**Comment by Manuito83** [comment]
I have the same experience (not with videos, but other elements).

I tried activating/deactivating it tactically in certain websites, but then I'm also running into [this issue](https://github.com/pichillilorenzo/flutter_inappwebview/issues/854).
