### ISSUE TITLE
When the video full screen is closed, the keyboard does not come up when inputting text fields.

### ISSUE THREAD

**Issue by Fixid-Fuzz** [pichillilorenzo/flutter_inappwebview#1176]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         stable, 2.10.5, on macOS 12.3.1      |
| Plugin version       |        ^5.4.3+7       |
| Android version      |      SDK version 32.1.0-rc1         |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
When the video full screen is closed, the keyboard does not come up when inputting text fields.

**Expected behavior:** 
keyboard show up

**Current behavior:** 
keyboard don't show up. 
If I go to the background and come back, it's fine.

## Steps to reproduce

1) i used borrow source
https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/example/lib/in_app_webiew_example.screen.dart

2) move to video site (ex: youtube)
and then video open by full screen.
and then exit.

3) input text field. 

## Stacktrace/Logcat   
Log when the keyboard does not appear after the video full screen is finished

![image](https://user-images.githubusercontent.com/99014005/167250152-082b1643-d577-449e-bf57-9fc89e681e7d.png)

**Comment by racyon** [comment]
try this...
InAppWebViewChromeClient {
...
@Override
  public void onHideCustomView() {
    Activity activity = getActivity();
    if (activity == null) {
      return;
    }

    View decorView = getRootView();
    if (decorView == null) {
      return;
    }
    ((FrameLayout) decorView).removeView(this.mCustomView);
    this.mCustomView = null;
    decorView.setSystemUiVisibility(this.mOriginalSystemUiVisibility);
    activity.setRequestedOrientation(this.mOriginalOrientation);
    this.mCustomViewCallback.onCustomViewHidden();
    this.mCustomViewCallback = null;
    activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
    Map<String, Object> obj = new HashMap<>();
    channel.invokeMethod("onExitFullscreen", obj);

    decorView.clearFocus();   // Added.
  }
...
}

**Comment by Jinxishihenian** [comment]
I had the same problem

**Comment by Jinxishihenian** [comment]
Here's how I'm doing it so far
```
  onExitFullscreen: (controller){
                      SystemChannels.textInput.invokeMethod<void>('TextInput.show');
                    },
```
In version 6.0.0
