### ISSUE TITLE
on IOS, specific url is not opened! 

### ISSUE THREAD

**Issue by kotran88** [pichillilorenzo/flutter_inappwebview#1177]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.10.5      |
| Plugin version       |          5.4.3+6     |
| Android version      |               |
| iOS version          |     11          |
| Xcode version        |          latest     |

Device information: 

## Description

**Expected behavior:** 

http://place.map.kakao.com/27402711

other link is okay. 

above link is not opened with error 
```

assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
[ProcessSuspension] 0x1180044e0 - ProcessAssertion: Failed to acquire RBS assertion 'WebProcess Background Assertion' for process with PID=12792, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
```

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by mycoalchen** [comment]
I'm getting the same error with Flutter 3.0.5 and plugin version 5.4.3+7, has anyone found a fix for this yet?

**Comment by minh-dai** [comment]
+1
