### ISSUE TITLE
[iOS] Sometimes I get LoadError -1004 Could not connect to the server.

### ISSUE THREAD

**Issue by amitrotner** [pichillilorenzo/flutter_inappwebview#1179]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.10.5          |
| Plugin version       |   5.4.3+7            |
| iOS version          |   15.4.1            |
| Xcode version        |   13.3.1            |

Device information: iPhone 11

## Description

**Current behavior:** 
I am using the plug in to create a server on http://localhost:8080/ , load my assets file on a server using `InAppLocalhostServer` and displaying the page using `InAppWebView`.
Sometimes I get the page as required but sometimes (very often but very randomly) I get a blank page with a this loading error: 
`error code: -1004 message: Could not connect to the server.`
When catching this error I'm reloading the page using `controller.reload()` but this doesn't help and I keep getting this error. 
When this happens, the webview is stuck in a loop (error -> rebuild -> error -> rebuild -> etc...) and only a complete widget rebuild can make the page to render again.

In addition this only happens in iOS (in some devices it happens much more excessively) and not in Android (with the same implementation of course).

**Expected behavior:** 
The page should be displayed every time and not only sometimes.

## Steps to reproduce

As this happens randomly I don't have steps to reproduce - just try to display the page and you will experience it quite often.

**Comment by mathewthe2** [comment]
I had a similar issue using [LocalAssetsServer](https://github.com/lesnitsky/local_assets_server) and InAppWebView.

I could reproduce the issue on profile build or testflight when I turn off the phone screen and reopen the app.

The issue seems to stem from[ the local server getting stopped when the app goes into the background](https://github.com/flutter/flutter/issues/67628). 

The solution was to add a [WidgetsBindingObserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html) mixin to the main app and listen to App state changes by overriding _didChangeAppLifecycleState_.

Finally, I stop the server on inactive state and start the server on resume state.

```dart
class _AppState extends State<App> with WidgetsBindingObserver {
  bool isLocalAssetsServerReady = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    setupProviders();
  }

  Future<void> setupProviders() async {
    localAssetsServerProvider = await LocalAssetsServerProvider.create();
    vocabularyListProvider = await VocabularyListProvider.create();
    setState(() {
      isLocalAssetsServerReady = true;
    });
  }

  Future<void> startLocalAssetsServer() async {
    await localAssetsServerProvider!.server!.serve();
    setState(() {
      isLocalAssetsServerReady = true;
    });
  }

  Future<void> stopLocalAssetsServer() async {
    await localAssetsServerProvider!.server!.stop();
    setState(() {
      isLocalAssetsServerReady = true;
    });
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    switch (state) {
      case AppLifecycleState.resumed:
        startLocalAssetsServer();
        break;
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
        stopLocalAssetsServer();
        break;
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}
```
