### ISSUE TITLE
setcookie ios failed

### ISSUE THREAD

**Issue by Hiram-Y** [pichillilorenzo/flutter_inappwebview#118]
```
 CookieManager.setCookie(http://m.test.com, "token", "h7dcc4islpbfigvpg25aqq7ru4",domain: 'm.test.com',expiresDate: time);

   CookieManager.setCookie(http://m.test.com, "phone", "111222333",domain: 'm.test.com',expiresDate: time);

   CookieManager.setCookie(http://m.test.com, "code", "223453",domain: 'm.test.com',expiresDate: time);
```

**Comment by Hiram-Y** [comment]
by 
```
 onLoadStop: (InAppWebViewController controller, String url) async {
             print(await controller.injectScriptCode("document.cookie"));
          },
```
`print Hm_lpvt_14d35254d0c1854c4be8cb1155be9fe8=1560851694; Hm_lvt_14d35254d0c1854c4be8cb1155be9fe8=1560850617,1560850626,1560851685,1560851694; token=mkunnarvgtbmf85vj304978v17`
my setcookie ios  is failed ， but android is ok。

**Comment by daryll-fourie** [comment]
Any update on this? I'm also getting this issue...

**Comment by nemoryoliver** [comment]
setCookie still doesn't seem to work for iOS. It successfully saves it to the CookieManager but doesn't actually work on the WebView

**Comment by pichillilorenzo** [comment]
@nemoryoliver @daryll-fourie @Hiram-Y Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.

A full example that I tried on both Android (API level `28`) and iOS (version `13.1`) platforms and it works for both:
```dart
import 'dart:async';

import 'package:flutter/material.dart';

import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: InAppWebViewPage()
    );
  }
}

class InAppWebViewPage extends StatefulWidget {
  @override
  _InAppWebViewPageState createState() => new _InAppWebViewPageState();
}

class _InAppWebViewPageState extends State<InAppWebViewPage> {
  InAppWebViewController webView;
  final CookieManager cookieManager = CookieManager.instance();

  @override
  void initState() {
    super.initState();

    var expiresDate = DateTime.parse("2019-09-30 00:00:00.000").millisecondsSinceEpoch;
    cookieManager.setCookie(url: "https://flutter.dev", name: "myToken", value: "wertygubnm5046rhndf", domain: ".flutter.dev", expiresDate: expiresDate);
    cookieManager.setCookie(url: "https://flutter.dev", name: "myCookie", value: "myValue", domain: ".flutter.dev", expiresDate: expiresDate);
    cookieManager.setCookie(url: "https://flutter.dev", name: "myCookie2", value: "myValue2");
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        appBar: AppBar(
            title: Text("InAppWebView")
        ),
        body: SafeArea(
            child: Column(children: <Widget>[
              Expanded(
                child: Container(
                  child: InAppWebView(
                    initialUrl: "https://flutter.dev",
                    initialHeaders: {},
                    initialOptions: InAppWebViewWidgetOptions(
                      inAppWebViewOptions: InAppWebViewOptions(
                        debuggingEnabled: true,
                      )
                    ),
                    onWebViewCreated: (InAppWebViewController controller) {
                      webView = controller;
                    },
                    onLoadStart: (InAppWebViewController controller, String url) {

                    },
                    onLoadStop: (InAppWebViewController controller, String url) async {
                      print(await controller.evaluateJavascript(source: "document.cookie"));
                    },
                  ),
                ),
              ),
              ButtonBar(
                alignment: MainAxisAlignment.center,
                children: <Widget>[
                  RaisedButton(
                    child: Icon(Icons.arrow_back),
                    onPressed: () {
                      if (webView != null) {
                        webView.goBack();
                      }
                    },
                  ),
                  RaisedButton(
                    child: Icon(Icons.arrow_forward),
                    onPressed: () {
                      if (webView != null) {
                        webView.goForward();
                      }
                    },
                  ),
                  RaisedButton(
                    child: Icon(Icons.refresh),
                    onPressed: () {
                      if (webView != null) {
                        webView.reload();
                      }
                    },
                  ),
                ],
              ),
            ]))
    );
  }
}
```
It prints all of my cookies:
```
myCookie=myValue; myToken=wertygubnm5046rhndf; myCookie2=myValue2; _ga=GA1.2.919201585.1575042727; _gid=GA1.2.2019611942.1575737332; _gat=1
```

**Comment by nemoryoliver** [comment]
> @nemoryoliver @daryll-fourie @Hiram-Y Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
> 
> A full example that I tried on both Android (API level `28`) and iOS (version `13.1`) platforms and it works for both:
> 
> ```dart
> import 'dart:async';
> 
> import 'package:flutter/material.dart';
> 
> import 'package:flutter_inappwebview/flutter_inappwebview.dart';
> 
> Future main() async {
>   runApp(new MyApp());
> }
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => new _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
> 
>   @override
>   void initState() {
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>         home: InAppWebViewPage()
>     );
>   }
> }
> 
> class InAppWebViewPage extends StatefulWidget {
>   @override
>   _InAppWebViewPageState createState() => new _InAppWebViewPageState();
> }
> 
> class _InAppWebViewPageState extends State<InAppWebViewPage> {
>   InAppWebViewController webView;
>   final CookieManager cookieManager = CookieManager.instance();
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     var expiresDate = DateTime.parse("2019-09-30 00:00:00.000").millisecondsSinceEpoch;
>     cookieManager.setCookie(url: "https://flutter.dev", name: "myToken", value: "wertygubnm5046rhndf", domain: ".flutter.dev", expiresDate: expiresDate);
>     cookieManager.setCookie(url: "https://flutter.dev", name: "myCookie", value: "myValue", domain: ".flutter.dev", expiresDate: expiresDate);
>     cookieManager.setCookie(url: "https://flutter.dev", name: "myCookie2", value: "myValue2");
>   }
> 
>   @override
>   Widget build(BuildContext context) {
> 
>     return Scaffold(
>         appBar: AppBar(
>             title: Text("InAppWebView")
>         ),
>         body: SafeArea(
>             child: Column(children: <Widget>[
>               Expanded(
>                 child: Container(
>                   child: InAppWebView(
>                     initialUrl: "https://flutter.dev",
>                     initialHeaders: {},
>                     initialOptions: InAppWebViewWidgetOptions(
>                       inAppWebViewOptions: InAppWebViewOptions(
>                         debuggingEnabled: true,
>                       )
>                     ),
>                     onWebViewCreated: (InAppWebViewController controller) {
>                       webView = controller;
>                     },
>                     onLoadStart: (InAppWebViewController controller, String url) {
> 
>                     },
>                     onLoadStop: (InAppWebViewController controller, String url) async {
>                       print(await controller.evaluateJavascript(source: "document.cookie"));
>                     },
>                   ),
>                 ),
>               ),
>               ButtonBar(
>                 alignment: MainAxisAlignment.center,
>                 children: <Widget>[
>                   RaisedButton(
>                     child: Icon(Icons.arrow_back),
>                     onPressed: () {
>                       if (webView != null) {
>                         webView.goBack();
>                       }
>                     },
>                   ),
>                   RaisedButton(
>                     child: Icon(Icons.arrow_forward),
>                     onPressed: () {
>                       if (webView != null) {
>                         webView.goForward();
>                       }
>                     },
>                   ),
>                   RaisedButton(
>                     child: Icon(Icons.refresh),
>                     onPressed: () {
>                       if (webView != null) {
>                         webView.reload();
>                       }
>                     },
>                   ),
>                 ],
>               ),
>             ]))
>     );
>   }
> }
> ```
> 
> It prints all of my cookies:
> 
> ```
> myCookie=myValue; myToken=wertygubnm5046rhndf; myCookie2=myValue2; _ga=GA1.2.919201585.1575042727; _gid=GA1.2.2019611942.1575737332; _gat=1
> ```

It also successfully sets and gets it from CookieManager. but it weirdly doesn't get passed in the actual webview's cookie. I think I tried printing the actual document.cookie using evaluate javascript.

**Comment by pichillilorenzo** [comment]
@nemoryoliver Can you share the code you tested and didn't work? Also, the device information and Xcode version, please? Thanks!

**Comment by wj1234** [comment]
url must be https

**Comment by Kimhak-Loem** [comment]
@nemoryoliver excuse me, did you able to let CookieManager work with the webview with iOS. I'm currently having the same issue. It successfully saves it to the CookieManager but not able to see in `controller.evaluateJavascript(source: "document.cookie")`

Any help would be appreciated,

**Comment by nemoryoliver** [comment]
> @nemoryoliver excuse me, did you able to let CookieManager work with the webview with iOS. I'm currently having the same issue with iOS. It successfully saves it to the CookieManager but not able to see in `controller.evaluateJavascript(source: "document.cookie")`
> 
> Any help would be appreciated,

sorry for the late response. what I did was used the https://pub.dev/packages/webview_flutter package plus the https://pub.dev/packages/webview_cookie_manager they work brilliant with cookies

**Comment by lugael** [comment]
Hi, any news on this issue? 
I performed some tests, on Android everything is fine, but on IOS when it's for an HTTPS URL don't set the cookie.

**Comment by lugael** [comment]
@pichillilorenzo Here's an example of IOS, test on an iPhone 13 IOS 16

`String url = https://homologacao-morador.apcontrole.com.br
String domain = apcontrole.com.br
String name = _onesignal-player-identifier
String value = UUidd


await _cookieManager
        .setCookie(
            url: Uri.parse(url),
            domain: domain,
            name: name,
            value: value,
            isSecure: true,
            isHttpOnly: true,
            expiresDate: expires is DateTime ? expires.millisecondsSinceEpoch : DateTime.now().add(Duration(days: 1)).millisecondsSinceEpoch,
            path: "/")
        .catchError((error) {
      print(error);
    });`
On android I have 8 cookies and 5 of them I put through the app:
![Android](https://user-images.githubusercontent.com/79815839/195605735-b4cec179-1400-42a4-bd3b-c1e576361398.png)


But on IOS only the website is left, the app doesn't set any cookies and doesn't show an error:
![IOS](https://user-images.githubusercontent.com/79815839/195610915-83ec8438-09f2-4cb8-8621-748e8541bfea.png)

**Comment by pichillilorenzo** [comment]
@lugael you need to set the domain as `.apcontrole.com.br`, with a **dot** in front!
If the dot is omitted, this attribute defaults to the host of the current document URL, not including subdomains.

**Comment by lugael** [comment]
It's work for me thanks

**Comment by fabienbranchel** [comment]
I don't have to handle any subdomain in my case but anyway, specify `domain` seems to be the key to make it works for iOS.


```
_cookieManager.setCookie(
    url: InAppWebview.WebUri(cookie.domain),
    domain: cookie.domain,
    name: cookie.name,
    value: cookie.value,
);
```
