### ISSUE TITLE
Can't launch in ios

### ISSUE THREAD

**Issue by kandangit** [pichillilorenzo/flutter_inappwebview#1181]
## Environment

-| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.10.4             |
| Plugin version       |  5.3.2              |
| iOS version          |  15.4              |
| Xcode version        |  13.3              |

Device information: Emulator: iPhone 11

## Description

**Expected behavior:** 

The app loads in the emulator with the inappbrowser working

**Current behavior:** 

The app fails to run in the emulator:

[  +40 ms] Error running pod install
[   +3 ms] **Error launching application on iPhone 11.**

## Steps to reproduce

fluter create --ios-language swift testflutter 
cd testflutter
-- ADD dependency to pubspec.yaml: flutter_inappwebview: ^5.3.2
flutter pub get
flutter run

NOTES: 
- I have uncommented in Podfile: platform :ios, '9.0'
- Also have tried changing to platform :ios, '15.4'
- Also have tried other solutions like those form https://stackoverflow.com/questions/59418820/error-running-pod-install-error-- launching-application-on-iphone11-pro-max (update cocoa pods, etc)

Have no issues in Android or in iOS with other Flutter apps that don't include the pluggin dependency.

## Stacktrace/Logcat   

[  +40 ms] Error running pod install
[   +3 ms] Error launching application on iPhone 11.
[   +6 ms] "flutter run" took 19.412ms.
[  +17 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

**Comment by yunchiri** [comment]
same error

**Comment by pichillilorenzo** [comment]
I cannot replicate your error. I have created a new fresh app (using Android Studio in my case) and it just works.
I'm using `flutter_inappwebview: 5.4.3+7`.

Here is my `flutter doctor -v` command result:
```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale it-IT)
    • Flutter version 2.10.4 at /Users/lorenzopichilli/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/lorenzopichilli/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_HOME = /Users/lorenzopichilli/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/lorenzopichilli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • A4121D94-1313-46CD-B0D1-36BFA91A8D57 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.54
    ! Error: iPhone di Lorenzo is not connected. Xcode will continue when iPhone di Lorenzo is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

This is my `pubspec.yaml` file:
```yaml
name: flutter_inappwebview_test
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: 5.4.3+7
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

And this is the example code:
```dart
import 'dart:async';
import 'dart:developer';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (defaultTargetPlatform == TargetPlatform.android) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(kDebugMode);
  }
  runApp(const MaterialApp(
      home: MyApp()
  ));
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController? webViewController;
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text("InAppWebView TEST")),
        body: SafeArea(
            child: Column(children: <Widget>[
              Expanded(
                child: Stack(
                  children: [
                    InAppWebView(
                      key: webViewKey,
                      initialUrlRequest: URLRequest(
                          url: Uri.parse('https://github.com/flutter')),
                      initialOptions: options,
                      onWebViewCreated: (controller) {
                        webViewController = controller;
                      },
                      onLoadStart: (controller, url) {
                        log("onLoadStart $url");
                      },
                      onLoadStop: (controller, url) {
                        log("onLoadStop $url");
                      },
                    ),
                  ],
                ),
              ),
            ]))
    );
  }
}
```

Screen recording using iPhone 13 Pro Emulator of the code example:
![Simulator Screen Recording - iPhone 13 Pro - 2022-05-11 at 23 23 43 mp4](https://user-images.githubusercontent.com/5956938/167950426-c732b2b0-30f6-4c33-a8f2-8ed37714053e.gif)

**Comment by kandangit** [comment]
Thanks for your quick response, I will take a further look. I believe this may be an environment issue, not sure yet. It is happening whenever I build the app (just the dependency added is enough) in iOS.

**Comment by yunchiri** [comment]
> 



> Thanks for your quick response, I will take a further look. I believe this may be an environment issue, not sure yet. It is happening whenever I build the app (just the dependency added is enough) in iOS.

Are you working?

**Comment by kandangit** [comment]
> 

After some attempts I have removed developers' cache storage and restarted and the project loads ok (had also to reinstall Cocoa pods). 

Have not come accross the specific issue you show but will test it more, thanks anyway for the hint. Certainly simulators can give many problems but it is beyond the scope of the plugin.

Will close the issue as  it seems was an environment issue. I had problems with plugins, but this was happening with any plugin, i just tested this one first.
