### ISSUE TITLE
Date picker(Calendar) is not open in webview

### ISSUE THREAD

**Issue by mukkumukesh** [pichillilorenzo/flutter_inappwebview#1185]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.5.1         |
| Plugin version       |        5.3.2       |
| Android version      |      31         |
| iOS version          |         working      |
| Xcode version        |         NA      |

Device information: 

## Description

**Expected behavior:** 

The calendar should be open to pic date in webview.

**Current behavior:** 
Currently, nothing happens on clicking of input button on webview.

## Steps to reproduce

1. Open webview
2. Then there is a button from which we tap to select the date on the webview
3. Then nothing happens

## Images   

https://user-images.githubusercontent.com/12988908/168590911-68b2dabf-7daf-491c-9165-eb66debdfaeb.mp4

## Stacktrace/Logcat   

`
final InAppWebViewGroupOptions options = InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(useShouldOverrideUrlLoading: true, supportZoom: false,javaScriptCanOpenWindowsAutomatically: true,javaScriptEnabled: true),
  android: AndroidInAppWebViewOptions(
    supportMultipleWindows: true,
   useHybridComposition: true// crash If am I ussing this key
  ));
`

`
IndexedStack(index: _position, children: <Widget>[
                  Padding(
                      padding: EdgeInsets.only(top: 56),
                      child: InAppWebView(
                        initialOptions: options,
                        onWebViewCreated: (InAppWebViewController controller) {
                          setCookie();
                          controller.loadUrl(
                              urlRequest:
                                  URLRequest(url: Uri.parse(widget._url)));
                        },
                        shouldOverrideUrlLoading: navigationDelegate,
                        onLoadStart: showLoader,
                        onLoadStop: hideLoader,
                        androidOnPermissionRequest: (controller, origin, resources) async {
                          return PermissionRequestResponse(
                              resources: resources,
                              action: PermissionRequestResponseAction.GRANT);
                        },
                      ),
                    ),
                    Center(
                        child: SizedBox(
                      height: 98,
                      width: 98,
                      child: Image.asset("assets/images/loader.gif"),
                    )),
                  ])
`

**Comment by kimonneuhoff** [comment]
I have the same issue
