### ISSUE TITLE
[flutter_inappwebview] hybrid composition causes flickering in AppBar and BottomNavigationBar

### ISSUE THREAD

**Issue by fch21** [pichillilorenzo/flutter_inappwebview#1186]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   2.10.5   |
| Plugin version       |    5.4.3+7   |
| Android version      |     11     |
| iOS version          |               |
| Xcode version        |               |

Device information: Xiaomi Poco X3 Pro 

## Description

**Expected behavior: The expected is that the change between PageView pages will occur without any effect on the appBar or bottomNavigationBar. ** 

**Current behavior: We can see an unwanted flickering effect in the widgets. ** 

## Example Project

[example_bug_webview.zip](https://github.com/flutter/flutter/files/8709150/example_bug_webview.zip)

## Steps to reproduce

  final PageController _pageController = PageController();

  late InAppWebViewController webViewController;

  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,
        disableHorizontalScroll: true,
        disableVerticalScroll: true,
        supportZoom: false,
        transparentBackground: true,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      )
  );

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: PageView.builder(
        physics: const BouncingScrollPhysics(),
        controller: _pageController,
        itemCount: 5,
        itemBuilder: (BuildContext context, int index) {

          return SingleChildScrollView(
            padding: const EdgeInsets.fromLTRB(0, 50 , 0, 50),
            child: Stack(
              children: [

                Container(
                  height: MediaQuery.of(context).size.height * 1.2,
                  width: MediaQuery.of(context).size.width,
                  color: Colors.blue.withOpacity(0.5),
                ),

                Padding(
                  padding: const EdgeInsets.fromLTRB(0, 50, 0, 50),
                  child:  SizedBox(
                    height: 100,
                    child: InAppWebView(
                      initialData: InAppWebViewInitialData(data: '''
                      <!DOCTYPE html>
                        <html>
                          <head>
                              <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
                          </head>
                          <body>
                        
                          <h1>Heading of page $index</h1>
                        
                          <p> Paragraph.</p>   
                        
                          </body>
                        </html>
                      ''',),
                      initialOptions: options,
                      onWebViewCreated: (controller) {
                        webViewController = controller;
                      },
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: Colors.blue,
        selectedItemColor: Colors.white,
        iconSize: 32,
        items: const [

          BottomNavigationBarItem(
            label: "",
            icon: Icon(Icons.home),
          ),

          BottomNavigationBarItem(
            label: "",
            icon:  Icon(Icons.search),
          ),

          BottomNavigationBarItem(
            label: "",
            icon: Icon(Icons.settings,),
          ),

        ],
      ),
    );
  }

1. Execute `flutter run` on the code sample 
2. To demonstrate the bug found, it is only necessary to swipe between the PageView pages (which contains a webView). By doing this, when a widget is behind the AppBar or BottomNavigationBar, we can see an unwanted flickering effect. 
3. This effect is only seen when using the option useHybridComposition: true in the inAppWebView options. 

## Videos 

https://user-images.githubusercontent.com/32543363/168830359-235c20f6-95c0-4849-968a-962a74aa571b.mp4

## Flutter Doctor

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale fr-FR)
    • Flutter version 2.10.5 at /Users/devfuretcompany/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/devfuretcompany/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • M2102J20SG (mobile) • 8d9b713f • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by fch21** [comment]
Fixed in the Flutter 3.0.0

**Comment by fch21** [comment]
The problem is back in the latest versions

**Comment by Shu-Ji** [comment]
Flutter v3.3.10 also flickers
