### ISSUE TITLE
Back button or cross button to close

### ISSUE THREAD

**Issue by kandangit** [pichillilorenzo/flutter_inappwebview#1189]
## Environment

**Flutter version:** 2.10.4
**Plugin version:** 5.3.2

## Description

I have gone through all options in the documentation and have not found any option related:

This is to add a **left cross button to enable close the InAppBrowser within the InAppBrowser**. At the moment it is only possible with either going back all the pages with the device's back button or the right contextual menu which has the option to close it. In iOS that already exists.

I believe this helps the InAppBrowser integrating better within the app and improves the usability (when it comes to going back to the app), in comparison with the right contextual menu, regarding the "close" functionality.

Example: In React Native/NativeScript it is possible with the "hasBackButton" property: https://github.com/proyecto26/react-native-inappbrowser.
Example (in this case, NativeScript):

![image](https://user-images.githubusercontent.com/19682150/169071116-51ee3faa-54fd-4117-a2fc-3f4b689c6974.png)

Apologies if this has been asked before, didnt find it.

**Comment by realshovanshah** [comment]
Same problem here. This seems to be a problem on Android. The close button appears as expected on iOS.

**Comment by adminant** [comment]
Any news on this issue? Need close button on Android as well as on iOS for better usability
