### ISSUE TITLE
Can't load dynamic libraries from other packages when using flutter_inappweb (on Android 5 and 6.)

### ISSUE THREAD

**Issue by jpolstre** [pichillilorenzo/flutter_inappwebview#1197]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       3.0.1       |
| Plugin version      |     5.4.3+7     |
| Android version    |    5 and 6      |

Device information: 

## Description
Spected behavior:
Use flutter_inappwebview package on Android 5 and 6 devices in conjunction with other packages that load dynamic libraries (specifically Isar, flutter_js).

Current behavior:
It is not possible to load the dynamic libraries of the other packages, when using the flutter_inappwebview package(on Android 5 and 6).
 

## Steps to reproduce
 1.  Add this to your pubspect.yaml in a new project:
  
 ```
  ...
  flutter_js: ^0.5.0+6
  isar: ^3.0.0-dev.0
  flutter_inappwebview: ^5.4.3+7
```
2. Try on an emulator or physical device running Android 5 or 6. You will get an error like this:
```
Unable to load dynamic library  *.so
```

3.Now do the same but without the inappwebview flutter package:
 ```
  ...
  flutter_js: ^0.5.0+6
  isar: ^3.0.0-dev.0
```
4. Everything will load correctly.

Note.- on devices with Android >= 7, it works correctly. The problem appears only on devices with Android 5 and 6 (SDK <=22)

## Stacktrace/Logcat   

with Isar and flutter_inappwebview:
```
Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
E/flutter ( 5871): #0      initializeCoreBinary
package:isar/…/native/isar_core.dart:62
E/flutter ( 5871): #1      openIsar
package:isar/…/native/open.dart:53
E/flutter ( 5871): #2      _IsarNative.open
```

with flutter_js and futter_inappwebview:

```
( 6264): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libfastdev_quickjs_runtime.so': dlopen failed: library "libfastdev_quickjs_runtime.so" not found
E/flutter ( 6264): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
E/flutter ( 6264): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
E/flutter ( 6264): #2      _qjsLib
package:flutter_js/quickjs/ffi.dart:129
E/flutter ( 6264): #3      _qjsLib (package:flutter_js/quickjs/ffi.dart)
package:flutter_js/quickjs/ffi.dart:1
E/flutter ( 6264): #4      _jsNewRuntime
package:flutter_js/quickjs/ffi.dart:163
E/flutter ( 6264): #5      _jsNewRuntime (package:flutter_js/quickjs/ffi.dart)
package:flutter_js/quickjs/ffi.dart:1
E/flutter ( 6264): #6      jsNewRuntime
package:flutter_js/quickjs/ffi.dart:206
E/flutter ( 6264): #7      QuickJsRuntime2._ensureEngine
package:flutter_js/quickjs/quickjs_runtime2.dart:51
```
So the problem is from flutter inappwebview

**Comment by filipenanclarez** [comment]
Possible solution:

https://github.com/simolus3/drift/issues/895#issuecomment-729165464
