### ISSUE TITLE
Use "inappwebview" to show a white edge to the right

### ISSUE THREAD

**Issue by lh-xiaojiang** [pichillilorenzo/flutter_inappwebview#1204]
`InAppWebView(
    key: _key,
    initialUrlRequest: URLRequest(url: Uri.parse('https://image.baidu.com/search/wiseindex?tn=wiseindex')),
    gestureRecognizers: [
      Factory(() => VerticalDragGestureRecognizer()),
      Factory(() => HorizontalDragGestureRecognizer()),
    ].toSet(),
    initialOptions: options,
    onLoadStop: (controller, url) {
      timer.cancel();
    },
    onLoadStart: (controller, url) {
      _initTimer();
    },
    onLoadError: (controller, url, index, erro) {
      print(1111111);
      loadErr = true;
      setState(() {});
    },
)`

Emerging Problem：
![微信截图_20220531183427](https://user-images.githubusercontent.com/58511617/171154515-0877d4f9-9d47-4fc4-b4d0-a7e283d28c5c.png)
How to eliminate the white border?

**Comment by dev-kasibhatla** [comment]
This is a problem more specifically seen in phones with rounded rectangular displays and/or notches. Basically phones which have a non-zero `MediaQuery.of(context).padding.top` or `MediaQuery.of(context).padding.top` when the app is in full screen mode.

**Comment by BrianCliton** [comment]
I havae the same problem
