### ISSUE TITLE
URLCredential.fromMap returns null for username

### ISSUE THREAD

**Issue by veganD** [pichillilorenzo/flutter_inappwebview#1205]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.10.5         |
| Plugin version       |         5.4.3      |
| Android version      |        12       |
| iOS version          |               |
| Xcode version        |               |

Device information: Google Pixel 3a

## Description

**Expected behavior:** 
1. set URLCredentials with `setHttpAuthCredential`
2. get URLCredentials with `getHttpAuthCredentials`
3. URLCredential contains username & password

**Current behavior:** 
1. set URLCredentials with `setHttpAuthCredential`
2. get URLCredentials with `getHttpAuthCredentials`
3. URLCredential contains password but username is null

## Steps to reproduce

``` dart
HttpAuthCredentialDatabase database =
    HttpAuthCredentialDatabase.instance();

await database.setHttpAuthCredential(
  protectionSpace: URLProtectionSpace(
    host: url.host,
    port: url.port,
    protocol: url.scheme,
    realm: "user",
  ),
  credential: URLCredential(username: "USERNAME", password: "PASSWORD"),
);

List<URLCredential> credentials = await database.getHttpAuthCredentials(
    protectionSpace: URLProtectionSpace(
  host: url.host,
  protocol: url.scheme,
  port: url.port,
  realm: "user",
));

inspect(credentials);
// [{"username": null, "password": "PASSWORD", "iosPersistence": null, "iosCertificates": null}]
```

I believe the issue is in the `.toMap` method of the `URLCredential` class. The method maps the username with the property `user` instead of `username`, changing this fixes the problem.

``` diff dart
// flutter_inappwebview-5.4.3/lib/src/types.dart 
static URLCredential? fromMap(Map<String, dynamic>? map) {

  // ...

  return URLCredential(
-    username: map["user"],
+    username: map["username"],
    password: map["password"],
    iosCertificates: iosCertificates,
    iosPersistence:
        IOSURLCredentialPersistence.fromValue(map["iosPersistence"]),
  );
}
```

**Comment by pichillilorenzo** [comment]
Fixed with version `5.6.0`
