### ISSUE TITLE
Android App freezes after resuming from background

### ISSUE THREAD

**Issue by W3-Tariqul** [pichillilorenzo/flutter_inappwebview#1215]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        3.0.1       |
| Plugin version       |        flutter_inappwebview: ^5.4.3+7       |
| Android version      |     Android 10          |
| iOS version          |               |
| Xcode version        |               |

Device information: 

Samsung A10.
Ram 4 GB

## Description

I am using this plugin test app. After opening the app scroll through the web view content then pause the app by switching to another app and coming back again. Then scroll not working. Webview stuck.

**Expected behavior:** 

Should be scrollable

**Current behavior:** 

App stuck scroll not working even page not moving.

## Steps to reproduce

1. Just run the [example ](https://github.com/pichillilorenzo/flutter_inappwebview/tree/master/example)app
2. Scroll the content
3. Switch to another app. Spend 3-4 seconds there
4. Comeback to the example app and try to scroll through the web view

## Video  

https://user-images.githubusercontent.com/51702849/172613683-72501bb1-85e2-401f-894b-40724e2c10cd.mp4

**Comment by p-chaldaios** [comment]
Same problem here.
Got any update on this one?

**Comment by W3-Tariqul** [comment]
> Same problem here. Got any update on this one?

Unfortunately not. It seems it's a flutter current version problem cause I found flutter_webview and Google Maps has the same problem.

**Comment by p-chaldaios** [comment]
> > Same problem here. Got any update on this one?
> 
> Unfortunately not. It seems it's a flutter current version problem cause I found flutter_webview and Google Maps has the same problem.

Just found this project https://github.com/pichillilorenzo/flutter_browser_app
that uses flutter_inappwebview and seems that this issue does not exist.
Is it possible due to older flutter version?

**Comment by W3-Tariqul** [comment]
> > > Same problem here. Got any update on this one?
> > 
> > 
> > Unfortunately not. It seems it's a flutter current version problem cause I found flutter_webview and Google Maps has the same problem.
> 
> Just found this project https://github.com/pichillilorenzo/flutter_browser_app that uses flutter_inappwebview and seems that this issue does not exist. Is it possible due to older flutter version?

I found it starts from flutter 3.0

**Comment by YaaNafs** [comment]
> > > > Same problem here. Got any update on this one?
> > > 
> > > 
> > > Unfortunately not. It seems it's a flutter current version problem cause I found flutter_webview and Google Maps has the same problem.
> > 
> > 
> > Just found this project https://github.com/pichillilorenzo/flutter_browser_app that uses flutter_inappwebview and seems that this issue does not exist. Is it possible due to older flutter version?
> 
> I found it starts from flutter 3.0

Hi guys, I'm facing the same issue here and I have downgraded Flutter to version 2.2.0. The inappwebview UI freezes when the app is resumed from background on Android 10+ and it crashes on Android version less than 10

**Comment by p-chaldaios** [comment]
> > > > > Same problem here. Got any update on this one?
> > > > 
> > > > 
> > > > Unfortunately not. It seems it's a flutter current version problem cause I found flutter_webview and Google Maps has the same problem.
> > > 
> > > 
> > > Just found this project https://github.com/pichillilorenzo/flutter_browser_app that uses flutter_inappwebview and seems that this issue does not exist. Is it possible due to older flutter version?
> > 
> > 
> > I found it starts from flutter 3.0
> 
> Hi guys, I'm facing the same issue here and I have downgraded Flutter to version 2.2.0. The inappwebview UI freezes when the app is resumed from background on Android 10+ and it crashes on Android version less than 10

For me after downgrading to Flutter 2.0.6 the issue seems to be resolved. Can you test on Flutter 2.0.6 and give us feedback?

**Comment by Manuito83** [comment]
I have the same issue, but I'm unable to replicate it locally. 

Reverting to InAppWebView v5.3.2 seems to have fixed it. Could you maybe check? Perhaps that way we could try to identify what's causing it?

**Comment by W3-Tariqul** [comment]
> I have the same issue, but I'm unable to replicate it locally.
> 
> Reverting to InAppWebView v5.3.2 seems to have fixed it. Could you maybe check? Perhaps that way we could try to identify what's causing it?

Could you share your flutter doctor report?

**Comment by sathya4code** [comment]
Hi,

I am also facing the same issue. App crashing after resuming it from background.

**Crash Log**:
`F/libc    ( 6850): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 6991 (RenderThread), pid 6850 (m.xxx.xxx)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/dandelion_in/dandelion:10/QP1A.190711.020/V12.0.22.0.QCDINXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2022-07-01 16:41:03+0530
pid: 6850, tid: 6991, name: RenderThread  >>> com.xxx.xxx <<<
uid: 10456
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'drawRenderNode called on a context with no surface!'
    r0  00000000  r1  00001b4f  r2  00000006  r3  ba55ab50
    r4  ba55ab64  r5  ba55ab48  r6  00001ac2  r7  0000016b
    r8  ba55ab60  r9  ba55ab50  r10 ba55ab80  r11 ba55ab70
    ip  00001b4f  sp  ba55ab20  lr  e7150343  pc  e7150356
backtrace:
      #00 pc 0005f356  /apex/com.android.runtime/lib/bionic/libc.so (abort+166) (BuildId: af31ec96b35fedca378e07659b30896c)
      #01 pc 00005a31  /system/lib/liblog.so (__android_log_assert+176) (BuildId: 0e6ad61102d821f742108ac9db1c6d21)
      #02 pc 0029ec3b  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::getFrame()+26) (BuildId: cf5a3982d29f06d7a11e7d077a3d4440)
      #03 pc 002a4b11  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+140) (BuildId: cf5a3982d29f06d7a11e7d077a3d4440)
      #04 pc 002a414b  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+170) (BuildId: cf5a3982d29f06d7a11e7d077a3d4440)
      #05 pc 002b1aef  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+158) (BuildId: cf5a3982d29f06d7a11e7d077a3d4440)
      #06 pc 002b194d  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72) (BuildId: cf5a3982d29f06d7a11e7d077a3d4440)
      #07 pc 0000d8b3  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+182) (BuildId: a4424e73dbe004e8623d6713ad30a604)
      #08 pc 000a6293  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) (BuildId: af31ec96b35fedca378e07659b30896c)
      #09 pc 00060803  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: af31ec96b35fedca378e07659b30896c)`

**Comment by sathya4code** [comment]
Hi All,

This issue has been resolved after upgrading the Flutter version.(Current version 3.0.4)

**Comment by YaaNafs** [comment]
Yes  @sathya4code, the issue has been fixed in Flutter version 3.0.4, thanks!.
