### ISSUE TITLE
Xcode 14 build error: Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by SethuSenthil** [pichillilorenzo/flutter_inappwebview#1216]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     3.0.1          |
| Plugin version       |       5.4.3+7        |
| Android version      |    n/a           |
| iOS version          |        16.0 DB1       |
| Xcode version        |        14 B1       |

Device information: 

## Description
When attempting to compile with the new Xcode beta, the following error prevents us from completin.g the build

**Expected behavior:** 
No error

**Current behavior:** 
Throws build error: Stored properties cannot be marked potentially unavailable with '@available'

## Steps to reproduce

1. Run flutter run on any project that depends on flutter_inappwebview

## Images   
![Screen Shot 2022-06-08 at 4 01 13 PM](https://user-images.githubusercontent.com/20134046/172706399-2275f163-9950-4df7-8306-c42ba9b6fcf6.png)

**Comment by SethuSenthil** [comment]
After doing some experimentation, I believe the most straightforward approach would be to wrap the class around another class that will instantiate two different versions of the UserScript class, one specifically meant for iOS 14+ and the other for versions less than iOS 14. 
This is because we need the ' @available(iOS 14.0, *)' header above the entire class in order to utilize WKContentWorld in this new build process

**Comment by ghensto** [comment]
@pichillilorenzo is there any work around until the issue get fixed?

**Comment by mikhael28** [comment]
Code Eagle's open PR resolves this issue.

**Comment by note11g** [comment]
@mikhael28 Can you share PR link?

**Comment by cimplesid** [comment]
also exists on the Xcode 14.0 stable version

**Comment by mirkancal** [comment]
Exists in XCode 14.0 stable. My current fix is:

Update version in Podfile
`platform :ios, '14.0'
`

Reset pods
`cd ios && rm -rf Pods/ Podfile.lock && pod install --repo-update`

**Comment by mirkancal** [comment]
I've simply fixed it by updating the platform to iOS 14 in Podfile.

https://stackoverflow.com/a/73699790/9779791

**Comment by riegersan** [comment]
@mirkancal but this means that you only support iOS 14 and higher

I used another git repo wich already has the fix included as workaround

`flutter_inappwebview: 
    git: https://github.com/CodeEagle/flutter_inappwebview`

**Comment by mirkancal** [comment]
@riegersan yes. 7 years old iPhone 6s has iOS 14. I'm okay with it.

**Comment by luan20495** [comment]
I fix update target 14 in file ios/Podfile
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

**Comment by mirkancal** [comment]
@blue492 it seems like the package is asking higher iOS target. 

What's your target? It's in podfile, beginning of the file, in the line:
Probably commented out or less than 11.
`platform :ios, 'X.0'`

I'm also manually increasing with Podfile script.

 ```
     if Gem::Version.new('11.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
```
![image](https://user-images.githubusercontent.com/26160059/192320011-871ae036-64a3-4dc3-8d7c-53d22646b902.png)

**Comment by pichillilorenzo** [comment]
Released version `5.4.3+8` with pull request merged!

**Comment by Anna-Myzukina** [comment]
After updating Xcode to 14 version, I get this error and fixed it by changing in Podfile platform:ios to 14

- open folder ios
- open Podfile
- in Podfile uncomment line number 2 and change "platform :ios, '14.0'"

<img width="932" alt="Screenshot 2022-12-19 at 16 45 21" src="https://user-images.githubusercontent.com/26605804/208466095-7e1c3f4c-f119-4b4f-95bc-0b9b5ddd01a6.png">

**Comment by jcpriascRZ** [comment]
I was getting the same error, and i had to update @stripe/stripe-react-native:
<img width="394" alt="Screenshot 2023-03-21 at 4 02 46 pm" src="https://user-images.githubusercontent.com/82363228/226523005-c1951af6-bfd1-4e67-9661-0861e8d83841.png">

then i updated cocoapods with:
pod update

and change the platform :ios to '13.0'

<img width="313" alt="Screenshot 2023-03-21 at 4 04 43 pm" src="https://user-images.githubusercontent.com/82363228/226523174-5894b817-bae2-4d66-aa36-4fce1398dc1f.png">

**Comment by lyf571321556** [comment]
> @mirkancal but this means that you only support iOS 14 and higher
> 
> I used another git repo wich already has the fix included as workaround
> 
> `flutter_inappwebview: ` ` git: https://github.com/CodeEagle/flutter_inappwebview`

this repo  not exits.

**Comment by simranchawla20** [comment]
this was helpfull. Thanks:)
