### ISSUE TITLE
Xcode 14 beta Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by kelvinmarshall** [pichillilorenzo/flutter_inappwebview#1219]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Plugin version       |         5.1.0      |
| iOS version          |       16 beta        |
| Xcode version        |       14 beta        |

## Description
Error Stored properties cannot be marked potentially unavailable with '@available' when compiling in Xcode 14 beta.

**Expected behavior:** 
Compile in Xcode 14

**Current behavior:** 
Compile fails

## Steps to reproduce
Build in Xcode 14 beta

## Images   
<img width="780" alt="image" src="https://user-images.githubusercontent.com/26925891/173200371-d47b26f2-19be-4925-bfd9-13f920f3be04.png">

**Comment by lulumeimei** [comment]
hi @kelvinmarshall. Could you share your solution for this issue?

**Comment by kelvinmarshall** [comment]
@lulumeimei You can track this issue on #1216
