### ISSUE TITLE
 I want to send request body parameters with json type to a url. It works in android  but I get an error in ios

### ISSUE THREAD

**Issue by rahulrmishra** [pichillilorenzo/flutter_inappwebview#1225]
I want to open a url and send it a json request in body.
I am able to open the url in android phone but in I get an error in ios. Error code is -1103 and error message as "resource exceeds maximum size"
This is my code

InAppWebView(
                      initialUrlRequest: URLRequest(
                        url: Uri.parse(
                          widget.url,
                        ),
                        headers: {
                          "Accept": "application/json",
                          "Authorization": "${userDetails.accessToken}",
                          "Content-Type": "application/json"
                        },
                        body:
                            Uint8List.fromList((utf8.encode(body.toString()))),
                      ),
                      initialOptions: InAppWebViewGroupOptions(
                        crossPlatform: InAppWebViewOptions(
                        ),
                      ),
                      onWebViewCreated:
                          (InAppWebViewController controller) async {
                      },
                      onLoadStart:
                          (InAppWebViewController controller, Uri? url) async {
                      },
                      onLoadError: (_, __, ___, ____) {
                        print(___);
                        print(____);
                      },
                      onLoadStop:
                          (InAppWebViewController controller, Uri? url) async {
                      },
                    )

**Comment by hankfrinkle** [comment]
In my optionion, on iOS it's not allowed to add a body in GET request.

**Comment by rahulrmishra** [comment]
> In my optionion, on iOS it's not allowed to add a body in GET request.

Yes, I figured it out. I had to explicitly set method as 'POST'. After that it worked. Thank you for replying
