### ISSUE TITLE
ChromeSafariBrowser cannot open if default browser app does not support custom tabs on Android

### ISSUE THREAD

**Issue by addie9000** [pichillilorenzo/flutter_inappwebview#1232]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [ ] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.10.5 |
| Plugin version       |  5.4.3+7  |
| Android version      |  6.0.0+  |
| iOS version          | N/A |
| Xcode version        | N/A |

Device information: 

## Description

Only on Android.
ChromeSafariBrowser cannot open if default browser app does not support custom tabs, due to limitation of PackageManager#queryIntentActivities since Android M/N.

note:
issue #391 looks like similar but probably not exactly the same.

**Expected behavior:** 

Open with Chrome

**Current behavior:** 

Nothing happens but output StackTrace.
See Stacktrace/Logcat section.

## Steps to reproduce

1. Install browser app which does not support custom tabs such as Sleipnir
https://play.google.com/store/apps/details?id=jp.co.fenrir.android.sleipnir

2. Set installed browser as a default browser app by setting app

3. Try to open URL by ChromeSafariBrowser

## Stacktrace/Logcat   
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ChromeBrowserManager, ChromeCustomTabs is not available!, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      ChromeSafariBrowser.open (package:flutter_inappwebview/src/chrome_safari_browser/chrome_safari_browser.dart:112:5)
<asynchronous suspension>
#3      LoginPageState._openExternalBrowser (package:poddog2_app/ui/login/login_page.dart:253:5)
<asynchronous suspension>
```

**Comment by AnthonyGhizzo** [comment]
Yes ! We need...

**Comment by pichillilorenzo** [comment]
Fix merged now

**Comment by snipd-min** [comment]
This error seems to happen again after the fix from Android 13 devices... Did someone have the same issue?
