### ISSUE TITLE
Permission prompt appears twice

### ISSUE THREAD

**Issue by holailusoria** [pichillilorenzo/flutter_inappwebview#1239]
Hi. I'm using the last version(5.4.3) of inappwebview plugin. I am running a webview locally(without local server).
When permission is required for geolocation, the request is duplicated twice. As far as I understand, the first request is directly for the app, and the second for the webview.

How can I get rid of that second request ? Because it sure isn’t great UX…

Below are screenshots of what it looks like.
![image](https://user-images.githubusercontent.com/50683634/176375841-f913aa54-de54-4909-9658-915131c1e603.png)
![image](https://user-images.githubusercontent.com/50683634/176376003-2cc4ae89-682a-45e2-aa8b-973f5b06a7fb.png)

I found the same article for WKWebView on IOS. But I couldn't figure out how to implement it in Flutter.

https://stackoverflow.com/questions/39665367/how-to-prevent-wkwebview-to-repeatedly-ask-for-permission-to-access-location

**Comment by lehmannphi** [comment]
@holailusoria Ich have the same problem with react-native-webview. Any solution?

**Comment by 2000calories** [comment]
same problem. Any solution?
