### ISSUE TITLE
Any chances flutter_inappwebview supports for Flutter Web in the future ?

### ISSUE THREAD

**Issue by jpsarda** [pichillilorenzo/flutter_inappwebview#1243]
I'm aware that this is not an easy task, because this package is based in the native WKWebview on iOS and WebView on android, but would it be possible to implement web support for this package ? After all it's a web view and it would run on a web platform that already has a web engine. Maybe that could be implemented as an iframe, I'm not sure. I didn't find any discussion on this in the issues, sorry if I didn't search correctly.

**Comment by pichillilorenzo** [comment]
Hi @jpsarda, the next version 6.0.0 will have support for Flutter Web.
Actually, the "develop" branch of the repository is an unpublished "beta" version that already supports it: https://github.com/pichillilorenzo/flutter_inappwebview/tree/develop
However, more work is needed before it can be published.

**Comment by jpsarda** [comment]
Wow, I didn't expect that, that's great news. May I ask how are you doing this, using iframes maybe ? I'm also curious about the local web server, that doesn't seem to be possible in javascript, did you find a solution or a workaround for this ? 

On my app, I download html and images and I render them offline in the inappwebview using the local web server (because people use the app in locations with poor or no internet, so we ask them to download things before going there). Would it be possible to do something similar when the package supports the web ?

**Comment by pichillilorenzo** [comment]
It uses iframes because it's the only way to do something similar to a WebView.
However, the iframe has a lot of limitations! In fact, a lot of features simply cannot be implemented.
The local web server feature cannot be implemented on Flutter Web (you are on a Browser and not on an Operating System).
Currently on the "dev" branch, to check if a method, a class, or a feature of the plugin is supported by a specific Flutter platform, you can check the docs of the code directly.

**Comment by yadaniyil** [comment]
@pichillilorenzo is `window.flutter_inappwebview.callHandler('channel', message);` possible to listen from the flutter web? I'm using the develop branch. Thanks!

**Comment by pichillilorenzo** [comment]
@jpsarda New version 6 with web support is out right now!

**Comment by Cypher103360** [comment]
@pichillilorenzo I tried using the beta version 6 of the `InAppWebView`, it worked on the Android phone, but it didn't work on the web. I am using Linux. So, will it work on Linux or on Windows?

**Comment by MichaelSSY** [comment]
> @jpsarda支持网络的新版本 6 现已发布！

hello , I am using Flutter_inappwebview 6.0.0 and encountered an error while running the web. What is the reason?
Here are the error messages and the Flutter version information I am using,   @pichillilorenzo 

<img width="578" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/17715591/6fffc37a-36ce-4db4-b6c5-2feac6de654e">


` flutter_inappwebview: 6.0.0`

> Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (12 months ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
