### ISSUE TITLE
URL not setting in onLoadStart on Ajax webpages

### ISSUE THREAD

**Issue by sukhcha-in** [pichillilorenzo/flutter_inappwebview#125]
URL is not setting when site is using `Ajax` or no reload pages.
Example URL: `https://www.flipkart.com/search?q=iphone%20x`

Steps to reproduce:
1. Open above URL in `flutter_inappbrowser`
2. Tap on any product (Requires no reload because of ajax)
3. Check URL, It shows example URL stated above not the opened product URL

Each time i open new product i have to use `webController.reload();` to show the correct product URL

Note: To use example URL stated above `domStorage` must be enabled:
```
initialOptions: {
  "domStorageEnabled": true,
},
```

Code:
```
onLoadStart: (InAppWebViewController controller, String url) {
  setState(() {
    this.url = url;
  });
},
```

**Comment by pichillilorenzo** [comment]
Added new `onNavigationStateChange` event in version `2.0.0`, which is an event fired when the navigation state of the InAppWebView changes. 
Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
