### ISSUE TITLE
Calling enumerateDevices() will always return null value for labels

### ISSUE THREAD

**Issue by wer-mathurin** [pichillilorenzo/flutter_inappwebview#1250]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  3.0.5             |
| Plugin version       |  ^5.4.3+7             |
| Android version      |   12            |

Device information: 
Google Pixel 6 Pro

## Description
When running this command when inspecting the webview (in the console) after giving all permissions need for WebRTC

await navigator.mediaDevices.enumerateDevices();  

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

**Expected behavior:** 
This is the result of calling await navigator.mediaDevices.enumerateDevices() in a normal chrome browswer.
You can see there is 7 devices.
![image](https://user-images.githubusercontent.com/39314023/179295948-a91932a0-0011-44c7-8fa0-9b93d142360a.png)

**Current behavior:** 
This is the result of calling await navigator.mediaDevices.enumerateDevices() in a normal chrome browswer.
You can see there is 6 devices.
![image](https://user-images.githubusercontent.com/39314023/179296154-008bf831-2067-4aad-8073-3c2b01390db8.png)

Note that the **missing audioinput is the Bluetooth** device and the **labels are blank**

## Steps to reproduce
The code to test it.

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:permission_handler/permission_handler.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Permission.camera.request();
  await Permission.microphone.request();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: WebRTCWebview(),
    );
  }
}

class WebRTCWebview extends StatelessWidget {
  const WebRTCWebview({super.key});

  @override
  Widget build(BuildContext context) {
    return InAppWebView(
      initialOptions: InAppWebViewGroupOptions(
        crossPlatform: InAppWebViewOptions(
          mediaPlaybackRequiresUserGesture: false,
        ),
      ),
      initialUrlRequest: URLRequest(
        url:
            Uri.parse('https://www.pubnub.com/developers/demos/webrtc/launch/'),
      ),
      androidOnPermissionRequest: (controller, origin, resources) async {
        return PermissionRequestResponse(
          resources: resources,
          action: PermissionRequestResponseAction.GRANT,
        );
      },
    );
  }
}
```

1. Open the chrome://inspect/#devices
2. Inspect the webview
3. In the console run this command: await navigator.mediaDevices.enumerateDevices()
4. Now connect your bluetooth device
5. In the console run this command: await navigator.mediaDevices.enumerateDevices()

## Stacktrace/Logcat   
E/chromium( 8461): [ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.

**Comment by martipello** [comment]
Im seeing this also, and i also have a pixel 6 pro, i checked it on a samsung s8 running android 10 and the issue is reproducible there too

**Comment by hy-net** [comment]
``navigator.mediaDevices`` returns null for label as well.

**Comment by HoseinHaqiqian** [comment]
Same here

**Comment by Muhammad-Mohsen** [comment]
Hi,

Did anyone find a way to solve that problem?
