### ISSUE TITLE
@available(iOS 14.0, *) Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by jackobst** [pichillilorenzo/flutter_inappwebview#1251]
@available(iOS 14.0, *) Stored properties cannot be marked potentially unavailable with '@available'

**Comment by macuser79** [comment]
The problem has been solved and the solution is available at this address but I did not understand if it is already present in the latest version or if it must be released with a new version of the plugin

https://github.com/pichillilorenzo/flutter_inappwebview/pull/1238/commits/06f87e81c4f55b7b251a149ec0db60442bb351c3
