### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by wajehs** [pichillilorenzo/flutter_inappwebview#1254]
Extending macOS support would helpful

**Comment by Sunsiha** [comment]
hi @wajehs Have u got any other plugin for web version for this webview?

**Comment by wajehs** [comment]
@Sunsiha  Not yet so far for macOS.

**Comment by Sunsiha** [comment]
what about

> @Sunsiha Not yet so far for macOS.

what about web version?

**Comment by wajehs** [comment]
@Sunsiha  I think this package works fine with the web version. I also tried it

**Comment by Sunsiha** [comment]
@wajehs It's not working.

**Comment by wajehs** [comment]
@Sunsiha  May I know the exception you are facing?

**Comment by Sunsiha** [comment]
> @Sunsiha May I know the exception you are facing?

When am trying to load it in google chrome.

<img width="592" alt="Screenshot 2022-08-11 at 9 37 23 PM" src="https://user-images.githubusercontent.com/27992382/184179260-8ea9a0ff-476f-4d93-8841-2e5c40aef0d4.png">

**Comment by willemdjong** [comment]
Hi, it would be great if there could be support for both macOS and Windows for the in-app webview.

**Comment by sugur** [comment]
> Hi, it would be great if there could be support for both macOS and Windows for the in-app webview.

I also need to macOs for in-app webview, thanks!

**Comment by wajehs** [comment]
> > Hi, it would be great if there could be support for both macOS and Windows for the in-app webview.
> 
> I also need to macOs for in-app webview, thanks!

I think there is the beta version which already provides the resource for web view.

**Comment by pichillilorenzo** [comment]
check #460 for desktop support.
