### ISSUE TITLE
Youtube video not play in same page ( iframe tag ) IOS

### ISSUE THREAD

**Issue by amit-flutter** [pichillilorenzo/flutter_inappwebview#1255]
## Description

if we are using iframe and set any video path like youtube then in IOS it will redirect to the browser page.  it must be same like a safari where an iframe video is playing on the same page and user can interact with it easily. 

https://user-images.githubusercontent.com/64255990/180137094-ecedfd3d-7224-46ec-a345-2739d5af06a4.mov

**Comment by Chappie74** [comment]
@amit-flutter were you able to get this workign?
