### ISSUE TITLE
Android crashes when WebView opened

### ISSUE THREAD

**Issue by alectogeek** [pichillilorenzo/flutter_inappwebview#1256]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   3.0.5 / 2.10.5 (checked on both) |
| Plugin version       |   5.4.3+7 |
| Android version      | spotted on 10 and 11 |
| iOS version          |        -       |
| Xcode version        |       -        |

Device information: spotted on: Oppo A53s, Samsung Galaxy A7 (2018), Vivo V2065, and others

## Description

**Expected behavior: No crash :D** 

**Current behavior: App crashes in production. I can't reproduce the problem locally, but can see crashes mostly in Google Play console** 

## Steps to reproduce
Still couldn't reproduce locally. I don't know how to catch it. I'm here to provide any additional information.

## Stacktrace/Logcat   

# Crash reports in Google Play Console:
***
pid: 0, tid: 0 >>> my.bundle.id <<<

backtrace:
signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)
base.apk!libmonochrome.so (offset 0x48b000)

  #00  pc 0000000003e2d26c  /data/app/~~RgP4oLuAq6yMx70Hl-PU9A==/com.google.android.webview-Z7rqcPEw8X9r6_1BJ1dkow==/base.apk!libmonochrome.so (offset 0x48b000)
***
and
***
signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)
base.apk!libmonochrome_64.so

pid: 0, tid: 0 >>> my.bundle.id <<<

backtrace:
  #00  pc 000000000476daa0  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 00000000041b2808  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 00000000041b2354  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000001ff4208  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 000000000292ad4c  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000002921028  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 000000000254614c  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 00000000042043e0  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004203d80  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004202868  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 00000000040f5c84  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 00000000040f5908  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004203d80  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004203440  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004202d14  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004202b14  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 000000000404f99c  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 00000000041c2f28  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004ac4b04  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004ac4ab4  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000004ac4a30  /data/app/~~8NLXpq68zlnmXuQA2a8Tmw==/com.google.android.trichromelibrary_506007134-24MMUMJYdkbjX9fEEkfQvg==/base.apk!libmonochrome_64.so
  #00  pc 0000000000018184  /system/lib64/libutils.so (android::Looper::pollInner(int)+916)
  #00  pc 0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
  #00  pc 00000000001589a8  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
  #00  pc 000000000028444c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (art_jni_trampoline+108)
  #00  pc 00000000007e9808  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.MessageQueue.next+232)
  #00  pc 00000000007e69f4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.Looper.loopOnce+100)
  #00  pc 00000000007e68f4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.Looper.loop+516)
  #00  pc 0000000000563530  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.app.ActivityThread.main+800)
  #00  pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 000000000035b5d0  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+608)
  #00  pc 000000000035b348  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
  #00  pc 00000000000b2f74  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+132)
  #00  pc 0000000000b3a19c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+140)
  #00  pc 0000000000b435f8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2376)
  #00  pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 000000000044ca04  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+464)
  #00  pc 000000000062cf30  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+268)
  #00  pc 00000000000b3bf8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124)
  #00  pc 00000000000c01e4  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+852)
  #00  pc 00000000000025a8  /system/bin/app_process64 (main+1360)
  #00  pc 0000000000049f14  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100)
***

# Crash reports in Firebase Crashlytics (not sure if related):
***
Util.java line 119
com.pichillilorenzo.flutter_inappwebview.Util.invokeMethodAndWait

ThreadPoolForeg (waiting): tid=89 systid=17688 
       at sun.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1023)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1334)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
       at com.pichillilorenzo.flutter_inappwebview.Util.invokeMethodAndWait(Util.java:119)
       at com.pichillilorenzo.flutter_inappwebview.ServiceWorkerManager$1.shouldInterceptRequest(ServiceWorkerManager.java:55)
       at androidx.webkit.internal.FrameworkServiceWorkerClient.shouldInterceptRequest(FrameworkServiceWorkerClient.java:45)
       at lm0.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506007134:32)
       at ec.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506007134:122)
       at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebViewGoogle6432.aab-stable-506007134:34)
       
       

==============================

main (blocked): tid=1 systid=12648 | waiting to lock <0x0a900fcb> (java.lang.Object) held by thread 89
       at mm0.setServiceWorkerClient(chromium-TrichromeWebViewGoogle6432.aab-stable-506007134:58)
       at androidx.webkit.internal.ServiceWorkerControllerImpl.setServiceWorkerClient(ServiceWorkerControllerImpl.java:88)
       at com.pichillilorenzo.flutter_inappwebview.ServiceWorkerManager.<init>(ServiceWorkerManager.java:41)
       at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:91)
       at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:68)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:74)
       at java.lang.reflect.Method.invoke(Native method)
       at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
       at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1086)
       at my.bundle.id.MainActivity.configureFlutterEngine(MainActivity.kt:10)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:200)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
       at android.app.Activity.performCreate(Activity.java:8282)
       at android.app.Activity.performCreate(Activity.java:8262)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4005)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4197)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
***

**Comment by alectogeek** [comment]
Yeah, I have already searched for the problem. I'm fighting it almost for a month, but still can't figure out what is wrong and why it is occurring.

**Comment by jesphinpt** [comment]
I am also facing the error. Any solution for this. I am getting this error only on the Samsung modals.

**Comment by coob** [comment]
I'm suffering from similar issues with a Unity app which has a built-in webview. Has somebody found a solution? Please, help!

`backtrace:
  #00  pc 0x0000000002fffb92  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #01  pc 0x00000000031d71f1  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #02  pc 0x00000000031d75d3  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #03  pc 0x00000000031c5a2b  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #04  pc 0x00000000031c5043  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #05  pc 0x00000000031c4f51  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #06  pc 0x0000000002cb79b1  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #07  pc 0x0000000002cb78c5  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #08  pc 0x0000000002d3e953  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #09  pc 0x0000000002d3e51b  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #10  pc 0x0000000002d3e29f  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #11  pc 0x0000000002d3e201  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #12  pc 0x0000000002ca86ad  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #13  pc 0x0000000002ca8647  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #14  pc 0x0000000002ca8601  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #15  pc 0x0000000001cdb45f  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #16  pc 0x0000000000da3d33  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #17  pc 0x0000000000da3e11  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #18  pc 0x0000000001cdb45f  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #19  pc 0x0000000000da406f  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #20  pc 0x0000000000da44cb  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #21  pc 0x0000000000d9bda1  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #22  pc 0x0000000000d9af8f  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #23  pc 0x0000000000da0b2b  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #24  pc 0x0000000000d95e87  /data/app/~~hOtTv8IKicf9-gOvZugApg==/com.google.android.trichromelibrary_519513630-iAfGXzbj3tB_k8zzcmPZXg==/base.apk!libmonochrome.so
  #25  pc 0x0000000000002545  /system/lib/libwebviewchromium_plat_support.so (android::(anonymous namespace)::draw_gl(int, void*, android::uirenderer::DrawGlInfo const&)+228)
  #26  pc 0x00000000002fca53  /system/lib/libhwui.so (android::uirenderer::WebViewFunctor::drawGl(android::uirenderer::DrawGlInfo const&)+34)
  #27  pc 0x00000000002de155  /system/lib/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+1908)
  #28  pc 0x0000000000355291  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+44)
  #29  pc 0x000000000057dabf  /system/lib/libhwui.so (SkGpuDevice::drawDrawable(SkDrawable*, SkMatrix const*, SkCanvas*)+206)
  #30  pc 0x00000000002ac7bb  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+662)
  #31  pc 0x00000000002c3e39  /system/lib/libhwui.so (android::uirenderer::$_24::__invoke(void const*, SkCanvas*, SkMatrix const&)+44)
  #32  pc 0x00000000002ac7d7  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+690)
  #33  pc 0x00000000002c3e39  /system/lib/libhwui.so (android::uirenderer::$_24::__invoke(void const*, SkCanvas*, SkMatrix const&)+44)
  #34  pc 0x00000000002ac7ef  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+714)
  #35  pc 0x00000000002c3e39  /system/lib/libhwui.so (android::uirenderer::$_24::__invoke(void const*, SkCanvas*, SkMatrix const&)+44)
  #36  pc 0x00000000002ac7d7  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+690)
  #37  pc 0x00000000002c3e39  /system/lib/libhwui.so (android::uirenderer::$_24::__invoke(void const*, SkCanvas*, SkMatrix const&)+44)
  #38  pc 0x00000000002ac7ef  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+714)
  #39  pc 0x00000000002c3e39  /system/lib/libhwui.so (android::uirenderer::$_24::__invoke(void const*, SkCanvas*, SkMatrix const&)+44)
  #40  pc 0x00000000002ac7d7  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+690)
  #41  pc 0x00000000002e33bd  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrameImpl(SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, SkCanvas*, SkMatrix const&)+488)
  #42  pc 0x00000000002e30c9  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+92)
  #43  pc 0x00000000002e0fed  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+272)
  #44  pc 0x00000000002e7baf  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+974)
  #45  pc 0x00000000002e93e7  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+458)
  #46  pc 0x00000000002dc0ff  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+162)
  #47  pc 0x00000000002f33d1  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72)
  #48  pc 0x000000000000ee85  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+168)
  #49  pc 0x000000000000e9cd  /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+256)
  #50  pc 0x00000000000aaf33  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
  #51  pc 0x00000000000642e3  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)`

**Comment by malbolged** [comment]
any updates ?
