### ISSUE TITLE
[Web support] Member not found: 'InAppWebViewController.setWebContentsDebuggingEnabled'

### ISSUE THREAD

**Issue by jpsarda** [pichillilorenzo/flutter_inappwebview#1264]
I'm aware the web support is not yet announced, but I'm testing the developer branch, so I guess I could submit this isssue.
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       3        |
| Plugin version       |       developer branch        |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

This line of code doesn't compile for web :
`await InAppWebViewController.setWebContentsDebuggingEnabled(true);`

## Images   
![Screenshot 2022-07-28 at 23 48 21](https://user-images.githubusercontent.com/517839/181643319-5bd4453b-741e-48e5-a95f-1f8d006ceda6.png)

**Comment by pichillilorenzo** [comment]
The new version `6.0.0` has been released now!
You can't use methods that aren't supported on the Web platform!
Check the code docs if the method you want to use is supported or not on web and use the `kIsWeb` flutter constant, for example:
```dart
if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
    await InAppWebViewController.setWebContentsDebuggingEnabled(true);
}

// ...

InAppLocalhostServer localhostServer = new InAppLocalhostServer(documentRoot: 'assets');
if (!kIsWeb) {
    await localhostServer.start();
}
```
