### ISSUE TITLE
[web support] web_support.js: Failed to load resource.

### ISSUE THREAD

**Issue by jpsarda** [pichillilorenzo/flutter_inappwebview#1265]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         3      |
| Plugin version       |        develop branch       |
| Android version      |               |
| iOS version          |               |

| Xcode version        |               |

Device information: 

## Description

I'm testing the inappwebview for web support. In the readme it's says to add in the web/index.html the script web_support.ks which I did like this :
![Screenshot 2022-07-29 at 00 24 27](https://user-images.githubusercontent.com/517839/181647404-b22035d7-bd66-45fb-ab8b-fbf174032d1a.png)

But when I execute the app on chrome, I get an error in the javascript console log of chrome :
`web_support.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)`

## Images   
![Screenshot 2022-07-29 at 00 21 30](https://user-images.githubusercontent.com/517839/181647096-52283489-91c1-45e4-a35e-9d2623930926.png)

**Comment by jpsarda** [comment]
The problem is solved, I had to remove the flutter_inappwebview 5.4.3+7 package from local cache, despite having removed it from my pubspec and replaced it by flutter_inappwebview developer branch on git, when building for web, flutter was still using the assets from the flutter_inappwebview 5.4.3+7.
So after removing flutter_inappwebview 5.4.3+7 from the cache, and executing `flutter pub get`, it worked.

**Comment by pichillilorenzo** [comment]
Use this to add the `web_support.js` file:
```html
<script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
```

**Comment by Shiba-Kar** [comment]
> Use this to add the `web_support.js` file:
> 
> ```
> <head>
>   
>     <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
>   
> </head>
> ```

Same error still on latest one .

**Comment by sahilsmartq** [comment]
@pichillilorenzo 
Failed to load resource: the server responded with a status of 404 (Not Found)
time2eat-v2:70 Refused to execute script from 'http://localhost:64765/assets/packages/flutter_inappwebview_web/assets/web/web_support.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Inside Head:

 <script type="application/javascript"
            src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
            defer></script>
Inside Body:
<script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: "/time2eat-v2/main.dart.js",
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
          serviceWorkerUrl: "/time2eat-v2/flutter_service_worker.js",
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });

</script>

**Comment by annng** [comment]
> Use this to add the `web_support.js` file:
> 
> ```
> <head>
>   
>     <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
>   
> </head>
> ```

did the web_support.js should be generated? because I cannot find the file in my directory
