### ISSUE TITLE
[WebView-IOS] Touch delay 300ms.

### ISSUE THREAD

**Issue by manle93** [pichillilorenzo/flutter_inappwebview#1268]
## Environment

**Flutter version: 3.0.5
**Plugin version:**  flutter_inappwebview: ^5.4.3+7
**iOS version: deployment target 12
**Xcode version: 13.4.1
**Device information:**  Any IOS devices

## Description

**
- Currently I use flutter inappwebview on to my app. The problem is new touch is only recognize after 300ms (or 500ms , I guest). When touch fast it will not recognize. My website I embbed is work normally on android and browsser.** 

**Is there a feature of IOS or anyway to config it on IOS?

**Comment by manle93** [comment]
I was try on native WKWebview and its work normally. TOuch was recognized!

**Comment by manle93** [comment]
Any suggestion for me? :( Really bad UX on IOS

**Comment by harryhjsh** [comment]
Has anyone found a solution to this? 

Think it's related to this: https://webkit.org/blog/5610/more-responsive-tapping-on-ios/ 
It seems like WebKit is happy to not try and use double-tap to zoom when those meta tags are set, and this is the case in stock Safari. 

It doesn't behave in the same way in an InAppWebView, though. I've also tried setting `supportZoom: false` but this hasn't made a difference. Is there a gesture handler I can set to work around this, perhaps?

**Comment by JoaaoVerona** [comment]
+1. Not even `meta width=device-width` nor `touch-action: manipulation` works.

**Comment by SangHunShin** [comment]
Is there any solution yet?

**Comment by harryhjsh** [comment]
Has anyone made any progress on this?

**Comment by JoaaoVerona** [comment]
After some digging, this seems to be caused by [this issue](https://github.com/flutter/flutter/issues/94325). So, not even related to the "slow tap delay" from Safari WebKit at all, but caused by Flutter's handling of gestures between native/platform views and their own UI kit's views.

Didn't find a proper solution yet.

**Comment by AlexMatovnikov** [comment]
+1 такая же проблема!

**Comment by JoaaoVerona** [comment]
@swordyy7 published a fix on https://github.com/pichillilorenzo/flutter_inappwebview/issues/216.

To anyone else who wants to try this fix, I just published a fork of flutter_inappwebview.

- `flutter pub remove flutter_inappwebview`
- `flutter pub add flutter_inappwebview_fix_iostouchdelay`
- Update your imports from `flutter_inappwebview` to `flutter_inappwebview_fix_iostouchdelay`, example:
  - From: `import "package:flutter_inappwebview/flutter_inappwebview.dart";`
  - To: `import "package:flutter_inappwebview_fix_iostouchdelay/flutter_inappwebview_fix_iostouchdelay.dart";`

The forked library is listed on pub.dev [here](https://pub.dev/packages/flutter_inappwebview_fix_iostouchdelay), and the source code is [here](https://github.com/Skiley/flutter_inappwebview_fix_iostouchdelay).

Hope this helps someone. :)

**Comment by andreasgangso** [comment]
Adding the `FlutterPlatformViewGestureRecognizersBlockingPolicyWaitUntilTouchesEnded` policy seems to fix this in a less hacky way, but it shares the same tradeoffs as the other solutions mentioned above, which is that gestures get passed through to the webview even if you put opaque widgets on top of the webview.

I've created a PR (#1665) which adds a flag `preventGestureDelay` which is off by default, but you can optionally enable it to use a view with the "WaitUntilTouchesEnded" policy.

**Comment by deekshithdv** [comment]
Hello there!

I am also facing the same issue. I have a page where I need to select multiple options one after the other. I can select options but can't select them fast.

I guess this is due to the touch response delay. If anyone can help me to solve this issue, it would be great.

Thanks

**Comment by Codewealth** [comment]
Why is this closed? This issue still exists.. Has there been any update on this? This issue is a significant performance downgrade. You have to wait around 300-500ms before touch is re-enabled, which creates a terrible scrolling experience. For example, if you tap on a button and then want to immediately scroll, you can't—the screen is locked until you touch again. It's 2024; this should have been fixed by now. There are numerous complaints online about this issue.

Please, someone, provide a fix for this.
