### ISSUE TITLE
Scroll jank on iOS when keyboard opened in certain layout

### ISSUE THREAD

**Issue by Amareis** [pichillilorenzo/flutter_inappwebview#1271]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        3.0.5       |
| Plugin version       |      develop branch    |
| Android version      |      -         |
| iOS version          |       any from 12 to 15        |
| Xcode version        |        latest       |

Device information: 
iPhone 6+ (real)
iPhone 13 (simulator)

## Description

Given such layout:
a) Webview is inside safe area (just like in repo example)
b) body and html is overflow: hidden and height: 100% (so it should be resized when keyboard is opened)
c) !!! There is input in bottom part of screen (so it will be hidden by keyboard)

**Expected behavior:** 
Click on input with keyboard opening should just resize window with proper layout changes.

**Current behavior:** 
There is pretty strange jank, video attached.

Size of this jank is related to position of input - the more input in keyboard zone, the bigger jank is. Pretty sure it's related to standard safari behavior of scrolling input into view on focus.

## Steps to reproduce

1. In develop branch, create `scroll-bug.html` in `example/assets` with such content: 
```
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }

        body {
            position: relative;
            background: green;
        }

        #header {
            background: red;
            font-size: 30px;
            top: 0;
            left: 0;
            right: 0;
        }

        #input {
            position: absolute;
            font-size: 30px;
            bottom: 0;
            left: 0;
            right: 0;
        }
    </style>
</head>
<body>
<div id="header">Header</div>
<input id="input"/>
</body>
</html>
```
3. Replace initialUrlRequest with `initialFile: "assets/scroll-bug.html"` in `in_app_webiew_example.screen.dart`
5. Start app on iPhone, then click on input

## Images   

https://user-images.githubusercontent.com/4806617/182839146-479b7489-4724-46d7-b0a6-ca1e1c791ecf.mov

## Additional
There is similar bug in flutter webview widget: https://github.com/flutter/flutter/issues/98090
Also may be related: https://github.com/flutter/flutter/issues/105687

**Comment by Amareis** [comment]
Currently I just fork repo and disable `onScrollChanged` at all, and Instead just make:
```
public func scrollViewDidScroll(_ scrollView: UIScrollView) {
    scrollView.contentOffset = CGPoint(x: 0, y: 0)
}
```

And all is working good. For our app it's perfectly ok, since it is SPA with custom scroll logic, but there should be some more general solution, I think.

**Comment by RMatushkin** [comment]
Any updates here?
