### ISSUE TITLE
通信不能自定义桥梁名称

### ISSUE THREAD

**Issue by cleanown** [pichillilorenzo/flutter_inappwebview#1285]
目前在InAppWebView使用addJavaScriptHandler上，web端需window.flutter_inappwebview.callHandler('myHandlerName',...something）进行通信，可否自定义桥梁关键字（flutter_inappwebview   ->   company_name），如：window.company_name.callHandler('myHandlerName',...something），届时使用该框架封装好，对外文档不会那么明显用的什么框架

**Comment by hefei314** [comment]
add UserScript like this:
```
const myHandlerName= (...args) => window.flutter_inappwebview.callHandler('myHandlerName', ...args)
window.myCustomObj = { myHandlerName: myHandlerName }
```
then you can call as `window.myCustomObj.myHandlerName()`

**Comment by cleanown** [comment]
thank you! Is a good way to use!
but I dont want developer know we used inappwebview frame at develop. can I change way in flutter to use?
