### ISSUE TITLE
Xcode 14 failed to compile due to a swift file annotation

### ISSUE THREAD

**Issue by davidAg9** [pichillilorenzo/flutter_inappwebview#1287]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   3.0.5            |
| Plugin version       |   >= 5.4.2+1             |
| Android version      |               |
| iOS version          |    15.5           |
| Xcode version        |  14             |

Device information: 

## Description

**Expected behavior:** 
To compile and build my app successfully 
**Current behavior:** 
Build failure 
## Steps to reproduce

1. The environment sdk in my pub spec.yaml has a range of 
`environment:
  sdk: ">=2.7.0 <3.0.0"`

## errorMessage
`Error output from Xcode build:
/Users/daveagyakwa/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.2+1/ios/Classes/Types/UserScript.swift:13:6: error: stored properties cannot be marked potentially unavailable with '@available'
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
Error launching application on Dave’s iPhone.`

**Comment by combi-35** [comment]
Can also confirm this issue with `iOS 16.0` installed.

**Comment by thilojaeggi** [comment]
Same issue here, compiles fine on CI (Codemagic) though, so this is also related to Xcode 14 I think?

**Comment by akshayApplore** [comment]
Same here.

**Comment by daironigr** [comment]
Same here, any solution?

**Comment by bcmehdi8** [comment]
the issue start appearing after upgrading to Xcode 14

**Comment by GregoryConrad** [comment]
This is definitely an issue with upgrading to Xcode 14; see here: https://stackoverflow.com/questions/41904724/using-available-with-stored-properties

**Comment by digit81** [comment]
PR is waiting to fix this issue:
https://github.com/pichillilorenzo/flutter_inappwebview/pull/1238

**Comment by j-ixcayau** [comment]
To me works change 13 to 14 in podfile

platform :ios, '14.0'

**Comment by jeff-odopass** [comment]
Downgrading xCode from version 14.0 to previous version 13.4.1 also fix the issue, and looks like a better option according to me as some users still use IOS < 14.  
Simply downnload whatever version of xCode you want, install it, and then in xCode > Preferences > Locations select the desired version in the bottom dropdown.

Hope it helps

**Comment by daironigr** [comment]
This solution works for me 👌🏻
👉🏻 [https://stackoverflow.com/a/73699790/13821080](https://stackoverflow.com/a/73699790/13821080)

> Update version in Podfile platform :ios, '14.0' 
> Reset pods cd ios && rm -rf Pods/ Podfile.lock && pod install --repo-update
