### ISSUE TITLE
Videos not visible on ios

### ISSUE THREAD

**Issue by woutervanwijk** [pichillilorenzo/flutter_inappwebview#1289]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  3.0.5             |
| Plugin version       |  5.4.3+7             |
| iOS version          |         15      |
| Xcode version        |         13.4.1      |

Device information: All ios

## Description

**Expected behavior:** 
Go to e.g. https://www.rtlboulevard.nl/video/tv-fragmenten/video/5328092/snelle-reageert-koeltjes-op-verrassing-komt-misschien-niet or https://www.rtlboulevard.nl/video/tv-fragmenten/video/5328092/snelle-reageert-koeltjes-op-verrassing-komt-misschien-niet

**Current behavior:** 
No video shown

It can be a special situation on this site, but in other apps using the sfsafaribrowser view, it works normally. But not in this plugin or the webview_flutter plugin (also filed there https://github.com/flutter/flutter/issues/109939 )

## Steps to reproduce

import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late InAppWebViewController webViewController;
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      ));

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            bottomSheet: Row(children: [
              TextButton(
                  child: const Text('rtlnieuws'),
                  onPressed: () {
                    webViewController.loadUrl(
                        urlRequest: URLRequest(
                            url: Uri.parse(
                                'https://www.rtlnieuws.nl/nieuws/video/video/5328094/spannende-minuten-kinderen-vast-attractie-hellendoorn')));
                  }),
              TextButton(
                child: const Text('rtlblv'),
                onPressed: () => webViewController.loadUrl(
                    urlRequest: URLRequest(
                        url: Uri.parse(
                            'https://www.rtlboulevard.nl/video/tv-fragmenten/video/5328092/snelle-reageert-koeltjes-op-verrassing-komt-misschien-niet'))),
              ),
            ]),
            body: InAppWebView(
              onWebViewCreated: (InAppWebViewController controller) {
                webViewController = controller;
              },
            )));
  }
}

## Images   
![Simulator Screen Shot - iPhone 5s - 2022-08-21 at 13 22 27](https://user-images.githubusercontent.com/480348/185788588-4179be3d-778f-485d-95bb-96bbaff9ff94.png)

**Comment by woutervanwijk** [comment]
By the way, this also happens with Twitter embeds on websites! That's quite something. No video in Flutter Webview for this url: https://www.vrt.be/vrtnws/nl/2022/09/26/protest-dagestan/ 
In the Swift app, it just works

**Comment by flutter-clutter** [comment]
@woutervanwijk 
I am experiencing the very same issue! To me, it happens for youtube videos as well if I embed them into my website. Example: https://www.youtube.com/embed/-r2FX7E_b-Q?controls=1&loop=0&showinfo=0&modestbranding=1&rel=0&modestbranding=1&disablekb=1&autoplay=1&playsinline=0

Have you found a workaround?

**Comment by flutter-clutter** [comment]
An update to `5.4.4+2` hasn't led to any better results.

**Comment by woutervanwijk** [comment]
> Have you found a workaround?
Nope!

Here is the same issue for webview_flutter btw: https://github.com/flutter/flutter/issues/109939
