### ISSUE TITLE
flutter_inappbrowser/InAppBrowserFlutterPlugin.h' file not found

### ISSUE THREAD

**Issue by twopai** [pichillilorenzo/flutter_inappwebview#129]
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/fkkj_wjdtf/Project/flutter/colect/twopai/twopai/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'flutter_inappbrowser/InAppBrowserFlutterPlugin.h' file not found
    #import <flutter_inappbrowser/InAppBrowserFlutterPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by konstantin-mohin** [comment]
@twopai 
same

**Comment by pichillilorenzo** [comment]
Did you are using the latest version of the plugin??
However try to clean the project and run `pod install` inside the `ios` folder
