### ISSUE TITLE
crash InAppWebViewController.reload(in_app_webview_controller.dart:1301) [Android]

### ISSUE THREAD

**Issue by ttb-inc** [pichillilorenzo/flutter_inappwebview#1296]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       3.0.5        |
| Plugin version       |       5.4.3+7        |
| Android version      |       9, 10, 11, 12        |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 
There seems to be a crash in the background.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: MissingPluginException(No implementation found for method reload on channel com.pichillilorenzo/flutter_inappwebview_8). Error thrown null.
       at MethodChannel._invokeMethod(platform_channel.dart:165)
       at InAppWebViewController.reload(in_app_webview_controller.dart:1301)

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   
<img width="865" alt="스크린샷 2022-08-30 오후 1 56 09" src="https://user-images.githubusercontent.com/59724931/187352842-78d67347-8f6b-446b-acc1-1ccd43b514ce.png">
<img width="865" alt="스크린샷 2022-08-30 오후 1 56 24" src="https://user-images.githubusercontent.com/59724931/187352857-9a3255e4-2678-411e-88f5-f872720fba6d.png">
<img width="865" alt="스크린샷 2022-08-30 오후 1 56 48" src="https://user-images.githubusercontent.com/59724931/187352868-64e75727-6f52-4d6f-877c-95d56cf704d1.png">
<img width="843" alt="스크린샷 2022-08-30 오후 1 57 11" src="https://user-images.githubusercontent.com/59724931/187352880-394f04ec-6b78-4ead-933d-ba870ba8e33a.png">

------

Please let me know if I am using the plugin wrong or if there is a workaround.
Thank you.

**Comment by tomsun** [comment]
same in 6.0.0-beta.22 with iOS

**Comment by GuillaumeDgr** [comment]
Any update on this pls?

**Comment by TJRoger** [comment]
we run into the same problem in  6.0.0-beta.22. Is it fixed?

**Comment by 539863010** [comment]
Has this problem been resolved? I also encountered this issue in version 5.8.0

`
E/flutter (20973): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method reload on channel com.pichillilorenzo/flutter_inappwebview_3)
E/flutter (20973): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (20973): <asynchronous suspension>
E/flutter (20973): #1      InAppWebViewController.reload (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1341:5)
E/flutter (20973): <asynchronous suspension>
E/flutter (20973): `

**Comment by Letalus** [comment]
Nop, it does still exist
