### ISSUE TITLE
ios mic permission

### ISSUE THREAD

**Issue by MahmoudMamdoouh** [pichillilorenzo/flutter_inappwebview#1297]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       3.0.5      |
| Plugin version       |     5.4.3+7      |
| Android version      |               |
| iOS version          |         12.5      |
| Xcode version        |         13.4.1      |

Device information: 

## Description
i cant use the mic or camera
mic permission not given and doesn't ask for it 

**Expected behavior:** 
mic permission popup to give to work

**Current behavior:** 
it refuses the permission without asking or it doesn't ask

**Comment by vlad-buhaescu** [comment]
Hi, make sure you use permission handler package and follow the setup guide from https://pub.dev/packages/permission_handler
It needs adding code in the pod file for iOS
