### ISSUE TITLE
 'flutter_inappbrowser/flutter_inappbrowser-Swift.h' file not found

### ISSUE THREAD

**Issue by shijianzhong** [pichillilorenzo/flutter_inappwebview#130]
ng/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappbrowser-1.2.1/ios/Cl
    asses/InAppBrowserFlutterPlugin.m:19:9: fatal error:
    'flutter_inappbrowser/flutter_inappbrowser-Swift.h' file not found
    #import <flutter_inappbrowser/flutter_inappbrowser-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by akshatjagga** [comment]
Hi,

Did you find how to fix his?

Thanks

**Comment by pichillilorenzo** [comment]
Try to clean the project and install the latest version of this plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.

**Comment by dudizimber** [comment]
I have the same problem...

flutter_inappwebview: ^2.0.1+1
Xcode 11.3

**Comment by andre-arsenault** [comment]
I'm having the same problem:

```
/Users/andre/Development/flutter/.pub-cache/git/flutter_inappwebview-9c7ac0da8f01ceb40430da58397bdb31968ca5b1/ios/Classes/InAppWebViewFlutterPlugin.m:19:9: fatal error: 'flutter_inappwebview/flutter_inappwebview-Swift.h' file not found
#import <flutter_inappwebview/flutter_inappwebview-Swift.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I am using this plugin (direct from `master`) as a work-around for [this issue](https://github.com/flutter/flutter/issues/25767), as mentioned [here](https://github.com/flutter/flutter/issues/25767#issuecomment-566700162). This solves the Android crash, but now I can't build on iOS!

My Flutter project is Swift-based for iOS.

Any solutions out there?

**Comment by VeeTsien** [comment]
Same issue here. This is the error message from Xcode 11.2:

`/Users/veratsien/Development/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppWebViewFlutterPlugin.m:19:9: 'flutter_inappwebview/flutter_inappwebview-Swift.h' file not found`

Any troubleshooting we can try out?

**Comment by MeshkaniMohammad** [comment]
same here

**Comment by SimonRijn** [comment]
Same here

**Comment by LailaiMaster** [comment]
Same here

**Comment by LailaiMaster** [comment]
I solved
1.your project/ios/Podfile use_frameworks! ,run .
`
...
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pod
...
`
If this problem occurs：
"target has transitive dependencies that include statically linked binaries"
 2.find this library，pod/xxx.podspec ，add   “s.static_framework=true”
`A new Flutter plugin.
                       DESC
  s.homepage         = 'http://lllgm.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => '527639282@qq.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'AlipaySDK-iOS'
  s.platform = :ios, '8.0'
  s.static_framework=true #add it
`

**Comment by VeeTsien** [comment]
Adding `use_frameworks!` and `use_modular_headers!` worked!!!

Thank you thank you thank you!!! @LailaiMaster

**Comment by LailaiMaster** [comment]
@VeeTsien No thanks 😁

**Comment by nehamallama** [comment]
@LailaiMaster first step worked for me thanks :)

**Comment by AAChartModel** [comment]
Add  `use_frameworks!` into your Podfile , Just like this. 



![image](https://user-images.githubusercontent.com/16357599/108588065-349c2580-7392-11eb-95b2-2d182bbec83f.png)


That's all. Thanks @LailaiMaster
