### ISSUE TITLE
 packagename conflict between flutter_inappwebview and flutter_inappwebview_quill

### ISSUE THREAD

**Issue by GerJeffrey** [pichillilorenzo/flutter_inappwebview#1306]
After I update my flutter to 3.0 then error happened:
ERROR:build/app/intermediates/transforms/APMSPlugin/release/119.jar: R8: Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times: build/app/intermediates/transforms/APMSPlugin/release/119.jar:com/pichillilorenzo/flutter_inappwebview/BuildConfig.class, ycapp/build/app/intermediates/transforms/APMSPlugin/release/128.jar:com/pichillilorenzo/flutter_inappwebview/BuildConfig.class

**I find in my pubspec.lock:**
flutter_inappwebview:
    dependency: transitive
    description:
      name: flutter_inappwebview
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "5.4.3+7"
  flutter_inappwebview_quill:
    dependency: transitive
    description:
      name: flutter_inappwebview_quill
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "5.4.6"

**### And I check the flutter build intermediates BuildConfig
the two packages has the same package name:**
package com.pichillilorenzo.flutter_inappwebview;

so conflicts happened.
How Do I Resolve This Problem, thanks!

**Comment by definitelyme** [comment]
Any update on this? @pichillilorenzo

**Comment by pichillilorenzo** [comment]
Just use `flutter_inappwebview`. It has been updated to support iOS 16 and Android 33
