### ISSUE TITLE
How to make webview show prompt to save username password after login success

### ISSUE THREAD

**Issue by thanhpd56** [pichillilorenzo/flutter_inappwebview#1311]
Hi, 
I try to use webview for users to login. However, after the login success it does not show-up option to save username/password for later login. That means users need to type username/password every login times.
Is it possible to show the option of saving login info? If yes how can I implement it?
Thanks in advanced.

**Comment by fattiger00** [comment]
You can use js scripts to capture the username and password when the user taps the login button. 
example: [https://github.com/CustedNG/CustedNG/blob/material/lib/ui/webview/plugin_login.dart](URL)
