### ISSUE TITLE
hideDefaultSystemContextMenuItems not working, onCreateContextMenu not triggered on iOS 16

### ISSUE THREAD

**Issue by imchlorine** [pichillilorenzo/flutter_inappwebview#1315]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      3.0.1         |
| Plugin version       |        5.4.3+7       |
| Android version      |         n/a      |
| iOS version          |     16          |
| Xcode version        |      14.0         |

Device information: 

## Description

**Expected behavior:** 

`hideDefaultSystemContextMenuItems: true
`  System context menu items should be hided on iOS 16
`onCreateContextMenu` should be triggered after long press

**Current behavior:** 
`hideDefaultSystemContextMenuItems: true
`not working on iOS 16
`onCreateContextMenu` is not triggered with info `[Text] Using UIMenuController to add items into text menus is deprecated. Please implement the UITextInput API editMenuForTextRange:suggestedActions: instead.`

**Comment by zjyjstgbc** [comment]
oh

**Comment by filipenanclarez** [comment]
Same here ... 

After update IOS, get the message:

`[Text] Using UIMenuController to add items into text menus is deprecated. Please implement the UITextInput API editMenuForTextRange:suggestedActions: instead.`

Here, still not found any workaround yet.

**Comment by uc-vrm** [comment]
I am also facing the same issue if anyone find any solution please tell me too.

**Comment by dmitry-grin** [comment]
Hi there, 

`hideDefaultSystemContextMenuItems: true`

does not hide default options of Copy/Search etc on iOS 17.0

Could you verify?

**Comment by colarking** [comment]
HI there.
i have this same issue on ios 17.0
hideDefaultSystemContextMenuItems: true
this is not working in
flutter_inappwebview: ^5.8.0
anyone know how to fix this?
