### ISSUE TITLE
Render process (11786)'s crash wasn't handled by all associated webviews, triggering application crash. 

### ISSUE THREAD

**Issue by huangsir0** [pichillilorenzo/flutter_inappwebview#1325]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     3.3.0          |
| Plugin version       |   5.4.3+7            |
| Android version      |    Android 10,level 29           |
| iOS version          |               |
| Xcode version        |               |

## Stacktrace/Logcat 

``` dart
09-19 14:04:50.994 12140 12140 F chromium: [FATAL:crashpad_client_linux.cc(561)] Render process (17621)'s crash wasn't handled by all associated webviews, triggering application crash.

```
## Possible Cause

https://www.jianshu.com/p/29a8dce65634

**Comment by DevWiz96** [comment]
I'm having the exact same problem! Been stuck with for a week, is there any solution ?

**Comment by androideveloper** [comment]
onRenderProcessGone method should be implemented by all webviews in the app, otherwise once webview process crashes, it will crash the app
https://developer.android.com/reference/android/webkit/WebViewClient#onRenderProcessGone(android.webkit.WebView,%20android.webkit.RenderProcessGoneDetail)

**Comment by pakeng** [comment]
@huangsir0 Are you have any solution?

**Comment by royston-c** [comment]
@androideveloper Thanks for the hint on the `onRenderProcessGone` override. 

I have implemented this method via `androidOnRenderProcessGone` in this plugin (on v5, I think it has changed in v6). Where I try to recreate the `InAppWebView` via a new `Key`. 

However, I still see crashes with the error: `[FATAL:crashpad_client_linux.cc(732)] Render process (2370)'s crash wasn't handled by all associated  webviews, triggering application crash.` in the Play Console.

Example implementation:

```dart
    String inAppWebViewKeyString = Uuid().v4().toString();
    Uri? currentUri; // tracked via the controller

    final webview = InAppWebView(
      key: Key(inAppWebViewKeyString),
      initialUrlRequest: URLRequest(
        url: currentUri,
      ),
      initialOptions: InAppWebViewGroupOptions(
        android: AndroidInAppWebViewOptions(
          useOnRenderProcessGone: true,
        ),
      ),
      androidOnRenderProcessGone: (controller, details) {
        // reload the creashed webview
        setState(() {
          inAppWebViewKeyString = Uuid().v4().toString();
        });
      },
    );
```

Any ideas? I'd really appreciate any points anyone might have :)

**Comment by androideveloper** [comment]
Yor crashing webview might come from another internal dependency/sdk that you don't control.
