### ISSUE TITLE
InAppBrowser: cookie problems with Android

### ISSUE THREAD

**Issue by micmar** [pichillilorenzo/flutter_inappwebview#1326]
Hello,
I am using   
Flutter 3.3.2
flutter_inappwebview: ^5.4.3+7
Android 12

with InAppBrowser.

**Expected behavior:** 
Setting app cookies with InAppBrowser will allow to fill an email field for both: iOS and Android platforms.

**Current behavior:** 
It works on iOS, not on Android.

I am using this code:

    var options = InAppBrowserClassOptions(
      crossPlatform: InAppBrowserOptions(
        hideToolbarTop: true,
        hideUrlBar: true,
      ),
      inAppWebViewGroupOptions: InAppWebViewGroupOptions(
        crossPlatform: InAppWebViewOptions(javaScriptEnabled: true),
      ),
      ios: IOSInAppBrowserOptions(
          presentationStyle: IOSUIModalPresentationStyle.PAGE_SHEET),
    );

    await webView.openUrlRequest(
      urlRequest: URLRequest(
        url: initialRoute,
      ),
      options: options,
    );

  And then I set cookies like this:

    CookieManager cookieManager = CookieManager.instance();

    await cookieManager.deleteAllCookies();

    await cookieManager.setCookie(
      url: Uri.parse(_myInitialRoute()),
      name: 'email',
      value: emailAddress,
      domain: _currentDomain(),   // << NOTE this line
    );

  The goal is to open a web view with an email address pre filled in.
  About the last line: I need to use this with iOS, otherwise the email will not be set.
  But as it is, this code DOES WORK with iOS.

  But if I move to Android I have a funny behaviour.
  I check cookies with following code:

    // get cookies
    List<Cookie> cookies =
        await cookieManager.getCookies(url: Uri.parse(_myInitialRoute()));

  If I keep this line:
        domain: _currentDomain(), 

  I will NOT get any cookie on Android.
  If I remove it then there will be the one cookie I set.

  Either case, even if the cookie is there, the email address is never pre-filled in on Android.

  Any clue about what is going on?
  Thanks,
  Mik

**Comment by davideravasi** [comment]
Hello, any update regarding this bug?

**Comment by davideravasi** [comment]
Hello, any update? I've seen in the answer https://github.com/pichillilorenzo/flutter_inappwebview/issues/1483 that there should be a way to make this work, can you confirm this?

**Comment by davideravasi** [comment]
Issue has been solved with: upgrading the library and using the full path in the URL when setCookies is called
We can close this issue (all users in this thread were working on the same product 👍 )

**Comment by aliazxs** [comment]
it is not working with me can someone please add more details?!!!
