### ISSUE TITLE
android WebView error: cannot find symbol       settings.setAppCacheEnabled(false);

### ISSUE THREAD

**Issue by ivangoluuk** [pichillilorenzo/flutter_inappwebview#1327]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by terry8204** [comment]
compiledsdk 33
flutter 3.3.2

**Comment by ivangoluuk** [comment]
> compiledsdk 33 flutter 3.3.2

it didn't work for me either

**Comment by ivangoluuk** [comment]
it could be? This happens when you use compilesdk 33 for Android

**Comment by pichillilorenzo** [comment]
Fixed starting from version `5.4.4`
