### ISSUE TITLE
An error occurs when using a specific intent

### ISSUE THREAD

**Issue by tranzal** [pichillilorenzo/flutter_inappwebview#1328]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       3.3.2        |
| Plugin version       |       ^5.4.3+7        |
| Android version      |       32        |
| iOS version          |               |
| Xcode version        |               |

Device information:  pixel_4 playstore android emulator

## Description

The next sentence is a translation sentence. 
When opening an intent of a specific type, we confirmed a situation in which the intent does not open. The self-confirmed thing is that the result of the channel.invokeMethod("shouldOverrideUrlLoading"... part of the InAppWebViewClient.java file is an error. It seems that the intent is not processed.

**Expected behavior:**  starting V3 app

**Current behavior:** error, FormatException: Invalid port (at character 18) 
                                      intent://%7B"CD":"17a62bbbb6350acf37bc18ed9a286e14","TK":"Z5hnMPf4ReKe8-jTP...

## Steps to reproduce

1. Excute an intent similar to "intent://%7B"CD":"17a62bbbb6350acf37bc18ed9a286e14","TK":"Z5hnMPf4ReKe8-jTP"
2. An error occurs

## Stacktrace/Logcat   

E/IAWebViewClient(19873): error, FormatException: Invalid port (at character 18)
E/IAWebViewClient(19873): intent://%7B"CD":"a72e9fb1222a89b258d62e152e286c62","TK":"DyNMSqhu-bLJMcaUr...
E/IAWebViewClient(19873):                  ^
I/chestertons.ay(19873): Background concurrent copying GC freed 154816(2895KB) AllocSpace objects, 76(3316KB) LOS objects, 49% free, 4822KB/9644KB, paused 8.517ms,73us total 201.484ms
E/FrameEvents(19873): updateAcquireFence: Did not find frame.
E/FrameEvents(19873): updateAcquireFence: Did not find frame.
W/System.err(19873): java.net.MalformedURLException: invalid port: "a72e9fb1222a89b258d62e152e286c62","TK":"DyNMSqhu-bLJMcaUr6J45gh0EYmYYHyhC3zLvb5iIDo=","LK":"3170971732885714458531799018726825261335175037699017379950691091211575550480097878711113392634904369829725091772318674534157285535518452422644171802439221","DT":"2022-09-20-17:10","TM":"15","CH":"dacs.wooricard.com:8886","CU":"https%3A%2F%2Fdacs.wooricard.com%3A8886%2Fwcrpay%2FCOM300001A.wcdo%3Bjsessionid%3DH3CUMcSpYrSvt5PicHvnpj9xAy5a9Yvit2gKlcy61smbiiFHbIg6lTLPZgYCTBxt.amV1c19kb21haW4vd2NycGF5MTE%3D%3FmemKey%3DC88510A3A2549E6A64B806A9F4ED7459BDA611EA58AD499595928AD63A4277A4E760CFA6C2FCAAFA21977D5ABF8696F70CBC4BD5788145279BA6EC3F659D3DE8D3052E1F9DE955EA6E68ED27DA98FC55991B293B25E603C541F880C92C900021873A73A372D84F055DCF31787AF6A9522F670205CB59BCBFF402E7BCAC8BAAB6BE2247227138BBB844F380A61C14845D12743EE72A6B91F829FB0373AEA36A723B9C9A6048CA618F23AD429725242EEF2DC94F26A4ECBAD5FF730EF924FDE235","SA":"https:
W/System.err(19873): 	at java.net.URL.<init>(URL.java:635)
W/System.err(19873): 	at java.net.URL.<init>(URL.java:498)
W/System.err(19873): 	at java.net.URL.<init>(URL.java:447)
W/System.err(19873): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewClient.shouldInterceptRequest(InAppWebViewClient.java:619)
W/System.err(19873): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewClient.shouldInterceptRequest(InAppWebViewClient.java:682)
W/System.err(19873): 	at A8.a(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:15)
W/System.err(19873): 	at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:2)
W/System.err(19873): Caused by: java.lang.IllegalArgumentException: invalid port: "a72e9fb1222a89b258d62e152e286c62","TK":"DyNMSqhu-bLJMcaUr6J45gh0EYmYYHyhC3zLvb5iIDo=","LK":"3170971732885714458531799018726825261335175037699017379950691091211575550480097878711113392634904369829725091772318674534157285535518452422644171802439221","DT":"2022-09-20-17:10","TM":"15","CH":"dacs.wooricard.com:8886","CU":"https%3A%2F%2Fdacs.wooricard.com%3A8886%2Fwcrpay%2FCOM300001A.wcdo%3Bjsessionid%3DH3CUMcSpYrSvt5PicHvnpj9xAy5a9Yvit2gKlcy61smbiiFHbIg6lTLPZgYCTBxt.amV1c19kb21haW4vd2NycGF5MTE%3D%3FmemKey%3DC88510A3A2549E6A64B806A9F4ED7459BDA611EA58AD499595928AD63A4277A4E760CFA6C2FCAAFA21977D5ABF8696F70CBC4BD5788145279BA6EC3F659D3DE8D3052E1F9DE955EA6E68ED27DA98FC55991B293B25E603C541F880C92C900021873A73A372D84F055DCF31787AF6A9522F670205CB59BCBFF402E7BCAC8BAAB6BE2247227138BBB844F380A61C14845D12743EE72A6B91F829FB0373AEA36A723B9C9A6048CA618F23AD429725242EEF2DC94F26A4ECBAD5FF730EF924FDE235","SA":"https:
W/System.err(19873): 	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:249)
W/System.err(19873): 	at java.net.URL.<init>(URL.java:630)
W/System.err(19873): 	... 6 more

**Comment by Woojin-Crive** [comment]
Are you using a payment solution? (korea PG)
I am suffering the same problem too.

URI parser throws exception while handling the url.
i wrapped the shouldOverrideUrlLoading with try catch and used native method channel(android) to handle the url.

**Comment by pichillilorenzo** [comment]
Schemes/Protocols that are different from something used by a webview (`http`, `https`, etc...), such as `intent://`, `tel:`, `whatsapp://` or `facebook://`, should be handled by your self, for example using the [url_launcher](https://pub.dev/packages/url_launcher) plugin.

**Comment by pichillilorenzo** [comment]
Released new version `6.0.0-beta.10` with new type `WebUri` to replace the `Uri` dart core type and fixed "java.net.MalformedURLException: invalid port:".
With `WebUri`, you have access to the raw string value used by the Uri parser.
So, if you need the unmodified string, use the `WebUri.rawValue` property.

For more details on how `WebUri` works, check the [WebUri Official docs](https://inappwebview.dev/docs/web-uri).
