### ISSUE TITLE
error UserScript.swift:13:6: error build: Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by hc2088** [pichillilorenzo/flutter_inappwebview#1331]
flutter_inappwebview: ^5.4.3+7

xcode 14.0

/Volumes/huc/myshared/opt/fvm/versions/3.3.1/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-5.4.3+7/ios/Classes/Types/UserScript.swift:13:6: error build: Stored properties cannot be marked potentially unavailable with '@available'

 ```
public class UserScript : WKUserScript {
    var groupName: String?
    @available(iOS 14.0, *)
    lazy var contentWorld: WKContentWorld = WKContentWorld.page
  
```

**Comment by pirrest** [comment]
Hello! We have the same issue that prevent s us to build our app.

**Comment by ybbond** [comment]
for temporary fix, you can follow the steps on https://github.com/pichillilorenzo/flutter_inappwebview/issues/1312#issuecomment-1245705493

**Comment by SalsabeelaHasan** [comment]
Here also!
any solution?
<img width="746" alt="Screen Shot 2022-09-27 at 4 07 02 AM" src="https://user-images.githubusercontent.com/62775384/192407838-b6bf1fde-6708-44f9-87d9-d09f969dac19.png">
