### ISSUE TITLE
Publish apk in google play got an issue 

### ISSUE THREAD

**Issue by clgg** [pichillilorenzo/flutter_inappwebview#1333]
is there anyone has the same issue
![image](https://user-images.githubusercontent.com/6767765/192187018-522e5ba4-e924-42c4-8823-222c957b9472.png)

searched in my app ,only found 
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/6767765/192187082-0464729f-f7ce-4f87-ae0d-bd6394a22540.png">

the path is "package com.pichillilorenzo.flutter_inappwebview.Util" getUnsafeOkHttpClient() .

**Comment by pichillilorenzo** [comment]
You can use version `5.4.4+3` where I removed `getUnsafeOkHttpClient`
