### ISSUE TITLE
120 frame flicker when load webview

### ISSUE THREAD

**Issue by wf1992** [pichillilorenzo/flutter_inappwebview#1335]
when I use 13pro max\ 14pro max to load webview, in high frame rate ,I get flicker shadow when webview scrolling . you can try it,
must appear！！hope you fix it。

**Comment by wf1992** [comment]
but when I use webview_flutter ,this donot appear. I checked the frame rate is bigger than 60.

**Comment by filipenanclarez** [comment]
> but when I use webview_flutter ,this donot appear. I checked the frame rate is bigger than 60.

whats is your version of flutter? i have same problem, and this gone after update to flutter 3.3.4

**Comment by wf1992** [comment]
Flutter  Channel stable, 3.0.2  ,when I update to  flutter 3.3.4 , I will comment the result

**Comment by wf1992** [comment]
nope，when I update to flutter 3.3.4, this also appears , good news is : flicker shadow is better, but it also appears

**Comment by pichillilorenzo** [comment]
Could you share a screen record of this issue please?

**Comment by wf1992** [comment]
https://user-images.githubusercontent.com/12962946/194693754-a1d9292e-ec28-4746-89fe-8e8404fb5623.MP4

env:
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

flutter_inappwebview: 5.4.4+3

**Comment by wf1992** [comment]
https://user-images.githubusercontent.com/12962946/194693851-fe938e48-db68-46d0-b458-0bb98f6b1354.MP4

when I zipped this video , the situation is not obvious

**Comment by wf1992** [comment]
13 pro max , did not limit iPhone high frame rate

**Comment by wf1992** [comment]
When you release your finger and webview scroll naturally, the situation happens

**Comment by wf1992** [comment]
this url contains lots of pictures ,so this happens. when url did not contains lots of pictures , may not appear

**Comment by wf1992** [comment]
> Could you share a screen record of this issue please?

hi , up stairs.

**Comment by pichillilorenzo** [comment]
I'm using a real iPhone 12 Pro and I don't have any problem with scroll:
https://user-images.githubusercontent.com/5956938/197167405-e65d8452-b346-4ae6-a20f-af7247cb8e83.mp4

Unfortunately, I don't have an iPhone 13 to test 120 frame refresh rate, but it may be something related to how Flutter native views are rendered.

**Comment by pichillilorenzo** [comment]
Also, check https://github.com/flutter/flutter/issues/90675
