### ISSUE TITLE
Plugin error causing the build to crash in iOS 14.0.1

### ISSUE THREAD

**Issue by csacchetti** [pichillilorenzo/flutter_inappwebview#1341]
this error prevents iOS 14.0.1 from doing the build

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
/Users/carlosacchetti/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/ios/Classes/Types/UserScript.swift:12:5

<img width="691" alt="Schermata 2022-09-28 alle 18 04 53" src="https://user-images.githubusercontent.com/46923349/192830043-bd45ff15-32f7-4b98-ad8b-77a78e1f587f.png">

**Comment by hemantbeast** [comment]
I can confirm this error causing build to not generate.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/10476066/192966619-7fae4c90-d77f-4523-83fb-7d2e2712786f.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/10476066/192966735-214374d7-b993-404b-abab-9ecb52556a71.png">

**Comment by xang555** [comment]
Same issue

**Comment by tim-eucalyptus** [comment]
Same issue for me too.

**Comment by choiks14** [comment]
same here

**Comment by haydgately** [comment]
Unfortunately, same here!

**Comment by johnkreagan** [comment]
Same here!

**Comment by jasonrlloyd** [comment]
same here

**Comment by pichillilorenzo** [comment]
Released new version `5.4.3+8` with the fix

**Comment by johnkreagan** [comment]
Thank you @pichillilorenzo!
