### ISSUE TITLE
How to change text selection color?

### ISSUE THREAD

**Issue by RMatushkin** [pichillilorenzo/flutter_inappwebview#1346]
Faced a problem in that I can't find an option on how to change the text selection color, it always shows some kind of green color:
<img width="210" alt="Screenshot 2022-10-04 at 15 31 10" src="https://user-images.githubusercontent.com/54648323/193820156-27e6c387-5fe5-4f46-a753-d26685ecb517.png">

Theme colors under MaterialApp don't help me:
<img width="557" alt="Screenshot 2022-10-04 at 15 33 31" src="https://user-images.githubusercontent.com/54648323/193820388-9f256f39-cd8f-41a1-bf95-05024f7d23cf.png">

**Comment by RMatushkin** [comment]
I've managed to find a solution by adding an item to styles.xml, here is an answer on StackOverflow: https://stackoverflow.com/a/65746919
`<item name="android:colorControlActivated">#YourColorString</item>`

It would be awesome to be able to set the color through `TextSelectionThemeData` according to Flutter documentation.

**Comment by pichillilorenzo** [comment]
Flutter Platform Views (such as `InAppWebView`) are native views **embedded** in the Flutter widgets tree.
They are not standard Flutter widgets, so things like `TextSelectionThemeData` won't work on them.
The only solution is to use something like you already did, in this case, setting the `colorControlActivated` style attribute.
