### ISSUE TITLE
iOS findNext function not work

### ISSUE THREAD

**Issue by qingzhu001** [pichillilorenzo/flutter_inappwebview#1347]
FindTextHighlightJS.swift 
line 45
"WKWEBVIEW_SEARCH_WORD_" + \(FIND_TEXT_HIGHLIGHT_SEARCH_RESULT_COUNT_JS_SOURCE)

line 159
var scrollTo = document.getElementById("\(JAVASCRIPT_BRIDGE_NAME)_SEARCH_WORD_" + idx);

Id not consistent

**Comment by pichillilorenzo** [comment]
Fixed with version `5.5.0`
