### ISSUE TITLE
useragent not work on release mode

### ISSUE THREAD

**Issue by ridz0n3** [pichillilorenzo/flutter_inappwebview#135]
Hi, 

im currently do the google login using my current backend,
i put the user agent like this,
`"userAgent": 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Mobile Safari/537.36',`
it working on debug mode, when in release mode, the browser return `403 - disallowed useragent` is there any solution to this problem?

Thanks

**Comment by do4Mother** [comment]
same problem

**Comment by pichillilorenzo** [comment]
Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.

**Comment by lawliet467** [comment]
> Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.

not work for me, please check it and hope your reply

**Comment by fif1973** [comment]
I just test on iOS (debug and release), it works.
The problem still exists on Androïd

**Comment by ariefaprilianto** [comment]
Not worked for me too, please @pichillilorenzo give your any advice.

**Comment by ariefaprilianto** [comment]
Somehow my InAppWebViewOptions values not passed through libraries constructor, is it possible that those values are being stripped?

**Comment by ariefaprilianto** [comment]
For my workarround, I try to give default value to the source constructor.

**Comment by vavramovski** [comment]
I fixed this problem by changing the default value of the userAgent in android version of the webview package.
This is the file
flutter_inappwebview-9c7ac0da8f01ceb40430da58397bdb31968ca5b1\**android**\src\main\java\com\pichillilorenzo\flutter_inappwebview\InAppWebView\InAppWebViewOptions.java

`  public String userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36";
`

**Comment by pichillilorenzo** [comment]
Fix available starting from the version `3.0.0`.
