### ISSUE TITLE
Login Popup is blocked

### ISSUE THREAD

**Issue by shameemreza** [pichillilorenzo/flutter_inappwebview#1353]
How can I enable the Login popup? I already enabled javaScriptCanOpenWindowsAutomatically and supportMultipleWindows, but still now getting it to work.

![processed-03778b1e-a7a7-452d-98b1-b79a2c401ef7_8WCe2pfo](https://user-images.githubusercontent.com/14240438/194765847-68dc77a7-20d6-4eac-87ac-2df17a4db826.jpeg)

`
I/flutter (20204): ---console---{message: Unsafe attempt to initiate navigation for frame with URL 'https://mywebsite.com/' from frame with URL 'https://embed.twitch.tv/?autoplay=false&channel=cryptoplus&muted=true&parent=mywebsite.com&referrer=https%3A%2F%2Fmywebsite.com%2F&theme=light'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.
I/flutter (20204): , messageLevel: 3}
`

Note: For privacy reasons, I have removed my website link and used mywebsite.com

Any guide to resolving this popup issue?

I appreciate any help you can provide.

**Comment by shameemreza** [comment]
I already searched, but I couldn't find anything that could resolve this issue.

**Comment by shameemreza** [comment]
I have resolved it.

**Comment by mthinh** [comment]
@shameemreza how could you resolve it ? Thank you
