### ISSUE TITLE
< 安卓.上传图片> 相机权限默认是禁止的。直接跳转到了相册。

### ISSUE THREAD

**Issue by dushiling** [pichillilorenzo/flutter_inappwebview#1356]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      3.0         |
| Plugin version       |       5.3.2        |
| Xcode version        |      13.3         |

## Description

1.相机权限默认是禁止的。直接跳转到相册。
2.开启相机权限，闪退。
3.授权被拒绝后，无法再弹出授权
4.无法直接跳转到相机拍照

##具体现象见下面本人文章记录
https://www.jianshu.com/p/bf0707988afc

##其他
不知最新版本修复此问题没有，若无，请辛苦修复下~

**Comment by dushiling** [comment]
The question is based on inAppWebiew
I didn't find the answer among the many existing questions

I think it will be more intuitive for you to say this differently, and I hope you can test it more:
< **Running on the iPhone, photos are uploaded with a picker box that separates the album from the camera; But when running on an Android phone, it goes straight to select File/Photo, no picker pops up** >

Details:
The same four I mentioned last time:
**1. Camera permission is disabled by default. Jump directly to the album.
2. Enable the camera permission and blink back.
3. After the authorization is rejected, the authorization cannot be displayed again
4. Unable to directly jump to the camera to take photos（Can be ignored）**
Detailed in my record article: https://www.jianshu.com/p/bf0707988afc

Test method:
You put a fixed url in the in_app_webiew_example.screen.dart class: **https://ant.design/components/upload-cn/**, and then respectively on the iphone and android mobile phone click the upload button to check the effect.

Problem:
Because of these problems, I had to change the source code and then put the plug-in into the project, which was very troublesome.

Expectations:
android works the same as iOS.
Select picker when the camera or album is selected. Authorization will pop up and you can operate after authorization.

Attached: 
ios rendering
![5481665485771_ pic](https://user-images.githubusercontent.com/13375221/195076434-2e274ae6-161b-4aa0-ac9d-0991ca92175a.jpg)

android rendering
![549_1665487427](https://user-images.githubusercontent.com/13375221/195078050-554a5272-d882-4828-8c2f-41b7f3844c8f.gif)

Enable camera permission and crash.
![550_1665488672](https://user-images.githubusercontent.com/13375221/195082653-b6df284e-7e2f-496f-aaff-0889cbfb8362.gif)

**Comment by pichillilorenzo** [comment]
To request permissions, such as camera and microphone, you need to use some other packages, such as [permission_handler](https://pub.dev/packages/permission_handler).
Example:
```dart
import 'package:permission_handler/permission_handler.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Permission.camera.request();
  await Permission.microphone.request();
  // ...
}
```

Implement the `androidOnPermissionRequest` event, for example:
```dart
androidOnPermissionRequest: (controller, origin, resources) async {
  return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
}
```

and add your specific `permissions` in your `AndroidManifest.xml` file, for example:
```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.VIDEO_CAPTURE" />
<uses-permission android:name="android.permission.AUDIO_CAPTURE" />
```

Also, starting with plugin version `5.5.0`, Android now have direct camera capture feature.
