### ISSUE TITLE
can't get cookie isSessionOnly

### ISSUE THREAD

**Issue by HajerWael** [pichillilorenzo/flutter_inappwebview#1357]
I'm trying to get session Cookies of a Webview  using **InAppwebview and CoookieManager** widget in my flutter App, it works fine in Android and IOS simulator but doesn't in IOS  real device .

**Here is my trial**

IOS version : +11 <br>

**Options :**<br>
sharedCookiesEnabled: true <br>
incognito: false <br>
```

build(BuildContext context) {
  var cookieObj = CookieManager();
  cookieObj.ios = IOSCookieManager();
  InAppWebView(
          initialOptions: InAppWebViewGroupOptions(
              ios: IOSInAppWebViewOptions(sharedCookiesEnabled: true),
              crossPlatform: InAppWebViewOptions(
                incognito: false,
              )),
          initialUrlRequest: URLRequest(
            url: Uri.parse("https://example.com"),
          ),
          onUpdateVisitedHistory: (controller, url, androidIsReload) {},
          onWebViewCreated: (controller) {},
          onLoadStop: (controller, url) {
            debugPrint(url!.origin);
            cookieObj.ios.getAllCookies().then((list) {
              if (list.isNotEmpty) {
                var filteredList = list
                    .where((element) =>
                        element.domain == 'example.com' &&
                        element.isSessionOnly == true)
                    .toList();
                if (filteredList.isNotEmpty) {
                  for (var element in filteredList) {
                    debugPrint('${element.name} :   ${element.value}');
                  }
                }
              }
            });
          },
        );
}
```

It retrieves when I'm inside webview once at first time "when it has been set ", but across my app. during navigation , I tried to cache it then , set it manually to the domain, not found  as well.

I'm stuck at this for. while , so any help , thanks n advanced

**Comment by pichillilorenzo** [comment]
To obtain the cookie manager instance, you must use `CookieManager.instance()`, so the `ios` property will be already set.
Using `CookieManager()` is not correct and will be removed.
Also, when you check for the domain, you are just checking for `example.com`, without including subdomains, such as `.example.com` (with a dot in front).

Try to use something like:
```dart
(element.domain == 'example.com' || element.domain == '.example.com')
```
or also:
```dart
element.domain.endsWith('example.com')
```

**Comment by HajerWael** [comment]
@pichillilorenzo 

Thanks, for your response  , it's working like charm , I made test on more than one real devices as below : 

Iphone : 15.5.1 (works fine)
Iphone : 16.0.1 (works fine)

Ipad: 13.4 (not working)

It suppose to work fore +11 , version

**Comment by pichillilorenzo** [comment]
The native Cookie Manager logic is the same for all iOS versions from 11+.
Try to print all the cookies and check if there is something in your logic you need to add to get what you want.

**Comment by HajerWael** [comment]
@pichillilorenzo  App. has the same logic to apply , thanks for reply by the way
