### ISSUE TITLE
Crashes app on Android when pressing home button

### ISSUE THREAD

**Issue by micsan13br** [pichillilorenzo/flutter_inappwebview#136]
I am not sure what other details to include.
I've tested this on a simple Android app on my Pixel 3.
Changing orientation is not a problem but simply pressing the home button (in the middle) will crash the app every single time.
Too bad because inappbrowser seems otherwise very stable.
I still have to check on iOS.

**Comment by micsan13br** [comment]
Did you just fix this? or is it because Androidx + Kotlin has somehow better support? I just completely rebuilt the app using swift (ios) and kotlin (android) with androidx dependencies and it seems that inappbrowser works perfectly ...

**Comment by MohammedYAmmar** [comment]
same problem

**Comment by micsan13br** [comment]
> same problem

Did you try my suggestion? does it still crash when the app is built on kotlin?

**Comment by VladimirCourse** [comment]
The same problem, app crashed with NullPointerException after Android locked. Also. it seems to common problem with other webviews: https://github.com/flutter/flutter/issues/36441

**Comment by huixisheng** [comment]
same problem +1

**Comment by twopai** [comment]
same problem+1

**Comment by micsan13br** [comment]
to all the people replying "+1": did you try my suggestion?
I've rebuilt the app and the crash is now gone.
I'm still not using the browser because (on iOS) I cannot load files from the sandbox folder using file:/// ... but that's another issue.

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
