### ISSUE TITLE
cannot enter content through soft keyboard on Android

### ISSUE THREAD

**Issue by wydsjyoung** [pichillilorenzo/flutter_inappwebview#137]
I can pop up a soft keyboard and focus the input box, but cannot enter content through soft keyboard

**Comment by wydsjyoung** [comment]
I tring to  build an embeded webview page, using the InAppWebview,but could not enter the content through soft keyboard,the soft keyboard can pop up normally,and the input can get the focus .
Please help me .Thanks.

**Comment by crushman1** [comment]
Is there no fix for this?

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.

**Comment by StevenKek** [comment]
I just encountered the very same thing on flutter_inappwebview 3.2.0, Android 8.0.0

When I click in a text field, keyboard appears, disappears and reappears super quickly (first issue).
I can then enter text, but when the browser navigates further in the background, keyboard stays open. When I click other text field on newly navigated page, text caret blinks, but I can't enter any text (second issue).

**Comment by StevenKek** [comment]
@pichillilorenzo Just making sure you saw my previous comment. No idea how notifications work on closed issues with no direct mentions.

**Comment by pichillilorenzo** [comment]
@StevenKek Notifications still send emails to me, don't worry. I have so many messages to read that takes me a lot of time and I'm working alone in this project.

However, the fact is that the keyboard is a mess right now with flutter native views (as you can see in the `README.md`: "_Keyboard support within webviews is also experimental_").
I'm trying to add some workarounds to make it work properly. Now, With my latest release `3.3.0` it should hide if you click/touch outside (but inside the WebView) of a text-field.

About your first issue, try the latest version of this plugin. Could you make a screen record of this first issue? Thanks!

About your second issue, if you click and focus on a text-field and then navigate to other pages without closing the keyboard and you try to type into another text-field, it won't work. Probably because the focus of the keyboard is not pointing to the correct text-field. However, as I said, now, if you click outside, the keyboard should hide.

Instead, for the numeric keyboard, I need to investigate more.

**Comment by StevenKek** [comment]
> @StevenKek Notifications still send emails to me, don't worry. I have so many messages to read that takes me a lot of time and I'm working alone in this project.
> 
> However, the fact is that the keyboard is a mess right now with flutter native views (as you can see in the `README.md`: "_Keyboard support within webviews is also experimental_").
> I'm trying to add some workarounds to make it work properly. Now, With my latest release `3.3.0` it should hide if you click/touch outside (but inside the WebView) of a text-field.
> 
> About your first issue, try the latest version of this plugin. Could you make a screen record of this first issue? Thanks!
> 
> About your second issue, if you click and focus on a text-field and then navigate to other pages without closing the keyboard and you try to type into another text-field, it won't work. Probably because the focus of the keyboard is not pointing to the correct text-field. However, as I said, now, if you click outside, the keyboard should hide.
> 
> Instead, for the numeric keyboard, I need to investigate more.

I understand. Thanks for intel :)

I also found one more issue, on one of the websites we allow to visit in our InAppWebView has dropdowns implemented not using select, but by using input element, like so: `<input name="" type="text" autocomplete="nope" placeholder="" tabindex="0" class="multiselect__input" style="width: 0px; position: absolute; padding: 0px;">`

When I click it, it opens properly, but at the same time, soft keyboard opens as well and when it opens completely, the dropdown menu is closed automatically. How could I prevent the keyboard from opening in this case? Sorry for piling up so many issues.

About the video, I will try to shoot all the mentioned issues. Never recorded mobile screen, will have to investigate the best way.

**Comment by pichillilorenzo** [comment]
Could you share the URL containing this input with custom dropdown?
However, It's an `input type="text"`, so, technically, it's correct that the keyboard appears.
Does it work as you expect if you use a browser such as Chrome?

> I also noticed suggestions keyboard panel hiding after opening the keyboard completely

Yes, I know about this issue.

**Comment by StevenKek** [comment]
> Could you share the URL containing this input with custom dropdown?
> However, It's an `input type="text"`, so, technically, it's correct that the keyboard appears.
> Does it work as you expect if you use a browser such as Chrome?
> 
> > I also noticed suggestions keyboard panel hiding after opening the keyboard completely
> 
> Yes, I know about this issue.

You are correct. In Firefox it worked correctly, but in Chrome on my device the issue persists. I can't provide the URL since it's login based proprietary website.
I can't change the sites code though. Is there a way to prevent the keyboard from opening there with javascript handlers?
