### ISSUE TITLE
REQUEST_INSTALL_PACKAGES makes app not complaint with Google Play Policies

### ISSUE THREAD

**Issue by BBrowns** [pichillilorenzo/flutter_inappwebview#1371]
Currently, I have a problem when pushing an app to the Play Store. Due to the fact that the library uses the 
REQUEST_INSTALL_PACKAGES permission, the app gets rejected. 

The attribute "tools:node=remove" in the manifest file has been removed from the "uses-permission" element. Previously, this was the only solution to remove the permission. I cannot seem to find an up-to-date solution anywhere.

The core use of the app does not require the permission and I would like to know how to remove the permission or how I can get Google to approve the app.

**Comment by pichillilorenzo** [comment]
Sorry but my plugin isn't using the `REQUEST_INSTALL_PACKAGES` anywhere.
Probably it's some other packages, but for sure not mine.
Just check the [Android manifest](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/android/src/main/AndroidManifest.xml) of the plugin.

**Comment by BBrowns** [comment]
Hmm, how come I get the following line from the manifest merger release report:

```
ADDED from [:flutter_inappwebview] /Users/pathToUser/pathToApp/build/flutter_inappwebview/intermediates/merged_manifest/release/AndroidManifest.xml:25:13-61 uses-permission#android.permission.REQUEST_INSTALL_PACKAGES
```

Do you know anything about how and why is being shown?

**Comment by pichillilorenzo** [comment]
Sincerely, I don't know, but I'm not using `REQUEST_INSTALL_PACKAGES` permission.

**Comment by BBrowns** [comment]
Could it be due to the fact that I'm using version 5.3.2 or did you not include the permission in that version either?

**Comment by pichillilorenzo** [comment]
Here is the manifest of that version: https://github.com/pichillilorenzo/flutter_inappwebview/blob/v5.3.2/android/src/main/AndroidManifest.xml

I **never** used `REQUEST_INSTALL_PACKAGES` permission in any version of the plugin.

**Comment by LennertDefauw1** [comment]
@BBrowns did you manage to solve the issue? Got the same problem :/ 

```
ADDED from [:flutter_inappwebview] /home/jimber/Documents/Threefold/backup/threefold_connect/app/build/flutter_inappwebview/intermediates/merged_manifest/debug/AndroidManifest.xml:44:13-61
uses-permission#android.permission.REQUEST_INSTALL_PACKAGES
```

**Comment by LennertDefauw1** [comment]
@BBrowns, actually in my project, the REQUEST_INSTALL_PACKAGES is required in the open_file pub package, don't know why the logs reference to this repo ^^
