### ISSUE TITLE
Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'

### ISSUE THREAD

**Issue by SanjayMehra-27** [pichillilorenzo/flutter_inappwebview#1372]
![Screen Shot 2022-10-15 at 11 51 08 AM](https://user-images.githubusercontent.com/58074189/195972463-bddb8545-2ed6-442b-a0b9-808ffca0c7a8.png)

**Comment by pichillilorenzo** [comment]
duplicated #1369, you need to update Xcode version to 14
