### ISSUE TITLE
I faced some errors when I try to use CookieManager 

### ISSUE THREAD

**Issue by oussemaRidene** [pichillilorenzo/flutter_inappwebview#1373]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by Shakle** [comment]
We have this error in pipeline, somehow related to CookieManager:

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/runner/hostedtoolcache/Flutter/3.3.4/macos/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/ios/Classes/MyCookieManager.swift:259:43

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/runner/hostedtoolcache/Flutter/3.3.4/macos/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/ios/Classes/MyCookieManager.swift:293:43

**Comment by pichillilorenzo** [comment]
duplicated #1369, you need to update Xcode version to 14
