### ISSUE TITLE
I encountered an error when I tried to use CookieManager IOS

### ISSUE THREAD

**Issue by oussemaRidene** [pichillilorenzo/flutter_inappwebview#1374]
`Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+2/ios/Classes/MyCookieManager.swift:259:43`

`[✓] Flutter (Channel stable, 3.3.0, on macOS 12.4 21F79 darwin-x64, locale en-TN)
    • Flutter version 3.3.0 on channel stable at /Users/oussamaridene/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (7 weeks ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/oussamaridene/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Users/oussamaridene/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • a7164a43aefbbe5c91d0a4220c00261905f0f327 • ios            • iOS 15.5 19F77
    • macOS (desktop)   • macos                                    • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available`

**Comment by pichillilorenzo** [comment]
duplicated #1369, you need to update Xcode version to 14
