### ISSUE TITLE
ARCHIVE FAILED on github action

### ISSUE THREAD

**Issue by Kiruel** [pichillilorenzo/flutter_inappwebview#1375]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       3.3.4        |
| Plugin version       |       5.5.0+3        |
| Android version      |               |
| iOS version          |               |
| Xcode version        |       13.2.1        |

Device information: 

## Description

**Expected behavior:** 
In local I don't have a compile problem (using Mac M1), but in github action the compilation fail.
**Current behavior:** 
Got an error on the logs github action see stacktrace

## Stacktrace/Logcat 

```
** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64 (in target 'flutter_inappwebview' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'flutter_inappwebview' from project 'Pods')
```

**Comment by pichillilorenzo** [comment]
Which version of XCode is it using? Version `5.5.0` requires XCode version 14

**Comment by Kiruel** [comment]
Yes the problem come from macos, the CI using `macos-lastest` but then don't migrated already for macos12, so I change directly for:
`runs-on: macos-12`

I close this. Thanks @pichillilorenzo .

**Comment by pichillilorenzo** [comment]
You are welcome! 👍
