### ISSUE TITLE
iOS - MyCookieManager.swift - Cannot call value of non-function type 'String?

### ISSUE THREAD

**Issue by Chandankumar26** [pichillilorenzo/flutter_inappwebview#1376]
Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/chandankumar/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+2/ios/Classes/MyCookieManager.swift:259:43

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/chandankumar/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+2/ios/Classes/MyCookieManager.swift:293:43

Could not build the application for the simulator.
Error launching application on iPhone 11.

**Comment by pichillilorenzo** [comment]
duplicated https://github.com/pichillilorenzo/flutter_inappwebview/issues/1369, you need to update Xcode version to 14

**Comment by ialyzaafan** [comment]
same issue

**Comment by pichillilorenzo** [comment]
@ialyzaafan as already written, you need to update Xcode version to 14

**Comment by ialyzaafan** [comment]
@pichillilorenzo  after updating  Xcode to v 14
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'

**Comment by pichillilorenzo** [comment]
You are using an old plugin version. You need to update it as weel

**Comment by hayelom123** [comment]
Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/hayelomkiros/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+5/ios/Classes/MyCookieManager.swift:259:43

**Comment by hayelom123** [comment]
> You are using an old plugin version. You need to update it as weel

it is not old version .please see below comment

**Comment by pichillilorenzo** [comment]
@hayelom123 Did you update your Xcode version to 14?

**Comment by PriyaSareen** [comment]
I am also facing the similar issue with iPhone

My project was working fine with the existing plugin version of "flutter_inappwebview" but it starts throwing error for iPhone now without doing any change.

Error is:
Xcode's output:
↳
Writing result bundle at path:
/var/folders/78/qh6vl1s50cvfdgtm51blwk2w0000gn/T/flutter_tools.R7B2E0/flutter_ios_build_temp_dirOEWi1S/temporary_xcresult_bundle

/Users/deepaksharma/Library/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.6.0+1/ios/Classes/MyCookieManager.swift:260:44: error: cannot
call value of non-function type 'String?'
                        domain = domainUrl.host()

**Comment by pichillilorenzo** [comment]
Please stop writing the same thing over again. I have already said that XCode version must be 14+.

I’m not closing this issue as complete only because other people don’t search and post same issue for the same thing, so I will wait a little.

As a reference, here is the official docs of the requirements for versions 5.x.x: https://inappwebview.dev/docs/5.x.x/intro

**Comment by ShejaEddy** [comment]
I'm using an old version of macbook, I can't upgrade my xcode version, I'm using Xcode 12.4. Is there a work around or any otherway to get my app building again?
Your help will be much appreciated.

**Comment by pichillilorenzo** [comment]
@ShejaEddy the workaround is to fork the repo (branch 6.x.x or 5.x.x, depending on which version are you using) and replace every part of code inside ios/Classes/MyCookieManager.swift:
```swift
if #available(iOS 16.0, *) {
  domain = domainUrl.host()
} else {
  domain = domainUrl.host
}
```

with:
```swift
domain = domainUrl.host
```

**Comment by hayelom123** [comment]
updating to xcode 14 fixed my problem.

**Comment by arvindsolanki** [comment]
if you don't want to update Xcode to 14 then another workaround is to add the below lines in pubspec.yaml file

dependency_overrides:
 flutter_inappwebview: version(don't use ^)

**Comment by ShejaEddy** [comment]
> @ShejaEddy the workaround is to fork the repo (branch 6.x.x or 5.x.x, depending on which version are you using) and replace every part of code inside ios/Classes/MyCookieManager.swift:
> 
> ```swift
> if #available(iOS 16.0, *) {
>   domain = domainUrl.host()
> } else {
>   domain = domainUrl.host
> }
> ```
> 
> with:
> 
> ```swift
> domain = domainUrl.host
> ```

This worked perfectly, thanks a lot!

**Comment by subzero911** [comment]
> you need to update Xcode version to 14

I confirm, updating XCode to 14.1 solved the issue.

**Comment by junaidhassan-axian** [comment]
> Please stop writing the same thing over again. I have already said that XCode version must be 14+.
> 
> I’m not closing this issue as complete only because other people don’t search and post same issue for the same thing, so I will wait a little.
> 
> As a reference, here is the official docs of the requirements for versions 5.x.x: https://inappwebview.dev/docs/5.x.x/intro

To hell with your third class plugin which is not able to work with existing XCodes! Users are repeatedly telling you that they already have XCode 14 so as me, but still facing your dam third class plugin issue! feeling pity for you the way you replied!

**Comment by pichillilorenzo** [comment]
@junaidhassan-axian feel free to post your `flutter doctor -v`. Also, is your issue exactly the same? Post the error logs and error screenshot, if possible.
This issue is related to the XCode version, unfortunately. I tested it with XCode versions 14.0 and 14.1

**Comment by junaidhassan-axian** [comment]
> @junaidhassan-axian feel free to post your `flutter doctor -v`. Also, is your issue exactly the same? Post the error logs and error screenshot, if possible. This issue is related to the XCode version, unfortunately. I tested it with XCode versions 14.0 and 14.1

Are you sure it will work with Xcode 14.2 if i spent a lot of my time just to download that dead animal lol literarily a bizarre animal size of mbs!

**Comment by pichillilorenzo** [comment]
@junaidhassan-axian please, in the meantime, post the result of your current `flutter doctor -v` and which version of the plugin you are using, to give me some more info about your environment, otherwise, I can't help you in any way.

**Comment by pichillilorenzo** [comment]
@junaidhassan-axian I confirm that it's working with XCode 14.2. Tested both the latest plugin versions 5 and 6 with Flutter 3.

**Comment by junaidhassan-axian** [comment]
> @junaidhassan-axian I confirm that it's also working with XCode 14.2. Tested both the latest plugin versions 5 and 6 with Flutter 3.

ok thanks dear, will check in a while!

**Comment by AgarwalMilan** [comment]
Downgrade it to `5.4.4` in pubspec.yaml to make it work without upgrading the Xcode until the developer make it compatible for older Xcode versions

**Comment by GiddyNaya** [comment]
> @ShejaEddy the workaround is to fork the repo (branch 6.x.x or 5.x.x, depending on which version are you using) and replace every part of code inside ios/Classes/MyCookieManager.swift:
> 
> ```swift
> if #available(iOS 16.0, *) {
>   domain = domainUrl.host()
> } else {
>   domain = domainUrl.host
> }
> ```
> 
> with:
> 
> ```swift
> domain = domainUrl.host
> ```

Why not just check if "domainUrl.host" is String or function?

**Comment by absc** [comment]
XCode 14.2 has same issue

**Comment by KiraResari** [comment]
As does XCode 13.4.1
Our problem is that because of technical reasons, we can't freely upgrade XCode, so we are stuck with this XCode Version until further notice. Just wanted to let you know that such use cases exist for Flutter developers.

**Comment by pichillilorenzo** [comment]
@KiraResari it’s possible to install multiple versions of XCode: https://developer.apple.com/forums/thread/692271
For example, new WKWebView features requires you to install newer version of XCode, otherwise you won’t be able to compile.
Differently from Android, where you can install every Android SDKs without any problem, you can’t install newer SDKs for iOS separately from XCode.
Unfortunately, this is how it works for Apple.

**Comment by h3nr1ke** [comment]
If you have more than one Xcode installed, make sure you are using the correct one in the command line with 

```
$ xcodebuild -version

Xcode 13.0
Build version 13A233
```

if you are not using the version 14, then you can set the correct version using, for instance

```
$ sudo xcode-select -s /Applications/Xcode.app
```

make sure to point to the correct path

after I did this

```
$ xcodebuild -version
Xcode 14.3.1
Build version 14E300c
```

hope it helps =)

**Comment by pro100svitlo** [comment]
Hey guys, any progress on this issue?
Maybe any ETA? 😅 

Would much appreciate 😍
