### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript

### ISSUE THREAD

**Issue by Doflatango** [pichillilorenzo/flutter_inappwebview#1377]
Some page are mgiht have a CSP directive that refused to evaluate a string, such as github.com.
I search this repo and found one line use  `eval`, that wiil be cause an `EvalError`.

https://github.com/pichillilorenzo/flutter_inappwebview/blob/44189ae75c61f5e9bc2df6dc167bae250b41fb4b/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/plugin_scripts_js/PluginScriptsUtil.java#L33

## Steps to reproduce

1. Open devtool at current page;
2. Execute code below:
```javascript
eval("var a;");
```
4. Getting an error:
> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src translate.googleapis.com translate.google.com www.google.com www.gstatic.com chrome-extension://bfdogplmndidlpjfhoijckpakkdjkkil/ github.githubassets.com".

**Comment by pichillilorenzo** [comment]
That's how Content World is implemented on Android.
It could occur If you are using `evaluateJavascript` with a content world.
Unfortunately, there is no such thing as we have on iOS, so there are limitations.
In fact, another limitations is using iframes for content worlds on Android.

If you don't need content worlds, don't use it.

**Comment by pichillilorenzo** [comment]
Here is the official plugin docs that explains it: https://inappwebview.dev/docs/webview/javascript/content-worlds

**Comment by Doflatango** [comment]
Thank you for the explanation.
