### ISSUE TITLE
Xcode 14 and iOS 16, Errors with Color, Size and Uint8List in the package

### ISSUE THREAD

**Issue by bilaldrndo** [pichillilorenzo/flutter_inappwebview#1378]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   Flutter 3.0.5 stable  |
| Plugin version       |   flutter_inappwebview: ^5.5.0+3  |
| Android version      |               |
| iOS version          |  iOS 16.0  |
| Xcode version        |    14.0.1    |

Device information: 
iPhone XS Max

## Description

When I run flutter run, it throws me these errors:

    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/in_app_webview_controller.dart:1199:52: Error: Type 'Uint8List' not found.
      Future<void> postUrl({required Uri url, required Uint8List postData}) async {
                                                       ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/in_app_webview_controller.dart:1612:10: Error: Type 'Uint8List' not found.
      Future<Uint8List?> takeScreenshot(
             ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/in_app_webview_controller.dart:2044:10: Error: Type 'Color' not found.
      Future<Color?> getMetaThemeColor() async {
             ^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:41:9: Error: Type 'Size' not found.
      final Size initialSize;
            ^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:184:24: Error: Type 'Size' not found.
      Future<void> setSize(Size size) async {
                           ^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:197:10: Error: Type 'Size' not found.
      Future<Size?> getSize() async {
             ^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:451:52: Error: Type 'Uint8List' not found.
      void Function(InAppWebViewController controller, Uint8List icon)?
                                                       ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/chrome_safari_browser/chrome_safari_browser.dart:194:3: Error: Type 'Uint8List' not found.
      Uint8List icon;
      ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/pull_to_refresh/pull_to_refresh_controller.dart:77:25: Error: Type 'Color' not found.
      Future<void> setColor(Color color) async {
                            ^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/pull_to_refresh/pull_to_refresh_controller.dart:84:35: Error: Type 'Color' not found.
      Future<void> setBackgroundColor(Color color) async {
                                      ^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/ios/in_app_webview_controller.dart:34:10: Error: Type 'Uint8List' not found.
      Future<Uint8List?> createPdf(
             ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/ios/in_app_webview_controller.dart:48:10: Error: Type 'Uint8List' not found.
      Future<Uint8List?> createWebArchiveData() async {
             ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:44:33: Error: Couldn't find constructor 'Size'.
          {this.initialSize = const Size(-1, -1),
                                    ^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/in_app_webview_controller.dart:395:11: Error: 'Uint8List' isn't a type.
              Uint8List icon =
              ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/in_app_webview_controller.dart:396:15: Error: The getter 'Uint8List' isn't defined for
    the class 'InAppWebViewController'.
     - 'InAppWebViewController' is from 'package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart'
     ('../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/in_app_webview_controller.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'Uint8List'.
                  Uint8List.fromList(call.arguments["icon"].cast<int>());
                  ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/in_app_webview_controller.dart:1199:52: Error: 'Uint8List' isn't a type.
      Future<void> postUrl({required Uri url, required Uint8List postData}) async {
                                                       ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:41:9: Error: 'Size' isn't a type.
      final Size initialSize;
            ^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:184:24: Error: 'Size' isn't a type.
      Future<void> setSize(Size size) async {
                           ^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/in_app_webview/headless_in_app_webview.dart:451:52: Error: 'Uint8List' isn't a type.
      void Function(InAppWebViewController controller, Uint8List icon)?
                                                       ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/chrome_safari_browser/chrome_safari_browser.dart:194:3: Error: 'Uint8List' isn't a type.
      Uint8List icon;
      ^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/pull_to_refresh/pull_to_refresh_controller.dart:77:25: Error: 'Color' isn't a type.
      Future<void> setColor(Color color) async {
                            ^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.5.0+3/lib/src/pull_to_refresh/pull_to_refresh_controller.dart:84:35: Error: 'Color' isn't a type.
      Future<void> setBackgroundColor(Color color) async {
                                      ^^^^^

**Comment by pichillilorenzo** [comment]
It seems very strange. I don't get any of these errors, I can run my code example with any problem.
Have you tried to run `flutter clean` and `flutter pub get` again?

**Comment by bilaldrndo** [comment]
Hey, thanks for the fast response. 
I have tried restarting my computer, running `flutter clean` and `flutter pub get` many times, using the 6.0 beta version of the package but I still get these errors.
I tried manually editing the code in the package and resolving the Errors, the app then builds without a problem but the package then doesn't work i.e, It doesn't want to open the desired website.

**Comment by pichillilorenzo** [comment]
Have you tried to update your Flutter version?

**Comment by bilaldrndo** [comment]
No, good idea, can you please tell me what Flutter version You are using?

**Comment by pichillilorenzo** [comment]
I'm running on Flutter 3.3.3

**Comment by bilaldrndo** [comment]
I will give it a try and see what happens!

**Comment by bilaldrndo** [comment]
Solved the issue completely! Thank You so much!

**Comment by pichillilorenzo** [comment]
You are welcome! 👍
