### ISSUE TITLE
Flutter 2.8.1 Issue

### ISSUE THREAD

**Issue by chandrabezzo** [pichillilorenzo/flutter_inappwebview#1380]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment
[✓] Flutter (Channel unknown, 2.8.1, on macOS 12.6 21G115 darwin-arm, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.72.2)

Device information: 
None

## Description
Can running the apps without error Color and UInt8List.
**Expected behavior:** 

**Current behavior:** 
Always got an error in several place for UInt8List, Color, and Size.
## Steps to reproduce
1. Install fvm or stable Flutter with version 2.8.1
2. Clone this repo
3. Run command `flutter pub get` using version 2.8.1
4. You will got an error for UInt8List and Color
5. You need to import:
  - 'dart:typed_data'; to fix UInt8List issue
  - 'package:flutter/material.dart'; to fix Color and Size issue

## Images   
![Screen Shot 2022-10-20 at 10 48 11](https://user-images.githubusercontent.com/16184998/196852089-180db139-82da-4ebb-8356-8e8c85e40174.png)
![Screen Shot 2022-10-20 at 10 48 20](https://user-images.githubusercontent.com/16184998/196852095-c5a32f4b-cb3f-4df1-8e47-d5f975ebeb21.png)

**Comment by boszedave** [comment]
Yep, I have also the same problem using youtube_player_flutter which relies on this package.

**Comment by nsalleron** [comment]
got the same problem here with 2.5.3

**Comment by pichillilorenzo** [comment]
It should be fixed now with release `5.5.0+4`

**Comment by nsalleron** [comment]
it's fixed with this version thanks
