### ISSUE TITLE
onLoadStop does not get called the second time the WebView is created on Android

### ISSUE THREAD

**Issue by bugnano** [pichillilorenzo/flutter_inappwebview#1384]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 3.3.4         |
| Plugin version       | 6.0.0-beta.3  |
| Android version      |  11           |
| iOS version          |               |
| Xcode version        |               |

Device information: Android Emulator (any)
Samsung Galaxy (any)

## Description

**Expected behavior:** 
When I put the InAppWebView in a modal bottom sheet, I expect it to call onLoadStop every time I open the bottom sheet.

**Current behavior:** 
When I put the InAppWebView in a modal bottom sheet, the onLoadStop callback is called correctly only the first time I open the modal bottom sheet.

## Steps to reproduce

1. Clone the repository: https://github.com/talkjs/webview_bug
2. Run the example app
3. Click on the button
4. See that the background is green
5. Pull down the bottom sheet
6. Click the button again
7. See that the background is red

All the example app code is in main.dart
The way the example app works is:
The InAppWebView is created with an initialUrlRequest with null as the URL.
Then, the onWebViewCreated callback will load an HTML page with a red background, and set its baseUrl to https://app.talkjs.com
Finally, the onLoadStop callback, injects the JS that sets the background colour to green, but only if the URL is not about:blank.

You can see that the first time, onLoadStop is called 2 times (1 for about:blank, and 1 for https://app.talkjs.com)
From the second time on, onLoadStop is called only once (only for about:blank).

**Comment by bugnano** [comment]
I wanted to add that this problem is Android-specific.
On iOS, onLoadStop gets called correctly every time.

**Comment by pichillilorenzo** [comment]
You are setting `initialUrlRequest: URLRequest(url: null)` to `null` which means it will load `about:blank` and also you are loading another URL using `loadData` when the WebView is created.

The loading operation is something asynchronous, and also depends on the platform itself, so I think Android is trying to load one URL before the other one or something similar.

Just delete `initialUrlRequest` (it isn't required, also setting with `URLRequest(url: null)` doesn't make any sense to me) and it will work:
```dart
child: InAppWebView(
  onWebViewCreated: _onWebViewCreated,
  onLoadStop: _onLoadStop,
),
```
