### ISSUE TITLE
InjectJavascriptFromURL and InjectCSSFromURL  is not working as expected.

### ISSUE THREAD

**Issue by omerbyrk** [pichillilorenzo/flutter_inappwebview#1385]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         3.3.2      |
| Plugin version       |         6.0.0-beta.2      |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

I am try to inject my JS file to the app using the link: https://cdn.jsdelivr.net/gh/omerbyrk/webvify-public/delete-my-account.js

However, it is added webview link hostname to it like https://domain.com/https://cdn.jsdelivr.net/gh/omerbyrk/webvify-public/delete-my-account.js

And it gives error.

## Steps to reproduce

1. Create an empty webview project
2. Try to inject javascript from URL
3. You will see library adds host link to the url as prefix.

**Comment by pichillilorenzo** [comment]
Sorry, but I can't replicate your issue.
This is an example code and it is working as expected:
```dart
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
    await InAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(MaterialApp(home: new MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey webViewKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("InAppWebView test")),
        body: SafeArea(
            child: Column(children: <Widget>[
              Expanded(
                child: InAppWebView(
                  key: webViewKey,
                  initialUrlRequest:
                  URLRequest(url: Uri.parse("https://example.com/")),
                  onLoadStop: (controller, url) async {
                    await controller.injectJavascriptFileFromUrl(
                        urlFile: Uri.parse(
                            'https://cdn.jsdelivr.net/gh/omerbyrk/webvify-public/delete-my-account.js'));
                    await controller.injectCSSFileFromUrl(
                        urlFile: Uri.parse(
                            'https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css'));
                  },
                ),
              ),
            ])));
  }
}
```

Here is the screenshot:
![Schermata 2022-10-21 alle 12 49 00](https://user-images.githubusercontent.com/5956938/197179193-b5a1589e-8c54-468a-82b6-e13195045b24.png)

**Comment by omerbyrk** [comment]
Thank you for the answer. I will retry it, and open the issue again if I meet the bug.
