### ISSUE TITLE
Compare to webview_flutter, inappwebview is significant frame dropped while page scrolling

### ISSUE THREAD

**Issue by Doflatango** [pichillilorenzo/flutter_inappwebview#1386]
Compare using the example in each plugin on a device with 60Hz screen.
This issue might happened since Flutter 3.0.

**Comment by pichillilorenzo** [comment]
Please, share more info, such as on which platform, code example and some video recording if possible, thanks.

**Comment by pichillilorenzo** [comment]
May be related to #1335? Does it happen on iOS?

**Comment by Doflatango** [comment]
I am tested on Android and iOS with 60Hz, i think it's fine on iOS compare to Safari.
I don't think so that the two issues are related because the mechanics are completely different in Android and iOS.

Based on previous testing that compared with plugin `webview_flutter`, I think we need to do some changes in `inappwebview`.
I am trying to do more testing on old version of inappwebview and Flutter, and will add more info later.

**Comment by Doflatango** [comment]
Testing info:
> device: Redmi 7A
> Android version: 10
> useHybridComposition: true
> page: https://flutter.dev

| flutter_inappwebview  | Flutter | Result |
| ------------- |:-------------:| ---- |
| 5.4.0      | 2.10.5     | Good |
| 5.5.0+5   | 2.10.5     | Good |
| 5.4.0   | 3.0.0     | Bad |
| 5.5.0+5   | 3.0.0     | Bad |
| 5.4.0   | 3.3.5     | Bad |
| 5.5.0+5   | 3.3.5     | Bad |

| [webview_flutter_android](https://pub.dev/packages/webview_flutter_android)  | Flutter | Result |
| ------------- |:-------------:| ---- |
| 2.10.4  | 3.0.0     | Good |
| 2.10.4  | 3.3.5     | Good |

There may something changed since Flutter 3.

@pichillilorenzo hope it helps.
