### ISSUE TITLE
Ios16 contextMenu Not Working

### ISSUE THREAD

**Issue by zjyjstgbc** [pichillilorenzo/flutter_inappwebview#1389]
Ios16 contextMenu Not Working！！

**Comment by zjyjstgbc** [comment]
hideDefaultSystemContextMenuItems 
onHideContextMenu
onCreateContextMenu
None of them work

**Comment by filipenanclarez** [comment]
Same as https://github.com/pichillilorenzo/flutter_inappwebview/issues/1315 right?

**Comment by zjyjstgbc** [comment]
> Same as #1315 right?

yes

**Comment by filipenanclarez** [comment]
@pichillilorenzo can you help here?
