### ISSUE TITLE
Works on debug, not release.

### ISSUE THREAD

**Issue by krypticallusion** [pichillilorenzo/flutter_inappwebview#139]
For some reason, shouldOverrideUrlLoading is never called when using a release build, it works fine when use a debug build.

**Comment by pichillilorenzo** [comment]
Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.

**Comment by pichillilorenzo** [comment]
Fix available starting from the version `3.0.0`.
