### ISSUE TITLE
Cannot call value of non-function type 'String?'

### ISSUE THREAD

**Issue by PriyaSareen** [pichillilorenzo/flutter_inappwebview#1391]
My project was working fine with the existing plugin version of "flutter_inappwebview" but it starts throwing error for iPhone now without doing any change.

Error is:
Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/78/qh6vl1s50cvfdgtm51blwk2w0000gn/T/flutter_tools.R7B2E0/flutter_ios_build_temp_dirOEWi1S/temporary_xcresult_bundle

    /Users/deepaksharma/Library/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.6.0+1/ios/Classes/MyCookieManager.swift:260:44: error: cannot
    call value of non-function type 'String?'
                            domain = domainUrl.host()

**Comment by MinhCuongIT** [comment]
I have the same issues, how to fix this?

**Comment by pichillilorenzo** [comment]
@MinhCuongIT https://github.com/pichillilorenzo/flutter_inappwebview/issues/1376
