### ISSUE TITLE
Web platform not working in 6.x.x

### ISSUE THREAD

**Issue by YohanWadia** [pichillilorenzo/flutter_inappwebview#1392]
I followed everything in https://inappwebview.dev/docs/intro
 **The Android app works fine**
but as mentioned to make the WebPlatform work i did this: 

```
<head>
  <!-- ... -->
    <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
  <!-- ... -->
</head>
```
but nothing happens... when I put the above line in build/web/index.html... nothing happens, but I get stuff in the console that says:

_

> TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
>     at FlutterInAppWebViewWebPlatform.registerWith (http://localhost:58821/packages/flutter_inappwebview/src/web/web_platform.dart.lib.js:46:60)
>     at Object.registerPlugins (http://localhost:58821/packages/inappwebview_pkg/generated_plugin_registrant.dart.lib.js:14:49)
>     at http://localhost:58821/web_entrypoint.dart.lib.js:39:39
>     at Object._checkAndCall (http://localhost:58821/dart_sdk.js:5279:16)
>     at Object.dcall (http://localhost:58821/dart_sdk.js:5284:17)
>     at http://localhost:58821/dart_sdk.js:140287:18
>     at Generator.next (<anonymous>)
>     at runBody (http://localhost:58821/dart_sdk.js:40660:34)
>     at Object._async [as async] (http://localhost:58821/dart_sdk.js:40691:7)
>     at _engine.AppBootstrap.new.<anonymous> (http://localhost:58821/dart_sdk.js:140285:67)
>     at Object._checkAndCall (http://localhost:58821/dart_sdk.js:5279:16)
>     at Object.callMethod (http://localhost:58821/dart_sdk.js:5322:17)
>     at Object.dsend (http://localhost:58821/dart_sdk.js:5325:17)
>     at _engine.AppBootstrap.new.<anonymous> (http://localhost:58821/dart_sdk.js:140636:22)
>     at Generator.next (<anonymous>)
>     at runBody (http://localhost:58821/dart_sdk.js:40660:34)
>     at Object._async [as async] (http://localhost:58821/dart_sdk.js:40691:7)
>     at http://localhost:58821/dart_sdk.js:140635:215
>     at Object._checkAndCall (http://localhost:58821/dart_sdk.js:5279:16)
>     at Object.dcall (http://localhost:58821/dart_sdk.js:5284:17)
>     at ret (http://localhost:58821/dart_sdk.js:62210:21)
>     at new Promise (<anonymous>)
>     at http://localhost:58821/dart_sdk.js:140635:119
>     at Object._checkAndCall (http://localhost:58821/dart_sdk.js:5279:16)
>     at Object.dcall (http://localhost:58821/dart_sdk.js:5284:17)
>     at Object.ret [as runApp] (http://localhost:58821/dart_sdk.js:62210:21)
>     at http://localhost:58821/:53:26

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version     (sdk: ">=2.17.0 <3.0.0")
| Plugin version     flutter_inappwebview: ^6.0.0-beta.7
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Is there a special way to run the WebPlatform?
All I need is in my Website(ie being developed by flutter web) one of the widgets on the screen will be an InAppWebView displaying information from another site. Is there something I am missing???

Thanks,
YOhan

**Comment by YohanWadia** [comment]
Yes this is a real problem. I have looked at the code on StackOverflow... it is wrong and conflicts with the code in your example repo. There is not a single place where you have pasted code that shows how to simply have an InAppWebView inside a flutter web page. Will urge you to do so, as you have claimed on numerous occasions on stackOverflow that this widget does work as claimed!
Will await your reply & help. Thanks

**Comment by pichillilorenzo** [comment]
Version 6.x.x requires Flutter 3.
From your environment, you are using Flutter < 3.

However, here is a very basic code example that it is working:
```dart
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
    await InAppWebViewController.setWebContentsDebuggingEnabled(kDebugMode);
  }
  runApp(const MaterialApp(
      home: MyApp()
  ));
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController? webViewController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text("InAppWebView TEST")),
        body: SafeArea(
            child: Column(children: <Widget>[
              Expanded(
                child: Stack(
                  children: [
                    InAppWebView(
                      key: webViewKey,
                      initialUrlRequest: URLRequest(
                          url: Uri.parse('https://flutter.dev')),
                      onWebViewCreated: (controller) {
                        webViewController = controller;
                      },
                    ),
                  ],
                ),
              ),
            ]))
    );
  }
}
```

`index.html` code:
```html
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="flutter_inappwebview_test">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>flutter_inappwebview_test</title>
  <link rel="manifest" href="manifest.json">

  <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>

  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = null;
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>
</head>
<body>
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
</body>
</html>
```

Screenshot:

![Schermata 2022-10-23 alle 21 10 52](https://user-images.githubusercontent.com/5956938/197411476-536570e4-d518-4e08-9ec1-d927fdbf5b2a.png)

**Comment by YohanWadia** [comment]
Hi @pichillilorenzo ,
This was perfect.
I thank you for your time and greatly appreciate you outlining the particulars.

it worked perfectly there were no errors.
changed the environment to **sdk: ">=2.17.0 <3.3.5"** in the .yaml
I ran a flutter build web... 
then edited the index.html like you said
hosted it on a server... and BOOM!... just as you said.

Thanks,
And I will go back to those StackOverFlow resources and post the new code you helped me out with.

YOhan

**Comment by pichillilorenzo** [comment]
@YohanWadia no problem! You are welcome!

**Comment by vinnytwice** [comment]
@pichillilorenzo I guess that to use the version 6 then we have to switch to the dev branch as the stable branch max sdk is 2.8.x right?

**Comment by pichillilorenzo** [comment]
@vinnytwice no, you should install it from pub.dev
The latest available is [6.0.0-beta.22](https://pub.dev/packages/flutter_inappwebview/versions/6.0.0-beta.22)

**Comment by pichillilorenzo** [comment]
@vinnytwice check the requirements online:
- Version 6: https://inappwebview.dev/docs/intro/#requirements
- Version 5: https://inappwebview.dev/docs/5.x.x/intro

**Comment by vinnytwice** [comment]
I'm using the 6.0.0-beta.22, and I'm on flutter channel master which Flutter 3.3.10/ Dart 2.18.6 .

@pichillilorenzo I changed the pubspec.yaml sdk: ">=2.17.0 <3.3.5" and it should work right?
Unfortunately it  works only on Android, I guess it has to with the screen I use the plugin in.

Should I open a new issue?

**Comment by vinnytwice** [comment]
@pichillilorenzo  I opened an issue so to show all the steps.
Many thanks
