### ISSUE TITLE
Follow up Question to #1392 about a ScreenShot on Web

### ISSUE THREAD

**Issue by YohanWadia** [pichillilorenzo/flutter_inappwebview#1397]
<html>
<body>

Technology | Version
-- | --
Flutter version | 3.3.5
Plugin version | flutter_inappwebview: ^6.0.0-beta.7

</body>
</html>

After @pichillilorenzo helped me out in getting the Webview working on Flutter Web.... I cant seem to get a snapshot/screenshot of the InAppWebView!? Just wanted to know is a snapshot supported in Flutter Web?

Everything from my project remains the same from #1392. But when I use your below code I found on stackoverflow... I get a null error.

```
 Uint8List screenshotBytes = (await webViewController?.takeScreenshot())!;
                    showDialog( context: context, builder: (context) {
                      return AlertDialog( content: Image.memory(screenshotBytes),);
                    });
```

I also tried wrapping it in RepaintBoundary, but that failed too with null errors!? :-( 
Any advice would be helpful.
Thanks.

**Comment by pichillilorenzo** [comment]
`takeScreenshot` is not supported on Web! Just check the code docs of each method or event or whatever to see what is supported in which platform.

Just for reference, [takeScreenshot API](https://pub.dev/documentation/flutter_inappwebview/6.0.0-beta.8/flutter_inappwebview/InAppWebViewController/takeScreenshot.html)
