### ISSUE TITLE
SCREENSHOT/SNAPSHOT ON FLUTTER WEB

### ISSUE THREAD

**Issue by YohanWadia** [pichillilorenzo/flutter_inappwebview#1399]
## Environment
FLUTTER WEB 

**Flutter version:** sdk: ">=2.17.0 <3.3.5"
**Plugin version:**  flutter_inappwebview: ^6.0.0-beta.7  
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description
Cant get a screenshot/snapshot of the webview in FlutterWeb
Sometimes the website you are displaying in the webview might have a popup Ad. I need to detect that. Because these Ads are wired via JS from a link the Advertisers ask us to place in the body <tag> there is no way i receive this information(about when it pops up) via an onLoad/onCreate etc etc... so if I can get a snapshot(of my webview) I could detect the pixel color change... and hence be aware that the webview has just been covered by a pop up.

**What you'd like to happen:** 
It would be nice if we could have `screenshotBytes = (await webViewController?.takeScreenshot())!;` work in flutter web too

**Alternatives you've considered:**   
tried wrapping the webview in RepaintBoundary
Also asked the Advertising guys if I could receive an event when the popup is going to occur, but they were helpless

**Comment by pichillilorenzo** [comment]
Unfortunately, it’s not possible to take screenshot on Web platform.
Web is not like Android or iOS.

It uses an [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) HTML element to render the content, so it is also very very limited on what we can do with it!
In fact, all InAppWebViewController methods implemented for Web requires the iframe to have the same origin (check https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#scripting).

That’s how it works on Web platform.

**Comment by YohanWadia** [comment]
I appreciate the time you took to explain me this.
Thanks & all the best.
YOhan
