### ISSUE TITLE
Debug Android WebView from Chrome Inspect

### ISSUE THREAD

**Issue by drozdzynski** [pichillilorenzo/flutter_inappwebview#140]
Hello,

I have a small feature request for this library, to add an option to enable inspect WebView from Chrome Browser.

This method make inspect enabled:
```java
WebView.setWebContentsDebuggingEnabled(true);
```

More info you can find here:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

**Comment by pichillilorenzo** [comment]
Added in `2.0.0` version. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
