### ISSUE TITLE
Not allowed to load local resource when html img src use local path

### ISSUE THREAD

**Issue by 826327700** [pichillilorenzo/flutter_inappwebview#1406]
e.g :
html->img src ="file:///data/user/0/com.example.flutter_demo/cache/xxx.png"

It's error message Not allowed to load local resource . but I hope I can read local file in html.

**Comment by gaurvishal** [comment]
html->img src ="file:///data/user/0/com.example.flutter_demo/cache/xxx.png" working fine for android but breaking in ios.  is this the correct way to load image from apps folder like cache or other or there is other ways.
