### ISSUE TITLE
 v5.7.1 take long time to load page

### ISSUE THREAD

**Issue by phamconganh** [pichillilorenzo/flutter_inappwebview#1408]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        3.3.6       |
| Plugin version       |         5.7.1      |
| Android version      |       11        |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:**  I upgrade from version 5.5.0+5   to version  5.7.1

**Current behavior:**  It take x2, x3 time to loading a page compared to before

**Comment by pichillilorenzo** [comment]
5.5.0+5 and 5.7.1 differs only the usage of hybrid composition implementation for Flutter 3, that is literally just the usage of new Flutter API for hybrid composition.. are you using hybrid composition? have you tried to disable it?

**Comment by phamconganh** [comment]
@pichillilorenzo I just tested in v5.6.0 + 1, and it's fine too.

**Comment by pichillilorenzo** [comment]
As I said, it differs only the usage of hybrid composition implementation for Flutter 3.
are you using hybrid composition? have you tried to disable it?
Could you post a code example here to test?

**Comment by phamconganh** [comment]
i'm using hybrid composition and it work fine to v5.7.0. In v5.7.1, I have to use hybrid composition false to get the same loading speed as before.

**Comment by pichillilorenzo** [comment]
It doesn’t make any sense.
5.7.1 has just “ Exposed "shared" property of HttpServer bind method to support more use-cases.”

**Comment by pichillilorenzo** [comment]
Here is the commit comparison: https://github.com/pichillilorenzo/flutter_inappwebview/compare/v5.7.0...v5.7.1

**Comment by phamconganh** [comment]
Thanks you. I have double checked. In debug mode, My Webview load 2.0s with v5.6.0+2 with hybrid composition true. From v5.7.0 it is 3.5s. From v5.7.1 it is 7s. When using hybrid composition false with v5.7.0+, it is not different from v5.6.0 + 2

**Comment by phamconganh** [comment]
I think it's because 
`
if (hybridComposition) {
      return PlatformViewsService.initExpensiveAndroidView(
        id: id,
        viewType: viewType,
        layoutDirection: layoutDirection,
        creationParams: creationParams,
        creationParamsCodec: const StandardMessageCodec(),
      );
    }
`

**Comment by pichillilorenzo** [comment]
Please post a code example that could reproduce this issue.
Web page loading time depends from a lot of factors, such your internet speed in that current moment of your tests, caching, etc.
Android native code WebView implementation is the same as previous versions. 
As I said, the only thing that changed is the usage of Flutter API for hybrid composition for Flutter >= 3.0.0
But I don’t think is the loading time, but the rendering time of the platform native view.
So, I think it’s related on how Flutter native code implements hybrid composition for Flutter >= 3.0.0

**Comment by phamconganh** [comment]
Thank you for your help. I will create a test repo from my projects and share as soon as I'm done
