### ISSUE TITLE
js stops running in hidden InAppBrowser on ios

### ISSUE THREAD

**Issue by peter-meemo** [pichillilorenzo/flutter_inappwebview#141]
JS running in a hidden InAppBrowser will stop after a few seconds (and resume when the browser becomes visible again). Is this caused by some ios system restriction?

This is observed on a physical ios device, but not on Android or in the ios simulator.

Reproduce:
```
class TestBrowser extends InAppBrowser {
  @override
  void onConsoleMessage(ConsoleMessage consoleMessage) {
    print('CONSOLE LOG: ${consoleMessage.message}');
  }
}
```

Then open the following page in a TestBrowser that is hidden:

```
<html>
   <head>
      <script>
         async function a() {
         let c = 0;
         while(true) {
           let p = new Promise(resolve => {
         setTimeout(() => {
         resolve('resolved');
         }, 200);
         });
         await p;
         c += 1;
         console.log('ASYNC ' + c);
         document.body.innerHTML += ' ' + c;
         }
         return
         }
         a();
      </script>
   </head>
   <body>
      BODY-A
   </body>
</html>
```

You will see that the console stops logging after a few seconds. If you call .show() on the browser after waiting, console logging and js will resume.

**Comment by peter-fingo** [comment]
Sounds like this is indeed a consequence of ios js execution model?
https://www.raymondcamden.com/2013/01/20/FYI-iOS-JavaScript-and-inactive-tabs
