### ISSUE TITLE
Unable to use with Xcode 14

### ISSUE THREAD

**Issue by shubham2bansal** [pichillilorenzo/flutter_inappwebview#1416]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 3.3.7              |
| Plugin version       | 5.7.1              |
| Android version      | not relevant           |
| iOS version          |  12.5.6             |
| Xcode version        | 14.1              |

Device information: 

## Description
The plugin is giving lot of errors for many classes that are available only on iOS version greater than 14.0 and 14.1. While the same was working fine in Xcode 13. Please let me know what need to do

**Expected behavior:** 
It should not give any error on Xcode 14
**Current behavior:** 
The plugin does not seems working. It is giving errors in many files and on resolving them it starts to show in respective files where those classes are used.
## Steps to reproduce
Update the Xcode to version 14 and try to use the plugin in Flutter project. It will not allow to run the app.

The issue is not in the code that is implemented in project. But the issue is in the plugin code. 

Below are the few images of the issues shown in VSCode and Xcode 14. There around 30-40 such errors which does not allow app to run.
<img width="1012" alt="Screenshot 2022-11-08 at 9 29 44 PM" src="https://user-images.githubusercontent.com/100115910/200615968-12893687-3bd3-4f7d-960a-a399ab67b185.png">

Error in Xcode

<img width="1063" alt="Screenshot 2022-11-08 at 9 36 59 PM" src="https://user-images.githubusercontent.com/100115910/200615987-c0894f4b-8c06-4853-bbb4-d44e255c0bc7.png">

**Comment by pichillilorenzo** [comment]
I have just checked but I don't have your errors. Please, remove and install the dependency again.
From the screenshot, it seems you are still using version `5.3.2` and not the latest one (from the path of `flutter/.pub-cache` in your first screenshot).

**Comment by toda-bps** [comment]
I failed to build with:

* flutter 3.3.8
* Xcode 14.1
* example of flutter_inappwebview v6.0.0-beta.12

<details>
<summary>doctor (partial)</summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6.1 21G217 darwin-x64, locale ja-JP)
    • Flutter version 3.3.8 on channel stable at /System/Volumes/Data/buildroot/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (34 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode14.1.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3
```
</details>

Logs(username masked)

[failed-14.1.txt](https://github.com/pichillilorenzo/flutter_inappwebview/files/9981296/failed-14.1.txt)

[failed-verbose-14.1.txt](https://github.com/pichillilorenzo/flutter_inappwebview/files/9981297/failed-verbose-14.1.txt)

But I got success with Xcode 14.0.1

[succeeded-verbose-14.0.1.txt](https://github.com/pichillilorenzo/flutter_inappwebview/files/9981316/succeeded-verbose-14.0.1.txt)

**Comment by shubham2bansal** [comment]
I checked again the error. Basically when we use this plugin Xcode shows error only for this plugin. But there is compatibility issues with Xcode 14 for all other plugins also. So you need to follow the below steps to fix the issue.

1. Update flutter SDK to the latest version. I used 3.3.7. Because 3.3.8 is release today only.
2. You need to update all plugins with their latest version.
3. Resolve the conflicts between plugin versions and try to keep most updated and compatible plugin version
4. Most importantly, Xcode failed the build because project was using functionality of plugin "modal_bottom_sheet" and Xcode was unable to find this plugin. So add this plugin in your project and try to add using "flutter pub add ..." command.
5. Xcode has made it mandatory to enable Bitcode for product Runner and Pods. So open Pods project and Enable Bitcode. It will enable for all the Targets.
6. After that Run your app on Simulator only, having iOS version 16, that came with Xcode 14. Xcode 14 is currently not allowing to run app on real devices. 
7. By running it once it will update all your flutter project settings. 
8. Then you can also proceed to create Archive and share your app.
