### ISSUE TITLE
flutter_inappwebview-5.7.1/ios/Classes/MyCookieManager.swift:259:43

### ISSUE THREAD

**Issue by RAFI-006** [pichillilorenzo/flutter_inappwebview#1419]
Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'

**Comment by pichillilorenzo** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1376

**Comment by himani2022** [comment]
I downgrade flutter version to flutter_inappwebview: 5.5.0+1 for XCode version >= 12 still getting the same error @pichillilorenzo
