### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference

### ISSUE THREAD

**Issue by twopai** [pichillilorenzo/flutter_inappwebview#142]
E/AndroidRuntime(25050): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference
E/AndroidRuntime(25050): 	at io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:195)
E/AndroidRuntime(25050): 	at io.flutter.view.FlutterView.onCreateInputConnection(FlutterView.java:397)
E/AndroidRuntime(25050): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1254)
E/AndroidRuntime(25050): 	at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1578)
E/AndroidRuntime(25050): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3653)
E/AndroidRuntime(25050): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25050): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(25050): 	at android.app.ActivityThread.main(ActivityThread.java:6381)
E/AndroidRuntime(25050): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25050): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
E/AndroidRuntime(25050): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

**Comment by twopai** [comment]
Can you help me? This problem has lasted for a long time!

**Comment by wd668944** [comment]
> Can you help me? This problem has lasted for a long time!
Switch to a webview plugin

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
