### ISSUE TITLE
How can I get HTML Source Code from site?

### ISSUE THREAD

**Issue by desmeit** [pichillilorenzo/flutter_inappwebview#1420]
Hello,

I want to detect the html source code (or the html tags) of a page.

I checked this https://github.com/pichillilorenzo/flutter_inappwebview/issues/2#issuecomment-423858427
but `var html = await this.injectScriptCode("document.body.innerHTML");` is not working for me. Is there a complete example?

Thanks and best regards

**Comment by Rustam-Z** [comment]
@desmeit did you solve the problem? Can you please leave your solution here?

**Comment by desmeit** [comment]
@Rustam-Z 
I solved it with https://pub.dev/packages/webview_flutter

Infos here:
https://medium.com/@janithsg/flutter-extract-web-page-html-content-from-webview-1c39e43e675d
