### ISSUE TITLE
Android Q Beta 6 Keyboard Wont Open

### ISSUE THREAD

**Issue by robisaks** [pichillilorenzo/flutter_inappwebview#143]
The keyboard works fine in other versions of android, but on Android Q beta 6, the keyboard wont open, and the below error is shown in the debug console. This appears to be different than other keyboard issues, so I created a separate issues.

` W/InputMethodManager(25621): b/117267690: Display ID mismatch found. ViewRootImpl displayId=54 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
W/InputMethodManager(25621): java.lang.Throwable
W/InputMethodManager(25621): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:537)
W/InputMethodManager(25621): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1578)
W/InputMethodManager(25621): 	at org.chromium.content.browser.input.ImeAdapterImpl.o(PG:314)
W/InputMethodManager(25621): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(PG:207)
W/InputMethodManager(25621): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/InputMethodManager(25621): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/InputMethodManager(25621): 	at android.os.Looper.loop(Looper.java:174)
W/InputMethodManager(25621): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/InputMethodManager(25621): 	at java.lang.reflect.Method.invoke(Native Method)
W/InputMethodManager(25621): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/InputMethodManager(25621): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
