### ISSUE TITLE
How to close the in-app browser programmatically 

### ISSUE THREAD

**Issue by fathah** [pichillilorenzo/flutter_inappwebview#1434]
Hey, 
I have been using this package for a while.  I want to know (if it's already available\request a feature) how to close the in-app webview called using  `launch` function.

*Function*:
```java
  try {
    await launch(
      'URL_HERE',
      customTabsOption: const CustomTabsOption(
        toolbarColor: Color(0xff000000),
        enableDefaultShare: false,
        enableUrlBarHiding: true,
        showPageTitle: true,
        extraCustomTabs: <String>[
          'org.mozilla.firefox',
          'com.microsoft.emmx',
        ],
      ),
      safariVCOption: const SafariViewControllerOption(
        preferredBarTintColor: Color(0xff000000),
        preferredControlTintColor: Colors.white,
        barCollapsingEnabled: true,
        entersReaderIfAvailable: false,
        dismissButtonStyle: SafariViewControllerDismissButtonStyle.close,
      ),
    );
  } catch (e) {
    print(e.toString());
  }
```
![Screenshot 2022-11-21 101451](https://user-images.githubusercontent.com/48355244/202967689-1656eea4-8a0c-4111-ab6e-54cb329dd751.png)

I'hv marked it in the above image. The event called when the X button is clicked should be called programmatically.

**Comment by pichillilorenzo** [comment]
It's already implemented! Use the [close](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/ChromeSafariBrowser/close.html) method of your `ChromeSafariBrowser` instance.

**Comment by srinad** [comment]
Hi, Used browser.close() function, its working on most of devices but we found its not working on MI devices. Please check it once.

**Comment by zanelladev** [comment]
Can you help me? I have a code when i need open and close the browser, just to clean the cookies of my website from the default navigatior.

`await browser.open(
          url: inAppWebView.WebUri('http://172.10.254.39:51671/auth/signout'));

      //browser.close();`
      
   if i don't use .close(), don't close, of couse. but when i use the close(), don't close anyways, and if i close manuality, the screen turns all black.

**Comment by zanelladev** [comment]
Can you help me? I have a code when i need open and close the browser, just to clean the cookies of my website from the default navigatior.

```
await browser.open(
          url: inAppWebView.WebUri('http://example.com/'));

      //browser.close();
```
      
   if i don't use .close(), don't close, of couse. but when i use the close(), don't close anyways, and if i close manuality, the screen turns all black.

**Comment by zanelladev** [comment]
same problem, works on most cell phones, but not on Xiaomi
