### ISSUE TITLE
Bug when set useHybridComposition to true

### ISSUE THREAD

**Issue by Payalpatel-wrteam** [pichillilorenzo/flutter_inappwebview#1435]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |   3.3.8            |
| Plugin version  |       5.7.1+2        |
| Android version |     31          |
| iOS version     |               |
| macOS version   |       12.4        |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:**  When navigate to new tab in screen, it should navigate smoothly

**Current behavior:** I have used Pageview for battom navigation items.  when navigate to new screen from webview screen in which i have set 'useHybridComposition' to true, my splash screen blinks in middle for some seconds. It gives very bad user experience. If i set 'useHybridComposition' to false then this issue dont persist. And even in version like 5.4.3+7 , this issue not persist at all.

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
Starting from `5.7.0`, Hybrid composition uses a new native Flutter API.
As you can read on the official repo of Flutter [here](https://github.com/flutter/flutter/wiki/Hybrid-Composition#performance):

> Prior to Android 10, Hybrid composition copies each Flutter frame out of the graphic memory into main memory and then copied back to a GPU texture. As this copy happens per frame, the performance of the entire Flutter UI may be impacted.

**Comment by pichillilorenzo** [comment]
Unfortunately, that's how Flutter Hybrid Composition works.
In older flutter versions, Hybrid Composition was required for the pull-to-refresh feature otherwise it would be very laggy without it.
I should test again if it is still laggy or not with Flutter 3 and without Hybrid Composition, and if it works, I could release a new version to remove this requirement.
Currently, it's required.

**Comment by Payalpatel-wrteam** [comment]
Thank you sir
