### ISSUE TITLE
Phyiscal keyboard arrow keys don't work.

### ISSUE THREAD

**Issue by nawbc** [pichillilorenzo/flutter_inappwebview#1444]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |      3.3.7         |
| Plugin version  |       6.0.0-beta18 & 5.7.x        |
| Android version |      12         |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

**Current behavior:** 
Phyiscal keyboard arrow left up... key doesn't work. After that all the keys doesn't work.
`webview_flutter` has the same issue.

Relate to https://github.com/flutter/flutter/issues/74044

## Images   
![录制_2022_11_30_14_20_11_889](https://user-images.githubusercontent.com/45007226/204723093-23e13e25-377b-41a0-9f35-c4baa4e93929.gif)

**Comment by razfazz** [comment]
having the same issue

**Comment by lirantzairi** [comment]
Same issue here

**Comment by lirantzairi** [comment]
For reference, I think the related webview_flutter's issue is https://github.com/flutter/flutter/issues/102505

**Comment by nawbc** [comment]
> For reference, I think the related webview_flutter's issue is https://github.com/flutter/flutter/issues/102505

My mistake, i collected part of relate issues https://github.com/flutter/flutter/issues/118309#issuecomment-1378437104

This is a flutter engine bug. It seems like FlutterView dispatchKeyEvent doesn't send data to PlatformView on Android.
