### ISSUE TITLE
Please add webviewfeature  userscript for android in version 5

### ISSUE THREAD

**Issue by Imdavyking** [pichillilorenzo/flutter_inappwebview#1446]
## Environment

**Flutter version:** 
**Plugin version:**  version 5
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 
 I have seen that userscripts works well on version  6 for android, please could you also add the userscripts webview feature for version 5 of flutter in app webview,or please explain how I can do it on version 5

**Alternatives you've considered:**   

**Images:**

**Comment by pichillilorenzo** [comment]
There is already User Script feature for version 5: https://inappwebview.dev/docs/5.x.x/webview/javascript/user-scripts

**Comment by Imdavyking** [comment]
please how can i use this WebViewFeature.DOCUMENT_START_SCRIPT in version 5.

**Comment by pichillilorenzo** [comment]
It’s available only on version 6

**Comment by Imdavyking** [comment]
ok thank you
