### ISSUE TITLE
Cannot Grant Permission at Android 21 

### ISSUE THREAD

**Issue by GitMustafaAksoy** [pichillilorenzo/flutter_inappwebview#1447]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.3.8        |
| Plugin version  |         any      |
| Android version |       Api 21       |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 
Asus k012_2 SM | Samsung SM-N9000Q
## Description
**Expected behavior:** 
Same code for WEB RTC works fine at Android Api level 23 and greater levels, but at api level 21 the devices cannot grant microphone permission.
**Current behavior:** 
The devices cannot grant microphone permission at api level 21.
## Steps to reproduce

```
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:permission_handler/permission_handler.dart';


Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Permission.camera.request();
  await Permission.microphone.request();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MainPage(),
    );
  }
}


class MainPage extends StatefulWidget {
  const MainPage({Key? key}) : super(key: key);

  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
      children: [
          ElevatedButton(
            onPressed: () {
              Navigator.push(context, MaterialPageRoute(builder: (context) => CallApp()));
            },
            child: Text('call'),
          )
      ],
    ),
        ));
  }
}

class CallApp extends StatefulWidget {
  @override
  _CallAppState createState() => new _CallAppState();
}

class _CallAppState extends State<CallApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: InAppWebViewPage()
    );
  }
}

class InAppWebViewPage extends StatefulWidget {
  @override
  _InAppWebViewPageState createState() => new _InAppWebViewPageState();
}

class _InAppWebViewPageState extends State<InAppWebViewPage> {
  late InAppWebViewController _webViewController;


  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: const Text("InAppWebView")
        ),
        body: Container(
            child: Column(children: <Widget>[
              Expanded(
                child: Container(
                  child: InAppWebView(
                      initialData: InAppWebViewInitialData(data: '''
<html>                                   
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
  <body>
      <script type="text/javascript" src="test.com.js"></script>
  <script type="text/javascript">
      startScript({
        client_data: {PhoneNumber: "XXXXXXXXXXXX", id: "XXXX"}});</script>
  </body>
  </html>'''),

                      initialOptions: InAppWebViewGroupOptions(
                        android: AndroidInAppWebViewOptions(hardwareAcceleration: false,
                        ),
                        crossPlatform: InAppWebViewOptions(
                          mediaPlaybackRequiresUserGesture: false,
                          javaScriptEnabled: true,
                          allowFileAccessFromFileURLs: true,
                          javaScriptCanOpenWindowsAutomatically: true,
                          allowUniversalAccessFromFileURLs: true,
                        ),
                      ), onWebViewCreated: (InAppWebViewController controller) {
                        _webViewController = controller;

                      },
                      androidOnPermissionRequest: (InAppWebViewController controller, String origin, List<String> resources) async {
                        return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
                      }
                  ),
                ),
              ),
            ])
        )
    );
  }
}
```

**Comment by pichillilorenzo** [comment]
On Android, `onPermissionRequest` for plugin version 6 and `androidOnPermissionRequest` for plugin version 5 are available only starting from Android SDK 23+ (check the Android
Official API - WebChromeClient.onPermissionRequest: https://developer.android.com/reference/android/webkit/WebChromeClient#onPermissionRequest(android.webkit.PermissionRequest)

**Comment by pichillilorenzo** [comment]
On Android, `onPermissionRequest` for plugin version 6 and `androidOnPermissionRequest` for plugin version 5 are available only starting from Android SDK 23+.
Check the API Reference:
- Version 6: https://pub.dev/documentation/flutter_inappwebview/6.0.0-beta.18/flutter_inappwebview/WebView/onPermissionRequest.html
- Version 5: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/WebView/androidOnPermissionRequest.html

**Comment by GitMustafaAksoy** [comment]
I want to be sure what I understand, could you please clarify that for me? In native development, this [information](https://developer.android.com/reference/android/webkit/WebChromeClient#onPermissionRequest(android.webkit.PermissionRequest)) "onPermissionRequest method" is avaible for api 21+, but not avaible for flutter_inappwebview api 23<=? So I need native development.

**Comment by pichillilorenzo** [comment]
Ah wow, for some strange reason, the Android Studio IDE was telling me it was 23 and not 21.
Well, I will release a new version 6 and new version 5 with that fix

**Comment by GitMustafaAksoy** [comment]
Thank you in advance for your help, I will wait for your new release.

**Comment by pichillilorenzo** [comment]
Released new version `6.0.0-beta.19` and new version `5.7.2+1`.

**Comment by GitMustafaAksoy** [comment]
Thank you for your time, the fastest release ever in the world :) I’m going to test it in api 21 devices, tomorrow.

**Comment by GitMustafaAksoy** [comment]
The release has been tested in the devices, and works well. Thank you again.
