### ISSUE TITLE
HeadlessInAppWebView not working on emulator

### ISSUE THREAD

**Issue by TheCarpetMerchant** [pichillilorenzo/flutter_inappwebview#1448]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |         3.3.8      |
| Plugin version  |        5.7.2+1       |
| Android version |       API 31        |
| iOS version     |        /       |
| macOS version   |        /       |
| Xcode version   |       /        |

Device information: Pixel 2 emulator

## Description

**Expected behavior:** 
Webview loads.

**Current behavior:** 
Nothing happens. None of the callbacks are called.

## Steps to reproduce

```
Future<void> test() async {
    headlessWebView = HeadlessInAppWebView(
      initialUrlRequest: URLRequest(url: Uri.parse('https://www.google.com')),
      onWebViewCreated: (controller) {
        print('onWebViewCreated');
      },
      onLoadStart: (controller,_) {
        print('onLoadStart');
      },
      onLoadStop: (controller,_) async {
        print('onLoadStop');
        String? html = await controller.getHtml();
        final doc = parse(html ?? 'nothing');
        headlessWebView.dispose();
      },
    );
  }
```

**Comment by pichillilorenzo** [comment]
Well, you need to `headlessWebView.run();` it.

**Comment by TheCarpetMerchant** [comment]
Ah, might be good to mention this in the docs (like, at the top of the docs) and in the dartdoc comment of the class. Thanks !
