### ISSUE TITLE
flutter_inappbrowser.modulemap' not found

### ISSUE THREAD

**Issue by justinsuny** [pichillilorenzo/flutter_inappwebview#145]
flutter_inappbrowser: ^1.2.1 + onesignal_flutter: ^2.0.2
I am using  packages.
error ios : 
/Library/Developer/Xcode/DerivedData/Runner-cgoqmbcrddvqgsefiddanmmsjbry/Build/Products/Debug-iphonesimulator/flutter_inappbrowser/flutter_inappbrowser.modulemap' not found

flutter create -i swift 'project name' 

Profile

target 'Runner' do
  use_frameworks!  # required by simple_permission
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

I tried the above methods but got the same error.

Is there a solution?

**Comment by pichillilorenzo** [comment]
Try to clean the project and install the latest version of this plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
