### ISSUE TITLE
Live broadcast opens instead of camera on IOS

### ISSUE THREAD

**Issue by CartmanGD** [pichillilorenzo/flutter_inappwebview#1452]
Whenever the user starts a video recording in the app, it accidentally redirects them to a live broadcast instead of the camera.

![ezgif com-gif-maker-4](https://user-images.githubusercontent.com/110026289/204847285-712dd4f3-00e1-44b2-99fb-ea501eb59dcd.gif)

Flutter doctor:

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale en-IL)                                                                                         Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

IOS version: 15.2.1

Link to StackOverflow discussion:
https://stackoverflow.com/questions/73320367/flutter-inappwebview-ios-goes-to-live-broadcast-instead-of-camera

**Comment by pichillilorenzo** [comment]
I think it's related to how native WKWebView interprets the video stream element when requested by the web page.
I don't have control over showing or not the "Live Broadcast", it's a decision taken by the WKWebView itself and not mine.

Check this [answer on Stackoverflow](https://stackoverflow.com/a/65892906/4637638).
Has the `video` HTML element the `playsinline` attribute??

**Comment by pichillilorenzo** [comment]
I'm closing this issue in favor of #1248
