### ISSUE TITLE
How can I make sure the page load is complete? onLoadStop called twice on Android

### ISSUE THREAD

**Issue by onurgunes** [pichillilorenzo/flutter_inappwebview#1453]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  3.3.2             |
| Plugin version  |  5.7.2+2             |
| Android version |  12 and 8             |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: Samsung S21 and Samsung S7

## Description

**Expected behavior:** 
Call onLoadStop once when page load finished.
**Current behavior:** 
onLoadStop called twice on Android (on iOS, onLoadStop called one time as expected)

## Steps to reproduce

1. Implement inappwebview as sample code
2. Check printed messages in console
```
final Set<Factory<OneSequenceGestureRecognizer>> _gestureRecognizers = {const Factory(EagerGestureRecognizer.new)};
  final UniqueKey _webViewKey = UniqueKey();

  InAppWebViewController? webViewController;
  final InAppWebViewGroupOptions _webviewOptions = InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(useShouldOverrideUrlLoading: true, mediaPlaybackRequiresUserGesture: false),
    android: AndroidInAppWebViewOptions(useHybridComposition: true),
  );

  @override
  Widget build(BuildContext context) {
    return BlocProvider<XBloc>(
      create: (context) => getIt.get<XBloc>(),
      child: BlocConsumer<XBloc, XState>(
        listener: (context, state) {
          if (state is LoginFailedState) {
          } else if (state is LoginCompletedState) {}
        },
        builder: (context, state) {
          return InAppWebView(
            gestureRecognizers: _gestureRecognizers,
            initialOptions: _webviewOptions,
            initialUrlRequest: URLRequest(url: Uri.parse(context.read<XBloc>().requestUrl)),
            key: _webViewKey,
            onWebViewCreated: (controller) => webViewController = controller,
            onLoadError: (controller, url, code, message) => log('onLoadError ${url.toString()}, $code $message'),
            onLoadStart: (controller, url) => log('onLoadStart ${url.toString()}'),
            onLoadStop: (controller, url) async {
              log('onLoadStop ${url.toString()}');
              final redirectUrl = context.read<XBloc>().redirectUrl;
              if (url.toString().startsWith(redirectUrl)) {
                BlocProvider.of<XBloc>(context).add(GetAccessEvent(url.toString()));
              }
            },
            onReceivedServerTrustAuthRequest: (InAppWebViewController controller, URLAuthenticationChallenge challenge) async {
              return ServerTrustAuthResponse(action: ServerTrustAuthResponseAction.PROCEED);
            },
          );
        },
      ),
    );
  }
```

**Comment by pichillilorenzo** [comment]
From this issue on Stackoverflow "[Android - Webview onPageFinished Called Twice](https://stackoverflow.com/questions/18282892/android-webview-onpagefinished-called-twice)", it seems related to how Chromium WebView is implemented on native side by Android (check this [answer](https://stackoverflow.com/a/46298285/4637638)).

For your use case, I think you have 2 options:
- use `onProgressChanged` and check when the `progress == 100` to execute your code.
- use a boolean flag inside `onLoadStop` to check if that part of code has been already executed.

**Comment by sametsariyildiz** [comment]
Hello my friends,

The solution best way;

Problem --> Android device onPagefinished  calling twice. (At the IOS device has not problem)

Solution --> Before OnLoadStop You can Call onLoadStart method that  define bool param in this section.
