### ISSUE TITLE
Android plugin version 6 - UserScripts not executing on new tabs.

### ISSUE THREAD

**Issue by Imdavyking** [pichillilorenzo/flutter_inappwebview#1455]
userscript works well, but once a new tab is open by javascript, or a new tab is opened manually, the Userscripts does not execute on that webview.

 initialUserScripts: UnmodifiableListView([
                UserScript(
                  source: widget.provider + initJs,
                  injectionTime: UserScriptInjectionTime.AT_DOCUMENT_START,
                )
              ]),

**Comment by pichillilorenzo** [comment]
Released new version `6.0.0-beta.21` with the fix

**Comment by Imdavyking** [comment]
Thank you so much,I appreciate
