### ISSUE TITLE
Cannot get desktop mode

### ISSUE THREAD

**Issue by TheCarpetMerchant** [pichillilorenzo/flutter_inappwebview#1458]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.3.8        |
| Plugin version  |       5.7.2+1        |
| Android version |        API 31       |
| iOS version     |        /       |
| macOS version   |      /         |
| Xcode version   |      /         |

Device information: Pixel 2 emulator

Here are the options I have activated :
```
HeadlessInAppWebView headlessWebView = HeadlessInAppWebView(
    initialUrlRequest: URLRequest(
      url: Uri.parse('https://www.fanfiction.net/'),
    ),
    initialOptions: InAppWebViewGroupOptions(
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
        useWideViewPort: false,
        supportMultipleWindows: true,
      ),
      crossPlatform: InAppWebViewOptions(
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
        preferredContentMode: UserPreferredContentMode.DESKTOP,
      ),
    ),
  );
```

Using the Chrome app on the emulator, I get the website in desktop mode just fine, so it is the Android Webview that doesn't communicate the correct informations to the website.

**Comment by TheCarpetMerchant** [comment]
@pichillilorenzo After investigating further, it seems the webview doesn't have the same behavior as browsers. Calling loadUrl opens a new session from the point of view of Cloudflare. How can I emulate the behavior of navigating to a new page ?

**Comment by erickcchoi** [comment]
Same issue here, just change the above code's url to www.olevod.com, the example above cannot get desktop mode.
