### ISSUE TITLE
useShouldOverrideUrlLoading is broken for InAppWebView

### ISSUE THREAD

**Issue by peter-meemo** [pichillilorenzo/flutter_inappwebview#146]
On ios: the provided `shouldOverrideUrlLoading` callback is never called.
On android: the browser sometimes returns empty pages.

**Comment by YudiH** [comment]
Any solutions for this? Having the same issue when I put useShouldOverrideUrlLoading": true in initialOptions. Empty/blank page. Loads fine when I remove that option.

I'm trying to find a solution to listen to url changes. Is there a workaround for this plugin? Or is the alternative only in finding/using some other plugin?

Cheers

**Comment by YudiH** [comment]
For now, my bandage solution is listening to the url change inside onLoadStart, seems to fire everytime a diff url has to load.

**Comment by pcegarra** [comment]
@YudiH im using onLoadStart on ios and seems not working, only the first time, Can you show me your code please?

**Comment by YudiH** [comment]
@pcegarra 
![image](https://user-images.githubusercontent.com/45711925/65547027-de2f7b00-df42-11e9-8618-b941de540229.png)

That's all I did. Made a function that takes the loaded url and do with it whatever you need.
You could add a print() to check whenever it fires. Should help you understand how it works on ios. I personally am testing this on Android. So I can't help you there, sorry. Hope this helps.

**Comment by pichillilorenzo** [comment]
Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.

**Comment by ductranit** [comment]
@pichillilorenzo 
I can confirm this issue still happen on iOS with the latest version  in my `pubspec.yaml`: ` flutter_inappwebview: ^2.1.0+1`
Here is my code:
```
InAppWebView(
          initialUrl: "https://www.google.com",
          initialOptions: InAppWebViewWidgetOptions(inAppWebViewOptions: InAppWebViewOptions(useShouldOverrideUrlLoading: true, useOnLoadResource: true)),
          onLoadStop: (InAppWebViewController controller, String url) {
            hideLoading();
          }, shouldOverrideUrlLoading: (InAppWebViewController controller, String url) {
              LogUtil.v("shouldOverrideUrlLoading $url");
          })
```

**Comment by pichillilorenzo** [comment]
@ductranit Do you mean at the first load or also when you navigate other links?

In the first load, the `shouldOverrideUrlLoading` event is not called (that's because both Android and iOS platforms don't call this event in their webview implementation).

**Comment by ductranit** [comment]
@pichillilorenzo ok, so it isn't called on the first time.
When user clicks on an url, it works
But when website is navigated by javascript, `shouldOverrideUrlLoading` isn't called.
For example, my app uses azure b2c authenticate, after user login, it navigates to https://jwt.ms to get the token, only the `onLoadStop` works (but I need to handle url before it loads).  I tried the plugin https://pub.dev/packages/webview_flutter 
 and it can catch all the navigation in the `navigationDelegate` callback.

**Comment by pichillilorenzo** [comment]
@ductranit then you can try the `onNavigationStateChange` event. As the [documentation](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebView/onNavigationStateChange.html) says:

> Event fired when the navigation state of the InAppWebView changes throught the usage of javascript History API functions (pushState(), replaceState()) and onpopstate event.
>
> Also, the event is fired when the javascript window.location changes without reloading the webview (for example appending or modifying an hash to the url).

Let me know

**Comment by ductranit** [comment]
@pichillilorenzo the `onNavigationStateChange` is never called. I debug & see these events are called when it navigates:
- `onLoadStop`: when the url is loaded completely
- `onProgressChanged`: I use `controller.getUrl()` during the progress changed, but this way isn't stable, sometime the url changes after progress is 100 (page loaded)
- `onLoadResource` - same as onProgressChanged (page loaded)

**Comment by YudiH** [comment]
> Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.


@pichillilorenzo Updated to that version. But a friend that built on ios reported this problem:

CustomeSchemeHandler.swift:22:27: warning:
    expression implicitly coerced from 'String?' to 'Any'
                        print((result as! FlutterError).message

Had to revert back to flutter_inappbrowser 1.2.2 for now

**Comment by kbokarius** [comment]
I have the same issue with federated sign in through Cognito, switching over to https://pub.dev/packages/webview_flutter

**Comment by arnaudelub** [comment]
i'm facing the same issue, i'm using the git url in my pubsec.yaml:
```yaml 
flutter_inappwebview:
  git: 
    url: https://github.com/pichillilorenzo/flutter_inappwebview
```
It's working fine in debug mode, but in release, the souldOverrideUrlLoading is never triggered

**Comment by pichillilorenzo** [comment]
It should work with the new version! Let me know

**Comment by dwiprawira1989** [comment]
Hi I think useShouldOverrideUrlLoading broken again after I updated flutter to stable version 1.22.0.

My workaround is use onLoadStart for android platform and shouldOverrideUrlLoading on iOS

**Comment by lo-re-co** [comment]
It's broken again

**Comment by mozaa-vn** [comment]
> It's broken again
I'm using version 5.3.2 and it works perfectly

**Comment by aamir-nazir** [comment]
I'm using version 5.3.2. It's neither working in Android nor in iOS.

@pichillilorenzo any plans to fix it?

**Comment by Zamaruu** [comment]
> I'm using version 5.3.2 and it works perfectly

Can you share your code please?

**Comment by aamir-nazir** [comment]
> > I'm using version 5.3.2 and it works perfectly
> 
> Can you share your code please?

I managed to get it working. I was missing something. Thank you for the quick reply.

**Comment by mozaa-vn** [comment]
> > I'm using version 5.3.2 and it works perfectly
> 
> Can you share your code please?

I just follow the document, here is my code:
```java
shouldOverrideUrlLoading: (controller, navigationAction) async {
  final uri = navigationAction.request.url!;
  print("uri = " + uri.toString());
  if (uri.toString().contains(GameRoute.GAME_COMPLETE)) {
    //
    return NavigationActionPolicy.CANCEL;
  }
  return NavigationActionPolicy.ALLOW;
},
```

**Comment by mrgulshanyadav** [comment]
It's not working for me too in iOS.

**Comment by djks74** [comment]
Its broken.

why there is none perfect webview plugin in this world? :-(

**Comment by SCaptainCAP** [comment]
Why is this issue closed? It does not work for now

**Comment by dwikurniantom** [comment]
@bakatsuyuki DUDE! you save me a lot of time. Thanks man, i appreciate it, really.
<img src="https://media.giphy.com/media/ZEvw9evrRxNP4kQ3RR/giphy.gif">

**Comment by thapli9A** [comment]
@kouchi32 : This only works when you are openning any new page. If you come back, it doesn't work
