### ISSUE TITLE
Client Certificate authentication not working as in Chrome.

### ISSUE THREAD

**Issue by darsh-shah-ub** [pichillilorenzo/flutter_inappwebview#1465]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |    Channel stable, 3.3.9, on macOS 11.6 20G165 darwin-arm, locale en-IN           |
| Plugin version  |     5.7.2+2          |
| Android version |       12.0        |
| iOS version     |       16.0        |
| macOS version   |       --        |
| Xcode version   |      Version 13.2.1 (13C100)         |

Device information:  iPhone 13  

## Description
I have enrolled my device to MS Intune which is an MDM solution, while I try to authenticate my user through Safari/Chrome it works perfectly fine, but as soon as I use InAppWebBrowser to authenticate it gives me a 53003 error which is a Device not enrolled error in Intune.

I have tried using `onReceivedClientCertRequest` but since various devices have different PKCS certificates, I wouldn't be able to add all assets certificates in the app. 

**Expected behavior:** 
The user should be authenticated from the InAppWebBrowser while using Azure Intune.

**Current behavior:** 
The user is not being authenticated.

## Steps to reproduce

1. Enroll, the device in an MDM solution. And try to authenticate the user from the server.
2. Check the user is able to log in.

## Stacktrace/Logcat   

... [error:aw_contents client bridge.cc(239)] no client certificate selected.

-- This was the last statement after the screen went to loading state.

**Comment by darsh-shah-ub** [comment]
Yes! I have checked the documentation and even the previous closed issue. None of them matches my current issue.

**Comment by darsh-shah-ub** [comment]
@pichillilorenzo  any update on this?

**Comment by pichillilorenzo** [comment]
I don't know how MDM works, however, a WebView is not a browser such as Chrome, Firefox, or Safari.
They are browsers with different and complex native capabilities. 

Also, the [`InAppBrowser`](https://inappwebview.dev/docs/in-app-browsers/in-app-browser) class represents just a native WebView displayed on top of the Flutter App, that is not integrated into the Flutter widget tree. It's not a full-featured browser such as Chrome, Firefox, or Safari.

Probably, you should use something else for your use case (maybe, there is a plugin for MDM, I don't know) or let the user upload the PKCS certificate to make the authentication using the `onReceivedClientCertRequest` event.

That's something you should handle by yourself.
