### ISSUE TITLE
Flutter Web crashes with TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

### ISSUE THREAD

**Issue by Binozo** [pichillilorenzo/flutter_inappwebview#1468]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.3.9        |
| Plugin version  |       6.0.0-beta.21        |
| Android version |               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: Microsoft Edge 108.0.1462.46 and Firefox 107

## Description

**Expected behavior:** 

Normal application startup on Flutter Web

**Current behavior:** 

Application doesn't start, loads forever.

## Steps to reproduce

1. Setup a Flutter Web Project
2. Follow flutter_inappwebview documentation for setting up web
3. Start your web application

## Stacktrace/Logcat   
```
TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
packages/flutter_inappwebview/src/web/web_platform.dart 33:5                                                                   registerWith
web_plugin_registrant.dart 22:34                                                                                               registerPlugins
web_entrypoint.dart 27:24                                                                                                      <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/initialization.dart 73:24                                  <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/initialization.dart 71:16                                  <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 398:10  callMethod
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 402:5   dsend
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/app_bootstrap.dart 27:18                       autoStart
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future.dart 528:22                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                         callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15               <fn>

```

**Comment by ayushkadbe** [comment]
@Binozo What's the solution?

**Comment by Binozo** [comment]
> @Binozo What's the solution?

@ayushkadbe my Problem was not related with the package. I made a rollback to the latest stable release (5.x.x). But the error was caused by an crash of my code in my application

**Comment by sugur** [comment]
I have same problem on flutter_inappwebview: ^6.0.0-beta.22.
How to fix this problem?

TypeError: Cannot set properties of undefined (setting 'nativeCommunication') TypeError: Cannot set properties of undefined (setting 'nativeCommunication') packages/flutter_inappwebview/src/web/web_platform.dart 33:5                      registerWith web_plugin_registrant.dart 23:34                                                  registerPlugins web_entrypoint.dart 27:24                                                         <fn> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall

**Comment by sischnei** [comment]
For me - updating the index.html was necessary, make sure to add


    <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>


to the web/index.html file (in the <head> section).

**Comment by xdkaka** [comment]
+1

**Comment by sugur** [comment]
> For me - updating the index.html was necessary, make sure to add
> 
> ```
> <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
> ```
> 
> to the web/index.html file (in the section).

OK, I use it to work. 
Thanks

**Comment by oscardcd** [comment]
> For me - updating the index.html was necessary, make sure to add
> 
> ```
> <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
> ```
> 
> to the web/index.html file (in the section).

it works for me!

**Comment by t0uh33d** [comment]
if someone is still facing this issue and are depending on the version (6.0.0-beta.30)[https://pub.dev/packages/flutter_inappwebview/versions/6.0.0-beta.30] or later

Add this line in the `head` tag of your `index.html`

```html
    <script
      type="application/javascript"
      src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
      defer
    ></script>
```

**Comment by Mounix99** [comment]
Small note: make sure you have placed above solution in the end of `head` tag

**Comment by sujit471** [comment]
> If someone is still facing this issue and is depending on the version [6.0.0-beta.30](https://pub.dev/packages/flutter_inappwebview/versions/6.0.0-beta.30) or later
> 
> Add this line in the `head` tag of your `index.html`
> 
> ```
>     <script
>       type="application/javascript"
>       src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
>       defer
>     ></script>
> ```

Thanks a lot ☺️☺️

**Comment by PrashanthKumarDS-yourdost** [comment]
> For me - updating the index.html was necessary, make sure to add
> 
> ```
> <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
> ```
> 
> to the web/index.html file (in the section).


Its not working for me. Please help

**Comment by sapar-io** [comment]
> > For me - updating the index.html was necessary, make sure to add
> > ```
> > <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the web/index.html file (in the section).
> 
> Its not working for me. Please help
It works for me too, just paste it before </head>

**Comment by sapar-io** [comment]
One big problem with this code snippet, its dissapear every time in index.html after flutter clean command

**Comment by mirza-d3x** [comment]
> > > For me - updating the index.html was necessary, make sure to add
> > > ```
> > > <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to the web/index.html file (in the section).
> > 
> > 
> > Its not working for me. Please help
> 
> It works for me too, just paste it before

can you give me an example for where should I place this code
I tried but it's doesn't works for me

**Comment by mirza-d3x** [comment]
> @sapar-io @mirza-d3x
> 
> make sure to add the line in `web/index.html` and not `build/web/index.html`

I did that but it's not working for me
is it necessary to do flutter clean & flutter pub get after add this

**Comment by t0uh33d** [comment]
No, it is not. What exact issue are you facing? Is the screen going blank on launch?

**Comment by mirza-d3x** [comment]
<img width="493" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/85556071/1201d41f-8be9-4ab8-9078-2d55ce2dcce0">
<img width="770" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/85556071/8894e327-1e6a-4c44-840d-ae6ae7250c30">

this is the issue I'm facing

**Comment by mirza-d3x** [comment]
> No, it is not. What exact issue are you facing? Is the screen going blank on launch?

I added some screenshots of my issue could you check that

**Comment by oukpov** [comment]
for me,when i met this problem by added pakage, Example: flutter_inappwebview_web: ^1.0.8 and aba_payment: ^0.0.3 etc, becuase when i build web application ,i imported many package, like this i met it by pakage​ floor pakage

**Comment by t0uh33d** [comment]
@mirza-d3x which version of flutter_inappwebview_web are you using?

**Comment by mirza-d3x** [comment]
> @mirza-d3x which version of flutter_inappwebview_web are you using?

Version 6.0.0

**Comment by mirza-d3x** [comment]
> @mirza-d3x 
>     
>     <script
>       type="application/javascript"
>       src="/assets/packages/flutter_inappwebview_web/lib/assets/web/web_support.js"
>       defer
>     ></script>
>     
>     try to add this in <head> tag of your web/index.html

I added this tag but it's not working

**Comment by minhaj123456** [comment]
Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

**Comment by Akash-ptl** [comment]
same Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

**Comment by kkalisz** [comment]
Same here

**Comment by poringe** [comment]
> Same here it looks that "web_support.js" is not present in the asset folder
> 
> ```
>    GET http://localhost:5300/assets/packages/flutter_inappwebview/assets/web/web_support.js net::ERR_ABORTED 404 (Not Found)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/5392781/309073059-23f3c98d-2765-4366-8c8c-38a494a734c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTQwMDcsIm5iZiI6MTcwOTYxMzcwNywicGF0aCI6Ii81MzkyNzgxLzMwOTA3MzA1OS0yM2YzYzk4ZC0yNzY1LTQzNjYtOGM4Yy0zOGE0OTRhNzM0YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDQ0MTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU5MGQ4NmU3NTg5NzNmOGU5M2I5NTVlNWZjNGUxZWMxZTYxNWZmMWQ4ODk0ODE4MDFmNDEzMzNiMGVhNTdjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1f9D1ZFEcaWGQtAnhtaxFZCEZG1STUUOaz7GWzzRTi8)

change this
`assets/packages/flutter_inappwebview/assets/web/web_support.js`

to this
`assets/packages/flutter_inappwebview_web/assets/web/web_support.js`

**Comment by Akash-ptl** [comment]
`<!DOCTYPE html>
<html>
<head>
    <link href=”favicon.ico” rel=”icon”>
    <script
            defer
            src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
            type="application/javascript"
    ></script>

    
    <base href="$FLUTTER_BASE_HREF">

    <meta charset="UTF-8">
    <meta content="IE=Edge" http-equiv="X-UA-Compatible">
    <meta content="A new Flutter project." name="description">

    
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <meta content="bulltrek" name="apple-mobile-web-app-title">
    <link href="icons/Icon-192.png" rel="apple-touch-icon">

    
    <link href="favicon.png" rel="icon" type="image/png"/>

    <title>bulltrek</title>
    <link href="manifest.json" rel="manifest">

    <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = null;


    </script>
    
    <script defer src="flutter.js"></script>
    <style>
      .container {
        width: 100vw;
        height: 100vh;
        display: flex; /* Default Axis is X*/
        justify-content: center; /* Main Axis */
        align-items: center; /* Cross Axis */
      }
      .indicator{
        width: 6vw;
      }


    </style>
</head>
<body>
<div class="container" id="loading_indicator">
    <img class="indicator" src="./assets/images/loading-main.gif"/>
</div>
<script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });


</script>
</body>
</html>
`

This is my index.html file

This is the Log

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:61657/sqEb_22LQhw=/ws
Debug service listening on ws://127.0.0.1:61657/sqEb_22LQhw=/ws
Debug service listening on ws://127.0.0.1:61657/sqEb_22LQhw=/ws
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

**Comment by sebastianbuechler** [comment]
> > Same here it looks that "web_support.js" is not present in the asset folder
> > ```
> >    GET http://localhost:5300/assets/packages/flutter_inappwebview/assets/web/web_support.js net::ERR_ABORTED 404 (Not Found)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/5392781/309073059-23f3c98d-2765-4366-8c8c-38a494a734c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTQwMDcsIm5iZiI6MTcwOTYxMzcwNywicGF0aCI6Ii81MzkyNzgxLzMwOTA3MzA1OS0yM2YzYzk4ZC0yNzY1LTQzNjYtOGM4Yy0zOGE0OTRhNzM0YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDQ0MTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU5MGQ4NmU3NTg5NzNmOGU5M2I5NTVlNWZjNGUxZWMxZTYxNWZmMWQ4ODk0ODE4MDFmNDEzMzNiMGVhNTdjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1f9D1ZFEcaWGQtAnhtaxFZCEZG1STUUOaz7GWzzRTi8)
> 
> change this `assets/packages/flutter_inappwebview/assets/web/web_support.js`
> 
> to this `assets/packages/flutter_inappwebview_web/assets/web/web_support.js`
> 
> add/edit this script in web/index.html
> 
> ```
> <script
>   type="application/javascript"
>   src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
>   defer
> ></script>
> ```
Thanks!

Here's the change for version >= 6.0.0 in the official docs: https://inappwebview.dev/docs/intro/#setup-web

**Comment by PrashanthKumarDS-yourdost** [comment]
> > Same here it looks that "web_support.js" is not present in the asset folder
> > ```
> >    GET http://localhost:5300/assets/packages/flutter_inappwebview/assets/web/web_support.js net::ERR_ABORTED 404 (Not Found)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/5392781/309073059-23f3c98d-2765-4366-8c8c-38a494a734c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTQwMDcsIm5iZiI6MTcwOTYxMzcwNywicGF0aCI6Ii81MzkyNzgxLzMwOTA3MzA1OS0yM2YzYzk4ZC0yNzY1LTQzNjYtOGM4Yy0zOGE0OTRhNzM0YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDQ0MTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU5MGQ4NmU3NTg5NzNmOGU5M2I5NTVlNWZjNGUxZWMxZTYxNWZmMWQ4ODk0ODE4MDFmNDEzMzNiMGVhNTdjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1f9D1ZFEcaWGQtAnhtaxFZCEZG1STUUOaz7GWzzRTi8)
> 
> change this `assets/packages/flutter_inappwebview/assets/web/web_support.js`
> 
> to this `assets/packages/flutter_inappwebview_web/assets/web/web_support.js`
> 
> add/edit this script in web/index.html
> 
> ```
> <script
>   type="application/javascript"
>   src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
>   defer
> ></script>
> ```

Thank you so much it worked for me.

**Comment by ahmedmahershaaban** [comment]
make sure you  have added this package first in pubspec.yaml
https://pub.dev/packages/flutter_inappwebview_web
then add this line 
<script  type="application/javascript"  src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"  defer></script>

**Comment by Sahilkumar420** [comment]
<script
      type="application/javascript"
      src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
      defer
    ></script>
    
    thank you its working

**Comment by ravi2143** [comment]
<script type="application/javascript" src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" defer ></script>

this is working Thank you

**Comment by Sahilkumar420** [comment]
Okays

**Comment by Sahilkumar420** [comment]
Great!

**Comment by GulTaskeen** [comment]
> ```
> <script
>       type="application/javascript"
>       src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
>       defer
>     ></script>
> ```

Thanks!
This worked for me

**Comment by voxoid0** [comment]
I get the same error on version 6.0.0, tried updating the index.html with the above `script` element, as the last part of the `<head>` element, and still get the same error. Any other ideas?

**Comment by robinwesterik** [comment]
> I get the same error on version 6.0.0 (and flutter_inappwebview_web 1.0.8), tried updating the index.html with the above `script` element, as the last part of the `<head>` element, and still get the same error.
> 
> I see three instances of web_support.js in my project's folder, all in the "build" folder, e.g. <my_project_folder>/build/flutter_assets/packages/flutter_inappwebview_web/assets/web/web_support.js
> 
> Any other ideas?

Bump, I currently have the same issue with those versions

**Comment by Sahilkumar420** [comment]
<script type="application/javascript"
src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
defer ></script>
using this

**Comment by philvmx1** [comment]
Workaround if you're still having problems:

Remove `defer` from the script tag. If this loads after main.js you're still hosed. Let it parse inline so it can add the `window.flutter_inappwebview` object.

```
<script type="application/javascript"
src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" ></script>
```


"If the defer attribute is set, it specifies that the script is downloaded in parallel to parsing the page, and executed after the page has finished parsing." (https://www.w3schools.com/tags/att_script_defer.asp)

Solution for the dev team: use some kind of event triggered by web_support.js script to set `nativeCommunication` rather than assuming `window.flutter_inappwebview` is already there.

**Comment by tasibalint** [comment]
I was looking for this for months... for me it worked well in debugger or on local `flutter run -d edge`. <br>
BUT! on my server it didn't! why, because my `https://server.com/web` is the url for the default index, which nginx nincely forwards, but my index.html can not find `<script type="application/javascript"
src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" ></script>` <br>
Solution:
```
  <!-- inAppWebView, for local web --->
<script type="application/javascript"
src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" ></script>
  <!-- inAppWebView, for remote https://server.com/web --->
<script type="application/javascript"
src="/web/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" ></script>
```

How I found this out:
Under developertools/networkcalls looked for web_support.js which had a result of:
```
<meta http-equiv="refresh" content="0;url=https://server.com/web">
```
After fixing `/web` before the `/assets` it worked!
