### ISSUE TITLE
the plugin's methods is not work on iPhone x 12.2

### ISSUE THREAD

**Issue by twopai** [pichillilorenzo/flutter_inappwebview#147]
the plugin's methods is not work on iPhone x 12.2

**Comment by pichillilorenzo** [comment]
Try the latest version of the plugin. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
