### ISSUE TITLE
DeepLink to open an custom URL in InAppWebView (from a push notification)

### ISSUE THREAD

**Issue by chrisvidal** [pichillilorenzo/flutter_inappwebview#1474]
## Environment

**Flutter version:**  3.3.8
**Plugin version:**  5.7.1

## Description

**What you'd like to happen:** 
From a push notification, to open a custom URL  in my InAppWebView app

**Alternatives you've considered:**   
Still digging around deeplink

**Comment by HarishBirlangi242** [comment]
Hello @chrisvidal 
Did you find any solution to do this?

**Comment by chrisvidal** [comment]
Yes, I implemented this package https://pub.dev/packages/uni_links

**Comment by ks1505** [comment]
How? @chrisvidal

**Comment by chrisvidal** [comment]
> How? @chrisvidal

by checking their doc and examples

**Comment by ks1505** [comment]
> > How? @chrisvidal
> 
> by checking their doc and examples


Can you share how you implemented it with inappwebview

**Comment by ks1505** [comment]
> > > How? @chrisvidal
> > 
> > 
> > by checking their doc and examples
> 
> Can you share how you implemented it with inappwebview

nvm
