### ISSUE TITLE
ChromeSafariBrowser only appbar with close button 

### ISSUE THREAD

**Issue by AnkushCodes** [pichillilorenzo/flutter_inappwebview#1477]
## Environment

**Flutter version:** 3 
**Plugin version:**  5.7.2+2
**Android version:**  11

## Description

ChromeSafariBrowser with Appbar with close button with appbar title
hiding title url how to achive this pls help
Thanks

**Comment by ilu55** [comment]
@AnkushCodes can you please share screenshot and url of link for batter to debug
