### ISSUE TITLE
How to use ProxyController with running local HttpServer in android?

### ISSUE THREAD

**Issue by ozexpert** [pichillilorenzo/flutter_inappwebview#1478]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  3.3.6             |
| Plugin version  |  6.0.0-beta.21             |
| Android version |  12             |
| iOS version     | --              |
| macOS version   | 13.0.1              |
| Xcode version   | --              |

Device information: Samsung Galaxy Z Fold 4

## Description

**Expected behavior:** 
If we use HttpServer locally in the mobile app and use ProxyController to use the local HttpServer as a proxy, we expect to access host, uri, and path from the HttpRequest object, but somehow we aren't seeing the expected values being returned.

**Current behavior:** 

the object i have in the html is the img object.
```
<img src="https://images.unsplash.com/photo-1664263679485-c26eaf17559d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60" />
```

printing host port and path, i get `Proxying images.unsplash.com 0 443`
printing the request.uri object i get `images.unsplash.com:443` with no path. port is actually reported as `0`, path has `443`. strangely. 
```
proxyServer = await HttpServer.bind("127.0.0.1", 8081);
proxyServer.listen((HttpRequest request) {
      // Get the hostname from the request headers
      String host = request.headers.host!;
      int reqPort = request.uri.port;
      String reqPath = request.uri.path;

      LogService.log("Proxying $host $reqPort $reqPath");

      ...
    });
```

## Steps to reproduce

1. ProxyController setup 
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // WE SUPPORT ANDROID ONLY
  var proxyAvailable =
      await WebViewFeature.isFeatureSupported(WebViewFeature.PROXY_OVERRIDE);
  if (proxyAvailable) {
    ProxyController proxyController = ProxyController.instance();

    // await proxyController.clearProxyOverride();
    await proxyController.setProxyOverride(
        settings: ProxySettings(proxyRules: [
      ProxyRule(url: "${InternetAddress.loopbackIPv4.address}:8081")
    ], bypassRules: []));
  }

  runApp(const Main());
}
```

2. Add HttpServer logic when the app starts.
```
proxyServer = await HttpServer.bind("127.0.0.1", 8081);
proxyServer.listen((HttpRequest request) {
      // Get the hostname from the request headers
      String host = request.headers.host!;
      int reqPort = request.uri.port;
      String reqPath = request.uri.path;

      LogService.log("Proxying $host $reqPort $reqPath");

      ...
    });
```

3. Using InAppWebView() in the widget that access local index.html that pulls that image. 

Have anyone done anything like this and had a successful result?

**Comment by ozexpert** [comment]
looks like this might not be an issue with the plugin. but i just have lack of knowledge how to process CONNECT method from the proxy server. any advise would be appreciated.

**Comment by ozexpert** [comment]
nvm. this is not a plugin issue, but more of a knowledge how to do HTTP tunneling. Thanks.

**Comment by josuva1211** [comment]
Is it working?

**Comment by josuva1211** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1760. I have raised a similar issue few days back. Can you please look at it?
