### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

### ISSUE THREAD

**Issue by ayushkadbe** [pichillilorenzo/flutter_inappwebview#1479]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |Flutter 3.3.9 • channel stable |
| Plugin version  |flutter.dev 71.1.3 |
| Android version |               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:**  
While running project for web via "flutter run -d chrome". It should show browser screen just like on android apk.

**Current behavior:**
 It loads on chrome, but only shows blank screen, even if go on any other page by changing link.

## Steps to reproduce

1. Clone: https://github.com/pichillilorenzo/flutter_browser_app.git
2. Build Web: 
   flutter config --enable-web
   flutter create .
3. flutter run -d chrome

## Images   
![image](https://user-images.githubusercontent.com/67881141/208051822-40b89c69-56c3-4d29-ad4d-2dfb838f2906.png)

## Chrome Console:   

Flutter Web Bootstrap: Programmatic    js_primitives.dart:30
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'nativeCommunication') web_platform.dart:33 
    at FlutterInAppWebViewWebPlatform.registerWith (web_platform.dart:33:5)
    at Object.registerPlugins (web_plugin_registrant.dart:18:34)
    at web_entrypoint.dart:27:24
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at initialization.dart:73:24
    at Generator.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at _engine.AppBootstrap.new.<anonymous> (initialization.dart:71:16)
    at Object._checkAndCall (operations.dart:334:14)
    at Object.callMethod (operations.dart:398:10)
    at Object.dsend (operations.dart:402:5)
    at _engine.AppBootstrap.new.<anonymous> (app_bootstrap.dart:72:22)
    at Generator.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at app_bootstrap.dart:70:25
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at ret (js_patch.dart:413:11)
    at new Promise (<anonymous>)
    at app_bootstrap.dart:68:14
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at Object.ret [as runApp] (js_patch.dart:413:11)
    at (index):53:26

**Comment by pichillilorenzo** [comment]
The "Flutter Browser App" project doesn't support the web platform.

For the error, ask in https://github.com/pichillilorenzo/flutter_inappwebview/issues/1468 what was the solution.

**Comment by ayushkadbe** [comment]
This isn't an issue of "Flutter Browser App". It's an issue in **web_platform.dart** file in **flutter_inappwebview**. Please  fix it.

**Comment by doppio** [comment]
>  Did you add the following `<script>` tag inside the `<head>` of your `web/index.html` file?

@pichillilorenzo Is there any way to stop the plugin from registering on web? I only use the in-app web view on mobile and don't want to include an unused script in my web deployment.

**Comment by sugur** [comment]
I have same problem on   flutter_inappwebview: ^6.0.0-beta.22.
How to fix this problem?


`TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
packages/flutter_inappwebview/src/web/web_platform.dart 33:5                      registerWith
web_plugin_registrant.dart 23:34                                                  registerPlugins
web_entrypoint.dart 27:24                                                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall`

**Comment by ayushkadbe** [comment]
Error is occuring because App isn't able to read & write files on device. path_provider doesn't support web. https://pub.dev/packages/path_provider.
App will be working on android, ios, linux, windows but not on web.

Find any other plugin to find commonly used locations on the filesystem for web project.

**Comment by sugur** [comment]
> Error is occuring because App isn't able to read & write files on device. path_provider doesn't support web. https://pub.dev/packages/path_provider. App will be working on android, ios, linux, windows but not on web.
> 
> Use any other plugin to find commonly used locations on the filesystem for web project like https://pub.dev/packages/file_picker_cross

how can I to fix this on my project?

**Comment by colarking** [comment]
![Xnip2024-01-03_16-42-07](https://github.com/pichillilorenzo/flutter_inappwebview/assets/1024702/6d0941ce-8ad7-4844-a3a6-9da6373a0481)


I have added code in index.html:
<head>
  <script type="application/javascript" src="/assets/packages/flutter_inappwebview/assets/web/web_support.js" defer></script>


yaml config:
  flutter_inappwebview: ^6.0.0

and my env:
[!] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at /Users/amaya/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

**Comment by colarking** [comment]
please fix this, Thanks very much

**Comment by colarking** [comment]
> The "Flutter Browser App" project doesn't support the web platform.
> 
> For the error, ask in #1468 what was the solution.



this is worked for me, thanks

**Comment by pichillilorenzo** [comment]
@colarking the path of the JavaScript file is not correct.
The correct one is: `<script type="application/javascript" src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" defer></script> `

**Comment by thcbk** [comment]
> @colarking the path of the JavaScript file is not correct. The correct one is: `<script type="application/javascript" src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" defer></script> `

Thank you, you save me a lot of work ahead.
