### ISSUE TITLE
Why comment out the download listener without exposing it to the Flutter side?

### ISSUE THREAD

**Issue by chaunqingren** [pichillilorenzo/flutter_inappwebview#148]
The Flutter side does not support file download processing. Why comment out the download listener without exposing it to the Flutter side?
======
Flutter端不支持文件下载处理，为什么要注释掉下载监听器而不暴露给Flutter端呢？
![image](https://user-images.githubusercontent.com/54255354/64029236-c6005200-cb76-11e9-8e9b-1fbd5ac7d168.png)

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
