### ISSUE TITLE
Different context handling at Runtime under iOS and Android

### ISSUE THREAD

**Issue by robertosw** [pichillilorenzo/flutter_inappwebview#1480]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |          3.3.8    |
| Plugin version  |    6.0.0-b21           |
| Android version |    API 33           |
| iOS version     |        16.1       |
| macOS version   |   Ventura 13.0            |
| Xcode version   |              14.1 |

Device information: Simulator / Emulator

## Description

Outsourced functions get the BuildContext only once when the class is created. If the build function is called afterwards and the context has changed, the outsourced functions continue to access the old context. This is only an Issue under iOS, Android does not seem to care about this at all.

Example code:
```Dart
  @override
  Widget build(BuildContext context) {
    return InAppWebView(
       onLoadStart: myLoadStartFunction,
     ),
   };

   void myLoadStartFunction(InAppWebViewController controller, WebUri? url) {...}
```

**Expected behavior:**  If you relocate the functions that the WebView calls, so that they are parallel to the build method, they will still work.

**Current behavior:** `myLoadStartFunction` always accesses the old BuildContext, this can be seen if you log the context.hashCode in initState and from inside `myLoadStartFunction`

## Steps to reproduce

Code needed to reproduce seen above. BuildContext changes in my App everytime one Page has finished Loading. The new loading process will have a new BuildContext

## Temporary Solution:
Call your outsourced methods inside the build method and give them the current BuildContext
```Dart
@override
  Widget build(BuildContext context) {
    return InAppWebView(
      shouldOverrideUrlLoading: (controller, navigationAction) async => await wvLoadRequest(context, controller, navigationAction),
      onLoadStart: (controller, url) => wvLoadStart(context, controller, url),
    );
  }

  Future<NavigationActionPolicy> wvLoadRequest(BuildContext context, InAppWebViewController controller, NavigationAction navigationAction) async {...}

  void wvLoadStart(BuildContext context, InAppWebViewController controller, WebUri? url) => {Globals().currentUrl = url.toString()};


```

**Comment by pichillilorenzo** [comment]
That could be something related to Flutter itself or how Flutter manages Platform Views.
For sure, it's not related to the plugin or any native platform code.
Also, I don't do anything with the build context when the `InAppWebView` widget is displayed. Check the `build` method: https://github.com/pichillilorenzo/flutter_inappwebview/blob/a42b0e4dfd6c2dd0506391b03c2c901dcec8b325/lib/src/in_app_webview/in_app_webview.dart#L691
It's simply Flutter/Dart code.

**Comment by robertosw** [comment]
Okay I already thought that It might not have anything to do with your plugin :D
Just wanted to make sure, before making a issue at flutters repo

**Comment by pichillilorenzo** [comment]
@robertosw did you try some other webview plugin?

**Comment by robertosw** [comment]
Not to find out more about this problem, I had the "simple" webview_flutter, but it had subpar performance when scrolling fast on larger sides. And it had way less customizing options

**Comment by robertosw** [comment]
I found the real problem that causes this. My Widget Tree is like this:
```
|-- My Widget (Stateful, with Variables and Methods, no const key)
   |-- InAppWebView(key: Globals.xyz)
```

Globals is a singleton class, where I store global Variables etc.. As in your "tutorial" the InAppWebView needs a const key, but my Widget did not have a const key. And this was the problem.
My Widget was rebuild multiple times, and got a new context everytime. Meanwhile, the InAppWebView's context was never changed, because the key always stayed the same. Thats why the functions always use the "old" context from my Widget.

The simple solution was giving my Widget a const GlobalKey()
