### ISSUE TITLE
[Android] Screen will flicker when pop up page

### ISSUE THREAD

**Issue by drown0315** [pichillilorenzo/flutter_inappwebview#1487]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.3.2         |
| Plugin version  |    6.0.0-beta.22          |
| Android version |     Android12 SDK32          |

Device information: 

## Description
Pop-up page and the screen will flicker

Ps: In addition to cupertino transition, other transition types are normal.

## Steps to reproduce
1. Navigate to a page with a review
2. Press back

## Video

https://user-images.githubusercontent.com/108989782/209266864-78a76d6d-caa2-4c4a-b969-d27618883c35.mp4

## Reproduce code
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('home'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            MaterialButton(
              color: Colors.blue,
              onPressed: () {
                Navigator.push(context,
                    CupertinoPageRoute(builder: (_) => const MyHomePage()));
              },
              child: const Text('home'),
            ),
            MaterialButton(
              color: Colors.blue,
              onPressed: () {
                Navigator.push(context,
                    CupertinoPageRoute(builder: (_) => const WebViewPage()));
              },
              child: const Text('navigate to webview'),
            )
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class WebViewPage extends StatelessWidget {
  const WebViewPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('web page'),
      ),
      body: InAppWebView(
        initialUrlRequest: URLRequest(url: WebUri('https://flutter.dev/')),
      ),
    );
  }
}

```

**Comment by rakesh0689** [comment]
I am also facing this issue, an update on this issue.
Using Flutter 3.7 and flutter_inappwebview: ^6.0.0-beta.22.

**Comment by josephsssss** [comment]
why does it have to be inappview??
my flutter flickers on context.pop()
show the initial page for short amount of time

**Comment by Stitch-Taotao** [comment]
Same issue ,when my second page contains InappView,naviator.pop will made screen flicker.

**Comment by pichillilorenzo** [comment]
Have you tried in profile/release mode?

It could be related on Android Hybrid Composition: https://github.com/flutter/flutter/wiki/Hybrid-Composition#performance

Hybrid Composition is used by default on Android  on plugin version 6.
It allows to fix a lot of Flutter platform view issues, such as issues related to keyboard and others.
If you want to disable it, set `InAppWebViewSettings.useHybridComposition` to `false`.

**Comment by Stitch-Taotao** [comment]
In release mode, the chance of flickering is indeed smaller, but it still happens. If ‘useHybridComposition’ is set to false, there will be no jitter both in Debug and Release mode. 
But I don't know why,After all, setting ‘useHybridComposition’ to true is a trend.

**Comment by pichillilorenzo** [comment]
> But I don't know why,After all, setting ‘useHybridComposition’ to true is a trend.

Because it resolves other issues, check https://github.com/flutter/flutter/wiki/Hybrid-Composition#android:
> Starting from Flutter 1.20.0, hybrid composition can be used on Android. This new feature fixes most of the [issues with the preview platform view approach](https://github.com/flutter/flutter/wiki/Virtual-Display#associated-problems-and-workarounds) (Virtual Display); in particular, accessibility and keyboard related issues. See also [Android Platform Views](https://github.com/flutter/flutter/wiki/Android-Platform-Views) for an overview of modes.

**Comment by pichillilorenzo** [comment]
It's not a bug, it's simply how Flutter Platform Views works on Android.
Native Views come in Flutter with tradeoffs, unfortunately.
Hybrid Composition or not, either one or the other brings some "problems" with it.

By the way, if you want to implement something like that, you are already able to take screenshots of the WebView and use it as image when needed: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/PlatformInAppWebViewController/takeScreenshot.html

**Comment by pichillilorenzo** [comment]
Another way could be just to wait for an animation to end and then show the WebView.
Instead, in the opposite case, dispose the widget removing it from the Flutter widget tree and/or taking a screenshot before removing it and then start your Flutter animation.

**Comment by hisham-safade** [comment]
> Have you tried in profile/release mode?
> 
> It could be related on Android Hybrid Composition: https://github.com/flutter/flutter/wiki/Hybrid-Composition#performance
> 
> Hybrid Composition is used by default on Android on plugin version 6. It allows to fix a lot of Flutter platform view issues, such as issues related to keyboard and others. If you want to disable it, set `InAppWebViewSettings.useHybridComposition` to `false`.

Thanks, it's worked for me.
