### ISSUE TITLE
Error log spam from URLProtectionSpace

### ISSUE THREAD

**Issue by omnicron-llc** [pichillilorenzo/flutter_inappwebview#1488]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |         3.6.0-0.1.pre      |
| Plugin version  |        6.0.0-beta22       |
| Xcode version   |          14.2     |

## Description
Many instances of the following log line:
This method should not be called on the main thread as it may lead to UI unresponsiveness.

## Steps to reproduce

Any minimal web viewer flutter project exhibits it for me, just take the minimal sample app from the project documentation - https://inappwebview.dev/docs/in-app-localhost-server/ for example - should exhibit the behavior. Simply populate any index in the assets directory and run the app.

## Notes
According to XCode, this fault originates from line 18 of URLProtectionSpace.swift, specifically this line:
let secTrustEvaluateStatus = SecTrustEvaluate(serverTrust, &secResult);  - this line is flagged in the editor itself with the same message that appears in the log.

**Comment by moffatman** [comment]
Appears to be Apple's fault and a common bug with any use of WKWebView

https://developer.apple.com/forums/thread/714467?answerId=734799022#734799022

**Comment by omnicron-llc** [comment]
Well, isn't that peachy. At least they know about it, but the "we may or may not ever fix this" tone of the comment isn't promising.
