### ISSUE TITLE
Adblock Feature required.

### ISSUE THREAD

**Issue by parmeetmaster** [pichillilorenzo/flutter_inappwebview#1489]
## Environment

**Flutter version:**  3.3.9
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 

I am using this example to block ads such admob and outbrain.but there are thousands of other plaforms that provide irritating popup ads.So for block those popup ads we using in android [https://easylist.to/easylist/easylist.txt](url) import this webview to block hosts.But inappwebview are unable to do.In order to apply this feature you refer this simple repository here : [https://github.com/MonsterTechnoGits/WebViewAdblock-Library](url).Since this year i am developing app in flutter try to use this adblock feature in app faces lots of challange.Since you have webview and team. I request please apply this feature.This feature can make revolution to your plugin.Because adblock is very necessary nowdays due spam traffic around the world.

`  Future<void> init() async {
    final response = await rootBundle.loadString('assets/adlist.txt');
    LineSplitter.split(response).forEach((line) => adUrlFilters.add(line));

    // for each Ad URL filter, add a Content Blocker to block its loading.
    for (final adUrlFilter in adUrlFilters) {
      contentBlockers.add(ContentBlocker(
          trigger: ContentBlockerTrigger(
            urlFilter: adUrlFilter,
          ),
          action: ContentBlockerAction(
            type: ContentBlockerActionType.BLOCK,
          )));
    }

    // apply the "display: none" style to some HTML elements
    contentBlockers.add(ContentBlocker(
        trigger: ContentBlockerTrigger(
          urlFilter: ".*",
        ),
        action: ContentBlockerAction(
            type: ContentBlockerActionType.CSS_DISPLAY_NONE,
            selector: ".banner, .banners, .ads, .ad, .advert")));
  setState(() {
    isLoading=true;
  });
  }`

**Alternatives you've considered:**   

**Images:**

**Comment by SethuSenthil** [comment]
Are there any updates on this?

**Comment by parmeetmaster** [comment]
Yes, Sir it block on google adsense ads.Can you make compatable to to remove all ads.

**Comment by SethuSenthil** [comment]
You can try using https://github.com/islamdidarmd/flutter_adblocker_webview , it is basically a fork of `flutter_inappwebview` but with AdBlock support
