### ISSUE TITLE
When onWebContentProcessDidTerminate is triggered, how should the web be refreshed?

### ISSUE THREAD

**Issue by resfandiari** [pichillilorenzo/flutter_inappwebview#1497]
When an app is in the background for a long time, then comes to the foreground, it displays a white screen. This is because onWebContentProcessDidTerminate is called sometimes. I would like the best approach to handle this situation. Thank you.

**Comment by palancana** [comment]
I think the best way to handle this is just to reload the webpage:

```
onWebContentProcessDidTerminate: (controller) async {
  // Reload the page when the web content process is terminated.
  // This can happen when the app is backgrounded for too long, on iOS only.
  await controller.reload();
},
```

On the previous versions of the plugin (v5) the property is called `iosOnWebContentProcessDidTerminate`.
