### ISSUE TITLE
[web platform] unable to load a pdf page on example project 

### ISSUE THREAD

**Issue by dariolr** [pichillilorenzo/flutter_inappwebview#1502]
replacing url in example project from 

https://flutter.dev

to

https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

pdf is not showed, how can I solve?
thanks a lot!

**Comment by edgarMejia** [comment]
Same here, any solution?

**Comment by mlab817** [comment]
have you solved this? i'm having trouble loading a pdf file from web browser in android. i don't encounter the issue in other platforms.

**Comment by edgarMejia** [comment]
Apparently it is a limitation with android webview as it does not support PDF preview
