### ISSUE TITLE
iOS app crashes on camera permission request (which I want to block)

### ISSUE THREAD

**Issue by alectogeek** [pichillilorenzo/flutter_inappwebview#1510]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | Flutter 3.3.10 • channel stable |
| Plugin version  | 6.0.0-beta.22 |
| iOS version     | ios 16.2 |
| Xcode version   |14.2 (14C18) |

Device information: 
iPhone 11 (real device)
## Description

**Expected behavior:** 
I expect to be able to catch camera access request in onPermissionRequest and deny it.
**Current behavior:** 
App crashes with error: 
```
[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
* thread #32, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
    frame #0: 0x00000001e55ceb44 libsystem_kernel.dylib`__abort_with_payload + 8
libsystem_kernel.dylib`:
->  0x1e55ceb44 <+8>:  b.lo   0x1e55ceb64               ; <+40>
    0x1e55ceb48 <+12>: pacibsp 
    0x1e55ceb4c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1e55ceb50 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```
## Steps to reproduce
1. **Don't** set NSCameraUsageDescription in Injo.plist
2. Catch camera request in onPermissionRequest and deny it
3. Run on a real device

**Comment by Vong3432** [comment]
NSCameraUsageDescription must be defined in Info.plist for the apps that wants to use camera. Otherwise the app will crash as expected.

Source from [Stackoverflow](https://stackoverflow.com/a/39825049 ) 

> A significant change in iOS 10 is that you must declare ahead of time any access to private data or your App will crash.

> Once you link with iOS 10 you must declare access to any user private data types. You do this by adding a usage key to your app’s Info.plist together with a purpose string. The list of frameworks that count as private data is a long one

> Contacts, Calendar, Reminders, Photos, Bluetooth Sharing, Microphone, Camera, Location, Health, HomeKit, Media Library, Motion, CallKit, Speech Recognition, SiriKit, TV Provider.

It is also stated in the [Apple Developer Documentation](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources) :
> Always provide a valid purpose string in the Info.plist file if your app uses a protected resource. If you don’t, attempts to access the resource fail, and might even cause your app to crash.

Once NSCameraUsageDescription is defined, I think you should be able to handle the permission request and grant/deny it.
