### ISSUE TITLE
Flutter Web error: TargetPlatform.windows is not yet supported by the flutter_inappvwebview plugin

### ISSUE THREAD

**Issue by razfazz** [pichillilorenzo/flutter_inappwebview#1514]
When using Flutter Web with the flutter_inappwebview: ^5.7.2+3 and launching the chrome browser on windows i get the error

"TargetPlatform.windows is not yet supported by the flutter_inappvwebview plugin"

i used this guide to set it up on Flutter Web https://inappwebview.dev/docs/intro/

**Comment by adamsmaka** [comment]
looks like version 5.7.2+3 doesn't support web nor macos. have you ried 6.0.0 beta?

**Comment by mdbabarkhaan** [comment]
Same here

**Comment by trnchawla** [comment]
is this solved? I am using 6.0.0 beta but still getting this issue.

**Comment by SERCHISER** [comment]
Same here

**Comment by Devhric** [comment]
Same here

**Comment by RelicOfTesla** [comment]
6.0.0-beta.31 can load...but not support https??
