### ISSUE TITLE
addWebMessageListener not always set correctly

### ISSUE THREAD

**Issue by elliotrtd** [pichillilorenzo/flutter_inappwebview#1518]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |    3.7.0           |
| Plugin version  |    6.0.0+22    |
| Android version |    13           |
| iOS version     |      X         |
| macOS version   |    X           |
| Xcode version   |       X        |

Device information: Google Pixel 7

## Description

**Expected behavior:** 
Adding 2 WebMessageListener works correctly

**Current behavior:** 
On the first load the controller often fails to initialise the listener properly. Thus the JS never finds the listener and cannot send the data back. 

If I exit and reload the same page then it seems to be set more reliably. 

I have tried calling these separately in onLoadStop and onWebViewCreated but with the same result. 

Trying to set again throws an exception that _webMessageListenerObjNames already contains the listener.

My current solution is to reload the page onLoadStop and force them to try and set again, I have branched this to my own GitHub to ignore the Exception. 

I have had this with both iOS and Android but Android is more consistently buggy. 

## Steps to reproduce

1. Set 2 different WebMessageListener in onWebViewCreated
2. Have some JS in the web page to call these a short while after it's loaded
3. JS error thrown that the object is not found.

**Comment by emulatorchen** [comment]
@elliotrtd thinking I may have the same issue as you and I found that the listener maybe added after the page is loaded where the listener should be loaded in the very beginning(that's why most of the tutorials put the method on created).

So the workaround is to remove the usage of initialUrlRequest, then load the url after your listener is added:

 ```
           await inAppWebViewController
                .addWebMessageListener(getYourWebMessageListener());
            inAppWebViewController(urlRequest: URLRequest(url: WebUri(YOUR_URL)));
```

**Comment by elliotrtd** [comment]
> @elliotrtd thinking I may have the same issue as you and I found that the listener maybe added after the page is loaded where the listener should be loaded in the very beginning(that's why most of the tutorials put the method on created).
> 
> So the workaround is to remove the usage of initialUrlRequest, then load the url after your listener is added:
> 
> ```
> await inAppWebViewController.addWebMessageListener(getYourWebMessageListener());
> inAppWebViewController.loadUrl(URLRequest(WebUri(YOUR_URL)));
> ```

@emulatorchen Ahh! That makes sense as to why when I reload the page it's working. I did some initial tests and it seems to be working correctly - I need to test all possible scenarios for how we're using the listeners in a few places & I'll update here / close as necessary. 

Thanks so much!

**Comment by emulatorchen** [comment]
No problem, just I would say it's still a bug as the addWebMessageListener method did not work well with initialUrlRequest. It's not working unexpected but also have chance to crash the app when you need to switch the page frequently in my case.
