### ISSUE TITLE
"window.flutter_inappwebview.callHandler" dosn't work  in ios

### ISSUE THREAD

**Issue by rhecs** [pichillilorenzo/flutter_inappwebview#1522]
window.flutter_inappwebview.callHandler('handlerFoo')
version:  ^5.7.2+2
android is ok，but can't use in ios;  In addition, it is found that consoleMessage is invalid under ios.
my options:
options = InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      useShouldOverrideUrlLoading: true,
      useShouldInterceptFetchRequest: true,
    ),
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),
    ios: IOSInAppWebViewOptions(
      allowsInlineMediaPlayback: true,
    ),
  );

<img width="931" alt="image" src="https://user-images.githubusercontent.com/26713879/216493488-ff5328dc-15cf-4816-9345-be9bab191dcb.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/26713879/216493743-788b48e8-68f7-4ea8-bcfe-371b2a061ff6.png">

by the way ，There is a very old project in which he uses webview interaction within ios:
"window.webkit.messageHandlers.openScan.postMessage({})"
How to intercept the request "window.webkit.messageHandlers.openScan.postMessage ({})" without modifying the original web page project?

Thank you very much for your help

**Comment by mohammedX6** [comment]
i have the same problem

**Comment by thomarga** [comment]
I also experienced the same problem with window.webkit.messageHandlers.openScan.postMessage({})

i use this 
``` window.webkit = {
    messageHandlers: {
      requestUserAccessToken: {
        postMessage: function (param) {
          
          const parsedParam = JSON.parse(param);
  
          const callback = parsedParam.callbackMethod;
          const token = '';
  
          window[callback]({
            success: token != null ? true : false,
            accessToken: token,
          });
        },
      }, ```

but "window.flutter_inappwebview.callHandler" dosn't work in ios

**Comment by rishabh-oc** [comment]
For me also "window.flutter_inappwebview.callHandler" dosn't work in ios
