### ISSUE TITLE
[iOS] On click and Scroll error RenderBox 

### ISSUE THREAD

**Issue by thongvo109** [pichillilorenzo/flutter_inappwebview#1525]
When i touch and scroll i get this error. Hope to help. 

════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while routing a pointer event:
RenderBox was not laid out: RenderUiKitView#88636 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
package:flutter/…/rendering/box.dart:1
Failed assertion: line 2001 pos 12: 'hasSize'

- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |         3.3.0      |
| Plugin version  |      ^5.7.2+3         |
| Android version |               |
| iOS version     |         16.0      |
| macOS version   |               |
| Xcode version   |         14.2      |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by Johnblundon** [comment]
I have this exact same issue, really really hoping someone can help. It's very random but once it happens, it happens everywhere.
