### ISSUE TITLE
inappwebview and download troubleshooting

### ISSUE THREAD

**Issue by Ladriel** [pichillilorenzo/flutter_inappwebview#1530]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

For context we are trying to replace os-related browser with one unique webview in our app, mostly for displaying web content.
This plugin seemed like a real good candidate, however i'm still experiencing some discrepancies here and there concerning downloads. 
I have already investigated multiple threads and would like definite answers to decide if we have to keep or dismay the use of this plugin.

TLDR : download is working fine for direct access links, however we don't have a mean to recognize server-side protected document download urls all the time.

## Environment

Flutter version  :  3.X.X            
Plugin version  :  5.X.X / 6.X.X 
Android version  :  SDK 23/Android 6+
iOS version  :   iOS 13+
macOS version  :  Monterey 12.5
Xcode version  :  14.2

Device information: Multiple devices, Samsungs, iphone SE

## Description

**Expected behavior:** 

Download should be recognized and start for both a direct link to files (i.e.: .../file.pdf url) and also for server restricted access links (i.e: .../api/download/id=XXX).

**Current behavior:** 

At the moment, the onDownloadStartRequest feedback is launching only for direct links => http..url.pdf

Whenever files are sent securely from behind the server this onDownload trigger doesn't launch. 
How could one make sure the url we are trying to access is to be handled as a download.

We have the shouldOverrideUrl trigger but navigationAction request doesn't give any hint as to if the destination is a file.
We can hard-code the our download-url recognition here but it should work with any secured url from any site so that's out of the question.

Basically if(urlString.contains(download-pattern)) won't work for any site which isn't ours.

As an alternative we don't have enough informations on onLoadStop to do the same sort of things, unless i'm missing something.

## Steps to reproduce

1. I added the useOnDownloadStart and useShouldOverrideUrlLoading true in settings
2. When onDownloadStart is triggered i delegate the download to my DownloadService, which works fine
3. For server protected URL onDownloadStart doesn't trigger. As an alternative if i identify our download URL on shouldOverrideUrl and trigger the download service manually here it does download.
However it should work for any site and as such *i don't have a definitive recognition pattern.*
4. i tried updating to the 6.X.X beta version, but even there the navigationAction.shouldPerformDownload on iOS always returns false for server protected download urls.
5. i seen the flutter_dowloader plugin recommended however it seems to be lagging behind after latest Android 11 permission related problems, and it is currently changing maintainers and might be discontinued.
6. i did check out https://github.com/pichillilorenzo/flutter_inappwebview_examples/tree/main/file_download too

In short : Is there an implementation-proof way of detecting download urls (especially server secured ones) ? Independent of whether the file is returned in response content, as an attache file, bytes etc ? Maybe we can get some mime-type, headers for this somewhere but i can't seem to find a solution.

Related threads :
https://gist.github.com/pichillilorenzo/ee74e103fdc324f761c5fde7b73bd430
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1309
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1087
https://github.com/pichillilorenzo/flutter_inappwebview/issues/842

**Comment by ilovesusu** [comment]
How to solve the problem of not being able to download pictures
