### ISSUE TITLE
iOS: WebView is blank(empty) when opening the app from background after a few hours

### ISSUE THREAD

**Issue by ruthoferroman** [pichillilorenzo/flutter_inappwebview#1531]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |    3.7.0, on macOS 13.2 22D49 darwin-arm64           |
| Plugin version  |    6.0.0-22beta           |
| Android version |    -           |
| iOS version     |     16.1.2          |
| macOS version   |   13.2             |
| Xcode version   |    14.2           |

Device information: Apple iPhone 13

## Description

**Expected behavior:** 
put app in background 
open it again - web view should show the webpage from url 

**Current behavior:** 
put app in background
open app again after a short time (less than around 2hours) - everything is fine
put app in background
open app again after a short time (after around 8hours) - web view is blank - progress seems to be 0

## Steps to reproduce

1. put app in background
2. open app again after a short time (after around 8hours) - web view is blank - progress seems to be 0

**Comment by alapeta** [comment]
check docs for iosOnWebContentProcessDidTerminate event.

https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebView/iosOnWebContentProcessDidTerminate.html

and also:

https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455639-webviewwebcontentprocessdidtermi

**Comment by mrnusa** [comment]
use onWebContentProcessDidTerminate and reload the webview

**Comment by ruthoferroman** [comment]
Seems to work. Thanks to everybody!
