### ISSUE TITLE
Camera Stream freezes on the Android Webview

### ISSUE THREAD

**Issue by alexcgrd** [pichillilorenzo/flutter_inappwebview#1534]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |   3.0.2   |
| Plugin version  |   5.7.2+3    |
| Android version |  EMUI 12  (Android 11?)  |

Device information: 
huawei p30 lite 

## Description
On some Android devices the video for the camera-stream doesn't work properly. I noticed this behavioru when using the barcode libraries ZXING and html5-qrcode reader (https://github.com/mebjas/html5-qrcode). This behaviour was noticed on the Huawei P30 lite and the Samsung Galaxy S10. All other Android and iOS devices that I was able to test this on seem to work fine. The scanner works fine in all of the other browsers including chrome on said devices.

**Expected behavior:** 
The expected behaviour is to accept the camera permission and display the camera stream smoothly.

**Current behavior:** 
The current behaviour is that you accept the camera permission. Then the video will start playing and freez right away. The camera freez stops as long as you touch on the screen and will continue freezing once you take your finger of the screen. The actual scan of the barcodes still work fine, only the camera output is not updated at all.

## Steps to reproduce
I had been testing this with the html5-qrcode library.

To reproduce this behaviour, you will need one of the devices mentioned above.

1. Create a new Flutter App using this Plugin
2. Open "InAppWebView" with the following URL https://scanapp.org/
3. Enable the camera permission
4. Open the scanner 

https://user-images.githubusercontent.com/58855614/218070184-3e2f5122-d017-4254-bceb-2a1ea3889e90.mp4

## Stacktrace/Logcat
Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.2486], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

I get the following terminal output when opening the camera:

I/CameraManager(21695): open camera: 1, package name: XYZ
E/cr_VideoCapture(21695): CameraDevice.StateCallback onOpened
D/SensorManager(21695): 0x774b5bb0e0 addFd fd=356
I/DecorView[](21695): pkgName:XYZ old windowMode:1 new windoMode:1, isFixedSize:false
W/MessageQueue(21695): Handler (android.os.Handler) {b983089} sending message to a Handler on a dead thread
W/MessageQueue(21695): java.lang.IllegalStateException: Handler (android.os.Handler) {b983089} sending message to a Handler on a dead thread
W/MessageQueue(21695): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:618)
W/MessageQueue(21695): 	at android.os.Handler.enqueueMessage(Handler.java:771)
W/MessageQueue(21695): 	at android.os.Handler.sendMessageAtTime(Handler.java:717)
W/MessageQueue(21695): 	at android.os.Handler.sendMessageDelayed(Handler.java:687)
W/MessageQueue(21695): 	at android.os.Handler.post(Handler.java:416)
W/MessageQueue(21695): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2458)
W/MessageQueue(21695): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
W/MessageQueue(21695): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:535)
W/MessageQueue(21695): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:826)
W/MessageQueue(21695): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
W/MessageQueue(21695): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
W/MessageQueue(21695): 	at java.lang.Daemons$Daemon.run(Daemons.java:137)
W/MessageQueue(21695): 	at java.lang.Thread.run(Thread.java:929)
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 46 lines
W/cr_HandleImpl(21695): Handle was not closed.
I/HwViewRootImpl(21695): removeInvalidNode all the node in jank list is out of time
W/XYZ(21695): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 1 line
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 3 lines
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 1 line
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 3 lines
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 92 lines
W/cr_HandleImpl(21695): Handle was not closed.
W/System  (21695): A resource failed to call release. 
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 9 lines
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 11 lines
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
I/chatty  (21695): uid=11687(XYZ) FinalizerDaemon identical 1 line
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.
W/cr_HandleImpl(21695): Handle was not closed.

**Comment by alexcgrd** [comment]
Also, I have been playing around wihh the webview options. Nothing seemed to work here either. I am currently running these configurations:

  ```
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(

        crossPlatform: InAppWebViewOptions(
            userAgent                         : '',
            useShouldOverrideUrlLoading       : true,
            useOnLoadResource                 : true,
            useOnDownloadStart                : false,
            mediaPlaybackRequiresUserGesture  : false,
            useShouldInterceptAjaxRequest     : false,
            useShouldInterceptFetchRequest    : false,
            supportZoom                       : false,
            allowUniversalAccessFromFileURLs  : true,
            preferredContentMode              : UserPreferredContentMode.MOBILE,
            clearCache                        : false,
            cacheEnabled                      : false,
            disableHorizontalScroll           : true
        ),

        android: AndroidInAppWebViewOptions(
            useHybridComposition        : true,
            builtInZoomControls         : true,
            useShouldInterceptRequest   : true,
            useOnRenderProcessGone      : false,
            cacheMode                   : AndroidCacheMode.LOAD_DEFAULT,
            hardwareAcceleration        : true
            // networkAvailable
        ),

        ios: IOSInAppWebViewOptions(
            allowsInlineMediaPlayback           : true,
            allowsLinkPreview                   : false,
            allowsBackForwardNavigationGestures : false,
        )

    );
```

**Comment by alexcgrd** [comment]
I have found a temporary fix - you need to an animated svg to keep the Android Webview refreshed. Just put it into the background with a width and height of 1px.

https://bugs.chromium.org/p/chromium/issues/detail?id=1401352&q=webview%20camera&can=2

**Comment by mohammedX6** [comment]
@alexcgrd  hi can you please share some more info, i have the same problem.
Thanks !

**Comment by helenooliveiraa** [comment]
i found another workaround if you install the "qr_code_scanner" package it works normally.

Hope this helps

**Comment by alexcgrd** [comment]
@mohammedX6 The issue is shown in the video that I posted in the video. Other please have a look at this issue, I think it is related to this problem: https://bugs.chromium.org/p/chromium/issues/detail?id=1401352 

@helenooliveiraa That seems to do the job for now, thanks. Hopefully this problem will be fixed soon.
