### ISSUE TITLE
List opened WebViews

### ISSUE THREAD

**Issue by jkoenig134** [pichillilorenzo/flutter_inappwebview#1537]
## Environment

**Flutter version: 3.7.3** 
**Plugin version: 5.7.2+3** 

## Description

I am using the HeadlessInAppWebView to access my JS / TS libs inside of my Flutter app.

When I trigger a hot restart I want the current HeadlessInAppWebView to be disposed to avoid memory leaks. B/c of https://github.com/flutter/flutter/issues/69949 dispose isn't triggered during hot restart.

Therefore I'd suggest to provide a possibilitiy to list and manage already opened WebViews and then attach to the old webview or dispose it.

**Comment by jkoenig134** [comment]
@pichillilorenzo would you please re-open this? I think it's still valid and was just closed because is was never answered.

**Comment by pichillilorenzo** [comment]
This is something that should be explored more! If Flutter gives an event on native side when an Hot Reload is called, it could be very helpful to fix this.
