### ISSUE TITLE
unable to build on ios ?

### ISSUE THREAD

**Issue by harryandroiddev** [pichillilorenzo/flutter_inappwebview#1538]
Could not build the precompiled application for the device.
Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Type 'WKDataDetectorTypes' has no member 'WKDataDetectorTypes'
/Users/kp/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.7.2+3/ios/Classes/Util.swift:85:20

flutter doctor output:

[✓] Flutter (Channel stable, 3.7.3, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by JoaoAlmeida-dev** [comment]
Having the same issue

**Comment by clevonnoel** [comment]
Me too

**Comment by tapas-tw** [comment]
facing the same, anyone on it?
