### ISSUE TITLE
Ability to load local files from application document directory

### ISSUE THREAD

**Issue by apremalal** [pichillilorenzo/flutter_inappwebview#1544]
## Environment

`flutter_webview` is able to load files from `path_provider.getApplicationDocumentsDirectory()` would it be possible to add this capability here as well?

Use case:

Application downloads a secure package to the application document directory at runtime and wants to render the HTML file inside.

**Comment by YouYue123** [comment]
+1 for the feature

**Comment by YouYue123** [comment]
@apremalal Actually I found out there is a workaround to use as following

```
   await webViewController.loadUrl(
      urlRequest: URLRequest(url: Uri.parse(path)),
    );
```
