### ISSUE TITLE
When the keyboard is open and I click inside a field for the second time the webview scroll cannot go to the bottom of the page

### ISSUE THREAD

**Issue by JChPal** [pichillilorenzo/flutter_inappwebview#1556]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |      3.3.10         |
| Plugin version  |     ^5.7.2+3          |
| iOS version     |    16.2           |
| Xcode version   |     14.2          |

Device information: iPhone SE

## Description

**Expected behavior:** 

When keyboard is open we can access the bottom of the de page

**Current behavior:** 

Load a page, try filling a first field. Here we still can access the bottom of the page.

When we try to go to fill a second field the bottom of the page is not reachable anymore.

## Steps to reproduce

My code:

```
InAppWebView(
            initialUrlRequest: URLRequest(
              url: Uri.parse('https://www.netflix.com/fr/login'),
            ),
            initialOptions: InAppWebViewGroupOptions(
              crossPlatform: InAppWebViewOptions(
                useShouldOverrideUrlLoading: true,
                cacheEnabled: false,
                clearCache: true,
              ),
              android: AndroidInAppWebViewOptions(
                useHybridComposition: true,
                clearSessionCache: true,
              ),
              ios: IOSInAppWebViewOptions(),
            ),
          )
```

## Images   

The part not accessible when the bug occur:
![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-02-24 at 17 09 57](https://user-images.githubusercontent.com/121486170/221231655-71d9fed8-bfb8-47b0-b4aa-d940b9403d25.png)

Video to reproduce:
First field (still can reach the bottom of the page) then click the second field (same behavior if you click on the `⌄` `^` symbols of the keyboard), cannot reach the bottom of the page
https://user-images.githubusercontent.com/121486170/221232027-fb5f1840-a08f-4014-a958-c8accab2309f.mp4

## Stacktrace/Logcat 

Nothing available

**Comment by anhkhoi159** [comment]
@JChPal  hi Pal, you can add **_resizeToAvoidBottomInset:false_** in Scaffold widget, It worked for me.

**Comment by boat-jitrapon** [comment]
Any updates on this issue?
