### ISSUE TITLE
How do I set Referer because I need to add Referer when wechat Pay

### ISSUE THREAD

**Issue by 2971026328** [pichillilorenzo/flutter_inappwebview#1558]
I would like to implement setting referer, similar to the link below for other plugins, but I can't find it in this version, so if anyone implements this, please help me fix this problem, thanks
[https://www.jianshu.com/p/cd02cfab39f8/](url)
I used   flutter_inappwebview: ^6.0.0-beta.22 this version

I have tried the following picture but it doesn't work. Is it my fault
![c7ed90e8ebe9ec2545944c486989a0f](https://user-images.githubusercontent.com/50520799/221467786-cc079f79-01b9-40fa-9832-b5df3144f795.png)
![dca9258a42b17723610f024f50c3827](https://user-images.githubusercontent.com/50520799/221467826-958a58ff-2139-442f-a848-e16267468bb7.png)

**Comment by saixin** [comment]
any update?

**Comment by 2971026328** [comment]
I have used the latest version :flutter_inappwebview: ^6.0.0-beta.22 , but the problem still exists.    Could you help me solve this problem?    Thank you very much

**Comment by xuixnwei** [comment]
@ @2971026328 
how did you finished this question?
i got the same question now

**Comment by xuixnwei** [comment]
@2971026328 
i get it!!!

`shouldOverrideUrlLoading: (controller, navigationAction) async {
                        var uri = navigationAction.request.url!;
                        navigationAction.request.headers =  {
                          "Referer":referer
                        };
                        controller.loadUrl(urlRequest: navigationAction.request);
                        referer = uri.toString();
                        String url = uri.toString();
                        if (url.startsWith("weixin://") || url.startsWith("alipays://") || url.startsWith("alipay://")) {
                          controller.stopLoading();
                          await launchUrl(uri);
                          Future.delayed(const Duration(milliseconds: 500), () {
                            navigationAction.request.url = Uri.parse(cloudUrl);
                            controller.loadUrl(urlRequest: navigationAction.request);
                          });
                          return NavigationActionPolicy.CANCEL;
                        }
                        return NavigationActionPolicy.ALLOW;
                      },`
