### ISSUE TITLE
Simulated tap gesture not working inside InAppWebView on iOS

### ISSUE THREAD

**Issue by zsolthathazi** [pichillilorenzo/flutter_inappwebview#1559]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.7.5          |
| Plugin version  |    5.7.2+3           |
| Android version |               |
| iOS version     |      16.3         |
| macOS version   |               |
| Xcode version   |        14.1       |

Device information: Iphone SE 2

## Description
I am trying to simulate a tap event inside the webview, with the following code: 

```
Future<void> tap() async {
    setState(() {
      hideButton = true;
    });

    await Future.delayed(const Duration(milliseconds: 200));

    GestureBinding.instance.handlePointerEvent(PointerDownEvent(position: Offset(coordX, coordY + appBarAndStatusBarHeight)));
    GestureBinding.instance.handlePointerEvent(PointerUpEvent(position: Offset(coordX, coordY + appBarAndStatusBarHeight)));

    setState(() {
      hideButton = false;
    });
  }
```

And I am using the following options in my webview:
```

  initialOptions: InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        transparentBackground: true,
        allowFileAccessFromFileURLs: true,
        useShouldOverrideUrlLoading: true,
        allowUniversalAccessFromFileURLs: true,
        javaScriptEnabled: true,
        javaScriptCanOpenWindowsAutomatically: false,
        preferredContentMode: UserPreferredContentMode.MOBILE,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
        allowsPictureInPictureMediaPlayback: false,
        allowsAirPlayForMediaPlayback: false,
      ),
      android: AndroidInAppWebViewOptions(
        preventFullScreen: true,
        useHybridComposition: false,
      ),
    ),
```

It works fine on Android, but on iOS it doesn't trigger the tap event, but it does on a button or any other touchable widgets.

**Expected behavior:** 

Trigger the tap event in the webview.

**Current behavior:** 

Tap event is not recognized by the webivew's content.

## Steps to reproduce

I tried with a draggable Positioned widget, which I can drag over buttons in the webview, so I can trigger the button's functionality.

Unfortunately, I can't share the whole code, because it is my company's property, but I can answer questions, if there will be any.

**Comment by Zigotote** [comment]
Same problem here, I want to call tap() on my InAppWebview during tests. It works well on Android but not with iOS.
