### ISSUE TITLE
i find a bug

### ISSUE THREAD

**Issue by wd668944** [pichillilorenzo/flutter_inappwebview#157]
I had a problem with the flutter inappbrowser,I entered a route using InAppWebView,After I exit this route,I call up other apps through my app,When I went back to my app my app quit,this is my log:
E/AndroidRuntime(18843): 	at android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1447)
E/AndroidRuntime(18843): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3316)
E/AndroidRuntime(18843): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18843): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(18843): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime(18843): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18843): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(18843): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(18843): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process (18843): Sending signal. PID: 18843 SIG: 9
Lost connection to device.

**Comment by wd668944** [comment]
When I don't close this routing address and do the same thing, my app doesn't exit,I guess that's because the flutter was still calling something flutter_inappbrowser, and when I went back to my app, I had the null pointer problem because I had turned off flutter_inappbrowser

**Comment by wd668944** [comment]
D/AndroidRuntime(22023): Shutting down VM
D/JIGUANG-JCore-IMPL(22023): [JCommonInterface] onEvent action:deviceinfo
D/JIGUANG-JCore(22023): [HttpHelper] status code:200 retry left:2
E/AndroidRuntime(22023): FATAL EXCEPTION: main
E/AndroidRuntime(22023): Process: com.zhiyeit.mall, PID: 22023
E/AndroidRuntime(22023): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
