### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'callHandler')

### ISSUE THREAD

**Issue by msutharworkspace** [pichillilorenzo/flutter_inappwebview#1574]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.3.10        |
| Plugin version  |       6.0.0-beta.22        |
| Android version |               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

Callback function is not calling in flutter web.

## Steps to reproduce

     class _MyAppState extends State<MyApp> {
     InAppWebViewController? _webViewController;
       final _settings = InAppWebViewSettings(
      useShouldOverrideUrlLoading: true,
      mediaPlaybackRequiresUserGesture: false,
      allowsInlineMediaPlayback: true,
      useHybridComposition: true,
      clearCache: true,
      iframeAllow: "camera; microphone",
      iframeAllowFullscreen: true);

      String initialData = """
    <!DOCTYPE html>
    <html lang="en">
         <head>
        <meta charset="UTF-8">
           <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum- 
     scale=1.0">
    </head>
    <body>
        <h1>JavaScript Handlers (Channels) TEST</h1>
        <script>
           console.log("script=====");
           console.log(window)
           window.flutter_inappwebview.callHandler('ready', {"name":"hello"});
           if(window.flutter_inappwebview)
           {
            console.log("not undefined");
           }
          
            window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
             console.log("flutterInAppWebViewPlatformReady");
                window.flutter_inappwebview._callHandler('handlerFoo')
                  .then(function(result) {
                    // print to the console the data coming
                    // from the Flutter side.
                    console.log(JSON.stringify(result));
                    
                    window.flutter_inappwebview
                      .callHandler('handlerFooWithArgs', 1, true, ['bar', 5], {foo: 'baz'}, result);
                });
            });
        </script>
    </body>
      </html>
                      """;
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('InAppWebView Example'),
        ),
        body: Container(
            child: Column(children: <Widget>[
          Expanded(
            child: InAppWebView(
              initialData: InAppWebViewInitialData(data: initialData),
              initialSettings: _settings,
              onPermissionRequest: (controller, request) async {
                return PermissionResponse(
                    resources: request.resources,
                    action: PermissionResponseAction.GRANT);
              },
              onWebViewCreated: (InAppWebViewController controller) {
                print("onWebViewCreated=====");
                _webViewController = controller;

                // _webViewController!.addJavaScriptHandler(
                //     handlerName: 'handlerFoo',
                //     callback: (args) {
                //       // return data to JavaScript side!
                //       return {'bar': 'bar_value', 'baz': 'baz_value'};
                //     });
                //
                // _webViewController!.addJavaScriptHandler(
                //     handlerName: 'handlerFooWithArgs',
                //     callback: (args) {
                //       print(args);
                //       // it will print: [1, true, [bar, 5], {foo: baz}, {bar: bar_value, baz: baz_value}]
                //     });
              },
              onLoadStop:
                  (InAppWebViewController controller, WebUri? url) async {
                print("onLoadStop=====");
                setState(() {});
              },
              onConsoleMessage: (controller, consoleMessage) {
                print(consoleMessage);
                // it will print: {message: {"bar":"bar_value","baz":"baz_value"}, messageLevel: 1}
              },
            ),
          ),
        ])),
      ),
    );
    }
  }
## Stacktrace/Logcat   
<img width="1522" alt="Screenshot 2023-03-09 at 9 58 29 PM" src="https://user-images.githubusercontent.com/127428254/224090414-f2f954da-d472-4752-add0-2035ed53f551.png">

**Comment by msutharworkspace** [comment]
@pichillilorenzo  Could you help me here?

**Comment by thanhnd10kn** [comment]
I had the same problem. but I solved it by not very good that is listening to the console log

**Comment by msutharworkspace** [comment]
Yes also resolved this by using other way.

**Comment by andresg747** [comment]
+1

**Comment by andresg747** [comment]
Having the same issue. 
It seems that "flutterInAppWebViewPlatformReady" is not being called on web. It works on iOS as expected.

**Comment by pichillilorenzo** [comment]
As you can see from the documentation (https://pub.dev/documentation/flutter_inappwebview/6.0.0-beta.23/flutter_inappwebview/InAppWebViewController/addJavaScriptHandler.html), “ addJavaScriptHandler” is not supported on Web platform.
Unfortunately, the Web platform it’s very limited on features because of iframe limitations.

**Comment by fawdlstty** [comment]
I think this issue should remain open and be closed after it is supported

**Comment by mfkk16** [comment]
I have the same issue. how can resole @msutharworkspace

**Comment by fawdlstty** [comment]
@mfkk16 if you wish call flutter api from html, you can follow this step:
1. create cache variable in html:
```html
<script type="text/javascript">
var call_flutter_ = [];
function invoke_flutter(func, args) {
    call_flutter_.push({ func: func, args: args });
}
</script>
```
2. when you want call flutter api, you can use for this: `invoke_flutter ('test_func', ['a', 1, 2])`
3. create read cache loop in flutter:
```dart
// in window:
late InAppWebViewController webController_;

// in build method:
return InAppWebView(
  // ...
  onLoadStop: (controller, url) async {
    webController_ = controller;
    timer_ = Timer.periodic(const Duration(milliseconds: 50), (timer) {
      loopTakeFromHtml(model);
    });
  },
);

// in window:
void loopTakeFromHtml(RadarReplayViewModel model) async {
  Map<String, dynamic>? item = await webController_.evaluateJavascript(
      source: "call_flutter_.shift()");
  if (item == null) {
    return;
  }
  List<dynamic> args = [];
  if (item['args'] != null) {
    if (item['args'] is List<dynamic>) {
      args = item['args'];
    }
  }
  // TODO check api and call dest methods
  // ...
}
```

**Comment by cxs8** [comment]
Do not import **web_support.js** in the web page,
as it will overwrite **window.flutter_inappwebview**,
which will result in "TypeError: window.flutter_inappwebview.callHandler is not a function".
