### ISSUE TITLE
Can you provide a screenshot of the entire page?

### ISSUE THREAD

**Issue by RodeyManager** [pichillilorenzo/flutter_inappwebview#1578]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by heralight** [comment]
You just need to fill the rect field of ScreenshotConfiguration.

**Comment by Dancas93** [comment]
How i can do the screenshot of the whole page?

**Comment by Dancas93** [comment]
> You just need to fill the rect field of ScreenshotConfiguration.

How can I do that?
