### ISSUE TITLE
HeadlessInAppWebView Android Error

### ISSUE THREAD

**Issue by Dancas93** [pichillilorenzo/flutter_inappwebview#1580]
On android i got this error with HeadlessInAppWebView, on IOS it work properly.

## Stacktrace/Logcat
```
W/cr_SupportWebSettings(18276): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): Failed to handle method call
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:574)
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:543)
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:567)
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): 	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): 	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:84)
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): 	at com.pichillilorenzo.flutter_inappwebview.headless_in_app_webview.HeadlessInAppWebViewManager.run(HeadlessInAppWebViewManager.java:77)
E/MethodChannel#com.pichillilorenzo/flutter_headless_inappwebview(18276): 	at com.pichillilorenzo.flutter_inappwebview.headless_in_app_webview.HeadlessInAppWebViewManager.onMethodCall(HeadlessInAppWebViewManager.java:62)
```

**Comment by mumenma** [comment]
D/InAppWebView(32281): Using InAppWebViewClientCompat implementation
I/System.out(32281): recordForce value 6
E/MethodChannel#flutter/platform_views(32281): Failed to handle method call
E/MethodChannel#flutter/platform_views(32281): java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL
E/MethodChannel#flutter/platform_views(32281): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:574)
E/MethodChannel#flutter/platform_views(32281): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:543)
E/MethodChannel#flutter/platform_views(32281): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:567)
E/MethodChannel#flutter/platform_views(32281): 	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:441)
E/MethodChannel#flutter/platform_views(32281): 	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:84)
E/MethodChannel#flutter/platform_views(32281): 	at com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:44)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter/platform_views(32281): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(32281): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(32281): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(32281): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#flutter/platform_views(32281): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#flutter/platform_views(32281): 	at android.app.ActivityThread.main(ActivityThread.java:8292)
E/MethodChannel#flutter/platform_views(32281): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(32281): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/MethodChannel#flutter/platform_views(32281): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/flutter (32281): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature REQUESTED_WITH_HEADER_CONTROL, null, java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL
E/flutter (32281): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:574)
E/flutter (32281): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:543)
E/flutter (32281): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:567)
E/flutter (32281): 	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:441)
E/flutter (32281): 	at com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:84)
E/flutter (32281): 	at com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:44)
E/flutter (32281): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
E/flutter (32281): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
E/flutter (32281): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter (32281): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter (32281): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (32281): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (32281): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/flutter (32281): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(Unknown Source:12)
E/flutter (32281): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (32281): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (32281): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter (32281): 	at android.os.Looper.loop(Looper.java:299)
E/flutter (32281): 	at android.app.ActivityThread.main(ActivityThread.java:8292)
E/flutter (32281): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32281): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter (32281): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/flutter (32281): )

**Comment by keremkabiloglu** [comment]
Same for me.

**Comment by Dancas93** [comment]
Any update on this? It is unusable on android.

**Comment by JeganGitHub** [comment]
Same error and same issue.

java.lang.RuntimeException: Unknown feature REQUESTED_WITH_HEADER_CONTROL

**Comment by keremkabiloglu** [comment]
According to https://developer.android.com/reference/androidx/webkit/WebViewFeature, there is no feature named REQUESTED_WITH_HEADER_CONTROL.

**Comment by DanieleCastronovo** [comment]
I tried it and the problem was gone but I got the following error on createPdf function:
`E/flutter ( 8897): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method createPdf on channel com.pichillilorenzo/flutter_inappwebview_1222170103234226210241242422502341422221012392)
E/flutter ( 8897): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter ( 8897): <asynchronous suspension>
E/flutter ( 8897): #1      InAppWebViewController.createPdf (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:3446:12)
E/flutter ( 8897): <asynchronous suspension>`

I don't know if it is related.

**Comment by JeganGitHub** [comment]
Issue is resolved, we had all latest dependency packages updated in the pubspec.lock, especially the webview_flutter_android and so forth of all dependencies associated to the Inappwebview is the root cause of this issue. Once we reverted back to the previous versions all good and working!

**Comment by IbrahimYildirim** [comment]
@JeganGitHub when will the changes be updated to the beta?

**Comment by danialvesb** [comment]
@pichillilorenzo

**Comment by icgoogo** [comment]
is this issue only on pre release 6 beta version?
6.0.0-beta.22
@Dancas93

**Comment by Dancas93** [comment]
> is this issue only on pre release 6 beta version? 6.0.0-beta.22 @Dancas93

To be honest i tried only this version.

**Comment by Alejandroem** [comment]
I got this error, but it happened when I also had another web view package this is true

> I also encountered the same problem. After troubleshooting, I found that adding the package "webview_flutter" in pubspec.yaml caused the issue. Commenting out this package resolved the problem.

**Comment by icgoogo** [comment]
> > is this issue only on pre release 6 beta version? 6.0.0-beta.22 @Dancas93
> 
> To be honest i tried only this version.

thank you. i also encountered this error on version 6. solve it with the stable version 5

**Comment by mikhael28** [comment]
<img width="865" alt="Screenshot 2023-04-27 at 9 05 38 AM" src="https://user-images.githubusercontent.com/15205259/234921149-c4c1b60c-3f53-4b5a-8dbd-3b25c537bbd4.png">

Like @JeganGitHub said, it came from transitive dependency updates. I reverted some of the lock files to these versions, and voila things work.

**Comment by mikhael28** [comment]
Also, @pichillilorenzo I'm not sure this ticket should have been closed? It looks like, moving forward, clean installs of this plugin may or may not work if people are also using the latest versions of webview_flutter alongside inappwebview, like I am. Someone should contribute a PR if they can.

**Comment by ahmed-naeem1012** [comment]
I have also been faccing the same issue for the android side!
On the Ios it works fine but for android webview doesnt load at all and prompts this error message in console!!

**Comment by Innovat-ED** [comment]
So, I am now suffering from this.

I have a HTTPS website, running an API/POST!

I can a static post to work with:


      bool trustSelfSigned = true;
      HttpClient httpClient = new HttpClient()
        ..badCertificateCallback =
            ((X509Certificate cert, String host, int port) => trustSelfSigned);
      IOClient ioClient = new IOClient(httpClient);
      var response = await ioClient.post(Uri.parse(url),
          headers: {"Content-Type": "application/json"},
          body: jsonEncode(body));
          
    I just cannot get an inappwebviewer post to work:
    
    child: InAppWebView(
                  initialUrlRequest: URLRequest(
                    url: Uri.parse(widget.url),
                    method: 'POST',
                    body: utf8.encode(postData),
                    headers: {
                      'Content-Type': 'application/json',
                    },
                  ),
                  
                  
            I have tired 6.0.0 and 5.8.0 etc no luck on andriod - IOS is fine!
