### ISSUE TITLE
Object is not define when i run app on android platform 

### ISSUE THREAD

**Issue by Azmaa22** [pichillilorenzo/flutter_inappwebview#1583]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/5.x.x/webview/javascript/communication/#web-message-listeners) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |      3.7.5         |
| VS Code version  |        1.76.1      |
| Android version |       30.0.3        |
| Xcode version   |       14.2        |

## Description
in JS side : there is the message that it will be sent to flutter side "java script communication using java script listener within inappWebview "
**Expected behavior:** 
message sent to android and ios apps 
**Current behavior:** 
message sent only to ios app but in android platform throw this error "submitData" is not defined so this is line don't work {    submitData.postMessage('submitted')}
### in app side:
`   onWebViewCreated:(InAppWebViewController controller) async {
                      webViewController = controller;if (!Platform.isAndroid ||
                          await AndroidWebViewFeature.isFeatureSupported(
                              AndroidWebViewFeature.WEB_MESSAGE_LISTENER)) {
                        await controller.addWebMessageListener(
                          WebMessageListener(
                            jsObjectName: "submitData",
                            onPostMessage: (message, sourceOrigin, isMainFrame,
                                replyProxy) {
                              print('message from js ${message!}');
                            },
                          ),
                        );
                      }}`
### in js side:
`if(status == true){
    submitData.postMessage('submitted')
}else{
    submitData.postMessage('not submitted')
}`

**Comment by Fintasys** [comment]
Does that happen with release build only or also in debug build? I just made an issue that might be related.

**Comment by ByteHunterTeam** [comment]
same

**Comment by MagTuxGit** [comment]
Same. Added channel works only after controller reload.
