### ISSUE TITLE
How to Hide Progressbar in Webview

### ISSUE THREAD

**Issue by sekkit** [pichillilorenzo/flutter_inappwebview#1588]
As the title indicates

**Comment by sjoodin** [comment]
I would also like to know. Am using this webview for a single-page app and having a bar on top of the page constantly is a bit annoying.

**Comment by sjoodin** [comment]
After searching through all documentation and not finding an answer, it turns out the problem for me was that I had implemented using an example that contained an LinearProgressIndicator stacked on top of the InAppWebView. So the solution for me was not tied to the InAppWebView itself.

**Comment by sekkit** [comment]
thx
