### ISSUE TITLE
supportZoom not working

### ISSUE THREAD

**Issue by saharvx9** [pichillilorenzo/flutter_inappwebview#159]
Here is my code:

`
Widget _inlineWebView() {
    Map<String, dynamic> options = Map<String, dynamic>();
    options.addAll({
      "supportZoom": true,
      "displayZoomControls": true,
      "javaScriptEnabled": true,
    });
    return InAppWebView(
      initialUrl: widget.link,
      onWebViewCreated: (InAppWebViewController controller){
        setState(() {
          controller.setOptions(options);
        });
      },
    );
  }
`

displayZoomControls not working and supportZoom not working i try with google link too and nothing but when i add textZoom it works this current option
pls assist me why its not working :(

**Comment by sunqihui222** [comment]
我也遇到了这个问题

**Comment by pichillilorenzo** [comment]
Fix available starting from the version `3.0.0`.
