### ISSUE TITLE
Cannot open TikTok video ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by razfazz** [pichillilorenzo/flutter_inappwebview#1590]
I can open a TikTok link in iap but when i click a video i get an error ERR_UNKNOWN_URL_SCHEME

flutter_inappwebview: 6.0.0-beta.22
Flutter (Channel stable, 3.7.7)

**Comment by abdullah017** [comment]
I encountered this problem too. Does anyone have a solution?

**Comment by pichillilorenzo** [comment]
You should use `shouldOverrideUrlLoading` event and manage there other url with custom schemes.
Check https://inappwebview.dev/docs/webview/in-app-webview#handle-custom-urls

**Comment by abdullah017** [comment]
Thank you for the reply.

Here is a sample code here;

```
shouldOverrideUrlLoading:
                      (controller, navigationAction) async {

                    //return NavigationActionPolicy.ALLOW;
                    var uri = navigationAction.request.url;
                    var url = navigationAction.request.url.toString();
                    //log("URL" + url.toString());

                    if (Platform.isAndroid && url.contains("intent")) {
                      if (url.contains("maps")) {
                        var mNewURL = url.replaceAll("intent://", "https://");
                        if (await canLaunchUrl(Uri.parse(mNewURL))) {
                          await launchUrl(Uri.parse(mNewURL));
                          return NavigationActionPolicy.CANCEL;
                        }
                      } else {
                        String id = url.substring(
                            url.indexOf('id%3D') + 5, url.indexOf('#Intent'));
                        print(id);
                        //await StoreRedirect.redirect(androidAppId: id);
                        return NavigationActionPolicy.CANCEL;
                      }
                    } else if (contains(widget.nativeApplication!, url)) {
                      print(url);
                      //url = Uri.encodeFull(url);
                      try {
                        launchUrl(Uri.parse(url));
                        return NavigationActionPolicy.CANCEL;
                      } catch (e) {
                        //launchUrl(Uri.parse(url!));
                        return NavigationActionPolicy.CANCEL;
                      }
                    } else if (![
                      "http",
                      "https",
                      "chrome",
                      "data",
                      "javascript",
                      "about"
                    ].contains(uri!.scheme)) {
                      if (await canLaunchUrl(Uri.parse(url))) {
                        await launchUrl(Uri.parse(url));
                        return NavigationActionPolicy.CANCEL;
                      }
                    }
                    return NavigationActionPolicy.ALLOW;
                  },
```

And here is the tiktok url; - debug console print -

**snssdk1340://aweme/detail/7256492730119900422?refer=web&gd_label=click_wap_top_banner_open_app&page_name=reflow_video-unifying&params_url=https%3A%2F%2Fwww.tiktok.com%2F%40egm33904lhx%2Fvideo%2F7256492730119900422%3Ftarget%3Dtop_banner_open_app%26rid%3D17043788052434331130%26vidab%3D70508271%252C71671791%252C71716731%252C71767865%252C71772629%252C71796849%252C71817220%252C71827041%252C71827226%252C71835866%252C71846813%26click_item_id%3D7256492730119900422&needlaunchlog=1&referer=direct&wid=7320236535076013574&vidab=70508271%2C71671791%2C71716731%2C71767865%2C71772629%2C71796849%2C71817220%2C71827041%2C71827226%2C71835866%2C71846813&jump_time=1704378812658&is_sub_only_video=0&ug_source=&ug_campaign= is null**

Yes, how will we perform this operation in this sample code and url structure? Can you help us?
