### ISSUE TITLE
Performance on Android

### ISSUE THREAD

**Issue by chrisvidal** [pichillilorenzo/flutter_inappwebview#1594]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.7.7        |
| Plugin version  |        ^5.7.2+3       |
| Android version |        33       |
| iOS version     |       15.        |
| macOS version   |               |
| Xcode version   |               |

## Description

**Expected behavior:** 

same perf and speed while navigating in the InAppWebView than Chrome on Android

**Current behavior:** 

While encapsulating an existing website in the InAppWebView widget, 
the navigation through the pages are slower than with using Chrome on the same mobile phone.

**Comment by ohdonpiano** [comment]
same problem here

**Comment by MonteGraph** [comment]
use inappwebview 6.0 beta it work's very fast
