### ISSUE TITLE
UIConstraintBasedLayout Error

### ISSUE THREAD

**Issue by kyuna312** [pichillilorenzo/flutter_inappwebview#1597]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  3.7.7        |
| Plugin version  |  ^0.4.0       |
| Android version |               |
| iOS version     |  16.1.1       |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:** 
Will attempt to recover by breaking constraint
**Current behavior:** 
<NSLayoutConstraint:0x28039f6b0 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x162d7e640]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x162d7e410 )>
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by maririn312** [comment]
"I searched for a solution, but I keep encountering an error related to iOS BaseLayout."

    "Despite my efforts to find a solution, I'm consistently facing an error with iOS BaseLayout."

    "I'm having trouble with iOS BaseLayout, as I keep receiving an error message despite my attempts to resolve it."

    "I've been trying to troubleshoot the issue, but I can't seem to fix the error that keeps occurring with iOS BaseLayout."
