### ISSUE TITLE
Calling show function on MacOS InAppBrowser breaks tabs

### ISSUE THREAD

**Issue by dmeuwissen** [pichillilorenzo/flutter_inappwebview#1602]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.7.1 |
| Plugin version  | 6.0.0-beta.22 |
| Android version | - |
| iOS version     | - |
| macOS version   | 13.2.1 |
| Xcode version   | 14.2 |

Device information: Macbook Pro M1

## Description

**Expected behavior:** 
When windowType = WindowType.TABBED and the show function is called on the InAppBrowser the tab should switch to the browser tab.

**Current behavior:** 
A child window is opened.

## Steps to reproduce

- windowType: WindowType.TABBED
- Open the browser with `browser.openUrlRequest`
- Switch back to the original tab (manually)
- Call `widget.browser.show();` (with a button press)

## Proposed fix
In the `InAppBrowserWindow.swift` file the show function is declared. The show function is missing a check to see if windowType is child.

Revised code:
```
 public func show() {
        if #available(macOS 10.12, *),
           !(NSApplication.shared.mainWindow?.tabbedWindows?.contains(self) ?? false),
           browserSettings?.windowType == .tabbed {
            NSApplication.shared.mainWindow?.addTabbedWindow(self, ordered: .above)
        } else if !(NSApplication.shared.mainWindow?.childWindows?.contains(self) ?? false),
                browserSettings?.windowType == .child {
            NSApplication.shared.mainWindow?.addChildWindow(self, ordered: .above)
        } else {
            orderFront(self)
        }
        NSApplication.shared.activate(ignoringOtherApps: true)        
    }
```

**Comment by pichillilorenzo** [comment]
Does it work with latest version of the plugin?

**Comment by dmeuwissen** [comment]
Just tried with version: 6.0.0-beta.24+1 and the issue still persists Here is a screen recording of the issue. With the proposed fix the issue is solved.


https://github.com/pichillilorenzo/flutter_inappwebview/assets/9661455/05e1f418-7f92-4023-9027-45b0bc1dc80c
