### ISSUE TITLE
Camera works on emulator but doesn't work on device

### ISSUE THREAD

**Issue by leobastiani** [pichillilorenzo/flutter_inappwebview#1616]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |        3.7.10-stable       |
| Plugin version  |       5.7.2+3 and 6        |
| Android version |       9        |

Device information: 

## Description

Camera works fine on emulator but I can't see anything on my device

Microphone works fine on both

## Steps to reproduce

Here is my repo https://github.com/leobastiani/flutter-good-practices-inappwebview

Take a look to commits sections, it may help

The apk can be downloaded from here https://github.com/leobastiani/flutter-good-practices-inappwebview/actions

## Images

![image](https://user-images.githubusercontent.com/8663061/230726918-f6fa3570-66b8-4310-b58c-58e97c4225dc.png)

**Comment by mohammedX6** [comment]
i have the same problem

**Comment by leobastiani** [comment]
I just found this amazing project https://github.com/holtwick/briefing ❤️
It's working fine with this one
I realized the site webcammictest.com I was using is not working on Google Chrome app too, sorry for that, I'll close this issue because the lib behaviour is the same as the browser app
