### ISSUE TITLE
Unable to Debug Web Pages Using Safari on iOS Environment

### ISSUE THREAD

**Issue by fangkyi03** [pichillilorenzo/flutter_inappwebview#1619]
Please use the following template to describe your issue:

- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section.
- [x] I have already searched for the same problem.

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.7.10        |
| Plugin version  |     5.7.2+3          |
| Android version |               |
| iOS version     | 16.4.1        |
| macOS version   | 13.3.1 (22E261)|
| Xcode version   | 14.3          |

Device information: 

## Description

**Expected behavior:** I should be able to debug web pages using Safari on iOS environment.

**Current behavior:** I am unable to connect to my web page instance on either simulator or real device, making it impossible to debug.

## Steps to reproduce

1. Try to use Safari browser's developer tools to debug a web page.
2. Attempt to connect to web page instance on either simulator or real device.
3. Fail to connect with an error message.

## Stacktrace/Logcat

**Comment by fangkyi03** [comment]
I gave every possible solution a shot in hope of getting this issue closed once and for all. Yet here I am still stuck without anything actually fixing the problem. This is absolutely annoying and upsetting.

**Comment by boring-km** [comment]
@fangkyi03 I also reported this issue [here](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1629).
