### ISSUE TITLE
Android bug: TypeError: Cannot convert object to primitive value  

### ISSUE THREAD

**Issue by AlexDochioiu** [pichillilorenzo/flutter_inappwebview#1628]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.7.12       |
| Plugin version  |     6.0.0-beta.22  |
| Android version |     12  |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: All android phones (personally tested on Xiaomi Redmi Note 11 Pro but other users reported this issue on multiple different phones)

## Description

Opening the web page [https://app.liqwid.finance/](https://app.liqwid.finance/) fails with the following error:

```
143:1 Uncaught TypeError: Cannot convert object to primitive value
    at console.<computed> [as log] (<anonymous>:1:521)
    at index-b4a08318.js:5590:248488
```

This fails in my app and the inappwebview browser (from play store). I also tried to install and use beta/canary/dev versions of WebView. The issue persists.

I tried other browser and the website loads fine.

## Steps to reproduce

1. Set inappwebview to debug mode
2. Using chrome://inspect , attache the debugger to the webview
3. Load [https://app.liqwid.finance/](https://app.liqwid.finance/) 
4. Notice error in console (and empty white page on webview)
5. Cross-reference with other browsers to see this doesn't happen and website loads

**Comment by azhon** [comment]
I also meet the same problem

**Comment by AlexDochioiu** [comment]
@azhon while this is ongoing, you might want to use my "hacky" fix:

As part of `onProgressChanged` (setup via `InAppWebView` -> `initialSettings`), run the following code:

```dart
    // disable console.log in production/profile because of a bug crashing some websites
    if (kDebugMode.not() && Platform.isAndroid) {
      await controller.evaluateJavascript(
        source: "console.debug = () => {}; window.console.debug = () => {};"
            "console.log = () => {}; window.console.log = () => {};"
            "console.info = () => {}; window.console.info = () => {};"
            "console.warn = () => {}; window.console.warn = () => {};"
            "console.error = () => {}; window.console.error = () => {};",
      );
    }
    ```

P.s: Do not try to run it only once per page or inside `onLoadStart`. I tried this first and it was flaky. Quite often the error was still happening. Having it inside `onProgressChanged` and running multiple times during page load seemed like the only consistent way to not get this issue.
