### ISSUE TITLE
iOS 16.4 WebDebugging WKWebView.isInspectable

### ISSUE THREAD

**Issue by boring-km** [pichillilorenzo/flutter_inappwebview#1629]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.7.12 |
| Plugin version  | 6.0.0-beta.22 |
| Android version |               |
| iOS version     | 16.4 |
| macOS version   |               |
| Xcode version   | 14.3 (14E222b) |

Device information: 

## Description
**Expected behavior:** 
Inspecting application on iOS 16.4 Devices by MacOS Safari

![Expected](https://user-images.githubusercontent.com/34850203/234485551-945b08e9-54ca-4fa4-8f2d-caf9078edf55.png)

**Current behavior:** 
I can't inspect application on iOS 16.4 Devices.

I already check this link: https://inappwebview.dev/docs/debugging-webviews#inspect-ios-and-macos-webviews
And WKWebView.isInspectable option have been added since **iOS 16.4**.

## Steps to reproduce

1. Set iOS Device to Enable Web Inspector on Safari Settings
2. Set inappwebview to debug mode
3. Click Safari Develop menu
4. Click Connected iOS Device and find the inspectable Applications

## Images   
![Safari No Inspectable Applications](https://user-images.githubusercontent.com/34850203/234484444-1ce1af3e-7a31-45b1-a389-3d2dfdd6fb87.png)

## Suggestion

I just add some code in InAppWebView/InAppWebView.swift and **Inspecting Application works**.

```swift
public class InAppWeView {
  // ...
  init {
    // ...
    if #available(iOS 16.4, *) {
      self.isInspectable = true
    }    
    // ...
  }
}
```

please add like this :)

```dart
InAppWebViewSettings settings = InAppWebViewSettings(
    isInspectable: true, // add this property (type bool)
);
```

**Comment by boring-km** [comment]
iOS 16.4 Document about WKWebView.isInspectable: https://developer.apple.com/documentation/webkit/wkwebview/4111163-isinspectable

**Comment by rohitvishwakarma-sf** [comment]
If you don't want to update your macOS or xcode try this
```
if webView.responds(to: Selector(("setInspectable:"))) {
    webView.perform(Selector(("setInspectable:")), with: true)
}
```
This worked for me with
`XCode -> 14.2 (14C18)`
`macOS -> 13.4 (22F66)`

Ref -> https://stackoverflow.com/a/76603043/12150745
