### ISSUE TITLE
The NavigationActionPolicy.CANCEL does not work properly in shouldOverrideUrlLoading in iOS.

### ISSUE THREAD

**Issue by HanCharles** [pichillilorenzo/flutter_inappwebview#1635]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |    3.7.12           |
| Plugin version  |    ^5.7.2+3   |
| Android version |     -          |
| iOS version     |       11.0        |
| macOS version   |     -          |
| Xcode version   |     14.2(14C18)          |

Device information: 

## Description

**Expected behavior:** 
I want to pass headers using the controller.loadUrl() method within shouldOverrideUrlLoading.
I was able to set the headers in Android by referring to 
https://stackoverflow.com/questions/61482001/flutter-webview-intercept-and-add-headers-to-all-requests, 
but I haven't been able to do it in iOS.

**Current behavior:** 
In iOS, when I do the same thing within shouldOverrideUrlLoading, 'return NavigationActionPolicy.CANCEL;' doesn't work and it seems like shouldOverrideUrlLoading is in an infinite loop.

## Steps to reproduce
Below is the code corresponding to shouldOverrideUrlLoading.

```
shouldOverrideUrlLoading: (controller, navigationAction) async {
                  var uri = navigationAction.request.url!;
                  print('shouldOverrideUrlLoading : $uri');
                  print('deviceToken : ${this.deviceToken}');

                  if (![ "http", "https", "file", "chrome", "data", "javascript", "about"].contains(uri.scheme)) {
                    if(Platform.isAndroid) {
                      if (await canLaunchUrl(uri)) {
                        print('navigate url : $uri');
                        await launchUrl(uri,);
                        return NavigationActionPolicy.CANCEL;
                      } else {
                        try {
                          var result = await platform.invokeMethod('getAppUrl', {'url': uri.toString()});
                          if(result != null) {
                            await controller.loadUrl(urlRequest: URLRequest(url: Uri.parse(result)));
                          }
                        } catch(e) {
                          print('url fail $e');
                        }
                        return NavigationActionPolicy.CANCEL;
                      }
                    } else if(Platform.isIOS){
                      if (await canLaunchUrl(uri)) {
                        print('navigate url : $uri');
                        await launchUrl(uri,);
                        return NavigationActionPolicy.CANCEL;
                      }
                    }
                  }
                  else {
                    if(this.deviceToken.isNotEmpty) {
                      print('loadUrl before');
                      controller.loadUrl(
                          urlRequest: URLRequest(
                              url: uri,
                              headers: {'authorized-fcm-token' : '${this.deviceToken}'}
                          )
                      );
                      print('loadUrl after');
                      return NavigationActionPolicy.CANCEL;
                    }
                  }

                  return NavigationActionPolicy.ALLOW;
                },
```

In the code above, when running a webview in iOS, 'loadUrl before' and 'loadUrl after' are repeatedly printed.

**Comment by HanCharles** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1350#issuecomment-1286491027

I found a similar type of question, but it was related to Android and I couldn't find the answer.

**Comment by awallgr** [comment]
Same problem for me. Anyone looking at this issue?

Did you solve it in another way?

**Comment by GunkQing** [comment]
I've got this same issue and somehow this is the only thing i can find on it and it has no solution lmao
