### ISSUE TITLE
shouldOverrideUrlLoading callback not called in Flutter web

### ISSUE THREAD

**Issue by manandhar-aarya** [pichillilorenzo/flutter_inappwebview#1636]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | >=3.7.0           |
| Plugin version  | 6.0.0-beta.22   |
| Android version |               |
| iOS version     |       16.4.1        |
| macOS version   |        13.2.1 (22D68)       |
| Xcode version   |               |

Device information: 

## Description
On Flutter web, shouldOverrideUrlLoading is not called even though I set useShouldOverrideUrlLoading: true. Other callbacks like onUpdateVisitedHistory, onNavigationResponse, shouldInterceptFetchRequest, shouldInterceptAjaxRequest and shouldInterceptRequest are also not called in the web version but they are called in iOS. Only the onLoadStart and onLoadStop are called but in the url, I am getting the initial url and not the redirected url. 

I am unable to intercept the urls during redirection in flutter web. Is there any other way that can be achieved? 

**Expected behavior:** 
shouldOverrideUrlLoading callback should be called when there is a redirection in the webview in Flutter Web.

**Current behavior:** 
shouldOverrideUrlLoading callback is not called when there is a redirection in the webview in Flutter Web.

**Comment by gkhnbks** [comment]
Have the same problem , I need to get a solution asap. are there any other possible solution ?

**Comment by manandhar-aarya** [comment]
I found that if the webview is redirecting to the same domain as the domain of the web app, then it calls onUpdateVisitedHistory function. you have to handle the redirect policy yourself from there.

**Comment by Sycket** [comment]
I have the same issue in flutter web platform. I obtain always the initial url instead of the current url. 
Have you found any solution?

**Comment by gkhnbks** [comment]
> I found that if the webview is redirecting to a link with same domain as the domain of the web app, then it calls onUpdateVisitedHistory function. you have to handle the redirect policy yourself from there.

unfortunatly I need to open a diffrent domain

**Comment by pichillilorenzo** [comment]
As you can see from the documentation (https://pub.dev/documentation/flutter_inappwebview/6.0.0-beta.23/flutter_inappwebview/InAppWebView/shouldOverrideUrlLoading.html), “ shouldOverrideUrlLoading” is not supported on Web platform.
Unfortunately, the Web platform it’s very limited on features because of iframe limitations.
