### ISSUE TITLE
target _blank not working iphone

### ISSUE THREAD

**Issue by Tharaka8999** [pichillilorenzo/flutter_inappwebview#164]
my web site have target _blank forms. they are not working in iphone. when chnage it ti _self its working. but i need it to _blank

**Comment by pichillilorenzo** [comment]
Added new `onTargetBlank` event and new `useOnTargetBlank` option in version `2.0.0`. You need to set `useOnTargetBlank` to `true` and listen the `onTargetBlank` event. In the `onTargetBlank` event, you can do whatever you want such as open another webview, etc.
Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
