### ISSUE TITLE
`windowFrame` parameter is not working [MacOS]

### ISSUE THREAD

**Issue by mustafarenkci-st** [pichillilorenzo/flutter_inappwebview#1640]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.7.12 |
| Plugin version  | 6.0.0-beta.22 |
| Android version |               |
| iOS version     |               |
| macOS version   | Ventura 13.3.1 |
| Xcode version   | 14.3 |

Device information: 

## Description
I am developing a MacOS app that includes `InAppBrowser`. Although I am setting the `windowFrame` parameter to specify the window size of `InAppBrowser` when it opens, the window size is not being updated.

```dart
  @override
  void onBrowserCreated() {
    debugPrint('onBrowserCreated called');
    InAppBrowserClassSettings browserSettings = InAppBrowserClassSettings(
      webViewSettings: InAppWebViewSettings(
        useShouldOverrideUrlLoading: false,
        mediaPlaybackRequiresUserGesture: false,
        allowsInlineMediaPlayback: true,
        iframeAllowFullscreen: true,
        sharedCookiesEnabled: true,
      ),
      browserSettings: InAppBrowserSettings(
        hideUrlBar: true,
        windowFrame: InAppWebViewRect(x: 1000, y: 0, width: 1000, height: 300),
      ),
    );

    setSettings(settings: browserSettings);
  }
```

**Comment by mustafarenkci-st** [comment]
@pichillilorenzo thanks for the update. But I'm afraid it's still not working.

**Comment by pichillilorenzo** [comment]
@mustafarenkci-st version `6.0.0-beta.24` is not released yet
