### ISSUE TITLE
WebRTC page with camera feature lags on Android

### ISSUE THREAD

**Issue by giovannilattanziocrispy** [pichillilorenzo/flutter_inappwebview#1642]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.7.11          |
| Plugin version  |       5.7.2+3 / 6.0.0-beta.22         |
| Android version |    tested on 11 and 12           |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

In a WebRTC page the camera feature lags a lot on Android devices.
Works smoothly on iOS.

**Expected behavior:** 

It should open the camera and not freeze in it.

**Current behavior:** 

The camera screen freezes. If you tap on that, it refreshes but it stops on the new state.

## Steps to reproduce

Create a blank project. Integrate flutter_inappwebview and open [this link](https://webrtc.github.io/samples/src/content/getusermedia/gum/).

**Comment by jimmyvo0512** [comment]
I also got the same issue. Are there any solutions?

**Comment by Joseph-Nathan** [comment]
any news ?
