### ISSUE TITLE
iOS build error when use 6.0.0-beta.23

### ISSUE THREAD

**Issue by hellohejinyu** [pichillilorenzo/flutter_inappwebview#1648]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |   3.10.0            |
| Plugin version  |    6.0.0-beta.23           |
| Android version |               |
| iOS version     |     iOS 16.2          |
| macOS version   |   13.3.1 (a)             |
| Xcode version   |      14.2          |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

<img width="1148" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/8766034/b50d1f9d-e93c-480e-b926-c42df8750fa0">

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
These are new properties of WKWebView available in iOS 16.4. It seems you need to upgrade XCode to the latest version 14.3 to download the latest iOS SDK to support also 16.4

**Comment by hellohejinyu** [comment]
Thanks, I see. However due to a bug in XCode 14.3, the app cannot be opened on some iOS 13.x devices, so I have not upgraded. So I can only use the latest version of `flutter_inappwebview` until Apple fixes this problem.

https://developer.apple.com/forums/thread/727680

**Comment by hellohejinyu** [comment]
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/8766034/a9413206-034a-4f01-8eb3-2396604c9c3f)
 
Everyone, you can use the latest version after upgrading to XCode 14.3.1🎉
