### ISSUE TITLE
how to hide scroll bar?

### ISSUE THREAD

**Issue by cnloop** [pichillilorenzo/flutter_inappwebview#165]

**Comment by pichillilorenzo** [comment]
Added new options `verticalScrollBarEnabled ` and `horizontalScrollBarEnabled` in `2.0.0`.
Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
