### ISSUE TITLE
flutter_inappwebview-master/ios/Classes/InAppWebView/InAppWebView.swift

### ISSUE THREAD

**Issue by Gagandeep1408** [pichillilorenzo/flutter_inappwebview#1652]
Please have a look getting error

**Comment by Gagandeep1408** [comment]
<img width="281" alt="Screenshot 2023-05-16 at 3 57 23 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/59157362/0f5115bf-75e9-472d-a565-69d20f3aa54c">

**Comment by pichillilorenzo** [comment]
duplicate of #1648

**Comment by pichillilorenzo** [comment]
Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/1648#issuecomment-1549202188

**Comment by AliPunjabi** [comment]
@pichillilorenzo for xcode 14.3.1, mac 13 is required, what if someone doesn't have it?
