### ISSUE TITLE
'Flutter/Flutter.h' file not found for other library when changing pod file for inappwebview plugin in xcode

### ISSUE THREAD

**Issue by Hardiklogistreak** [pichillilorenzo/flutter_inappwebview#1654]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |             3.3.10  
| Plugin version  |             ^6.0.0-beta.23 
| iOS version     |              Xcode 13.2.1 |

## Description

**Expected behavior:**  build app on ios 

**Current behavior:** can't build app on ios because of the error "Flutter/Flutter.h" file not found because edit pod file for inappwebview plugin this line :
''' flutter_additional_ios_build_settings(target)
 With this : installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'  # required by simple_permission
          config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end'''

## Steps to reproduce
1 run inappwebview gitrepo with any other library like permission handler on ios give this error

![Screen Shot 2023-05-17 at 11 53 38 AM](https://github.com/pichillilorenzo/flutter_inappwebview/assets/121487571/6eceee33-5376-4455-8d3b-1018503d38ed)

**Comment by bvoq** [comment]
You will need XCode 14.3 to build the newest inappwebview and make sure you've accepted the xcodelicense for the new version.
After this run flutter clean, flutter pub get, and finally pod install in the ios folder.
Then try to run it from XCode 14.3.

**Comment by Hardiklogistreak** [comment]
Ok @bvoq Will update the Xcode and check if the issue will resolve or not and will give update here

**Comment by Hardiklogistreak** [comment]
Still have an issue after update

**Comment by bvoq** [comment]
Mmm.. that's strange. 
You might have to reinstall rosetta after the update using:
`softwareupdate --install-rosetta --agree-to-license`
Open the project in Xcode and press Xcode > Project > Clean Build Folder
Then try running: `flutter clean`, `flutter pub get` and `cd ios;pod cache clean --all;pod update;pod install`.

**Comment by Hardiklogistreak** [comment]
@bvoq It's working now this was the version issue only
