### ISSUE TITLE
[Android] Issue when closing in-app browser with exit confirmation webpage

### ISSUE THREAD

**Issue by vladimir-beloded** [pichillilorenzo/flutter_inappwebview#1658]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.10.1          |
| Plugin version  |       6.0.0-beta.23        |
| Android version |     Tiramisu  (API 33)        |
| iOS version     |         -      |
| macOS version   |        -       |
| Xcode version   |        -       |

Device information: Any Android device/emulator.

## Description

When a website with the exit confirmation is opened in the in-app browser and the user closes the in-app browser, it throws an error and does not open any pages then. 

**Expected behavior:** 

When a user tries to close the in-app browser, it should wait for the user's answer on the exit confirmation dialog and only after that, close the in-app browser. 

**Current behavior:** 

When a user tries to close the in-app browser, it closes immediately and throws a `WindowLeaked` error.

## Steps to reproduce

1. Open the website with the exit confirmation in the in-app browser on Android.
2. Close the in-app browser.
3. Observe the error in the console.
4. Try to open this website again.
5. Observe that the in-app browser is stuck on the loading page.

## Images 

https://github.com/pichillilorenzo/flutter_inappwebview/assets/98315622/81675fe7-56cd-4306-b4c2-f016f9b6c5d8

## Stacktrace/Logcat 

E/WindowManager( 5115): android.view.WindowLeaked: Activity com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity has leaked window DecorView@e118b24[InAppBrowserActivity] that was originally added here
E/WindowManager( 5115): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:920)
E/WindowManager( 5115): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:908)
E/WindowManager( 5115): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:391)
E/WindowManager( 5115): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
E/WindowManager( 5115): 	at android.app.Dialog.show(Dialog.java:352)
E/WindowManager( 5115): 	at android.app.AlertDialog$Builder.show(AlertDialog.java:1131)
E/WindowManager( 5115): 	at android.webkit.JsDialogHelper.showDialog(JsDialogHelper.java:128)
E/WindowManager( 5115): 	at dF0.f(chromium-TrichromeWebViewGoogle6432.apk-stable-506007134:721)
E/WindowManager( 5115): 	at Ea.run(chromium-TrichromeWebViewGoogle6432.apk-stable-506007134:651)
E/WindowManager( 5115): 	at android.os.Handler.handleCallback(Handler.java:942)
E/WindowManager( 5115): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/WindowManager( 5115): 	at android.os.Looper.loopOnce(Looper.java:201)
E/WindowManager( 5115): 	at android.os.Looper.loop(Looper.java:288)
E/WindowManager( 5115): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/WindowManager( 5115): 	at java.lang.reflect.Method.invoke(Native Method)
E/WindowManager( 5115): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/WindowManager( 5115): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by adminant** [comment]
Exactly same issue here, after closing InAppBrowser with page not allowing to loose changes, exception comes:

Activity com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity has leaked window DecorView@8f92cd4[InAppBrowserActivity]
[...]

and subsequent runs of InAppBrowser end with empty page.
Any workaround?
