### ISSUE TITLE
How to konw  inappwebview height?

### ISSUE THREAD

**Issue by OwnerKobe** [pichillilorenzo/flutter_inappwebview#166]

**Comment by goYou** [comment]
`
onLoadStop: (InAppWebViewController controller, String url) {
              controller.evaluateJavascript(source: '''(() => { return document.body.scrollHeight;})()''').then((value) {
                if(value == null || value == '') {
                  return;
                }
                webHeight = double.parse('$value');
                setState(() {});
              });
            },
`

**Comment by goYou** [comment]
```
onLoadStop: (InAppWebViewController controller, String url) {
              controller.evaluateJavascript(source: '''(() => { return document.body.scrollHeight;})()''').then((value) {
                if(value == null || value == '') {
                  return;
                }
                webHeight = double.parse('$value');
                setState(() {});
              });
            },
```

**Comment by pichillilorenzo** [comment]
Also using the `getContentHeight` method available starting from the version `3.0.0`.

**Comment by gingerJY** [comment]
> Also using the `getContentHeight` method available starting from the version `3.0.0`.

onLoadStop: (InAppWebViewController controller, String url) async {
    int _contentHeight = await controller.getContentHeight();
    _height = double.parse(_contentHeight.toString());
    setState(() {});
},


I used 'getContentHeight', but didn't work in android. I only got 0.

**Comment by wilz05** [comment]
Did you try the above on android emulator with api version 22.. 
```
controller.getContentHeight()  //  gives wrong height  

   controller.evaluateJavascript(source: '''(() => { return document.body.scrollHeight;})()''').then((value) {
                if(value == null || value == '') {
                  return;
                }
                webHeight = double.parse('$value');
                setState(() {});
              }); // this code doesn't work. 
```

**Comment by guanshuwen** [comment]
```document.documentElement.scrollHeight``` may be better than ```document.body.scrollHeight```

**Comment by programmermager** [comment]
im little confuse, i try getContentHeight() and using evaluateJavascript the result is not same when i try log onScrollChanged and at the bottom of page.

the content height show -> 43019.
but the log of scrollX only show 9807

@pichillilorenzo please help
