### ISSUE TITLE
payment popup window (about:blank) not opening on android || ios white blank space 

### ISSUE THREAD

**Issue by abdulahath** [pichillilorenzo/flutter_inappwebview#1667]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
|----------------------| ------------- |
| Project Example Name |               |
| Flutter version      |    3.3.10           |
| Plugin version       |  6.0.0-beta.22         |
| Android version      |   11            |
| iOS version          |   12.4 & 16.2 simulator    |
| macOS version        |   12.6.3       |
| Xcode version        |  14.2             |

Device information: iphone 8 - ios 15.5 & Android 11  

## Description

**Expected behavior:** 

I am using flutter_inappwebview: ^6.0.0-beta.22 to creating a webview app for a ecommerce website .
Everything works fine except the payments popups ( about:blank ). 
==My webview app not opening the popup window on android. 
==On ios it's gone to a blank white space [ xcode log shown "[ViewportSizing] minimumViewportInset cannot be larger than frame"

**Comment by abdulahath** [comment]
No more interested

**Comment by hsb9kr** [comment]
how to fixed?

**Comment by bassamsellowpay** [comment]
> how to fixed?

have anyone got any fix yet
