### ISSUE TITLE
iOS macOS - This method should not be called on the main thread as it may lead to UI unresponsiveness

### ISSUE THREAD

**Issue by nayanAubie** [pichillilorenzo/flutter_inappwebview#1678]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |   3.10.2    |
| Plugin version  |    5.7.2+3    |
| iOS version     |     16.5     |
| macOS version   |  13.4      |
| Xcode version   |   14.3     |

Device information: iPhone 11

## Description
Error in the iOS platform when the device opens a web view "This method should not be called on the main thread as it may lead to UI unresponsiveness."

## Code
```dart
InAppWebView(
   initialUrlRequest: URLRequest(url: _webViewUri),
   initialOptions: InAppWebViewGroupOptions(
   crossPlatform: InAppWebViewOptions(
   transparentBackground: true,
   ),
   ios: IOSInAppWebViewOptions(
   allowsBackForwardNavigationGestures: false,
   ),
  ),
)
```
simply add above code in body of `Scaffold`.

## Images
<img width="500" alt="Screenshot 2023-05-31 at 11 00 05 AM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/109264909/737d76f1-2c81-4b7c-b1ad-bc44cd1dc6af">

## Stacktrace
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2023-05-31 16:42:14.217971+0530 Runner[13155:1108980] [Security] __delegate_identifier__:Performance Diagnostics__:::____message__:This method should not be called on the main thread as it may lead to UI unresponsiveness.

**Comment by Hilbert2048** [comment]
I got  so many warning message in Xcode when using InAppWebView:

This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.
This method should not be called on the main thread as it may lead to UI unresponsiveness.

**Comment by fabiansvensson** [comment]
Why are there non comments on this bug yet?

**Comment by puahhhh** [comment]
Anyone has any solution to this yet ?
