### ISSUE TITLE
Pull to refresh will not trigger in android when there's no scroll bar

### ISSUE THREAD

**Issue by emulatorchen** [pichillilorenzo/flutter_inappwebview#1683]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |   3.10.2            |
| Plugin version  |        6.0.0-beta.20 - 6.0.0-beta.23      |
| Android version |     12, 13         |
| iOS version     |        14.3.1, 14.2       |
| macOS version   |               |
| Xcode version   |       14.2        |

Device information: 

- Android simulator in version 13
- Samsung S20 Ultra

- iPhone Pro Max simulator 14.2
- iPhone Pro Max 14.3.1

## Description

**Expected behavior:** 
Pull To Refresh should trigger the event

**Current behavior:** 
Pull To Refresh will not trigger the event in android

## Steps to reproduce

Precondition:
- TestUrl: a webpage use body { height: 100%}
- Setup PullToRefresh code as [the doc described](https://inappwebview.dev/docs/webview/pull-to-refresh-controller/) for iOS and Android
- Add a log to the onRefresh event 
- Deploy code to above 4 devices

Steps: 
1. When test the app with TestUrl
2. And pull the webpage to refresh
3. Expect that
  a. iPhone simulator should show refresh icon 
  b. iPhone device should show refresh icon 
  c. Android simulator should show refresh icon 
  d. Samsung S20 Ultra should show refresh icon 
4. Actual Result
  a. iPhone simulator show refresh icon ✅ 
  b. iPhone device show refresh icon ✅ 
  c. Android simulator does not show refresh icon nor the page was not dragged ❌ 
  d. Samsung S20 Ultra does show refresh icon  nor the page was not dragged ❌ 

There will have no log output in android for onRefresh

P.S. 
- Workaround: update the page body{ height:101%} to force a scroll bar will work.
- Once there's a scroll bar in android and it's able to refresh, there will have log output for  onRefresh
- There's a similar issue found but the case was not even for iOS and also the plugin version is also not in 6, where I did not verify 5.x and old versions of target platform. https://github.com/pichillilorenzo/flutter_inappwebview/issues/1021

## Stacktrace/Logcat   
There's no stack trace when trying PullToRefresh in android

**Comment by alllohaaa** [comment]
there is one more temp workaround, but  I'm not sure if there are any drawbacks

InAppWebView.java
```
  public boolean canScrollVertically() {
    return true; //computeVerticalScrollRange() > computeVerticalScrollExtent();
  }
```

**Comment by bigr00** [comment]
It is still an issue, as when the page is not scrollable then the pull to refresh feature does not work at all.

**Comment by hxt0630** [comment]
+1
