### ISSUE TITLE
Can't compile on Android

### ISSUE THREAD

**Issue by Takabrycheri** [pichillilorenzo/flutter_inappwebview#1691]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.12.0               |
| Plugin version  | 6.0.0-beta.24              |
| Android version | 13               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 
Google Pixel 4 (original Android Studio VM with default settings)
## Description

**Expected behavior:**
Compile the app
(6.0.0-beta.23 is working fine)

**Current behavior:** 
Getting this error while compiling

## Steps to reproduce

1. Created simple WebView widget following docs
2. Trying to run the app
## Stacktrace/Logcat   
/Users/bryanmainardi/.pub-cache/hosted/pub.dev/flutter_inappwebview-6.0.0-beta.24/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/webview/in_app_webview/InAppWebViewChromeClient.java:683: error: local variable finalWindowId is accessed from within inner class; needs to be declared final
            plugin.inAppWebViewManager.windowWebViewMessages.remove(finalWindowId);

**Comment by pichillilorenzo** [comment]
it seems strange. I didn't have any compilation problems during tests. I will release a quick hotfix for that
