### ISSUE TITLE
InAppLocalhostServer is displaying the blank screen when the iPhone screen locks and try to open.

### ISSUE THREAD

**Issue by sathya4code** [pichillilorenzo/flutter_inappwebview#1695]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |    3.10.5           |
| Plugin version  |     5.7.2+3          |
| iOS version     |      all version         |

Device information: iPhone

## Description
I am using the InAppLocalhostServer to load the local html files from the device. But I am facing blank screen, when i keep the iPhone idle for sometime until the screen locks. I can't reproduce this issue in the development. Its happening from the TestFlight version only.

**Expected behavior:** 
App should not show the blank page if the phone is locked and unlocked again.

**Current behavior:** 
Keep the Mobile phone idle for sometime until the screen locks try to open the app and sub pages
Note: Pages are working fine when we kill the app and reopened.

## Steps to reproduce
1. Open the app.
2. Leave it for few minutes to lock the screen.
3. Open the app and click to load the webpage.

I have attached the video recording of the app for more understanding.

## Video 
[https://www.screencast.com/t/cpRpNpAtJP](url)

**Comment by sathya4code** [comment]
Hi,

Anyone facing this issue?

**Comment by Shinhwe** [comment]
try stop stopLocalServer when [inactive] , [paused], [detached]

`
class MainAppState extends State<MainApp> with WidgetsBindingObserver {
  @override
    void didChangeAppLifecycleState(AppLifecycleState state) {
      super.didChangeAppLifecycleState(state);
      switch (state) {
        case AppLifecycleState.resumed:
          startLocalServer();
          break;
        case AppLifecycleState.inactive:
        case AppLifecycleState.paused:
        case AppLifecycleState.detached:
          stopLocalServer();
          break;
      }
    }
}
`

**Comment by sathya4code** [comment]
Hi

**Comment by Link-X** [comment]
> Hi @Shinhwe
> 
> Thanks for your response. I tried this but didn't work. So I changed to file loading from local server.
> 
> Thanks

Can I ask you how you solved it?
