### ISSUE TITLE
Implement Authentication Flow using Deep Linking for ChromeSafariBrowser

### ISSUE THREAD

**Issue by jonasblendstrup** [pichillilorenzo/flutter_inappwebview#1696]
## Environment

**Flutter version:** 3.10.5
**Plugin version:** 6.0.0-beta.24+1
**Android version:** 13  
**iOS version:** 16.5
**Xcode version:** 14.3.1
**Device information:** -

## Description

**What you'd like to happen:** 
In issues #349, #401, and #699 @pichillilorenzo mentioned the need for implementing authentication flow using deep linking for ChromeSafariBrowser, which would allow developers to receive data from the Custom Chrome Tab / SFSafariViewController. This could solve quite a few issues, considering the amount of issues posted about the need for knowing the url's in a ChromeSafariBrowser (eg. aforementioned issues, as well as #1613, #1443, #1047).

**Alternatives you've considered:**
The package Flutter Web Auth 2 (https://pub.dev/packages/flutter_web_auth_2) allows giving a callback scheme, which may be used to return data from the opened Custom Chrome Tab. However this package doesn't use SFSafariViewController on iOS, it doesn't allow any customisation of the browser opened (such as colors), and it has other problems that could be solved using flutter_inappwebview's implementation of ChromeSafariBrowser.

**Comment by sebastianbuechler** [comment]
@jonasblendstrup Deep linking is not related to this package and you should implement it yourself: https://docs.flutter.dev/ui/navigation/deep-linking

It is highly recommended to use the Navigator 2.0 in combination with dedicated packages like go_router for this, as deep linking then comes almost for free.
