### ISSUE TITLE
Swift Compiler Error (Xcode): Cannot find 'isInspectable' in scope

### ISSUE THREAD

**Issue by Kirti1606** [pichillilorenzo/flutter_inappwebview#1697]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.10.3  |
| Plugin version  |  flutter_inappwebview: ^6.0.0-beta.24+1            |
| Android version |    11.0           |
| iOS version     |    16           |
| macOS version   |    13.4     |
| Xcode version   |   14.2            |

## Description
Launching lib/main.dart on iPhone 14 Plus in debug mode...
Xcode build done.                                            7.6s
Failed to build iOS app
Swift Compiler Error (Xcode): Cannot find 'isInspectable' in scope
/Users/kirtitripathi/.pub-cache/git/flutter_inappwebview-b00b3781ef48459cef127ff9071fb95615a1b88e/ios/Classes/InAppWebView/InAppWebView.swift:478:16
InAppWebView.swift:478

Swift Compiler Error (Xcode): Value of type 'WKPreferences' has no member 'shouldPrintBackgrounds'
/Users/kirtitripathi/.pub-cache/git/flutter_inappwebview-b00b3781ef48459cef127ff9071fb95615a1b88e/ios/Classes/InAppWebView/InAppWebView.swift:523:42

## Steps to reproduce
- I am getting this error while running the build on ios simulator.
- and I have also tried this one flutter_inappwebview: ^5.7.2+3  but  with this version I am not getting callback url to my backend server after login.
<img width="1440" alt="Screenshot 2023-06-16 at 6 13 46 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/136815955/86e24324-2152-4db9-bdfa-14009881f194">

**Comment by 2000calories** [comment]
Requirements for ^6.0.0-beta.24+1
`Xcode version >= 14.3`

**Comment by vanlooverenkoen** [comment]
This issue is still happening on 6.0.0

**Comment by daidaishuiping** [comment]
My computer's configuration doesn't support updating xcode anymore

**Comment by chief-nerd** [comment]
Same error on XCode 15.2 (which is the latest-stable) during CI/CD run

**Comment by sohamD07** [comment]
please suggest solution for those we are not able to update xcode

**Comment by wanjm** [comment]
same issue

**Comment by hoangphuc1103** [comment]
Hi everyone, my MacOs is `Monterey 14.7.5` and I can't update `XCode version >= 14.3` :((
Are there any solutions?

**Comment by phinq-mobile-dev** [comment]
Hi everyone, my MacOs is Sonoma 14.4.1 and  Xcode version 15.4 still Error
Are there any solutions?

**Comment by leadpresence** [comment]
> Hi everyone, my MacOs is `Monterey 12.7.5` and I can't update `XCode version >= 14.3` :(( Are there any solutions?

Try building app  in codemagic
