### ISSUE TITLE
Access-Control-Allow-Origin' header has a value 'null' 

### ISSUE THREAD

**Issue by devilishWei** [pichillilorenzo/flutter_inappwebview#170]
i found some solution for this

https://stackoverflow.com/questions/11318703/access-control-allow-origin-error-at-android-4-1

and it works

**Comment by pichillilorenzo** [comment]
Added new option `allowUniversalAccessFromFileURLs` for Android in version `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
