### ISSUE TITLE
flutter3.10.5 [android] cannot fill the screen

### ISSUE THREAD

**Issue by qa137** [pichillilorenzo/flutter_inappwebview#1706]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.10.5        |
| Plugin version  |       v6.0.0-beta.24+1        |
| Android version |       android9        |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

The CupertinoPageScaffold package's InAppWebView will appear with a 1-pixel right white line that will not fill the screen.

## Examples
CupertinoPageScaffold(
        backgroundColor: Colors.red,
        child: InAppWebView(.....),
)

**Comment by BrianCliton** [comment]
I also found the same problem, after testing, the android  native webview will not appear, but the flutter inappwebview  will appear

**Comment by vietkhuephan** [comment]
I also found the same problem
