### ISSUE TITLE
Cannot get mobile mode when useAgent propertie is set

### ISSUE THREAD

**Issue by doriansabo** [pichillilorenzo/flutter_inappwebview#1713]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |      3.10.5         |
| Plugin version  |       ^5.7.2+3       |
| Android version |       Android SDK version 32.1.0-rc1        |

## Description

When I run this code:

```
InAppWebView(
  key: _webViewKey,
  initialUrlRequest: URLRequest(url: Uri.parse(cubit.currentPageUrl)),
  initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      preferredContentMode: UserPreferredContentMode.MOBILE,
      applicationNameForUserAgent: 'myApp',
      userAgent: '${cubit.info.appName}/${cubit.info.version}',
      incognito: false,
      cacheEnabled: true,
      useShouldOverrideUrlLoading: true,
      useOnLoadResource: true,
    ),
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),
    ios: IOSInAppWebViewOptions(),
  ),
  onWebViewCreated: cubit.onWebViewCreated,
),
```

I get always a desktop view when the userAgent property is set. If I omit it will display the mobile view:
![Screenshot_1689069942](https://github.com/pichillilorenzo/flutter_inappwebview/assets/105852695/28422e35-ef6c-4da7-b04b-e7005cf1a850)

**Comment by totzk9** [comment]
Getting this issue as well

**Comment by totzk9** [comment]
@doriansabo I found a workaround. please use this instead `Mozilla/5.0 Mobile AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15`
