### ISSUE TITLE
how does onDownloadStartRequest work under the hood?

### ISSUE THREAD

**Issue by gerritwitkamp** [pichillilorenzo/flutter_inappwebview#1720]
Hi, 

first of all; this isn't a bug neither a feature request. I just need to know how it works and how to implement. I did not found it in the docs.

I have implemented the onDownloadStartRequest property. The downloadStartRequest argument contains some info like a suggestedFilename and mimeType.  To gather this information, a request to the uri must been done already, right? I see an incoming request in my access-log anyway. If the request has been made already, why does the downloadStartRequest argument does not contain the response of the request? Is it stored somewhere else? Based on the property name I would expect another property like onDownloadEndRequest. Do I miss something?

Thanks
Regards,
Gerrit

**Comment by edgarMejia** [comment]
Any idea about this question?

**Comment by gerritwitkamp** [comment]
Anyone?

**Comment by gerritwitkamp** [comment]
Bump
