### ISSUE TITLE
Does not support hiding dialog

### ISSUE THREAD

**Issue by hoangphuc1103** [pichillilorenzo/flutter_inappwebview#1723]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.10.6        |
| Plugin version  |     5.7.2+3          |
| Android version |               |
| iOS version     |       16.1.2     |
| macOS version   |    monterey 12.6.7      |
| Xcode version   |     14.3.1            |

Device information: 

## Description

**Expected behavior:** Support hide dialog

**Current behavior:** I use JS codes to hide the Footer and Dialog, on the web it is successfully hidden, but under the application only the footer can be hidden.

## Steps to reproduce

1. Access the website in incognito mode - https://www.tagnimal.com/th/privacy-policy/
2. Open Inspect -> Paste the JS code
`document.getElementsByClassName('footer-info footer-wrapped')[0].remove();document.querySelector('.cc-window.cc-floating.cc-type-opt-in.cc-theme-classic.cc-bottom.cc-left.cc-color-override--85071466').remove();`
4. As you can see it works fine on the web but under the app hides only the footer - https://tppr.me/9mtWa## Images 

  

![Google Chromae_2023-07-21 09-43-45@2x](https://github.com/pichillilorenzo/flutter_inappwebview/assets/135586774/cfc99fc6-2053-4002-bd5c-970f4b5dab55)

**Comment by Uhtredtb** [comment]
@pichillilorenzo Have you check this bug? 

Please let me know
