### ISSUE TITLE
webview_flutter vs flutter_inappwebview

### ISSUE THREAD

**Issue by guyluz11** [pichillilorenzo/flutter_inappwebview#1730]
I would love to get more data about this package competing to `webview_flutter` which is supported by the Flutter team.

Does it include more features and support more web technologies?

Does moving to this package may introduce speed improvements if I am loading a web game inside a web view in the app.

**Comment by MonteGraph** [comment]
I tested both and I can say what:

inappwebview 5.8 is slow than webview_flutter 3.3
but inappwebview 6.0 beta28 is very fast, work very cool

and yes inappwebview_flutter have much more settings - [InAppWebView Settings Page](https://inappwebview.dev/docs/webview/in-app-weview-settings)

**Comment by guyluz11** [comment]
> I tested both and I can say what:
> 
> inappwebview 5.8 is slow than webview_flutter 3.3 but inappwebview 6.0 beta28 is very fast, work very cool
> 
> and yes inappwebview_flutter have much more settings - [InAppWebView Settings Page](https://inappwebview.dev/docs/webview/in-app-weview-settings)

Thanks, this is helpful
