### ISSUE TITLE
using shouldOverrideUrlLoading lead to extra webview history 

### ISSUE THREAD

**Issue by adolfodoriano** [pichillilorenzo/flutter_inappwebview#1732]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.10.6        |
| Plugin version  |        ^6.0.0-beta.21       |
| Android version |       8.1.0        |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 
Huawei DUB-LX3
## Description
webview instance open webpage A, then redirect to webPageB using window.location.replace(url). after the redirection,  controller.canGoBack() return different values.

if i dont use shouldOverrideUrlLoading , controller.canGoBack() false.
if i use shouldOverrideUrlLoading, controller.canGoBack() return true, and can controller.goBack() back to webpageA.

**Expected behavior:** 
when using window.location.replace(url) to redirect, expect controller.canGoBack() always return false;
**Current behavior:** 
described above.
## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by adolfodoriano** [comment]
been searching for a few days

**Comment by cap-ylegarrec** [comment]
I think I have the same issue, did you finally found something?

**Comment by sofitry** [comment]
I can confirm this issue affects both Android and iOS on plugin version: 
  flutter_inappwebview:
    dependency: "direct main"
    description:
      name: flutter_inappwebview
      sha256: d198297060d116b94048301ee6749cd2e7d03c1f2689783f52d210a6b7aba350
      url: "https://pub.dev"
    source: hosted
    version: "5.8.0"
    
turning off shouldOverrideUrlLoading resolves the issue, but is not an option in some cases.


A sample html page which should demonstrate the issue:
'''<!DOCTYPE html>
<html>
<body onload=myFunction()>

<h1>This will auto-navigate in 1 second!</h1>

<script>

function myFunction() {
  setTimeout(function() {  location.replace("https://developer.mozilla.org/en-US/docs/Web/API/Location/replace"); }, 1000);
}
</script>

</body>
</html> 
'''
