### ISSUE TITLE
IOS application not working

### ISSUE THREAD

**Issue by sagarZodage** [pichillilorenzo/flutter_inappwebview#1734]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |               |
| Plugin version  |               |
| Android version |               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description
I have used below code but its not working and IOS side , This same code works as android for fine.

await webViewController?.loadUrl(
                urlRequest: URLRequest(
              url: Uri.tryParse(rawUrl),
              method: httpMethod,
             // headers: headers,
              body: postBodyParamString == null
                  ? null
                  : Uint8List.fromList(utf8.encode(postBodyParamString)),
            ));

Info.plist changes below

 <key>NSAppTransportSecurity</key>
        <dict>
          <key>NSExceptionDomains</key>
          <dict>
            <key>www.cashfree.com</key>
            <dict>
              
              <key>NSIncludesSubdomains</key>
              <true/>
              
              <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
              <true/>
              
              <key>NSTemporaryExceptionMinimumTLSVersion</key>
              <string>TLSv1.1</string>
            </dict>
          </dict>
        </dict>
        <key>NSAppTransportSecurity</key>
        <dict>
          <key>NSAllowsArbitraryLoads</key><true/>
        </dict>

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   
![WhatsApp Image 2023-08-01 at 10 09 04 AM](https://github.com/pichillilorenzo/flutter_inappwebview/assets/141108333/cc5f5cd8-5ff2-40b1-969e-652d0ef7522f)

## Stacktrace/Logcat   
[Security] __delegate_identifier__:Performance Diagnostics__:::____message__:This method should not be called on the main thread as it may lead to UI unresponsiveness.
[Security] __delegate_identifier__:Performance Diagnostics__:::____message__:This method should not be called on the main thread as it may lead to UI unresponsiveness.
[Security] __delegate_identifier__:Performance Diagnostics__:::____message__:This method should not be called on the main thread as it may lead to UI unresponsiveness.

**Comment by booooohdan** [comment]
Any solutions?
