### ISSUE TITLE
Can't find the sub folder files in assets

### ISSUE THREAD

**Issue by winsonet** [pichillilorenzo/flutter_inappwebview#1741]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.10.0        |
| Plugin version  |       6.0.0-beta.24+1        |
| Android version |       didn't try        |
| iOS version     |        16.4       |
| macOS version   |      13.4.1 (c)         |
| Xcode version   |        14.3.1       |

Device information: 

iPhone 14 Pro Max  simulator 

## Description

I want to display the HTML5 game with local server mode, so put all of the html and image/js files into /assets/game/ folder, and set it to flutter assets

```
flutter:
   assets:
      - assets/
```      

**Expected behavior:**   

Should be display the html5 game result 

**Current behavior:** 

Just show the errors can't find the file in html site's subfolder, for example my html site folder as below

```
game/
      images/
           wu.png
      js/
         main.js
         require.js
      index.html
```

the error as below

```
flutter: Unable to load asset: "assets/game/index.html".
The asset does not exist or has empty data.
```

## Steps to reproduce

1. copy all of the html files with a `game` folder into `assets` folder and set the `assets` folder in flutter

```
flutter:
   assets:
      - assets/
```    

actually folder structure

```
app-project
    assets/
         game/
              images/
                  ygdbns.jpg
                  gdyx.png
              js/
                 main.js
                 require.js
             index.html
```

2. create the local server
```
final InAppLocalhostServer localhostServer =
    new InAppLocalhostServer(documentRoot: 'assets');
```
 
3. call the InAppWebView

```
InAppWebView(
            //initialFile: "assets/index.html",
            initialUrlRequest: URLRequest(
                url: WebUri("http://localhost:8080/game/index.html")),
            onWebViewCreated: (controller) {},
            onLoadStart: (controller, url) {},
            onLoadStop: (controller, url) {},
          ),
```

show the error

```
flutter: Unable to load asset: "assets/game/index.html".
The asset does not exist or has empty data.
```

and I updated the flutter assets setting as below

```
flutter:
   assets:
      - assets/game/
```    

and show the error

```
flutter: Unable to load asset: "assets/game/js/require.js".
The asset does not exist or has empty data.
flutter: Unable to load asset: "assets/game/js/main.js".
The asset does not exist or has empty data.
```

and I updated the flutter assets settings again
```
  assets:
    - assets/game/
    - assets/game/js/
```

and show the error
```
flutter: Unable to load asset: "assets/game/images/ygdbns.jpg".
The asset does not exist or has empty data.
flutter: Unable to load asset: "assets/game/images/gdyx.png".
The asset does not exist or has empty data.
```

in the end, I updated the settings again and include all subfolders

```
  assets:
    - assets/game/
    - assets/game/js/
    - assets/game/images/
 ```

and this time was working very well! 

but my question is if there are many subfolders and many levels in the html site, should I need to add all of them into assets settings? I think that does not make sense and is difficult to do, so any ideas can fix it?

Thanks a lot!

**Comment by winsonet** [comment]
no one can help?

**Comment by anarnoli** [comment]
Any luck @winsonet for this issue? I am facing same issue in iOS.

**Comment by winsonet** [comment]
> Any luck @winsonet for this issue? I am facing same issue in iOS.

I am still not solving the issue and no one responded to that :(
