### ISSUE TITLE
run podinstall failed

### ISSUE THREAD

**Issue by iperfectapp** [pichillilorenzo/flutter_inappwebview#175]
[!] Unable to determine Swift version for the following pods:

- `flutter_inappbrowser` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
