### ISSUE TITLE
onCreateContextMenu not called on ios

### ISSUE THREAD

**Issue by rbonciu** [pichillilorenzo/flutter_inappwebview#1755]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.10.4      |
| Plugin version  |    5.7.2+3    |
| iOS version     |        16.0       |
| Xcode version   |      14.3      |

Device information: 

## Description

**Expected behavior:** 
Show anything in log when "onCreateContextMenu" is called. I put the "print" function inside.

**Current behavior:** 
The "onCreateContextMenu" function are not triggered after text is selected

## Steps to reproduce

1. Select text
2. Print the selected text inside "onCreateContextMenu" funtion

**Comment by westernbuptboy** [comment]
> * [x]  I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
> * [x]  I have already searched for the same problem
> 
> ## Environment
> Technology	Version
> Flutter version	3.10.4
> Plugin version	5.7.2+3
> iOS version	16.0
> Xcode version	14.3
> Device information:
> 
> ## Description
> **Expected behavior:** Show anything in log when "onCreateContextMenu" is called. I put the "print" function inside.
> 
> **Current behavior:** The "onCreateContextMenu" function are not triggered after text is selected
> 
> ## Steps to reproduce
> 1. Select text
> 2. Print the selected text inside "onCreateContextMenu" funtion

the latest version has fixed this bug

**Comment by rbonciu** [comment]
> > * [x]   I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
> > * [x]   I have already searched for the same problem
> > 
> > ## Environment
> > Technology	Version
> > Flutter version	3.10.4
> > Plugin version	5.7.2+3
> > iOS version	16.0
> > Xcode version	14.3
> > Device information:
> > ## Description
> > **Expected behavior:** Show anything in log when "onCreateContextMenu" is called. I put the "print" function inside.
> > **Current behavior:** The "onCreateContextMenu" function are not triggered after text is selected
> > ## Steps to reproduce
> > 
> > 1. Select text
> > 2. Print the selected text inside "onCreateContextMenu" funtion
> 
> the latest version has fixed this bug

I have last version and I also tried the beta version.

**Comment by westernbuptboy** [comment]
> > > * [x]    I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
> > > * [x]    I have already searched for the same problem
> > > 
> > > ## Environment
> > > Technology	Version
> > > Flutter version	3.10.4
> > > Plugin version	5.7.2+3
> > > iOS version	16.0
> > > Xcode version	14.3
> > > Device information:
> > > ## Description
> > > **Expected behavior:** Show anything in log when "onCreateContextMenu" is called. I put the "print" function inside.
> > > **Current behavior:** The "onCreateContextMenu" function are not triggered after text is selected
> > > ## Steps to reproduce
> > > 
> > > 1. Select text
> > > 2. Print the selected text inside "onCreateContextMenu" funtion
> > 
> > 
> > the latest version has fixed this bug
> 
> I have last version and I also tried the beta version.

if you use the latest version, you must add 

        menuItems: [
          ContextMenuItem(
              id: 1,
              title: "",
              action: () async {
                print("Menu item Special clicked!");
              })
        ],

to the contextMenu
