### ISSUE TITLE
Android app will crash if a screen have more than one webview and user clicked on any text of webpage.

### ISSUE THREAD

**Issue by winterdl** [pichillilorenzo/flutter_inappwebview#1758]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

flutter doctor

[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4 22F66 darwin-x64, locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

flutter_inappwebview: **^6.0.0-beta.24+1**

useHybridComposition: **false (will crash)**  // wont crash if true.

Device information: 

Redmi 9, Android 10

## Description

if a screen have more than 1 webview, useHybridComposition = false, user click on any text of a webpage, then when close the screen, app will crash.

**Expected behavior:** 
wont crash

**Current behavior:** 

Crash with message:

E/AndroidRuntime(13273): FATAL EXCEPTION: main
E/AndroidRuntime(13273): Process: com.example.webviewtest, PID: 13273
E/AndroidRuntime(13273): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime(13273):        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1627)
E/AndroidRuntime(13273):        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1871)
E/AndroidRuntime(13273):        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4881)
E/AndroidRuntime(13273):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(13273):        at android.os.Looper.loop(Looper.java:225)
E/AndroidRuntime(13273):        at android.app.ActivityThread.main(ActivityThread.java:7563)
E/AndroidRuntime(13273):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13273):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(13273):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

## Steps to reproduce

1. Run the example code on real android device, release mode
2. Select Test 2
3. Tap on text of a webpage of the screen, then press back
4. App will crash

[webviewtest.zip](https://github.com/pichillilorenzo/flutter_inappwebview/files/12385279/webviewtest.zip)

**Comment by orevial** [comment]
I can reproduce this bug after my recent upgrade of Flutter from 3.10.6 to 3.13.0.

As a workaround, setting `useHybridComposition = true` seems to fix the issue but of course it's not ideal because this parameter is not recommended for Android versions below Android 10.

```dart
InAppWebView(
   initialOptions: InAppWebViewGroupOptions(
      android: AndroidInAppWebViewOptions(
          useHybridComposition: true,
      ),
   ),
)
```

**Comment by jianxingbieli** [comment]
> 已在 flutter_inappwebview 中修复：^6.0.0-beta.30。
> 
> 谢谢！

请问如何在5.x版本中修复该问题....
