### ISSUE TITLE
Proxy Controller setProxyOverride not working

### ISSUE THREAD

**Issue by tronghuudlx** [pichillilorenzo/flutter_inappwebview#1761]
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/142889347/a030824f-f802-4218-8bca-367300911534)
[](url)
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/142889347/89a499b2-ace7-45c7-98f8-af0e8e7b9180)
I installed a proxy with username and password security but it says Invalid Proxy error
           String urlProxy = '''$host:$port''';
          if (username.isNotEmpty && password.isNotEmpty) {
            urlProxy = '''http://$username:$password@$urlProxy''';
          }
          await proxyController.setProxyOverride(
              settings: ProxySettings(
                  proxyRules: [ProxyRule(url: urlProxy)], bypassRules: []));

**Comment by yenyichau** [comment]
Same here. I want to use Socks5 username:password@host:port. It said invalid url. 
Actually is it possible to use proxy on webview? Can't find any solution.
