### ISSUE TITLE
关闭页面的时候

### ISSUE THREAD

**Issue by object1984** [pichillilorenzo/flutter_inappwebview#1774]
E/flutter (28753): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
请问是什么问题

**Comment by LianYuguai** [comment]
Have you solved it yet？
I found a similar issue in Flutter。
[https://github.com/flutter/flutter/issues/112542](https://github.com/flutter/flutter/issues/112542)
