### ISSUE TITLE
InAppWebView In ListView，show error!

### ISSUE THREAD

**Issue by zynzszyn521** [pichillilorenzo/flutter_inappwebview#1794]
Nesting an InAppWebView inside a ListView results in an error. I don't want to specify the WebView's height; I want it to adjust automatically based on the actual content. How should I solve this?

class SavePage extends GetView<SaveController> {
  const SavePage({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return GetBuilder<SaveController>(builder: (_) {
      return Scaffold(
        appBar: AppBar(
          title: Text('InAppWebView in ListView'),
        ),
        body: Column(
          children: [
            // 上部分固定在顶部
            Container(
              color: Colors.blue,
              height: 100.0,
              child: Center(
                child: Text('这是顶部部分'),
              ),
            ),
            // 中间部分可以垂直滑动
            Expanded(
              child: ListView(
                children: [
                  // 添加InAppWebView到ListView
                  InAppWebView(
                    initialUrlRequest: URLRequest(
                        url: WebUri.uri(Uri.parse('https://www.baidu.com'))),
                  ),
                  // 其他ListView子部件
                  ListTile(
                    title: Text('条目 1'),
                  ),
                  ListTile(
                    title: Text('条目 2'),
                  ),
                  // 添加更多子部件...
                ],
              ),
            ),
            // 下部分固定在底部
            Container(
              color: Colors.red,
              height: 100.0,
              child: Center(
                child: Text('这是底部部分'),
              ),
            ),
          ],
        ),
      );
    });
  }
}

**Comment by lan2000** [comment]
我最近也在搞这个，你可以看下extended_sliver ，它是 CustomScrollView + SliverToNestedScrollBoxAdapter + WebView。
不过它有一个问题，地址：`https://github.com/fluttercandies/extended_sliver/issues/18`
我测试过ListView + SizedBox （固定某个高度）+ InAppWebView ，同样也会出现以上的问题。
如果有解决方案，请告诉我，谢谢~

I've been working on this lately, you can take a look at the extended_ Sliver, it is a Custom ScrollView+SliderToNestedScrollBoxAdapter+WebView.
But it has one problem, address:` https://github.com/fluttercandies/extended_sliver/issues/18 `
I have tested ListView+SizedBox (fixed at a certain height)+InAppWebView, and the same issues can occur.
If there is a solution, please let me know. Thank you~
