### ISSUE TITLE
IllegalArgumentException couldnot find meta-data 

### ISSUE THREAD

**Issue by adnan-haider007** [pichillilorenzo/flutter_inappwebview#1798]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  Channel stable, 3.13.2             |
| Plugin version  |   flutter_inappwebview: ^5.7.2+3             |
| Android version |  Android SDK version 34.0.0             |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.2 22G91 darwin-x64, locale en-AE)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 15.0)
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

## Description
  HI i am running my website in flutter web view  using this package but i am facing a issue which is , in my website there is a form where i need to upload my data , name , details also image, so there is a button which is insert photo  when i click on it ,it works fine in web but in this plugin it give me error which is " java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.demo.flutter_inappwebview.fileprovider" i dont know what is the reason why it behave like this.

**Expected behavior:** 
it should be open a file picker or image picker in my phone , 
**Current behavior:** 
it didnot pick but app crashed and show error in log.
## Stacktrace/Logcat   
```
Java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.demo.flutter_inappwebview.fileprovider
W/System.err(12101): 	at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:664)
W/System.err(12101): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:695)
W/System.err(12101): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:645)
W/System.err(12101): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:449)
W/System.err(12101): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.getOutputUri(InAppWebViewChromeClient.java:1145)
W/System.err(12101): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.getPhotoIntent(InAppWebViewChromeClient.java:1013)
W/System.err(12101): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.startPickerIntent(InAppWebViewChromeClient.java:966)
W/System.err(12101): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.onShowFileChooser(InAppWebViewChromeClient.java:799)
W/System.err(12101): 	at WV.EC0.h(chromium-TrichromeWebViewGoogle.aab-stable-584517231:34)
W/System.err(12101): 	at WV.qc.runFileChooser(chromium-TrichromeWebViewGoogle.aab-stable-584517231:32)
W/System.err(12101): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(12101): 	at android.os.MessageQueue.next(MessageQueue.java:363)
W/System.err(12101): 	at android.os.Looper.loop(Looper.java:173)
W/System.err(12101): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(12101): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(12101): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(12101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
F/chromium(12101): [FATAL:jni_android.cc(289)] Please include Java exception stack in crash report
F/crashpad(15951): -----BEGIN CRASHPAD MINIDUMP-----
F/crashpad(15951): -----BEGIN CRASHPAD MINIDUMP-----
F/crashpad(15951): )iyJD')EqtVLK'^h-OkD7+nN?-R7+0j.'cP7)\_V_5&YaKw81e#E#_jBjPxj+SVCO7=DrB,8\]~,}-SL[g8`RrUl@uk?5Dnsv\,Adosl\gvoGV^r.DBu5lhk>\6-$Sn!a1!!J!2JEdd(ym8ZUuz$1Zov|43<]$w\^,/xQbu>2x'V1xbW>@v;kthO=/,v$yRJ+\)!6$s4<!owd8W,3J`e)Yz4Ux%N=H!1-j).=oc.APAe{-`}qv:c-!y)-wK*EWH78MYNh%;^}oF1}g\o5+?0nwx"SkWD;gjW6MjL2hr]tb`54q{gOj1p^`lV|$93Mqdz!MWLU7h8A`<N*vMV8HI]GLVzq:nw&%5aU1&u$RB`!8q_NwP'f'8+].@LE_xA!|B`}xC7@qkT3+.wYw''`Y|AkA{lS1;T%/+)_A{L,7}W?V,rTJWl`_x"_P"=x"suvblM"7nm(X<!ld<L/ZrR*t58YAVn@990Z`ftszWl8QDO,tl)]|<e:n$eb2@u2*N%p-N6
F/crashpad(15951): +xX5ozV!^vrAc"at\[X2:S}WWOLh0ZxgR[vm6O$AH-K"?An+{kOOhm>pbL.+G9,81:]ZtSAkE4o[rhP%$D|^ES3`t6Kmn-f(=O29m(gnDip9[?r\WPi1xdGLjPpF~4aA[um>kzKTS]O\9<#SNP2WOEA1:KN[kd2u~BJJ1QkS$MHrIv'Lin(B1WV)=V]zO\73b1e(66r|aA%vYT4~?.F={(E'J]8?#cL'eC11Piq67SV)6>*TDJdOFA)5crVuYT}49v0N~!])$I4?E$`chupF7Wf4J4&_m_qqq]Y.7ah*Db!s\\IF+`.b.Qmi{=cRB:L!C~BJ>}-o+ss2_gPC?JR^4xTh"LaVO6R\Z5-3uu)_6xNmiaa<9^k9#[^bsS/rN0-oni*!/=Npn0-l?BT/@c1k'?=`~!5[Lj`Y|sRX)xrb_i;vgdscsQH*5U\Rh))LajC1=fm2s/|oyun3?J&K1x,+zS:F;tF0}PQK'%P;z:J6`O2W7&1)GQ=qUR0AiCKe"2Af
```

**Comment by RamiroGarrido** [comment]
Trying to upload a file inside the web view is throwing this same error. It seems that possible solutions can be achieved by modifying the AndroidManifest.xml file....Take a look: https://stackoverflow.com/questions/56598480/couldnt-find-meta-data-for-provider-with-authority
