### ISSUE TITLE
Swift compile warning

### ISSUE THREAD

**Issue by DonizeteVida** [pichillilorenzo/flutter_inappwebview#180]
I cannot compile using flutter_inappbrowser because we got a lot of erros in xcode compiler

**Comment by pichillilorenzo** [comment]
What errors?? if they are only warnings, then there are no problems! Maybe could it be something else

**Comment by zhancheng** [comment]
i got this error for mine . 
`
note: 'NSLayoutAttribute' was obsoleted in Swift 4.2
`

**Comment by pichillilorenzo** [comment]
@zhancheng This is already done in the next version **2.0** that will be released as soon as possible! The swift code is upgraded to swift 5.0

**Comment by pichillilorenzo** [comment]
Now it should be fixed in `2.0.0`. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
