### ISSUE TITLE
Requestedwithheadermode to delete  "x requested with" header

### ISSUE THREAD

**Issue by kareldb** [pichillilorenzo/flutter_inappwebview#1817]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  3.10.0  |
| Plugin version  |  6.0.0-beta25  |
| Android version |   API 31   |

Device information: Pixel 4 Emulator

## Description

I want to delete the "x requested with" header.
The documentation speaks about Requestedwithheadermode, but that attribute isn't recognized in my IDE.

https://inappwebview.dev/docs/webview/in-app-weview-settings#requestedwithheadermode

How can I achieve this?

**Comment by pichillilorenzo** [comment]
That setting has been deleted by Android unfortunately and it was in `beta`.
I need to update also the website.
