### ISSUE TITLE
"flutterInAppWebViewPlatformReady" won't be fired

### ISSUE THREAD

**Issue by ShehabSherbiny** [pichillilorenzo/flutter_inappwebview#1820]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |        3.13.0        |
| Plugin version  |         ^5.8.0      |
| Android version |               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information:  Galaxy XCover Pro & Iphone 11 pro max

## Description

**Expected behavior:** 
It is expected that the  **flutterInAppWebViewPlatformReady** will fire consistently when loading an InAppview
**Current behavior:** 
Often, the event will not fire at all. This results in not being able to correctly manipulate the webview. 
Seems similar to https://github.com/pichillilorenzo/flutter_inappwebview/issues/541#issue-711956930

**Comment by hamonCordova** [comment]
Same here. Any solution?

**Comment by pichillilorenzo** [comment]
Provide some code example about your issue.

That event will be fired only once.
If you listen to late, you won’t receive it.
In that case, you can just check if `window.flutter_inappwebview.callHandler != null`.
If it `true`, then it means is ready to be used.

**Comment by hamonCordova** [comment]
Yeah, was the case here. I was listining to late.

**Comment by ShehabSherbiny** [comment]
> Provide some code example about your issue.
> 
> That event will be fired only once. If you listen too late, you won’t receive it. In that case, you can just check if `window.flutter_inappwebview.callHandler != null`. If it's `true`, then it means it is ready to be used.

This might very well be me misunderstanding something, but i dont see how i am listening too late?
Here is a code sample from the JS application i am hosting:

`
 window.addEventListener("flutterInAppWebViewPlatformReady", function (event) {
        if(isFlutterInAppWebViewReady === false){
       //setup....
        }
    });
`
I am adding a listener to the window. Does this need to be done as the first thing in the JS application?
@pichillilorenzo

**Comment by ShehabSherbiny** [comment]
Thank you for the explanation and example @pichillilorenzo. In retrospect, i can see that my issue was probably that i was listening to late as you say. Since posting this issue, i switched to using flutters official webview package but it presents limitations  in how it handles javascript communication, compared to your package. I'll likely have to revert it back in the near future, and then i'll rewrite the JS application to better fit your suggestion.
Thank you for your time.
