### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by farmanteachedison** [pichillilorenzo/flutter_inappwebview#1824]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |      3.10.0         |
| Plugin version  |      [6.0.0-beta.25](https://pub.dev/packages/flutter_inappwebview/versions#prerelease)         |
| Android version |      21-34         |
| iOS version     |      12-17         |
| macOS version   |               |
| Xcode version   |     15          |

Device information: 

## Description

**Expected behaviour:** 

**Current behaviour:** 

## Steps to reproduce

    private static func _setCookie(cookie: NSDictionary, result: @escaping FlutterResult) {
        let domain = cookie["domain"] as? String
        let expiresDate = cookie["expires"] as? Double
        let isSecure = cookie["secure"] as? Bool
        let isHttpOnly = cookie["httpOnly"] as? Bool
        let origin = cookie["origin"] as? String
        
        var properties: [HTTPCookiePropertyKey: Any] = [:]
        properties[.name] = cookie["name"] as! String
        properties[.value] = cookie["value"] as! String
        properties[.path] = cookie["path"] as? String ?? "/"
        if domain != nil {
            properties[.domain] = domain;
        }
        if origin != nil {
            properties[.originURL] = origin;
        }
        if expiresDate != nil {
            properties[.expires] = Date(timeIntervalSince1970: expiresDate!)
        }
        if isSecure != nil && isSecure! {
            properties[.secure] = "TRUE"
        }
        if isHttpOnly != nil && isHttpOnly! {
            properties[.init("HttpOnly")] = "YES"
        }
        
        let cookie = HTTPCookie(properties: properties)!   Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value
        
        httpCookieStore!.setCookie(cookie)
    }

I am trying to run the web view code in iOS 17 with code 15, but every time I try to access the web view iOS app crashes. Then this error was produced "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value". it targets this line "let cookie = HTTPCookie(properties: properties)!". you can see it on the above code.

## Images   

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 14.0 23A344 darwin-arm64
    (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)

**Comment by farmanteachedison** [comment]
no answer till

**Comment by farmanteachedison** [comment]
anyone can help

**Comment by pichillilorenzo** [comment]
Fixed on latest 6 version.

**Comment by farmanteachedison** [comment]
can you give me the link
