### ISSUE TITLE
I would like to add something to clearCache() that can clear cache withou clearing cookies and sessions

### ISSUE THREAD

**Issue by Samuelg0ld** [pichillilorenzo/flutter_inappwebview#1838]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by jdeepwell** [comment]
I too think this would be a great addition. I often during testing run in to situation were clearing the cache is necessary - but the fact that this also clears cookies/sessions makes it very cumbersome...

**Comment by pichillilorenzo** [comment]
Feature added starting from version 6.0.0-beta.32. Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/1903 for details.

**Comment by EArminjon** [comment]
I've tested with the flutter_inappwebview: ^6.0.0-rc.2.

Android and iOS cookies are well kept if we call clearAllCache :).
