### ISSUE TITLE
Flutter Web - TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'. error

### ISSUE THREAD

**Issue by MauroGentile** [pichillilorenzo/flutter_inappwebview#1841]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |       3.13.3        |
| Plugin version  |     flutter_inappwebview: ^6.0.0-beta.17          |
| Android version |               |
| iOS version     |               |
| macOS version   |       13.5.2 (22G91)        |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:** 
I need to integrate a D3.js chart in Flutter WEB.
I am trying to reproduce your code found in this pages https://stackoverflow.com/questions/74567197/how-to-use-flutters-webview-to-show-graphs-or-charts-e-g-through-d3-js-or-cha

**Current behavior:** 

Initially I had CORS problems which I solved by adding the line '--disable-web-security' to the chrome.dart file. And already here I am not very convinced.

Now instead I have in console this error 

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at HTMLIFrameElement.<anonymous> (web_support.js:150:32)

I am using flutter_inappwebview: ^6.0.0-beta.17

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
Indeed, you shouldn't disable web security!
As written in the official doc https://inappwebview.dev/docs/webview/in-app-webview (see the "WEB PLATFORM LIMITATION" alert), iframes have a lot of limitations, that's because you have CORS errors.
An iframe is not the same thing as a WebView that we have on Android or iOS.
