### ISSUE TITLE
Webview reload method is losing header data

### ISSUE THREAD

**Issue by tulioccalazans** [pichillilorenzo/flutter_inappwebview#1847]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |               |
| Plugin version  |               |
| Android version |               |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

On Android, await webViewController?.reload() does not consider header.

The reload method must consider all headers during reload.
If he doesn't do this, he will disregard important information such as a bearer token (which is the problem I'm facing).

**Expected behavior:** 

The reload method must consider all headers during reload.

**Current behavior:** 

After calling the reload method, error 401 occurs. In other words, this method did not reload all the headers present on the original page.

## Steps to reproduce

```
      pullToRefreshController = PullToRefreshController(
        options: PullToRefreshOptions(
          color: Colors.blue,
        ),
        onRefresh: () async {
          if (Platform.isAndroid) {
            await webViewController?.reload(); // <- This does not consider headers
          } else if (Platform.isIOS) {
            await webViewController?.loadUrl(urlRequest: URLRequest(url: await webViewController?.getUrl(), headers: _headers));
          }
        },
      );
```

1. Add some important information to the page in the header, such as a bearer token
2. Call the reload method on Android
3. If the page requires the bearer token, a 401 error will occur, as the token present in the header was not taken into account when reloading the page

**Comment by tulioccalazans** [comment]
> 👋 @tulioccalazans
> 
> **NOTE**: This comment is auto-generated.
> 
> Are you sure you have already searched for the same problem?
> 
> Some people open new issues but they didn't search for something similar or for the same issue. Please, search for it using the GitHub issue search box or on the official [inappwebview.dev](https://inappwebview.dev/) website, or, also, using Google, StackOverflow, etc. before posting a new one. You may already find an answer to your problem!
> 
> If this is really a new issue, then thank you for raising it. I will investigate it and get back to you as soon as possible. Please, make sure you have given me as much context as possible! Also, if you didn't already, post a code example that can replicate this issue.
> 
> In the meantime, you can already search for some possible solutions online! Because this plugin uses native WebView, you can search online for the same issue adding `android WebView [MY ERROR HERE]` or `ios WKWebView [MY ERROR HERE]` keywords.
> 
> Following these steps can save you, me, and other people a lot of time, thanks!

Yes. I didn't find any mention of this problem in other issues.
Perhaps this problem has not been noticed until now.

**Comment by pichillilorenzo** [comment]
Reload method just reloads the current URL. You can check the official API for Android and other platforms.
If you need to "reload" with headers, then you should call `loadUrl` again.
