### ISSUE TITLE
WebView issue in Flutter web - Not capturing URL changes

### ISSUE THREAD

**Issue by harshitkumawat20** [pichillilorenzo/flutter_inappwebview#1851]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |         3.13.3      |
| Plugin version  |        flutter_inappwebview: ^6.0.0-beta.25       |

Device information: Flutter Web(Chorme)

## Description

**Expected behavior: *I expect to be able to capture URL changes within the WebView in Flutter web and execute specific code based on the new URL.* 

**Current behavior: *I'm not able to capture these URL changes.* 

## Steps to reproduce

I have integrated a WebView in my Flutter web application, and I need to capture URL changes within the WebView and trigger specific actions based on the new URL. However, I'm not able to capture these URL changes. Neither the onLoadStop  or shouldOverrideUrlLoading or onUpdateVisitedHistory event worked as expected for Web.

The new Url gets executed but InAppWebview is not able to capture the url change.

**Comment by abdul-razzaq-now-floats** [comment]
Same issue did not worked for me. I want to capture URL changes but none of the events onLoadStop or shouldOverrideUrlLoading or onUpdateVisitedHistory works as expected for Web.

**Comment by MoriSandip** [comment]
Same issue did not worked for me... 
I want to capture URL changes but none of the events onLoadStop or shouldOverrideUrlLoading or onUpdateVisitedHistory works as expected for Web........

**Comment by pichillilorenzo** [comment]
Check the official API Reference or code doc comments for what events are supported on Web platform!
Web platform is very limited due to its nature (iframe)
