### ISSUE TITLE
Unable to run flutter_inappwebview: ^6.0.0-beta.25 on Flutter Web

### ISSUE THREAD

**Issue by StocksCafe** [pichillilorenzo/flutter_inappwebview#1856]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |         3.13.2      |
| Plugin version  |       ^6.0.0-beta.25        |
| Android version |               |
| iOS version     |               |
| macOS version   |        13.2.1       |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:** 
No errors and able to display the website

**Current behavior:** 
Uncaught PlatformException(unregistered_view_type, A HtmlElementView widget is trying to create a platform view with an unregistered type: <com.pichillilorenzo/flutter_inappwebview>., If you are the author of the PlatformView, make sure `registerViewFactory` is invoked., null)

## Steps to reproduce
Tried to run the following code on Flutter Web (i.e. Chrome) but it works on local test mode of chrome (before pushing to production).

import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

class WebView extends StatefulWidget {
  const WebView({super.key});

  @override
  WebViewState createState() => WebViewState();
}

class WebViewState extends State {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
        height: 100,
        child: InAppWebView(
          initialUrlRequest: URLRequest(url: WebUri("https://stocks.cafe/main"),
        ));
  }
}

1. This
2. Than that
3. Then

**Comment by mellowcello77** [comment]
Also getting this

**Comment by pichillilorenzo** [comment]
I was able to compile `flutter build web` the example of the repository and simply deploy and check locally using the [http-server npm package](https://www.npmjs.com/package/http-server) running the command `npx http-server` and it loads the example correctly.

**Comment by mellowcello77** [comment]
I think I did a flutter clean and it worked
