### ISSUE TITLE
Webview's Web page scroll area shrinks on Ios safari when redirect with keypad opened

### ISSUE THREAD

**Issue by qkreltms** [pichillilorenzo/flutter_inappwebview#1862]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |    3.13.9            |
| Plugin version  |      6.0.0-beta.22 and 6.0.0-beta.25         |
| Android version |               |
| iOS version     |      16.6.1         |
| macOS version   |               |
| Xcode version   |         14.3      |

Device information:  iphone 14

## Description
I have page A and B
and A page has input tag in it.
B page has height like 9999px with scroll area.

When I'm at page A with input tag focused. The keypad will open.
<img width="374" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/25196026/bcbe1ade-4bb0-4a65-aa35-05733ddf2a32">

And then when I type someting like 1234, then will be redirected to page B automatically.

**Expected behavior:** 
webview scroll area should scrollable 0 to 9999px;

**Current behavior:** 
webview scroll area scrollable 0 to 9999px - 300px (keypad height);  * page's height is still 9999px
It seems webview dosen't calculate scrollable area properly in this case. 
## Steps to reproduce
Should have resizeToAvoidBottomInset: false 
```
Scaffold(
            resizeToAvoidBottomInset: !Platform.isIOS,
            appBar: VisibleAppBar(),
            body: InAppWebView(...),
            bottomNavigationBar: const Footer()));
```
Redirect page A to B with keypad opened in ios

**Comment by pichillilorenzo** [comment]
That's because you have set `resizeToAvoidBottomInset` to `false` for iOS.
If you close the keyboard, you should see the webpage.
As you can see from the Flutter official doc of [Scaffold.resizeToAvoidBottomInset](https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html), you need to set it to `true`: 

> For example, if there is an onscreen keyboard displayed above the scaffold, the body can be resized to avoid overlapping the keyboard, which prevents widgets inside the body from being obscured by the keyboard.
