### ISSUE TITLE
5.x is not compatible with gradle 8

### ISSUE THREAD

**Issue by kjxbyz** [pichillilorenzo/flutter_inappwebview#1880]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |        3.16.0       |
| Plugin version  |        5.8.0       |
| Android version |        33       |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 

## Description

**Expected behavior:** 

```
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@10de4117 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':flutter_inappwebview'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```

**Current behavior:** 

5.x is not compatible with gradle 8.

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
Use version 6, version 5 will not be updated

**Comment by kjxbyz** [comment]
@pichillilorenzo There are many libraries that also depend on 5.x

**Comment by pichillilorenzo** [comment]
Version 5 is getting old and I can’t manage to update other versions.
I’m personally focusing on the new one, it will be officially out pretty soon.
