### ISSUE TITLE
What we gonna do after onRenderProcessUnresponsive

### ISSUE THREAD

**Issue by nizwar** [pichillilorenzo/flutter_inappwebview#1883]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | v3.16              |
| Plugin version  |  v6.0.0-beta.28             |
| Android version |  34             | 
 
## Description

**Expected behavior:** 
A way to avoid this kind of behavior

**Current behavior:** 
i load a website and inject my Javascript, i'm not sure this is the trigger, but once it loaded somehow half of the page was white blank (no console logs or message)

After that i load another website, i got onRenderProcessUnresponsive and the Webview can't no longer be use until i kill the app and open it again (restart the app, not hot restart)
 
My sus was the Ads make the problem, but it hard to track since there is no logs for the error
Once i put 
```dart 
onRenderProcessUnresponsive: (controller, uri) async {
   return WebViewRenderProcessAction.TERMINATE;
},
```
But the app was terminate once it happened and it shows error
`E/chromium( 7918): [ERROR:aw_browser_terminator.cc(156)] Renderer process (7973) crash detected (code -1).
E/chromium( 7918): [ERROR:aw_browser_terminator.cc(112)] Render process (7973) kill (OOM or update) wasn't handed by all associated webviews, killing application.`

[crashes.webm](https://github.com/pichillilorenzo/flutter_inappwebview/assets/33113137/debde0b3-4134-4c5e-aac8-31f6d4d1ea03)

Its weird behavior for user's experiences, i need some solution regarding this

**Comment by sulo61** [comment]
@nizwar how did you fix it?

**Comment by Pholluxion** [comment]
any solution?

**Comment by nizwar** [comment]
Hi, i figured out the problem, 
it caused because i set iOS userAgent, and the webview kinda invoke something that only iOS can handle, Once i make it adaptive (with android's userAgent for android) it working fine

If you wonder that your website doesn't have special code to invoking the platform, On my case, my problem is coming from the ads
