### ISSUE TITLE
onLoadStop not triggered consistently on iOS

### ISSUE THREAD

**Issue by BobVarwykTW** [pichillilorenzo/flutter_inappwebview#1886]
## Description

Expected behavior: `onLoadStop` is triggered every time the `InAppWebView` has been built.

**Current behavior: `onLoadStop` is not triggered consistently. Sometimes it runs, sometimes it does not. Which is very annoying, as a part of my screens logic depends on the `onLoadStop` Method. 

There is no error shown in the debug console or anything. It just stops out of nowhere (See attached image). I'm running the ^6.0.0-beta.30 version of InAppWebView. My current Flutter Version is 3.16.1 and `flutter doctor` provides no helpful output.

Did anyone else encounter (and fix) this issue?

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.16.1          |
| Plugin version  |    ^6.0.0-beta.30    |
| Android version |      -     |
| iOS version     |    17.0     |
| macOS version   |    Sonoma 14.1.1   |
| Xcode version   |       15.0.1        |

Device information: iOS iPhone 15 (PRO | PRO Max | Plus) Simulators & iPhone 14 Pro Device.

## Images 

<img width="1056" alt="Screenshot 2023-11-29 at 17 39 41" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/94045740/850c2061-430a-4011-a299-bac171cc6593">

**Comment by pichillilorenzo** [comment]
From your screenshot, it seems it still loading as the progress didn’t get to 100% yet.
If you share the URL, I can also test it.
The plugin just call the events as soon as they are dispatched from the native side, so it could be also possible that is related to a bug on the WebView from native side.

**Comment by BobVarwykTW** [comment]
Thanks for your answer. The URL that I am using is http://www.pipstudio.com. The issue occurs more often on my physical device (iPhone 14 Pro). I have no clue why the loading does not finish.

**Comment by pichillilorenzo** [comment]
I'm using https://www.pipstudio.com/ (HTTPS), and it's working every time on a real iPhone device.
Maybe, you are having connection issues, but I can't reproduce this issue as it seems to work correctly.
Without any additional info, I can do nothing.

This is my test code:
```dart
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
    await InAppWebViewController.setWebContentsDebuggingEnabled(kDebugMode);
  }

  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController? webViewController;
  InAppWebViewSettings settings =
      InAppWebViewSettings(isInspectable: kDebugMode);

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Example'),
        ),
        body: Column(children: <Widget>[
          Expanded(
              child: InAppWebView(
            key: webViewKey,
            initialUrlRequest:
                URLRequest(url: WebUri("https://www.pipstudio.com/")),
            initialSettings: settings,
            onWebViewCreated: (InAppWebViewController controller) {
              webViewController = controller;
            },
          )),
        ]));
  }
}
```

**Comment by BobVarwykTW** [comment]
Hi @pichillilorenzo Thanks for your feedback. I have since identified the issue. The video tag in the `Hero Banner` is preventing the `onLoadStop` from triggering. For some reason, sometimes the video can't be loaded. This only happens in the `InAppWebView` not in Device Browsers. Unsure why this is.
