### ISSUE TITLE
app doesn't launch [java.lang.ClassNotFoundException]

### ISSUE THREAD

**Issue by KnifeLemon** [pichillilorenzo/flutter_inappwebview#1890]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |  3.16.0  |
| Plugin version  | 6.0.0-beta.30    |
| Android version |  13    |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: Samsung Galaxy S23 Ultra

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

E/AndroidRuntime(15404): FATAL EXCEPTION: main
E/AndroidRuntime(15404): Process: com.test.app, PID: 15404
E/AndroidRuntime(15404): java.lang.RuntimeException: Unable to get provider com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider" on path: DexPathList[[zip file "/data/app/~~w07HC6T_PPm4B0pzAQ9avA==/com.test.app-yZoAEeSWpq6EhatUALNeGw==/base.apk"],nativeLibraryDirectories=[/data/app/~~w07HC6T_PPm4B0pzAQ9avA==/com.test.app-yZoAEeSWpq6EhatUALNeGw==/lib/arm64, /data/app/~~w07HC6T_PPm4B0pzAQ9avA==/com.test.app-yZoAEeSWpq6EhatUALNeGw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(15404): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8333)
E/AndroidRuntime(15404): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7833)
E/AndroidRuntime(15404): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7582)
E/AndroidRuntime(15404): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime(15404): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
E/AndroidRuntime(15404): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15404): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(15404): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(15404): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime(15404): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15404): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(15404): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(15404): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider" on path: DexPathList[[zip file "/data/app/~~w07HC6T_PPm4B0pzAQ9avA==/com.test.app-yZoAEeSWpq6EhatUALNeGw==/base.apk"],nativeLibraryDirectories=[/data/app/~~w07HC6T_PPm4B0pzAQ9avA==/com.test.app-yZoAEeSWpq6EhatUALNeGw==/lib/arm64, /data/app/~~w07HC6T_PPm4B0pzAQ9avA==/com.test.app-yZoAEeSWpq6EhatUALNeGw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(15404): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(15404): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(15404): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(15404): 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
E/AndroidRuntime(15404): 	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
E/AndroidRuntime(15404): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8317)
E/AndroidRuntime(15404): 	... 11 more

**Comment by pichillilorenzo** [comment]
Starting from version 6.0.0-beta.29, there is a breaking change about Android package name.
That’s the Changelog:

- Android package name has been changed to `com.pichillilorenzo.flutter_inappwebview_android`. References to old package name `com.pichillilorenzo.flutter_inappwebview` should be updated, for example inside `AndroidManifest.xml` file: `<provider android:name="com.pichillilorenzo.flutter_inappwebview_android.InAppWebViewFileProvider" android:authorities="${applicationId}.flutter_inappwebview_android.fileprovider" ...`

**Comment by kapil708** [comment]
This works for me.
New Version 6.0.0 and above.

Just change the below code in **AndroidManifest.xml**

**OLD**

`<provider
            android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
            android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>`
        
**NEW**

`<provider
            android:name="com.pichillilorenzo.flutter_inappwebview_android.InAppWebViewFileProvider"
            android:authorities="${applicationId}.flutter_inappwebview_android.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>`

**Comment by Leptune** [comment]
> This works for me. New Version 6.0.0 and above.
> 
> Just change the below code in **AndroidManifest.xml**
> 
> **OLD**
> 
> `<provider android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider" android:authorities="${applicationId}.flutter_inappwebview.fileprovider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`
> 
> **NEW**
> 
> `<provider android:name="com.pichillilorenzo.flutter_inappwebview_android.InAppWebViewFileProvider" android:authorities="${applicationId}.flutter_inappwebview_android.fileprovider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`

thx~it worked~

**Comment by Leptune** [comment]
> This works for me. New Version 6.0.0 and above.
> 
> Just change the below code in **AndroidManifest.xml**
> 
> **OLD**
> 
> `<provider android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider" android:authorities="${applicationId}.flutter_inappwebview.fileprovider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`
> 
> **NEW**
> 
> `<provider android:name="com.pichillilorenzo.flutter_inappwebview_android.InAppWebViewFileProvider" android:authorities="${applicationId}.flutter_inappwebview_android.fileprovider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`

thx!!  it worked!!
