### ISSUE TITLE
Doesn't support MacOS

### ISSUE THREAD

**Issue by sanalkv** [pichillilorenzo/flutter_inappwebview#1892]
## Environment

Flutter version - Channel stable, 3.16.2        
Plugin version  - flutter_inappwebview: ^6.0.0-beta.30          
macOS version - 14.1.1

Device information: MacBook Pro 14-inch 2023

## Description

**Expected behavior:** 
As it's mentioned that the package works on macOS, it should run without any problem.

**Current behavior:** 
The package is not running in macOS 
"**createPlatformInAppWebViewWidget is not implemented on the current platform."**

## Images

<img width="568" alt="Screenshot 2023-12-01 at 2 21 20 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/30585556/b0e798e7-9f75-4224-9f81-2d4fe193a0ab">

**Comment by pichillilorenzo** [comment]
MacOS is supported, but not the InAppWebView widget. You can use for example InAppBrowser and CookieManager.
You should check the official API reference to see the main class that are supported by the various platforms.

**Comment by sanalkv** [comment]
Ah okay thanks for the info. I will check that out (y)
