### ISSUE TITLE
getFavicons: _TypeError: type '_Map<String, dynamic>' is not a subtype of type 'Iterable<dynamic>'

### ISSUE THREAD

**Issue by AlexDochioiu** [pichillilorenzo/flutter_inappwebview#1897]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |     3.16.0     |
| Plugin version  |     6.0.0-beta.30    |
| Android version |      13     |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: Samsung SM-G985F

=======

Got the following error reported in Sentry in production:  _TypeError: type '_Map<String, dynamic>' is not a subtype of type 'Iterable<dynamic>'.

**Comment by pichillilorenzo** [comment]
Fixed in platform-specific package implementations, you can run "flutter upgrade"

**Comment by AlexDochioiu** [comment]
Awesome, thank you
