### ISSUE TITLE
Flutter 3.7.10 error Dart library 'dart:ui_web' is not available on this platform

### ISSUE THREAD

**Issue by matteopapiani01** [pichillilorenzo/flutter_inappwebview#1900]
## Environment

| Technology         |    Version       |
|-----------------| ------------- |
| Flutter version |          3.7.10       |
| Dart version     |         2.19.6       |
| Plugin version  |  6.0.0-beta.31  |
| Android version |        -       |
| iOS version     |        16.4       |
| macOS version   | 13.6.1 (22G313) |
| Xcode version   | 14.3.1 (14E300c) |

Device information: 
Chrome

## Description
After adding the dependency to the project, when you start a build (I've just tested in debug mode but I think is the same in release-mode), after a while this error message (image attached) will returns in console.

We used Flutter 3.7.10 and dart-sdk 2.19.6.
The build was done for web (so chrome) on a MacbookPro with Mac 13.6.1. 

You don't need any kind of library component, just add it to the pubspec.

## Images 
![Screenshot 2023-12-05 alle 12 44 09](https://github.com/pichillilorenzo/flutter_inappwebview/assets/132063349/9b988c14-3d54-4e5a-a404-6fc758440618)

**Comment by pichillilorenzo** [comment]
Could you try to run “flutter clean” and then install dependencies again?

**Comment by pichillilorenzo** [comment]
Have you tried to upgrade to the latest Flutter version?

**Comment by matteopapiani01** [comment]
Yeap, on the latest version of Flutter and Dart it seems to work correctly. But I am actually strictly tied to version 3.7.10 and can't update. So its certain now that the problem is the Dart and Flutter version, I will then resolve it by updating flutter. 

I would like to suggest you to update the minimum requirements to avoid a similar issues.

**Comment by pichillilorenzo** [comment]
Ok, then probably I need to update the minimum Dart SDK version.
Maybe you can use Flutter 3.7 and update just the Dart SDK?

**Comment by matteopapiani01** [comment]
No, I can't do it because Flutter depends on dart language version. Even if I try to upgrade only the Dart-SDK, Flutter will only use the embedded Dart-SDK version, so the 2.19.6. In any I case I don't think that upgrade only the Dart-SDK is a good idea, who knows how many errors it could lead to... the only one solution is to upgrade Flutter I think.

**Comment by pichillilorenzo** [comment]
Ok, in the meantime I will check if I can fix somehow the error using Flutter 3.7

**Comment by pichillilorenzo** [comment]
@fawdlstty I'm not able to reproduce the error, I can compile using Flutter 3.7.10 and latest Flutter version without any error.
Try to run `flutter clean` and install all the dependencies again.

**Comment by fawdlstty** [comment]
Using flutter clean does not work, updating the flutter version solves the problem, but it brings more problems, and I am still investigating the cause of the problem

**Comment by pichillilorenzo** [comment]
Unfortunately I’m not able to reproduce the issue, it just compiles as expected using Flutter 3.7.10.

@matteopapiani01 are you able to compile using Flutter 3.7.10?

**Comment by matteopapiani01** [comment]
I don't know, I tried it yesterday with Flutter 3.7.10 and it worked. So yes I guess.
@fawdlstty maybe you have in cache an old version; try with `flutter pub cache clean`, this command will remove every package every of every Flutter project that you have installed on your pc. Then try again with `flutter pub get` and `flutter pub upgrade`.

**Comment by fawdlstty** [comment]
No, I encountered issues with the old version of Flutter and the new version of this package.

**Comment by rahul-dezerv** [comment]
I'm getting the same error, how to resolve it? @pichillilorenzo @matteopapiani01 

```
Launching lib/main.dart on Chrome in debug mode...
main.dart:1
: Error: Undefined name 'platformViewRegistry'.
platform_view_registry_dart_ui_web.dart:8
    return ui_web.platformViewRegistry
Failed to compile application.
```

**Version details:**
`flutter_inappwebview:` ^6.0.0
> Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (6 months ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

**Comment by a-wallen** [comment]
> I'm getting the same error, how to resolve it? @pichillilorenzo @matteopapiani01
> 
> I tried `flutter pub cache clean` but still same
> 
> ```
> Launching lib/main.dart on Chrome in debug mode...
> main.dart:1
> : Error: Undefined name 'platformViewRegistry'.
> platform_view_registry_dart_ui_web.dart:8
>     return ui_web.platformViewRegistry
> Failed to compile application.
> ```
> 
> **Version details:** `flutter_inappwebview:` ^6.0.0
> 
> > Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
> > Framework • revision f468f3366c (6 months ago) • 2023-07-12 15:19:05 -0700
> > Engine • revision cdbeda788a
> > Tools • Dart 3.0.6 • DevTools 2.23.1

👋 late to the party. I'm on 3.10.1 - I get `Error: Undefined name 'platformViewRegistry'.` on every version after `6.0.0-beta.28`. I'm going to switch my project version over to `3.7.10` to try the other fix.

**Comment by psikosen** [comment]
Same issue, anyone found a work around ?
```
../../../.pub-cache/hosted/pub.dev/flutter_inappwebview_web-1.0.8/lib/web/shims/platform_view_registry_dart_ui_web.dart:8
:19: Error: Undefined name 'platformViewRegistry'.
    return ui_web.platformViewRegistry
                  ^^^^^^^^^^^^^^^^^^^^
```
Version Details: 
Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (9 months ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1

**Comment by a-wallen** [comment]
@psikosen `flutter master` doesn't seem to have this issue if you're able to switch. I'm using `3.13.9` and that works as well.

**Comment by MichaelSSY** [comment]
> 同样的问题，有人找到解决方法吗？
> 
> ```
> ../../../.pub-cache/hosted/pub.dev/flutter_inappwebview_web-1.0.8/lib/web/shims/platform_view_registry_dart_ui_web.dart:8
> :19: Error: Undefined name 'platformViewRegistry'.
>     return ui_web.platformViewRegistry
>                   ^^^^^^^^^^^^^^^^^^^^
> ```
> 
> 版本详情： Flutter 3.10.1 • 稳定版 • https://github.com/flutter/flutter.git 框架 • 修订版本 d3d8effc68（9 个月前） • 2023-05-16 17:59:05 -0700 引擎 • 修订版本 b4fb11214d 工具 • Dart 3.0.1 • DevTools 2.23.1


Has anyone found a solution to the same problem?

../../.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview_web-1.0.8/lib/web/shims/platform_view_registry_dart_ui_web.dart:8:19: Error: Undefined name 'platformViewRegistry'.
    return ui_web.platformViewRegistry
                  ^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by MichaelSSY** [comment]
> 我遇到了同样的错误，如何解决？@pichillilorenzo@matteopapiani01
> 
> 我试过了`flutter pub cache clean`，但还是一样
> 
> ```
> Launching lib/main.dart on Chrome in debug mode...
> main.dart:1
> : Error: Undefined name 'platformViewRegistry'.
> platform_view_registry_dart_ui_web.dart:8
>     return ui_web.platformViewRegistry
> Failed to compile application.
> ```
> 
> **版本详情：** `flutter_inappwebview:` ^6.0.0
> 
> > Flutter 3.10.6 • 频道稳定 • https://github.com/flutter/flutter.git
> > 框架 • 修订版 f468f3366c（6 个月前） • 2023-07-12 15:19:05 -0700
> > 引擎 • 修订版 cdbeda788a
> > 工具 • Dart 3.0.6 • DevTools 2.23.1



> > 我遇到了同样的错误，如何解决？@pichillilorenzo@matteopapiani01
> > 我试过了`flutter pub cache clean`，但还是一样
> > ```
> > Launching lib/main.dart on Chrome in debug mode...
> > main.dart:1
> > : Error: Undefined name 'platformViewRegistry'.
> > platform_view_registry_dart_ui_web.dart:8
> >     return ui_web.platformViewRegistry
> > Failed to compile application.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **版本详情：** `flutter_inappwebview:` ^6.0.0
> > > Flutter 3.10.6 • 频道稳定 • https://github.com/flutter/flutter.git
> > > 框架 • 修订版 f468f3366c（6 个月前） • 2023-07-12 15:19:05 -0700
> > > 引擎 • 修订版 cdbeda788a
> > > 工具 • Dart 3.0.6 • DevTools 2.23.1
> 
> 👋 迟到了。我使用的是 3.10.1 -`Error: Undefined name 'platformViewRegistry'.`之后的每个版本我都用过`6.0.0-beta.28`。我要将我的项目版本切换到`3.7.10`以尝试其他修复。

I encountered the same error. How did you solve it?

**Comment by MichaelSSY** [comment]
> 我遇到了同样的错误，如何解决？@pichillilorenzo@matteopapiani01
> 
> 我试过了`flutter pub cache clean`，但还是一样
> 
> ```
> Launching lib/main.dart on Chrome in debug mode...
> main.dart:1
> : Error: Undefined name 'platformViewRegistry'.
> platform_view_registry_dart_ui_web.dart:8
>     return ui_web.platformViewRegistry
> Failed to compile application.
> ```
> 
> **版本详情：** `flutter_inappwebview:` ^6.0.0
> 
> > Flutter 3.10.6 • 频道稳定 • https://github.com/flutter/flutter.git
> > 框架 • 修订版 f468f3366c（6 个月前） • 2023-07-12 15:19:05 -0700
> > 引擎 • 修订版 cdbeda788a
> > 工具 • Dart 3.0.6 • DevTools 2.23.1

我也遇到了同样的错误。你是怎么解决的？ @rahul-dezerv @pichillilorenzo

**Comment by MichaelSSY** [comment]
> @matteopapiani01 没有，我在使用旧版本的 Flutter 和新版本的这个包时都遇到了这个问题。 触发问题的代码很新，两天前更新的： https://github.com/pichillilorenzo/flutter_inappwebview/blob/7bb70eb7d97ef36866af5915c61548a456a45578/flutter_inappwebview_web/lib/web/shims/platform_view_registry_dart_ui_web.dart

I encountered the same error. How did you solve it?  @fawdlstty

**Comment by fawdlstty** [comment]
> I encountered the same error. How did you solve it? @fawdlstty

@MichaelSSY Good night. Time has passed too long, and I have forgotten this mistake. As I mentioned earlier, the Flutter version is strongly related to the Flutterapp. I will share a version I am using: Flutter: 3.16.9, Dart：3.2.6，DevTools：2.28.5，flutter_inappwebview：^6.0.0-beta.31

**Comment by MichaelSSY** [comment]
> > I encountered the same error. How did you solve it? @fawdlstty
> 
> @MichaelSSY Good night. Time has passed too long, and I have forgotten this mistake. As I mentioned earlier, the Flutter version is strongly related to the Flutterapp. I will share a version I am using: Flutter: 3.16.9, Dart：3.2.6，DevTools：2.28.5，flutter_inappwebview：^6.0.0-beta.31

Does this version run on the web without any errors? I am using this version to run the web end, but it still reports an error, which is strange.

<img width="568" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/17715591/64f4ceb1-a1da-4c0d-982e-a8391c190d22">
<img width="447" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/17715591/ceed6ef7-8f0c-4e4e-b817-401b02cf6c35">

**Comment by fawdlstty** [comment]
> Does this version run on the web without any errors? I am using this version to run the web end, but it still reports an error, which is strange.

After using this version, you can create a new project and add the content to `web/index.html` file:
```html
<script type="application/javascript" src="assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
    defer></script>
```
See if there is no problem, it may be caused by the original project file and needs to be checked one by one

Additionally, the screenshot does not seem to indicate the version of `flutter_inappwebview`

**Comment by MichaelSSY** [comment]
> > 这个版本在web端运行没有错误吗？我用这个版本运行web端，但是还是报错，很奇怪。
> 
> 使用该版本后，您可以创建一个新项目并将内容添加到`web/index.html`文件中：
> 
> ```
> <script type="application/javascript" src="assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
>     defer></script>
> ```
> 
> 看看没有问题的话，可能是原有项目文件导致的，需要逐个检查
> 
> 此外，截图似乎没有显示版本`flutter_inappwebview`

The version I am using is flutter_inappwebview: 6.0.0 rc.3

**Comment by AAChartModel** [comment]
Same issue, is there any solution?

**Comment by fawdlstty** [comment]
> Time has passed too long, and I have forgotten this mistake. As I mentioned earlier, the Flutter version is strongly related to the Flutterapp. I will share a version I am using: Flutter: 3.16.9, Dart：3.2.6，DevTools：2.28.5，flutter_inappwebview：^6.0.0-beta.31

>After using this version, you can create a new project and add the content to `web/index.html` file:
>```html
><script type="application/javascript" src="assets/packages/flutter_inappwebview_web/assets/web/web_support.js" defer></script>
>```
>See if there is no problem, it may be caused by the original project file and needs to be checked one by one
>Additionally, the screenshot does not seem to indicate the version of `flutter_inappwebview`

@AAChartModel This solution is effective for me, you can try following the steps

**Comment by Ch4rl3B** [comment]
In case someone gets here you can find a solution in [here](https://github.com/flutter/flutter/issues/137881)

Also in my case the problem was that for using ` usePathUrlStrategy()` in main I imported `import 'package:flutter_web_plugins/flutter_web_plugins.dart` and it doesn't work. The right way is to `import 'package:flutter_web_plugins/url_strategy.dart';`
