### ISSUE TITLE
FlutterInAppWebView 6.0.0-beta.31 does not work with headers [object ProgressEvent]

### ISSUE THREAD

**Issue by matteopapiani01** [pichillilorenzo/flutter_inappwebview#1901]
## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |      3.16.2         |
| Dart version     |         3.2.2       |
| Plugin version  | 6.0.0-beta.31 |
| Android version |       -        |
| iOS version     |       16.4        |
| macOS version   | 13.6.1 (22G313) |
| Xcode version   | 14.3.1 (14E300c) |

Device information: 
chrome

## Description
The InAppWebView seems don't work with custom headers

## Steps to reproduce
Configure an InAppWebView with any url and giving custom headers, the behavior obtained is the following. By removing the headers or giving an empty map it works again.

## Images
![error](https://github.com/pichillilorenzo/flutter_inappwebview/assets/132063349/1ca97c15-9280-47c7-99fc-e6daed59b141)

## Stacktrace/Logcat 
Error: [object ProgressEvent]

dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 327:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 337:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1386:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7            <fn>
[WebPlatformInAppWebViewWidget] (Web) WebPlatformInAppWebViewWidget ID 0 calling "onWebViewCreated" using []

**Comment by pichillilorenzo** [comment]
Unfortunately, Web Platform is very limited due to its nature.
The plugin works on the web platform using the [iframe HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe), which has a lot of limitations.
That error is caused by CORS policy error, so unfortunately you can't use headers where you can't change 'Access-Control-Allow-Origin' header.
It will work only if the iframe has the same origin.
