### ISSUE TITLE
[Feature Request] clearCache + keepCookies

### ISSUE THREAD

**Issue by EArminjon** [pichillilorenzo/flutter_inappwebview#1903]
## Environment

**Flutter version:** 3.13.9
**Plugin version:**  flutter_inappwebview: ^5.8.0
**Android version:**  all
**iOS version:** all
**Xcode version:** 15  
**Device information:**  all

## Description

**What you'd like to happen:** 

Could it be a good idea to create a feature to disable cache and keep cookies ?  

For example, my app contain a webview which is not always visible (it's a page). I would like to ensure that my user see the latest version of the web page every time (so no cache). The webview display some popups based on cookie choices. If I use today the 'cacheEnabled: false', cookie are deleted every times so the popups are displayed every times.

A new option to clear the cache and keep the cookies could be a good idea ?

**Alternatives you've considered:**   

**Images:**

**Comment by pichillilorenzo** [comment]
Thanks for the request, I will add this feature to the new plugin version 6 as soon as possible.

**Comment by EArminjon** [comment]
@pichillilorenzo 

I maybe miss see something. This feature seems to be already 'implemented'. But i didn't understand how :').

When i launch a webview with cacheEnabled: false, cookie are well persisted on Android and iOS.

**Comment by pichillilorenzo** [comment]
I think I need to refactor this feature in a better way.
I will reopen this issue to keep track about it, thanks.

**Comment by pichillilorenzo** [comment]
Released new version `6.0.0-beta.32`: 
- Deprecated `InAppWebViewController.clearCache` method and `InAppWebViewSettings.clearCache` property. Use `InAppWebViewController.clearAllCache` static method instead

`InAppWebViewController.clearAllCache` will clear only cache.
