### ISSUE TITLE
Flutter WebView Animation Performance Issue on Android

### ISSUE THREAD

**Issue by alphaSoft99** [pichillilorenzo/flutter_inappwebview#1914]
https://github.com/pichillilorenzo/flutter_inappwebview/assets/48862051/56d352f5-67be-40fb-b847-2a45b1938a91

I'm encountering performance issues with WebView animations in my Flutter app after upgrading from Flutter version 3.0.2 to 3.13.1. About a year ago, the app was running smoothly and correctly. However, after the update, I've noticed that iframe page animations are no longer as smooth as before.

I have uploaded a video that demonstrates the issue. In the video, you can observe the difference in animation performance between a WebView page and a page without WebView. Specifically, when displaying a bottom sheet, the animation appears to be working very slowly.

Environment
Flutter Version: 3.13.1
flutter_inappwebview Package Version: 6.0.0-beta.31 (also tested with 5.8.0)
Platform: Android (iOS app works normally)
Steps to Reproduce
Upgrade Flutter to version 3.13.1.
Use flutter_inappwebview package version 6.0.0-beta.31 or 5.8.0.
Load a WebView page containing iframes.
Observe slow animations, especially when showing a bottom sheet.
Additional Information
The issue is specific to the Android app; the iOS app works as expected.
I've tested both flutter_inappwebview versions (6.0.0-beta.31 and 5.8.0), and the problem persists.
The Home Screen includes youtube_player_flutter, which is dependent on flutter_inappwebview, and exhibits the same animation issue.
Request for Assistance
I would appreciate any guidance or assistance in resolving this performance issue. If there are specific configurations, optimizations, or updates that could address the problem, please let me know.

Thank you in advance for your support.

**Comment by pichillilorenzo** [comment]
You can try to disable Android hybrid composition and test if it can fit your use case.
New version 6 has hybrid composition enabled by default, here is more about performance: https://github.com/flutter/flutter/wiki/Hybrid-Composition#performance
Hybrid composition fixes a lot of issues (https://github.com/flutter/flutter/wiki/Hybrid-Composition#android) but it comes with performance trade-offs, that is how Flutter works for native platform views.

To disable it, use `InAppWebViewSettings.useHybridComposition` with `false`.

Also, have you tried latest flutter version?

**Comment by alphaSoft99** [comment]
Thank you for your contribution! I wanted to let you know that after setting InAppWebViewSettings.useHybridComposition to false, the Android animations started working seamlessly. Your solution resolved the issue, and the animations now run smoothly.
