### ISSUE TITLE
MacOS createPlatformInAppWebViewWidget is not implemented on the current platform.

### ISSUE THREAD

**Issue by alphaSoft99** [pichillilorenzo/flutter_inappwebview#1920]
UnimplementedError: createPlatformInAppWebViewWidget is not implemented on the current platform.
See also: https://flutter.dev/docs/testing/errors

I used  flutter_inappwebview: ^6.0.0-beta.32 version, Flutter version: 3.13.1, MacOS 14.1. Release and Debug mode both not worked

**Comment by pichillilorenzo** [comment]
That’s correct, it is not supported yet

**Comment by alphaSoft99** [comment]
Which macOS version support now?

**Comment by pichillilorenzo** [comment]
Currently, you can use InAppBrowser or HeadlessInAppWebView on macOS.
InAppWebView is not supported yet because Flutter itself doesn’t support platform views on desktop.

**Comment by ekuleshov** [comment]
> Currently, you can use InAppBrowser or HeadlessInAppWebView on macOS. InAppWebView is not supported yet because Flutter itself doesn’t support platform views on desktop.

That is actually critical information that should be highlighted and emphasized in the macOS sections of this plugin readme.

**Comment by pichillilorenzo** [comment]
@ekuleshov each `flutter_inappwebview` API has already its own Platform support list.
Check the official API Reference for it.

**Comment by ekuleshov** [comment]
> @ekuleshov each `flutter_inappwebview` API has already its own Platform support list. Check the official API Reference for it.

@pichillilorenzo you missed the readme part. It makes an illusion that all platforms are fully supported, yet you have to dig through API Reference pages to discover severe limitations of each individual platform.

**Comment by pichillilorenzo** [comment]
Probably, for each main feature, such as InAppWebView, InAppBrowser, CookieManager, etc., I can add a simple platform support table.
But for each specific API, it’s not feasible 
, so you should use the API Reference and/or doc comments. 
There are a lot of classes, methods, and properties, so it’s not feasible to list them all. 
For that, you would use the API Reference. 

As you can see, this plugin is not simple and doesn’t contain just few methods.

If you want, feel free to make pull requests on the repo of the official website.

**Comment by pichillilorenzo** [comment]
Also, WebViews are not a simple concept.
There is no magic here, just a lot of work on my free time.

**Comment by pichillilorenzo** [comment]
For desktop support, follow https://github.com/pichillilorenzo/flutter_inappwebview/issues/460

**Comment by bahricanyesil** [comment]
I agree with the creator of this issue and the comments from @ekuleshov. I've decided to migrate to your package from webview_cef when I see the macOS support. However, it's not yet supported as intended as far as I understand. You may highlight this critical information @pichillilorenzo. Thank you for all your hard work and the package. Have a nice year 🙏

**Comment by pichillilorenzo** [comment]
As I said, I will add info for the main features to have a quick overview for platform support also on the README and on the official website, but for methods and properties you should use the API Reference.

You can also help, adding documentation on the repo or updating the official website making pull requests 👍.

webview_cef seems to use its own “platform view” implementation.
Maybe it could be a possible way to implement the InAppWebView widget before Flutter itself releases a new version that natively supports it.

**Comment by alphaSoft99** [comment]
Hello contributors, in the Flutter InAppWebView version 6.0.0 release, the inAppWebView functionality is still not operational on MacOS (Sonama 14.2.1 (23C71)). While developing a desktop app, I've resorted to using the webview_windows plugin for Windows. However, I'm facing difficulties finding a similar plugin for MacOS.

**Comment by bahricanyesil** [comment]
> Hello contributors, in the Flutter InAppWebView version 6.0.0 release, the inAppWebView functionality is still not operational on MacOS (Sonama 14.2.1 (23C71)). While developing a desktop app, I've resorted to using the webview_windows plugin for Windows. However, I'm facing difficulties finding a similar plugin for MacOS.

Hello, you may choose to use [webview_cef](https://github.com/hlwhl/webview_cef) for now. You should not add it directly as a dependency but you should add it as a path dependency like:
`
  webview_cef:
    path: ./custom-packages/custom-webview_cef
`

Additionally, since its Pubdev page is not up to date, you need to refer to the [GitHub page](https://github.com/hlwhl/webview_cef) and GitHub readme.
