### ISSUE TITLE
Read FileSystem from applicationDocument directory

### ISSUE THREAD

**Issue by MiguelG97** [pichillilorenzo/flutter_inappwebview#1921]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description
Currently when setting a path to the application directory in the js file, the widget is adding the "assets/" extension to load it from the asset folder.
**What you'd like to happen:** 
I wish to pass references to the application directory instead of the assets folder.

**Alternatives you've considered:**   
I've considered using the webViewAssetLoader(pathHandlers: [
InternalStoragePathHandler() .... 
])

![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/21e8cee3-f0e7-489d-8d96-200f58a03467)

but did not succeed with it since there is lack of documentation and something was failing.
The AssetsPathHandler() didn't help

**Images:**

**Comment by pichillilorenzo** [comment]
The default `PathHandler`s available are relative to the current application, I don't think you can use such an absolute path there.

Plugin documentation: https://inappwebview.dev/docs/webview/webview-asset-loader
> WebViewAssetLoader is an Android-only helper class used to load local files including application's static assets and resources

Official Android documentation:
- `WebViewAssetLoader`: https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader
- `WebViewAssetLoader.AssetsPathHandler`: https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader.AssetsPathHandler
- `WebViewAssetLoader.ResourcesPathHandler`: https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader.ResourcesPathHandler
- `WebViewAssetLoader.InternalStoragePathHandler`: https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader.InternalStoragePathHandler

If you need a custom path handler, using the latest plugin version `6.0.0-rc.2`, you can extend the `CustomPathHandler` abstract class.

Here is an example using also the [mime](https://pub.dev/packages/mime) package to try to get the correct resource content type:
```dart
import 'package:mime/mime.dart';

class MyCustomPathHandler extends CustomPathHandler {
  MyCustomPathHandler({required super.path});

  @override
  Future<WebResourceResponse?> handle(String path) async {
    try {
      final assetPath = path.replaceFirst("flutter_assets/", "");
      final data = await rootBundle.load(assetPath);
      return WebResourceResponse(
        contentType: lookupMimeType(path),
        data: data.buffer.asUint8List(),
      );
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }
    return WebResourceResponse(data: null);
  }
}
// ...
InAppWebViewSettings settings = InAppWebViewSettings(
  webViewAssetLoader: WebViewAssetLoader(
    pathHandlers: [
      MyCustomPathHandler(path: '/assets/')
    ]
  )
);
```

**Comment by MiguelG97** [comment]
Hi @pichillilorenzo, Hope you've got a wonderful christmas time!
Here is some context of what is going on

i) from js file, an API command ask for a local path:
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/77e73c3c-9963-42ac-b5d9-66e7ac7d8f34)
```
  const options = {
    env: "Local",
    document:
      "./data/user/0/com.example.minisitewalkapp/app_flutter/Floor Plan/Unit Floor Plan1.pdf",
  };
```
And I'm providing a pdf from the docApp directory

List of assets:
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/f3528361-8dda-4887-b4fc-b574473485c2)


ii)from flutter side, the /assets/wwwroot extension gets included even after using the custom path handler
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/5365434a-5e32-4ff7-b81c-69846c55aa2d)

I/flutter (14058): ./assets/wwwroot/data/user/0/com.example.minisitewalkapp/app_flutter/Floor Plan/Unit Floor Plan1.pdf
I/flutter (14058): Unable to load asset: "./assets/wwwroot/data/user/0/com.example.minisitewalkapp/app_flutter/Floor Plan/Unit Floor Plan1.pdf".
I/flutter (14058): The asset does not exist or has empty data.


Seems to be the way but the breakpoints are not being triggered for the customPathHandler. Would be nice if the handle function actually intercept the action and response with data from the docAppDirectory

```
class MyCustomPathHandler extends CustomPathHandler {
  MyCustomPathHandler({required super.path});

  @override
  Future<WebResourceResponse?> handle(String path) async {
    try {
      final assetPath = path.replaceFirst("/assets/wwwroot", "");
      final data = await rootBundle.load(assetPath);
      return WebResourceResponse(
        contentType: lookupMimeType(path),
        data: data.buffer.asUint8List(),
      );
    } catch (e) {
      print(e);
    }
    return WebResourceResponse(data: null);
  }
}
```



```
return InAppWebView(
          initialSettings: InAppWebViewSettings(
              webViewAssetLoader: WebViewAssetLoader(
                  pathHandlers: [MyCustomPathHandler(path: "/")])),
          onConsoleMessage: (controller, consoleMessage) {
            print(consoleMessage.message);
          },
          initialUrlRequest: URLRequest(
              url: WebUri.uri(Uri.parse(
                  "http://localhost:8080/assets/wwwroot/index.html"))),
```

**Comment by pichillilorenzo** [comment]
You are using it using an absolute path that is `/data/user/0/com.example.minisitewalkapp/app_flutter/`.
Flutter [rootBundle](https://api.flutter.dev/flutter/services/rootBundle.html) function will consider only the file that are inside your Flutter assets folder
Please, read the official documentation, you probably can just use the default `AssetsPathHandler(path: '/assets/')` like this:
```dart
InAppWebView(
  initialSettings: InAppWebViewSettings(
      webViewAssetLoader: WebViewAssetLoader(
          pathHandlers: [AssetsPathHandler(path: '/assets/')])),
  onConsoleMessage: (controller, consoleMessage) {
    print(consoleMessage.message);
  },
  initialUrlRequest: URLRequest(
      url: WebUri.uri(Uri.parse(
          "https://appassets.androidplatform.net/assets/flutter_assets/assets/wwwroot/index.html"))),
),
```
Also, you are using `http://localhost:8080` as webview URL but your current `WebViewAssetLoader` implementation implies `https://appassets.androidplatform.net` to be the current URL using the default `WebViewAssetLoader` without a custom domain, so you current implementation will not work as it is.

**Comment by pichillilorenzo** [comment]
Anyway, the WebView doesn't have a way to display PDF.
A WebView is not like a Browser, as may you think.
**WebView != Browser**

**Comment by MiguelG97** [comment]
autodesk forge api allows to pass local pdf files to display 2D floor plans or svf files for 3D views. We taking advantage of this since managers requested to the team to support offline workflow otherwise we were about to drop it out since the lack of network in site.

Many thanks @pichillilorenzo! appreciate the help, we managed to use the customPathHandler to return files from the app document directory folder instead of the flutter asset folder!! Brilliant package!

**Comment by MiguelG97** [comment]
I take back what I've just said since the main platform we are targetting is ios. 

@pichillilorenzo  Are you planning to release a new version that support customPathHandlers for IOs?

or any suggestions on how to make it work for ios. The current implementation is throwing those stacks and notifications:

![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/bde75bfb-796a-4f3b-b48b-362655bfa70c)
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/68375081-c9a6-4194-9337-77bba7871798)

{error: {description: A server with the specified hostname could not be found., type: -1003}, request: {hasGesture: false, method: GET, url: https://appassets.androidplatform.net/assets/flutter_assets/assets/wwwroot/index.html, headers: null, isRedirect: false, isForMainFrame: true}}

createPlatformCustomPathHandler is not implemented on the current platform.


kind regards!

**Comment by pichillilorenzo** [comment]
WebViewAssetLoader is something specific only to Android.
If you want something similar on iOS, you should register and use a custom scheme and a custom scheme handler.

**Comment by MiguelG97** [comment]
Appreaciate the suggestion @pichillilorenzo !
Indeed, registering a URL scheme enables me to return a new CustomSchemeResponse using data coming from the app document directory instead of the asset folder

`initialUrlRequest: URLRequest(
              url: WebUri.uri(Uri.parse(
                  "sitewalkappsch://localhost:8080/assets/wwwroot/index.html"))),
  ...
  ...
onLoadResourceWithCustomScheme: (controller, request) async {
            String path = "";
            if (request.url.toString().contains("Users/miguelg97")) {

              //FINALLY REMOVING THE assets/wwwroot/ extension from the doc directory folder path!!
              path = request.url.toString().replaceFirst(
                  "sitewalkappsch://localhost:8080/assets/wwwroot/", "");
              path = path.replaceAll("%20", " ");

              print(path);
              File mainFile = File(path);
              try {
                Uint8List bytesStored = await mainFile.readAsBytes();
                return CustomSchemeResponse(
                  contentType: lookupMimeType(path)!,
                  data: bytesStored,
                );
              } catch (e) {
                print(e);

                return null;
              }
            }
            
            return null;
          },
                  `

Cheers!!

**Comment by MiguelG97** [comment]
It's us again, sorry to bother you @pichillilorenzo

We are having a hard time loading data from files with unrecognized extensions. For instance: 
- ${appDocDir.Path}/3dview/{3D}.svf
- ...0.pf
- etc

we tried using the text/plain | application/octet-stream as the mime type since the lookupMimeType(path) returns null for those file types.

`onLoadResourceWithCustomScheme: (controller, request) async {
            String path = "";
            if (request.url.toString().contains("Users/miguelg97")) {
              path = request.url.toString().replaceFirst(
                  "sitewalkappsch://localhost:8080/assets/wwwroot/", "");
              path = path.replaceAll("%20", " "); //blank spaces
              path = path.replaceAll("%7B", "{");
              path = path.replaceAll("%7D", "}");
              //or app doc directory + file name!
              print(path);
              File mainFile = File(path);
              try {
                Uint8List bytesStored = await mainFile.readAsBytes();
                print(lookupMimeType(path));
                return CustomSchemeResponse(
                  contentType: lookupMimeType(path) != null
                      ? lookupMimeType(path)!
                      : "text/plain", //application/json | application/octet-stream
                  data: bytesStored,
                );
              } catch (e) {
                print(e);

                return null;
              }
            }
            
            ...
          },`

Any hints on which mime type should we use for those cases?
Regards
Miguel G.

**Comment by pichillilorenzo** [comment]
Sorry, but I don’t know. It seems they are not standard extensions.
You should check how it would work maybe on Google chrome or some other browser to understand how it works and try to replicate the behaviour.

**Comment by MiguelG97** [comment]
From this quick [demo](https://aps-simple-viewer-nodejs.autodesk.io/#dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6cGV0cmJyb3otc2FtcGxlcy9ybWVfYWR2YW5jZWRfc2FtcGxlX3Byb2plY3QucnZ0)

the conten type for .svf files seems to be a octet-stream

![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/0469fdea-c3cc-4bf2-bea8-c6790e28bb10)

In the flutter side, when setting it up I still get this error:

flutter: Error while processing SVF: {"url":"sitewalkappsch://localhost:8080/assets/wwwroot//Users/miguelg97/Library/Developer/CoreSimulator/Devices/25A2A121-705C-478B-81B3-412BC8702AE1/data/Containers/Data/Application/D54C04F5-5079-4FE9-8650-8208900F2FE9/Documents/46_HARRISON_SQUARE/3dview/3D.svf","httpStatus":0,"httpStatusText":"","data":{"url":"sitewalkappsch://localhost:8080/assets/wwwroot//Users/miguelg97/Library/Developer/CoreSimulator/Devices/25A2A121-705C-478B-81B3-412BC8702AE1/data/Containers/Data/Application/D54C04F5-5079-4FE9-8650-8208900F2FE9/Documents/46_HARRISON_SQUARE/3dview/3D.svf"}}

![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/ca9e1067-9012-4a42-b1a6-c68c596d7d35)

and the screen shows up this:
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/78984964/2ec8fb21-8b5b-4f91-9a4f-a0d882a6204a)

**Comment by pichillilorenzo** [comment]
Have you checked that the request for the .svf file is called on the event callback `onLoadResourceWithCustomScheme`?
Are you able to get the bytes of that file? The file path is correct??

If yes, I don’t know why is not working.
Maybe something else missing to make it work, but I don’t know.
