### ISSUE TITLE
Expanded webview

### ISSUE THREAD

**Issue by M0in4** [pichillilorenzo/flutter_inappwebview#1926]
I am pushing a flutter app inside the webview but when the webview is pushed on iOS the flutter app inside the webview is not full screen. I got two option:
- I add the safearea but its not really good
- I got the bottom tab bar a lot on the bottom and the appbar is on the notch of iPhone X+

How can I fix?

**Comment by EArminjon** [comment]
Please give some screenshots, reproductible steps, version used etc.

**Comment by hugoyair** [comment]
You can use a container but you need to use a height and width to draw it. If you want to have a fullscreen size you can check about MediaQuery to get every width and height of differents kind of cellphones.

**Comment by EArminjon** [comment]
Use SafeArea() around your inAppWebView or use a scaffold.

**Comment by M0in4** [comment]
I already tried it but the problem is that I will got a blank/white space at bottom.
I don't push YouTube, I push a flutter app with a tab bar controller at bottom and I want that it display correctly without blank/white space at bottom caused by the safe area.
If you push a tab bar controller standardly inside an app, on iOS, it will adapt automatically the size (like all app on iOS) but pushing it trough the web app not

**Comment by pichillilorenzo** [comment]
Checkout the `main.dart` file of my code example here: https://github.com/pichillilorenzo/flutter_inappwebview_examples/tree/main/pwa_to_flutter_app
Maybe you can use a `Scaffold` with an `AppBar` using `toolbarHeight: 0`:
```dart
Scaffold(
    appBar: AppBar(
      // remove the toolbar
      toolbarHeight: 0,
    ),
    body: // YOUR CODE HERE
)
```

Other than that, this is not an issue of the plugin, I'm going to close it.
