### ISSUE TITLE
shouldOverrideUrlLoading not working for Flutter Web

### ISSUE THREAD

**Issue by Marvioso** [pichillilorenzo/flutter_inappwebview#1927]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.13.3        |
| Plugin version        |     ^6.0.0-rc.2          |
| Android version       |   19            |
| iOS version           |       11        |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

The shouldOverrideUrlLoading parameter does not work as expected on flutter web, but it works perfectly well on mobile. 

**Expected behavior:** 
It should be able to register a URL navigation request, and then execute my custom code in that block. This should work on flutter web just as it does in the flutter mobile apps

**Current behavior:** 
Instead, shouldOverrideUrlLoading is not triggered at all on flutter web. I know this because the very first thing that I do in that function is make a print statement. This displays in the debug console for the mobile apps, but is never printed to the chrome console when running flutter web. And yes, other print statements do work in that environment, for example, the onLoadStart function is indeed triggered on start-up. Instead of triggering the shouldOverrideUrlLoading and allowing me to run my custom code (which is an in-app navigation to another screen), it just tries to load the URL from the navigation request directly. This behaviour does not happen on mobile. This flutter web behaviours is the same on different browsers on different devices, the shouldOverrideUrlLoading is not triggered when a nav request is received.
Example:
shouldOverrideUrlLoading:
                        (controller, navigationAction) async {
                      Uri uri = navigationAction.request.url!;
                      print('Navigation Request: ${uri.toString()}');
                      // rest of code

## Steps to reproduce
Simply set up an environment where you receive a navigation request that is handled by the shouldOverrideUrlLoading, and run custom code, even something as simple as a print statement. This will work on flutter mobile apps but not on flutter web.

**Comment by pichillilorenzo** [comment]
That event is not supported on Web. Please, check the Official API Reference to see if something is supported or not on the specific platform: https://pub.dev/documentation/flutter_inappwebview/6.0.0-rc.2/flutter_inappwebview/PlatformInAppBrowserEvents/shouldOverrideUrlLoading.html
