### ISSUE TITLE
Specify declared API reasons for iOS

### ISSUE THREAD

**Issue by ueman** [pichillilorenzo/flutter_inappwebview#1929]
## Description

Apple requires developers to add a xprivacy manifest (also known as declared API reasons).
This package is listed in https://developer.apple.com/support/third-party-SDK-requirements/
See https://developer.apple.com/news/?id=z6fu1dcu for the announcement

Related Flutter issue and PR: https://github.com/flutter/flutter/issues/131494 and https://github.com/flutter/engine/pull/48951

**What you'd like to happen:** 

Add the xprivacy manifest

**Comment by michalsrutek** [comment]
Duplicate of https://github.com/pichillilorenzo/flutter_inappwebview/issues/1909

**Comment by ueman** [comment]
Thanks for pointing this out
