### ISSUE TITLE
[MACOS] launching InAppBrowser with 'hidden: true' calls onExit immediately

### ISSUE THREAD

**Issue by mlb5000** [pichillilorenzo/flutter_inappwebview#1939]
I know that on iOS/Android you can convert a `HeadlessInAppWebView` to a normal `InAppWebView` which can then be presented to the user. However, is it possible do something similar on MacOS? We need to rely on `InAppBrowser` instances on MacOS, but I'm not seeing any constructors that accept an `InAppWebView`, and the `webViewController` field on `InAppBrowser` has no setter.

Is this even technically possible (right now) given https://github.com/flutter/flutter/issues/41722 ?

**Comment by pichillilorenzo** [comment]
Currently, there is no such feature to convert a `HeadlessInAppWebView` to an `InAppBrowser` instance.
I think you can achieve the same result using `InAppBrowser` with `InAppBrowserSettings.hidden: true` and then when needed, you can call `InAppBrowser.show` method.

**Comment by mlb5000** [comment]
@pichillilorenzo So when I launch `InAppBrowser` with these settings, `onExit` is called immediately and it never does anything. Setting `hidden: false` runs as expected.

```
var settings = InAppBrowserClassSettings(
        browserSettings: InAppBrowserSettings(
            hideUrlBar: true, hideToolbarTop: true, hidden: true),
        webViewSettings: InAppWebViewSettings(
            javaScriptEnabled: true, isInspectable: kDebugMode));
```

**Comment by mlb5000** [comment]
However, if I set `hidden: false`, call `openUrlRequest`, and then immediately call `webView.hide()`, it runs in the background as expected, and I can show/hide it on demand. So there must be something with the initial request when `hidden: true` that causes it to believe the user closed the browser.
