### ISSUE TITLE
E/FrameEvents(31309): updateAcquireFence: Did not find frame.

### ISSUE THREAD

**Issue by WAUMeStore** [pichillilorenzo/flutter_inappwebview#1943]
- [x] My Flutter app show me this error 

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |  3.16.5             |
| Plugin version        |  flutter_inappwebview: ^5.8.0   |
| Android version       |  
![Screenshot 2023-12-26 040603](https://github.com/pichillilorenzo/flutter_inappwebview/assets/68748406/e59792c7-c48b-404a-bce6-533d7c125e34)

**Comment by MUmerYasin** [comment]
Upgrade Your version: https://pub.dev/packages/flutter_inappwebview
flutter_inappwebview: ^6.0.0
Migration guide, minimum required section: https://inappwebview.dev/docs/migration-guide

**Comment by xOldeVx** [comment]
@MUmerYasin same.
How can I remove these logs?
There are more some disturbing logs:
<img width="792" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/24361103/df193e6a-bdab-4e75-94c9-99d8c028dc9c">

Both logs are `false` in the code, and still not disabled:
      `InAppWebViewController.setWebContentsDebuggingEnabled(false);`
      `PlatformInAppWebViewController.debugLoggingSettings.enabled = false;`

**Comment by pichillilorenzo** [comment]
These are internal Android logs or Flutter internal logs.
Not related to this plugin.

**Comment by xOldeVx** [comment]
Of course, but the package is the bridge of this at end, these logs are really shocking and sometimes I have no choice but i'm using `useHybridComposition`(!) to avoid them.
Is there a way to solve this?

**Comment by pichillilorenzo** [comment]
This is not something that the plugin should manage.
Also, the plugin can’t turn off internal Flutter logs or internal Android logs.
Probably, you could filter the logs by setting the right configuration of your IDE, check:
- https://developer.android.com/studio/debug/logcat?hl=en
- https://stackoverflow.com/questions/57544372/how-to-filter-logging-of-flutter-app-in-intellij-console

Or just search on the Internet about it.

**Comment by pichillilorenzo** [comment]
Also, you shouldn’t use `useHybridComposition` because of that.
It’s a specific setting that has its purpose and meaning.
