### ISSUE TITLE
Sign in with Google NOT Working

### ISSUE THREAD

**Issue by WAUMeStore** [pichillilorenzo/flutter_inappwebview#1944]
- [x] Error 400: redirect_uri_mismatch
- [x] Access block: This App's request is invalid

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |Channel stable, 3.16.5 |
| Plugin version        | flutter_inappwebview: ^6.0.0, url_launcher: ^6.2.2 |
| Android version       |Android SDK version 34. |

  
  
  
## Images 
![Screenshot 2023-12-26 040603](https://github.com/pichillilorenzo/flutter_inappwebview/assets/68748406/3e9c4ee2-6b60-4dd2-8be7-e9030adb8188)

**Comment by WAUMeStore** [comment]
<img width="893" alt="Screenshot 2023-12-26 040603" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/68748406/8fe148bc-c078-480e-89b9-9d9fb0fccf64">
<img width="895" alt="2" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/68748406/05c7c635-c7d0-47ba-a2e2-31ed57bb6dde">

Sign in with Google NOT Working in App, but if we open in Google Chrome its work

**Comment by pichillilorenzo** [comment]
Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/1112
