### ISSUE TITLE
Why inappwebview does not support desktop

### ISSUE THREAD

**Issue by Crush-star** [pichillilorenzo/flutter_inappwebview#1945]
I noticed that the existing webview packages can only be used as widgets on mobile phones, and can only be used as new windows on the desktop. Why can't they be used as widgets on the desktop? Is it because Flutter itself does not support it?

**Comment by pichillilorenzo** [comment]
Exactly, the Flutter team is working on it. Maybe we will have that with Flutter 4 🤷🏻‍♂️

**Comment by Crush-star** [comment]
> Exactly, the Flutter team is working on it. Maybe we will have that with Flutter 4 🤷🏻‍♂️

Thank you. I don't know much about ios development. I want to ask a question. Can this effect be achieved by embedding web pages through WKWebView in macos?

**Comment by pichillilorenzo** [comment]
InAppBrowser and HeadlessInAppWebView are already implemented on macOS, check the API Reference to see what is supported on macOS
