### ISSUE TITLE
A problem occurred to updrage flutter_inappwebview_android v5.8 to 6.0.0

### ISSUE THREAD

**Issue by WAUMeStore** [pichillilorenzo/flutter_inappwebview#1946]
- [x] A problem occurred configuring project ':flutter_inappwebview_android'.
- [x] Could not open cp_proj generic class cache for build file 'C:\Users\LENOVO\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_inappwebview_android-1.0.12\android\build.gradle' (C:\Users\LENOVO\.gradle\caches\7.5\scripts\46aylth0xhcjkg2x1sml5eomu).
   > Unexpected lock protocol found in lock file. Expected 3, found 0.

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |               |
| Plugin version        |               |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_inappwebview_android'.
> Could not open cp_proj generic class cache for build file 'C:\Users\LENOVO\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_inappwebview_android-1.0.12\android\build.gradle' (C:\Users\LENOVO\.gradle\caches\7.5\scripts\46aylth0xhcjkg2x1sml5eomu).
   > Unexpected lock protocol found in lock file. Expected 3, found 0.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_inappwebview_android' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_inappwebview_android' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1

## Images 
<img width="847" alt="Screenshot 2023-12-26 040603" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/68748406/f943af0e-74eb-4b10-9d3b-61495dba20b8">

**Comment by pichillilorenzo** [comment]
I don’t know what is it but maybe you have some problem on your computer.
I suggest to clean your dependencies and try again.

**Comment by MUmerYasin** [comment]
Step one: Use version = 7.3.0 (only use Android Gradle)

Second Step: Go to File > `android/app/build.gradle`   change  `compileSdkVersion 34`
Problem Solve

**Comment by pichillilorenzo** [comment]
Exactly, it's already written in the migration guide, minimum required section: https://inappwebview.dev/docs/migration-guide
