### ISSUE TITLE
After input gets the focus, the done button appears on the soft keyboard of ios

### ISSUE THREAD

**Issue by Lauweal** [pichillilorenzo/flutter_inappwebview#1948]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |     3.16.4       |
| Plugin version        |    6.0.0           |
| Android version       |               |
| iOS version           |       16.4        |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 
![WechatIMG56](https://github.com/pichillilorenzo/flutter_inappwebview/assets/54409768/b2e6f408-7488-45a0-8903-51809aac7e93)

**Current behavior:** 
<img width="471" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/54409768/c9667f8b-bccd-4c81-9e8b-16e096900908">

## Steps to reproduce

Normally, the done button and gray module should not appear on the soft keyboard after getting focus
1.Click input to make the keyboard pop up

**Comment by pichillilorenzo** [comment]
That’s something related on your iOS Simulator settings.
It’s not related to the WebView, can change it to show the full keyboard.
