### ISSUE TITLE
On macOS 13.4 , it return a error  " createPlatformInAppWebViewWidget is not implemented on the current platform "

### ISSUE THREAD

**Issue by combing520** [pichillilorenzo/flutter_inappwebview#1955]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |        3.13.3       |
| Plugin version        |           flutter_inappwebview: ^6.0.0    |
| Android version       |        Android SDK version 33.0.0       |
| iOS version           |            iOS 16.4   |
| macOS version         |       macOS 13.4        |
| Xcode version         |          Xcode 14.3.1     |
| Google Chrome version |          120.0.6099.129     |

Device information: 

## Description
When I use   flutter_inappwebview: ^6.0.0    and run on  Android ,iOS ,web and  macOs Platform , i got a erro like this when it run on macos platform
**" createPlatformInAppWebViewWidget is not implemented on the current platform.",** ,
but it run ok  on  Android ,iOS ,web ;

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This

 double _webHeight = 500;
 InAppWebViewController? webViewController;

  InAppWebViewSettings settings = InAppWebViewSettings(
      isInspectable: kDebugMode,
      allowsInlineMediaPlayback: true,
      allowFileAccessFromFileURLs: false,
      allowUniversalAccessFromFileURLs: false,
      allowFileAccess: false,
      allowContentAccess: false,
      javaScriptEnabled: true,
      iframeAllowFullscreen: true);

SizedBox(
          height: _webHeight,
          child: InAppWebView(
              initialData: InAppWebViewInitialData(data: webContent),
              initialSettings: settings,
              onWebViewCreated: (InAppWebViewController controller) async {
                webViewController = controller;
              },

2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
The message is already saying the reason, it is not currently supported.
Follow https://github.com/pichillilorenzo/flutter_inappwebview/issues/460 for desktop support.
