### ISSUE TITLE
InAppWebView startup time 

### ISSUE THREAD

**Issue by ylaptiev-sommo** [pichillilorenzo/flutter_inappwebview#1956]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |  3.10.3             |
| Plugin version        |   ^6.0.0-beta.31            |
| Android version       |        14       |
| iOS version           |        17.2      |

Device information: 

Google Pixel 7 Pro (Android 14)
Apple iPhone SE 2022 (iOS 17.2)

## Description
In my application WebView located almost in the root of a tree: MaterialApp -> MyRootWidget.
InAppWebView returning in the build method of MyRootWidget.
It takes up to 3.5 seconds from onWebviewCreated callback to onLoadStart.

## Steps to reproduce
To measure it, use Timeline class (built in dart:developer).
Place Timeline.startSync('put timeline name to find it in devtools') in the onWebviewCreated callback.
Place Timeline.finishSync() in the onLoadStart callback.
Run app in profile mode on real device and use DevTools to see timeline results

**Comment by pichillilorenzo** [comment]
WebView needs to create something complicated, it is not a simple widget, it has its own rendering engine for web contents, etc…
That could depends on a lot of things, such as the device itself.
You can hide the widget with a loader in front and then show it when your WebView is ready to be used, or you can create an headless WebView at startup and then convert it to a InAppWebView widget: https://inappwebview.dev/docs/webview/headless-in-app-webview#convert-to-an-inappwebview-widget
