### ISSUE TITLE
addJavaScriptHandler is not supported in web

### ISSUE THREAD

**Issue by wolru** [pichillilorenzo/flutter_inappwebview#1958]
## Environment

**Flutter version: 3.16.5
**Plugin version:**  6.0.0
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

I was using the addJavaScriptHandler function on mobile, but when I ran it on the web, it said the function was not supported.
I think I understand why support is not available, but how should I handle this case?

```
onWebViewCreated: (InAppWebViewController controller) async {
            controller.addJavaScriptHandler(
              handlerName: 'onWebViewReady',
              callback: (dynamic) {
                widget.onWebViewReady?.call(controller);
              },
            );
          },
```

**Comment by pichillilorenzo** [comment]
It’s simply not supported, iframes on Web are very limited.

**Comment by MichaelSSY** [comment]
> ## 环境
> **Flutter版本：3.16.5 **插件版本：** 6.0.0 **Android版本：** **iOS版本：** **Xcode版本：** **设备信息：**
> 
> ## 描述
> 我在移动设备上使用 addJavaScriptHandler 函数，但在 Web 上运行它时，它说不支持该函数。 我想我明白了为什么不支持，但我该如何处理这种情况？
> 
> ```
> onWebViewCreated: (InAppWebViewController controller) async {
>             controller.addJavaScriptHandler(
>               handlerName: 'onWebViewReady',
>               callback: (dynamic) {
>                 widget.onWebViewReady?.call(controller);
>               },
>             );
>           },
> ```

May I ask how you write the code on the JS side?

**Comment by MichaelSSY** [comment]
> ## 环境
> **Flutter版本：3.16.5 **插件版本：** 6.0.0 **Android版本：** **iOS版本：** **Xcode版本：** **设备信息：**
> 
> ## 描述
> 我在移动设备上使用 addJavaScriptHandler 函数，但在 Web 上运行它时，它说不支持该函数。 我想我明白了为什么不支持，但我该如何处理这种情况？
> 
> ```
> onWebViewCreated: (InAppWebViewController controller) async {
>             controller.addJavaScriptHandler(
>               handlerName: 'onWebViewReady',
>               callback: (dynamic) {
>                 widget.onWebViewReady?.call(controller);
>               },
>             );
>           },
> ```

May I ask how you write the code on the JS side? @wolru
