### ISSUE TITLE
Alerts and Snackbars in Web project do not allow clicks when opened over an InAppWebview

### ISSUE THREAD

**Issue by ReallySmallSoftware** [pichillilorenzo/flutter_inappwebview#1960]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |   3.16.2            |
| Plugin version        |    6.0.0           |
| Android version       |   n/a            |
| iOS version           |     n/a          |
| macOS version         |    n/a           |
| Xcode version         |       n/a        |
| Google Chrome version |   120.0.6099.109            |

Device information: Ubuntu 22.04.1

## Description

Using the InAppWebview in a web project is causing overlaid widgets to not be interacted with.

**Expected behavior:** 
Using an InAppWebview on a page which subsequently displays a Snackbar or Alert allows the user to interact with the Snackbar or Alert.

**Current behavior:** 
Using an InAppWebview on a page which subsequently displays a Snackbar or Alert passes any click events to the underlying webview making it impossible to interact with the Snackbar or Alert.

## Steps to reproduce

```
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

class FAQPage extends StatelessWidget {
  const FAQPage({super.key});

  @override
  Widget build(BuildContext context) {
    Future.delayed(Duration.zero, () => showAlert(context));

    var child = InAppWebView(
      initialUrlRequest:
          URLRequest(url: WebUri.uri(Uri.parse('https://example.com'))),
      initialSettings: InAppWebViewSettings(
        useHybridComposition: true,
        javaScriptEnabled: true,
        iframeSandbox: <Sandbox>{}..add(Sandbox.ALLOW_SCRIPTS),
      ),
    );

    return Scaffold(body: child);
  }

  void showAlert(BuildContext context) {
    showDialog(
        context: context,
        builder: (context) => AlertDialog(
              title: const Text('AlertDialog Title'),
              content: const SingleChildScrollView(
                child: ListBody(
                  children: <Widget>[
                    Text('This is a demo alert dialog.'),
                    Text('Would you like to approve of this message?'),
                  ],
                ),
              ),
              actions: <Widget>[
                TextButton(
                  child: const Text('Approve'),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                ),
              ],
            ));
  }
}
```

**Comment by pichillilorenzo** [comment]
This is a problem of `HtmlElementView` flutter class.
You should use `pointer_interceptor` plugin to make it work on web, check the official doc “Setup Web”: https://inappwebview.dev/docs/intro#setup-web

**Comment by ReallySmallSoftware** [comment]
Thank you. I really did search but obviously not well enough! I appreciate the quick response.
