### ISSUE TITLE
initialUserScripts doesn't work for HeadlessInAppWebView

### ISSUE THREAD

**Issue by fyxtc** [pichillilorenzo/flutter_inappwebview#1963]
```
    final headlessWebView = HeadlessInAppWebView(
      initialUserScripts: UnmodifiableListView<UserScript>([
        UserScript(
            source: "var test1 = 123", injectionTime: UserScriptInjectionTime.AT_DOCUMENT_START),
      ]),
    );
    await headlessWebView.run();
    final controller = headlessWebView.webViewController!;
    final data = await controller.evaluateJavascript(source: "test1");

```
data is null on iOS

**Comment by pichillilorenzo** [comment]
Well, you should load a URL for that.
Your current WebView status is not either a blank page.
For example, you can load url `about:blank` and on onLoadStop you can evaluate your JavaScript code.
If you need the result outside the event callback, just create a Future Completer and `complete` it when the `onLoadStop` event is called.
`await` the complete after the `HeadlessInAppWebView.run` method and, after that you can call the evaluate JavaScript method.
