### ISSUE TITLE
Does InAppLocalhostServer support read content from document directory?

### ISSUE THREAD

**Issue by extrame** [pichillilorenzo/flutter_inappwebview#1965]
I got a [discussion ](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1921)of using docuement directory in InAppWebView.

And I have samilar problem  in InAppLocalhostServer.

So I wonder if i can set CustomPathHandler for InAppLocalhostServer

**Comment by pichillilorenzo** [comment]
Nope, if you want to have that, you can create your own custom localhost server.
If you want, you can copy and modify the implementation of the current InAppLocalhostServer and make changes to whatever you want.
Path Handlers is a feature specific to native Android WebViews and not servers.
