### ISSUE TITLE
onConsoleMessage() is not getting called on WEB Platform

### ISSUE THREAD

**Issue by rahul-dezerv** [pichillilorenzo/flutter_inappwebview#1966]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |        3.13.9      |
| Plugin version        |      ^6.0.0        |
| Android version       |        -       |
| iOS version           |           -    |
| macOS version         |       -       |
| Xcode version         |          -    |
| Google Chrome version |    120.0.6099.199 (Official Build) (arm64)           |

Device information:  MacBook Pro M2

## Description

**Expected behavior:** 
"onConsoleMessage()" should get called when messages are logged on the console, It works perfectly on Android/iOS.

**Current behavior:** 
"onConsoleMessage()" is not getting called on **Flutter Web Platform**, it's getting automatically logged on the Flutter Debug console(VSCode's console) somehow, but not from the logger which I added in onConsoleMessage().

## Steps to reproduce

```dart
  Widget _buildWebView() {
    return InAppWebView(
      // initialUrlRequest: URLRequest(url: WebUri(widget.url)),
      initialData: InAppWebViewInitialData(data: _getWebPageData()),
      onConsoleMessage: (_, ConsoleMessage consoleMessage) {
        log("onConsoleMessage", error: consoleMessage.message);      },
    );
  }

// Optional, can use initialUrlRequest too
  String _getWebPageData() {
    return """
            <!DOCTYPE html>
            <html>
            <body style="width: 100vw; height: 100vh; margin: 0">
              <script>
                console.log("From Web");
              </script>
            </body>
            </html>
""";
  }

```

## Images   
<img width="773" alt="image" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/117640471/f0729757-edc6-45d0-a05e-2455c917172c">

**Comment by pranayk533** [comment]
Any update on this issue? I am facing the same problem.

**Comment by pichillilorenzo** [comment]
As you can see from the API Reference https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/PlatformInAppBrowserEvents/onConsoleMessage.html, it is not supported on Web.
Web platform has a lot of limitations because of its nature (iframe HTML element)
