### ISSUE TITLE
where l use keep alive， how can l dispose  some one

### ISSUE THREAD

**Issue by YYL1999** [pichillilorenzo/flutter_inappwebview#1969]
```
InAppWebView(
    keepAlive: keepAlive,
    initialUrlRequest: URLRequest(url: WebUri(widget.url)),
    initialSettings: options,
    onWebViewCreated: (InAppWebViewController controller) {
      _webViewController = controller;
    },
)
```
example, l have two webview, url A and B, both use keepalive , l want to dispose url A webview, what should l do?

**Comment by pichillilorenzo** [comment]
To dispose a keep alive WebView, use `InAppWebViewController.disposeKeepAlive` static method: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebViewController/disposeKeepAlive.html

**Comment by YYL1999** [comment]
![image](https://github.com/pichillilorenzo/flutter_inappwebview/assets/39796460/8ded5801-3342-48a9-9201-6294da172322)
docs is not show

**Comment by pichillilorenzo** [comment]
Yep, probably I forgot to add it in the docs, sorry! I will add it as soon as possible! 👍

**Comment by YYL1999** [comment]
bro, you are really awesome
