### ISSUE TITLE
Camera returns null image path on the Android device

### ISSUE THREAD

**Issue by amanzimble** [pichillilorenzo/flutter_inappwebview#1971]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.16.3        |
| Plugin version        |         6.0.0      |
| Android version       |        13       |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: Samsung Galaxy A22

## Description
My app is using the flutter_inappwebview plugin to open the url in the InAppWebview widget. The url loads the page which is developed in the Python. Webpage uses the ”Django-image-uploader-widget” to capture the image or pick image from the gallery of the both Android & iOS devices. Everything working fine in the iOS. But in the Android device, after capturing the image, local image path is returned as null.

**Expected behavior:** 
On Android device, when the "Django-image-uploader-widget" opens the camera and captures the image, then app should receive an image path to show the image on the webpage.
**Current behavior:** 
On the Android device, when the "Django-image-uploader-widget" opens the camera and captures the image, local image path is returned as null. However gallery option is working fine.
## Steps to reproduce

1. Open the url in the InAppWebView widget.
2. After the page loads, tap on the image uploader view, select the camera.
3. Capture the image.
4. Image does show up on the webpage inside the inappwebview. Image path returned as null. 

## Images
Added Permissions in the Android Manifest file
<img width="916" alt="Screenshot 2024-01-11 at 7 19 33 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/47678316/34459d44-4600-4928-af43-b6e8ff38d712">

Added provider tag with the meta-data in the Android Manifest file.
<img width="934" alt="Screenshot 2024-01-11 at 7 20 54 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/47678316/aa3e505a-1b96-4d39-ae0e-72e5a8dabd98">

Added provider path in the xml
<img width="662" alt="Screenshot 2024-01-11 at 7 25 05 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/47678316/540d4b63-e10a-4e84-8fdd-5b523f5b8d82">

added the logs to check the path of the returned image
<img width="931" alt="Screenshot 2024-01-11 at 7 21 36 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/47678316/29bc6a9f-f6c9-47bf-8cb9-bc27da890dab">

This is how my Inappwebview widget looks like
<img width="696" alt="Screenshot 2024-01-11 at 7 23 07 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/47678316/5d071ba6-76cf-4245-9c99-a1a2ccc6c9fb">

## Stacktrace/Logcat 

Case: When selecting image from gallery/files
Android onActivityResult: image path: content://media/picker/0/com.android.providers.media.photopicker/media/1000001581

Case: When capturing image from camera
Android onActivityResult: image path: null

**Comment by pichillilorenzo** [comment]
Your `provider` seems not correct, the `android:authorities` value should be as follow:
```xml
<provider
    android:name="com.pichillilorenzo.flutter_inappwebview_android.InAppWebViewFileProvider"
    android:authorities="${applicationId}.flutter_inappwebview_android.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />
</provider>
```
