### ISSUE TITLE
A problem occurred configuring project ':flutter_inappwebview'.

### ISSUE THREAD

**Issue by 1Mahmoud12** [pichillilorenzo/flutter_inappwebview#1975]
classpath 'com.android.tools.build:gradle:8.1.4'
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip
## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |     3.16.5          |
| Plugin version        |        5.8.0       |

**Comment by 1Mahmoud12** [comment]
> ```
* What went wrong:
A problem occurred configuring project ':flutter_inappwebview'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

>    
> ```
>  classpath 'com.android.tools.build:gradle:8.1.4'
> distributionUrl=https://services.gradle.org/distributions/gradle-8.0-all.zip
> 
> ## Environment
> Technology	Version
> Flutter version	3.16.5
> Plugin version	5.8.0

**Comment by pichillilorenzo** [comment]
You need to use new version 6.
