### ISSUE TITLE
pdf issue

### ISSUE THREAD

**Issue by prashant9251** [pichillilorenzo/flutter_inappwebview#1976]
- [Y] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [Y] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
[✓] Flutter (Channel stable, 3.16.6, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.85.1)
[✓] Network resources

Device information: same result in all device

**Expected behavior:
this method i was manual created in plugin   flutter_inappwebview: ^5.7.2+3
this method is for created webview  pdf save in application document directory   and its working perfectly for me approx 2 years 

but after flutter upgrade and plugin update to flutter_inappwebview: ^6.0.0. this 
** 

**Current behavior:

this function behavior. not working properly

its creating pdf but 3 pdf creating out of 10 attempt 
means if i click on creating pdf button 10 time then  but  its create only 3 time ** 

## 
  //------newMethod. this method i was create in InAppWebView.java 
  @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
  public void printCurrentPageDirectShare(final String mobile, final String email, final String sendType,List<String> extraFileListForShare) {
    if (plugin != null && plugin.activity != null) {
      PrintManager printManager = (PrintManager) plugin.activity.getSystemService(Context.PRINT_SERVICE);

      if (printManager != null) {
        String jobName = getTitle() + " Document";

        // Get a printCurrentPage adapter instance
        PrintDocumentAdapter printAdapter = createPrintDocumentAdapter(jobName);

        final ProgressDialog progress = new ProgressDialog(getContext());
        progress.setTitle("Please wait");
        progress.setMessage("creating pdf");
        progress.setCancelable(true); // disable dismiss by tapping outside of the dialog
        progress.show();
        PrintAttributes attributes = null;
        if (Build.VERSION.SDK_INT >= 19) {
          attributes = (new PrintAttributes.Builder()).setMediaSize(PrintAttributes.MediaSize.ISO_A4).setResolution(new PrintAttributes.Resolution("pdf", "pdf", 600, 600)).setMinMargins(PrintAttributes.Margins.NO_MARGINS).build();
        }
        PdfPrint pdfPrint = new PdfPrint(attributes);
        if (Build.VERSION.SDK_INT >= 21) {
          ContextWrapper contextWrapper = new ContextWrapper(getContext());
          File directory = getContext().getFilesDir();//get dir
          String name=getTitle();//get name
          SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yy HH:mm", Locale.getDefault());
          String formattedDateTime = sdf.format(currentDate);
          name=name.replaceAll("[;\\/:*?\"<>|&']"," ");
          name +=" (PDF GENERATED ON "+formattedDateTime+") ";
          final String fileName = name + ".pdf";
          final File f = new File(directory, fileName);
          if (f.exists()) {
            f.delete();
            Log.d("---del_Directory", String.valueOf(f));
          }
          try {
            f.createNewFile();
          } catch (IOException e) {
            e.printStackTrace();
          }
          Log.e(LOG_TAG, "startPrinting save");

          pdfPrint.print(printAdapter, directory, fileName, new PdfPrint.CallbackPrint() {
            public void success(String path) {
              Log.d("---new_file_path", path);
              progress.dismiss();
              File f=new File(path);
             // this f file we want to return in flutter so user can share this webview pdf
            }
            public void onFailure() {
              progress.dismiss();
            }
          });
        }
        Log.e(LOG_TAG, "direct share PrintManager available ------------------print screen here prashant");//------------------print screen here prashant
      } else {
        Log.e(LOG_TAG, "No PrintManager available");
      }
    }
  }

///-----this method for webview pdf save to files

package android.print;

import android.os.Build;
import android.os.CancellationSignal;
import android.os.ParcelFileDescriptor;
import android.print.PrintDocumentAdapter.WriteResultCallback;
import android.util.Log;

import java.io.File;

public class PdfPrint {
    private static final String TAG = PdfPrint.class.getSimpleName();
    public final PrintAttributes printAttributes;

    public PdfPrint(PrintAttributes printAttributes) {
        this.printAttributes = printAttributes;
    }

    public void print(final PrintDocumentAdapter printAdapter, final File path, final String fileName, final CallbackPrint callback) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            printAdapter.onLayout(null, printAttributes, null, new PrintDocumentAdapter.LayoutResultCallback() {
                @Override
                public void onLayoutFinished(PrintDocumentInfo info, boolean changed) {
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                        printAdapter.onWrite(new PageRange[]{PageRange.ALL_PAGES},
                                getOutputFile(path, fileName),
                                new CancellationSignal(),
                                new WriteResultCallback() {
                                    @Override
                                    public void onWriteFinished(PageRange[] pages) {
                                        super.onWriteFinished(pages);
                                        if (pages.length>0){
                                            File file = new File(path, fileName);
                                            String path=file.getAbsolutePath();
                                            callback.success(path);
                                        }else {
                                            callback.onFailure();
                                        }

                                    }
                                });
                    }
                }
            }, null);
        }
    }

    public ParcelFileDescriptor getOutputFile(File path, String fileName) {
        if (!path.exists()) {
            path.mkdirs();
        }
        File file = new File(path, fileName);
        try {
            file.createNewFile();
            return ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_WRITE);
        } catch (Exception e) {
            Log.e(TAG, "Failed to open ParcelFileDescriptor", e);
        }
        return null;
    }

    public interface CallbackPrint{
        void success(String path);
        void onFailure();
    }

}
//-------

## Images <iframe src="https://firebasestorage.googleapis.com/v0/b/autobackupdatabase-90253.appspot.com/o/WhatsApp%20Image%202024-01-15%20at%2009.13.39%20(1).jpeg?alt=media&token=b56dc338-40ba-4fe2-942e-4cc76d6f3bd8" height="100%" width="100%">
</iframe>

**Comment by prashant9251** [comment]
yes

**Comment by pichillilorenzo** [comment]
Why would you use something like that?
You should not change the Java API.

Probably, you can already do that using simply Dart on Flutter side.
To set pdf print properties, you can use the `PrintJobSettings` parameter of the `InAppWebViewController.printCurrentPage` method: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/PlatformInAppWebViewController/printCurrentPage.html

Currently, changing the underlying native platform code could break something, so you should not do that.
If you are using a modified version of the plugin, then this is something up to you and not an issue with the official plugin.

If you want to add some new behaviour, create a pull request for the specific platform.

**Comment by prashant9251** [comment]
InAppWebViewController.printCurrentPage.   this is just open print as pdf screen -> save pdf -> then search this pdf file in file manager- then share its is too long process to share pdf of webview

but if this method can save direct to files or return Uint8List. or bytes xyz then  its easy to use and understandable i think

**Comment by pichillilorenzo** [comment]
Currently no, this method is not able to get the bytes of the pdf.
There isn’t an API to get the PDF bytes such as we have on iOS WKWebView.
If you think this could be made using workarounds on Android, then you can try to make a pull request about it.
On iOS and macOS with have this: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/PlatformInAppWebViewController/createPdf.html

**Comment by prashant9251** [comment]
i think. requested  you need to use this  implementation 'com.github.pramodkr123:ConvertWebViewToPdfDemo:1.0.4'. for android this is best way to convert Webview to pdf and save to directory  directly just pass- directory path, filename & webview its convert Webview to pdf smoothly  .
just like InAppWebViewController.printCurrentPage. for android.  i think you must try this 


this lib. i was using in native android  above 5 year but now i am transfer in flutter.
most of things are full filled by your plugin  only for android. you try this and i guaranteed. this is best way .
please you must try please please please 

we just need you provide this feature in build in your flutter inAppWebview plugin 

for more details https://github.com/pramodkr123/ConvertWebViewToPdfDemo

**Comment by prashant9251** [comment]
please check  file InAppWebView.java
function name :  printCurrentPageDirectShare

 flutter_inappwebview-5.7.2+3.zip
<https://drive.google.com/file/d/1hbxSxaeKk_grOuDcWiezKahQi2gtT78O/view?usp=drive_web>

**Comment by prashant9251** [comment]
in  (flutter_inappwebview: ^5.7.2+3) i was created
printCurrentPageDirectShare. method natively please check one time only

**Comment by prashant9251** [comment]
Why you are going to onDownloadStart.
there is no need to go onDownloadStart.

'com.github.pramodkr123:ConvertWebViewToPdfDemo:1.0.4'.   this
implementation. is use for what your webview screen loaded from web
url this implementation.  is just convert html css content to pdf
file.

this 'com.github.pramodkr123:ConvertWebViewToPdfDemo:1.0.4'. lib not
use for  download any file. its convert webview to pdf file just like
you calling Ios pdf  system InAppWbviewCOntroller.createPdf() function
.

just for example.
step
 1. We always first load any url in webview
 2. then if we call this function from android side
            File directory =
Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM
+ "/PDFTest/");
            final String fileName="Test.pdf";

            final ProgressDialog progressDialog=new
ProgressDialog(MainActivity.this);
            progressDialog.setMessage("Please wait");
            progressDialog.show();
            PdfView.createWebPrintJob(MainActivity.this, webView,
directory, fileName, new PdfView.Callback() {

                @Override
                public void success(String path) {
                    progressDialog.dismiss();

PdfView.openPdfFile(MainActivity.this,getString(R.string.app_name),"Do
you want to open the pdf file?"+fileName,path);
                }

                @Override
                public void failure() {
                    progressDialog.dismiss();

                }
            });
3.  now we can share this file or convert in bytes xyz.

this is just for example what we need and what we want to do.

if you go deep in this
com.github.pramodkr123:ConvertWebViewToPdfDemo:1.0.4 code there is
just simple android print code

kindly requested
for this function InAppWbviewCOntroller.createPdf() your android side
code is pending in your flutter_inappwebview. flutter plugin .
I think it will take its place of android side.

again kindly requested please please please




this is for what you load content on Webview( like webpage html,css )
 this api just convert webview page to pdf file

if you agree then can i share my flutter code that what i was changes
done in your plugin (flutter_inappwebview: ^5.7.2+3) natively for
android and its work perfectly nice and so fast quickly


please check  file InAppWebView.java file in android  
function name :  printCurrentPageDirectShare. i made this function and its working perfectly above 1 years 

[flutter_inappwebview-5.7.2+3.zip](https://github.com/pichillilorenzo/flutter_inappwebview/files/13989338/flutter_inappwebview-5.7.2%2B3.zip)
