### ISSUE TITLE
Communication between webview and flutter

### ISSUE THREAD

**Issue by M0in4** [pichillilorenzo/flutter_inappwebview#1979]
Hi guys,
I got a flutter app and I need to transform it to a PWA.
I am opening the Flutter app trough the webview but I got few function that need to communicate with flutter to open phone calendar for example.
I need to click a button inside the webview that fire me a listener or something like that inside the flutter code (outside of webview)
Is it possible?

**Comment by pichillilorenzo** [comment]
Yes, there is already an example of a PWA:
- code: https://github.com/pichillilorenzo/flutter_inappwebview_examples/tree/main/pwa_to_flutter_app
- article: https://medium.com/better-programming/convert-a-pwa-into-a-flutter-app-using-webviews-387060548a37

Check https://inappwebview.dev/docs/webview/javascript/communication for more info about javascript communication

**Comment by M0in4** [comment]
Ok but you're firing for example the buttoj 'Request dummy notification' from HTML.
I don't got nothing on HTML.
I need to show full flutter app inside a webview and click a button inside the webview that is showing the flutter app and fire the main code to show notification for example.
Is it possible? On docs I didn't found that

**Comment by pichillilorenzo** [comment]
What do you mean by “Flutter App inside a WebView”? Maybe you mean the other way around, that is a WebView inside your Flutter App?

On what platform are you talking about? Web platform? If you mean that, Web platform is implemented using IFrame HTML elements, that are very limited, so in that case you probably can’t do much about it.

Instead, if you are talking about Android or iOS, then you can communicate with the web contenta of the WebView using JavaScript using what you can find on the official docs.
Flutter to WebView and WebView to Flutter, for example using JavaScript handlers, as you can see in the example code or in the docs.

**Comment by M0in4** [comment]
I mean that I have to show a flutter app trough the web view because I need to upload it on the store.

Flutter app A need to show Flutter app B trough web view and I need to communicate from webview trough Flutter A (to show notification/calendar popup or other functions)

**Comment by pichillilorenzo** [comment]
Then, if you are able to access JavaScript objects and method on the Web App, yes you can do that.
The docs speaks about JavaScript, but I think you do the same as Dart should have access to the JavaScript (DOM) API.
Use the official dart html library to access the same objects you would do in JavaScript code, such the window object: https://api.dart.dev/stable/3.2.4/dart-html/Window-class.html

**Comment by M0in4** [comment]
Any hint how to do that?
