### ISSUE TITLE
Can I get resource from cache?

### ISSUE THREAD

**Issue by fyxtc** [pichillilorenzo/flutter_inappwebview#1982]
Such as: a.js, a.jpg

**Comment by pichillilorenzo** [comment]
No, there isn’t any official native API to allow that.
Probably, one thing that you could try, at least for Android, is to implement the `shouldInterceptRequest`:  https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/PlatformWebViewCreationParams/shouldInterceptRequest.html
and implement your own custom logic for each request: make the request, save the resource somewhere you have access and return it to the WebView.
