### ISSUE TITLE
navigator.share

### ISSUE THREAD

**Issue by hpodong** [pichillilorenzo/flutter_inappwebview#1985]
i have error in Android "navigator.share is not a function" 
in iOS this function work only android error

**Comment by pichillilorenzo** [comment]
As you can see from this table https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility, it is not supported natively on Android WebView.
So, you would create your own implementation using JavaScript communication and handle the share logic on Flutter side.
