### ISSUE TITLE
App crashes silently when screenshot is taken

### ISSUE THREAD

**Issue by jakubgros** [pichillilorenzo/flutter_inappwebview#199]
## Environment

**App version:**  1.2.2
**Android version:**  Android 9.0 API 28
**Device information:**  Pixel 3 XL  

## Description
when webpage https://haikusushi.pl/products.html is loaded and I want to take screenshot of it, app crashes without any information

## Steps to reproduce
1. Open https://haikusushi.pl/products.html using  InAppWebView by passing the url as initialUrl 
2. Take screenshot using controller

**Comment by jakubgros** [comment]
I get the same error on:

Pixel 3 XL API 28 - Adroid 9.0 x86 
Pixel 3 XL API 29 - Adroid 10.0 x86 

The problem doesn't appear on
Pixel 3 XL API 25 - Adroid 7.1.1 x86

**Comment by jakubgros** [comment]
The same problem appears on:

https://www.pyszne.pl/tandoori-flame#kategoria_Najpopularniejsze_dania

However everything is fine for:

http://www.restauracjawarsztat.pl/pl/ul.-miodowa-20/menu-miodowa.html

**Comment by pichillilorenzo** [comment]
Try the latest version of the plugin **2.0.0** and let me know. Thanks

**Comment by pichillilorenzo** [comment]
Can you share also the code that you are using, please? I have tested your URL and I can take screenshots.

**Comment by jakubgros** [comment]
Thank you for your response. I will check it in next week and if it doesn't work with the newest version I will share the code with you.
