### ISSUE TITLE
Web Does Not Compile

### ISSUE THREAD

**Issue by a-wallen** [pichillilorenzo/flutter_inappwebview#1992]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.10.1        |
| Plugin version        |       1.0.8        |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |        ??       |

Device information: 

## Description

**Expected behavior:** 
`flutter run -d chrome` on a new project after adding flutter_inappwebview should work.

**Current behavior:** 

```
The getter 'platformViewRegistry' isn't defined for the class
'InAppWebViewFlutterPlugin'
```

**Comment by QoLTech** [comment]
Did you do https://inappwebview.dev/docs/intro/#setup-web?

**Comment by a-wallen** [comment]
Yeah - this isn't an issue for me anymore though. I'm just going to work off of `flutter master`
