### ISSUE TITLE
Can't access a httpOnly Cookies using the CookieManager

### ISSUE THREAD

**Issue by escamoteur** [pichillilorenzo/flutter_inappwebview#1995]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |    3.16.5           |
| Plugin version        |   6.0.0            |
| Android version       |     14          |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: Pixel 7

## Description

We have to handle Cloud Flare User Challenges that need to be shown in a WebView (in this case I used the `WCInAppBrowser` which works fine so far. unfortuantely the way the Cloudflare challenge works is that is stores a HttpOnly cookie on success which I need so that I can pass it with my API requests after the challenge suceeded.

I tried to list the existing cookies but the one from cloudflare that I can see in our webapp is not returned when I try:
```dart
            await browser.openData(
              data: response.body,
              settings: InAppBrowserClassSettings(
                webViewSettings: InAppWebViewSettings(
                  javaScriptEnabled: true,
                ),
              ),
              baseUrl: webUri,
            );
            await browser.exitCompleter.future;

            final cookies = await CookieManager.instance().getCookies(
                url: WebUri('https://mysite.com/'),
                webViewController: browser.webViewController);
 ```

Other cookies are sucessfully returned

Is there another way to intercept when the page creates the cookie?

**Comment by escamoteur** [comment]
Yep, I think I have tried almost everything and also did a lot of research

**Comment by pichillilorenzo** [comment]
Maybe the cookie is using another domain.
Open the WebView chrome inspector and check what domain is using the cookie you want to access.

**Comment by escamoteur** [comment]
Hi,

How do I open the web view chrome inspector?

Cheers
Thomas
Am 24. Jan. 2024, 23:03 +0100 schrieb Lorenzo Pichilli ***@***.***>:

**Comment by pichillilorenzo** [comment]
As already written in the official website docs here: https://inappwebview.dev/docs/debugging-webviews#inspect-android-webviews:
> On Android, in order to enable/disable debugging WebViews using chrome://inspect/#devices on Chrome, you should use the InAppWebViewController.setWebContentsDebuggingEnabled(bool debuggingEnabled) static method.

**Comment by escamoteur** [comment]
Thanks, will look into it
Am 24. Jan. 2024, 23:08 +0100 schrieb Lorenzo Pichilli ***@***.***>:

**Comment by escamoteur** [comment]
OK, it turned out that the inapp browser seems not to create cookies when using the `browser.openData` method. when use the `openURLRequest` method it works
