### ISSUE TITLE
Strict MIME type checking is enabled

### ISSUE THREAD

**Issue by rahulvsharma19** [pichillilorenzo/flutter_inappwebview#1996]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |     3.16.8   |
| Plugin version        |     6.0.0          |
| Android version       |     13          |
| iOS version           |          17.2     |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

## Description
Getting error while loading React project in InAppWebView.
If I'm trying to  simple Html with JavaSrcipt it working when I’m trying to load my React Build its not working.
I'm hosting using `In-App Localhost Server` and loading into InAppWebView.

I have added my project into Asset folder.

<img width="1301" alt="Screenshot 2024-01-25 at 1 09 19 PM" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/157685123/6eecaa55-30a5-411d-b8a7-3f6e9f62eb6f">

**Comment by pichillilorenzo** [comment]
If you need custom behaviour, then you could implement your own localhost server.
Current default implementation is found here: https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/flutter_inappwebview_platform_interface/lib/src/in_app_localhost_server.dart

You can also try to use WebViewAssetLoader for Android: https://inappwebview.dev/docs/webview/webview-asset-loader
