### ISSUE TITLE
Can I check controller status if disposed?

### ISSUE THREAD

**Issue by fyxtc** [pichillilorenzo/flutter_inappwebview#1997]
"Once the IOSInAppWebViewController has been disposed of, it can no longer be used"
I do something in 'onProgressChanged async'， if webview was disposed before the code was done, I got this exception

**Comment by pichillilorenzo** [comment]
Probably, you should already be able to do so using a different approach on how you are using the controller.
As an example, you could have a nullable InAppWebViewController variable in the widget State that is set when onWebViewCreated is fired and set to `null` when the current Widget State is calling the `dispose` method.
Then you should use that variable reference wherever you need.
Also, you could check for `context.mounted` (https://api.flutter.dev/flutter/widgets/BuildContext/mounted.html) value. If it is false, then you current widget context is not rendered and it could means that is too early or the widget has been disposed from the widget tree. In that case, the InAppWebViewController will be also disposed.

**NOTE**: Currently, each InAppWebView event callback has the InAppWebViewController controller as the first parameter, but in future plugin versions it will be removed. That way, the management of the controller should go to the developers.
