### ISSUE TITLE
Support zoom not working[6.0.0] 

### ISSUE THREAD

**Issue by fkaksi** [pichillilorenzo/flutter_inappwebview#2024]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |3.16.9|
| Plugin version        |6.0.0|
| Android version       |16|
| iOS version           |17.3.1|
| Xcode version         |15.0.1|

Device information: 
iPad 10th. Gen
Samsung Galaxy Tab S9 FE+

## Description
I have set from  InAppWebViewSettings supportZoom=false but webview still able to zooming 

**Expected behavior:** 
Not zoom action in any way, especially by finger gestures

**Current behavior:** 
I can still zoom by finger gesture.

**Comment by fkaksi** [comment]
I am not sure, but this works on my project

```
onLoadStart: (controller, url) {
        controller.injectCSSCode(source: ':root {touch-action: pan-x pan-y;height: 100%}');
      },
```
```
onLoadStop: (controller, url) {
        controller.injectCSSCode(source: ':root {touch-action: pan-x pan-y;height: 100%}');
      },
```

**Comment by clewm** [comment]
> 我不确定，但这适用于我的项目
> 
> ```
> onLoadStart: (controller, url) {
>         controller.injectCSSCode(source: ':root {touch-action: pan-x pan-y;height: 100%}');
>       },
> ```
> 
> ```
> onLoadStop: (controller, url) {
>         controller.injectCSSCode(source: ':root {touch-action: pan-x pan-y;height: 100%}');
>       },
> ```

useful!!

**Comment by iifast2** [comment]
[https://stackoverflow.com/a/69390739/10216101](https://stackoverflow.com/a/69390739/10216101)
