### ISSUE TITLE
After dispose a InAppWebViewKeepAlive using InAppWebViewController.disposeKeepAlive.  NullPointerException is thrown when main activity enter destroyed state.

### ISSUE THREAD

**Issue by Murmurl912** [pichillilorenzo/flutter_inappwebview#2025]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |    3.16.9    |
| Plugin version        |          flutter_inappwebview: ^6.0.0-beta.25       |
| Android version       |      9~14       |

Device information: 

This issue is device unrelated.

## Description

When using InAppWebViewController.disposeKeepAlive to manually dispose a keepalive webview.
A NullPointerException is thrown when app enter destoryed state and InAppWebViewController.dispose() is called. 
The nullptr is caused by InAppWebViewManager.disposeKeepAlive not update keepAliveWebViews correctly .  
It simply using  ```keepAliveWebViews.put(keepAliveId, null); ``` to remove release webview.

```
  public void disposeKeepAlive(@NonNull String keepAliveId) {
    FlutterWebView flutterWebView = keepAliveWebViews.get(keepAliveId);
    if (flutterWebView != null) {
      flutterWebView.keepAliveId = null;
      // be sure to remove the view from the previous parent.
      View view = flutterWebView.getView();
      if (view != null) {
        ViewGroup parent = (ViewGroup) view.getParent();
        if (parent != null) {
          parent.removeView(view);
        }
      }
      flutterWebView.dispose();
    }
    // keepAliveWebViews contains null value entry
    if (keepAliveWebViews.containsKey(keepAliveId)) {
      keepAliveWebViews.put(keepAliveId, null);
    }
  }
```
And in dispose method null check is missing.
```
  @Override
  public void dispose() {
    super.dispose();
    Collection<FlutterWebView> flutterWebViews = keepAliveWebViews.values();
    // flutterWebViews contains null element
    for (FlutterWebView flutterWebView : flutterWebViews) {
      String keepAliveId = flutterWebView.keepAliveId;
      if (keepAliveId != null) {
        disposeKeepAlive(flutterWebView.keepAliveId);
      }
    }
    keepAliveWebViews.clear();
    windowWebViewMessages.clear();
    plugin = null;
  }
```
**Expected behavior:** 

Add a null check in dispose method's disposeKeepAlive loop.
```
  @Override
  public void dispose() {
    super.dispose();
    Collection<FlutterWebView> flutterWebViews = keepAliveWebViews.values();
    for (FlutterWebView flutterWebView : flutterWebViews) {
      if (flutterWebView == null) {
        continue;
      }
      String keepAliveId = flutterWebView.keepAliveId;
      if (keepAliveId != null) {
        disposeKeepAlive(flutterWebView.keepAliveId);
      }
    }
    keepAliveWebViews.clear();
    windowWebViewMessages.clear();
    plugin = null;
  }
```
Or refactor disposeKeepAlive to handle ConcurrentModificationException by extract a new method to dispose FlutterWebView
```
  public void disposeKeepAlive(@NonNull String keepAliveId) {
    FlutterWebView flutterWebView = keepAliveWebViews.remove(keepAliveId);
    dispoeKeepAlive(flutterWebView);
  }
  
  public void dispoeKeepAlive(FlutterWebView flutterWebView) {
    if (flutterWebView.keepAliveId == null) {
      return;
    }
    flutterWebView.keepAliveId = null;
    View view = flutterWebView.getView();
    if (view != null) {
      ViewGroup parent = (ViewGroup) view.getParent();
      if (parent != null) {
        parent.removeView(view);
      }
    }
    flutterWebView.dispose();
  }

  @Override
  public void dispose() {
    super.dispose();
    Collection<FlutterWebView> flutterWebViews = keepAliveWebViews.values();
    for (FlutterWebView flutterWebView : flutterWebViews) {
      dispoeKeepAlive(flutterWebView);
    }
    keepAliveWebViews.clear();
    windowWebViewMessages.clear();
    plugin = null;
  }
```

## Steps to reproduce

1. create a InAppWebview with keepAlive
2. dispose InAppWebview using  InAppWebViewController.disposeKeepAlive
3. press back to exit app and wait main activity destory
4. app crashed.

## Stacktrace/Logcat   
Unable to destroy activity {xxx.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.keepAliveId' on a null object reference in method 'void com.pichillilorenzo.flutter_inappwebview_android.webview.InAppWebViewManager.dispose()'

**Comment by Murmurl912** [comment]
Here is the demo code to reproduce this issue: [inappwebview_dispose_keepalive_nullptr](https://github.com/Murmurl912/inappwebview_dispose_keepalive_nullptr)

**Comment by namnh-0652** [comment]
@pichillilorenzo could you help check this?

**Comment by malthee** [comment]
Yes please, this is causing a lot of errors for us

**Comment by pichillilorenzo** [comment]
Thanks, yes I missed the `flutterWebView` null check.

**Comment by Murmurl912** [comment]
Before the next release resolves this issue. Anyone using `keepAlive` should use the following code to safely dispose the `InAppWebViewFlutterPlugin`. Simply using a `try-catch` block will prevent the Flutter engine from completely destroy, which can lead to memory leaks and other issues.

It took me several weeks of investigation to discover that a `SqliteException(5): while executing statement, database is locked` error was actually caused by the Flutter engine not being disposed of properly.

```kotlin
override fun onDestroy() {
    try {
        super.onDestroy()
    } catch (e: Exception) {
        // no-op
    }
}
```

Instead, using to following code the remove null webview from inAppWebViewManager :

```kotlin
import com.pichillilorenzo.flutter_inappwebview_android.InAppWebViewFlutterPlugin


override fun onDestroy() {
    safeDispose()
    super.onDestroy()
}


private fun safeDispose() {
    kotlin.runCatching {
        val flutterEngine = flutterEngine ?: return
        val plugins = flutterEngine.plugins.get(InAppWebViewFlutterPlugin::class.java) as? InAppWebViewFlutterPlugin
            ?: return
        val manager = plugins.inAppWebViewManager ?: return
        val clone = manager.keepAliveWebViews.toMap()
        for (entry in clone) {
            if (entry.value == null) {
                manager.keepAliveWebViews.remove(entry.key)
            }
        }
    }
}
```
