### ISSUE TITLE
[Flutter Web] evaluateJavascript is broke in latest version.

### ISSUE THREAD

**Issue by sanalkv** [pichillilorenzo/flutter_inappwebview#2045]
## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |   3.19.1   |
| Plugin version        |  6.0.0  |
| macOS version         |  Sonoma 14.2.1  |

Device information: MacBook Pro. 14-inch, 2023.

## Description

**Expected behavior:** 
[Flutter Web]
inAppWebViewController.evaluateJavascript(source: "functionName();"); works perfectly fine in flutter version 3.16.4. 

**Current behavior:** 
[Flutter Web]
inAppWebViewController.evaluateJavascript(source: "functionName();"); stopped working in flutter 3.19.1.

## Steps to reproduce

1. Upgrade to latest version of flutter.
2. add the html initial file to InAppWebView (which has a script file connected to the html with the following function name 'abc') .
3.  Store the web view controller in a variable.
   onWebViewCreated: (InAppWebViewController controller) {
                        inAppWebViewController = controller;
                      },
4. call inAppWebViewController.evaluateJavascript(source: "abc();"); somewhere in the app, mostly in onTap property of an inkwell.
5. the 'abc' function present in the script file is never triggered.

## Summarry

I'm currently using flutter web and the inAppWebViewController.evaluateJavascript was working perfectly fine in version 3.16.4. I recently upgraded to 3.19.1 and it stopped working. There was no code modification.

Please let me know me if you need anything else. Really appreciate the work you have done for this package.

**Comment by andynvt** [comment]
up
