### ISSUE TITLE
[Flutter Web] [Flutter 3.19.x] Callbacks (onLoadStart, onLoadStop, onConsoleMessage, onUpdateVisitedHistory) not firing

### ISSUE THREAD

**Issue by TarishAhmed** [pichillilorenzo/flutter_inappwebview#2046]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       | 3.19.1 |
| Plugin version        | 6.0.0 |
| Google Chrome version | 121.0.6167.184 (Official Build) (arm64)  |

Device information: Apple M2 (14.0 (23A344))

## Description

**Expected behavior:** 
All web supported callbacks to work like onLoadStart, onLoadStop, onConsoleMessage, onUpdateVisitedHistory 

**Current behavior:** 
Only onWebViewCreated seems to be working
## Steps to reproduce
load html as data in InAppWebView and execute console message in any window load function

**Comment by asarkar101** [comment]
same issue

**Comment by kleyos** [comment]
It's the same issue on iOS. I have not tried Android yet. Flutter 3.19.5

**Comment by fawdlstty** [comment]
Downgrading to Flutter version 3.16.9 can works for me
