### ISSUE TITLE
[iOS] WebPage is not resized properly when used inside Scaffold, Also sometimes stops the user from scrolling when keyboard is open

### ISSUE THREAD

**Issue by prateekrk** [pichillilorenzo/flutter_inappwebview#2049]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |          Flutter 3.3.10     |
| Plugin version        |       ^5.8.0        |
| Android version       |        -       |
| iOS version           |        17.2       |
| macOS version         |       -        |
| Xcode version         |        15.2       |
| Google Chrome version |      -         |

Device information: Apple iPhone 15 Pro

## Description

**Expected behavior: Screen should resize considering the keyboard length, And Scrolls should not be disabled

**Current behaviour: Screen is resized to wierd coordinates, and also stops user from scrolling

## Steps to reproduce
<details>
<summary>Sample Code</summary>
  import 'package:flutter/foundation.dart';
  import 'package:flutter/material.dart';
  import 'package:flutter_inappwebview/flutter_inappwebview.dart';
  
  void main() {
    runApp(const MyApp());
  }
  
  class MyApp extends StatelessWidget {
    const MyApp({super.key});
    @override
    Widget build(BuildContext context) {
      return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: Scaffold(body: LandingPage(title: "Landing Page")));
    }
  }
  
  class LandingPage extends StatefulWidget {
    const LandingPage({super.key, required this.title});
    final String title;
  
    @override
    State<LandingPage> createState() => _LandingPage();
  }
  
  class _LandingPage extends State<LandingPage> {
    double _pageProgressValue = 0;
    InAppWebViewController? inAppWebViewController;
  
    InAppWebViewGroupOptions settings = InAppWebViewGroupOptions(
        crossPlatform: InAppWebViewOptions(
          useShouldOverrideUrlLoading: true,
          mediaPlaybackRequiresUserGesture: false,
        ),
        android: AndroidInAppWebViewOptions(
          useHybridComposition: true,
        ),
        ios: IOSInAppWebViewOptions(
          allowsInlineMediaPlayback: true,
        ));
    @override
    Widget build(BuildContext context) {
      return Stack(children: [
        InAppWebView(
            shouldOverrideUrlLoading: ((controller, navigationAction) async {
              var request = navigationAction.request.url.toString();
              setState(() {
                request;
              });
              return NavigationActionPolicy.ALLOW;
            }),
            initialUrlRequest: URLRequest(url: Uri.tryParse("https://gmail.com")),
            initialOptions: settings,
            onWebViewCreated: (controller) => inAppWebViewController = controller,
            onProgressChanged: ((controller, progress) {
              if (mounted) {
                setState(() {
                  _pageProgressValue = progress / 100;
                });
              }
            }),
            onLoadStop: (controller, url) {}),
        SizedBox(
          height: _pageProgressValue < 1.0 ? 2 : 0,
          child: LinearProgressIndicator(
            backgroundColor: Colors.white,
            color: Colors.blue,
            value: _pageProgressValue,
            semanticsLabel: 'Linear progress indicator',
          ),
        ),
      ]);
    }
  }

</details>

1. Have two text fields
2. Enter details in the first field
3. Go to the second field, keep switching

## Images

https://github.com/pichillilorenzo/flutter_inappwebview/assets/35128534/128ad55c-7cfb-436f-8746-39eff52cc2ec

**Comment by Thembelani-M** [comment]
We're also experiencing this exact issue @prateekrk were you able to find a workaround ...?

**Comment by adamk22** [comment]
Ran into the same issue here on a page with multiple input fields. In my case its a screen for filling in 2 factor auth codes. I think this issue is related: https://github.com/pichillilorenzo/flutter_inappwebview/issues/2050

**Comment by pichillilorenzo** [comment]
Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/1947#issuecomment-2471147587
