### ISSUE TITLE
Are there plans to add settings to open screen sizes?

### ISSUE THREAD

**Issue by ifredom** [pichillilorenzo/flutter_inappwebview#205]
## Environment
![image](https://user-images.githubusercontent.com/13759936/70031385-18259900-15e6-11ea-9ff4-ac740c17f6e7.png)

## Description

**Are there plans to add settings to open screen sizes?**

**Comment by pichillilorenzo** [comment]
Sorry, but I didn't understand what you mean with "open screen sizes"! Which setting do you want and for what?

**Comment by ifredom** [comment]
> Sorry, but I didn't understand what you mean with "open screen sizes"! Which setting do you want and for what?

Thank you for your answer. I mean, after the webview is opened, it defaults to full screen. Can you provide parameters to display in a certain part of the screen
