### ISSUE TITLE
[iOS] WebPage page, multiple input input boxes, in the page is not satisfied with a screen, switch back and forth input box, page down, keyboard blocking content.

### ISSUE THREAD

**Issue by wangpeitao123** [pichillilorenzo/flutter_inappwebview#2050]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.7.9        |
| Plugin version        |       5.7.2+3 / 6.0.0        |
| Android version       |               |
| iOS version           |         17.2/17.3.1      |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description
When there are multiple input boxes on a page that is not full screen, selecting the first input box will cause the page to move down and hide the keyboard when switching to the second input box.
**Expected behavior:** 
The keyboard does not block the content.
**Current behavior:** 
The page moves downwards, and the keyboard blocks the content.
## Steps to reproduce

1. Select the first input box
2. Switch to the second input field

## Images   
https://github.com/pichillilorenzo/flutter_inappwebview/assets/16298773/85d633bf-e12d-4211-b119-55513b15af55

**Comment by TomStormwind** [comment]
I am facing the same issue
Environment

Flutter version | 3.19.3
Plugin version | 6.0.0
Android version |  
iOS version | 17.2
macOS version |  
Xcode version |  
Google Chrome version

**Comment by TomStormwind** [comment]
it doesn't appear on iOS 15.7

**Comment by MarsLeo** [comment]
I am facing the same issue
Environment

Flutter version | 3.13.8
Plugin version | 5.7.2+3
Android version |  
iOS version | 17.4、17.2
macOS version |  
Xcode version |  
Google Chrome version

**Comment by grays820** [comment]
I am facing the same issue
Environment

Flutter version | 3.19.3
Plugin version | 5.8.0
Android version |
iOS version | 17.4.1
macOS version |
Xcode version |
Google Chrome version

**Comment by LXG19961206** [comment]
最基本的 input 用起来都一堆坑

**Comment by adamk22** [comment]
Ran into the same issue with multiple input fields, in this case a screen for filling in 2 factor auth codes.

**Comment by pichillilorenzo** [comment]
Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/1947#issuecomment-2471147587
