### ISSUE TITLE
WASM compatibility

### ISSUE THREAD

**Issue by The-RootCause** [pichillilorenzo/flutter_inappwebview#2052]
Hello,

The current package is not Wasm compatible. 
The following files has issues when attempting wasm compilation:

`Detailed import paths for (some of) the these imports:

    main.dart => web_plugin_registrant.dart => package:flutter_inappwebview_web/web/main.dart => package:flutter_inappwebview_web/web/web_platform.dart => package:flutter_inappwebview_web/web/headless_inappwebview_manager.dart => dart:html
    main.dart => web_plugin_registrant.dart => package:flutter_inappwebview_web/web/main.dart => package:flutter_inappwebview_web/web/web_platform.dart => package:flutter_inappwebview_web/web/headless_inappwebview_manager.dart =>
    package:flutter_inappwebview_web/web/in_app_web_view_web_element.dart => dart:html
    main.dart => web_plugin_registrant.dart => package:flutter_inappwebview_web/web/main.dart => package:flutter_inappwebview_web/web/web_platform.dart => package:flutter_inappwebview_web/web/headless_inappwebview_manager.dart =>
    package:flutter_inappwebview_web/web/headless_in_app_web_view_web_element.dart => package:flutter_inappwebview_web/web/in_app_web_view_web_element.dart => dart:html
    main.dart => web_plugin_registrant.dart => package:flutter_inappwebview_web/web/main.dart => package:flutter_inappwebview_web/web/web_platform.dart => package:flutter_inappwebview_web/web/in_app_web_view_web_element.dart => dart:html
    main.dart => web_plugin_registrant.dart => package:flutter_inappwebview_web/web/main.dart => package:flutter_inappwebview_web/web/web_platform.dart => package:flutter_inappwebview_web/web/shims/platform_view_registry.dart =>
    package:flutter_inappwebview_web/web/shims/platform_view_registry_dart_ui_web.dart => dart:html
`

Thank you

**Comment by josh-burton** [comment]
Wasm is now stable in Flutter 3.22.0 so would be great to support it.

**Comment by zh4ngx** [comment]
Same. Looks like there's documentation on migration - should be somewhat simplifying / net deletion of code & imports :) 
https://dart.dev/interop/js-interop
https://dart.dev/interop/js-interop/package-web
