### ISSUE TITLE
Listen to requests

### ISSUE THREAD

**Issue by dudizimber** [pichillilorenzo/flutter_inappwebview#206]
## Description

Hi,
I'm developing an app where the user is required to do few things in different websites, and I have to detect whether he completed that task or not.
In a few websites I can simply inject some javascript and send a message back to the app, but there are some websites that I cannot to that since they block inline javascript, or that's what I understood (Ex: twitter.com).
So looking for other option, I stumbled across the "chrome.webRequest" API which is used to listen to requests made from a page. However it looks like this API is mainly for extensions.

I wonder if it is possible to do something like that with InAppWebView package.
 
Thank you.

**Comment by pichillilorenzo** [comment]
There are also other ways to execute some javascript that is not restricted to injecting a javascript file! You can also use:
- `controller.evaluateJavascript(source: "");` 
- `controller.loadUrl(url: "javascript:(function(){ ... here some javascript ... })();");`

For example, I loaded `"https://twitter.com/home"` and it works:
```dart
...

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: Text("InAppWebView")
        ),
        body: Container(
            child: Column(children: <Widget>[
              Expanded(
                child: Container(
                  child: InAppWebView(
                    initialUrl: "https://twitter.com/home",
                    initialHeaders: {},
                    initialOptions: InAppWebViewWidgetOptions(
                      inAppWebViewOptions: InAppWebViewOptions(
                        debuggingEnabled: true,
                      )
                    ),
                    onWebViewCreated: (InAppWebViewController controller) {
                      webView = controller;
                    },
                    onLoadStart: (InAppWebViewController controller, String url) {

                    },
                    onLoadStop: (InAppWebViewController controller, String url) {
                      controller.evaluateJavascript(source: "alert('HI');");
                      controller.loadUrl(url: "javascript:(function(){ alert('HI'); })();");
                    },
                  ),
                ),
              ),
            ]))
    );
  }

...
```

However, chrome APIs, such as `chrome.webRequest`, are only for Chrome Extension!

**Comment by dudizimber** [comment]
> 
> 
> There are also other ways to execute some javascript that is not restricted to injecting a javascript file! You can also use:
> 
>     * `controller.evaluateJavascript(source: "");`
> 
>     * `controller.loadUrl(url: "javascript:(function(){ ... here some javascript ... })();");`
> 
> 
> For example, I loaded `"https://twitter.com/home"` and it works:
> 
> ```dart
> ...
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>         appBar: AppBar(
>             title: Text("InAppWebView")
>         ),
>         body: Container(
>             child: Column(children: <Widget>[
>               Expanded(
>                 child: Container(
>                   child: InAppWebView(
>                     initialUrl: "https://twitter.com/home",
>                     initialHeaders: {},
>                     initialOptions: InAppWebViewWidgetOptions(
>                       inAppWebViewOptions: InAppWebViewOptions(
>                         debuggingEnabled: true,
>                       )
>                     ),
>                     onWebViewCreated: (InAppWebViewController controller) {
>                       webView = controller;
>                     },
>                     onLoadStart: (InAppWebViewController controller, String url) {
> 
>                     },
>                     onLoadStop: (InAppWebViewController controller, String url) {
>                       controller.evaluateJavascript(source: "alert('HI');");
>                       controller.loadUrl(url: "javascript:(function(){ alert('HI'); })();");
>                     },
>                   ),
>                 ),
>               ),
>             ]))
>     );
>   }
> 
> ...
> ```
> 
> However, chrome APIs, such as `chrome.webRequest`, are only for Chrome Extension! These APIs are not Android WebView APIs (that are [here](https://developer.android.com/reference/android/webkit/WebView)).

I'll definitely try that! 
Thank you very much!
