### ISSUE TITLE
It's possible to add a global variable(window.xxx) before page loaded?

### ISSUE THREAD

**Issue by Doflatango** [pichillilorenzo/flutter_inappwebview#207]
## Description

**What you'd like to happen:** 

I want to add a global variable like **window.flutter_inappwebview** before page loaded, therefore, the script can use this variable once the page loaded.

Currently, i call **InAppWebViewController.evaluateJavascript** on event **onLoadStart** to do this, by it is too late, because the script in the page throw an error **xxx is not defined**.

**Comment by pichillilorenzo** [comment]
Why you can't use `window.flutter_inappwebview.callHandler`? There is a particular case?

You can simply add a javascript handler with `controller.addJavaScriptHandler` and, on the javascript side, just listen the `flutterInAppWebViewPlatformReady` global event with `window.addEventListener("flutterInAppWebViewPlatformReady", function(event) { })` method and your handler. With this, you are sure that your handlers are defined.

For example:

- Flutter side:
```dart
onWebViewCreated: (InAppWebViewController controller) {
  webView = controller;

  controller.addJavaScriptHandler(handlerName: "mySum", callback: (args) {
    // Here you receive all the arguments from the JavaScript side 
    // that is a List<dynamic>
    print("From the JavaScript side:");
    print(args);
    return args.reduce((curr, next) => curr + next);
  });
},
```
- Javascript side:
```html
... 

<script>
    // In order to call window.flutter_inappwebview.callHandler(handlerName <String>, ...args) 
    // properly, you need to wait and listen the JavaScript event flutterInAppWebViewPlatformReady. 
    // This event will be dispatched as soon as the platform (Android or iOS) is ready to handle the callHandler method. 
    window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
      // call flutter handler with name 'mySum' and pass one or more arguments
      window.flutter_inappwebview.callHandler('mySum', 12, 2, 50).then(function(result) {
        // get result from Flutter side. It will be the number 64.
        console.log(result);
      });
    });
</script>

...
```
