### ISSUE TITLE
Release app crashes without permission

### ISSUE THREAD

**Issue by koteezy** [pichillilorenzo/flutter_inappwebview#208]
Hello!

When we compile an application with a production (release ) mode, it crashes, and immediately closes.

This happens only in the release version!

When we began to study the logs, we realized that the application does not have access to the Internet, maybe we should add some description in the documentation?

Decision, add new settings line <manifest> in AndroidManifest.xml (android/app/src/main)

`<uses-permission android:name="android.permission.INTERNET"/>`

**Comment by pichillilorenzo** [comment]
I thought it was obvious to add this permission on Android. 
So, I will add it to the documentation. Thanks!
