### ISSUE TITLE
flutter windows cookies not working

### ISSUE THREAD

**Issue by selvam920** [pichillilorenzo/flutter_inappwebview#2093]
after submit login it's again redirected to login instead of homepage, seems the cookies are not working

[WindowsInAppWebViewController] (windows) WebView ID 2503702453472 calling "onReceivedError" using {error: {description: Indicates that the operation was canceled., type: 14}, request: {headers: {Content-Type: application/x-www-form-urlencoded, Origin: https://sms.tccl.co.in, Upgrade-Insecure-Requests: 1, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0, sec-ch-ua: "Microsoft Edge";v="123", "Not:A-Brand";v="8", "Chromium";v="123", "Microsoft Edge WebView2";v="123", sec-ch-ua-mobile: ?0, sec-ch-ua-platform: "Windows"}, isForMainFrame: true, method: null, url: https://sms.tccl.co.in/index.php/lco_portal/}}

**Comment by aliazxs** [comment]
same issue

**Comment by selvam920** [comment]
No one supporting this issue

**Comment by selvam920** [comment]
can you support this issue?

**Comment by selvam920** [comment]
it's working when i comment the lines in in_app_webview.cpp file line no from 219 to 346 (webView->add_NavigationStarting)

**Comment by pichillilorenzo** [comment]
It should work with the latest version 6.1.3 published now.

**Comment by selvam920** [comment]
InAppWebView used in page1
in page 2 when i click button page1 will display.
the below url used cookies to login, once logged in after 10 min will logout.
https://sms.tccl.co.in/index.php/lco_portal/

everytime when i open page 1, it's asking the login page.
this issue only in Windows platform, in android everything is working fine.
