### ISSUE TITLE
Setting of presentationStyle not working on iOS

### ISSUE THREAD

**Issue by panndoraBoo** [pichillilorenzo/flutter_inappwebview#213]
Hi there! 
First, thank you so much for this plugin, it has been a lifesaver for me.
So I have found out the setting of the presentationstyle doesn't seem to work (at least in ios13) I think it is because it is set too late in the native ios code. If I set
webViewController.modalPresentationStyle = UIModalPresentationStyle.fullScreen
hardcoded in "SwiftFlutterPlugin.swift" at "open", it displays a fullscreen popup. I'm totally new to Swift so I am not really able to fix it in a correct way, but maybe it helps you to fix it :)

Original question:

_I wanted to ask if there's an option to disable the closing of the in-app browser when the user swipes it down in ios. I want to disallow the user to close the in-app browser on its own and thought I handled it with removing the close button. But I found out by accidentally swiping the window down, it also closes/hides.  It also doesn't fire the on close callback._ 

_I've   flutter_inappwebview: ^2.1.0+1 (but it also occurred on older versions) and am using the plugin on an iPad._ 

_Please help. If the browser is closed by dragging, the whole app freezes and can't do anything anymore._

**Comment by panndoraBoo** [comment]
Ok so I have found the issue. In iOS 13, the setting of "presentationStyle" is not working. I think it is because it is set too late in the native ios code. If I set 
webViewController.modalPresentationStyle = UIModalPresentationStyle.fullScreen
hardcoded in "SwiftFlutterPlugin.swift" at "open", it displays a fullscreen popup. I'm totally new to Swift so I am not really able to fix it in a correct way, but maybe it helps you to fix it :)

**Comment by pichillilorenzo** [comment]
Ok! Thanks!

**Comment by prajwalmr62** [comment]
@pichillilorenzo I'm also facing the same issue here. Can you please let me know in which release the fix is going to be?

**Comment by prajwalmr62** [comment]
This change is available from `v 3.0.0`
