### ISSUE TITLE
Build error with latest flutter/agp versions

### ISSUE THREAD

**Issue by holzgeist** [pichillilorenzo/flutter_inappwebview#2139]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |  3.22             |
| Plugin version        |       1.0.13        |
| Android version       |   14            |
| iOS version           |         --      |
| macOS version         |     --          |
| Xcode version         |        --       |
| Google Chrome version |   --            |
| *Android Gradle Plugin* | 8.4.0 |

Device information:  irrelevant, as this is a build error

## Description

**Expected behavior:** 

Be able to compile an app on Android using this plugin with obfuscation/minification

**Current behavior:** 

Build error during minification:

```
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in .../build/flutter_inappwebview_android/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class android.window.BackEvent (referenced from: void io.flutter.embedding.android.FlutterActivity.startBackGesture(android.window.BackEvent) and 3 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_inappwebview_android:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete
```

## Steps to reproduce

1. Depend on flutter_inappwebview
2. Upgrade to latest flutter/AGP/...
3. Do a release build with minification (e.g. `flutter build apk --obfuscate --split-debug-info /tmp/debug-info`. Alternatively, skip `--obfuscate --split-debug-info ...` and set `minifyEnabled true` in `android/app/build.gradle`

**Comment by Augustinekan** [comment]
> It would be great if the according PR could be merged quickly, as this currently blocks us (and probably other devs as well) from building releases, and downgrading to an earlier version is quite cumbersome as the API has changed in between.

Any luck pointing your dependency to the pull request? it doesn't work on my side

**Comment by komaxx** [comment]
Ah, good point!
Got it to run with:
```
dependency_overrides:
  # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
```

**Comment by flechajm** [comment]
> Ah, good point! Got it to run with:
> 
> ```
> dependency_overrides:
>   # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
>   flutter_inappwebview_android:
>     git:
>       url: https://github.com/holzgeist/flutter_inappwebview
>       path: flutter_inappwebview_android
>       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
> ```

You saved my deploy today. Thank you so much!

**Comment by specOper99** [comment]
Still having an issue even afetr depending on `holzgeist` repo

```
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/username/Desktop/projectname/build/app/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class com.google.j2objc.annotations.ReflectionSupport$Level (referenced from: com.google.common.util.concurrent.AbstractFuture)
Missing class com.google.j2objc.annotations.ReflectionSupport (referenced from: com.google.common.util.concurrent.AbstractFuture)
Missing class com.google.j2objc.annotations.RetainedWith (referenced from: com.google.common.collect.ImmutableSet com.google.common.collect.ImmutableMap.entrySet and 3 other contexts)

FAILURE: Build failed with an exception.

```

**Comment by Yohan-J** [comment]
> Still having an issue even afetr depending on `holzgeist` repo
> 
> ```
> ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/username/Desktop/projectname/build/app/outputs/mapping/release/missing_rules.txt.
> ERROR: R8: Missing class com.google.j2objc.annotations.ReflectionSupport$Level (referenced from: com.google.common.util.concurrent.AbstractFuture)
> Missing class com.google.j2objc.annotations.ReflectionSupport (referenced from: com.google.common.util.concurrent.AbstractFuture)
> Missing class com.google.j2objc.annotations.RetainedWith (referenced from: com.google.common.collect.ImmutableSet com.google.common.collect.ImmutableMap.entrySet and 3 other contexts)
> 
> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':app:minifyReleaseWithR8'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
>    > Compilation failed to complete
> ```

@specOper99  - looks like your issue is not linked to flutter_inappwebview, but that fact that your proguard.pro file is not there.  
check if you have the proguard-rules.pro file in your project (android/app/). if not create one and then add the following lines

-ignorewarnings
-keep class * {
    public private *;
}

**Comment by nayanbabariya** [comment]
@Yohan-J You have an issue with Proguard but it's a different one. check the actual issue [here](https://github.com/pichillilorenzo/flutter_inappwebview/issues/2139#issue-2294962738).

- Actual issue is about the `R8: Missing class android.window.BackEvent` and your issue is `R8: Missing class com.google.j2objc.annotations.ReflectionSupport$Level` that is from a different thing.

**Comment by Yohan-J** [comment]
@nayanbabariya  yes, this wasn't my issue, but i was also replying to the comment above mine, stating that his issue was something else.

**Comment by nayanbabariya** [comment]
@Yohan-J Okay. but the mentioned issue is from the `flutter_inappwebview` plugin.

**Comment by MaxB5** [comment]
In my case, it seems the issue was cause by youtube_player_flutter that depends on flutter_inappwebview

**Comment by toshiossada** [comment]
the same here

**Comment by AcuitySoftwareDev** [comment]
> the same here. but, I solved it.
> 
> my error code
> 
> ```
> Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/jeonglockpark/Desktop/work/daopass/daopass/build/flutter_inappwebview_android/outputs/mapping/release/missing_rules.txt.
> ```
> 
> Add 1
> 
> ```
> dependency_overrides:
>   # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
>   flutter_inappwebview_android:
>     git:
>       url: https://github.com/holzgeist/flutter_inappwebview
>       path: flutter_inappwebview_android
>       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
> ```
> 
> Add 2
> 
> ```
> # Please add these rules to your existing keep rules in order to suppress warnings.
> # This is generated automatically by the Android Gradle plugin.
> -dontwarn com.google.j2objc.annotations.ReflectionSupport$Level
> -dontwarn com.google.j2objc.annotations.ReflectionSupport
> -dontwarn com.google.j2objc.annotations.RetainedWith
> ```
> 
> The build was successful with the two additional methods above. Hopefully the package will be updated normally soon.
> 
> Thanks a lot.

Sorry, where am i putting this add, which file, Gradle or proguard?

**Comment by komaxx** [comment]
> > the same here. but, I solved it.
> > my error code
> > ```
> > Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/jeonglockpark/Desktop/work/daopass/daopass/build/flutter_inappwebview_android/outputs/mapping/release/missing_rules.txt.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Add 1
> > ```
> > dependency_overrides:
> >   # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
> >   flutter_inappwebview_android:
> >     git:
> >       url: https://github.com/holzgeist/flutter_inappwebview
> >       path: flutter_inappwebview_android
> >       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Add 2
> > ```
> > # Please add these rules to your existing keep rules in order to suppress warnings.
> > # This is generated automatically by the Android Gradle plugin.
> > -dontwarn com.google.j2objc.annotations.ReflectionSupport$Level
> > -dontwarn com.google.j2objc.annotations.ReflectionSupport
> > -dontwarn com.google.j2objc.annotations.RetainedWith
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The build was successful with the two additional methods above. Hopefully the package will be updated normally soon.
> > Thanks a lot.
> 
> Sorry, where am i putting this add, which file, Gradle or proguard?

The first add goes to your `pubspec.yaml` file. 
Just add that below your `dependencies` block if you don't have any `dependency_overrides` yet. This tells the build pipeline to not use the real dependency but instead the one defined as override (a specific commit in a different repo).

The second one is not required in my setup, so you might not need it either. But if you do, this goes to the `proguard-rules.pro`  file in your project's `android/app` folder.

**Comment by subzero911** [comment]
> Ah, good point! Got it to run with:
> 
> ```
> dependency_overrides:
>   # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
>   flutter_inappwebview_android:
>     git:
>       url: https://github.com/holzgeist/flutter_inappwebview
>       path: flutter_inappwebview_android
>       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
> ```


After I added dependency_overrides, my apk size increased from 60 Mb to almost 110 Mb!
Seems like you turned off some Proguard rules, and some unneeded stuff got into the assembly.

**Comment by AcuitySoftwareDev** [comment]
Noted with thanks, let me do that and build.

**Comment by subzero911** [comment]
I'm still sitting on a flutter_inappwebview 5.8, and we managed to remove this R8 error by adding the following line in the beginning of the `android/build.gradle` script:
```groovy
project.gradle.startParameter.excludedTaskNames.add(":flutter_inappwebview:minifyReleaseWithR8")
```
I hope it will help to someone.

**Comment by kevinzhow** [comment]
> I'm still sitting on a flutter_inappwebview 5.8, and we managed to remove this R8 error by adding the following line in the beginning of the `android/build.gradle` script:
> 
> ```groovy
> project.gradle.startParameter.excludedTaskNames.add(":flutter_inappwebview:minifyReleaseWithR8")
> ```
> 
> I hope it will help to someone.

This really helps

**Comment by cc-rock** [comment]
We tried @subzero911 's fix (which seems better than referencing a PR branch) but did not work for our app, because when building from clean repo, skipping the minification task caused other tasks to fail because they weren't finding the expected output (the jar file).

This is an evolution of that fix, which properly disables minification instead of skipping the task, and for us it works even when building from scratch.
Add this in the `android/build.gradle` file:

```
subprojects {
    afterEvaluate {
        if (it.name == "flutter_inappwebview_android") {
            it.android.buildTypes.release.minifyEnabled = false
        }
    }
}
```
If your file already has a subprojects / afterEvaluate section you might have to put it in there instead. 

Anyway, should the minification be enabled for an open source android library project? I think that generally it shoudn't, because the code would be merged with the whole app's codebase and minification would then run globally.. so a better "official" fix could be to change `minifyEnabled` to false in this project's `build.gradle`. @pichillilorenzo what do you think?

**Comment by mustafa-fahimi** [comment]
I still have this problem and none of solutions provided is working for me.

**Comment by HelmiAshraf** [comment]
I encountered evaluation timing issues when configure within the `android/build.gradle` file. To resolve this, I moved the configuration to the `settings.gradle` file and used the `beforeProject` and `afterEvaluate` hooks. This method worked 

```
include ":app", ":flutter_inappwebview_android"


gradle.beforeProject { project ->
    if (project.name == "flutter_inappwebview_android") {
        project.afterEvaluate {
            if (project.hasProperty("android")) {
                project.android.buildTypes.release.minifyEnabled = false
            }
        }
    }
}
```

**Comment by edisonlsm** [comment]
I'm still on version 5.8.0 because of some reasons, tried both methods above from @cc-rock and @HelmiAshraf and none of them worked :(

I can see the `minifyEnabled` property being set to false, if I println `project.android.buildTypes.release.minifyEnabled`it shows minifyEnabled as false but the same R8 error keep happening :(

I also added `-dontwarn android.window.**` to my proguard file and it also did not work :(

Did anyone manage to build in release mode with the version 5.8? Actually, did upgrading to 6.0.0 fixes the issue or not?

**Comment by kevinzhow** [comment]
> I encountered evaluation timing issues when configure within the `android/build.gradle` file. To resolve this, I moved the configuration to the `settings.gradle` file and used the `beforeProject` and `afterEvaluate` hooks. This method worked
> 
> ```
> include ":app", ":flutter_inappwebview_android"
> 
> 
> gradle.beforeProject { project ->
>     if (project.name == "flutter_inappwebview_android") {
>         project.afterEvaluate {
>             if (project.hasProperty("android")) {
>                 project.android.buildTypes.release.minifyEnabled = false
>             }
>         }
>     }
> }
> ```

After I upgrade to Gradle 8.5, this solution works.

**Comment by alostsega** [comment]
> I'm still on version 5.8.0 because of some reasons, tried both methods above from @cc-rock and @HelmiAshraf and none of them worked :(
> 
> I can see the `minifyEnabled` property being set to false, if I println `project.android.buildTypes.release.minifyEnabled`it shows minifyEnabled as false but the same R8 error keep happening :(
> 
> I also added `-dontwarn android.window.**` to my proguard file and it also did not work :(
> 
> Did anyone manage to build in release mode with the version 5.8? Actually, did upgrading to 6.0.0 fixes the issue or not?

@edisonlsm I'm using 5.8.0 and I made it work with @HelmiAshraf solution but you need to change "flutter_inappwebview_android" to "flutter_inappwebview" on version "5.xx"

**Comment by flechajm** [comment]
> We tried @subzero911 's fix (which seems better than referencing a PR branch) but did not work for our app, because when building from clean repo, skipping the minification task caused other tasks to fail because they weren't finding the expected output (the jar file).
> 
> This is an evolution of that fix, which properly disables minification instead of skipping the task, and for us it works even when building from scratch. Add this in the `android/build.gradle` file:
> 
> ```
> subprojects {
>     afterEvaluate {
>         if (it.name == "flutter_inappwebview_android") {
>             it.android.buildTypes.release.minifyEnabled = false
>         }
>     }
> }
> ```
> 
> If your file already has a subprojects / afterEvaluate section you might have to put it in there instead.
> 
> Anyway, should the minification be enabled for an open source android library project? I think that generally it shoudn't, because the code would be merged with the whole app's codebase and minification would then run globally.. so a better "official" fix could be to change `minifyEnabled` to false in this project's `build.gradle`. @pichillilorenzo what do you think?

Since the branch is no longer available (at least I can't connect to the branch anymore when run `pub get`), this solution works by far.

My `build.gradle` is this right now:

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
    // --------------------- ADDED HERE ---------------------
    subprojects {
        afterEvaluate {
            if (it.name == "flutter_inappwebview_android") {
                it.android.buildTypes.release.minifyEnabled = false
            }
        }
    }
}

// AND THIS IS THE REST OF MY GRADLE...

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

Another problem, if it is a "problem", the package `youtube_player_flutter: ^9.0.0` depends on `flutter_inappwebview: ^6.0.0`, and I cannot downgrade to inappwebview 5.8.0

Hope this package get and update soon! (8 months since last time to this days)

**Comment by AcuitySoftwareDev** [comment]
Thanks bro for the update

**Comment by FlutteriPOP** [comment]
Is there any other package because it is still not working, same warning?

**Comment by phamconganh** [comment]
For everyone who wants hotfix and waiting for update. You can comment version `com.android.application` 8+ in `android/settings.gradle`
plugins {
    // id "com.android.application" version "8.1.0" apply false
    id "com.android.application" version "7.3.0" apply false
}

**Comment by thobiassilva** [comment]
Any update?

**Comment by tungpham6195** [comment]
Fixed in [v6.1.1](https://github.com/pichillilorenzo/flutter_inappwebview/blob/v6.1.1/flutter_inappwebview_android/android/proguard-rules.pro#L19)
![Screenshot 2024-10-02 at 22 42 45](https://github.com/user-attachments/assets/c731bccc-c0a0-4d8e-b63d-d3dfef84ca57)

**Comment by pichillilorenzo** [comment]
> Anyway, should the minification be enabled for an open source android library project? I think that generally it shoudn't, because the code would be merged with the whole app's codebase and minification would then run globally.. so a better "official" fix could be to change `minifyEnabled` to false in this project's `build.gradle`. @pichillilorenzo what do you think?

@cc-rock I think you are right, so the developer should know what to "-keep" inside the proguard-rules.pro file of the his/her App in case the minification is enabled.
Doing so now could be a breaking change, so it could be part of the next major version.

**Comment by MuddassarElexoft** [comment]
> > I'm still sitting on a flutter_inappwebview 5.8, and we managed to remove this R8 error by adding the following line in the beginning of the `android/build.gradle` script:
> > ```groovy
> > project.gradle.startParameter.excludedTaskNames.add(":flutter_inappwebview:minifyReleaseWithR8")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope it will help to someone.
> 
> This really helps

This works with release builds, But I am unable to open browser any idea why.
