### ISSUE TITLE
maybe its bug or my fault？

### ISSUE THREAD

**Issue by Maxbee** [pichillilorenzo/flutter_inappwebview#215]
i copy your demo code in my program and when i run my program,its show this ,what should i do?thank!
```
 Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.pichillilorenzo/flutter_inappwebview')
```

**Comment by teejayhh** [comment]
What was your fault ?

**Comment by divrse** [comment]
> What was your fault @Maxbee?
@teejayhh io.flutter.embedded_views_preview needed to be added as boolean and set to YES in info.plist
