### ISSUE TITLE
[InAppWebView] double click but touchstart event only trigger once 

### ISSUE THREAD

**Issue by OPY-bbt** [pichillilorenzo/flutter_inappwebview#216]
## Environment

**Flutter version:** 1.10.15
**Plugin version:**    2.1.0+1
**Android version:**    
**iOS version:** 13.1.3
**Xcode version:**  xcode 11.1
**Device information:**    iOS

## Description
I use `InAppWebView` load html, then double click div tag, but only trigger once event;
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        div {
            font-size: 30px;
        }
    </style>
</head>
<body>
    <div>click</div>
    <script>
        document.querySelector('div').addEventListener('touchstart', function() {
            console.log('click');
        });
    </script>
</body>
</html>
```

**Expected behavior:** 
two click log
**Current behavior:** 
one click log

**Comment by ammmmmmmmmmmmm** [comment]
I debugged my demo
, It is found that the ```FlutterTouchInterceptingView ```  ```DelayingGestureRecognizer``` interception is an event

**Comment by ammmmmmmmmmmmm** [comment]
I added the following code and it works as expected：
` override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        
        let view = super.hitTest(point, with: event);
        
        let gestureRecognizers = self.superview?.superview?.gestureRecognizers ?? []
        for gesture in gestureRecognizers{
        
            gesture.isEnabled = false
        }
        return view
    }`

**Comment by lucashsilva** [comment]
I have the same problem. @ammmmmmmmmmmmm where did you add that code?

**Comment by lucashsilva** [comment]
I have the same issue and that code snippet solved it. However, I'm not sure if it impacts something else.

**Comment by AlexMatovnikov** [comment]
Hi! Tell me, where do I need to add this code?

**Comment by swordyy7** [comment]
> Hi! Tell me, where do I need to add this code?

https://github.com/flutter/flutter/issues/94325#issuecomment-1442098594

**Comment by JoaaoVerona** [comment]
Thanks @swordyy7 for the fix!

To anyone else who wants to try this fix, I just published a fork of flutter_inappwebview with the touch delay fix provided by @swordyy7.

- `flutter pub remove flutter_inappwebview`
- `flutter pub add flutter_inappwebview_fix_iostouchdelay`
- Update your imports from `flutter_inappwebview` to `flutter_inappwebview_fix_iostouchdelay`, example:
  - From: `import "package:flutter_inappwebview/flutter_inappwebview.dart";`
  - To: `import "package:flutter_inappwebview_fix_iostouchdelay/flutter_inappwebview_fix_iostouchdelay.dart";`

The forked library is listed on pub.dev [here](https://pub.dev/packages/flutter_inappwebview_fix_iostouchdelay), and the source code is [here](https://github.com/Skiley/flutter_inappwebview_fix_iostouchdelay).

Hope this helps someone. :)

**Comment by deekshithdv** [comment]
@swordyy7 
The code snippet resolve the touch issue but it disables the interaction with any flutter native components displayed on top of the WebView! :(
