### ISSUE TITLE
Keyboard doesn't close when input loses focus (Android)

### ISSUE THREAD

**Issue by DieBrise** [pichillilorenzo/flutter_inappwebview#217]
## Environment

**Flutter version:** 1.9.1+hotfix.6
**Plugin version:**  ^2.1.0 
**Android version:**  9
**iOS version:**
**Xcode version:**  
**Device information:**  Android 

## Description
When I click on an input, the Android keyboard pops up and works fine. However, when I click out of the input, the keyboard still remains on screen.

**Expected behavior:**
The keyboard closes when the input that brought it up loses focus.

**Current behavior:** 
The keyboard persists on the page, no matter what action is taken. The only way to remove the keyboard is to click the Android back button.

## Steps to reproduce

1. Using the Webview, open a page with a form or an input.
2. Click on the input (Keyboard shows)
3. Click any other element to remove focus from the input.

**Comment by DieBrise** [comment]
> ## Environment
> **Flutter version:** 1.9.1+hotfix.6
> **Plugin version:** ^2.1.0
> **Android version:** 9
> **iOS version:**
> **Xcode version:**
> **Device information:** Android
> 
> ## Description
> When I click on an input, the Android keyboard pops up and works fine. However, when I click out of the input, the keyboard still remains on screen.
> 
> **Expected behavior:**
> The keyboard closes when the input that brought it up loses focus.
> 
> **Current behavior:**
> The keyboard persists on the page, no matter what action is taken. The only way to remove the keyboard is to click the Android back button.
> 
> ## Steps to reproduce
> 1. Using the Webview, open a page with a form or an input.
> 2. Click on the input (Keyboard shows)
> 3. Click any other element to remove focus from the input.

**Comment by pichillilorenzo** [comment]
Yes, this is a known issue for embedded native views in flutter.

**Comment by DieBrise** [comment]
#182
