### ISSUE TITLE
[InAppWebview]: window.flutter_inappwebview.callHandler is not a function

### ISSUE THREAD

**Issue by OPY-bbt** [pichillilorenzo/flutter_inappwebview#218]
## Environment

**Flutter version:** 1.10.15
**Plugin version:**    ^2.1.0+1
**Android version:**    9
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description
I use demo to load url, but get javascript error when click div.
`I/flutter (27593): Uncaught TypeError: window.flutter_inappwebview.callHandler is not a function`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        div {
            font-size: 30px;
        }
    </style>
</head>
<body>
    <div>click</div>
    <script>
        window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
            console.log("ready");

            var div = document.body.querySelector('div');
            div.addEventListener('click', function() {
                window.flutter_inappwebview.callHandler('handleData', 1, true, ['bar', 5], {foo: 'baz'});
            });
        });
    </script>
</body>
</html>
```

```dart
onLoadStop:
    (InAppWebViewController controller, String url) async {
  setState(() {
    this.url = url;
  });

  webView.addJavaScriptHandler(
      handlerName: 'handleData',
      callback: (args) {
        print(args);
      });
},
```

**Comment by OPY-bbt** [comment]
![image](https://user-images.githubusercontent.com/16717283/70675909-77119f00-1cc5-11ea-8d69-e545b6313538.png)

**Comment by ositano** [comment]
I get this error **TypeError: undefined is not an object (evaluating 'window.flutter_inappbrowser.callHandler')** on running the below example

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  InAppWebViewController webView;
  String url = "";
  double progress = 0;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('InAppWebView Example'),
        ),
        body: Container(
            child: Column(children: <Widget>[
          Container(
            padding: EdgeInsets.all(20.0),
            child: Text(
                "CURRENT URL\n${(url.length > 50) ? url.substring(0, 50) + "..." : url}"),
          ),
          Container(
              padding: EdgeInsets.all(10.0),
              child: progress < 1.0
                  ? LinearProgressIndicator(value: progress)
                  : Container()),
          Expanded(
            child: Container(
              margin: const EdgeInsets.all(10.0),
              decoration:
                  BoxDecoration(border: Border.all(color: Colors.blueAccent)),
              child: InAppWebView(
                initialUrl: "https://flutter.dev/",
                initialHeaders: {},
                initialOptions: InAppWebViewWidgetOptions(
                    inAppWebViewOptions: InAppWebViewOptions(
                  debuggingEnabled: true,
                  javaScriptEnabled: true,
                  useShouldOverrideUrlLoading: true,
                  useOnLoadResource: true,
                  cacheEnabled: true,
                )),
                onWebViewCreated: (InAppWebViewController controller) {
                  webView = controller;
                  webView.addJavaScriptHandler(
                      handlerName: "HtmlViewer",
                      callback: (arguments) async {
                        print('hello from htmlViewer');
                        print(arguments.length);
                        print(arguments);
                      });
                },
                onLoadStart: (InAppWebViewController controller, String url) {
                  setState(() {
                    this.url = url;
                  });
                },
                onLoadStop:
                    (InAppWebViewController controller, String url) async {
                  setState(() {
                    this.url = url;
                  });

                  String htmlData = "";
                  //htmlData = result3;
                  htmlData = "<html>hello guys are there<\/html>";

                  String js =
                      "window.flutter_inappbrowser.callHandler('HtmlViewer', '$htmlData')";
                  await controller.evaluateJavascript(source: js);
                },
                onProgressChanged:
                    (InAppWebViewController controller, int progress) {
                  setState(() {
                    this.progress = progress / 100;
                  });
                },
                onConsoleMessage: (InAppWebViewController controller,
                    ConsoleMessage consoleMessage) {
                  print("""
                              console output:

                                message: ${consoleMessage.message}
                                messageLevel: ${consoleMessage.messageLevel}
                              """);
                }, //fires when browser receives console message
              ),
            ),
          ),
          ButtonBar(
            alignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Icon(Icons.arrow_back),
                onPressed: () {
                  if (webView != null) {
                    webView.goBack();
                  }
                },
              ),
              RaisedButton(
                child: Icon(Icons.arrow_forward),
                onPressed: () {
                  if (webView != null) {
                    webView.goForward();
                  }
                },
              ),
              RaisedButton(
                child: Icon(Icons.refresh),
                onPressed: () {
                  if (webView != null) {
                    webView.reload();
                  }
                },
              ),
            ],
          ),
        ])),
      ),
    );
  }
}

**Comment by pichillilorenzo** [comment]
@ositano that's because it is not `window.flutter_inappbrowser`, but it needs to be `window.flutter_inappwebview`

**Comment by OPY-bbt** [comment]
`flutter_inappwebview._callHandler`  resolve my problem.

**Comment by OPY-bbt** [comment]
#204

**Comment by ositano** [comment]
> @ositano that's because it is not `window.flutter_inappbrowser`, but it needs to be `window.flutter_inappwebview`

@pichillilorenzo thank you, I have changed it as you pointed, but now **it crashes the app**. I am running on iOS simulator. When i tried running using _callHandler as mentioned on the issue @OPY-bbt referenced  I get **TypeError: window.flutter_inappwebview._callHandler is not a function**

**Comment by pichillilorenzo** [comment]
`_callHandler` should not be used because it is a "private API" that I use to manage javascript handlers. `callHandler` is the public one that you need to use. I need to debug it more.

**Comment by pichillilorenzo** [comment]
@ositano please post the error log you get! For iOS, open launch your app with Xcode and take the logs from it

**Comment by ositano** [comment]
<img width="1440" alt="Screenshot 2019-12-13 at 9 01 03 AM" src="https://user-images.githubusercontent.com/50879868/70782538-7f321300-1d87-11ea-935e-507ef6d4d931.png">


@pichillilorenzo i was unable to run from xcode

**Comment by pichillilorenzo** [comment]
@ositano thats because you are using an Xcode version below 11. This plugin, as written in the Requirements section of the README.md file and in the official documantation, requires Xcode >= 11. Just update Xcode and it should work.

**Comment by ositano** [comment]
@pichillilorenzo see this 
<img width="1440" alt="Screenshot 2019-12-13 at 11 55 58 AM" src="https://user-images.githubusercontent.com/50879868/70795215-9977eb00-1d9f-11ea-8861-e5e02071f016.png">

**Comment by OPY-bbt** [comment]
@ositano  Please create a new issue. Don't ask questions that are irrelevant to the title

**Comment by koteezy** [comment]
```flutterInAppWebViewPlatformReady``` - is never called, my js:

```
console.log("JS injected");

window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
    console.log("flutterInAppWebViewPlatformReady is ready!");

    const tracks = [1,2,3,4];

    window.flutter_inappwebview.callHandler('tracks', JSON.stringify({ tracks: tracks }));
  });
```
![Browser console](https://user-images.githubusercontent.com/38183600/70988422-e24adf00-20d2-11ea-94f8-99c6bc88a95a.png)

**Comment by shaiful-hisham** [comment]
I also have the same issue in Android, but in iOS it working fine. Do we have any workaround yet?

**Comment by eryanwcp** [comment]
it's not working in Android 9-，but  in Android 10 and iOS it working fine.

**Comment by koteezy** [comment]
Any news?

**Comment by fuiyu** [comment]
Looking for help for this problem

**Comment by a4081675** [comment]
求解决。。。官方不支持选择文件，这个还有不少bug。心好累。。。。

**Comment by a4081675** [comment]
String js = InAppWebView.consoleLogJS.replaceAll("[\r\n]+", "");
    js += JavaScriptBridgeInterface.flutterInAppBroserJSClass.replaceAll("[\r\n]+", "");
    if (webView.options.useShouldInterceptAjaxRequest) {
      js += InAppWebView.interceptAjaxRequestsJS.replaceAll("[\r\n]+", "");
    }
    if (webView.options.useShouldInterceptFetchRequest) {
      js += InAppWebView.interceptFetchRequestsJS.replaceAll("[\r\n]+", "");
    }
    if (webView.options.useOnLoadResource) {
      js += InAppWebView.resourceObserverJS.replaceAll("[\r\n]+", "");
    }
    js += InAppWebView.printJS.replaceAll("[\r\n]+", "");

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      webView.evaluateJavascript(js, (ValueCallback<String>) null);
    } else {
      webView.loadUrl("javascript:" + js);
    }

换到onPageFinished里面就好使了

**Comment by hisaichi5518** [comment]
my workaround:
```js
const message = "value";
if (window.flutter_inappwebview.callHandler) {
  window.flutter_inappwebview.callHandler('handlerName', message);
} else {
   window.flutter_inappwebview._callHandler('handlerName', setTimeout(function(){}), JSON.stringify([message]));
}
```

**Comment by asjqkkkk** [comment]
I have the same issue.
and console logs:
```
Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
```
Maybe this is the problem

**Comment by hisaichi5518** [comment]
The cause of this issue is that only onPageStarted callback sets callHandler JS.
If you set the callHandler JS in onPageFinished, no problem will occur.

```diff
diff --git a/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/InAppWebView/InAppWebViewClient.java b/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/InAppWebView/InAppWebViewClient.java
index 84ad883..3276175 100644
--- a/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/InAppWebView/InAppWebViewClient.java
+++ b/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/InAppWebView/InAppWebViewClient.java
@@ -223,7 +223,8 @@ public class InAppWebViewClient extends WebViewClient {
     view.clearFocus();
     view.requestFocus();

-    String js = InAppWebView.platformReadyJS.replaceAll("[\r\n]+", "");
+    String js = JavaScriptBridgeInterface.flutterInAppBroserJSClass.replaceAll("[\r\n]+", "");
+    js += InAppWebView.platformReadyJS.replaceAll("[\r\n]+", "");

     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
       webView.evaluateJavascript(js, (ValueCallback<String>) null);
```

**Comment by mrcrixx** [comment]
I have tried everything but I'm still stucked on the original problem: callHandler is not a function...

on Dart side I use this that should inject the handler

  onWebViewCreated: (InAppWebViewController controller) {
                  webView = controller;
                  webView.addJavaScriptHandler(
                      handlerName: "mySum",
                      callback: (args) {
                        // Here you receive all the arguments from the JavaScript side
                        // that is a List<dynamic>
                        print("From the JavaScript side:");
                        print(args);
                        return args.reduce((curr, next) => curr + next);
                      });
              
                },

on HTML side I use this and I get the error:

<html>
	<head></head>
	<body>


        <script>
           // In order to call window.flutter_inappwebview.callHandler(handlerName <String>, ...args) 
           // properly, you need to wait and listen the JavaScript event flutterInAppWebViewPlatformReady. 
           // This event will be dispatched as soon as the platform (Android or iOS) is ready to handle the callHandler method. 
            window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
           console.log('Here I am, I get this message');
          
					             // call flutter handler with name 'mySum' and pass one or more arguments
					             window.flutter_inappwebview.callHandler('mySum', 12, 2, 50).then(function(result) {
					               // get result from Flutter side. It will be the number 64.
					               console.log(result);
					             });
           	
           });
        </script>
<h1>Just an example</h1>
	</body>
</html>

Any idea?

**Comment by taej0127** [comment]
anyone solved this?

**Comment by WangPe1n** [comment]
I solved this issue by adding these code in `onLoadStop` method:
```dart

...
String _js = '''
  if (!window.flutter_inappwebview.callHandler) {
      window.flutter_inappwebview.callHandler = function () {
          var _callHandlerID = setTimeout(function () { });
          window.flutter_inappwebview._callHandler(arguments[0], _callHandlerID, JSON.stringify(Array.prototype.slice.call(arguments, 1)));
          return new Promise(function (resolve, reject) {
              window.flutter_inappwebview[_callHandlerID] = resolve;
          });
      };
  }
  ''';
...

InAppWebView(
...
  onWebViewCreated: (controller) {
    controller.addJavaScriptHandler(
      ...
    );
  },
  onLoadStop: (controller, url) {
    controller.evaluateJavascript(source: _js);
  },
...
);
```
hope this help. 😁

**Comment by WangPe1n** [comment]
> anyone solved this?

look here

**Comment by JanusKun** [comment]
how can i solve it? head big

**Comment by Clean-Cole** [comment]
Confirmed @WangPe1n 's fix did the trick.

**Comment by checkblue** [comment]
@WangPe1n Your code is valid！！！

**Comment by rajashah33** [comment]
@WangPe1n  workaround not working. I'm still getting the same error

**Comment by DRL9** [comment]
@WangPe1n `window.flutter_inappwebview.callHandler is not a function` is solved. However, `addJavaScriptHandler`'s `callback` isn't invoked as calling `window.flutter_inappwebview.callHandler` in Android 7. All is right in Android 10.

**Comment by DRL9** [comment]
> @WangPe1n workaround not working. I'm still getting the same error

Copy that js fragment to `js` file can resolve it.

**Comment by cijianzy** [comment]
@WangPe1n you save me!!!

**Comment by pichillilorenzo** [comment]
@cijianzy it should already work with the latest version without any workaround

**Comment by kiwiidb** [comment]
I am using 
- version  ^5.3.2 
- classpath 'com.android.tools.build:gradle:3.5.4' 

```android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```
and I only got the callback it to work when using @WangPe1n 's workaround. Worked on ios but did not work on android except with this workaround.

**Comment by pichillilorenzo** [comment]
@kiwiidb if you have problems, please post a new issue with a code example to be able to reproduce that behavior. It should already work with version 5+.
Using that workaround could not work on future versions. It is something "private" and it could change at any time. So, open a new issue and post your problem there with all the info.

**Comment by mohammedX6** [comment]
@pichillilorenzo in version 5.7.2+3 it's not working

**Comment by maxmitz** [comment]
This bug still occurs for me. I'm going to post a new issue in the next few days.

**Comment by codemobiles** [comment]
You can use this code to prevent the crash error in the javascript level. I add try-catch to prevent the crash and allow flutter handle the exception itself.

`String _js = '''
      (function() {
        try {
        return $fullMethodSignature;        
      } catch (e) {
        return "failed";
      }
      })();
  ''';
  
  result = await webController.evaluateJavascript(source: _js) ?? "failed";
  `
