### ISSUE TITLE
Execution failed for task ':flutter_inappwebview_android:minifyReleaseWithR8'.

### ISSUE THREAD

**Issue by LScodeblack** [pichillilorenzo/flutter_inappwebview#2193]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |               |
| Plugin version        |               |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by ChrisElliotUK** [comment]
```
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in ./build/flutter_inappwebview_android/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class android.window.BackEvent (referenced from: void io.flutter.embedding.android.FlutterActivity.startBackGesture(android.window.BackEvent) and 3 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_inappwebview_android:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
```

**Comment by mynlexi** [comment]
Exact same problem here

**Comment by Igor-Pavlyshyn** [comment]
Also i have this problem

**Comment by marvinJ10** [comment]
Also i have this problem

**Comment by guiwestrup** [comment]
Same here.

**Comment by chplalex** [comment]
Me too

**Comment by agarwalrohit2503** [comment]
Me too

**Comment by ritzqureshi** [comment]
dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057 ..... it works for me

**Comment by DurgeshSawantWYLD** [comment]
same error here, please provide a fix

**Comment by ritzqureshi** [comment]
@DurgeshSawantWYLD please provide the error with screenshot

**Comment by Eng-Yuri89** [comment]
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in ./build/flutter_inappwebview_android/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class android.window.BackEvent (referenced from: void io.flutter.embedding.android.FlutterActivity.startBackGesture(android.window.BackEvent) and 3 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_inappwebview_android:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s

**Comment by ritzqureshi** [comment]
@DurgeshSawantWYLD please provide the pubspec.yaml

**Comment by bibek-ranjan-saha** [comment]
Same issue, Please fix it

**Comment by ritzqureshi** [comment]
@DurgeshSawantWYLD please provide the pubspec.yaml file ss show meor you can add this line after dependencies dependency_overrides:
flutter_inappwebview_android:
git:
url: https://github.com/holzgeist/flutter_inappwebview
path: flutter_inappwebview_android
ref: https://github.com/pichillilorenzo/flutter_inappwebview/commit/d89b1d32638b49dfc58c4b7c84153be0c269d057

**Comment by chplalex** [comment]
It resolves the issue. Thank you @ChrisElliotUK 

> I got around this by adding flutter_inappwebview_android to the `dependency_overrides`
> 
> ```
> dependency_overrides:
>   flutter_inappwebview_android:
>     git:
>       url: https://github.com/holzgeist/flutter_inappwebview
>       path: flutter_inappwebview_android
>       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
> ```

**Comment by JoseBarreto1** [comment]
Me too

**Comment by euferreira** [comment]
Same error

**Comment by ZunairImtiaz08** [comment]
Me too facing same issue

**Comment by JoseBarreto1** [comment]
I created a temporary package until this problem is resolved here.
Maybe it will help some people:
[](https://pub.dev/packages/webview_inapp)

**Comment by plchekspend** [comment]
any update @pichillilorenzo ? this issue still persistence in flutter SDK 3.22.3. Please solve this issue and release a new version. Thanks.

**Comment by MakSinroja** [comment]
Facing the same issue. 

FYI - @pichillilorenzo

**Comment by Den-creator** [comment]
Same issue on Flutter 3.24.1

**Comment by yelkamel** [comment]
same here

**Comment by plchekspend** [comment]
After January author maybe inactive since today. What should we do?

**Comment by HachichaRacem** [comment]
> I am facing this issue too. But this fixed it for now. I hope the owner releases an update soon.
> 
> > I got around this by adding flutter_inappwebview_android to the `dependency_overrides`
> > ```
> > dependency_overrides:
> >   flutter_inappwebview_android:
> >     git:
> >       url: https://github.com/holzgeist/flutter_inappwebview
> >       path: flutter_inappwebview_android
> >       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
> > ```

This worked, hopefully the issue gets fixed soon

**Comment by abdifatahmuse** [comment]
I had the same issue, and I `solved` this `issue` after downgrading the `com.android.application` from `8.1.0` to `7.3.0`
also added the `proguard-rules` in side the 

after changes it works the build release
```gradle
    buildTypes {
        release { 
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
from

```gradle
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.1.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}
```

to

```gradle
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}
```

**Comment by monisnap-jeremie** [comment]
The following fix worked for me:

```
dependency_overrides:
  flutter_inappwebview_android: 1.0.13
```

It avoids to fork the main repo.

**Comment by pichillilorenzo** [comment]
Released new `flutter_inappwebview_android` version `1.1.0+1` with the fix. You can run `flutter pub upgrade`.

**Comment by CodeWithJeet1204** [comment]
> d89b1d32638b49dfc58c4b7c84153be0c269d057

In which file?
Pubspec.yaml ??
