### ISSUE TITLE
D/InAppWebView( 9850): Using InAppWebViewClientCompat implementation

### ISSUE THREAD

**Issue by nischalpandey** [pichillilorenzo/flutter_inappwebview#2196]
I am using
 [flutter_inappwebview: ^6.0.0 ]
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.1.2" apply false
    id "com.google.gms.google-services" version "4.3.10" apply false
    id "org.jetbrains.kotlin.android" version "1.8.0" apply false
}

android {
    compileSdkVersion flutter.compileSdkVersion=34
    ndkVersion flutter.ndkVersion
    defaultConfig {
        multiDexEnabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.mmmm.ccc"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion flutter.minSdkVersion=21
        targetSdkVersion flutter.targetSdkVersion=34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
......
Slow Binder: BpBinder transact took 262 ms, interface=android.app.IActivityTaskManager, code=41 oneway=false
2
E/libc    ( 9850): Access denied finding property "ro.vendor.pref_scale_resolution"
D/EgretLoader( 9850): EgretLoader(Context context)
D/EgretLoader( 9850): The context is not activity
D/InAppWebView( 9850): Using InAppWebViewClientCompat implementation
W/cr_WebSettings( 9850): setForceDark() is a no-op in an app with targetSdkVersion>=T
W/cr_SupportWebSettings( 9850): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views( 9850): Failed to handle method call
E/MethodChannel#flutter/platform_views( 9850): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views( 9850): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/MethodChannel#flutter/platform_views( 9850): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/MethodChannel#flutter/platform_views( 9850): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/MethodChannel#flutter/platform_views( 9850): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:434)
E/MethodChannel#flutter/platform_views( 9850): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views( 9850): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:527)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:169)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views( 9850): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 9850): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views( 9850): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 9850): 	at android.os.Looper.loop(Looper.java:236)
E/MethodChannel#flutter/platform_views( 9850): 	at android.app.ActivityThread.main(ActivityThread.java:8097
E/MethodChannel#flutter/platform_views( 9850): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/flutter ( 9850): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter ( 9850): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter ( 9850): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter ( 9850): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter ( 9850): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:434)
E/flutter ( 9850): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter ( 9850): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter ( 9850): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:527)
E/flutter ( 9850): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:169)
E/flutter ( 9850): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter ( 9850): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlE/flutter ( 9850): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9850): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/flutter ( 9850): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/flutter ( 9850): )
E/flutter ( 9850): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 9850): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 9850): <asynchronous suspension>
E/flutter ( 9850): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1115:5)
E/flutter ( 9850): <asynchronous suspension>
E/flutter ( 9850): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:838:5)
E/flutter ( 9850): <asynchronous suspension>
E/flutter ( 9850): 
D/DecorView[]( 9850): getWindowModeFromSystem  windowmode is 1

**Comment by pdax-king** [comment]
Hi @nischalpandey how did you solve this issue? Thanks in advance!

**Comment by pdax-king** [comment]
I was able to resolve by downgrading the `webview_flutter_android` to 3.16.1.
