### ISSUE TITLE
Cant get cookie IOS

### ISSUE THREAD

**Issue by vawaysinhthanh** [pichillilorenzo/flutter_inappwebview#221]
## Environment

**Flutter version:**  1.9.6
**Plugin version:**    
**Android version:**    
**iOS version:** 11.1
**Xcode version:**  
**Device information:**    

## Description
InAppWebView(
              initialUrl: _webviewUrl,
              initialOptions: InAppWebViewWidgetOptions(
                  iosInAppWebViewOptions: IosInAppWebViewOptions(
                    sharedCookiesEnabled: true,
                  ),
                  inAppWebViewOptions: InAppWebViewOptions(
                    debuggingEnabled: true,
                  )),
              onWebViewCreated: (InAppWebViewController controller) {
                _webView = controller;
              },
              onLoadStart: (InAppWebViewController controller, String url) {
                getCookies();
                setState(() {
                  _webviewUrl = url;
                });
                webViewURLChange();
              },
              onLoadError: (InAppWebViewController controller, String url,
                  int code, String message) {
                Navigator.of(context).pop(null);
              },
              onLoadStop: (InAppWebViewController controller, String url) {
                getCookies();
              },
              onProgressChanged:
                  (InAppWebViewController controller, int progress) {
                setState(() {
                  _progress = progress / 100;
                });

                //if (_progress == 1.0) {
                webviewUpdate();
                //}
              },
            ),
            (_isShow == false
                ? Positioned.fill(
                    child: Container(
                      color: Colors.white,
                      alignment: Alignment.center,
                      child: Func.loading(),
                    ),
                  )
                : Container()),
          ]

void getCookies() async {
    var cookies = await CookieManager.instance().getCookie(url : 'https://facebook.com/', name: 'c_user');
    print(cookies);
    //checkLogin();
    
  }

but not print cookie
**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by wwwdata** [comment]
I also have this error and I could trace down the problem. It seems that when the cookies are read out, the code always tries to compare the URL with the cookie domain. But unfortunately, the domain field is optional. So it will be nil sometimes and that makes the code crash.

The affected lines of code are here:
`Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value`
https://github.com/pichillilorenzo/flutter_inappwebview/blob/9c7ac0da8f01ceb40430da58397bdb31968ca5b1/ios/Classes/MyCookieManager.swift#L105-L109
