### ISSUE TITLE
[Windows] InPrivate Mode missing

### ISSUE THREAD

**Issue by selvam920** [pichillilorenzo/flutter_inappwebview#2230]
Please enable inprivate mode for the windows webview

https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controlleroptions?view=webview2-dotnet-1.0.1518.46

**Comment by selvam920** [comment]
can you update this option?

**Comment by pichillilorenzo** [comment]
Released new flutter_inappwebview_windows version 0.4.1 with `InAppWebViewSettings.incognito` support for Windows
