### ISSUE TITLE
webview can not be released when in ios

### ISSUE THREAD

**Issue by ber6789** [pichillilorenzo/flutter_inappwebview#225]
**flutter:  latest version
ios: 12+
flutter_inappwebview: latest version**

In the latest  version (same as the old version) ,  the webviews that  this plugin created in ios app, would  never be released after the page is disposed , but in Android , it is ok.  

![image](https://user-images.githubusercontent.com/5801271/70840846-4ad65980-1e50-11ea-99d2-806067f18ce7.png)

###  **I have noticed that you have created one method  which intended to dispose webviews**
(  
     looks like this: 

```
  Future<void> dispose() async {
     Map<String, dynamic> args = <String, dynamic>{};
     if (Platform.isIOS){
      await _channel.invokeMethod('removeFromSuperview', args);
    }
  }
```

) ,but it seems not work properly when I use it , here are the steps and what happens:
(suppose  **webview** is the instance of **InAppWebViewController**)

1、 call **webview.dispose()**  and at the same time  not leave this page
(just because if I leave this page at the same time, the dispose will not even work)

2、the app will Lost connect then crash in a moment

### _**And by the way  ,  If  I just give it up , and not try to dispose these webviews, would they make a great influence on the performance on my ios app?**_

Sincerely,
forgive my poor English Expression ，and much heartfelt thanks for Looking into my issue

**Comment by ber6789** [comment]
I am just nearly breakdown on this issue ,  and my project will may not reach Acceptance due to this problem , is there anyone to help me? 
在这个问题上，我已经崩溃很久了，项目也因为这个问题无法验收，要哭死了，有人可以帮忙解决下？

**Comment by pichillilorenzo** [comment]
I tried to remove the webview on iOS but I can't get it work. I don't know why but, also, if I remove all the references, the webview seems to still there (maybe there are some references that I can't get off).

> I am just nearly breakdown on this issue , and my project will may not reach Acceptance due to this problem , is there anyone to help me?

Do you mean that the AppStore is rejecting your app? What they say?

**Comment by pichillilorenzo** [comment]
@ber6789 Also, if you use the official flutter plugin `webview_flutter`, do you get the same result? Or the webview is correctly disposed from memory?

**Comment by pichillilorenzo** [comment]
@ber6789 Ok I have finally found what was the problem! The fix will be available in the next release that is coming really soon! The iOS WebView will be released automatically like happens now for Android. Thanks a lot for the support!

**Comment by ber6789** [comment]
> @ber6789 Ok I have finally found what was the problem! The fix will be available in the next release that is coming really soon! The iOS WebView will be released automatically like happens now for Android. Thanks a lot for the support!

thanks very very much , I was busy last two days,  so I saw your reply just now,   you are really my savior !!  I love u so much , please accept my knees~, I am  expecting your new version,,,  you are really great man ~
