### ISSUE TITLE
Android 15 disable `getDatabaseEnabled` method

### ISSUE THREAD

**Issue by ShuheiSuzuki-07** [pichillilorenzo/flutter_inappwebview#2259]
The following description of Android 15 says that `getDatabaseEnabled`, which this plugin uses, will become unavailable within 12 months.

Does that mean that if this plugin is not fixed, webviews that use it will stop working within 12 months?

https://developer.android.com/about/versions/15/deprecations?hl=ja#websql-webview

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/561a92bf-eddf-4b28-9278-746c753bb6c0">

**Comment by ShuheiSuzuki-07** [comment]
Can somebody please answer?

**Comment by ShuheiSuzuki-07** [comment]
Does anyone have any opinions on this matter?

**Comment by pichillilorenzo** [comment]
English ref: https://developer.android.com/about/versions/15/deprecations?hl=en#websql-webview

They will not remove the method, it will be just a method no-op, that means it will do nothing.

> These methods will become a no-op on all Android versions in the next 12 months.

You won’t have build errors or whatever.
