### ISSUE TITLE
This package is no longer being maintained; someone should make a '_plus' version of it.

### ISSUE THREAD

**Issue by stan-at-work** [pichillilorenzo/flutter_inappwebview#2268]
This package is no longer beeing maintaned, someone should make a _plus version of it.

**Comment by stan-at-work** [comment]
There are 41 pull request open ATM and 1.1K issues... @pichillilorenzo it looks like you just don't care anymore

**Comment by Doflatango** [comment]
You can pay @pichillilorenzo to work for you, or make your own plus version by your self.

**Comment by ZoftPranav** [comment]
what a downfall for the package

**Comment by pichillilorenzo** [comment]
Sorry guys, I would like to continue with the project and I think I will but I don't know when exactly, probably as early as this month.
Being a free and open-source project and also that lately I had lost the desire, after a day of work I simply wanted to relax or do something else (my hobbies).
I am very proud of this project and that it is used by many people at work. I use it myself in my work and, for what I need to do, I have no problems and I can publish applications on the Apple and Android stores.
I hope to get back to it as soon as possible, thanks everyone.

**Comment by adamk22** [comment]
@pichillilorenzo the fact an issue like this pops up says a lot about how valuable your open source efforts means to the community. Glad to see you posted na update!

**Comment by arrrrny** [comment]
@stan-at-work now there is. [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview)

**Comment by p-mazhnik** [comment]
@arrrrny why did you drop all of the existing commits in your repo?

**Comment by arrrrny** [comment]
@stan-at-work I created a fork of this project and published a new package with the fixes of hot issues of js version update and xcode build error everyone having upgrading to Xcode 16.   [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview)

**Comment by pichillilorenzo** [comment]
I'm back. I need to update some other things and check some pull requests and then I'm going to release the new 6.1.0 version.
Thanks for the support!

**Comment by arrrrny** [comment]
@p-mazhnik thx for pointing out. It was a moment of rush to publish the package. I corrected the git base. It has all the history now  as it should.
