### ISSUE TITLE
Task :flutter_inappwebview:syncReleaseLibJars FAILED

### ISSUE THREAD

**Issue by Alihassan20** [pichillilorenzo/flutter_inappwebview#2280]
I face this error and I haven't found any solution 

after upgrading Flutter to the latest version this appears in release mode but in debug mode, it runs correctly 

this happen in android version not iOS version
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':flutter_inappwebview:syncReleaseLibJars' (type 'LibraryAarJarsTask').
  - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.tasks.LibraryAarJarsTask' property 'javaResourcesJar' specifies file 'myPth/build/flutter_inappwebview/intermediates/merged_java_res/release/minifyReleaseWithR8/feature-flutter_inappwebview.jar' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.

**Comment by Alihassan20** [comment]
upgrade flutter_inappwebview to the last version 6.0.0
and upgrade Gradle 
will fix this bug

**Comment by florianramaj** [comment]
doesnt work for me, still getting this error message
