### ISSUE TITLE
Why is there no support for the Windows platform?

### ISSUE THREAD

**Issue by istaru** [pichillilorenzo/flutter_inappwebview#2282]
## Environment

**Flutter version:3.24.1

**Plugin version:6.0.0

**Android version: (developed on Windows 11)

**IOS version: none (developed on Windows 11)

**Xcode version:none

**Device information:none

## Description

Because Windows development also has cross domain issues that need to be resolved, we hope to support the Windows platform. Thank you very much

**Comment by pichillilorenzo** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/issues/460
