### ISSUE TITLE
Xcode, IOS issue FIXED on NEW package,maintainer => search pub.dev  ZIKZAK_INAPPVIEW

### ISSUE THREAD

**Issue by arrrrny** [pichillilorenzo/flutter_inappwebview#2284]
My new package [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview) fork of this package that I will keep maintaining. Thanks @pichillilorenzo for developing/maintaining this package for a long time. I guess he is busy or on vacataion. I am the builder of [Flutter Vendure ](https://pub.dev/packages/vendure)(open source headless commerce framework) package. [Vendure](https://vendure.io/) Please open your PRs [here](https://github.com/arrrrny/zikzak_inappwebview) and I am happy to check them and merge them by Monday.

**Comment by pichillilorenzo** [comment]
Please, stop spamming

**Comment by arrrrny** [comment]
> Please, stop spamming

good to hear that you are back. It worked.
