### ISSUE TITLE
[ChromeSafariBrowser] Force open Chrome (or browser that supports CustomTab) in Android

### ISSUE THREAD

**Issue by skybur** [pichillilorenzo/flutter_inappwebview#229]
My App handles intent-filter for deeplinking. 
When I use the ChromeSafariBrowser to open a URL, the custom tab didn't open directly but showing the App Picker instead (like in the screenshot below)
![image](https://user-images.githubusercontent.com/11155424/70969176-d872ad00-20cd-11ea-85f9-5d59edc1b95a.png)

This is a problem because the URL I want to open is not handled by the app itself, and need to be opened in custom tab

Is there any way to force the custom tab open without showing the app picker?

flutter_inappwebview version 2.1.0+1

**Comment by pichillilorenzo** [comment]
Ok, I'm going to add this in the next release! Thanks

**Comment by skybur** [comment]
Thank you! Looking forward to it
