### ISSUE TITLE
Cannot invoke "String.length()" because "<parameter1>" is null

### ISSUE THREAD

**Issue by DimaOstrovskyiEk** [pichillilorenzo/flutter_inappwebview#2290]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |   3.24.3      |
| Plugin version        |   6.0.1+1     |
| Android version       |   API 35      |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat   
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDevDebug'...
Extracting release keystore config from keystore/key.properties
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ERROR:/Users/**********/.gradle/caches/transforms-3/4a35429d33794c7684685deada7a90f5/transformed/jetified-appcompat-resources-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
ERROR:/Users/**********/.gradle/caches/transforms-3/9fec11510cfb3d71c4bd04d0ae3e8b90/transformed/appcompat-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeExtDexDevDebug'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=29, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/*********/.gradle/caches/transforms-3/4a35429d33794c7684685deada7a90f5/transformed/jetified-appcompat-resources-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=29, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/**********/.gradle/caches/transforms-3/9fec11510cfb3d71c4bd04d0ae3e8b90/transformed/appcompat-1.7.0-runtime.jar.
         > Error while dexing.

BUILD FAILED in 33s
Error: Gradle task assembleDevDebug failed with exit code 1

**Comment by hann-yun** [comment]
same here!

**Comment by ShareZore** [comment]
Is there any way？

**Comment by chungxon** [comment]
You can downgrade `flutter_inappwebview_android` library to fix this problem

```yaml
dependency_overrides:
  # Workaround to fix build android issue
  flutter_inappwebview_android: 1.0.13
```

**Comment by pichillilorenzo** [comment]
You should be able to upgrade Android AGP version. Check the android example files:
- [android/settings.gradle](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/flutter_inappwebview/example/android/settings.gradle)
- [android/gradle/wrapper/gradle-wrapper.properties](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/flutter_inappwebview/example/android/gradle/wrapper/gradle-wrapper.properties)

**Comment by fabegalo** [comment]
Not all Flutter projects will be able to run on AGP 8.0+ due to potential compatibility issues with dependencies. Some projects may need to stick with earlier AGP versions for stable builds.

**Comment by monisnap-jeremie** [comment]
> You can downgrade `flutter_inappwebview_android` library to fix this problem
> 
> ```yaml
> dependency_overrides:
>   # Workaround to fix build android issue
>   flutter_inappwebview_android: 1.0.13
> ```

I can confirm that it fix this issue ✅

**Comment by fabegalo** [comment]
> > You can downgrade `flutter_inappwebview_android` library to fix this problem
> > ```yaml
> > dependency_overrides:
> >   flutter_inappwebview_android: 1.0.13
> > ```
> 
> I can confirm that it fix this issue ✅

Yes it works, but in my case I'm currently facing compatibility issues when using youtube_player_flutter. On Android, I need to use version 8.1.2 for everything to work correctly. However, on iOS 16, it's mandatory to use version 6.1.0 of flutter_inappwebview, and youtube_player_flutter version 8.1.2 doesn't support this version of flutter_inappwebview. On the other hand, versions 9.x+ of youtube_player_flutter do not work properly on Android, especially regarding video playback. To maintain functionality on both platforms (iOS and Android), I had to keep two separate branches for the time being.

**Comment by pichillilorenzo** [comment]
Released new `flutter_inappwebview_android` version `1.1.0+1` with the fix. You can run `flutter pub upgrade`.

**Comment by guilherme-cdl** [comment]
> You can downgrade `flutter_inappwebview_android` library to fix this problem
> 
> ```yaml
> dependency_overrides:
>   # Workaround to fix build android issue
>   flutter_inappwebview_android: 1.0.13
> ```

same here, fixed with this

**Comment by pichillilorenzo** [comment]
@guilherme-cdl flutter_inappwebview_android version 1.1.0+1 should already fixed it downgrading the appcompat to the same version of flutter_inappwebview_android: 1.0.13. So, you can run flutter pub upgrade to upgrade the flutter_inappwebview dependencies.

**Comment by bhavnagupta24** [comment]
> You can downgrade `flutter_inappwebview_android` library to fix this problem
> 
> ```yaml
> dependency_overrides:
>   # Workaround to fix build android issue
>   flutter_inappwebview_android: 1.0.13
> ```

Same worked for me.
