### ISSUE TITLE
jetified-appcompat-resources-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length() Error happened after updating new version

### ISSUE THREAD

**Issue by ijascookee** [pichillilorenzo/flutter_inappwebview#2297]
## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |         3.24.1      |
| Plugin version        |       6.1.0+1       |

ERROR:/Users/Apple/.gradle/caches/transforms-3/772418b938aa555c88328e65887df653/transformed/jetified-appcompat-resources-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "" is null

ERROR:/Users/Apple/.gradle/caches/transforms-3/6f430dba7a9d0caec54877b72ee5cd99/transformed/appcompat-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "" is null

This error happened while running application after new update 

Tried overriding flutter_inappweview_android package with older version, 
```
dependency_overrides:
  flutter_inappwebview_android: 1.0.13
```

then this error gone and app runs but some functionalities not working like in [youtube_player_flutter](https://github.com/sarbagyastha/youtube_player_flutter)  package.  Also i have checked this player's source code to ensure it is using latest flutter_inappwebview package.

The folllowing exception also showing i am not sure about this is related to [youtube_player_flutter](https://github.com/sarbagyastha/youtube_player_flutter) package or flutter_inappwebview package

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE

**Comment by sagarZodage** [comment]
I have facing same problem , after added below code its working fine . @ijascookee ijascookee Thank you so much.
Ijas Hussain

dependency_overrides:
  flutter_inappwebview_android: 1.0.13

**Comment by ZoftPranav** [comment]
any fix for this ?

**Comment by sagarZodage** [comment]
Not Yet . @ZoftPranav Please let me know if anyone find any solution

**Comment by pichillilorenzo** [comment]
I will try to downgrade to the previous version for the Android native appcompat dependency.

**Comment by sagarZodage** [comment]
I have also tried but not working below version I am currently working . 

        **_'androidx.appcompat:appcompat:1.3.1'_**

**Comment by pichillilorenzo** [comment]
@sagarZodage which version of Flutter are you using? 1.3.1 seems to be pretty old (check https://mvnrepository.com/artifact/androidx.appcompat/appcompat).
The previous version used by the plugin was 1.6.0

**Comment by sagarZodage** [comment]
Also tried with 'androidx.appcompat:appcompat:1.7.0' version not working

**Comment by pichillilorenzo** [comment]
@sagarZodage 1.7.0 is the current version, have you tried with 1.6.0? It’s the version used by flutter_inappwebview 6.0.0

**Comment by adityapatil18** [comment]
> @sagarZodage which version of Flutter are you using? androidx.appcompat 1.3.1 seems to be pretty old (check https://mvnrepository.com/artifact/androidx.appcompat/appcompat). The previous version used by the plugin was 1.6.0

I have also tried but not working . Its not the androidx.appcompat issue this issue is occuring becasue of the unstable flutter_inappwebview. and I used this 
dependency_overrides:
  flutter_inappwebview_android: 1.0.13
  still its causing the same issue.

**Comment by pichillilorenzo** [comment]
Have you tried to upgrade the Android gradle version? Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/2290#issuecomment-2370411857

**Comment by ijascookee** [comment]
> Have you tried to upgrade the Android gradle version? Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/2290#issuecomment-2370411857

Yes, tried... flutter_inappwebview_android is using old appCompact version

**Comment by pichillilorenzo** [comment]
Released new `flutter_inappwebview_android` version `1.1.0+1` with the fix. You can run `flutter pub upgrade`.

**Comment by ijascookee** [comment]
@pichillilorenzo 
Thank you, But, There is another issue, I don't know is it related to the package or not could you please help me to identify what it the following error means. In this error log, error is coming from the package.

```
W/cr_SupportWebSettings( 6167): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views( 6167): Failed to handle method call
E/MethodChannel#flutter/platform_views( 6167): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views( 6167): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/MethodChannel#flutter/platform_views( 6167): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/MethodChannel#flutter/platform_views( 6167): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/MethodChannel#flutter/platform_views( 6167): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#flutter/platform_views( 6167): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views( 6167): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views( 6167): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 6167): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter/platform_views( 6167): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 6167): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter/platform_views( 6167): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#flutter/platform_views( 6167): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#flutter/platform_views( 6167): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 6167): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#flutter/platform_views( 6167): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 
```
.

```
E/flutter ( 6167): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter ( 6167): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter ( 6167): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter ( 6167): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter ( 6167): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter ( 6167): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter ( 6167): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter ( 6167): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/flutter ( 6167): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/flutter ( 6167): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter ( 6167): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 6167): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 6167): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 6167): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 6167): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 6167): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter ( 6167): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 6167): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter ( 6167): 	at android.os.Looper.loop(Looper.java:294)
E/flutter ( 6167): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/flutter ( 6167): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6167): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter ( 6167): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter ( 6167): )
E/flutter ( 6167): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 6167): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 6167): <asynchronous suspension>
E/flutter ( 6167): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1104:5)
E/flutter ( 6167): <asynchronous suspension>
E/flutter ( 6167): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:827:5)
E/flutter ( 6167): <asynchronous suspension>
E/flutter ( 6167): 
```

**Comment by pichillilorenzo** [comment]
The SUPPRESS_ERROR_PAGE unsupported feature has been already removed on the new plugin version, so use flutter_inappwebview 6.1.0.
If you are already using 6.1.0, run flutter pub upgrade

**Comment by ijascookee** [comment]
> The SUPPRESS_ERROR_PAGE unsupported feature has been already removed on the new plugin version, so use flutter_inappwebview 6.1.0. If you are already using 6.1.0, run flutter pub upgrade

Thanks now its working fine😍

**Comment by sagarZodage** [comment]
I am currently trying to upload a new build to the Google Play Store and have encountered the following issue.

<img width="1004" alt="Screenshot 2024-09-26 at 12 38 34 PM" src="https://github.com/user-attachments/assets/14873a19-082f-4f55-a88d-a85a849a2290">

**Comment by pichillilorenzo** [comment]
@sagarZodage I don’t know what is your `zc.b$b.onReceive`. You should check your native code or other dependencies.

**Comment by JeffTyfoom** [comment]
> tter_inappwebview 6.1.0

Thanks it's working!

**Comment by JeffTyfoom** [comment]
> Released new `flutter_inappwebview_android` version `1.1.0+1` with the fix. You can run `flutter pub upgrade`.

Thanks it's working!
