### ISSUE TITLE
DartError: UnimplementedError: addJavaScriptHandler is not implemented on the current platform on Flutter Web

### ISSUE THREAD

**Issue by muhammadarslannasr** [pichillilorenzo/flutter_inappwebview#2299]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.22.2        |
| Plugin version        |        6.1.0       |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |      129.0.6668.59         |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

  onWebViewCreated: (controller) {
        controller.addJavaScriptHandler(handlerName: 'Captcha', callback: (args) {
          // print arguments coming from the JavaScript side!
          print(args);
        });

        _controller = controller;
      },

**Comment by pichillilorenzo** [comment]
As it says, it’s not implemented. Web Platform has very limited support.

**Comment by muhammadarslannasr** [comment]
can you tell me how its possible to do so in any other way as i have java script channel and i need to get response and same working fine in android and iOS but not in flutter web.

@pichillilorenzo 

> As it says, it’s not implemented. Web Platform has very limited support.
