### ISSUE TITLE
Session expired bug in windows platform

### ISSUE THREAD

**Issue by venky9885** [pichillilorenzo/flutter_inappwebview#2309]
I am using this for Windows Platform

I am using latest version of flutter,and also inappwebview
i am accessing the site see in pic
![image](https://github.com/user-attachments/assets/f2b7cb36-75a3-4cd8-bd14-4fc7e97e4dc6)
When i click forgot password or when i login itshows
![image](https://github.com/user-attachments/assets/2670c461-6bbd-4145-830e-e2911e548bb1)

**Comment by pichillilorenzo** [comment]
It should work with the latest version 6.1.3 published now.

**Comment by venky9885** [comment]
Yes it's solved thanks
