### ISSUE TITLE
Camera in webview android is opened. But when I press 'ok' button in camera. The Image is not uploaded.

### ISSUE THREAD

**Issue by RaisHelmy** [pichillilorenzo/flutter_inappwebview#2313]
Hi Everyone, this is not an bug but a question

I use this library but it seems that the camera photos is not uploaded in html. 

I already grant access to camera and storage but upon clicking camera, the camera is opened and capturing image on android phone but after clicking 'ok' it doesnt attach file to photo

**Comment by rhowelp** [comment]
Same issue with me. Uploading via file picker is working but I need to upload a photo using camera, but I can't capture the photo

**Comment by boonkahming** [comment]
I am also facing the same issue with Android 13, the camera launched, and after taking the photo and clicked on "Use Photo", nothing is being uploaded to the photo uploader plugin. 

However, the camera photo upload works fine on iPadOS 17.

**Comment by boonkahming** [comment]
Hey everyone! My camera photo is able to upload the image to the uploader input now. Below are the setups that need to done.

**1. Make sure to request for camera permission in your `main()` method.**
```
import 'package:permission_handler/permission_handler.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Permission.camera.request();
  await Permission.microphone.request(); // if you need microphone permission

  runApp(MyApp());
}
```

**2. Make sure to have the below permissions in your `AndroidManifest.xml`**
```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.VIDEO_CAPTURE" />
<uses-permission android:name="android.permission.AUDIO_CAPTURE" />
```

**3. Make sure to also add the below block in your `AndroidManifest.xml`**
```
<provider
    android:name="com.pichillilorenzo.flutter_inappwebview_android.InAppWebViewFileProvider"
    android:authorities="${applicationId}.flutter_inappwebview_android.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />
</provider>
```

This is officially documented in the documentation.
https://inappwebview.dev/docs/intro#enable-camera-for-html-inputs
