### ISSUE TITLE
[iOS] version 6.1.3 does not work on ios 16 and below, blank screen

### ISSUE THREAD

**Issue by Alex-esc1** [pichillilorenzo/flutter_inappwebview#2323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

working perfectly in android and iOS 18, but on iOS 16 and below it shows an empty page

### Expected Behavior

on the old version of iOS 16 and below the screen is not blank

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart
InAppWebView(
                                initialUserScripts:
                                    UnmodifiableListView<UserScript>([
                                  UserScript(
                                    source: """
                                    var style = document.createElement('style');
                                    style.innerHTML = `
                                      body, body * {
                                        color: white !important; 
                                      }
                                    `;
                                    document.head.appendChild(style);
                                  """,
                                    injectionTime: UserScriptInjectionTime
                                        .AT_DOCUMENT_START,
                                  ),
                                ]),
                                initialUrlRequest: URLRequest(
                                    url: WebUri(_geturl()),
                                    headers: {
                                      'Content-Type':
                                          'application/x-www-form-urlencoded',
                                    },
                                    method: 'POST',
                                    body: bytes),
                                initialSettings: options,
                                onWebViewCreated: (controller) {
                                  webViewController = controller;
                                },
                                onCreateWindow:
                                    (controller, createWindowRequest) async {
                                  _ifPopupOpen = true;
                                  context.dialog(
                                    name: bankWidget,
                                    builder: (contextDialog) {
                                      _dialogContext = contextDialog;
                                      return AlertDialog(
                                        scrollable: true,
                                        contentPadding: EdgeInsets.all(10.0.a),
                                        shape: borderTranspRadius15,
                                        content: SizedBox(
                                          width:
                                              MediaQuery.of(context).size.width,
                                          height: MediaQuery.of(context)
                                                  .size
                                                  .height -
                                              100.a,
                                          child: InAppWebView(
                                            gestureRecognizers:
                                                gestureRec.toSet(),
                                            windowId:
                                                createWindowRequest.windowId,
                                            initialSettings: options,
                                            onWebViewCreated:
                                                (InAppWebViewController
                                                    controller) {
                                              webViewControllerPopup =
                                                  controller;
                                            },
                                          ),
                                        ),
                                      );
                                    },
                                  );
                                  return true;
                                },
                                onLoadStop: (controller, uri) async {
                                  if (sessionIdResp != null &&
                                      progress == 1.0) {
                                    await controller
                                        .evaluateJavascript(source: """
                                      var style = document.createElement('style');
                                      style.innerHTML = `
                                        body, body * {
                                          color: black !important;
                                        }
                                      `;
                                      document.head.appendChild(style);
                                      1;
                                    """);
                                  }
                                },
                                onProgressChanged:
                                    (InAppWebViewController controller,
                                        int progress) {
                                  if (mounted) {
                                    setState(() {
                                      this.progress = progress / 100;
                                    });
                                  }
                                },
                                shouldOverrideUrlLoading: (controller,
                                    shouldOverrideUrlLoadingRequest) async {
                                  var uri = shouldOverrideUrlLoadingRequest
                                      .request.url
                                      .toString();
                                  if (uri
                                      .startsWith(EndPoints.widgetReturnUrl)) {
                                    if (_ifPopupOpen &&
                                        _dialogContext != null) {
                                      Navigator.of(_dialogContext!).pop();
                                      _ifPopupOpen = false;
                                      _dialogContext = null;
                                    }
                                    return NavigationActionPolicy.CANCEL;
                                  }
                                  return NavigationActionPolicy.ALLOW;
                                },
                              ),
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
on ios 15 does not call onZoomScaleChanged after this log everything freezes:
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 100}


ios 18 logs:
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 100}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadStop" using {url: NDA}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onZoomScaleChanged" using {oldScale: 0.43883275985717773, newScale: 1.0}
flutter: 10/4/2024 01:45:56 💡 Resource loaded: NDA
flutter: --------------------------------------------------------------------------------
flutter: 10/4/2024 01:45:56 💡 Resource loaded: NDA
flutter: --------------------------------------------------------------------------------
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onConsoleMessage" using {messageLevel: 1, message: AppComponent: ngOnInit: requestPayload }
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA,  initiatorType: xmlhttprequest, startTime: 3223, duration: 141}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {oldContentSize: {height: 782.0, width: 430.0}, newContentSize: {height: 782.0, width: 430.0}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {oldContentSize: {height: 343.0, width: 188.66666666666666}, newContentSize: {height: 782.0, width: 430.0}}
[IOSInAppWebViewController]

```
</details>

### Flutter version

3.24.2

### Operating System, Device-specific and/or Tool

Technology | Version
-- | --
Flutter version | 3.24.2
Plugin version | 6.1.3
Android version |  14
iOS version | 18
macOS version |  
Xcode version | 16

### Plugin version

6.1.3 (6.0.0)

### Additional information

I checked package versions 5.8.0 and 5.7.2+3, on which everything worked, but unfortunately, it did not help. At the moment, the error has not been resolved by downgrading the version.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by qkreltms** [comment]
My app has same issue when I reopen my app after a day. It display bottom navigation from flutter, but my web didn't appears  in My Iphone14(17.2.1) and flutter_inappwebview: 6.0.0

**Comment by Alex-esc1** [comment]
I checked package versions 5.8.0 and 5.7.2+3, on which everything worked, but unfortunately, it did not help. At the moment, the error has not been resolved by downgrading the version.

**Comment by pichillilorenzo** [comment]
@Alex-esc1 please post full logs from the start. Also, try to run your App from XCode and get the logs from it instead of Android Studio or VSCode, thanks.

**Comment by Alex-esc1** [comment]
@pichillilorenzo please take a look

Alas, I can’t show the full URL (NDA)

2024-10-04 11:02:23.169966+0300 Runner[360:7407] flutter: 10/4/2024 11:02:23 💡 ⬇️ Response: NDA
2024-10-04 11:02:23.170672+0300 Runner[360:7407] flutter: 10/4/2024 11:02:23 💡 {sessionId: 70687358616e65314f6a7246796569706444336d46413d3d, requestId: 0d434b42-3223-45cd-b37c-49ed26cdde79}
2024-10-04 11:02:23.173271+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------  

I received the session ID and from that moment I started logging into web view on iOS15:

2024-10-04 11:02:23.314289+0300 Runner[360:7218] [ViewportSizing] maximumViewportInset cannot be larger than frame
2024-10-04 11:02:23.314395+0300 Runner[360:7218] [ViewportSizing] minimumViewportInset cannot be larger than frame
2024-10-04 11:02:25.652791+0300 Runner[360:7407] flutter: 10/4/2024 11:02:25 💡 Resource loaded: NDA.js
2024-10-04 11:02:25.653217+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:25.654729+0300 Runner[360:7407] flutter: 10/4/2024 11:02:25 💡 Resource loaded: NDA/runtime.js?v=6njvbfEOZHcrZOnoVS6QKz6ADxhFYeHdxV6E89V6iEM
2024-10-04 11:02:25.655070+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:25.671932+0300 Runner[360:7407] flutter: 10/4/2024 11:02:25 💡 Resource loaded: ND/Apolyfills.js?v=x2fAj8legDpxSvwv_oYFRmik-OTwcpgQO1SemSubb5s
2024-10-04 11:02:25.672343+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:25.673116+0300 Runner[360:7407] flutter: 10/4/2024 11:02:25 💡 Resource loaded: NDA/js/aggRTV.js?v=TvcgpH0-KTrQTwMPJh6MzcoWBczcFrX34J6wsGC9ER8
2024-10-04 11:02:25.673356+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:25.674078+0300 Runner[360:7407] flutter: 10/4/2024 11:02:25 💡 Resource loaded: NDA/scripts.js?v=7xc-F3JeQJ1YTL8RS61heEOKv_jflMBpoidxLr0SPIo
2024-10-04 11:02:25.674466+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:26.272850+0300 Runner[360:7407] flutter: 10/4/2024 11:02:26 💡 Resource loaded: NDA/js/common.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=702c5ad6f89050dee9dd7d6d09d31b692a67a67ace519f1bcc8a47142c7415a7
2024-10-04 11:02:26.273254+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:26.371902+0300 Runner[360:7407] flutter: 10/4/2024 11:02:26 💡 Resource loaded: NDA/js/fisearch.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=aea2505e2d6b368c8c0ec7959ca148e61153249b2a2c3b2cccb47e3c78605c56
2024-10-04 11:02:26.372297+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:26.388625+0300 Runner[360:7407] flutter: 10/4/2024 11:02:26 💡 Resource loaded: NDA/js/aggPostMessage.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=3cf97d987d3577bef5e15ab23cf698173df5c391c8a1287f48444c4e9fe1a5f8
2024-10-04 11:02:26.389016+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:26.421413+0300 Runner[360:7407] flutter: 10/4/2024 11:02:26 💡 Resource loaded: NDA/css/sponsor.css?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=7a6cb97e44ec32caad53e5f1999a155e22f08a84911c2411c7f4e8378379e136
2024-10-04 11:02:26.421837+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:26.525236+0300 Runner[360:7407] flutter: 10/4/2024 11:02:26 💡 Resource loaded: NDA/js/dropdown.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=12cddba801ccd527aed311c0cc9ae3a5c0a2f521241da95a107636c0aea0a1bc
2024-10-04 11:02:26.525660+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:26.726721+0300 Runner[360:7407] flutter: 10/4/2024 11:02:26 💡 Resource loaded: NDA/main.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=90e8b72c381308d2f1a3a774fdf75db6a3f027e6eb39249a3b200d67ad1e86b3
2024-10-04 11:02:26.727142+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:27.160859+0300 Runner[360:7407] flutter: 10/4/2024 11:02:27 💡 Resource loaded: NDA/styles.css?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=778b0c7f0665da5db3f953d2c25383f7cd5badbae6630f452041881eb1ef2ed2
2024-10-04 11:02:27.161568+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:27.204714+0300 Runner[360:7407] flutter: 10/4/2024 11:02:27 💡 Resource loaded: NDA/c99a4269-161c-4242-a3f0-28d44fa6ce24?
2024-10-04 11:02:27.205122+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:27.289237+0300 Runner[360:7407] flutter: 10/4/2024 11:02:27 💡 Resource loaded: NDA/c99a4269-161c-4242-a3f0-28d44fa6ce24?
2024-10-04 11:02:27.289624+0300 Runner[360:7407] flutter: --------------------------------------------------------------------------------
2024-10-04 11:02:27.582266+0300 Runner[360:7407] flutter: 10/4/2024 11:02:27 💡 Resource loaded: NDA/fonts/OpenSans-Regular.woff2?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D796569706444336d46413d3d%26TRACEID%3DAISUI-336d46413d3d-WFx7mp%26UID%3D3968799&h=4c1c2e95835201077586a3698cd47806dd18df10d32a1e6cb6aa9e47224a55e3  


Then the download stops and nothing happens, no errors, nothing, it just seems to freeze

**Comment by Alex-esc1** [comment]
Full logs from VScode will probably give more information

[IOSInAppWebViewWidget] (iOS) IOSInAppWebViewWidget ID 0 calling "onWebViewCreated" using []
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onUpdateVisitedHistory" using {isReload: null, url: NDA/}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "shouldOverrideUrlLoading" using {isForMainFrame: true, hasGesture: null, isRedirect: null, sourceFrame: {isMainFrame: false, securityOrigin: {port: 0, protocol: , host: }, request: null}, shouldPerformDownload: false, targetFrame: {securityOrigin: {port: 0, host: , protocol: }, isMainFrame: true, request: {body: null, cachePolicy: 0, httpShouldUsePipelining: true, timeoutInterval: 2147483647.0, url: , networkServiceType: 0, allowsCellularAccess: true, allowsExpensiveNetworkAccess: true, assumesHTTP3Capable: false, method: GET, headers: {}, attribution: 0, allowsConstrainedNetworkAccess: true, mainDocumentURL: null, httpShouldHandleCookies: true}}, navigationType: -1, request: {networkServiceType: 0, allowsExpensiveNetworkAccess: true, url: NDA/, headers: {Origin: null, Content-Type: application/x-www-form-urlencoded, User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobil...
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onZoomScaleChanged" using {newScale: 0.3979591727256775, oldScale: 1.0}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadStart" using {url: NDA/}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {oldContentSize: {width: 0.0, height: 0.0}, newContentSize: {height: 711.0, width: 390.0}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {oldContentSize: {height: 1787.0, width: 980.0}, newContentSize: {width: 390.0, height: 711.0}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onReceivedServerTrustAuthRequest" using {protectionSpace: {receivesCredentialSecurely: true, protocol: https, host: ais-ui-uat.fiservapps.com, sslCertificate: {issuedTo: null, validNotAfterDate: null, x509Certificate: [48, 130, 6, 234, 48, 130, 5, 210, 160, 3, 2, 1, 2, 2, 16, 11, 243, 192, 100, 159, 93, 27, 7, 184, 202, 41, 36, 244, 28, 109, 153, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 89, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 51, 48, 49, 6, 3, 85, 4, 3, 19, 42, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 71, 50, 32, 84, 76, 83, 32, 82, 83, 65, 32, 83, 72, 65, 50, 53, 54, 32, 50, 48, 50, 48, 32, 67, 65, 49, 48, 30, 23, 13, 50, 52, 48, 51, 49, 49, 48, 48, 48, 48, 48, 48, 90, 23, 13, 50, 53, 48, 52, 49, 49, 50, 51, 53, 57, 53, 57, 90, 48, 113, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 18, 48, 16, ...
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 50}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onPageCommitVisible" using {url: NDA/}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onTitleChanged" using {title: All Data}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/runtime.js?v=6njvbfEOZHcrZOnoVS6QKz6ADxhFYeHdxV6E89V6iEM, initiatorType: script, startTime: 1424, duration: 5}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/polyfills.js?v=x2fAj8legDpxSvwv_oYFRmik-OTwcpgQO1SemSubb5s, initiatorType: script, startTime: 1425, duration: 10}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/scripts.js?v=7xc-F3JeQJ1YTL8RS61heEOKv_jflMBpoidxLr0SPIo, initiatorType: script, startTime: 1425, duration: 13}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/js/aggRTV.js?v=TvcgpH0-KTrQTwMPJh6MzcoWBczcFrX34J6wsGC9ER8, initiatorType: script, startTime: 1425, duration: 28}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/18f5227b-e27b-445a-a53f-f845fbe69b40/stormcaster.js, initiatorType: script, startTime: 1423, duration: 142}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onReceivedServerTrustAuthRequest" using {protectionSpace: {authenticationMethod: NSURLAuthenticationMethodServerTrust, host: ais-ui-uat.fiservapps.com, distinguishedNames: null, protocol: https, sslError: {message: Indicates the evaluation succeeded and the certificate is implicitly trusted, but user intent was not explicitly specified., code: 4}, port: 443, sslCertificate: {validNotBeforeDate: null, issuedTo: null, issuedBy: null, x509Certificate: [48, 130, 6, 234, 48, 130, 5, 210, 160, 3, 2, 1, 2, 2, 16, 11, 243, 192, 100, 159, 93, 27, 7, 184, 202, 41, 36, 244, 28, 109, 153, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 89, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 51, 48, 49, 6, 3, 85, 4, 3, 19, 42, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 71, 50, 32, 84, 76, 83, 32, 82, 83, 65, 32, 83, 72, 65, 50, 53, 54, ...
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onReceivedServerTrustAuthRequest" using {protectionSpace: {receivesCredentialSecurely: true, proxyType: null, sslCertificate: {issuedBy: null, issuedTo: null, validNotAfterDate: null, x509Certificate: [48, 130, 6, 234, 48, 130, 5, 210, 160, 3, 2, 1, 2, 2, 16, 11, 243, 192, 100, 159, 93, 27, 7, 184, 202, 41, 36, 244, 28, 109, 153, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 89, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 51, 48, 49, 6, 3, 85, 4, 3, 19, 42, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 71, 50, 32, 84, 76, 83, 32, 82, 83, 65, 32, 83, 72, 65, 50, 53, 54, 32, 50, 48, 50, 48, 32, 67, 65, 49, 48, 30, 23, 13, 50, 52, 48, 51, 49, 49, 48, 48, 48, 48, 48, 48, 90, 23, 13, 50, 53, 48, 52, 49, 49, 50, 51, 53, 57, 53, 57, 90, 48, 113, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 18, 48, 16, 6, 3, 85, 4, 8, 1...
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onReceivedServerTrustAuthRequest" using {protectionSpace: {distinguishedNames: null, realm: null, host: ais-ui-uat.fiservapps.com, authenticationMethod: NSURLAuthenticationMethodServerTrust, sslCertificate: {issuedTo: null, x509Certificate: [48, 130, 6, 234, 48, 130, 5, 210, 160, 3, 2, 1, 2, 2, 16, 11, 243, 192, 100, 159, 93, 27, 7, 184, 202, 41, 36, 244, 28, 109, 153, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 89, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 51, 48, 49, 6, 3, 85, 4, 3, 19, 42, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 71, 50, 32, 84, 76, 83, 32, 82, 83, 65, 32, 83, 72, 65, 50, 53, 54, 32, 50, 48, 50, 48, 32, 67, 65, 49, 48, 30, 23, 13, 50, 52, 48, 51, 49, 49, 48, 48, 48, 48, 48, 48, 90, 23, 13, 50, 53, 48, 52, 49, 49, 50, 51, 53, 57, 53, 57, 90, 48, 113, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 8...
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onReceivedServerTrustAuthRequest" using {protectionSpace: {receivesCredentialSecurely: true, proxyType: null, port: 443, host: ais-ui-uat.fiservapps.com, authenticationMethod: NSURLAuthenticationMethodServerTrust, realm: null, sslError: {message: Indicates the evaluation succeeded and the certificate is implicitly trusted, but user intent was not explicitly specified., code: 4}, protocol: https, sslCertificate: {validNotAfterDate: null, x509Certificate: [48, 130, 6, 234, 48, 130, 5, 210, 160, 3, 2, 1, 2, 2, 16, 11, 243, 192, 100, 159, 93, 27, 7, 184, 202, 41, 36, 244, 28, 109, 153, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 89, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 51, 48, 49, 6, 3, 85, 4, 3, 19, 42, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 71, 50, 32, 84, 76, 83, 32, 82, 83, 65, 32, 83, 72, 65, 50, 53,...
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onReceivedServerTrustAuthRequest" using {protectionSpace: {host: ais-ui-uat.fiservapps.com, protocol: https, realm: null, port: 443, authenticationMethod: NSURLAuthenticationMethodServerTrust, distinguishedNames: null, sslError: {code: 4, message: Indicates the evaluation succeeded and the certificate is implicitly trusted, but user intent was not explicitly specified.}, receivesCredentialSecurely: true, proxyType: null, sslCertificate: {issuedTo: null, validNotAfterDate: null, x509Certificate: [48, 130, 6, 234, 48, 130, 5, 210, 160, 3, 2, 1, 2, 2, 16, 11, 243, 192, 100, 159, 93, 27, 7, 184, 202, 41, 36, 244, 28, 109, 153, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 89, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 51, 48, 49, 6, 3, 85, 4, 3, 19, 42, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 71, 50, 32, 84, 76, 8...
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/js/common.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=702c5ad6f89050dee9dd7d6d09d31b692a67a67ace519f1bcc8a47142c7415a7, initiatorType: script, startTime: 1434, duration: 673}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/js/fisearch.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=aea2505e2d6b368c8c0ec7959ca148e61153249b2a2c3b2cccb47e3c78605c56, initiatorType: script, startTime: 1433, duration: 675}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/js/aggPostMessage.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=3cf97d987d3577bef5e15ab23cf698173df5c391c8a1287f48444c4e9fe1a5f8, initiatorType: script, startTime: 1435, duration: 723}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/js/dropdown.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=12cddba801ccd527aed311c0cc9ae3a5c0a2f521241da95a107636c0aea0a1bc, initiatorType: script, startTime: 1432, duration: 829}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/css/sponsor.css?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=7a6cb97e44ec32caad53e5f1999a155e22f08a84911c2411c7f4e8378379e136, initiatorType: link, startTime: 1438, duration: 823}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/styles.css?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=6cb3de8c776cf79aecce6fe37b20472ca9129a296c6225baa7f73194abb8b7ca, initiatorType: link, startTime: 1437, duration: 858}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/fonts/OpenSans-Regular.woff2?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=4c1c2e95835201077586a3698cd47806dd18df10d32a1e6cb6aa9e47224a55e3, initiatorType: css, startTime: 2306, duration: 178}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/main.js?fc=&cc=HID%3D50830001%26PID%3D50830000%26POD%3D0%26RGN%3DCERT%26SESSID%3D756649455164767334513d3d%26TRACEID%3DAISUI-767334513d3d-hcPoqL%26UID%3D3970603&h=90e8b72c381308d2f1a3a774fdf75db6a3f027e6eb39249a3b200d67ad1e86b3, initiatorType: script, startTime: 1430, duration: 1622}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 100}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadStop" using {url: NDA/}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onZoomScaleChanged" using {newScale: 1.0, oldScale: 0.3979591727256775}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {newContentSize: {height: 711.0, width: 390.0}, oldContentSize: {width: 390.0, height: 711.0}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {newContentSize: {height: 711.0, width: 390.0}, oldContentSize: {width: 155.0, height: 282.6666666666667}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/c99a4269-161c-4242-a3f0-28d44fa6ce24?, initiatorType: xmlhttprequest, startTime: 3202, duration: 145}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadResource" using [{url: NDA/c99a4269-161c-4242-a3f0-28d44fa6ce24?, initiatorType: xmlhttprequest, startTime: 3215, duration: 143}]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onConsoleMessage" using {messageLevel: 3, message: JavaScript execution returned a result of an unsupported type}

**Comment by Alex-esc1** [comment]
@pichillilorenzo 
I tried using another web_view package, but the problem was the same, the only thing I noticed in the logs was an error:

2024-10-15 Runner[81948:1303406] flutter: Page started loading: https:/
2024-10-15 Runner[81948:1302215] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by Alex-esc1** [comment]
@pichillilorenzo I decided to raise the minimum version of iOS to 16, the problem can be closed.
