### ISSUE TITLE
[CRITICAL] XCode 16.1 fails to build 

### ISSUE THREAD

**Issue by felipecastrosales** [pichillilorenzo/flutter_inappwebview#2327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current behaviour is that appears problems like:

`Overriding 'init' must be as available as declaration it overrides`

![image](https://github.com/user-attachments/assets/362fe813-d222-4c35-b098-25acb075f9da)

And others like: 

![image](https://github.com/user-attachments/assets/868251e0-59b9-4d44-8bda-8b154218ef74)

I was trying solve this errors and when I fixed and put to build the error was increased to 50 exceptions:

![image](https://github.com/user-attachments/assets/396feea6-e87c-4903-b044-3b132bbe4602)

I would like @pichillilorenzo and other developers who maintain this plugin to fix this, because it seems like a bigger deal to fix and there may be an easier way than what I was trying.

Thanks! 

### Expected Behavior

That works as expected and build for using Xcode16.1. :) 

### Steps with code example to reproduce

Only build an Flutter app.

### Stacktrace/Logs

`Overriding 'init' must be as available as declaration it overrides`

---

`Protocol 'WKUIDelegate' requires 'webView(_:willPresentEditMenuWithAnimator:)' to be available in iOS 16.0 and newer`

---

`Protocol 'WKUIDelegate' requires 'webView(_:requestMediaCapturePermissionFor:initiatedByFrame:type:decisionHandler:)' to be available in iOS 12.0 and newer`

---

`Protocol 'WKUIDelegate' requires 'webView(_:requestDeviceOrientationAndMotionPermissionFor:initiatedByFrame:decisionHandler:)' to be available in iOS 12.0 and newer`

---

etc.

### Flutter version

v3.24.0

### Operating System, Device-specific and/or Tool

iOS specifically

### Plugin version

v6.1.4

### Additional information

I've seen issues from others related to XCode 16, but Xcode 16.1 has other bugs that are very different from the previous ones.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by ARULNITHI0414** [comment]
Please change the deployment target ios version 14

**Comment by felipecastrosales** [comment]
> Please change the deployment target ios version 14

I saw your suggestion from hours ago, but thinking about it now, I think this is not good because I will lose access to other versions that my application supports.

**Comment by felipecastrosales** [comment]
Ok, I can try this but I think that this is not the best way to follow. @pichillilorenzo can you suggest anything?

**Comment by Imgkl** [comment]
@ARULNITHI0414 Didn't work.

**Comment by ARULNITHI0414** [comment]
> @ARULNITHI0414 Didn't work.

I am using Flutter version 3.24.0 and package version 6.1.0, and I have changed my iOS deployment target to version 14. Let's see if it works!

**Comment by felipecastrosales** [comment]
@ARULNITHI0414 I tried with version 14 and 15 and doesn't work as expected. It's the same error.

![image](https://github.com/user-attachments/assets/8fa5eb4f-ebe7-4b47-bb13-4c8e28ac4007)

**Comment by aorohith** [comment]
I have forked and changed in ios, Now the build issue is solved and I need to check the whole working
Please use the below as a dependency for now
  flutter_inappwebview:
    git:
      url: https://github.com/aorohith/flutter_inappwebview.git
      path: flutter_inappwebview
      ref: master
created a pull request #2336

**Comment by felipecastrosales** [comment]
@aorohith I saw your proposal, but I don't think it's correct - at least not completely. I haven't tested it yet, but I gave it a review.

**Comment by lstonussi** [comment]
I'm facing a similar issue after updating to Xcode 16. Any solutions?

**Comment by Marko1994** [comment]
@aorohith your solution works as expected, Thank you so much

**Comment by felipecastrosales** [comment]
@aorohith I tried using your implementation and kept with problems for me. And I make flutter clean and "pod cleans" relateds.

![image](https://github.com/user-attachments/assets/e254e40c-858e-4321-91bd-ca49c6934b88)

**Comment by felipecastrosales** [comment]
Also, when I use last version of this plugin I receive this error:

![image](https://github.com/user-attachments/assets/d37304c6-8e54-4781-afc1-7a137b48c1aa)

When I bumped to 14 as latest version for `IPHONEOS_DEPLOYMENT_TARGET` and on `platform :ios, '14.0'`, generate these errors:

![image](https://github.com/user-attachments/assets/22e5a223-36f0-4461-980b-842dbcc2c6bc)


I really appreciate that this issue has been resolved, because this will happen to more people in the future.

**Comment by Marko1994** [comment]
@felipecastrosales have you tried deleting all pods and podfile.lock ? 
And than "pod install" or "pod update"

**Comment by felipecastrosales** [comment]
@Marko1994 yes, all commands. like: `rm -rf Podfile.lock && pod repo update && pod update && pod install --verbose`, `pod repo remove trunk`, `pod deintegrate` etc.

**Comment by Marko1994** [comment]
@felipecastrosales  Strange

**Comment by Marko1994** [comment]
@felipecastrosales 
Let me tell you what I have followed

Step 1: add forked repo in pubspec instead of the version one, Like this 

flutter_inappwebview:
  git: url: https://github.com/aorohith/flutter_inappwebview.git
  path: flutter_inappwebview
  ref: master

Step 2: add flutter_inappwebview 6.x whatever you used in dependency_override, like this

dependency_overrides:
  flutter_inappwebview: ^6.0.0


and it works

**Comment by felipecastrosales** [comment]
@Marko1994, still isn't working as expected. Could you share your pubspec.yaml file here as an example of how you implemented it?

**Comment by aorohith** [comment]
@felipecastrosales Use the same forked package as the dependency override instead of pub package

git: url: https://github.com/aorohith/flutter_inappwebview.git
path: flutter_inappwebview
ref: master

**Comment by felipecastrosales** [comment]
@aorohith using your recommendation I have this problems:

![image](https://github.com/user-attachments/assets/06b1d285-45a1-429a-a138-920fe6844ca7)

**Comment by felipecastrosales** [comment]
After that I bump my minimum iOS version to `14.0` and `IPHONEOS_DEPLOYMENT_TARGET` to 14.

![image](https://github.com/user-attachments/assets/71c85434-0447-4ecf-90c2-0aac886de284)

**Comment by felipecastrosales** [comment]
I tried more onetime using a new version of XCode ([beta 3](https://xcodereleases.com/#:~:text=Xcode%2016.1-,Beta%203,-16B5029d)) + iPhone 16 Pro Max simulator and I receive this now: 

![image](https://github.com/user-attachments/assets/45a17709-c7db-4b95-a53e-5da20d106662)

**Comment by felipecastrosales** [comment]
Now with iPhone 16 Pro Max (18.0) using [XCode 16.0](https://xcodereleases.com/#:~:text=Release%20Notes-,Xcode%2016.0,-Release).

![image](https://github.com/user-attachments/assets/1b951c27-4bdb-43e2-bd6c-494feb816ca9)

I'm currently using macos 15.0.1.

**Comment by felipecastrosales** [comment]
All of tests are on your fork @aorohith and using as override. cc @Marko1994

**Comment by aorohith** [comment]
Let me share my settings
1.  Mac OS version : 15.0.1 (24A348)
2. Xcode : Version 16.0 (16A242d)
3. Fluter. : 2.24.0
4. Dart : 3.5.0
5. Using the forked flutter_inappwebview in both dependency and dependency_overrides section
6. In pod file and minimum iOS version to 13.0
Also in pod file added this code 
`post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end`
  
 Still, I am not sure about the issue you are facing.  Add the line below to the pod file like above and try. 
  `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'`

**Comment by felipecastrosales** [comment]
@aorohith i'm trying now with:
- `installer.generated_projects.each do |project|` instead of `installer.pods_project.targets.each do |target|`;
- adding forked flutter_inappwebview in both places;
- setting to 13 specifically (I tried with 14 and 15).

**Comment by pichillilorenzo** [comment]
Sorry guys, I will take a look into it as soon as possible.
In the meantime, could you just use XCode 16.0 instead of XCode 16.1? You can have multiple XCode versions installed on your machine.
You can download it from https://developer.apple.com/download/all/?name=Xcode

**Comment by felipecastrosales** [comment]
@pichillilorenzo I tried with different versions of XCode. After each test and installation I always delete the old one and restart the machine, to make sure it would restart. I was unable to use version 16.0 with Mac 15.0.1 and had the above problems.

**Comment by aorohith** [comment]
@felipecastrosales 
Clean all caches, Try all the below command
fvm flutter clean
rm -rf ios/Pods 
rm ios/Podfile.lock
pod cache clean --all
pod deintegrate
rm -rf ~/Library/Developer/Xcode/DerivedData/
rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport
rm -rf ios/Flutter/App.framework 
rm -rf ios/Flutter/Flutter.framework 
rm -rf ios/Flutter/Flutter.podspec
fvm flutter pub cache clean
fvm flutter pub get
cd ios
pod install

**Comment by felipecastrosales** [comment]
Any news?

**Comment by hieutran1999** [comment]
same issue

**Comment by felipecastrosales** [comment]
any news about it?

**Comment by pichillilorenzo** [comment]
I'm not able to reproduce your issue. I'm able to compile and run on the iOS simulator and real iPhone using XCode Version 16.1 (16B40).

Which version of the plugin are you using? Try the latest stable or beta available.

**Comment by felipecastrosales** [comment]
@pichillilorenzo what's your macos and iOS simulator versions?

**Comment by pichillilorenzo** [comment]
At this point, I think there is something on your XCode project that is causing this issue, but I don't know what it could be.

Try to create a new Flutter project, import this plugin, use an example code with `InAppWebView`, and just try to compile and run it.
If it runs, then I would assume there is something on your current XCode project that is not set correctly.

**Comment by felipecastrosales** [comment]
Hey guys! This problem was only on my work machine, and on my personal machine it worked as expected (there were differences in the environment).

So today I decided to risk deleting the entire cache, setting up the project I work on from scratch and updating XCode to 16.1 and iOS on the physical device to 18.1.1. And it worked right away!

**Comment by felipecastrosales** [comment]
I will be closing this issue, as I think it can be resolved by following the steps I mentioned above. But you can comment here if necessary and I can help.
