### ISSUE TITLE
Flutter_inappwebview-Swift.h not found

### ISSUE THREAD

**Issue by kaudy** [pichillilorenzo/flutter_inappwebview#233]
## Environment
**Flutter version: 1.13.6-pre.16** 
**Plugin version: 2.1.0+1**  
**iOS version: 13.2.2 **
**Xcode version: 11.2.1**  

## Description
When build the app to test in IOS crash with error:
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-2.1.0+1/ios/Classes/InAppWebViewFlutterPlugin.m:19:9: fatal error: 'flutter_inappwebview/flutter_inappwebview-Swift.h' file not found
    #import <flutter_inappwebview/flutter_inappwebview-Swift.h>

**Comment by sysmesh** [comment]
Same error here.
Flutter version: 1.12.13+hotfix.5 
Plugin version: 2.1.0+1
**iOS version: 13.2.2 **
Xcode version: 11.2.1
