### ISSUE TITLE
flutter webview for iOS14 and below is packaged as a link to access the white screen

### ISSUE THREAD

**Issue by yj229201093** [pichillilorenzo/flutter_inappwebview#2353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

flutter webview for iOS14 and below is packaged as a link to access the white screen

### Expected Behavior

flutter webview for iOS14 and below is packaged as a link to access the white screen

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart
// Paste your code here
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
<Replace this line by pasting your stacktrace or logs here>
```
</details>

### Flutter version

v3.19.6

### Operating System, Device-specific and/or Tool

iOS14， iPhoneX

### Plugin version

v6.0.0

### Self grab

- [X] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
Please, share any useful log from XCode and steps to reproduce the issue otherwise I don’t know what’s going on

**Comment by yj229201093** [comment]
[IOSInAppWebViewWidget] (iOS) IOSInAppWebViewWidget ID 0 calling "onWebViewCreated" using []
flutter: [__WAppViewState][App.onWebViewCreated]
flutter: [__WAppViewState][App.initBridge]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onUpdateVisitedHistory" using {url: about:blank, isReload: null}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "shouldOverrideUrlLoading" using {isRedirect: null, targetFrame: {request: null, securityOrigin: {host: , protocol: , port: 0}, isMainFrame: true}, hasGesture: null, shouldPerformDownload: null, request: {url: about:blank, networkServiceType: 0, timeoutInterval: 60.0, cachePolicy: 0, allowsCellularAccess: true, httpShouldUsePipelining: true, allowsConstrainedNetworkAccess: null, body: null, allowsExpensiveNetworkAccess: null, httpShouldHandleCookies: true, mainDocumentURL: about:blank, method: GET, headers: {Upgrade-Insecure-Requests: 1}, attribution: null, assumesHTTP3Capable: null}, isForMainFrame: true, navigationType: -1, sourceFrame: {request: null, securityOrigin: {port: 0, host: , protocol: }, isMainFrame: false}}
flutter: URL: about:blank
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadStart" using {url: about:blank}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onPageCommitVisible" using {url: about:blank}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onUpdateVisitedHistory" using {isReload: null, url: http://localhost:49742/desk_manager_cs/}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadStop" using {url: http://localhost:49742/desk_manager_cs/}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "shouldOverrideUrlLoading" using {request: {allowsCellularAccess: true, allowsConstrainedNetworkAccess: null, allowsExpensiveNetworkAccess: null, timeoutInterval: 60.0, attribution: null, headers: {User-Agent: Mozilla/5.0 (iPad; CPU OS 12_5_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, Upgrade-Insecure-Requests: 1}, body: null, networkServiceType: 0, method: GET, httpShouldUsePipelining: true, mainDocumentURL: http://localhost:49742/desk_manager_cs/, cachePolicy: 0, assumesHTTP3Capable: null, url: http://localhost:49742/desk_manager_cs/, httpShouldHandleCookies: true}, targetFrame: {isMainFrame: true, request: {attribution: null, body: null, mainDocumentURL: null, allowsExpensiveNetworkAccess: null, allowsCellularAccess: true, url: about:blank, allowsConstrainedNetworkAccess: null, cachePolicy: 0, method: GET, httpShouldUsePipelining: true, timeoutInterval: 214...
flutter: URL: http://localhost:49742/desk_manager_cs/
flutter: [ZAppController][Version][Server][0.0.62]
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onZoomScaleChanged" using {newScale: 1.0448979139328003, oldScale: 1.0}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {oldContentSize: {width: 0.0, height: 0.0}, newContentSize: {width: 1024.0, height: 768.0}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {newContentSize: {height: 768.0, width: 1024.0}, oldContentSize: {width: 980.0, height: 735.0}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadStart" using {url: http://localhost:49742/desk_manager_cs/}
flutter: 2024-10-17T14:13:46.094156  0:00:00.004807 GET     [200] /desk_manager_cs/
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 50}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onPageCommitVisible" using {url: http://localhost:49742/desk_manager_cs/}
flutter: 2024-10-17T14:13:46.657161  0:00:00.002910 GET     [200] /desk_manager_cs/main.dart.js
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onTitleChanged" using {title: desk_manager}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 89}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onConsoleMessage" using {messageLevel: 0, message: Flutter Web Bootstrap: Auto.}
flutter: [__WAppViewState][ConsoleMessage][ConsoleMessage{message: Flutter Web Bootstrap: Auto., messageLevel: TIP}]
flutter: 2024-10-17T14:13:49.224938  0:00:00.003988 GET     [200] /desk_manager_cs/assets/FontManifest.json
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 100}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onLoadStop" using {url: http://localhost:49742/desk_manager_cs/}
flutter: 2024-10-17T14:13:49.917803  0:00:00.002832 GET     [200] /desk_manager_cs/assets/fonts/MaterialIcons-Regular.otf
flutter: 2024-10-17T14:13:51.929797  0:00:00.002636 GET     [200] /desk_manager_cs/main.dart.js
flutter: 2024-10-17T14:13:54.852818  0:00:00.003215 GET     [200] /desk_manager_cs/assets/FontManifest.json
flutter: [__WAppViewState][App.onPageFinished][http://localhost:49742/desk_manager_cs/]
flutter: 2024-10-17T14:13:55.440304  0:00:00.004000 GET     [200] /desk_manager_cs/assets/fonts/MaterialIcons-Regular.otf

**Comment by yj229201093** [comment]
flutter: [__WAppViewState][App.registerBridge][exitZApp][null]
[IOSInAppWebViewWidget] (iOS) IOSInAppWebViewWidget calling "dispose" using []
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onWindowBlur" using []
flutter: [ZApp][openApp][zapp://desk_manager_cs/][null]
flutter: [ZApp][openApp][Serving at 55188]
flutter: [ZApp][openApp.Callback][zapp://desk_manager_cs/]
flutter: RouteSettings("/zapplication/desk_manager_cs", zapp://desk_manager_cs/)
flutter: [__WAppViewState][App.appInit]
flutter: [ZAppController][App.Controller][Init]
flutter: [ZAppController][Version][Local][0.0.62]
[IOSInAppWebViewWidget] (iOS) IOSInAppWebViewWidget ID 1 calling "onWebViewCreated" using []
flutter: [__WAppViewState][App.onWebViewCreated]
flutter: [__WAppViewState][App.initBridge]
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onUpdateVisitedHistory" using {isReload: null, url: about:blank}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onUpdateVisitedHistory" using {url: http://localhost:55188/desk_manager_cs/, isReload: null}
flutter: [ZAppController][Version][Server][0.0.62]
flutter: URL: about:blank
flutter: [__WAppViewState][App.onPageStarted][http://localhost:55188/desk_manager_cs/]
flutter: URL: http://localhost:55188/desk_manager_cs/
flutter: 2024-10-17T14:17:27.424408  0:00:00.000452 GET     [200] /desk_manager_cs/
flutter: 2024-10-17T14:17:27.437319  0:00:00.000281 GET     [200] /desk_manager_cs/manifest.json
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "shouldOverrideUrlLoading" using {sourceFrame: {securityOrigin: {protocol: , host: , port: 0}, isMainFrame: true, request: {assumesHTTP3Capable: false, allowsCellularAccess: true, allowsConstrainedNetworkAccess: true, body: null, allowsExpensiveNetworkAccess: true, httpShouldUsePipelining: true, networkServiceType: 0, mainDocumentURL: null, attribution: 0, cachePolicy: 0, url: , timeoutInterval: 2147483647.0, method: GET, headers: {}, httpShouldHandleCookies: true}}, request: {headers: {}, timeoutInterval: 60.0, mainDocumentURL: about:blank, httpShouldUsePipelining: false, attribution: 0, cachePolicy: 0, httpShouldHandleCookies: true, body: null, allowsCellularAccess: true, allowsConstrainedNetworkAccess: true, assumesHTTP3Capable: false, networkServiceType: 0, method: GET, allowsExpensiveNetworkAccess: true, url: about:blank}, shouldPerformDownload: false, navigationType: -1, hasGesture: null, isForMainFrame: true, isRedirect: null, targetFrame: {isMainFrame...
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onProgressChanged" using {progress: 0}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onProgressChanged" using {progress: 10}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onUpdateVisitedHistory" using {url: about:blank, isReload: null}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onLoadStart" using {url: about:blank}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onPageCommitVisible" using {url: about:blank}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onProgressChanged" using {progress: 100}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onLoadStop" using {url: about:blank}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "shouldOverrideUrlLoading" using {hasGesture: null, targetFrame: {isMainFrame: true, request: {method: GET, headers: {}, assumesHTTP3Capable: false, httpShouldHandleCookies: true, timeoutInterval: 2147483647.0, cachePolicy: 0, allowsCellularAccess: true, mainDocumentURL: null, networkServiceType: 0, allowsExpensiveNetworkAccess: true, allowsConstrainedNetworkAccess: true, body: null, url: about:blank, attribution: 0, httpShouldUsePipelining: true}, securityOrigin: {host: , port: 0, protocol: }}, isForMainFrame: true, isRedirect: null, request: {headers: {Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148}, networkServiceType: 0, timeoutInterval: 60.0, allowsExpensiveNetworkAccess: true, httpShouldHandleCookies: true, url: http://localhost:55188/desk_manager_cs/, method: GET, assumesHTTP3Capable: false, allowsConstrain...
flutter: 2024-10-17T14:17:27.454131  0:00:00.000288 GET     [200] /desk_manager_cs/main.dart.js
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onProgressChanged" using {progress: 10}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onUpdateVisitedHistory" using {isReload: null, url: http://localhost:55188/desk_manager_cs/}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onLoadStart" using {url: http://localhost:55188/desk_manager_cs/}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onProgressChanged" using {progress: 50}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onPageCommitVisible" using {url: http://localhost:55188/desk_manager_cs/}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onTitleChanged" using {title: desk_manager}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onZoomScaleChanged" using {newScale: 0.4010204076766968, oldScale: 1.0}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onContentSizeChanged" using {newContentSize: {height: 852.0, width: 393.0}, oldContentSize: {width: 0.0, height: 0.0}}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onContentSizeChanged" using {newContentSize: {height: 852.0, width: 393.0}, oldContentSize: {width: 980.0, height: 2125.0}}
flutter: 2024-10-17T14:17:27.603161  0:00:00.000475 GET     [200] /desk_manager_cs/assets/FontManifest.json
flutter: [__WAppViewState][App.onPageFinished][http://localhost:55188/desk_manager_cs/]
flutter: 2024-10-17T14:17:27.630097  0:00:00.000388 GET     [200] /desk_manager_cs/assets/fonts/MaterialIcons-Regular.otf
flutter: [__WAppViewState][ConsoleMessage][ConsoleMessage{message: Flutter Web Bootstrap: Auto., messageLevel: TIP}]
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onConsoleMessage" using {message: Flutter Web Bootstrap: Auto., messageLevel: 0}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onProgressChanged" using {progress: 100}
[IOSInAppWebViewController] (iOS) WebView ID 1 calling "onLoadStop" using {url: http://localhost:55188/desk_manager_cs/}
flutter: [__WAppViewState][App.interface.config]
flutter: [__WAppViewState][App.interface.config.end]   This is the content information of iOS15 and above, iOS15 and above can be loaded

**Comment by pichillilorenzo** [comment]
From the logs, it seems to load successfully.
Can you run it on XCode and get the logs from there on iOS 14?

**Comment by yj229201093** [comment]
2024-10-17 14:41:46.603201+0800 Runner[3463:1061759] flutter: [ZApp][openApp][zapp://desk_manager_cs/][null]
2024-10-17 14:41:47.466344+0800 Runner[3463:1061759] flutter: [ZApp][openApp][Serving at 50023]
2024-10-17 14:41:47.473966+0800 Runner[3463:1061759] flutter: [ZApp][openApp.Callback][zapp://desk_manager_cs/]
2024-10-17 14:41:47.482985+0800 Runner[3463:1061759] flutter: RouteSettings("/zapplication/desk_manager_cs", zapp://desk_manager_cs/)
2024-10-17 14:41:47.680994+0800 Runner[3463:1061759] flutter: [__WAppViewState][App.appInit]
2024-10-17 14:41:47.686217+0800 Runner[3463:1061759] flutter: [ZAppController][App.Controller][Init]
2024-10-17 14:41:48.035185+0800 Runner[3463:1061759] flutter: [ZAppController][Version][Local][0.0.62]
2024-10-17 14:41:48.813371+0800 Runner[3463:1061759] flutter: [__WAppViewState][App.onWebViewCreated]
2024-10-17 14:41:48.817031+0800 Runner[3463:1061759] flutter: [__WAppViewState][App.initBridge]
2024-10-17 14:41:49.928657+0800 Runner[3463:1061759] flutter: URL: about:blank
2024-10-17 14:41:50.056858+0800 Runner[3463:1061759] flutter: [ZAppController][Version][Server][0.0.62]
2024-10-17 14:41:50.112309+0800 Runner[3463:1061759] flutter: URL: http://localhost:50023/desk_manager_cs/
2024-10-17 14:41:50.600880+0800 Runner[3463:1061759] flutter: 2024-10-17T14:41:50.518730  0:00:00.073884 GET     [200] /desk_manager_cs/
2024-10-17 14:41:51.404309+0800 Runner[3463:1061759] flutter: 2024-10-17T14:41:51.400105  0:00:00.003837 GET     [200] /desk_manager_cs/main.dart.js
2024-10-17 14:41:53.530344+0800 Runner[3463:1061759] flutter: 2024-10-17T14:41:53.526599  0:00:00.003384 GET     [200] /desk_manager_cs/assets/FontManifest.json
2024-10-17 14:41:53.872178+0800 Runner[3463:1061759] flutter: [__WAppViewState][ConsoleMessage][ConsoleMessage{message: Flutter Web Bootstrap: Auto., messageLevel: TIP}]
2024-10-17 14:41:54.196064+0800 Runner[3463:1061759] flutter: 2024-10-17T14:41:54.192045  0:00:00.003622 GET     [200] /desk_manager_cs/assets/fonts/MaterialIcons-Regular.otf     This is Xocde15, iOS12 device, under iOS14 are white screen, loading can not come out

**Comment by yj229201093** [comment]
https://bugs.webkit.org/show_bug.cgi?id=227524   This is ios14 WK bug, see if there is any reference value, iOS15 and above are normal

**Comment by yj229201093** [comment]
Invalidating grant <invalid NS/CF object> failed
Invalidating grant <invalid NS/CF object> failed
flutter: [ZApp][openApp][zapp://desk_manager_cs/][null]
flutter: [ZApp][openApp][Serving at 60079]
flutter: [ZApp][openApp.Callback][zapp://desk_manager_cs/]
flutter: RouteSettings("/zapplication/desk_manager_cs", zapp://desk_manager_cs/)
flutter: [__WAppViewState][App.appInit]
flutter: [ZAppController][App.Controller][Init]
flutter: [ZAppController][Version][Local][0.0.62]
flutter: [__WAppViewState][App.onWebViewCreated]
flutter: [__WAppViewState][App.initBridge]
flutter: [ZAppController][Version][Server][0.0.62]
flutter: URL: about:blank
flutter: URL: http://localhost:60079/desk_manager_cs/
flutter: 2024-10-17T14:45:26.236091  0:00:00.000524 GET     [200] /desk_manager_cs/
flutter: 2024-10-17T14:45:26.242521  0:00:00.000336 GET     [200] /desk_manager_cs/manifest.json
flutter: 2024-10-17T14:45:26.248042  0:00:00.000244 GET     [200] /desk_manager_cs/main.dart.js
flutter: [__WAppViewState][ConsoleMessage][ConsoleMessage{message: Flutter Web Bootstrap: Auto., messageLevel: TIP}]
flutter: 2024-10-17T14:45:26.370802  0:00:00.000524 GET     [200] /desk_manager_cs/assets/FontManifest.json
flutter: 2024-10-17T14:45:26.391705  0:00:00.000412 GET     [200] /desk_manager_cs/assets/fonts/MaterialIcons-Regular.otf
flutter: [__WAppViewState][App.interface.config]
flutter: [__WAppViewState][App.interface.config.end]
flutter: [__WAppViewState][App.registerBridge][config][{"left":0.0,"top":59.0,"right":0.0,"bottom":34.0,"language_code":"zh","country_code":"Hans","query":null,"params":{},"dev_mode":1}]
flutter: [__WAppViewState][App.interface.oauth]
flutter: [__WAppViewState][App.interface.oauth.end][qvuwvTDmXHkRaZDt]
flutter: [__WAppViewState][App.registerBridge][oauth][qvuwvTDmXHkRaZDt]
flutter: [__WAppViewState][App.registerBridge][storeGetInt][0]
flutter: 2024-10-17T14:45:26.466838  0:00:00.000353 GET     [200] /desk_manager_cs/assets/AssetManifest.bin.json
flutter: 2024-10-17T14:45:26.530004  0:00:00.000385 GET     [200] /desk_manager_cs/assets/images/desk.unit.png
flutter: 2024-10-17T14:45:26.532289  0:00:00.000257 GET     [200] /desk_manager_cs/assets/images/desk.light.png
flutter: 2024-10-17T14:45:26.558755  0:00:00.000530 GET     [200] /desk_manager_cs/assets/images/desk.setting.png
flutter: 2024-10-17T14:45:26.560834  0:00:00.000236 GET     [200] /desk_manager_cs/assets/images/desk.management.mode.png
flutter: 2024-10-17T14:45:27.054457  0:00:00.000447 GET     [200] /desk_manager_cs/assets/images/desk.status.leisure.png
flutter: 2024-10-17T14:45:27.057191  0:00:00.000302 GET     [200] /desk_manager_cs/assets/images/desk.add.png
flutter: [__WAppViewState][App.registerBridge][storeGetInt][0]
flutter: 2024-10-17T14:45:27.483950  0:00:00.000550 GET     [200] /desk_manager_cs/assets/images/desk.tutorials1.png
flutter: 2024-10-17T14:45:28.222705  0:00:00.000509 GET     [200] /desk_manager_cs/assets/images/desk.status.pause.png
Invalidating grant <invalid NS/CF object> failed      This is the normal loadable content on the emulator for xcode15,iOS17.5. Whether there is an additional /desk_manager_cs/manifest.json file. Not loaded on iOS14, not sure if this has any effect

**Comment by pichillilorenzo** [comment]
Do you mean that this is related only for Web App using a Service Worker? If you load a website that is not using Service Workers, does it load correctly on iOS 14?

**Comment by yj229201093** [comment]
https://www.baidu.com  Baidu is OK On iOS14，  We have made js bridge

**Comment by pichillilorenzo** [comment]
Ok, thanks! Have you checked about https://inappwebview.dev/docs/service-worker#service-worker-on-ios ?

**Comment by yj229201093** [comment]
<img width="720" alt="image" src="https://github.com/user-attachments/assets/58abdae5-a1b3-4ff6-b96e-22c49d18caca">
Configure with， It's just weird. Not under iOS14, but iOS15

**Comment by yj229201093** [comment]
<img width="731" alt="image" src="https://github.com/user-attachments/assets/f61a362c-1892-43af-9783-ea411ea9621f">
It's just weird. Not under iOS14, but iOS15

**Comment by pichillilorenzo** [comment]
The important part is `limitsNavigationsToAppBoundDomains: true,` which adds Service Worker API on iOS 14.0+.
Below 14.0 Service worker will not work as there is not support about it on WKWebView of iOS.
The `isInspectable` is to enable inspect developer tool on Safari for your webview instance.

When using `limitsNavigationsToAppBoundDomains`, you can specify up to 10 "app-bound" domains using the key `WKAppBoundDomains` in your `Info.plist` iOS file.
Did you specify your app-bound domains?

**Comment by yj229201093** [comment]
https://github.com/flutter/flutter/issues/132927   [Web][Canvaskit] WebApp fails to render on iOS devices running iOS 14

**Comment by pichillilorenzo** [comment]
So it seems this is something related to flutter used for developing web apps and not to this plugin.
They said that Flutter Web supports iOS 14.5+.
You should set an higher minimum iOS version for your Native App.

**Comment by yj229201093** [comment]
I have a web application written by flutter, and then embed this web into the webview(flutter_inappwebview) of the flutter application, which has designed js Bridges, and app-bound domains are now configured. Need to find an iOS14 to test to see, but should have little to do with this, no configuration iOS15 is normal access. Only iOS14 doesn't work

**Comment by yj229201093** [comment]
<img width="852" alt="image" src="https://github.com/user-attachments/assets/805d3338-f246-4547-ac9f-43841c072895">
Does this mean you can't use the internal WKWebView

**Comment by pichillilorenzo** [comment]
No, that means if your App is designed to be a Browser, like the Google Chrome or Mozilla App, then you can use the Service Worker js API for every website.
This is not your case, as your App is not a Browser.

The problem here, from the Flutter issue you shared, seems to be the Flutter Web App rendering on iOS 14 and below and not the Flutter Mobile App (with this plugin) that is loading your Flutter Web App.
