### ISSUE TITLE
kScrollMultiplier should be configurable in Windows

### ISSUE THREAD

**Issue by augustresende** [pichillilorenzo/flutter_inappwebview#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The scroll is junky, scrolling large chunks of the page instead of smooth from default browser

### Expected Behavior

Smoth scrolling, making this variable default as 1 (or even better, customizable), fixes the problem

### Steps with code example to reproduce

N/A

### Stacktrace/Logs

N/A

### Flutter version

latest

### Operating System, Device-specific and/or Tool

Windows 11 23H2

### Plugin version

v6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by augustresende** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/blob/f67ae1f34868c7660c16a2473f53a7a7bfb6f784/flutter_inappwebview_windows/windows/in_app_webview/in_app_webview.cpp#L1792

**Comment by zhalil** [comment]
same problem, jumps by 500 pieces with one mouse scroll

**Comment by pichillilorenzo** [comment]
Yep, it probably should be something configurable. I can add it as a new parameter in `InAppWebViewSettings` 👍.
By the way, what could be the best default value for it? 1 should be ok?

**Comment by zhalil** [comment]
> Yep, it probably should be something configurable. I can add it as a new parameter in `InAppWebViewSettings` 👍. By the way, what could be the best default value for it? 1 should be ok?

yes I think 1 is the best solution, because everyone expects the same behavior as in the browser

**Comment by pichillilorenzo** [comment]
Released new version `6.2.0-beta.1`. The default value is `1` and you can change it using `InAppWebViewSettings.scrollMultiplier`.
