### ISSUE TITLE
pull to refresh and scrolling limits only to screen 

### ISSUE THREAD

**Issue by ailedev** [pichillilorenzo/flutter_inappwebview#2369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to implement a pull to refresh feature using RefreshIndicator in my webview application but while doing that my  scrolling is getting locked but the pull-to-refresh works fine. I am unable to scroll in my app, I think it is due to the ListView that I am using. If I remove ListView the scolling problem goes away but then again the pull-to-refresh feature doesn't work. I have also tried using singlechildscrollview: it fixes nothing

### Expected Behavior

It should give me the ability to reload the page and also scroll the contents of that page with no issues

### Steps with code example to reproduce

Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        if (await controller.canGoBack()) {
          await controller.goBack();
          return false; // Prevents closing the app if there's a back history.
        }
        return true; // Allows the app to close if there's no back history.
      },
      child: RefreshIndicator(
        onRefresh: () async {
          await controller.reload();
        },
        child: SingleChildScrollView(
        physics: const AlwaysScrollableScrollPhysics(),
        child: SizedBox(
        height: MediaQuery.of(context).size.height,
        child: child, // This is the WebViewStack with the progress bar.
        ),
        ),
      ));
  }

### Stacktrace/Logs

Syncing files to device sdk gphone64 x86 64...
I/WebViewFactory(13302): Loading com.google.android.webview version 91.0.4472.114 (code 447211487)
W/ple.webview_ex(13302): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/ple.webview_ex(13302): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/ple.webview_ex(13302): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/ple.webview_ex(13302): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/ple.webview_ex(13302): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_LibraryLoader(13302): Loaded native library version number "91.0.4472.114"
I/cr_CachingUmaRecorder(13302): Flushed 6 samples from 6 histograms.
W/chromium(13302): [WARNING:dns_config_service_android.cc(153)] Failed to read DnsConfig.
I/Choreographer(13302): Skipped 140 frames!  The application may be doing too much work on its main thread.
D/CompatibilityChangeReporter(13302): Compat change id reported: 171228096; UID 10147; state: ENABLED
W/ple.webview_ex(13302): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
D/HostConnection(13302): createUnique: call
D/HostConnection(13302): HostConnection::get() New Host Connection established 0x74a1cb8dda50, tid 13458
D/HostConnection(13302): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(13302): eglCreateContext: 0x74a1cb8ded10: maj 3 min 0 rcv 3
D/EGL_emulation(13302): eglMakeCurrent: 0x74a1cb8ded10: ver 3 0 (tinfo 0x74a3e747c280) (first time)
I/Choreographer(13302): Skipped 43 frames!  The application may be doing too much work on its main thread.
W/cr_media(13302): Requires BLUETOOTH permission
D/EGL_emulation(13302): eglCreateContext: 0x74a1cb8ded10: maj 3 min 0 rcv 3
D/EGL_emulation(13302): eglCreateContext: 0x74a1cb8de050: maj 3 min 0 rcv 3
I/PlatformViewsController(13302): Hosting view in view hierarchy for platform view: 0
I/PlatformViewsController(13302): PlatformView is using SurfaceProducer backend
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
I/Choreographer(13302): Skipped 30 frames!  The application may be doing too much work on its main thread.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
D/EGL_emulation(13302): app_time_stats: avg=583.76ms min=84.70ms max=2879.81ms count=7
D/EGL_emulation(13302): app_time_stats: avg=543.45ms min=71.46ms max=2860.43ms count=7
D/ImageReaderSurfaceProducer(13302): ImageTextureEntry can't wait on the fence on Android < 33
D/EGL_emulation(13302): app_time_stats: avg=3718.21ms min=3401.65ms max=4034.78ms count=2
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
D/EGL_emulation(13302): app_time_stats: avg=5586.65ms min=5586.65ms max=5586.65ms count=1
D/EGL_emulation(13302): app_time_stats: avg=5579.54ms min=5579.54ms max=5579.54ms count=1
I/Choreographer(13302): Skipped 185 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(13302): app_time_stats: avg=2510.82ms min=2510.82ms max=2510.82ms count=1
E/FrameEvents(13302): updateAcquireFence: Did not find frame.
I/OpenGLRenderer(13302): Davey! duration=3227ms; Flags=0, FrameTimelineVsyncId=44558, IntendedVsync=1750302356386, Vsync=1753385689596, InputEventId=0, HandleInputStart=1753398578700, AnimationStart=1753398623200, PerformTraversalsStart=1753411583900, DrawStart=1753411727200, FrameDeadline=1750335689718, FrameInterval=1753396604700, FrameStartTime=16666666, SyncQueued=1753507623500, SyncStart=1754076633500, IssueDrawCommandsStart=1754076739000, SwapBuffers=1754077310900, FrameCompleted=1754098969400, DequeueBufferDuration=59200, QueueBufferDuration=1122400, GpuCompleted=1754098502400, SwapBuffersCompleted=1754098969400, DisplayPresentTime=48636209659978, 
I/Choreographer(13302): Skipped 45 frames!  The application may be doing too much work on its main thread.

### Flutter version

Flutter 3.24.3

### Operating System, Device-specific and/or Tool

OS: windows 10 pro
Android SDK: Android API 34
AVD: Pixel 8 API 31
java 23.0.1
webview_flutter 4.10.0
[Android Studio Ladybug | 2024.2.1]

### Plugin version

webview_flutter 4.10.0

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
Currently, the pull to refresh feature is implemented natively on Android and iOS.
Creating it on Flutter seems to be problematic in general as the WebView is a PlatformView, that is a native view rendered on the Flutter widget tree.
Check this to know how to use the pull to refresh implementation: https://inappwebview.dev/docs/webview/pull-to-refresh-controller
