### ISSUE TITLE
shouldOverrideUrlLoading not Working in realse 

### ISSUE THREAD

**Issue by amrdesign** [pichillilorenzo/flutter_inappwebview#237]
Hello shouldOverrideUrlLoading work on debug mode only , but in release not working 

`crossPlatform: InAppWebViewOptions(
                               // useShouldOverrideUrlLoading: true,`

`shouldOverrideUrlLoading:  (InAppWebViewController controller, ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest){
                             print(shouldOverrideUrlLoadingRequest.url);

                             if (shouldOverrideUrlLoadingRequest.url.startsWith("tel:")) {
                               // launch myapp here
                               print('tel=>>>>>>>>>>>>>>');
                              launch(shouldOverrideUrlLoadingRequest.url);
                               return null;
                             }else if(shouldOverrideUrlLoadingRequest.url.startsWith("https://api.whatsapp.com")){
                               launch(shouldOverrideUrlLoadingRequest.url);
                               return null;
                              }else if(shouldOverrideUrlLoadingRequest.url.startsWith("mailto:")){
                               launch(shouldOverrideUrlLoadingRequest.url);
                               return null;
                             }else {
                               return webView.loadUrl(url: shouldOverrideUrlLoadingRequest.url);
                             }

                           },`

**Comment by amrdesign** [comment]
i use 

`flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master`

**Comment by wj1234** [comment]
在Android插件源码中将useShouldOverrideUrlLoading属性默认设置为true

**Comment by amrdesign** [comment]
@wj1234  i use it but same

**Comment by wwwdata** [comment]
Can confirm this as well for Android production builds with the latest code from the master branch of this repo. Did you already identify the cause of the problem?
