### ISSUE TITLE
Parse Issue (Xcode): Module 'DarwinFoundation' is needed but has not been provided

### ISSUE THREAD

**Issue by hanweixing** [pichillilorenzo/flutter_inappwebview#2378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my case, if i do not run`flutter pub add flutter_inappwebview` to use flutter_inappwebview, my flutter project is ok to run on ios simulator.
But when i add flutter_inappwebview and do nothing later, then i run my flutter project, i got this error:
> Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                           197.8s
Failed to build iOS app
Parse Issue (Xcode): Module 'DarwinFoundation' is needed but has not been provided, and implicit use of module files is disabled
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk/System/Library/Frameworks/Network.framework/Headers/nw_object.h:14:9
Could not build the application for the simulator.
Error launching application on iPhone Xʀ.

### Expected Behavior

It should be ok after i add `flutter_inappwebview`.

### Steps with code example to reproduce

<details>
<summary>Just run terminal commands, and then run flutter project on simulator</summary>

```dart
flutter pub add flutter_inappwebview
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                           197.8s
Failed to build iOS app
Parse Issue (Xcode): Module 'DarwinFoundation' is needed but has not been provided, and implicit use of module files is disabled
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk/System/Library/Frameworks/Network.framework/Headers/nw_object.h:14:9

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
```
</details>

### Flutter version

v3.26.0

### Operating System, Device-specific and/or Tool

1. MacOS: Sonoma 14.6.1（Intel Core i5）
2. Xcode: Version 16.0 (16A242d)
3. flutter:
Flutter 3.26.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision ee624bc4fd (7 weeks ago) • 2024-09-10 17:41:06 -0500
Engine • revision 059e4e6d8f
Tools • Dart 3.6.0 (build 3.6.0-216.1.beta) • DevTools 2.39.0
4. flutter pubspec.yaml:
environment:
  sdk: ^3.6.0-216.1.beta

### Plugin version

v6.1.5

### Additional information

Hi, anybody get error like title? 
In my case, if i do not run`flutter pub add flutter_inappwebview` to use flutter_inappwebview, my flutter project is ok to run on ios simulator.
But when i add flutter_inappwebview and do nothing later, then i run my flutter project, i got this error:
> Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                           197.8s
Failed to build iOS app
Parse Issue (Xcode): Module 'DarwinFoundation' is needed but has not been provided, and implicit use of module files is disabled
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk/System/Library/Frameworks/Network.framework/Headers/nw_object.h:14:9
Could not build the application for the simulator.
Error launching application on iPhone Xʀ.

And my environment is:
1. MacOS: Sonoma 14.6.1（Intel Core i5）
2. Xcode: Version 16.0 (16A242d)
3. flutter:
Flutter 3.26.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision ee624bc4fd (7 weeks ago) • 2024-09-10 17:41:06 -0500
Engine • revision 059e4e6d8f
Tools • Dart 3.6.0 (build 3.6.0-216.1.beta) • DevTools 2.39.0
4. flutter pubspec.yaml:
environment:
  sdk: ^3.6.0-216.1.beta

Could anyone give me help? Thanks in advance.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
Have you searched for it on internet, for example:
- https://stackoverflow.com/questions/78996804/vscode-flutter-xcode-16-parse-issue-xcode-module-foundation-is-needed-but-h
- https://stackoverflow.com/questions/46708926/xcode-9-could-not-build-module-foundation/47328607

**Comment by hanweixing** [comment]
> Have you searched for it on internet? For example:
> 
> * https://stackoverflow.com/questions/78996804/vscode-flutter-xcode-16-parse-issue-xcode-module-foundation-is-needed-but-h
> * https://stackoverflow.com/questions/46708926/xcode-9-could-not-build-module-foundation/47328607

@pichillilorenzo Thanks, i finally found that a flutter plugin caused the error, although i did not find something wrong where since, i just copy plugin codes (only in lib folder) to create a new package(which does not have any platform support folders) and pasted codes in, then everything is ok. I believe should be some built files affect the build process.

This error is not related to `flutter_inappwebiew`. Sorry, i am reckless.
