### ISSUE TITLE
i can't use for webrtc in android

### ISSUE THREAD

**Issue by Seven7up** [pichillilorenzo/flutter_inappwebview#238]
when application launched I have this error in android

D/FlutterActivity(21119): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(21119): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(21119): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
W/FlutterEngine(21119): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@5ae8309) but could not find and invoke the GeneratedPluginRegistrant.
D/FlutterActivityAndFragmentDelegate(21119): Attaching FlutterEngine to the Activity that owns this Fragment.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:56385/W8s6bkuCWd8=/

**Comment by HakuFlou** [comment]
+1

**Comment by MustafaGamalAbbas** [comment]
+1

**Comment by Parisius** [comment]
+1

**Comment by attiq-khan** [comment]
Sa,e Here

**Comment by attiq-khan** [comment]
https://pub.dev/packages/flutter_polywebview#-readme-tab-
annother fork of same plugin

**Comment by pichillilorenzo** [comment]
It has been fixed from version `3.0.0`+.
