### ISSUE TITLE
Swift Compiler Error (Xcode): Method does not override any method from its superclass /Users/sony/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/ios/Classes/InAppWebView/InAppWebView.swift:1225:25

### ISSUE THREAD

**Issue by AlHasanSony** [pichillilorenzo/flutter_inappwebview#2381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/0a1b0745-aeef-4dd6-bad3-708d469cc129">

### Expected Behavior

The error in text format (screenshot above):
> Launching lib/main.dart on iPhone 16 Plus in debug mode...
Running Xcode build...
Xcode build done.                                           19.3s
Failed to build iOS app
Swift Compiler Error (Xcode): Method does not override any method from its superclass
/Users/sony/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/ios/Classes/InAppWebView/InAppWebView.swift:1225:25

> Could not build the application for the simulator.
> Error launching application on iPhone 16 Plus.

-- After running the flutter project it shows the error though it previously worked very well in my machine on previous version of flutter and xcode.
What causes the issue ? 
What to do ?

### Steps with code example to reproduce

<details>
<summary>Pubspec.yaml file</summary>

```dart
name: abc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# Code Structure :- GetX

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^3.0.1
  get: ^4.6.5
  sizer: ^2.0.15
  get_storage: ^2.1.1
  fluttertoast: ^8.2.1
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  scrollable_positioned_list: ^0.3.6
  syncfusion_flutter_gauges: ^21.1.41
  charts_flutter_new: ^0.12.0
  align_positioned: ^3.0.0
  date_picker_timeline: ^1.2.3
  flutter_slidable: ^3.0.0
  youtube_player_flutter: ^8.1.2
  table_calendar: ^3.0.8
  sqflite: ^2.2.8+1
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.3
  pin_code_fields: ^8.0.1
  flutter_rounded_date_picker: ^3.0.2
  flutter_local_notifications: ^16.2.0
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.7
  flutter_tts: ^3.6.3
  audioplayers: ^5.2.1
  share_plus: ^7.2.1
  url_launcher: ^6.1.10
  open_settings: ^2.0.2
  android_intent_plus: ^4.0.3
  rate_my_app: ^2.0.0
  date_format: ^2.0.7
  connectivity_plus: ^5.0.2
  in_app_purchase: ^3.1.11
  dio: ^5.1.1
  in_app_purchase_android: ^0.3.0
  in_app_purchase_storekit: ^0.3.6+3
  timezone: ^0.9.2
  google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/database/
    - assets/icons/
    - assets/images/
    - assets/img_ex/
    - assets/img_ex/ABDOMINALCRUNCHES/
    - assets/img_ex/ADDUCTORSTRETCHINSTANDING/
    - assets/img_ex/AIRCYCLING/
    - assets/img_ex/ALTERNATINGHOOKS/
    - assets/img_ex/ALTVUP/


  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/roboto-regular.ttf #Reguler
          weight: 400

```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
Swift Compiler Error (Xcode): Method does not override any method from its superclass
/Users/sony/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/ios/Classes/InAppWebView/InAppWebView.swift:1225:25

Could not build the application for the simulator.
Error launching application on iPhone 16 Plus.
```
</details>

### Flutter version

v3.24.4

### Operating System, Device-specific and/or Tool

iOS 18.1

### Plugin version

My flutter project doesn't have the dependency but it shows the error

### Self grab

- [X] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
You are using `5.8.0` plugin version. You should use the latest 6 version otherwise it won't compile.

**Comment by pichillilorenzo** [comment]
I don’t know which dependency (probably youtube_player_flutter) may use it, but it is using an outdated version of the plugin.
Check for dependency version upgrade
