### ISSUE TITLE
callbacks onLoadStart & onLoadStop brocken on version 6.2.0

### ISSUE THREAD

**Issue by ArturLevchuk** [pichillilorenzo/flutter_inappwebview#2385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On loading and stop loading view callbacks don't work
![image_2024-10-30_20-39-20](https://github.com/user-attachments/assets/9222566e-9cbe-469d-bef0-01e06ae94ba4)

### Expected Behavior

For example on version 6.1.5 all is fine:
![image_2024-10-30_20-41-45](https://github.com/user-attachments/assets/f5c52397-cb87-4ae2-984d-86964f9f0fb9)

### Steps with code example to reproduce

default example from library is used

### Stacktrace/Logs

```
[WebPlatformInAppWebViewWidget] (Web) WebPlatformInAppWebViewWidget ID 0 calling "onWebViewCreated" using []
4
null
```

### Flutter version

3.24.4

### Operating System, Device-specific and/or Tool

Web

### Plugin version

6.2.0

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
Released official new version `6.2.0-beta.1`.
