### ISSUE TITLE
deprecated APIs use on Android 15

### ISSUE THREAD

**Issue by samueldubovec-embedit** [pichillilorenzo/flutter_inappwebview#2388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There has been a report from Google:

**Your app uses deprecated APIs or parameters for edge-to-edge**

One or more of the APIs you use or parameters that you set for edge-to-edge and window display have been deprecated in Android 15. Your app uses the following deprecated APIs or parameters:

- android.view.Window.setStatusBarColor
- android.view.Window.setNavigationBarColor

These start in the following places:

- com.google.android.material.bottomsheet.a.onCreate
- m61.a

### Expected Behavior

There is no deprecated APIs being used

### Steps with code example to reproduce

No need of code example

### Stacktrace/Logs

No need of stacktrace

### Flutter version

v3.24.4

### Operating System, Device-specific and/or Tool

Android 15

### Plugin version

v6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by vinaykharayat** [comment]
Any fix yet?

**Comment by pichillilorenzo** [comment]
As you can see, this is not caused by the plugin, but com.google.android.material.bottomsheet that is not used by this plugin.
Probably, you need to update the https://inappwebview.dev/docs/intro#enable-material-components-for-android component dependency.

**Comment by LNMCode** [comment]
@samueldubovec-embedit @vinaykharayat 
I facing same issue.
Have you any update for this?

- android.view.Window.setDecorFitsSystemWindows
- android.view.Window.setStatusBarColor
- android.view.Window.setNavigationBarColor
- android.view.Window.setNavigationBarDividerColor

These start in the following places:

- com.google.android.material.internal.c.a
- io.flutter.embedding.android.g.I
- io.flutter.plugin.platform.d.a
- io.flutter.plugin.platform.h.C
