### ISSUE TITLE
[iOS] Webview opened with windowId does not receive javascript handler callback.

### ISSUE THREAD

**Issue by ttb-inc** [pichillilorenzo/flutter_inappwebview#2393]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Webview opened with windowId on iOS does not receive javascript handler callback.
This works fine on Android.

### Expected Behavior

I also want to get a javascript handler callback from a webview opened by windowId on iOS.

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart
      onCreateWindow: (controller, createWindowAction) async {
          InAppWebView webview = InAppWebView(
               windowId: createWindowAction.windowId,
               ...
               );
        navigator.push(webview);
        return true;
      },
```

```dart
      onWebViewCreated: (controller) {
          controller.addJavaScriptHandler(
            handlerName: 'myJavascriptHandler',
            callback: (arguments) {
                 return 'test return';
             },
            );
      },
```

</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
<Replace this line by pasting your stacktrace or logs here>
```
</details>

### Flutter version

Channel stable, 3.24.4

### Operating System, Device-specific and/or Tool

iOS 16.x, 17.x

### Plugin version

flutter_inappwebview: 6.1.5

### Additional information

This works fine on Android.

Thank you.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by TeamRemited** [comment]
exactly same here!!!
