### ISSUE TITLE
Flutter WEB: UnimplementedError: addJavaScriptHandler is not implemented on the current platform

### ISSUE THREAD

**Issue by winmalveda** [pichillilorenzo/flutter_inappwebview#2398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

addJavaScriptHandler not working on Flutter Web

### Expected Behavior

addJavaScriptHandler will work as intended

### Steps with code example to reproduce

webViewController.addJavaScriptHandler(
                    handlerName: 'my.getAuthCode',
                    callback: (args) {
                    // Put code here
                    });

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
<Replace this line by pasting your stacktrace or logs here>
```
</details>
DartError: UnimplementedError: addJavaScriptHandler is not implemented on the current platform
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3                                      throw_
packages/flutter_inappwebview_platform_interface/src/in_app_webview/platform_inappwebview_controller.dart 688:5  addJavaScriptHandler
packages/flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart 171:16                           addJavaScriptHandler
packages/hitachi_wma/feature/mobile_emulator/presentation/pages/wma_mobile.dart 77:27                            <fn>
packages/flutter_inappwebview/src/in_app_webview/in_app_webview.dart 314:54                                      <fn>
packages/flutter_inappwebview_web/src/in_app_webview/in_app_webview.dart 323:26                                  [_onPlatformViewCreated]
packages/flutter_inappwebview_web/src/in_app_webview/in_app_webview.dart 304:9                                   <fn>
packages/flutter/src/widgets/_html_element_view_web.dart 65:30                                                   <fn>
dart-sdk/lib/async/zone.dart 1661:54                                                                             runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                                                       handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                                                       handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                                                       _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                                                        [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                                                        callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                                                 _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                                                  _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                                               <fn>

### Flutter version

vr 3.19.5

### Operating System, Device-specific and/or Tool

Chrome

### Plugin version

v6.0.0

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
As the error says, it is not implemented on Web platform
