### ISSUE TITLE
Does Windows webview2 support setting startup parameters, such as --proxy-server

### ISSUE THREAD

**Issue by xiaoma13** [pichillilorenzo/flutter_inappwebview#2429]
### Is there an existing feature request for this?

- [x] I have searched the existing feature request

### Operating System

windows

### Pain

I want to set startup parameters when starting webview2 on Windows, but I couldn't find the configuration option. Is it currently not supported

### Suggested solution

Currently not available

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
You can use additionalBrowserArguments  of  WebViewEnvironmentSettings: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/WebViewEnvironmentSettings-class.html
