### ISSUE TITLE
How to disable zoom feature in iOS?

### ISSUE THREAD

**Issue by SAAVY-ware** [pichillilorenzo/flutter_inappwebview#244]
## iOS

**Flutter version: 1.12.13+hotfix 5** 
**iOS version: 13.2.2** 
**Xcode version: 11.2.1**  
**Device information: iPhone 6s , Simulator 11 pro**

**Comment by MoAbdulmalik16** [comment]
Hi was this issue fixed.

**Comment by kustraslawomir** [comment]
anyone?

**Comment by RamiroGarrido** [comment]
We're having the same issue...any solutions for this problem on iOS?
