### ISSUE TITLE
could you please add sample app codes ?? for macos the main files is empty!!!

### ISSUE THREAD

**Issue by muhsinzyne** [pichillilorenzo/flutter_inappwebview#2440]
### Is there an existing feature request for this?

- [X] I have searched the existing feature request

### Operating System

macos

### Pain

could you please add sample app codes ?? for macos the main files is empty!!!

### Suggested solution

could you please add sample app codes ?? for macos the main files is empty!!!

### Useful resources

could you please add sample app codes ?? for macos the main files is empty!!!

### Additional information

could you please add sample app codes ?? for macos the main files is empty!!!

### Self grab

- [X] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
The example code is already available at `flutter_inappwebview/example`: https://github.com/pichillilorenzo/flutter_inappwebview/tree/master/flutter_inappwebview/example

Also, you can use all the docs available on the official website, for example: https://inappwebview.dev/docs/webview/in-app-webview
