### ISSUE TITLE
InAppWebView failed to record audio on the Windows platform. Is it not supported?

### ISSUE THREAD

**Issue by efanlee** [pichillilorenzo/flutter_inappwebview#2444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No audio stream has been captured.

In the script, The AudioContext, getUserMedia, createMediaStreamSource, and createScriptProcessor have all been successfully called.
When microphone function is opened, the headphones can already hear a "rustling" sound of electric current (which disappears when the microphone is stopped, so the microphone is confirmed to be properly opened).
However, the scriptProcessor.onaudioprocess() callback is not executed. So cannot capture the audio stream.

I confirmed that permissions are enabled. The same code runs normally on macOS and Android.

### Expected Behavior

The callback code in scriptProcessor.onaudioprocess() should be executed, and audio stream is captured

### Steps with code example to reproduce

```
const constraints = {
    audio: {
      sampleRate: 24000,
      channelCount: 1,
      echoCancellation: true,
      noiseSuppression: true
  }
};

stream = await navigator.mediaDevices.getUserMedia(constraints);
audioContext = new (window.AudioContext || window.webkitAudioContext)({
  sampleRate: 24000,
});

audioInput = audioContext.createMediaStreamSource(stream);
scriptProcessor = audioContext.createScriptProcessor(4096, 1, 1);

scriptProcessor.onaudioprocess = function(audioProcessingEvent) {
  const inputBuffer = audioProcessingEvent.inputBuffer;
  // Some other codes...
  window.flutter_inappwebview.callHandler('onAudioData', pcmData);
};

audioInput.connect(scriptProcessor);
scriptProcessor.connect(audioContext.destination);
```

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
<Replace this line by pasting your stacktrace or logs here>
```
</details>

### Flutter version

v3.24.0

### Operating System, Device-specific and/or Tool

Windows 11 with VS code 2022
macOS 15.1.1 with Xcode 16.1

### Plugin version

v6.1.0, v6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
It seems that the `scriptProcessor.onaudioprocess` event is Deprecated, check for more details and alternatives on the official js docs: https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode/audioprocess_event

**Comment by pichillilorenzo** [comment]
Check also this answer on StackOverflow for other possible examples: https://stackoverflow.com/questions/65447236/scriptnode-onaudioprocess-is-deprecated-any-alternative

**Comment by liyifa-efan** [comment]
> It seems that the `scriptProcessor.onaudioprocess` event is Deprecated, check for more details and alternatives on the official js docs: https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode/audioprocess_event

I've tried using AudioWorklet to capture audio stream, but it seems it's not supported: AbortError: Unable to load a worklet's module

**Comment by efanlee** [comment]
> It seems that the `scriptProcessor.onaudioprocess` event is Deprecated, check for more details and alternatives on the official js docs: https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode/audioprocess_event

I've tried using AudioWorklet to capture audio stream, but it seems it's not supported: AbortError: Unable to load a worklet's module

**Comment by efanlee** [comment]
I have solved this problem, the audioContext.state is suspended by default. Call audioContext.resume() and it is OK now
