### ISSUE TITLE
Is Headless Browsing supported?

### ISSUE THREAD

**Issue by lambasoft** [pichillilorenzo/flutter_inappwebview#245]
I would like to use the browser to fetch some data from a page, without showing the browser, aka headless mode.

Do I have to hide the InAppWebView in a Visibility class, or can I initialize it in a headless state so I could use it in a repository or Bloc pattern

**Comment by bpbunthoeun** [comment]
I want to hide the title tab as well please let me know about how to do it. thanks

**Comment by pichillilorenzo** [comment]
Added support with new released version `3.1.0` right now! Use the `HeadlessInAppWebView` class to create a WebView in headless mode.
An example can be found in the [README.md](https://github.com/pichillilorenzo/flutter_inappwebview#headlessinappwebview-class) file or in the example folder.
