### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'callHandler')

### ISSUE THREAD

**Issue by guptavirendra** [pichillilorenzo/flutter_inappwebview#2453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on flutter web I am facing this issue

<fn>
Highcharts warning #15: www.highcharts.com/errors/15/
null
null
null
null
TypeError: Cannot read properties of undefined (reading 'callHandler')
data:... 96:24                                      selection
https://code.highcharts.com/highcharts.js 9:2533    <fn>
https://code.highcharts.com/highcharts.js 9:2511    j
https://code.highcharts.com/highcharts.js 9:219252  transform
https://code.highcharts.com/highcharts.js 9:136902  drop
https://code.highcharts.com/highcharts.js 9:141988  onDocumentMouseUp

### Expected Behavior

Due to this, I am unable to handle zoom feature of highcharts.

### Steps with code example to reproduce

_controller?.addJavaScriptHandler(
                      handlerName: 'handlerFooWithArgs',
                      callback: (args) {
                        print('args: $args');
                        if (widget.selectedArguments != null) {
                          widget.selectedArguments!(args);
                        }

                        // it will print: [1, true, [bar, 5], {foo: baz}, {bar: bar_value, baz: baz_value}]
                      });
                },

### Stacktrace/Logs

[_completeWithValue]
../dart-sdk/lib/async/future_impl.dart 736:7
callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11
_microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5
_startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7
<fn>
Highcharts warning #15: www.highcharts.com/errors/15/
null
null
null
null
TypeError: Cannot read properties of undefined (reading 'callHandler')
data:... 96:24                                      selection
https://code.highcharts.com/highcharts.js 9:2533    <fn>
https://code.highcharts.com/highcharts.js 9:2511    j
https://code.highcharts.com/highcharts.js 9:219252  transform
https://code.highcharts.com/highcharts.js 9:136902  drop
https://code.highcharts.com/highcharts.js 9:141988  onDocumentMouseUp

### Flutter version

Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision 2663184aa7 (2 months ago) • 2024-09-11 16:27:48 -0500 Engine • revision 36335019a8 Tools • Dart 3.5.3 • DevTools 2.37.3

### Operating System, Device-specific and/or Tool

mac os 

### Plugin version

flutter_inappwebview: ^6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
Please, read the documentation before posting an issue. Currently, web platform doesn’t support JavaScript handlers.
With the next plugin version 6.2.0, it should be available, but, as always on web platform, it will require same origin
