### ISSUE TITLE
Does not work on iOS 17.5 iPhone 15 Pro Max

### ISSUE THREAD

**Issue by karmicdice** [pichillilorenzo/flutter_inappwebview#2455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Loads the webview but cannot start the page load

### Expected Behavior

Load the page

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart
InAppWebView(
                    initialUrlRequest: URLRequest(
                      url: WebUri('https://www.example.com')
                    ),
                        initialSettings: InAppWebViewSettings(
                          javaScriptEnabled: true,
                          clearCache: true,
                          transparentBackground: true,
                          supportZoom: false,
                          allowFileAccessFromFileURLs: true,
                          allowUniversalAccessFromFileURLs: true,
                          useHybridComposition: true,
                        ),
                    onWebViewCreated: (controller) {
                      print('WebView created successfully');
                    },
                    onLoadStart: (controller, url) {
                      print('Page started loading: $url');
                    },
                    onLoadStop: (controller, url) {
                      print('Page finished loading: $url');
                    },
                    onLoadError: (controller, url, code, message) {
                      print('Load Error: code $code, message: $message');
                    },
                    onReceivedError: (controller, request, error) {
                      print('Received Error: ${error.description}');
                    },
                    onConsoleMessage: (controller, consoleMessage) {
                      print('Console Message: ${consoleMessage.message}');
                    },
                  )
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
flutter: WebView created successfully
[IOSInAppWebViewWidget] (iOS) IOSInAppWebViewWidget ID 0 calling "onWebViewCreated" using []
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onUpdateVisitedHistory" using {url: https://example.com/, isReload: null}
```
</details>

### Flutter version

3.24.5

### Operating System, Device-specific and/or Tool

iOS 17.5

### Plugin version

6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by cade-2** [comment]
same here ios 18.0 iphone 16 not load

**Comment by crazecoder** [comment]
useShouldOverrideUrlLoading: false

**Comment by pichillilorenzo** [comment]
Please post full minimal code to reproduce the issue. 
@cade-2 in your case, it seems it could be caused by something not set correctly on your Flutter code, as the widget seems to be rebuilt every time.
Are you using Keys correctly? Maybe use a GlobalKey or try to understand why your widget tree is being rebuilt.

**Comment by karmicdice** [comment]
> Please post full minimal code to reproduce the issue. @cade-2 in your case, it seems it could be caused by something not set correctly on your Flutter code, as the widget seems to be rebuilt every time. Are you using Keys correctly? Maybe use a GlobalKey or try to understand why your widget tree is being rebuilt.

Somehow it fixed itself for me. Oh yes, I did upgrade the Android Studio and performed a flutter upgrade. Maybe that fixed it... I have no idea what went down.
