### ISSUE TITLE
Blob download is not possible

### ISSUE THREAD

**Issue by SoroushBeigi** [pichillilorenzo/flutter_inappwebview#2459]
### Is there an existing feature request for this?

- [X] I have searched the existing feature request

### Operating System

All platforms if possible

### Pain

Downloading blob (straight files from database without being hosted anywhere) shows weird behavior (downloading file with wrong name and format, usually under a kilobyte)

### Suggested solution

I managed to fix this on my own project by using a js function and returning base64 to flutter side and saving that. I'm willing to start working on this if you find it a good solution

### Self grab

- [X] I'm ready to work on this issue!

**Comment by pichillilorenzo** [comment]
This is something that depends on how native webview works.
For example, Android WebView: https://stackoverflow.com/a/76069824

So, it seems to be something that should be managed by the developer and not this plugin.
As you may know, a WebView is not a browser, please read: https://inappwebview.dev/docs/intro#what-is-a-webview-differences-between-a-webview-and-a-browser

**Comment by SoroushBeigi** [comment]
ok, thanks for clarification.
I'm closing this then
