### ISSUE TITLE
window.close() is not closing InAppBrowser

### ISSUE THREAD

**Issue by themisir** [pichillilorenzo/flutter_inappwebview#251]
When `window.close()` called by default ChromeSafariBrowser closes but InAppBrowser is not closing.

**Comment by MingSern** [comment]
Any solution to this? @themisir

**Comment by themisir** [comment]
> Any solution to this? @themisir

I'm not sure, it was long time ago sorry. I might have switched to some other package. Back then flutter's webview wasn't that great, but now I think they fixed a bunch of issues, so it might worth giving a try.

**Comment by TheRedSpy15** [comment]
Still having the issue here
