### ISSUE TITLE
can not open some website

### ISSUE THREAD

**Issue by Flipped-OvO** [pichillilorenzo/flutter_inappwebview#252]
target :
https://hgm.lovehg6.com/?sid=K4tkKqf8%2BXNM73x9toWVLLlAE4uSMGywdJi2yKw%2FaH19U8vTiA8%2BQDWJNpFZfebK6QEdG6o3lMKdgcsXNBtt189ORaJY9HkD5%2FLaWuioDZdBPiP5F7UnBgvCKk5iiHWltxF2CQD70zPoWKGd3CVHSIKDdXy3k86w3ZGaHv5L58M%3D&line=g9991

can not open this website , i get white screen on my device

**Comment by koteezy** [comment]
+1

**Comment by qrila** [comment]
At least on Android you need `AndroidInAppWebViewOptions(domStorageEnabled: true)`, I also needed to create apk with `--no-shrink` flag it to work with release package.

**Comment by koteezy** [comment]
> At least on Android you need `AndroidInAppWebViewOptions(domStorageEnabled: true)`, I also needed to create apk with `--no-shrink` flag it to work with release package.

I can confirm that.

Thanks a lot!
