### ISSUE TITLE
How to hide the keyboard

### ISSUE THREAD

**Issue by zhaojingadmin** [pichillilorenzo/flutter_inappwebview#253]

**Comment by aznh** [comment]
`
GestureDetector(
    onTap: () {
        SystemChannels.textInput.invokeMethod('TextInput.hide');
    },
    child: // your webview widget
)
`

This will help you

**Comment by zhaojingadmin** [comment]
This solution I know, what I want to solve now is that when I use inappwebview, when I click the input box to turn on the keyboard, it cannot be turned off automatically

**Comment by aznh** [comment]
> This solution I know, what I want to solve now is that when I use inappwebview, when I click the input box to turn on the keyboard, it cannot be turned off automatically

How about add "blur" event to your input box? And then you can call 'TextInput.hide' method in your flutter code

**Comment by julianramireze** [comment]
> ```
> GestureDetector(
>     onTap: () {
>         SystemChannels.textInput.invokeMethod('TextInput.hide');
>     },
>     child: // your webview widget
> )
> ```
> 
> This will help you

This really work
