### ISSUE TITLE
WebRTC background process

### ISSUE THREAD

**Issue by Soda-Flavour** [pichillilorenzo/flutter_inappwebview#257]
## Environment

**Flutter version:**  Channel stable, v1.12.13+hotfix.5
**Plugin version:**  2.1.0 
**Device information:**  Samsung Galaxy note 8

Hello~!
I implemented WebRTC using Janus-Gateway, and I use only voice except video.
I'm going to create a state of communication in the background.
However, voice communication slows down after about 30 seconds in the background.
If you come back up to the foreground, the slowdown will disappear.
Interval functions that come from the Web view in the background work without a problem
Is this a problem with web views?

**Comment by iampato** [comment]
I would encourage to you to take a look at `Flutter_background` pkg
