### ISSUE TITLE
Zoom not working on android, java error on zoomBy method

### ISSUE THREAD

**Issue by PijusPaulikas** [pichillilorenzo/flutter_inappwebview#258]
## Environment

flutter doctor -v        
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)    • Flutter version 1.12.13+hotfix.5 at /home/pijus/flutter/flutter    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800    • Engine revision 2994f7e1e6    • Dart version 2.7.0 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)    • Android SDK at /home/pijus/Android/Sdk    • Android NDK location not configured (optional; useful for native profiling support)    • Platform android-29, build-tools 29.0.2    • Java binary at: /home/pijus/Downloads/android-studio-ide-191.5900203-linux/android-studio/jre/bin/java    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /home/pijus/Downloads/android-studio-ide-191.5900203-linux/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

## Description
```
double zoomFactor = 100;
controller.zoomBy(zoomFactor);
```

**Expected behavior:** 
Zooms successfuly

**Current behavior:** 
Throws error:
`PlatformException (PlatformException(error, java.lang.Double cannot be cast to java.lang.Float, null))`

Also pich to zoom does not work

**Comment by pichillilorenzo** [comment]
Fixed in the new version `3.0.0`.
