### ISSUE TITLE
location.setItem() is not working in onLoadStart in iOS safari and working properly in Android. 

### ISSUE THREAD

**Issue by Sunsiha** [pichillilorenzo/flutter_inappwebview#268]
I have a use case where I have to set data in localStorage before the page loads. So I have written evaluateJavascript in onLoadStart() function and setting localStorage before the page loads. It's working fine in Android InAppWebView. But in IOS WebView its throwing error "security error. The operation is insecure". But when I run same javascript in onLoadStop localStorage.setItem() is working properly. But if I set data in onLoadStop() the page is loading first and data is being later. The webpage works like it checks for authenticationToken and Id in localStorage and if it's doesn't find them, it will redirect to signIn page. So, If I set data in onLoadStop the webpage is loading first  and redirecting to signIn page and then after redirecting data is being set into localStorage. If I go back out of WebView and open webView again, Then the data will be there in localStorage.

```
await controller.evaluateJavascript(
                        source: "(function() { try { "
                            "localStorage.setItem('DEVICE', JSON.stringify('${device}'));"
                        
                            "} catch (err) {  } })();");
```

**Comment by victorers1** [comment]
I think this was answered by  #582 and #585.

I tried to do the same but ended up having to wait for the screen to load for the first time, then I added data to localstorage, then reloaded the page with `webViewController.reload();`
