### ISSUE TITLE
Issue on intercepting ajax request

### ISSUE THREAD

**Issue by ariefaprilianto** [pichillilorenzo/flutter_inappwebview#269]
I got problem intercepting ajax request when adding some additional header. If I remove the header addition, request would be continued, otherwise request was stopped.

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8) 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.35.0)

flutter_inappwebview: ^2.1.0+1

```
android: AndroidInAppWebViewOptions(
    domStorageEnabled: true,
    databaseEnabled: true,
    clearSessionCache: false,
),
crossPlatform: InAppWebViewOptions(
    userAgent: DotEnv().env['DEFAULT_UA'],
    debuggingEnabled: true,
    javaScriptCanOpenWindowsAutomatically: true,
    preferredContentMode: InAppWebViewUserPreferredContentMode.MOBILE,
    useShouldInterceptAjaxRequest: true,
    useShouldInterceptFetchRequest: true,
)
...
shouldInterceptAjaxRequest: (InAppWebViewController controller, AjaxRequest ajaxReq) async {
    print("ajaxReq.url: ${ajaxReq.url}");
    
    ajaxReq.headers.setRequestHeader("someheader", "somevalue");
    
    return ajaxReq;
},
```

**Comment by ariefaprilianto** [comment]
It's solved. Actually it just get blocked by CORS policy at the preflight.

**Comment by leielyq** [comment]
@ariefaprilianto hello,how to fix

**Comment by norman93sun** [comment]
> It's solved. Actually it just get blocked by CORS policy at the preflight.

Hi there,
Could you tell me how to fix this?
