### ISSUE TITLE
AndroidX build incompatibilities failed even on new flutter app with androidx

### ISSUE THREAD

**Issue by dmvasheka** [pichillilorenzo/flutter_inappwebview#274]
Build fails with this error even for a new application with androidx
## Environment

**Flutter version:** 1.12.13+hotfix.5
**Plugin version:**  2.1.0+1
**Android version:**  Platform android-29, build-tools 28.0.3
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**Expected behavior:** build completed

**Current behavior:** build failed

## Steps to reproduce

run command `flutter build apk --split-per-abi`

## Images 
![Без названия](https://user-images.githubusercontent.com/13748224/73267563-fd386500-41e1-11ea-93f8-ae07e784c13a.png)
![image](https://user-images.githubusercontent.com/13748224/73267969-bdbe4880-41e2-11ea-8385-1b15e931c97d.png)

## LOG

Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      85,4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve
the incompatibility.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                   11,6s
√ Built build\app\outputs\repo.
Building plugin flutter_inappwebview...
The plugin flutter_inappwebview could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...

**Comment by cacing69** [comment]
how u fix this issue
