### ISSUE TITLE
Issue with launching the release version of the app with plugin

### ISSUE THREAD

**Issue by dmvasheka** [pichillilorenzo/flutter_inappwebview#276]
I encountered the problem of launching a release version of an application with this plugin.
## Environment

**Flutter version:** 1.12.13+hotfix.5
**Plugin version:**  2.1.0+1
**Android version:**  Platform android-29, build-tools 28.0.3
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**Expected behavior:** app was launched

**Current behavior:** app wasnt launched

## Images 
![image](https://user-images.githubusercontent.com/13748224/73650399-c69f9600-468a-11ea-803d-903a576d425f.png)

## LOG

02-03 12:43:49.273 18441 18441 E AndroidRuntime: FATAL EXCEPTION: main
02-03 12:43:49.273 18441 18441 E AndroidRuntime: Process: com.example.rrr2, PID: 18441
02-03 12:43:49.273 18441 18441 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.rrr2/com.example.rrr2.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'd.a.b.a.d d.a.b.a.p$d.e()' on a null object reference
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2919)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:198)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6732)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-03 12:43:49.273 18441 18441 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'd.a.b.a.d d.a.b.a.p$d.e()' on a null object reference
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at com.pichillilorenzo.flutter_inappwebview.j.<init>(Unknown Source:23)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at com.pichillilorenzo.flutter_inappwebview.q.a(Unknown Source:4)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at io.flutter.embedding.engine.e.a(Unknown Source:33)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:26)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at com.example.rrr2.MainActivity.a(Unknown Source:5)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at d.a.a.a.h.a(Unknown Source:64)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at d.a.a.a.e.onCreate(Unknown Source:22)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7173)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7164)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
02-03 12:43:49.273 18441 18441 E AndroidRuntime:        ... 11 more

**Comment by wwwdata** [comment]
Made a fix for this, it was caused by using reflection, which doesn't work in prod, look here: #295
