### ISSUE TITLE
Js window.print() make my app crash

### ISSUE THREAD

**Issue by NaufalHafizi** [pichillilorenzo/flutter_inappwebview#278]
## Environment

**Flutter version: 1.12.13+hotfix 7 
**Plugin version: from github master branch (Latest commit 9c7ac0d on Dec 17, 2019)
**Android version: 9

**Device information: xiaomi pocophone

## Description

**Expected behavior: should didn't do nothing

**Current behavior: app crashed after click

## Steps to reproduce

1. Go to website that use a command window.print() javascript;
2. Click print button
3. The app crash

**Comment by pichillilorenzo** [comment]
It should be fixed with latest release.
