### ISSUE TITLE
Problem with loading some links - iOS

### ISSUE THREAD

**Issue by dudizimber** [pichillilorenzo/flutter_inappwebview#279]
## Environment

Flutter version: 1.12.13+hotfix.5 • channel stable •

  flutter_inappwebview: 
    git: 
      url: https://github.com/pichillilorenzo/flutter_inappwebview
      ref: develop

iOS version: 13.3
Xcode version: 11.3
Device information: iPhone 11 Pro Max (Simulator)

## Description
It doesn't load some urls. For example, when login to google, after writing your email, it keeps loading forever.

The output message is
`Runner[43622:11712651] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service`

Expected behavior: Load the url

Current behavior: Not loading the url

**Comment by nemoryoliver** [comment]
Experiencing the same loading facebook.com on iOS

**Comment by dudizimber** [comment]
> 
> 
> Experiencing the same loading facebook.com on iOS

Did you tried in a physical device or just in the simulator?

**Comment by nemoryoliver** [comment]
I used a real device. Haven't tried it on the simulator yet.

**Comment by aleksandar-radivojevic** [comment]
@nemoryoliver any updates bro? 🍗 🔥

**Comment by nemoryoliver** [comment]
> @nemoryoliver any updates bro? 🍗 🔥

same thing.. some links are still broken

**Comment by whatamelon** [comment]
When I loading embeded youtube video with youtube api, console give to me same issue and youtube video just broken in IOS. Is there any solution?

**Comment by NiranjanShah** [comment]
Same thing, some links are not working on iOS, request quick solution.

**Comment by pichillilorenzo** [comment]
I tested and I have no problem with google or facebook logins.

Could you share the links that are not working??

Also, you need to consider that if the links are something like `<a href="https://myLink" target="_blank">myLink</a>`, then to capture links with `target="_blank"`, you need to use the `onCreateWindow` event and then decide there if you want open a new WebView or load the link in the current WebView.

Instead, if you need support to HTTP requests (non-HTTPS), you need to check the "Support HTTP request" section, under the [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios) section.

**Comment by NiranjanShah** [comment]
Thanks for the response, however, the same link with url_launcher, it is working fine.

**Comment by pichillilorenzo** [comment]
@NiranjanShah Could you share the link? Otherwise, I can't test it.
