### ISSUE TITLE
YouTube embedded player in webview

### ISSUE THREAD

**Issue by velsa** [pichillilorenzo/flutter_inappwebview#28]
I've set the option `'mediaPlaybackRequiresUserGesture': false`, but youtube player still doesn't autostart. I'm emeding YouTube player in webview by opening a url `https://www.youtube.com/embed/Mz3kHQxBjGg?autoplay=1`

Any ideas on how to make it autoplay in the webview?

**Comment by SteadyAction** [comment]
Same issue!

**Comment by SteadyAction** [comment]
@pichillilorenzo

**Comment by maltub9** [comment]
I encounter an issue when I click on full screen button inside the youtube video. the app crush after that. what is the solution for this?

**Comment by pichillilorenzo** [comment]
@maltub9 please post the error log you get, otherwise I can't fix it. Also, if possible, post the code you are using to show the youtube video in order to debug it. Thanks

**Comment by mind-easy** [comment]
I still have the same issue. Is there a solution for this?

**Comment by water-user** [comment]
Same here. Here's the code:

```
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      ));
```

```
  @override
  Widget build(BuildContext context) {
    return InAppWebView(
      key: webViewKey,
      initialUrlRequest: URLRequest(
        url: Uri.parse('https://www.youtube.com/embed/q_dsgjGRBsw?autoplay=1'),
      ),
      initialOptions: options,
      onWebViewCreated: (controller) {
        webViewController = controller;
      },
    );
  }
```
