### ISSUE TITLE
Blank rectangle on Android SDK 19 or lower

### ISSUE THREAD

**Issue by danieeelfc** [pichillilorenzo/flutter_inappwebview#284]
Flutter 1.12.13+hotfix.7
Dart 2.7.0

Hi! It's said on plugin description that it works on android SDK 17 or higher, however it just shows a blank rectangle when run over SDK 17, 18 and 19. I've tested on emulator and on physical device.

flutter_inappwebview version is 2.1.0+1

No error is shown on logcat. Indeed, progressbar seems to be working.

**Comment by devcat-net** [comment]
Same error here. Blank screen and no error message :-/

**Comment by virskor** [comment]
Same

**Comment by gianlucainnocente** [comment]
Same

**Comment by atavci** [comment]
I have a very similar error #418 not sure if it is the exact same one.

**Comment by pichillilorenzo** [comment]
In general, this plugin requires Android 17+.

For `InAppWebView` widget is supported only on Android 20+.
Unfortunately, this is a restriction of Flutter API: https://api.flutter.dev/flutter/widgets/AndroidView-class.html
and I can't do anything about that.
Here is an open issue on the official Flutter repo about that: https://github.com/flutter/flutter/issues/23728

I have also updated the README.md about that.
