### ISSUE TITLE
Using flutter_inwebview when i  pressing back button Application getting closed.

### ISSUE THREAD

**Issue by gods-mack** [pichillilorenzo/flutter_inappwebview#287]
I'm trying to use a webview in flutter  for my application. Everything loads just fine, however hitting the back button doesn't send me to the previous web page in the webview, it just exits the application.

**Comment by m-oehme** [comment]
Do you use InAppBrowser or InAppWebView?
InAppBrowser will go back when you press the backbutton. The InAppWebView on the other hand does not. You have to implement it yourself. Its like the native WebView on Android.
