### ISSUE TITLE
Camera file Upload

### ISSUE THREAD

**Issue by gianlucainnocente** [pichillilorenzo/flutter_inappwebview#290]
## Environment: Android

**Flutter version: v1.12.13+hotfix.7
**Plugin version: 2.1.0+1
**Android version: Android 7, Android 8, Android 9, Android 10
**Device information: Galaxy S6, Galaxy s7, Galaxy S8, Galaxy S10

## Description
**Expected behavior: When i tap on a <input type="file" /> it should ask to choose between taking photo from camera or select file from storage.

**Current behavior: It goes directly to the file storage, so i can't take a photo using camera. (on ios works well)

## Steps to reproduce
1. Open a website with a simple <input type="file" /> field;
2. Tap on the input field.

**Comment by pichillilorenzo** [comment]
Feature added within release `3.3.0`.

**Comment by marcoheine** [comment]
Same problem with v4.0.0+4 :-(

**Comment by barilki** [comment]
Any updates? version 6.0.0
