### ISSUE TITLE
Close ChromeSafariBrowser programmatically

### ISSUE THREAD

**Issue by jkyon** [pichillilorenzo/flutter_inappwebview#299]
**Flutter version: v1.12.13+hotfix.8 
**Plugin version:**  2.1.0+1  
**Android version:**  API 21 or upper
**iOS version: 12 or upper
**Xcode version:**  

It is nice to have a method to close the tab programmatically. it is usefull specially when you are using Oauth2 Code Grant method which requires to return the control to the app when user complete the login process on browser tab. In this case is required to close the browser tab automatically to get the auth token on native app. 

thank you in adavance, this plugin is amazing

**Comment by pichillilorenzo** [comment]
Support added with new released version `3.1.0` right now!
