### ISSUE TITLE
Get cookies

### ISSUE THREAD

**Issue by hungps** [pichillilorenzo/flutter_inappwebview#3]
How to get cookies?

**Comment by pichillilorenzo** [comment]
There isn't a method to get cookies from native webview at the moment, but I can add this feature in the new release (I think I will release it these days)!

However have you tried using javascript like so:
```dart
  @overidde
  Future onLoadStop(String url) async {
    print(await this.injectScriptCode("document.cookie"));
  }
```
Maybe this could work for now.

**Comment by scitbiz** [comment]
It works. Thanks!
