### ISSUE TITLE
【just give up this plugin!!】同胞们注意了，ios下极度不稳定，android下表现很一般，目前似乎作者已放弃这个插件

### ISSUE THREAD

**Issue by ber6789** [pichillilorenzo/flutter_inappwebview#303]
同胞们注意了!!，ios下极度不稳定，android下表现很一般，目前似乎作者已放弃这个插件
我关注以及使用这个插件很久了，然后并且投入了实际的生产使用当中，
然后，我想说的是，真的坑了，安卓时而页面就没了，ios只要待机时间长了，页面全部消失，而且这个问题似乎是flutter底层问题，本人目前已考虑重构。如果非要使用webview，建议 flutter_webview_plugin ，但即使这样，我个人也非常不推荐，作为过来人，真心提醒下，flutter+webview是个大坑，各位尽量放弃吧

**Translations is below:**

Attentions bros!! ,  this plugin performs really unstablelly in ios ，not good in android ,  and it seems that the owner of this plugin has been disappeared for a long time , as well as  I have been watching this plugin really long, And I use it  in my app which has been published.   unforturnatelly ,  this plugin performs really bad that  the webviews  will disappeared without sake when user stay their phone wake for a period.  And also I have no idea what causes this problem . I guess this may due to something with the base of flutter.   And I am planning to remake my app although I am not willing to  do all of this.    If you really need  webview in flutter ,  you may try another plugin called "flutter_webview_plugin" ( Although I still strongly not recommand ) .  Sincerely , you guys should give up webviews in flutter , which could really mess your app up ,  at least for now

**Comment by Karatla** [comment]
@ber6789

我也关注很久了，从圣诞节开始作者就没有更新过了，一直都觉得他这个插件做的挺好，真的很可惜，我也有项目在用，现在，不得不停下来.
如果你考虑重构，请一定要通知我，我需要这样的插件，wechat:SupYogurt

**Comment by LittleCai** [comment]
@ber6789 现在我们项目也是用flutter开发，也需要用到webview，不过是用的官方插件webview_flutter，基本能满足需求了，但还是有点小问题，在安卓上滑动就是感觉会掉帧，不能像原生webview那么流畅，头痛。不知道你有没有研究过官方的插件。

**Comment by aboutmydreams** [comment]
some problem: my wx :abouthomeloving

**Comment by gkblack** [comment]
唉，我也是，安卓上的页面有时会加载空白，有其它的推荐麽，现在都在试用阶段了

**Comment by lhcdims** [comment]
Yes, the example can't be run, you can't even compile it without changing some codes in the example/lib, I guess the writer has given up this plugin, don't use it unless you are going to rewrite the whole plugin yourself.

**Comment by ber6789** [comment]
> @ber6789 现在我们项目也是用flutter开发，也需要用到webview，不过是用的官方插件webview_flutter，基本能满足需求了，但还是有点小问题，在安卓上滑动就是感觉会掉帧，不能像原生webview那么流畅，头痛。不知道你有没有研究过官方的插件。

flutter_webview_plugin 即使用，也是推荐这个，而不是官方的那个

**Comment by aboutmydreams** [comment]
我的可以了，我详细的看了下api文档：https://pub.dev/documentation/flutter_inappwebview/latest/
@gkblack

**Comment by pichillilorenzo** [comment]
Published new version `3.0.0` right now!

**Comment by ber6789** [comment]
awesome man! you 're great!! I love u!!

**Comment by onewkl** [comment]
> awesome man! you 're great!! I love u!!

嫁了吧兄弟。marry him
