### ISSUE TITLE
style/Theme.AppCompat.Light not found.

### ISSUE THREAD

**Issue by MohammedYAmmar** [pichillilorenzo/flutter_inappwebview#307]
## Environment

**Flutter version:*1.12.13* 
**Plugin version:*2.1.0+1*    
**Android version:*3.3.2*    

 error: failed linking references.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 11s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_inappwebview...
The plugin flutter_inappwebview could not be built due to the issue above.## Stacktrace/Logcat

**Comment by pichillilorenzo** [comment]
Try the new version `3.0.0`!
