### ISSUE TITLE
WebView is Not Scrollable

### ISSUE THREAD

**Issue by divrse** [pichillilorenzo/flutter_inappwebview#316]
## Environment

**Flutter version:**  1.12.13 stable
**Plugin version:**  ^2.1.0+1
**Android version:**    
**iOS version:** 13.3
**Xcode version:**  11.3.1
**Device information:** Iphone 11 Max simulator
## Description
When I create a webview in my app, I expect the content to be scrollable,
but when I try to scroll within it, since the container of the webview is a descendent of SingleChildScrollView, the scroll happens on my page content, not the webview (yes, im scrolling within the actual content and not page).
**Expected behavior:** 

The webview should scroll down the contents of the website.

**Current behavior:** 
The actual flutter page that has SingleChildScrollView gets scrolled instead.

## Steps to reproduce

Create a component that looks like this
```dart
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
                Container(child:InAppWebView),
Container(child:otherpartofpage)
])
```

# Another Note
Im interested in running this plugin on Xcode 10.2, what properties do I have to modify in source code  besides the isFraudelent option? Thanks

**Comment by divrse** [comment]
Another Potential bug Ive noticed, sharedCookiesEnabled set to false doesn't seem to make the session not save the cookies, which is expected behavior.
The cookies still get saved and applied on subsequent applications of the code.

**Comment by pichillilorenzo** [comment]
You can try the latest release.
Also, you can apply the `EagerGestureRecognizer` gesture recognizer to the `InAppWebView` widget:
```dart
var gestureRecognizers = <Factory<OneSequenceGestureRecognizer>>[
	Factory<OneSequenceGestureRecognizer>(
		() => EagerGestureRecognizer(),
	),
].toSet();
```
