### ISSUE TITLE
Webview is Crashing 

### ISSUE THREAD

**Issue by ravitejaavv** [pichillilorenzo/flutter_inappwebview#317]
I am using latest 2.1.0+1 version. Below is the crash details
Flutter 1.12.13+hotfix.9 • channel stable

W/System.err(29735): java.lang.ClassCastException: $Proxy2 cannot be cast to android.view.WindowManagerImpl
W/System.err(29735): 	at android.view.Window.setWindowManager(Window.java:771)
W/System.err(29735): 	at android.view.Window.setWindowManager(Window.java:752)
W/System.err(29735): 	at android.app.Dialog.<init>(Dialog.java:194)
W/System.err(29735): 	at android.app.AlertDialog.<init>(AlertDialog.java:201)
W/System.err(29735): 	at android.app.AlertDialog$Builder.create(AlertDialog.java:1088)
W/System.err(29735): 	at CK2.a(PG:3)
W/System.err(29735): 	at dt2.<init>(PG:5)
W/System.err(29735): 	at org.chromium.content.browser.input.SelectPopup.show(PG:12)
W/System.err(29735): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(29735): 	at android.os.MessageQueue.next(MessageQueue.java:325)
W/System.err(29735): 	at android.os.Looper.loop(Looper.java:142)
W/System.err(29735): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
W/System.err(29735): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(29735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err(29735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
F/chromium(29735): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
F/libc    (29735): Fatal signal 5 (SIGTRAP), code -6 in tid 29735 (g.insurance.dev), pid 29735 (g.insurance.dev)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'motorola/potter_n/potter_n:8.1.0/OPS28.85-17-6-2/77e7:user/release-keys'
Revision: 'p3b0'
ABI: 'arm'
signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
'
    r0 00000000  r1 00000000  r2 7fffffff  r3 00000000
    r4 befd4914  r5 0000004f  r6 9daaa438  r7 0000004f
    r8 befd4d60  r9 befd4d64  sl b0f741b8  fp befd4914
    ip befd48c8  sp befd4900  lr b0f23ee1  pc 9bd36fa0  cpsr 60070030
backtrace:
    #00 pc 013f6fa0  /data/app/com.android.chrome-nJ02ij-37A9S2hjG36fCeg==/base.apk (offset 0xb98000)
Lost connection to device.

**Comment by pichillilorenzo** [comment]
Try the new version `3.0.0`!
