### ISSUE TITLE
incognito mode is broken swift

### ISSUE THREAD

**Issue by divrse** [pichillilorenzo/flutter_inappwebview#320]
incognito mode sets
```swift
configuration.websiteDataStore = WKWebsiteDataStore.nonPersistent()
```
This feature from apple allows you to run multiple webviews independent of shared cookies that only exist in memory.

However, this feature is completely broken due to a bug with swift.

When you initalize a webview with no websiteDataStore property, if you try to change it to noPersistent later it won't work.

The way this codebase works is when InAppWebview is created, init() creates a webview with no default options, thus doing exactly as the bug suggests.

I have modified the codebase and almost got it working correctly for myself, but there is another issue such as the actual options are nil within init so you kind of have to just set one and hope the other persists if you want to change it later.

**Comment by pichillilorenzo** [comment]
Could you explain it more? What bug? Which part of the code did you change? Thanks!

**Comment by pichillilorenzo** [comment]
New version `3.3.0+3` released!
