### ISSUE TITLE
Web view not asking for Audio (Microphone) and Video (Camera) permissions when calling a teams meeting link

### ISSUE THREAD

**Issue by Vishruthd92** [pichillilorenzo/flutter_inappwebview#323]
I am trying to call a Microsoft Teams meeting from the meeting link in flutter inappwebview, I am able to render the webpage but I am not able to click on Allow as per the screenshot below to allow audio and video in teams meeting. Can you please help?

![Teams_Meeting_screenshot](https://user-images.githubusercontent.com/58204074/79746661-fbd19100-8327-11ea-9577-d0f91ad3cccd.png)

**Comment by ManKeomorakort** [comment]
I want to access video and microphone via html 5, but it doesn't have permission. any idea please?

**Comment by pichillilorenzo** [comment]
To request permission, you need to use other plugins, such as [permission_handler](https://pub.dev/packages/permission_handler). Asking permission to use video and/or microphone is out of the scope of the WebView.

**Comment by e2haining** [comment]
why it is out of the scope?  does it mean the html5 Microphone and video will not work in this webview plugin?

**Comment by pichillilorenzo** [comment]
@e2haining Yes, they will work, but you need to ask permission. To ask permission, you can use the [permission_handler](https://pub.dev/packages/permission_handler) plugin.
It doesn't make any sense I reinvent the wheel for just asking, for example, camera and microphone. There is already a plugin that does it.

However, my plugin also has the `androidOnPermissionRequest` for Android, that is an event fired when the WebView is requesting permission to access the specified resources (that is the Android native [`WebChromeClient.onPermissionRequest` event](https://developer.android.com/reference/android/webkit/WebChromeClient#onPermissionRequest(android.webkit.PermissionRequest))).

An example of WebRTC on Android is:
```dart
import 'dart:async';

import 'package:flutter/material.dart';

import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:permission_handler/permission_handler.dart';

Future main() async {
  await PermissionHandler().requestPermissions([PermissionGroup.camera, PermissionGroup.microphone]);
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: InAppWebViewPage()
    );
  }
}

class InAppWebViewPage extends StatefulWidget {
  @override
  _InAppWebViewPageState createState() => new _InAppWebViewPageState();
}

class _InAppWebViewPageState extends State<InAppWebViewPage> {
  InAppWebViewController webView;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: Text("InAppWebView")
        ),
        body: Container(
            child: Column(children: <Widget>[
              Expanded(
                child: Container(
                  child: InAppWebView(
                      initialUrl: "https://appr.tc/r/158489234",
                      initialHeaders: {},
                      initialOptions: InAppWebViewGroupOptions(
                        crossPlatform: InAppWebViewOptions(
                          mediaPlaybackRequiresUserGesture: false,
                          debuggingEnabled: true,
                        ),
                      ),
                      onWebViewCreated: (InAppWebViewController controller) {
                        webView = controller;
                      },
                      onLoadStart: (InAppWebViewController controller, String url) {

                      },
                      onLoadStop: (InAppWebViewController controller, String url) {

                      },
                      androidOnPermissionRequest: (InAppWebViewController controller, String origin, List<String> resources) async {
                        print(origin);
                        print(resources);
                        return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
                      }
                  ),
                ),
              ),
            ]))
    );
  }
}
```

Also, for Android, in the `AndroidManifest.xml`, you need to add these permissions:
```xml
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.VIDEO_CAPTURE" />
<uses-permission android:name="android.permission.AUDIO_CAPTURE" />
```

**Comment by shpy2001** [comment]
> I am trying to call a Microsoft Teams meeting from the meeting link in flutter inappwebview, I am able to render the webpage but I am not able to click on Allow as per the screenshot below to allow audio and video in teams meeting. Can you please help?
> 
> ![Teams_Meeting_screenshot](https://user-images.githubusercontent.com/58204074/79746661-fbd19100-8327-11ea-9577-d0f91ad3cccd.png)

Hi.
Pls, can you share the url, code ? I try to show ms teams meeting in flutter inappwebview but i got err_unknown_url_scheme.
I use "copy meeting link" from host of meeting, and get url like this : https://teams.live.com/meet/000000000000
