### ISSUE TITLE
[iOS] Status bar text is "invisible" when theme brightness set to dark

### ISSUE THREAD

**Issue by shinsenter** [pichillilorenzo/flutter_inappwebview#325]
## Environment

```
flutter doctor -v

[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.5 19F62f, locale ja)
    • Flutter version 1.17.0 at /Users/develop/flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/webike/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
```

## Description

**What you'd like to happen:** 

First of all, I thank you for creating this great plugin. It works very well on both devices running iOS and Android.

However, on iOS, for themes with a brightness property set to dark, when calling ` ChromeSafariBrowser().open(url: url, options: options);`, the text in the status bar remains white, coinciding with the AppBar's background color in the browser, so it cannot be seen.

I want you to add options to adjust the color of the status bar text, or make the plugin can automatically calculate the brightness of the appBar and change the status bar text color accordingly.

Best regards

**Comment by arnaudelub** [comment]
@shinsenter  it's not maintained anymore apparently, we are maintaining a fork of this package flutter_polywebview, feel free to try it, just change the package name, all the rest remain the same

**Comment by shinsenter** [comment]
@arnaudelub 
Thanks for your response, I will check it later. Will you guys fix the issue in your fork?

**Comment by arnaudelub** [comment]
@shinsenter open an issue on the fork and we will try

**Comment by shinsenter** [comment]
@arnaudelub 
Could not create new issue on flutter_polywebview repo.

**Comment by motucraft** [comment]
Is this issue still unresolved? It's been four years.

**Comment by pichillilorenzo** [comment]
@motucraft use the `ChromeSafariBrowserSettings` options to update the whatever color you need on Android and iOS.
Check the API Reference about that: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/ChromeSafariBrowserSettings-class.html
