### ISSUE TITLE
Causes the app to crash on Android Emulator

### ISSUE THREAD

**Issue by owenkealey** [pichillilorenzo/flutter_inappwebview#327]
Please see https://github.com/flutter/flutter/issues/55908 that has all the information needed

**Comment by owenkealey** [comment]
The app works fine without this plugin, with this plugin it crashes.

**Comment by owenkealey** [comment]
Also is this actively maintained?

**Comment by andydean565** [comment]
I don't think it is but have seen in #182 that @arnaudelub has forked this project and seems to have continued some development on it here [flutter_polywebview](https://github.com/arnaudelub/flutter_polywebview)

**Comment by owenkealey** [comment]
@andydean565 thanks, i tried that plugin and while it doesn't crash the app anymore, it wont even build on ios @arnaudelub thoughts?

**Comment by owenkealey** [comment]
Android sees to work fine though which is good

**Comment by nullbytesoftware** [comment]
@owenkealey for me android is fine also, however on ios i get this error -> _".../flutter_polywebview-4.0.0+1/ios/Classes/SwiftFlutterPlugin.swift:465:85: Use of unresolved identifier 'InAppWebViewFlutterPlugin'"_

**Comment by sahharYoucef** [comment]
did you tried to edit your pod file

`target 'Runner' do
  use_frameworks!  # required by simple_permission
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end`

**Comment by andydean565** [comment]
@owenkealey I also ran into this issue on IOS around the name change to 'flutter_polywebview'

my solution was to fork the code and change the name back to 'flutter_inappbrowser' and include it straight from Github in the pubspec.yaml like so

`  
flutter_inappwebview:
    git:
      url: https://github.com/andydean565/flutter_inappwebview.git
`
 feel free to either use my repo or fork it for the time but hopefully, 'flutter_polywebview' will be working soon.

**Comment by arnaudelub** [comment]
Hey guys, iOS build has been fixed but phil also came back, so flutter_inappwebview is still maintained

**Comment by pichillilorenzo** [comment]
Released new version `3.0.0`! Let me know
