### ISSUE TITLE
Not able to run in Android, iOS its working fine.

### ISSUE THREAD

**Issue by do-lokesh** [pichillilorenzo/flutter_inappwebview#332]
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
D/FlutterFragmentActivity(24959): Using the launch theme as normal theme.
D/FlutterFragmentActivity(24959): Creating FlutterFragment with new engine:
D/FlutterFragmentActivity(24959): Background transparency mode: opaque
D/FlutterFragmentActivity(24959): Dart entrypoint: main
D/FlutterFragmentActivity(24959): Initial route: /
D/FlutterFragmentActivity(24959): App bundle path: flutter_assets
D/FlutterFragmentActivity(24959): Will attach FlutterEngine to Activity: true
D/FlutterActivityAndFragmentDelegate(24959): Setting up FlutterEngine.
D/FlutterFragment(24959): Deferring to attached Activity to provide a FlutterEngine.
D/FlutterActivityAndFragmentDelegate(24959): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
W/FlutterEngine(24959): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f1f9340) but could not find and invoke the GeneratedPluginRegistrant.
D/FlutterActivityAndFragmentDelegate(24959): Attaching FlutterEngine to the Activity that owns this Fragment.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:61428/rB6smw8YHIk=/

**Comment by enricodias** [comment]
Same issue here.

**Comment by pichillilorenzo** [comment]
Released new version `3.0.0`!
