### ISSUE TITLE
Unable to access camera and MicroPhone In WebView

### ISSUE THREAD

**Issue by suriyaKalidoss123** [pichillilorenzo/flutter_inappwebview#333]
## Environment
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.19041.207], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)    
[√] Connected device (1 available)  

! Doctor found issues in 1 category.

## Description

**Expected behavior:** 
  Can able to access camera and microphone ,Video call should be done

**Current behavior:** 
Unable to access the camera and microphone,Video call not done

## Steps to reproduce

1.Run the attached sample

## Stacktrace/Logcat   

Attached Sample:
[webview.zip](https://github.com/pichillilorenzo/flutter_inappwebview/files/4570161/webview.zip)

**Comment by pichillilorenzo** [comment]
Please, refer to this https://github.com/pichillilorenzo/flutter_inappwebview/issues/323#issuecomment-629874072 to have an example.

To ask permission, you can use the [permission_handler](https://pub.dev/packages/permission_handler) plugin.
However, my plugin also has the `androidOnPermissionRequest` for Android, that is an event fired when the WebView is requesting permission to access the specified resources (that is the Android native [`WebChromeClient.onPermissionRequest` event](https://developer.android.com/reference/android/webkit/WebChromeClient#onPermissionRequest(android.webkit.PermissionRequest))).

**Comment by suriyaKalidoss123** [comment]
@pichillilorenzo I had tried the above step, but still issue exists.

**Comment by pichillilorenzo** [comment]
Please, try to create a new fresh App and use the full code example of https://github.com/pichillilorenzo/flutter_inappwebview/issues/323#issuecomment-629874072. 
Add `permission_handler: ^5.0.0+hotfix.6` as a dependency to your `pubspec.yaml`.

Does it work if you use it in a new fresh App??
