### ISSUE TITLE
App show local page( show SVG) run on the emulator and doesnt run on Samasung Galaxy S3

### ISSUE THREAD

**Issue by WaelHeader** [pichillilorenzo/flutter_inappwebview#335]
## Environment

**Flutter version:**  1.17
**Plugin version:**  3.1.0 
**Android version:**  Android Jelly Bean 4.3 - API level 18
**iOS version:**
**Xcode version:**  
**Device information:**  Samsung Galaxy S3 ( Android Jelly Bean 4.3)  

## Description
i have application use flutter_inappwebview 3.1.0 to show local html which show SVG image which have interactions with java script. i do all configurations ( androidx and min sdk..)

**Expected behavior:** 
application run on the device.. the device meet the requirement specified in the plugin.

**Current behavior:** 
application work very well on emulator only.

thank you

**Comment by pichillilorenzo** [comment]
Could you share some code? Thanks
