### ISSUE TITLE
Confirmation dialog (onbeforeunload) displayed after popped from webview page

### ISSUE THREAD

**Issue by AlexVincent525** [pichillilorenzo/flutter_inappwebview#337]
## Environment

**Flutter version:** 1.17.0 (stable)
**Plugin version:** 3.1.0
**Android version:** Android 10

## Description

This issue will occur if a web page is using `onbeforeunload` to control page reload or close. An example would be [onbeforeunload](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onbeforeunload) .

**Expected behavior:** Closing a webView without any confirmation, or prevent pop before confirmed/cancelled.

**Current behavior:** A dialog shown after popped.

## Steps to reproduce

1. Visit [onbeforeunload](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onbeforeunload)
2. Pop the webview page. e.g. using `Navigator.pop(context)`.
3. A dialog displayed. (If not, click "navigate" or "goto" link)

## Images
A dialog shown after the webview has been popped.
![image](https://user-images.githubusercontent.com/15884415/81541659-0c64ac80-93a6-11ea-9b7d-0afa18dbbdbd.png)

**Comment by AlexVincent525** [comment]
And it's not localized too.

**Comment by pichillilorenzo** [comment]
Fixed! Instead, I think the localization depends on the language you set on the smartphone. For example, I see the same message but In Italian on my smartphone.
