### ISSUE TITLE
Adding a cookie not working on ios?

### ISSUE THREAD

**Issue by SwannLV** [pichillilorenzo/flutter_inappwebview#338]
## Environment

**Flutter version:** 1.17
**Plugin version:**  3.1.0
**iOS version:** 13.3
**Device:** Iphone11 simulator

## Description
Adding a cookie is working for me on android but not on ios simulator.

Here is my code:

```
  final CookieManager _cookieManager = CookieManager.instance();

  @override
  void initState() {
    super.initState();

    final expiresDate =
        DateTime.now().add(Duration(days: 3)).millisecondsSinceEpoch;

    _cookieManager.deleteAllCookies();

    _cookieManager.setCookie(
      url: env.webAppUrl,
      name: "session",
      value: ClientProvider.token,
      domain: env.webAppCookieDomain,
      expiresDate: expiresDate,
      isSecure: true,
    );
  }

```

Have I missed some configuration?

Thanks a lot!

**Comment by pichillilorenzo** [comment]
That's because you are `deleteAllCookies` and `setCookie` are async methods. You don't know which will be called first by the platform.
So, you need first call `deleteAllCookies` and then `setCookie` using `await` operator or `then` method on the `deleteAllCookies` result.

However, I noticed that `expiresDate` option is not working correctly on both iOS and Android platforms. I already fixed it and it will be available on the next release.

Here is an example using `then` method:
```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        initialRoute: '/',
        routes: {
          '/': (context) => CookieManagerExample()
        }
    );
  }
}

class CookieManagerExample extends StatefulWidget {
  final CookieManagerExampleState state = CookieManagerExampleState();

  @override
  CookieManagerExampleState createState() => state;
}

class CookieManagerExampleState extends State<CookieManagerExample> {
  InAppWebViewController webViewController;
  final CookieManager _cookieManager = CookieManager.instance();

  @override
  void initState() {
    super.initState();

    final expiresDate =
        DateTime.now().add(Duration(days: 3)).millisecondsSinceEpoch;

    _cookieManager.deleteAllCookies().then((value) {
      _cookieManager.setCookie(
        url: "https://flutter.dev/",
        name: "session",
        value: "54th5hfdcfg34",
        domain: ".flutter.dev",
        expiresDate: expiresDate,
        isSecure: true,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
            child: Column(children: <Widget>[
              Expanded(
                child: Container(
                  child: InAppWebView(
                    initialUrl: "https://flutter.dev/",
                    initialHeaders: {},
                    initialOptions: InAppWebViewGroupOptions(
                        crossPlatform: InAppWebViewOptions(
                            debuggingEnabled: true
                        )
                    ),
                    onWebViewCreated: (InAppWebViewController controller) {
                      webViewController = controller;
                    },
                    onLoadStart: (InAppWebViewController controller, String url) {

                    },
                    onLoadStop: (InAppWebViewController controller, String url) async {
                      List<Cookie> cookies = await _cookieManager.getCookies(url: url);
                      cookies.forEach((cookie) {
                        print(cookie.name + " " + cookie.value);
                      });
                    },
                  ),
                ),
              ),
            ])
        )
    );
  }
}
```

**Comment by jgadsby** [comment]
`
    await _cookieManager.deleteAllCookies();
    await _cookieManager.setCookie(
        url:
            "url",
        name: "token",
        value: "value,
        domain: "domain",
        isSecure: true,
        expiresDate: anHourFromNow
        );

    var cookieData = await _cookieManager.getCookie(url:"url", name: "token");
`

Here's an example of what I'm doing, with some data redacted. When I print the list of cookies like you did in your example above, I don't see the cookie I just set. In addition, 'cookieData' is null.

**Comment by SwannLV** [comment]
@pichillilorenzo thanks a lot for your answer.
It does not seem to work on ios for me, chaining with a `.then(`..
Maybe it is because I am on the simulator?
Will try on a real device...

**Comment by pichillilorenzo** [comment]
@SwannLV I tested it on iOS simulator and it is working.

@SwannLV and @jgadsby could you try in a fresh app the example code I gave to you? 
If the cookie for `"https://flutter.dev/"` url is set, then `CookieManager` is working. If it works with my example but not in your use case, then there is something else. In that case, I need more info about your use case (full code example that for you doesn't work), otherwise, I don't know what's going on and why it is not working for you.

**Comment by SwannLV** [comment]
I found my problem: cookie.domain not starting with a dot does seem to work on ios.
Thank you very much @pichillilorenzo for everything 🙏
