### ISSUE TITLE
onLongPressHitTestResult bug

### ISSUE THREAD

**Issue by Karatla** [pichillilorenzo/flutter_inappwebview#340]
first , thanks for your amazing webview plugin
and i am glad you keep to update this plugin
**Flutter version:** 1.17
**Plugin version:**    3.1.0

**Current behavior:** use onLongPressHitTestResult function

## Steps to reproduce

InAppWebView(
          initialOptions: InAppWebViewGroupOptions(
            crossPlatform: InAppWebViewOptions(),
          ),
          initialUrl: url,
          onLongPressHitTestResult: (InAppWebViewController inAppWebViewController,LongPressHitTestResult longPressHitTestResult){
            print("longPressHitTestResult: ${longPressHitTestResult.extra}");
            print("longPressHitTestResult: ${longPressHitTestResult.type}");
            showModalBottomSheet(context: context, builder: (BuildContext context){
              return Container(
                height: 500,
                child: Center(
                  child: Text("${longPressHitTestResult.extra}\n\n${longPressHitTestResult.type},style: TextStyle(fontSize: 10),),
                ),
              );
            });
          },
        )

## Images   
when i use long press , the longPressHitTestResult.type always return SRC_IMAGE_ANCHOR_TYPE which means always return an image url not website url
In my app like this:
![WechatIMG124](https://user-images.githubusercontent.com/55880954/81630155-6d889080-9437-11ea-8e0d-1d30d46ac8a6.jpeg)
but it should be like this :
![WechatIMG125](https://user-images.githubusercontent.com/55880954/81630178-7b3e1600-9437-11ea-9327-f5c50f7a0fb1.jpeg)

In ios onLongPressHitTestResult return ios way like below:
![Screen Shot 2020-05-12 at 10 18 09](https://user-images.githubusercontent.com/55880954/81631205-e983d800-9439-11ea-89db-937d4b8e33a5.png)
i can not controll

**Comment by pichillilorenzo** [comment]
@Karatla I will investigate about it.
For iOS, to make it work, you need to disable `allowsLinkPreview` option, otherwise, the long press event will be captured by the system.

**Comment by Karatla** [comment]
> @Karatla I will investigate about it.
> For iOS, to make it work, you need to disable `allowsLinkPreview` option, otherwise, the long press event will be captured by the system.

thank you

**Comment by pichillilorenzo** [comment]
To achieve that, you can use now:
```dart
var requestFocusNodeHrefResult =  = await inAppWebViewController.requestFocusNodeHref();
print(requestFocusNodeHrefResult.url);
print(requestFocusNodeHrefResult.title);
```
inside the `onLongPressHitTestResult` event.
