### ISSUE TITLE
Scrolling not smooth on iOS

### ISSUE THREAD

**Issue by rbocobo** [pichillilorenzo/flutter_inappwebview#341]
## Environment

**Flutter version:** 1.17.0
**Plugin version:**  3.1.0
**Android version:**    
**iOS version:** 13.3
**Xcode version:**  
**Device information:**  iPhone 7

## Description

When scrolling and you release, the scrolling slowly stops

**Current behavior:** 

When scrolling and you release, the scrolling abruptly  stops. It is not as smooth as before
## Steps to reproduce

1. Load a page with scrollable content

**Comment by pichillilorenzo** [comment]
Yes, it was my mistake! I fixed it in the next version that should be released today or tomorrow!
