### ISSUE TITLE
shouldInterceptAjaxRequest no call

### ISSUE THREAD

**Issue by leielyq** [pichillilorenzo/flutter_inappwebview#344]
initialOptions: InAppWebViewGroupOptions(
                    crossPlatform: InAppWebViewOptions(
                      debuggingEnabled: true,
                      javaScriptCanOpenWindowsAutomatically: true,
                      useShouldInterceptAjaxRequest: true,
                      useShouldInterceptFetchRequest: true,

                    )
                ),

                shouldInterceptAjaxRequest: (InAppWebViewController controller, AjaxRequest ajaxReq) async {
                  print("ajaxReq.url: ${ajaxReq.url}");

                  ajaxReq.headers.setRequestHeader("token", DeviceManager.getDeviceToken());
                  ajaxReq.headers.setRequestHeader("deviceid", DeviceManager.getDeviceId());

                  return ajaxReq;
                },

**Comment by pichillilorenzo** [comment]
I don't have enough information about your problem. I need a more detailed description.

An ajax example is available inside the `example/test_driver` folder: https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/example/test_driver/in_app_webview_ajax_test.dart

The corresponding server-side (Node.js) that manages the ajax request is here:
https://github.com/pichillilorenzo/flutter_inappwebview/blob/f569e369f433d218dac78f43462c83be1c5c4b1d/nodejs_server_test_auth_basic_and_ssl/index.js#L164

**Comment by leielyq** [comment]
This problem appears on Android phones

**Comment by pichillilorenzo** [comment]
Did you get some javascript errors from debugging (chrome://inspect/#devices)??

However, without any code to test, I can do nothing about it, because I can't reproduce your error.
As I said, the ajax example if linked to you is working.

If the ajax request you are trying to intercept has been made before the `onLoadStop` event (that is the `onPageFinished` event on Android platform), then, on Android, there isn't anyway to intercept it unfortunately!

If you can control the javascript code of the webpage your showing, then the ajax request should be made after the DOM is ready, otherwise you can't intercept it.

**Comment by leielyq** [comment]
@pichillilorenzo  Thanks, indeed as you said at the end

**Comment by leielyq** [comment]
@pichillilorenzo  hi,I have a problem again, sometimes it won't be called on the Android device. The URL is https://h5.jimmychat.com/active/#/pages/index/index, very sad, please help me.

**Comment by pichillilorenzo** [comment]
Could you explain to me where are your Ajax calls in your code? Otherwise, I can't tell if it is working or not. What do you expect exactly in your use case?

**Comment by leielyq** [comment]
@pichillilorenzo  in  init(), call  https://tchatweb.jimmychat.com/TChat/user/score/info,This ajax needs to set a specific request header, so I need to use the shouldInterceptAjaxRequest method to forward. Mainly, it is normally available on iOS devices.Oh hope you can understand what i'm talking about

**Comment by leielyq** [comment]
@pichillilorenzo I finally found out that it cannot be called in China. Is it because part of the network is blocked, like the Chinese network cannot access google.com

**Comment by leielyq** [comment]
Is there any Google service in flutter_inappwebview's js code that intercepts Ajax?
