### ISSUE TITLE
Android ChromeSafariBrowser MissingPluginException

### ISSUE THREAD

**Issue by sereja93** [pichillilorenzo/flutter_inappwebview#346]
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] Connected device (2 available)
```

Error when call `close` method in  `ChromeSafariBrowser` class. Library version 3.1.0
```
Unhandled Exception: MissingPluginException(No implementation found for method close on channel com.pichillilorenzo/flutter_chromesafaribrowser_7b85cd18-6e31-4003-817b-45d0eeacd6d3)
```

```
browser = MyChromeSafariBrowser(MyInAppBrowser(closeBrowser: close));

void close(bool success) async {
    await browser.close();
    if (success) {
      showResult(context, true, widget.openStore);
    } else {
      showResult(context, false, repeatOneError);
    }
  }
```

**Comment by pichillilorenzo** [comment]
It should work with the latest release `3.2.0`!
Also, remember that calling `browser.close();` on an already closed browser will result in a `MissingPluginException`!
You can check if it still opened using `isOpened` method.

**Comment by Djihanegh** [comment]
Im using the latest release `flutter_inappwebview: ^5.7.2+3` and im still having this issue :

`Unhandled Exception: MissingPluginException(No implementation found for method close on channel com.pichillilorenzo/flutter_chromesafaribrowser_17416323137453016815410166135761111016213)
E/flutter (29384): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (29384): <asynchronous suspension>
E/flutter (29384): #1      ChromeSafariBrowser.close (package:flutter_inappwebview/src/chrome_safari_browser/chrome_safari_browser.dart:119:5)
E/flutter (29384): <asynchronous suspension>
E/flutter (29384): `

Any solution for that ?
