### ISSUE TITLE
Hello, I don't know if I can get the height of InAppWebView or make it adapt to the height of Html content. What do I need to do?

### ISSUE THREAD

**Issue by JiangJuHong** [pichillilorenzo/flutter_inappwebview#35]
Hello, I don't know if I can get the height of InAppWebView or make it adapt to the height of Html content. What do I need to do?

**Comment by shahxadakram** [comment]
Did you find any idea?

**Comment by juliengit2** [comment]
I had to add:
<meta name="viewport" content="width=device-width, initial-scale=1.0">
to adapt the size of the html content to the size of the InAppWebView

**Comment by YouCii** [comment]
@juliengit2 The code only allows HTML pages to be adapted to mobile devices, but the height is not the biggest.

**Comment by jameszhao-io** [comment]
You can inject js code to do this, like:
```
controller.injectScriptCode('''
window.flutter_inappbrowser.callHandler('WebViewHeight', document.body.scrollHeight);
''');
```
But you still cannot set the height of InAppWebView to this height. It will crash on android because android (or flutter) doesn't support height more than device height.

**Comment by goYou** [comment]
This may help you:

```
onLoadStop: (InAppWebViewController controller, String url) {
              controller.evaluateJavascript(source: '''(() => { return document.body.scrollHeight;})()''').then((value) {
                if(value == null || value == '') {
                  return;
                }
                webHeight = double.parse('$value');
                setState(() {});
              });
            },
```

**Comment by sketcharsh** [comment]
This can also give you same result.

`controller
                            .getContentHeight()
                            .then((value) => print("Value $value"));`

**Comment by wilz05** [comment]
but the above code does not work on android api version 22 devices. have you tried ? @sketcharsh @goYou

**Comment by sketcharsh** [comment]
I've not checked in android api version 22 devices.

**Comment by goYou** [comment]
> but the above code does not work on android api version 22 devices. have you tried ? @sketcharsh @goYou

I've not checked in android api version 22 devices.

Several recommended steps:
(1) Check if the webpage is loaded successfully (Use flutter_inappwebview example)
(2)  You can try to print the return value to test whether evaluateJavascript is effective
```Dart
onLoadStop: (InAppWebViewController controller, String url) {
  print('onLoadStop')
  controller.evaluateJavascript(source: '''(() => { return 1; })()''').then((value) {
    print('onLoadStop - evaluateJavascript return: $value')
  });
},
```
(3) You can try to print the return value to test whether the JavaScript code works
```Dart
onLoadStop: (InAppWebViewController controller, String url) {
  controller.evaluateJavascript(source: '''(() => { return document.body.scrollHeight;})()''').then((value) {
    print('value: $value')
  });
},
```
