### ISSUE TITLE
 When uploading pictures using h5, you can only select the pictures of the mobile phone in the webview and cannot use the camera to upload pictures

### ISSUE THREAD

**Issue by zhou-zc** [pichillilorenzo/flutter_inappwebview#353]
using html tag `<input type="file" accept="image/*" capture>`

**Comment by pichillilorenzo** [comment]
Support added in the next release!
Please, refer to [How to enable the usage of camera for HTML inputs such as `<input type="file" accept="image/*" capture>`](https://github.com/pichillilorenzo/flutter_inappwebview#how-to-enable-the-usage-of-camera-for-html-inputs-such-as-input-typefile-acceptimage-capture) section to see how it works.

**Comment by pichillilorenzo** [comment]
New version `3.3.0` released!
