### ISSUE TITLE
Displaying an image while the page is loading

### ISSUE THREAD

**Issue by buraksimsek06** [pichillilorenzo/flutter_inappwebview#354]
## Environment

**Flutter version:*v1.17.1* 
**Plugin version:*3.1.0*    
**Android version:*23*    
**iOS version:**
**Xcode version:*Android Emulator Nexus*  
**Device information:**    

## Description

Hello there,
When the page address changes, I want to show a image until the page loads. Is this possible ? instead of linear progress indicators.

**Comment by pichillilorenzo** [comment]
Yes, you can show whatever you want. `InAppWebView` is just a widget like any other. For example, you could use the `Stack` widget or the `IndexedStack` widget to achieve that.
