### ISSUE TITLE
Please Add support for Auto Play video  or is it already there?

### ISSUE THREAD

**Issue by VikasJilla** [pichillilorenzo/flutter_inappwebview#355]

**Comment by whatamelon** [comment]
Hi @VikasJilla , you can use 
                      initialOptions: InAppWebViewGroupOptions(
                          crossPlatform: InAppWebViewOptions(
                              mediaPlaybackRequiresUserGesture:false
                          )}
this option. XD

**Comment by VikasJilla** [comment]
I'll check that thank you
