### ISSUE TITLE
InAppBrowser.openWithSystemBrowser crash on iOS

### ISSUE THREAD

**Issue by fif1973** [pichillilorenzo/flutter_inappwebview#358]
## Environment

**Flutter version:**  1.17.1
**Plugin version:**  3.2.0
**Android version:**  
**iOS version:** 13.4.1
**Xcode version:**  11.5
**Device information:**  iPhone 7 Plus

## Description

**Expected behavior:** 
Open the system browser

**Current behavior:** 
Application crashed

## Steps to reproduce

use:
```
InAppBrowser.openWithSystemBrowser(url: url);
```

**Comment by fif1973** [comment]
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/pmaes/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-3.2.0/ios/Classes/InAppBrowserManager.swift, line 37
```

**Comment by pichillilorenzo** [comment]
Fix available in the next release!

**Comment by fif1973** [comment]
thank you ;)

**Comment by pichillilorenzo** [comment]
New version `3.3.0` released!
