### ISSUE TITLE
 Modified the new version configuration error

### ISSUE THREAD

**Issue by zhou-zc** [pichillilorenzo/flutter_inappwebview#361]
Android resource linking failed
     /Users/admin/AndroidStudioProjects/yingtian_first_app/yingtian_first_app/build/app/intermediates/merged_manifests/debug/AndroidManifest.xml:52: AAPT: error: resource xml/provider_paths (aka com.yingtian.yingtianfirstapp:xml/provider_paths) not found.

Exception: The plugin flutter_inappwebview could not be built due to the issue above.

**Comment by pichillilorenzo** [comment]
Which version of the plugin are you using? Please, give some context

**Comment by zhou-zc** [comment]
3.2.0

**Comment by pichillilorenzo** [comment]
Your error is not related to my plugin, as it says:
`error: resource xml/provider_paths (aka com.yingtian.yingtianfirstapp:xml/provider_paths) not found.`, that means that it cannot find a file called `provider_paths.xml` inside your Android resource folder.
So, probably, you need to add a file called `provider_paths.xml` inside your `android/src/main/res/xml` folder, but I don't know which is the content of that file.
Check also other plugins you are using and if they require to add something like that to make it work.
