### ISSUE TITLE
[Android] shouldInterceptRequest

### ISSUE THREAD

**Issue by StevenKek** [pichillilorenzo/flutter_inappwebview#363]
It would be lovely to get a support for [shouldInterceptRequest](https://developer.android.com/reference/android/webkit/WebViewClient?authuser=1#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest))

I need it to change HTML prior to rendering it.

**Comment by pichillilorenzo** [comment]
It will be available in the next release only for Android because there isn't any way to do the same thing for iOS unfortunately.

**Comment by StevenKek** [comment]
Great, you rock!

Oh and BTW - let me thank you for this library. It is absolutely amazing!

**Comment by pichillilorenzo** [comment]
New version `3.3.0` released!
Now you can use the `androidShouldInterceptRequest` event. To be able to listen it, you need to set the Android-specific option `useShouldInterceptRequest` to `true`.
