### ISSUE TITLE
Popup downloadable url sometimes not loading

### ISSUE THREAD

**Issue by pmrajani** [pichillilorenzo/flutter_inappwebview#364]
I am using this plugins latest version to load my report website.
after few page loading completed i can comes to http://domain.com/5446oaidww0e/myreport.pdf url and this can be some time .doc file or .exl file.
If i install fresh app in phone first time i can detect this url in `onLoadStart` 

But if i try to go back to homescreen and again come to my webpage and generate report this is not load on `onLoadStart`

Browser works correct every time it's download my report file.

I am using same example code from repo, just replaced url with mine.

Here is flutter doctor
````
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

• No issues found!

````

**Comment by pichillilorenzo** [comment]
Have you tried the `onDownloadStart` event to intercept your file (in that case, you need to enable it: `useOnDownloadStart: true`)??

**Comment by pmrajani** [comment]
i am using  latest plugins `  flutter_inappwebview: ^3.2.0`

seems like there is no option for enable `useOnDownloadStart: true` 

@pichillilorenzo

**Comment by pichillilorenzo** [comment]
Yes, there is:
```dart
initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      debuggingEnabled: true,
      useOnDownloadStart: true
    ),
),
```

**Comment by pmrajani** [comment]
thanks it's works  @pichillilorenzo 

I was finding downloadable url on `OnPageStart `method.
But it's always retrieved on `onDownloadStart`
