### ISSUE TITLE
[Feature] Save webpage to local

### ISSUE THREAD

**Issue by c86jeff** [pichillilorenzo/flutter_inappwebview#366]
Is there any way to save web page to local and then could load local material from webview?
Does flutter have the mechanism to support such feature ?  if yes, i could do some contributions.

**Comment by pichillilorenzo** [comment]
Android has the `saveWebArchive()` method that will be available in the next release.
For iOS, this could be a hint: https://stackoverflow.com/questions/36246495/swift-ios-cache-wkwebview-content-for-offline-view

**Comment by c86jeff** [comment]
@pichillilorenzo thats cool! if you need help, call me

**Comment by rebootcode** [comment]
Any update on it? it's quite a great option.

**Comment by easazade** [comment]
this is a very needed feature for webview apps

**Comment by rebootcode** [comment]
@easazade - They are - I just hope someone from the community looks into this feature and sends PR to @pichillilorenzo

**Comment by pichillilorenzo** [comment]
Web archive support added also on iOS starting from version 5.

**Comment by DanieleCastronovo** [comment]
@E2-Pavithran any update on that?

**Comment by Dancas93** [comment]
@E2-Pavithran any update on that?

**Comment by marcelomoresco** [comment]
update?

**Comment by iKK001** [comment]
any update ?

**Comment by Its-NK** [comment]
is the offine save added for android platforms ?
