### ISSUE TITLE
Android app crashing when rotating iframe video to landscape mode.

### ISSUE THREAD

**Issue by sanjaysingh1990** [pichillilorenzo/flutter_inappwebview#368]
In some android devices mostly chinese app crashing when iframe embeded viedo being played in landscape mode. Any help for this please.

**Comment by pichillilorenzo** [comment]
Can you give me more info, please? Such as the Android version and smartphone brand? Thanks

**Comment by sanjaysingh1990** [comment]
https://www.gsmarena.com/xiaomi_redmi_8-9800.php

https://m.gsmarena.com/huawei_p20-ampp-9107.php

**Comment by pichillilorenzo** [comment]
Could you post also the error logs you get please? Thanks

**Comment by zhangxiaoga** [comment]
I also encountered the same problem, the mobile phone model Huawei Par-Al00, the system version Android 9.0

**Comment by zhangxiaoga** [comment]
> In some android devices mostly chinese app crashing when iframe embeded viedo being played in landscape mode. Any help for this please.

Excuse me, has the problem been solved? I have the same problem.
