### ISSUE TITLE
onCreateWindow does not work as advertised

### ISSUE THREAD

**Issue by edwin-egalite** [pichillilorenzo/flutter_inappwebview#369]
## Environment

**Flutter version: 1.19.0-2.0.pre.173** 
**Plugin version: 3.2.0**    
**Android version: 9 (Pie)**    
**iOS version: -**
**Xcode version: -**  
**Device information: Redmi Note 7**    

## Description
Clicked an anchor tag with target="_blank" got called to "shouldOverrideUrlLoading" with "isMainFrame = false" instead of "onCreateWindow"
**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. Opens a static page with an anchor tag with target="_blank" and any link in href.
2. Click on the anchor tag.
3. It opens in the current webview

**Comment by pichillilorenzo** [comment]
If you ever read the [API docs](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/WebView/onCreateWindow.html), it is clearly written that, on Android, you need to set the option `supportMultipleWindows: true`:
```dart
initialOptions: InAppWebViewGroupOptions(
  crossPlatform: InAppWebViewOptions(
    debuggingEnabled: true,
    useShouldOverrideUrlLoading: true
  ),
  android: AndroidInAppWebViewOptions(
    supportMultipleWindows: true
  )
),
```
