### ISSUE TITLE
How to set the color according to Light/Dark mode

### ISSUE THREAD

**Issue by Krishna21Soni13** [pichillilorenzo/flutter_inappwebview#378]
How we can customize the color for all tags from HTML string according to Light/Dark mode. 

![Screenshot 2020-06-04 at 12 15 36 PM](https://user-images.githubusercontent.com/59281891/83724216-7f87d880-a65d-11ea-82b6-08ec46c48fb8.png)

# Requirement
1.  Want black background color for all boxes and white color for all text.

NOTE:- I am loading HTML content in InAppWebView. 
Thanks

**Comment by pichillilorenzo** [comment]
Just add your CSS to your HTML. I didn't understand what is the problem with my plugin.

**Comment by pichillilorenzo** [comment]
> NOTE:- I am adding this plugin in an existing flutter project.

Then probably you need to add support for `Swift` on iOS (check this [StackOverflow issue](https://stackoverflow.com/questions/52244346/how-to-enable-swift-support-for-existing-project-in-flutter)). Also, check the [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios) section.

**Comment by Krishna21Soni13** [comment]
@pichillilorenzo It is resolved. Thanks
