### ISSUE TITLE
Android only. Selection controls works, but invisible/transparent

### ISSUE THREAD

**Issue by godzeit** [pichillilorenzo/flutter_inappwebview#380]
## Environment

**Flutter version:** 1.17.2
**Plugin version:** 3.3.0+3  

## Description

Android only. Text selection, copy paste from toolbar working, but when u select text there is no selection controls appears as it should be. Actually, looks like they are exsits, because the behaviour for selection is the same and it is working, but they are kinda invisible.

![Screenshot_1591349709](https://user-images.githubusercontent.com/48680083/83861315-dcf15780-a739-11ea-9dbe-18a18649f309.png)

![Screenshot_1591349926](https://user-images.githubusercontent.com/48680083/83861681-538e5500-a73a-11ea-921a-0a392857087c.png)

**Comment by pichillilorenzo** [comment]
This is a known issue, but I didn't find any solution to that yet, unfortunately.

**Comment by godzeit** [comment]
> This is a known issue, but I didn't find any solution to that yet, unfortunately. It is something related to how Flutter embeds native views.

Oh, that is very sad to hear, but anyway, can u at leat tell me what the probles is causing current situation. And, especially I will appreciate if you will tell me the exact location of probem?

**Comment by pichillilorenzo** [comment]
It seems that it could be fixed with next Flutter release: https://github.com/flutter/flutter/issues/24584#issuecomment-638562814

**Comment by PerryPro** [comment]
> It seems that it could be fixed with next Flutter release: [flutter/flutter#24584 (comment)](https://github.com/flutter/flutter/issues/24584#issuecomment-638562814)

The new Flutter version is now available, it seems that 'Hybrid Composition' should be enabled.

**Comment by pichillilorenzo** [comment]
new version 5.0.0 published with android-specific option `useHybridComposition`!
