### ISSUE TITLE
onUpdateVisitedHistory not calling every time when navigation state changes 

### ISSUE THREAD

**Issue by appstute-abhay** [pichillilorenzo/flutter_inappwebview#384]
**Flutter version:*1.17.1* 
**Plugin version:*^3.3.0+3*   
**iOS version:*13.3.1*
**Xcode version:*11.4*  
**Device information:*iPhone 6 *  

I have updated inAppWebView plugin from 2.1.0+1 to 3.3.0+3, I have used onNavigationStateChange method from previous version, In current version this method is removed so I have used onUpdateVisitedHistory method which is called when the navigation state of the InAppWebView changes as per documentation which is same as onNavigationStateChange but onUpdateVisitedHistory is not calling every time. Any solution to call method everytime when navigation state of the InAppWebView changes

**Comment by pichillilorenzo** [comment]
Could you make an example, please?
