### ISSUE TITLE
Change `flutterInAppWebViewPlatformReady`

### ISSUE THREAD

**Issue by krongnang** [pichillilorenzo/flutter_inappwebview#386]
How can I change `flutterInAppWebViewPlatformReady` to other name ?
I have to change from swift and java code or I can change from dart layer?
Thanks!

**Comment by pichillilorenzo** [comment]
You can't change it. It is the default event name you need to listen to be able to call javascript handlers. Why do you need to change it?

**Comment by krongnang** [comment]
I need change it because our client writing the web site, which we will integrate into our app. So, they need to change `flutterInAppWebViewPlatformReady` to other one

**Comment by pichillilorenzo** [comment]
You can use `flutterInAppWebViewPlatformReady` event on your web site without any problems. You can consider it such as any other default javascript event.
If you want, you can also choose to not use it: in this case, the most important thing is that you can call `window.flutter_inappweview.callHandler` only when the page is ready (for example inside [`load`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) or [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded) events).

Asking changing its name is like asking changing the name, for example, of any of the default events, such as [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded) event. You can't change it.
