### ISSUE TITLE
PlatformException(error, Can print only from an activity, null)

### ISSUE THREAD

**Issue by LeNgocHiep** [pichillilorenzo/flutter_inappwebview#387]
## Environment
Flutter :1.12.13 hotfix 8
Dark : 2.7.0
Android studio : 3.5.1
MinSDK level: 21 support androidx

## Description
I got this error while performing the function to print PDF files. Please help me solve this problem. Thanks very much.
my code : 
>```dart
>Scaffold(
>      appBar: AppBar(
>        title: Text(widget.arg.title),
>        actions: <Widget>[
>          IconButton(
>            icon: Icon(Icons.print),
>            onPressed: () async {
>              await controller.printCurrentPage();
>//              getHtmlDocument(widget.arg.url);
>            },
>          )
>        ],
>      ),
>      body: Stack(
>        children: <Widget>[
>          Container(
>            child: InAppWebView(
>              initialUrl: widget.arg.url,
>              initialHeaders: {},
>              initialOptions: InAppWebViewGroupOptions(
>                  android: AndroidInAppWebViewOptions(
>                    builtInZoomControls: true,
>                  ),
>                  crossPlatform: InAppWebViewOptions(
>                    useShouldOverrideUrlLoading: true,
>                    useOnLoadResource: true,
>                  )),
>              onWebViewCreated: (InAppWebViewController controller) {},
>              onLoadStart: (InAppWebViewController controller, String url) {
>                setState(() {
>                  _loading = true;
>                });
>              },
>              onLoadStop:
>                  (InAppWebViewController controller, String url) async {
>                this.controller = controller;
>                setState(() {
>                  _loading = false;
>                });
>              },
>              onPrint: (controller, url) async {
>                print('printting');
>              },
>            ),
>          ),
>          LoadingSpinner.loadingView(context: context, loading: _loading)
>        ],
>      ),
>    )```
## Stacktrace/Logcat   
```
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): Failed to handle method call
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): java.lang.IllegalStateException: Can print only from an activity
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at android.print.PrintManager.print(PrintManager.java:518)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView.printCurrentPage(InAppWebView.java:1433)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebView.FlutterWebView.onMethodCall(FlutterWebView.java:370)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at android.os.MessageQueue.nativePollOnce(Native Method)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at android.os.MessageQueue.next(MessageQueue.java:336)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at android.os.Looper.loop(Looper.java:174)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at java.lang.reflect.Method.invoke(Native Method)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_0(10171): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
>E/flutter (10171): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Can print only from an activity, null)
```

**Comment by pichillilorenzo** [comment]
It should be already fixed. Which version of the plugin are you using?

**Comment by LeNgocHiep** [comment]
The version I'm using is 3.2.0. After I updated to the latest version (3.3.0+3) this problem was fixed. thank you very much.
