### ISSUE TITLE
ChromeSafariBrowser not lunch when device has a default browser except of Chrome

### ISSUE THREAD

**Issue by samin-fs** [pichillilorenzo/flutter_inappwebview#391]
## Environment
**Android version:** Android 7.0.0 

## Description
Hi,
I'm using "ChromeSafariBrowser" in my app, I have a problem when running the app in an android device which has another browser except Chrome as a default browser, in this case, the ChromeSafariBrowser is not running and InAppBrowser in lunch in the device default browser.
what should I do to fix this problem?

**Expected behavior:** 

I want to lunch with chrome, even the user sets another default browser.

**Current behavior:** 

lunch with the device default browser.

**Comment by samin-fs** [comment]
I also set  packageName: "com.android.chrome"
but it still lunches with the device default browser.

**Comment by samin-fs** [comment]
@pichillilorenzo any idea why it's happening?

**Comment by pichillilorenzo** [comment]
Could you share the code you are using?
Also, could you share the device info?

I tested it trying to launch Chrome Custom Tabs using `packageName: "org.mozilla.firefox"` to open it with Firefox mobile Custom Tabs and it is working.

So, it could be that the device you are using doesn't support Chrome Custom Tabs.

**Comment by samin-fs** [comment]
@pichillilorenzo this is my code:

`
class MyChromeSafariBrowser extends ChromeSafariBrowser {
  MyChromeSafariBrowser(browserFallback) : super(bFallback: browserFallback);

  @override
  InAppBrowser get browserFallback => super.browserFallback;

  @override
  void onOpened() {
    dev.log("ChromeSafari browser opened");
  }

  @override
  void onLoaded() {
    dev.log("ChromeSafari browser loaded");
  }

  @override
  void onClosed() {
    dev.log("ChromeSafari browser closed");
  }
}
`
and also I have this class:
`
class MyInAppBrowser extends InAppBrowser {

  @override
  Future onBrowserCreated() async {
    print("\n\nMyInAppBrowser Created!\n\n");
  }

  @override
  Future onLoadStart(String url) async {
    print("\n\nMyInAppBrowserStarted $url\n\n");
  }

  @override
  Future onLoadStop(String url) async {
    print("\n\nMyInAppBrowserStopped $url\n\n");

  }

  @override
  void onLoadError(String url, int code, String message) {
    print("Can't load $url.. Error: $message");
  }

  @override
  void onProgressChanged(int progress) {
    print("Progress: $progress");
  }

  @override
  void onExit() {
    print("\n\nBrowser closed!\n\n");
  }

  @override
  Future<ShouldOverrideUrlLoadingAction> shouldOverrideUrlLoading(
      ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest) async {
    print("\n\n override ${shouldOverrideUrlLoadingRequest.url}\n\n");
    return ShouldOverrideUrlLoadingAction.ALLOW;
  }

  @override
  void onLoadResource(LoadedResource response) {
    print("Started at: " +
        response.startTime.toString() +
        "ms ---> duration: " +
        response.duration.toString() +
        "ms " +
        response.url);
  }

  @override
  void onConsoleMessage(ConsoleMessage consoleMessage) {
    print("""
    console output:
      message: ${consoleMessage.message}
      messageLevel: ${consoleMessage.messageLevel.toValue()}
   """);
  }
}
`

and I use them like this: 

`final ChromeSafariBrowser browser =
    new MyChromeSafariBrowser(new MyInAppBrowser());

    await browser.open(
        url: loginUrl,
        options: ChromeSafariBrowserClassOptions(
            android:
            AndroidChromeCustomTabsOptions(addDefaultShareMenuItem: false,
                packageName: "com.android.chrome"),
            ios: IOSSafariOptions(barCollapsingEnabled: true)));
    `

in an emulator with this description:
Nexus 5X API 24
android 7.0.0

I have chrome installed, but also I have Opera as my default browser, with code above, I get this output:
MyInAppBrowser Created!
and never get this: ChromeSafari browser opened.
and the URL opens with Opera instead of chrome.
