### ISSUE TITLE
How to get the POST data of an URL?

### ISSUE THREAD

**Issue by huiwen0212** [pichillilorenzo/flutter_inappwebview#392]
Hi, I would like to know is there a way to get the POST data of an URL after the URL changes?

Ex: in PHP you can use $POST['params']  to get the data
Thanks

**Comment by pichillilorenzo** [comment]
I didn't understand what you are trying to achieve.

PHP is server-side, so you can get data through `$POST['params']` on your server from the client POST Request.
Instead, here we are client-side. How could it even be possible to get data that is on your server? You can control your data before sending the request, for example using JavaScript.

Please, could you explain better your use case?

**Comment by pichillilorenzo** [comment]
if you need to intercept requests, on Android you can use `androidShouldInterceptRequest` event (you need to enable it using `useShouldInterceptRequest: true` android-specific option)

**Comment by huiwen0212** [comment]
> I didn't understand what you are trying to achieve.
> 
> PHP is server-side, so you can get data through `$POST['params']` on your server from the client POST Request.
> Instead, here we are client-side. How could it even be possible to get data that is on your server? You can control your data before sending the request, for example using JavaScript.
> 
> Please, could you explain better your use case?

I see, because I have an URL and that URL have POST data in that URL and I would to get the POST data.

**Comment by pichillilorenzo** [comment]
What do you mean with "URL have POST data"?? Can you make an example?
