### ISSUE TITLE
How to override headers in each request

### ISSUE THREAD

**Issue by rizkyramadhan** [pichillilorenzo/flutter_inappwebview#393]
Hi, I realize that there are initialHeaders, it only sends header on first request. I need to add an header to mark the webapp that every request sent from flutter app. Is there anyway to do this ?

**Comment by pichillilorenzo** [comment]
You can use the `shouldOverrideUrlLoading` event, for example:
```dart
shouldOverrideUrlLoading: (InAppWebViewController controller, ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest) async {
  if (Platform.isAndroid || shouldOverrideUrlLoadingRequest.iosWKNavigationType == IOSWKNavigationType.LINK_ACTIVATED) {
    await controller.loadUrl(url: shouldOverrideUrlLoadingRequest.url, headers: {
      "custom-header": "value"
    });
    return ShouldOverrideUrlLoadingAction.CANCEL;
  }
  return ShouldOverrideUrlLoadingAction.ALLOW;
},
```

To use this event, you need to enable it:
```dart
initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true
    )
),
```

Also, only for Android, you can use the `androidShouldInterceptRequest` event, that corresponds to [WebViewClient#shouldInterceptRequest](https://developer.android.com/reference/android/webkit/WebViewClient#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)) native event.
```dart
androidShouldInterceptRequest: (controller, request) {

},
```

To use this event, you need to enable it:
```dart
initialOptions: InAppWebViewGroupOptions(
    android: InAppWebViewOptions(
        useShouldInterceptRequest: true
    )
),
```

**Comment by rizkyramadhan** [comment]
Wow, superb answer. Thanks a bunch.

**Comment by franklink** [comment]
Is anything available for adding headers to a postUrl request? I am unable to transmit headers using the postUrl method or I haven't been able to figure it out based on documentation and available methods. I have tried androidShouldInterceptRequest but none of the headers are reaching the server. If that did work I would still have trouble in iOS. I can open a new issue if necessary. Thanks.

**Comment by masiJR** [comment]
@franklink  Did you fixed it with adding headers to a postUrl request?
Now i have the same issue like you. Thank in advanced.

**Comment by franklink** [comment]
@masiJR I only have it working for Android at this time using:

`androidShouldInterceptRequest: (controller, request) {
              request.headers = {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'x-api-key': API_KEY
              };`

@pichillilorenzo Are you planning on adding support for postUrl with headers in iOS? I don't have a solution for that platform at the moment. Thanks.

**Comment by k3vinb0ss** [comment]
Hi @pichillilorenzo  How can I override headers for <img> tag request ?  I tried **shouldOverrideUrlLoading** & **shouldInterceptFetchRequest** but it didn't pass through.
