### ISSUE TITLE
How can I get the callback when tap on the any URL in the webview?

### ISSUE THREAD

**Issue by Krishna21Soni13** [pichillilorenzo/flutter_inappwebview#394]
I am loading the HTML content in the InAppWebview. This HTML having the URL. I want to perform other operations when the user clicks on the URL.
How can I get the callback tap on any URL in the webview?
Thanks

**Comment by pichillilorenzo** [comment]
You can try the `shouldOverrideUrlLoading` event, for example:
```dart
shouldOverrideUrlLoading: (InAppWebViewController controller, ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest) async {
  if (Platform.isAndroid || shouldOverrideUrlLoadingRequest.iosWKNavigationType == IOSWKNavigationType.LINK_ACTIVATED) {
    if (shouldOverrideUrlLoadingRequest.url == "myUrl") {
         // do something
    }
    return ShouldOverrideUrlLoadingAction.CANCEL;
  }
  return ShouldOverrideUrlLoadingAction.ALLOW;
},
```

To use this event, you need to enable it:
```dart
initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true
    )
),
```

Also, only for Android, you can try the `androidShouldInterceptRequest` event, that corresponds to [WebViewClient#shouldInterceptRequest](https://developer.android.com/reference/android/webkit/WebViewClient#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)) native event.
```dart
androidShouldInterceptRequest: (controller, request) {

},
```

To use this event, you need to enable it:
```dart
initialOptions: InAppWebViewGroupOptions(
    android: InAppWebViewOptions(
        useShouldInterceptRequest: true
    )
),
```

Instead, if you need to intercept only click events, you can use JavaScript:
```dart
onLoadStop: (InAppWebViewController controller, String url) async {
  // touchstart events
  await controller.evaluateJavascript(source: """
window.addEventListener('touchstart', function(event) {
  // do something, for example:
  event.preventDefault();
});
""");

  // click events
  await controller.evaluateJavascript(source: """
window.addEventListener('click', function(event) {
  // do something, for example:
  event.preventDefault();
});
""");
  
},
```

**Comment by Krishna21Soni13** [comment]
@pichillilorenzo Thanks. It's working.

**Comment by ktnishide** [comment]
when the page is using angular relative path routing, `shouldOverrideUrlLoading` is not working.

using `onUpdateVisitedHistory` as workaround...
