### ISSUE TITLE
Never arrived to onAjaxReadyStateChange when ajax response only headers.

### ISSUE THREAD

**Issue by pyaehein** [pichillilorenzo/flutter_inappwebview#399]
When server only response set cookies header when login ajax success, this library never reached to onAjaxReadyStateChange? Is there any way to get the response header's data?

**Comment by rbocobo** [comment]
Were you able to resolve this?

**Comment by pyaehein** [comment]
No, I watched onAjaxProgress and if the condition is same as like this
`ajaxRequest.event.type == AjaxRequestEventType.LOADEND`
I called the cookie manager and got cookies.
