### ISSUE TITLE
select option not show running in Android Tablet device when use inappwebview 

### ISSUE THREAD

**Issue by lyh20190329** [pichillilorenzo/flutter_inappwebview#400]
I use the inappwebview plugin to open H5,and H5 has <select> option, it is not show or pop window
when I click the select option running in IPAD device of android platform. but  it is work ok on phone mobile device ,
 1、**H5 CODE like:**
	<select name="cars" id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
2、**flutter code like：**
 InAppWebView(
      initialUrl: this._url,
      initialHeaders: {},
      initialOptions: InAppWebViewGroupOptions(
          crossPlatform: InAppWebViewOptions(
            debuggingEnabled: false,
              transparentBackground:true,
            clearCache:true,
            javaScriptEnabled:true,
            javaScriptCanOpenWindowsAutomatically:true,
          ),
        android: AndroidInAppWebViewOptions(allowFileAccessFromFileURLs:true,
          appCachePath:_path,
          mixedContentMode:AndroidMixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW,
          thirdPartyCookiesEnabled:true,),
      ),
      onWebViewCreated: (InAppWebViewController controller) {
        _inAppcontroller = controller;
        //_inAppcontroller.clearCache();
      },
......
.......
I use the inAppWebview version is 3.4.0

Which expert clicks, thank you very much！！

**Comment by lyh20190329** [comment]
H5 CODE like:
	**<select name="cars" id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>**

**Comment by lyh20190329** [comment]
H5 CODE like:
/----	<select name="cars" id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>---/

**Comment by lyh20190329** [comment]
![微信图片_20200616104003](https://user-images.githubusercontent.com/49057412/84725706-c959b280-afbd-11ea-9dae-a164f69a5faf.png)

**Comment by lyh20190329** [comment]
[
![微信图片_20200616104643](https://user-images.githubusercontent.com/49057412/84726110-b4c9ea00-afbe-11ea-92ad-ecd4501a0249.png)
](url)

**Comment by lyh20190329** [comment]
it works ok in phone mobile device 
![微信图片_20200616105055](https://user-images.githubusercontent.com/49057412/84726365-4afe1000-afbf-11ea-967e-f9b322098431.jpg)

**Comment by lyh20190329** [comment]
For some reason, tapping on the rendered <select> button does not open the options list.This only happens on Android tablets, irrespective of the Android version. On Android smartphones, however, this bug does not occur and the options list opens as expected.

**Comment by pichillilorenzo** [comment]
Unfortunately, I didn't find any working workaround/solution for dropdown menus on Android Tablets yet.
There are some issues to how Flutter embeds Android native views.
I hope they will resolve this as soon as possible.

**Comment by lyh20190329** [comment]
Anyone can resolve this？thank you very much!

**Comment by Manuito83** [comment]
Hi. This seems to be working now with the default `flutter_webview` plugin, at least as of v1.0.0.

**Comment by tedwong** [comment]
Any one solve this issue?

**Comment by pichillilorenzo** [comment]
Try now the latest version of this plugin with `useHybridComposition: true` Android-specific webview option.

**Comment by tedwong** [comment]
@pichillilorenzo  due to the supporting issue, I need to use the `flutter_inappwebview: ^4.0.0+4`is this possible to fix?

**Comment by pichillilorenzo** [comment]
I don't know if `useHybridComposition: true` would fix it, that I said to try it.
However, `flutter_inappwebview: ^4.0.0+4` is not supported unfortunately
