### ISSUE TITLE
SFSafariViewController doesn't open like a native iOS modal

### ISSUE THREAD

**Issue by Crossplay-dev** [pichillilorenzo/flutter_inappwebview#403]
https://stackoverflow.com/questions/62404311/flutter-sfsafariviewcontroller-doesnt-open-like-a-native-ios-modal

## Description

Animation bug having to do with the POPOVER presentationstyle for SFSafariViewController.

**Expected behavior:** 

Notice how in the second GIF, the app itself is pushed back, whereas in the first GIF, we can see a semi-transparent view created instead of the native push back animation for the app.

**Current behavior:** 

While this works, there is a bug in the animation through which the SFSafariViewController appears. The background elements are not pushed backwards like in the native IOS push animation. Instead there is a faint transparent transition element.

**Comment by pichillilorenzo** [comment]
Fix will be available in the next release
