### ISSUE TITLE
How to block web page from opening other app on the device

### ISSUE THREAD

**Issue by MaxResolution** [pichillilorenzo/flutter_inappwebview#405]
I am using an iPhone, and when I click on the Instagram or youtube link, it will switch to that app, any way to disable this behavior?

**Comment by pichillilorenzo** [comment]
What class of the plugin are you using?

**Comment by MaxResolution** [comment]
> What class of the plugin are you using?

I am using InAppWebView

**Comment by pichillilorenzo** [comment]
You can use the `shouldOverrideUrlLoading` event (you need to enable it using the `crossPlatform` option: `useShouldOverrideUrlLoading: true`) in this way:

```dart
...

initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
        debuggingEnabled: true,
        useShouldOverrideUrlLoading: true
    )
),

...

shouldOverrideUrlLoading: (InAppWebViewController controller, ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest) async {
  
  if (Platform.isIOS &&
      shouldOverrideUrlLoadingRequest.iosWKNavigationType == IOSWKNavigationType.LINK_ACTIVATED &&
      shouldOverrideUrlLoadingRequest.url.contains("youtube")) {
    
    await controller.loadUrl(url: shouldOverrideUrlLoadingRequest.url);
    return ShouldOverrideUrlLoadingAction.CANCEL;
    
  }
  
  return ShouldOverrideUrlLoadingAction.ALLOW;
  
},
```

It should work now. Let me know, thanks!

**Comment by pichillilorenzo** [comment]
However, it seems that this is the default behavior of `WKWebView` on iOS.
It opens automatically other apps if it "sees" that it can open the specific URL using an installed App.

If you need a specific URL or more, you can check them inside the `shouldOverrideUrlLoading` event using the example I gave.
Otherwise, if you don't know what would be the links, I think you can just use:
```dart
shouldOverrideUrlLoading: (InAppWebViewController controller, ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest) async {
  
  if (Platform.isIOS &&
      shouldOverrideUrlLoadingRequest.iosWKNavigationType == IOSWKNavigationType.LINK_ACTIVATED) {
    
    await controller.loadUrl(url: shouldOverrideUrlLoadingRequest.url);
    return ShouldOverrideUrlLoadingAction.CANCEL;
    
  }
  
  return ShouldOverrideUrlLoadingAction.ALLOW;
  
},
```

without checking URLs, overriding every `LINK_ACTIVATED` requests.

**Comment by MaxResolution** [comment]
> However, it seems that this is the default behavior of `WKWebView` on iOS.
> It opens automatically other apps if it "sees" that it can open the specific URL using an installed App.
> 
> If you need a specific URL or more, you can check them inside the `shouldOverrideUrlLoading` event using the example I gave.
> Otherwise, if you don't know what would be the links, I think you can just use:
> 
> ```dart
> shouldOverrideUrlLoading: (InAppWebViewController controller, ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest) async {
>   
>   if (Platform.isIOS &&
>       shouldOverrideUrlLoadingRequest.iosWKNavigationType == IOSWKNavigationType.LINK_ACTIVATED) {
>     
>     await controller.loadUrl(url: shouldOverrideUrlLoadingRequest.url);
>     return ShouldOverrideUrlLoadingAction.CANCEL;
>     
>   }
>   
>   return ShouldOverrideUrlLoadingAction.ALLOW;
>   
> },
> ```
> 
> without checking URLs, overriding every `LINK_ACTIVATED` requests.

Thanks this works!
