### ISSUE TITLE
inappwebview shows half of the screen when screen orientation changes to landscape

### ISSUE THREAD

**Issue by PaulVinSoft249** [pichillilorenzo/flutter_inappwebview#407]
## Environment

**Flutter version:1.17.0
**Plugin version:**   flutter_inappwebview: ^3.2.0
 
**Android version:**  9 
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**Expected behavior:**  to fit all space on landscape mode

**Current behavior:** fitting to half on landscape mode

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
Please post an example and some screenshots or screen records. Thanks

**Comment by PaulVinSoft249** [comment]
![WhatsApp Image 2020-06-18 at 8 39 08 PM](https://user-images.githubusercontent.com/60345890/85064999-552d3380-b1a4-11ea-8fe3-55112cc874e7.jpeg)

**Comment by PaulVinSoft249** [comment]
![WhatsApp Image 2020-06-18 at 8 45 57 PM](https://user-images.githubusercontent.com/60345890/85065313-da184d00-b1a4-11ea-8aac-09d02d097dfd.jpeg)

Portrait mode it takes the whole of the screen

**Comment by pichillilorenzo** [comment]
Could you share the code you are using? Also the `AndroidManifest.xml` file. Thanks

**Comment by PaulVinSoft249** [comment]
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.chateko.admin.admin_chatapp">
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
   <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_GPS" />
    <uses-permission android:name="android.permission.ACCESS_ASSISTED_GPS" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Chateko"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />

              
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="com.onesignal.NotificationOpened.DEFAULT" 
            android:value="DISABLE"
        />
        <meta-data
            android:name="flutterEmbedding"
            android:resource="@drawable/ic_launcher"
            
            android:value="2" />
            <provider 
        android:name="androidx.core.content.FileProvider" 
        android:authorities="com.chateko.admin.chatapp.flutter_inappwebview.fileprovider" 
        android:exported="false" 
        android:grantUriPermissions="true">
			<meta-data 
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/provider_paths" />
		</provider>

      


        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="com.chateko.admin.chatapp.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
    </application>
</manifest>
`

**Comment by PaulVinSoft249** [comment]
`import 'dart:async';
import 'dart:io';
import 'package:admin_chatapp/models/button_models.dart';
import 'package:admin_chatapp/models/provider/button_prov.dart';
import 'package:admin_chatapp/utils/colors.dart';
import 'package:connectivity/connectivity.dart';
import 'package:dio/dio.dart';
import 'package:downloads_path_provider/downloads_path_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';


class WebViewPage extends StatefulWidget {
  static const routeName = '/webpage';
  @override
  _WebViewPageState createState() => _WebViewPageState();
}

class _WebViewPageState extends State<WebViewPage> {
  var uuid = Uuid();

  StreamSubscription<ConnectivityResult> subscription;

  GlobalKey<ScaffoldState> _scaffoldkey = GlobalKey<ScaffoldState>();

  InAppWebViewController webView;
  ContextMenu contextMenu = ContextMenu();
  var menu = ContextMenu().menuItems;
  String url = "";
  double progress = 0;
  int statusCodes;

  bool loadError = false;

  //-----------------
  bool downloading = false;
  var progressString = "";

  final snackbar = SnackBar(
      content:
          Text('Download Completed', style: TextStyle(color: Colors.pink)));

  @override
  void initState() {
    super.initState();

    // SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    subscription = Connectivity()
        .onConnectivityChanged
        .listen((ConnectivityResult result) {
      if (result != ConnectivityResult.none && webView != null) {
        print("reload");
        print("reload");
        loadError = false;
        webView.reload();
      }
    });
    subscription.cancel();

    contextMenu = ContextMenu(onCreateContextMenu: (hitTestResult) async {
      print("onCreateContextMenu");
      print(hitTestResult.extra);

      print(await webView.getSelectedText());

      if (hitTestResult.extra == null) {
        print(hitTestResult.extra);
      } else if (hitTestResult.extra.contains('.jpg') ||
          hitTestResult.extra.contains('.png')) {
        await downloadFile(hitTestResult.extra);
        _scaffoldkey.currentState.showSnackBar(snackbar);
      }
    }, onHideContextMenu: () {
      print("onHideContextMenu");
    }, onContextMenuActionItemClicked: (contextMenuItemClicked) {
      var id = (Platform.isAndroid)
          ? contextMenuItemClicked.androidId
          : contextMenuItemClicked.iosId;
      print("onContextMenuActionItemClicked: " +
          id.toString() +
          " " +
          contextMenuItemClicked.title);
    });

    menu = [
      ContextMenuItem(
          androidId: 1,
          iosId: "1",
          title: "Special",
          action: () async {
            print("Menu item Special clicked!");
          })
    ];
  }

  @override
  void dispose() {
    super.dispose();
  }

  Future<void> downloadFile(String imageUrl) async {
    Dio dio = Dio();
    Directory downloadsDirectory;

    try {
      downloadsDirectory = await DownloadsPathProvider.downloadsDirectory;

      // var dir = await getApplicationDocumentsDirectory();
      await Permission.storage.request();

      await dio.download(
          imageUrl, "${downloadsDirectory.path}${uuid.v4()}Chateko.jpg",
          onReceiveProgress: (recieve, total) {
        print("Recieve: $recieve , Total: $total");
        setState(() {
          downloading = true;
          progressString = ((recieve / total) * 100).toStringAsFixed(0) + "%";
        });
      });
    } catch (e) {
      print(e);
    }

    setState(() {
      downloading = false;
      progressString = "Completed";
    });
    print("Download completed");
  }

  @override
  Widget build(BuildContext context) {
    final productId = ModalRoute.of(context).settings.arguments as String;
    print('${productId.toString()}');
    final loadedPage =
        Provider.of<ButtonProv>(context, listen: false).findById(productId);
    final screenSize = MediaQuery.of(context).size;
    return WillPopScope(
      child: Scaffold(
        backgroundColor: Colors.white,
        key: _scaffoldkey,
        // floatingActionButton:
        body: SafeArea(
          child: Container(
            color: Colors.purple[100].withOpacity(.3),
            height: screenSize.height,
            width: screenSize.height,
            child: _webviewBodie(loadedPage),
          ),
        ),
      ),
      onWillPop: () {
        return webView != null
            ? webView.goBack()
            : Navigator.of(context).pushReplacement(
                    MaterialPageRoute(builder: (ctx) => HomePage())) ??
                false;
      },
    );
  }

  _linearProgress() {
    return Container(
      height: 2,
      child: LinearProgressIndicator(
        value: progress,
        backgroundColor: Colors.white,
        valueColor: AlwaysStoppedAnimation<Color>(primarColor),
      ),
    );
  }

  _errorPage() {
    final screenSize = MediaQuery.of(context).size;

    return Container(
      height: screenSize.height,
      width: screenSize.height,
      decoration: BoxDecoration(
        gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              Colors.white,
              Colors.pink[100],
              Colors.purple[100],
            ]),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Icon(
            Icons.signal_wifi_off,
            size: 140,
            color: primarColor,
          ),
          SizedBox(height: 2),
          RichText(
            text: TextSpan(
              children: [
                TextSpan(
                  text: statusCodes == 500
                      ? 'Internal Server Error'
                      : statusCodes == -8
                          ? 'Check data bundles'
                          : 'Check internet connections',
                  style: TextStyle(
                    fontSize: 18,
                    color: Colors.black,
                    // fontWeight: FontWeight.w700,
                  ),
                ),
                TextSpan(
                  text: '!',
                  style: TextStyle(
                    fontSize: 40,
                    color: Colors.red,
                    fontStyle: FontStyle.italic,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
          SizedBox(height: 20),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                onPressed: () => webView.reload(),
                child: Text('Retry'),
              ),
              SizedBox(width: 10),
              RaisedButton(
                onPressed: () => Navigator.of(context).pop(),
                child: Text('Go home'),
              ),
            ],
          ),
        ],
      ),
    );
  }

  _webviewBodie(ButtonModels loadedPage) {
    return Stack(
      children: <Widget>[
        Column(
          children: <Widget>[
            // _homeButton(),
            progress < 1.0 ? _linearProgress() : SizedBox(height: 0),
            Flexible(
              child: Container(
                child: InAppWebView(
                  initialUrl: loadedPage.buttonLinkUrl == null
                      ? 'http://chateko.com/'
                      : loadedPage.buttonLinkUrl,
                  contextMenu: contextMenu,
                  initialHeaders: {},
                  initialOptions: InAppWebViewGroupOptions(
                      android: AndroidInAppWebViewOptions(
                        allowFileAccess: true,
                        loadsImagesAutomatically: true,
                        allowFileAccessFromFileURLs: true,
                        allowContentAccess: true,
                        allowUniversalAccessFromFileURLs: true,
                        geolocationEnabled: true,
                      ),
                      crossPlatform: InAppWebViewOptions(
                        debuggingEnabled: true,
                        useOnLoadResource: true,
                        useOnDownloadStart: true,
                        disableHorizontalScroll: true,
                        transparentBackground: true,
                        // disableVerticalScroll: true,
                      )),
                  onWebViewCreated: (InAppWebViewController controller) {
                    webView = controller;
                  },
                  onLoadStart: (InAppWebViewController controller, String url) {
                    setState(() {
                      this.url = url;
                    });
                  },
                  onLoadStop:
                      (InAppWebViewController controller, String url) async {
                    setState(() {
                      this.url = url;
                    });
                  },
                  onProgressChanged:
                      (InAppWebViewController controller, int progress) {
                    setState(() {
                      this.progress = progress / 100;
                    });
                  },
                  onLoadError: (InAppWebViewController controller, String url,
                      int code, String message) async {
                    print("error $url: $code, $message");
                    print("error $url: $code, $message ");
                    setState(() {
                      statusCodes = code;
                      loadError = true;
                    });
                  },
                  onLoadHttpError: (InAppWebViewController controller,
                      String url, int statusCode, String description) async {
                    setState(() {
                      loadError = true;
                      statusCodes = statusCode;
                    });

                    print("HTTP error $url: $statusCode, $description");
                  },
                  onDownloadStart:
                      (InAppWebViewController controller, String url) async {
                    print("${controller.getUrl().toString()}");
                    print(url);
                    await downloadFile(url);
                    _scaffoldkey.currentState.showSnackBar(snackbar);
                  },
                ),
              ),
            ),
          ],
        ),
        loadError ? _errorPage() : Text(''),
        Positioned(
          bottom: 100,
          right: 10,
          child: FloatingActionButton(
            onPressed: () =>
                Navigator.of(context).pushNamed(HomePage.routeName),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Icon(Icons.home),
                Text('Home', style: TextStyle(letterSpacing: 0)),
                SizedBox(height: 5),
              ],
            ),
          ),
        ),
        downloading ? _showDownloading() : Text(''),
      ],
    );
  }

  _showDownloading() {
    return Center(
      child: Container(
        height: 120.0,
        width: 200.0,
        child: Card(
          color: Colors.black,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              CircularProgressIndicator(),
              SizedBox(
                height: 20.0,
              ),
              Text(
                "Downloading File: $progressString",
                style: TextStyle(
                  color: Colors.white,
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
  // _homeButton() {
  //   return Container(
  //     height: 30,
  //     width: MediaQuery.of(context).size.width,
  //     color: greyColor,
  //     child: Align(
  //       alignment: Alignment.centerLeft,
  //       child: FlatButton.icon(
  //           onPressed: () => Navigator.of(context).pop(),
  //           color: primarColor,
  //           textColor: Colors.white,
  //           icon: Icon(Icons.home),
  //           label: Text(
  //             'Home',
  //             style: TextStyle(
  //               // fontSize: 18,
  //               fontWeight: FontWeight.w700,
  //             ),
  //           )),
  //     ),
  //   );
  // }
}
// class WebViewPage extends StatefulWidget {
//   static const routeName = '/webpage';

//   @override
//   _WebViewPageState createState() => _WebViewPageState();
// }

// class _WebViewPageState extends State<WebViewPage> {
//   @override
//   Widget build(BuildContext context) {
//     return SafeArea(
//       child: Scaffold(
//         backgroundColor: primarColor,
//         body: WebviewScaffold(
//           headers: {'Cache-Control': 'no-store','Connection':'keep-alive','Accept':'text/html', 'User-Agent':'PostmanRuntime/7.25.0','Accept-Encoding':'gzip, deflate, br'},
//           // clearCache: false,
//           url: "https://www.chateko.com",
//           // appBar: new AppBar(
//           //   title: new Text("Widget webview"),
//           // ),
//           initialChild: Container(
//             child: SpinKitFadingCube(
//               size: 30,
//               duration: Duration(milliseconds: 800),
//               itemBuilder: (BuildContext context, int index) {
//                 return DecoratedBox(
//                   decoration: BoxDecoration(
//                     color: index.isEven ? primarColor : secondaryColor,
//                   ),
//                 );
//               },
//             ),
//           ),
//         ),
//       ),
//     );
//   }
// }
`

**Comment by pichillilorenzo** [comment]
It's not a plugin problem but there is something wrong with your UI.
I just deleted `height: screenSize.height` and `width: screenSize.height` inside the `Scaffold > Safe Area > Container` from your code and it works just fine:
```dart
child: Scaffold(
  backgroundColor: Colors.white,
  key: _scaffoldkey,
  // floatingActionButton:
  body: SafeArea(
    child: Container(
      color: Colors.purple[100].withOpacity(.3),
      child: _webviewBodie(),
    ),
  ),
),
```

Next time, check your UI before posting an issue like this. Thanks

**Comment by PaulVinSoft249** [comment]
Sorry man thanks
