### ISSUE TITLE
NoSuchFileException about package-aware-r.txt

### ISSUE THREAD

**Issue by BI7PRK** [pichillilorenzo/flutter_inappwebview#408]
I don't know if it‘s a package bug, this problem has troubled me for a long time.
```LOG
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.nio.file.NoSuchFileException: E:\******\build\flutter_inappwebview\intermediates\res\symbol-table-with-package\debug\package-aware-r.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by pichillilorenzo** [comment]
Does it happen when you try to build release mode or any mode?

However, I have never seen this error.
Have you tried to clean and rebuild the project?

**Comment by pichillilorenzo** [comment]
@BI7PRK did you resolve it?

**Comment by BI7PRK** [comment]
yes, i have resolve it.
first, if your network is artificially restricted from connecting to Google servers. You must make sure that you have broken through it.
second, 
- flutter clean
- cd [your project] ./android
- run `./gradlew check` and view a log.
- run `./gradlew assembleDebug` is passed?
- run `flutter packages get` in you project.
- go! `flutter run -v`
^_^

**Comment by pichillilorenzo** [comment]
Thanks! This could be helpful for other people 👍
