### ISSUE TITLE
takeScreenShot() not working as expected.

### ISSUE THREAD

**Issue by MohdFaizan123** [pichillilorenzo/flutter_inappwebview#409]
## Environment

**Flutter version:**  Flutter 1.17.3 • channel stable 
**Plugin version:** 3.3.0+3
**Android version:** Tested in Android 9, 10
**iOS version:** Not Tested on ios 
**Xcode version:** Not Tested on ios
**Device information:** Tested on veriety of Android phones - including Mi, OPPO and Emulators

## Description

When taken **Screenshot** using 

`  var screenshotBytes = await _controller.takeScreenshot();`

then I am writing these bytes into a file, like this

`imgFile.writeAsBytesSync(screenshotBytes.buffer.asUint8List());`

then using the image to show in `Image` widget

`Image.file(imgFile)`

The screenshot image must be visible inside the `Image` widget, but it's just showing as a **white blank screen**.

**Comment by pichillilorenzo** [comment]
Where do you call `takeScreenshot()` in your code? Maybe you are calling it too early.
Could you share your code?

However, you don't need to use `screenshotBytes.buffer.asUint8List()` because `takeScreenshot()` returns already an `Uint8List`, so it doesn't make any sense.
Also, you can use `Image.memory()` method:
```dart
var screenshot = await webViewController.takeScreenshot();

var image = Image.memory(screenshot);
```

**Comment by MohdFaizan123** [comment]
Sorry for the late reply, actually I didn't receive any mail just checked manually the issue, and found that you have replied!

I am doing it like this, as you mentioned, tried doing `Image.memory(screenshotBytes)` as well

```
onLoadStop:
                    (InAppWebViewController controller, String url) async {
                  if (Platform.isAndroid) {
                    setState(() {
                      _opacity = 1.0;
                    });
                    var screenshotBytes = await controller.takeScreenshot();
                    showDialog(
                      context: context,
                      builder: (context) {
                        return AlertDialog(
                          content: Image.memory(screenshotBytes),
                        );
                      },
                    );
                  }
                  init();
                },
```

but no effect.

**Comment by MohdFaizan123** [comment]
Actually for more info, I am using the **_flutter_inappwebview_** library, with this one 

> [flutter_echarts](https://pub.dev/packages/flutter_echarts)

This library generates html as a result which I am using to open in **_flutter_inappwebview_**, and I am not able to take screenshots of the graph.

**Comment by pichillilorenzo** [comment]
@MohdFaizan123 could you share a sample code that I can test? Thanks

**Comment by MohdFaizan123** [comment]
Sure, here's the full code:

`library flutter_echarts;

// --- FIX_BLINK ---
import 'dart:io';
// --- FIX_BLINK ---

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:path_provider/path_provider.dart';
import 'package:swasthyasetu/global/SizeConfig.dart';
import 'package:wc_flutter_share/wc_flutter_share.dart';

import 'package:webview_flutter/webview_flutter.dart';

import 'package:flutter_echarts/echarts_script.dart' show echartsScript;

/// <!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0, target-densitydpi=device-dpi" /><style type="text/css">body,html,#chart{height: 100%;width: 100%;margin: 0px;}div {-webkit-tap-highlight-color:rgba(255,255,255,0);}</style></head><body><div id="chart" /></body></html>
/// 'data:text/html;base64,' + base64Encode(const Utf8Encoder().convert( /* STRING ABOVE */ ))
const htmlBase64 =
    'data:text/html;base64,PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiPjxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wLCBtYXhpbXVtLXNjYWxlPTEuMCwgbWluaW11bS1zY2FsZT0xLjAsIHVzZXItc2NhbGFibGU9MCwgdGFyZ2V0LWRlbnNpdHlkcGk9ZGV2aWNlLWRwaSIgLz48c3R5bGUgdHlwZT0idGV4dC9jc3MiPmJvZHksaHRtbCwjY2hhcnR7aGVpZ2h0OiAxMDAlO3dpZHRoOiAxMDAlO21hcmdpbjogMHB4O31kaXYgey13ZWJraXQtdGFwLWhpZ2hsaWdodC1jb2xvcjpyZ2JhKDI1NSwyNTUsMjU1LDApO308L3N0eWxlPjwvaGVhZD48Ym9keT48ZGl2IGlkPSJjaGFydCIgLz48L2JvZHk+PC9odG1sPg==';

class EchartsCustom extends StatefulWidget {
  EchartsCustom({
    Key key,
    @required this.option,
    this.extraScript = '',
    this.onMessage,
    this.extensions = const [],
    this.theme,
    this.captureAllGestures = false,
    this.onLoad,
  }) : super(key: key);

  final String option;

  final String extraScript;

  final void Function(String message) onMessage;

  final List<String> extensions;

  final String theme;

  final bool captureAllGestures;

  final void Function() onLoad;

  @override
  _EchartsCustomState createState() => _EchartsCustomState();
}

class _EchartsCustomState extends State<EchartsCustom> {
  InAppWebViewController _controller;

  String _currentOption;

  // --- FIX_BLINK ---
  double _opacity = Platform.isAndroid ? 0.0 : 1.0;

  // --- FIX_BLINK ---

  @override
  void initState() {
    super.initState();
    _currentOption = widget.option;
  }

  void init() async {
    final extensionsStr = this.widget.extensions.length > 0
        ? this
            .widget
            .extensions
            .reduce((value, element) => (value ?? '') + '\n' + (element ?? ''))
        : '';
    final themeStr =
        this.widget.theme != null ? '\'${this.widget.theme}\'' : 'null';
    await _controller?.evaluateJavascript(source: '''
      $echartsScript
      $extensionsStr
      var chart = echarts.init(document.getElementById('chart'), $themeStr);
      ${this.widget.extraScript}
      chart.setOption($_currentOption, true);
    ''');
    if (widget.onLoad != null) {
      widget.onLoad();
    }
  }

  void update(String preOption) async {
    _currentOption = widget.option;
    if (_currentOption != preOption) {
      await _controller?.evaluateJavascript(source: '''
        try {
          chart.setOption($_currentOption, true);
        } catch(e) {
        }
      ''');
    }
  }

  @override
  void didUpdateWidget(EchartsCustom oldWidget) {
    super.didUpdateWidget(oldWidget);
    update(oldWidget.option);
  }

  // --- FIX_IOS_LEAK ---
  @override
  void dispose() {
    if (Platform.isIOS) {
      _controller.clearCache();
    }
    super.dispose();
  }

  // --- FIX_IOS_LEAK ---

  @override
  Widget build(BuildContext context) {
    // --- FIX_BLINK ---
    SizeConfig().init(context);
    // implement scrollable physics
    return ListView(
      shrinkWrap: true,
      physics: ScrollPhysics(),
      children: <Widget>[
        Opacity(
            opacity: _opacity,
            // --- FIX_BLINK ---
            child: Container(
              height: SizeConfig.blockSizeVertical * 50,
              child: InAppWebView(
                initialUrl: htmlBase64,
                //initialUrl: 'https://www.google.com/',
                initialOptions: InAppWebViewGroupOptions(
                  crossPlatform: InAppWebViewOptions(
                    useShouldOverrideUrlLoading: true,
                    useOnLoadResource: true,
                    javaScriptEnabled: true,
                    incognito: true,
                    mediaPlaybackRequiresUserGesture: false,
                    clearCache: true,
                    javaScriptCanOpenWindowsAutomatically: false,
                  ),
                  android: AndroidInAppWebViewOptions(),
                  ios: IOSInAppWebViewOptions(
                      allowsAirPlayForMediaPlayback: false,
                      allowsInlineMediaPlayback: true),
                ),
                /*javascriptMode: JavascriptMode.unrestricted,*/
                onWebViewCreated: (InAppWebViewController webViewController) {
                  _controller = webViewController;
                },
                onLoadStop:
                    (InAppWebViewController controller, String url) async {
                  if (Platform.isAndroid) {
                    setState(() {
                      _opacity = 1.0;
                    });
                  }
                  init();
                },
                gestureRecognizers: widget.captureAllGestures
                    ? (Set()
                      ..add(Factory<VerticalDragGestureRecognizer>(() {
                        return VerticalDragGestureRecognizer()
                          ..onStart = (DragStartDetails details) {}
                          ..onUpdate = (DragUpdateDetails details) {}
                          ..onDown = (DragDownDetails details) {}
                          ..onCancel = () {}
                          ..onEnd = (DragEndDetails details) {};
                      }))
                      ..add(Factory<HorizontalDragGestureRecognizer>(() {
                        return HorizontalDragGestureRecognizer()
                          ..onStart = (DragStartDetails details) {}
                          ..onUpdate = (DragUpdateDetails details) {}
                          ..onDown = (DragDownDetails details) {}
                          ..onCancel = () {}
                          ..onEnd = (DragEndDetails details) {};
                      })))
                    : null,
              ),
            ))
      ],
    );
  }

  void getImageAndShare() async {
    var screenshotBytes = await _controller.takeScreenshot();
    if (screenshotBytes != null)
      WcFlutterShare.share(
        sharePopupTitle: "Share Chart via",
        mimeType: 'image/png',
        fileName: "sharechart.png",
        bytesOfFile: screenshotBytes,
      );
    else {
      debugPrint("imgfile is null");
    }
  }
}
`

**Comment by MohdFaizan123** [comment]
Access this widget using

```
yAxisData = '[50, 60, 100]';
xAxisDatesData = '[20 jun 2020, 21 jun 2020, 22 jun 2020]';


return EchartsCustom(
                        option: '''
                  {
                    tooltip: {
                          trigger: 'axis',
                          position: function (pt) {
                              return [pt[0], '10%'];
                          }
                      },
                    xAxis: {
                      type: 'category',
                      boundaryGap: false,
                      data: $xAxisDatesData,
                    },
                    yAxis: {
                      type: 'value',
                      boundaryGap: false
                    },
                    series: [{data: $yAxisData,type: 'line',smooth: true,itemStyle: {color: $color}}]
                  }
                ''',
                      )
```

**Comment by MohdFaizan123** [comment]
Using [wc_flutter_share](https://pub.dev/packages/wc_flutter_share) plugin in above code

**Comment by MohdFaizan123** [comment]
Hello sir, any update on this issue? I need to complete this work urgently.

Thanks.

**Comment by pichillilorenzo** [comment]
It seems that on Android you need to set `hardwareAcceleration: false` to capture `<canvas>` HTML tag in screenshots (see https://stackoverflow.com/questions/38427433/how-can-i-capture-html5-canvas-in-android-webview).

So, add it to your android options:
```dart
initialOptions: InAppWebViewGroupOptions(
  crossPlatform: InAppWebViewOptions(
    useShouldOverrideUrlLoading: true,
    useOnLoadResource: true,
    javaScriptEnabled: true,
    incognito: true,
    mediaPlaybackRequiresUserGesture: false,
    clearCache: true,
    javaScriptCanOpenWindowsAutomatically: false,
  ),
  android: AndroidInAppWebViewOptions(
    hardwareAcceleration: false
  ),
  ios: IOSInAppWebViewOptions(
      allowsAirPlayForMediaPlayback: false,
      allowsInlineMediaPlayback: true),
),
```

Then, after you call your `void init()` method to initialize `echarts.init()` with JavaScript, add some delay to wait the chart rendering.
For example, using your sample data, this is working:

```dart
void init() async {
  final extensionsStr = this.widget.extensions.length > 0
      ? this
          .widget
          .extensions
          .reduce((value, element) => (value ?? '') + '\n' + (element ?? ''))
      : '';
  final themeStr =
      this.widget.theme != null ? '\'${this.widget.theme}\'' : 'null';
  await _controller?.evaluateJavascript(source: '''
    $echartsScript
    $extensionsStr
    var chart = echarts.init(document.getElementById('chart'), $themeStr);
    ${this.widget.extraScript}
    chart.setOption($_currentOption, true);
  ''');
  if (widget.onLoad != null) {
    widget.onLoad();
  }

  await Future.delayed(const Duration(milliseconds: 1000));
  
  var screenshot = await _controller?.takeScreenshot();
  await showDialog(
    context: context,
    builder: (context) {
      return AlertDialog(
        content: Image.memory(screenshot),
      );
    },
  );
}
```

![test_canvas_screenshot](https://user-images.githubusercontent.com/5956938/85388847-e4409f80-b546-11ea-999f-8e36a88cf40c.gif)

**Comment by festelo** [comment]
> hardwareAcceleration: false

I'm trying to take screenshot of mapbox inside webview. When hardwareAcceleration is set to false, content inside webview is not rendered at all.
