### ISSUE TITLE
Can I set the InAppWebview background to transparent?

### ISSUE THREAD

**Issue by winsonet** [pichillilorenzo/flutter_inappwebview#41]
I just want to show the inline html content in my app, so I want to set the webview background to transparent, so that it can show my app's background with the html content.

thx~~

**Comment by TuiyTuyHussein** [comment]
@pichillilorenzo 

Please add on prepare() [InAppWebView  java class ](https://github.com/pichillilorenzo/flutter_inappbrowser/blob/master/android/src/main/java/com/pichillilorenzo/flutter_inappbrowser/InAppWebView/InAppWebView.java#L109)

`        setBackgroundColor(Color.TRANSPARENT);
        setLayerType(WebView.LAYER_TYPE_SOFTWARE, null);`

**Comment by rafaelmaeuer** [comment]
use:
```dart
crossPlatform: InAppWebViewOptions(transparentBackground: true)
```

**Comment by mkmpvtltd1** [comment]
> use:
> 
> ```dart
> crossPlatform: InAppWebViewOptions(transparentBackground: true)
> ```

Yes it works

**Comment by bhanubbs** [comment]
initialOptions is Deprecated
 
 Use:
 initialSettings: InAppWebViewSettings(
     transparentBackground: true,
),
