### ISSUE TITLE
Can I hide the IOS keyboard toolbar?

### ISSUE THREAD

**Issue by lucky1213** [pichillilorenzo/flutter_inappwebview#410]
I want to hide the IOS keyboard toolbar

**Comment by lucky1213** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-20 at 16 27 15](https://user-images.githubusercontent.com/37032543/85197338-f508cf80-b312-11ea-8f07-d7151bc93c16.png)

What you want to hide is the row where the done button is located

**Comment by pichillilorenzo** [comment]
No, it's not possible at this moment.

**Comment by RaphaelBuffl** [comment]
@lucky1213 if still relevant: https://github.com/RaphaelBuffl/flutter_inappwebview
