### ISSUE TITLE
Can't scroll the page when the scroll starts from the webview

### ISSUE THREAD

**Issue by pixelgroup-israel** [pichillilorenzo/flutter_inappwebview#416]
I tried upgrading to the latest version but I can't seem to scroll the app when the scroll originated from within the webview, even if I add classes to not scroll the webview.

This is the code I'm using:

    return Container(
            padding: EdgeInsets.all(10.0),
            width: MediaQuery.of(context).size.width,
            child: AspectRatio(
                aspectRatio: _aspectRatio,
                child: InAppWebView(
                    initialUrl: iframeSrc,
                    initialHeaders: {
                        
                    },
                    initialOptions: InAppWebViewGroupOptions(
                        crossPlatform: InAppWebViewOptions(
                            debuggingEnabled: true,
                            useShouldOverrideUrlLoading: true,
                            verticalScrollBarEnabled: false,
                            horizontalScrollBarEnabled: false,
                            transparentBackground: true,
                            preferredContentMode: UserPreferredContentMode.MOBILE,
                            disableVerticalScroll: true,
                            disableHorizontalScroll: true,
                            disableContextMenu: true
                        ),
                        android: AndroidInAppWebViewOptions(
                            overScrollMode: AndroidOverScrollMode.OVER_SCROLL_NEVER
                        ),
                        ios: IOSInAppWebViewOptions(
                            enableViewportScale: true,
                            disallowOverScroll: true
                        )
                    ),
                    shouldOverrideUrlLoading: (InAppWebViewController controller, ShouldOverrideUrlLoadingRequest shouldOverrideUrlLoadingRequest) {
                        if(shouldOverrideUrlLoadingRequest.url.indexOf('article') > -1) {
                            var newUrl = shouldOverrideUrlLoadingRequest.url.split("/").last;
                            var articleId = newUrl.split("-").last;
                            Navigator.pushNamed(context, '/article/' + articleId);
                        }
                        else if(_firstFinishedUrl != null && shouldOverrideUrlLoadingRequest.url != _firstFinishedUrl) {
                            _launchURL(shouldOverrideUrlLoadingRequest.url);
                        }
                        else if(shouldOverrideUrlLoadingRequest.url != _firstFinishedUrl) {
                            _firstFinishedUrl = null;
                            webView?.loadUrl(url: shouldOverrideUrlLoadingRequest.url);
                        }
                    },
                    onWebViewCreated: (InAppWebViewController controller) {
                        webView = controller;
                    },
                    onLoadStop: _onPageFinished,
                ),
            ),
        );

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      1.12.13+hotfix.5         |
| Plugin version       |      3.4.0+1         |
| Android version      |      10         |
| iOS version          |        11       |
| Xcode version        |       11.0        |

Device information: Samsung Galaxy Note 10+

## Description

**Expected behavior:** 
The page should be scrolled when the the scroll starts from a non scrolled webview

**Current behavior:** 
The app only scrolls when the scroll started from outside the webview.

## Steps to reproduce

Implement a webview in a page that starts from the second half of the view and is longer then half the view.

**Comment by Ortes** [comment]
Same here
