### ISSUE TITLE
Plugin Throws DiagnosticsProperty<void> error and shows blank screen on Android Release and Profile Modes but works perfectly on debug mode

### ISSUE THREAD

**Issue by atavci** [pichillilorenzo/flutter_inappwebview#418]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | Flutter 1.17.4 • channel stable |
| Plugin version       | 3.4.0+1 |
| Android version      | Android 10.0 compileSdkVersion 28 minSdkVersion 21 targetSdkVersion 30 |

Device information:
Samsung Galaxy Tab S6 Lite

## Description
Plugin works as expected on the debug mode but when switched to profile or release mode a flutter error named DiagnosticProperty occurs and a blank screen is showed on the whole view. Unfortunately since the thrown error is an object, the true error message couldn't be read.

## Steps to reproduce
Camera and microphone used on the InAppWebView.

```
InAppWebView(
  initialUrl: "intentional-dummy-text"
  initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      mediaPlaybackRequiresUserGesture: false,
      cacheEnabled: false,
      debuggingEnabled: true
    )
  ),
  onWebViewCreated:
      (InAppWebViewController controller) {
    webViewController = controller;
    webViewController.addJavaScriptHandler(handlerName: "jsHandler", callback: (List<dynamic> arguments)  {
        if(arguments[0].toString() == 'navigateToHome'){
          CustomerClient().hangup();
        }
        print(arguments[0].toString());
        return arguments[0]+ " received";
    });
  },
  androidOnPermissionRequest:
      (InAppWebViewController controller,
          String origin,
          List<String> resources) async {
    return PermissionRequestResponse(
      resources: resources,
      action:
          PermissionRequestResponseAction.GRANT,
    );
  },
  onReceivedServerTrustAuthRequest: (InAppWebViewController controller, ServerTrustChallenge challenge) async {
    return ServerTrustAuthResponse(action: ServerTrustAuthResponseAction.PROCEED);
  },
),
```

## Images

![InAppWebViewError](https://user-images.githubusercontent.com/29902904/85721705-48579500-b6fa-11ea-9d0e-d0ce547e9bd4.jpg)

## Stacktrace/Logcat   

[   +1 ms] Application running.
[   +1 ms] Flutter run key commands.
[   +1 ms] h Repeat this help message.
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[+9983 ms] I/flutter (16944): setted url : https://intentionally-replaced-with-dummy-text//
[ +554 ms] I/flutter (16944): 
[   +1 ms] I/flutter (16944): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
[ +252 ms] I/flutter (16944): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
[ +116 ms] I/flutter (16944): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

**Comment by pichillilorenzo** [comment]
Take a look at this Stackoverflow issue: https://stackoverflow.com/questions/61615866/flutter-app-show-grey-screen-in-release-mode-but-works-fine-in-debug-mode-instan.
Maybe it will resolve your issue.

Otherwise, could you share the URL? Without it, I can't debug/resolve the problem.

**Comment by atavci** [comment]
Hello thanks for the quick response, unfortunately none of the solutions on the stackoverflow issue has worked for me. You can debug with this url https://meet.jit.si/test123

**Comment by atavci** [comment]
Issue has resolved. After a whole lot of debugging we discovered that this issue was related to flutter framework and not to this plugin, sorry for the inconvinience, I am closing this issue.
