### ISSUE TITLE
Web support for plugin

### ISSUE THREAD

**Issue by Luckey-Elijah** [pichillilorenzo/flutter_inappwebview#419]
### Devices
```
Web Server • web-server • web-javascript • Flutter Tools
Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116
```

### Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.157, on Mac OS X 10.15.5 19F101,locale en-US
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)
```
## Description

**What you'd like to happen:** Is there support for Flutter for Web? If not, is it a plan to implement? What the limitations (flutter sdk, contributors, etc.)

**Alternatives you've considered:** I've seeked out and inspected many different packages. This package seems to be extremely developed and matured compared to the rest in its area. It's not clear if support for web exists currently. I understand MacOS (and Windows 10?) support do not exits yet for something like this.

**Comment by pichillilorenzo** [comment]
I don't think it is possible to make it for Web, also because how do you map a WebView for the Web? It doesn't make any sense.

For MacOS, see https://github.com/pichillilorenzo/flutter_inappwebview/issues/402.
Instead, for Windows 10, I don't know if there is any WebView class such as on MacOS (`WKWebView`).

**Comment by Luckey-Elijah** [comment]
Ah, I see.

I'll look into other options.

Thank you for the quick response!
