### ISSUE TITLE
Using custom URLs within InAppBrowser

### ISSUE THREAD

**Issue by alsocalledchris** [pichillilorenzo/flutter_inappwebview#42]
Trying to use InAppBrowser and get a URL that redirects to a custom URL (e.g. myapp://gotoThisLink) which if hit using a native browser opens the desired app as expected. However with InAppBrowser the URL fails in onLoadError method with  'unsupported URL' error message. Any ideas how to solve this with InAppBrowser? Thanks

**Comment by pichillilorenzo** [comment]
The plugin doesn't have an API for direct handling custom URL yet (such as [WKURLSchemeHandler](https://developer.apple.com/documentation/webkit/wkurlschemehandler) for iOS)!
However, did you try the `shouldOverrideUrlLoading` method (with `useShouldOverrideUrlLoading` option setted to `true`) to capture your custom URL and, then, launch your App? I mean something like:
```dart
  @override
  void shouldOverrideUrlLoading(String url) {
    if (url.startsWith("myapp://gotoThisLink")) {
    // launch myapp here
    }
  }
```

To launch an App, you can use also my other plugin [flutter_appavailability](https://github.com/pichillilorenzo/flutter_appavailability) using the `AppAvailability.launchApp(String uri)` method.

**Comment by alsocalledchris** [comment]
cool thanks - I will give that a try

**Comment by alsocalledchris** [comment]
@pichillilorenzo tried to get the shouldOverrideUrlLoading working however the method is never called - even with the option useShouldOverrideUrlLoading set as required. Other overridden methods work fine, e.g. onLoadResource - it's just shouldOverrideUrlLoading that seems broken - any ideas?

**Comment by alsocalledchris** [comment]
Checking Android and shouldOverrideUrlLoading is working OK.
