### ISSUE TITLE
Open url inside webview via url_launcher

### ISSUE THREAD

**Issue by snj07** [pichillilorenzo/flutter_inappwebview#420]
I have some URLs (`<a>` tag) inside a `webview` and when a user clicks on any URL, I want it to be opened inside a browser using `url_launcher` rather than opening inside the `webview` itself. Is it possible? Could you please tell me how can I achieve this?

**Comment by pichillilorenzo** [comment]
Yes you can use the `shouldOverrideUrlLoading` event.
To use the `shouldOverrideUrlLoading` event, you need to enable it with `useShouldOverrideUrlLoading: true` option.

Here is an example:
```dart
initialOptions: InAppWebViewGroupOptions(
  crossPlatform: InAppWebViewOptions(
    debuggingEnabled: true,
    useShouldOverrideUrlLoading: true
  ),
),
shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
  var url = shouldOverrideUrlLoadingRequest.url;
  // here you can check the URL you want to open with url_launcher
  if (url == 'MY_URL') {
    if (await canLaunch(url)) {
      // Launch the App
      await launch(
        url,
      );
      // and cancel the request
      return ShouldOverrideUrlLoadingAction.CANCEL;
    }
  }

  return ShouldOverrideUrlLoadingAction.ALLOW;
},
```
