### ISSUE TITLE
Semantic versioning should be followed with new releases that include breaking changes

### ISSUE THREAD

**Issue by corcoran** [pichillilorenzo/flutter_inappwebview#421]
https://dart.dev/tools/pub/versioning#semantic-versions

Flutter recommends using the caret syntax for developers when including libraries/dependencies in their apps.

According to the [documentation](https://dart.dev/tools/pub/dependencies#version-constraints) on version constraints, non-major updates should be backwards compatible and not break existing implementations.

There have been a few updates that have broken apps (or created regression issues) using `flutter_inappwebview` without the developers explicitly bumping the version numbers in the pubspec.

**Comment by pichillilorenzo** [comment]
You are completely right! I apologize for any issue that I created.

However, I have documented every BREAKING CHANGES every time, if there were any of them, on each release: https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/CHANGELOG.md

In the next releases, if there are any breaking changes, I will update the plugin with a major release.
The next one will have for sure some breaking changes, so I will publish it as `4.0.0`.

Thanks!
