### ISSUE TITLE
Android version 10 has problems

### ISSUE THREAD

**Issue by szxv587** [pichillilorenzo/flutter_inappwebview#423]
Android version 10 has problems, after using the keyboard, the webview interface cannot be clicked, and the screen is blank

**Comment by pichillilorenzo** [comment]
Please, don't delete the issue template and use it to write issues.
It's there for a reason.

However, could you post the code you are using or an example that is not working? Also, a screen record of the problem?
Thanks.

**Comment by szxv587** [comment]
> Please, don't delete the issue template and use it to write issues.
> It's there for a reason.
> 
> However, could you post the code you are using or an example that is not working? Also, a screen record of the problem?
> Thanks.

![微信图片_20200628173128](https://user-images.githubusercontent.com/18606623/85943868-6ffe6580-b965-11ea-8810-26370403cc2d.jpg)
![微信图片_20200628173139](https://user-images.githubusercontent.com/18606623/85943887-8d333400-b965-11ea-8a82-ad95d991f079.jpg)
![微信图片_20200628173143](https://user-images.githubusercontent.com/18606623/85943889-8e646100-b965-11ea-98fd-b2c942dfcc9d.jpg)

**Comment by szxv587** [comment]
> Please, don't delete the issue template and use it to write issues.
> It's there for a reason.
> 
> However, could you post the code you are using or an example that is not working? Also, a screen record of the problem?
> Thanks.

Black screen at this position after the soft keyboard is retracted

**Comment by pichillilorenzo** [comment]
Could you post the code, please?

**Comment by szxv587** [comment]
Why is it possible in your example project, the same code file does not work in my project, the same is Android 10 mobile phone

**Comment by szxv587** [comment]
Why is your plugin version 4.0.0, can you update it?

**Comment by pichillilorenzo** [comment]
> Why is your plugin version 4.0.0, can you update it?

It's not released yet. I was working on it. I think I'm going to release it today.

> Why is it possible in your example project, the same code file does not work in my project, the same is Android 10 mobile phone

If you start a new Flutter app and use the sample code in the `README.md`, does it work? If not, do you have any exceptions? However, I tested it in Android 10 and it is working. So, it could be some configuration problem with your app.

This is the sample code of the `README.md` running in an Android 10 emulator:
![android_10_test](https://user-images.githubusercontent.com/5956938/86118113-7b21d480-bad0-11ea-8f48-418132292bc5.gif)
