### ISSUE TITLE
How can I integrate NativeView with existing library javascript

### ISSUE THREAD

**Issue by krongnang** [pichillilorenzo/flutter_inappwebview#426]
Using **flutter_inappwebview** library but we have some issues with the keyboard on Android
Decide to use the native screen for our webview screen and waiting for Google Engineer to fix keyboard issues.
We keep using **flutter_inappwebview** for ios. So, we need to use your **window.flutter_inappwebview.callHandler**. 
So, it hard to implement for me.
The question is: **how can I listen to the event from webview' script with the native screen.**
Our script on click the button html is: `window.flutter_inappwebview.callHandler('permissionLocation', { hasPermission: false });`  then in native app, we need to listen on button click.

Thanks in advance!

**Comment by krongnang** [comment]
Resolved by create callHandler function by @JavascriptInterface annotation

**Comment by pichillilorenzo** [comment]
For Android, keyboard problems have been fixed with the new version 5.0.0 (latest is `5.0.5+3`) and use the Android-specific webview option: `useHybridComposition: true`.
