### ISSUE TITLE
XML downloading issue - IOS

### ISSUE THREAD

**Issue by anthonydonx** [pichillilorenzo/flutter_inappwebview#427]
When I trying download the XML file using inside the inappwebview , that xml file  open in browser instead of a downloading the file in IOS,
Works with Android.
this is the code, 

`Expanded(
            child: InAppWebView(
              initialUrl: initialUrl,
              initialHeaders: {},
              initialOptions: InAppWebViewGroupOptions(
                  crossPlatform: InAppWebViewOptions(
                debuggingEnabled: true,
                useOnDownloadStart: true,
              )),
              onWebViewCreated: (InAppWebViewController appWebViewController) {
                webViewCreatedCallback(
                    appWebViewController); //call given function after webview created
              },
              onLoadStart:
                  (InAppWebViewController controller, String url) async {
                    _logger.i("onLoadStart $url");
                if (url.endsWith(".xml")) {
                  Util _util = Util();
                  String downloadValue = await _util.downloadAndSaveFile(url);
                  mainAppCallBack(downloadValue, context);
                } else {
                  urlChangedCallback(url);
                }
              },
              onProgressChanged:
                  (InAppWebViewController controller, int progress) {
              },
              onDownloadStart:
                  (InAppWebViewController controller, String url) async {
                _logger.i("onDownloadStart $url");
                Util _util = Util();
                String downloadValue = await _util.downloadAndSaveFile(url);
              },
            ),
          )
Please help me to resolve this problem

**Comment by pichillilorenzo** [comment]
Sorry I didn't understand your problem. Could you explain it in a better way, please? Thanks

**Comment by anthonydonx** [comment]
> Sorry I didn't understand your problem. Could you explain it in a better way, please? Thanks

I need to download the XML file using inappwebview. It works fine. but in IOS, the XML file open in web window instead of downloading

**Comment by pichillilorenzo** [comment]
What version of the plugin are you using? The latest is `4.0.0`.

I was able to download the file correctly on iOS and Android using the [flutter_downloader](https://pub.dev/packages/flutter_downloader) plugin.
Make sure to follow the steps required to make the plugin work: https://github.com/fluttercommunity/flutter_downloader#ios-integration

This is an example where the initial URL is an URL containing an XML file: https://www.w3schools.com/xml/note.xml

On Android, this is not recognized as a downloadable file, and it shows on the browser (this depends on the Android WebView implementation). Instead, on iOS, it is recognized as a downloadable file.

However, for some reason, if the `onDownloadStart` is not called, you can also use the `shouldOverrideUrlLoading` event (enable it with `useShouldOverrideUrlLoading: true` option) to intercept requests after the first one made with initial URL. Then you check for your specific URL, cancel the request, and download the file.

Here is the code:
```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:path_provider/path_provider.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await FlutterDownloader.initialize(
      debug: true // optional: set false to disable printing logs to console
  );

  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: InAppWebViewPage()
    );
  }
}

class InAppWebViewPage extends StatefulWidget {
  @override
  _InAppWebViewPageState createState() => new _InAppWebViewPageState();
}

class _InAppWebViewPageState extends State<InAppWebViewPage> {
  InAppWebViewController _webViewController;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('InAppWebView Example'),
        ),
        body: SafeArea(
          child: Container(
              child: InAppWebView(
                initialUrl: "https://www.w3schools.com/xml/note.xml",
                initialOptions: InAppWebViewGroupOptions(
                    crossPlatform: InAppWebViewOptions(
                      debuggingEnabled: true,
                      useOnDownloadStart: true,
                      useShouldOverrideUrlLoading: true
                    ),
                ),
                onWebViewCreated: (InAppWebViewController controller) {
                  _webViewController = controller;
                },
                shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
                  // use shouldOverrideUrlLoading to intercept requests after the first one and check if it is an XML file
                  var url = shouldOverrideUrlLoadingRequest.url;
                  if (url.endsWith(".xml")) {
                    // it's an xml file, then cancel the request and download the file
                    download(url);
                    return ShouldOverrideUrlLoadingAction.CANCEL;
                  }
                  return ShouldOverrideUrlLoadingAction.ALLOW;
                },
                onLoadStart: (controller, url) {
                  if (url.endsWith(".xml")) {
                    // put this check here if the first url contains your xml file.
                    // Instead, for subsequent requests, you can use shouldOverrideUrlLoading event.
                    download(url);
                  }
                },
                onDownloadStart: (controller, url) async {
                  download(url);
                },
              ),
            ),
          ),
      ),
    );
  }

  void download(String url) async {
    final taskId = await FlutterDownloader.enqueue(
      url: url,
      savedDir: (await getApplicationDocumentsDirectory()).path,
      showNotification: true, // show download progress in status bar (for Android)
      openFileFromNotification: true, // click on notification to open downloaded file (for Android)
    );
  }
}
```

**Comment by anthonydonx** [comment]
> What version of the plugin are you using? The latest is `4.0.0`.
> 
> I was able to download the file correctly on iOS and Android using the [flutter_downloader](https://pub.dev/packages/flutter_downloader) plugin.
> Make sure to follow the steps required to make the plugin work: https://github.com/fluttercommunity/flutter_downloader#ios-integration
> 
> This is an example where the initial URL is an URL containing an XML file: https://www.w3schools.com/xml/note.xml
> 
> On Android, this is not recognized as a downloadable file, and it shows on the browser (this depends on the Android WebView implementation). Instead, on iOS, it is recognized as a downloadable file.
> 
> However, for some reason, if the `onDownloadStart` is not called, you can also use the `shouldOverrideUrlLoading` event (enable it with `useShouldOverrideUrlLoading: true` option) to intercept requests after the first one made with initial URL. Then you check for your specific URL, cancel the request, and download the file.
> 
> Here is the code:
> 
> ```dart
> import 'dart:async';
> import 'package:flutter/material.dart';
> import 'package:flutter_downloader/flutter_downloader.dart';
> import 'package:flutter_inappwebview/flutter_inappwebview.dart';
> import 'package:path_provider/path_provider.dart';
> 
> Future main() async {
>   WidgetsFlutterBinding.ensureInitialized();
> 
>   await FlutterDownloader.initialize(
>       debug: true // optional: set false to disable printing logs to console
>   );
> 
>   runApp(new MyApp());
> }
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => new _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>         home: InAppWebViewPage()
>     );
>   }
> }
> 
> class InAppWebViewPage extends StatefulWidget {
>   @override
>   _InAppWebViewPageState createState() => new _InAppWebViewPageState();
> }
> 
> class _InAppWebViewPageState extends State<InAppWebViewPage> {
>   InAppWebViewController _webViewController;
> 
>   @override
>   void initState() {
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         appBar: AppBar(
>           title: const Text('InAppWebView Example'),
>         ),
>         body: SafeArea(
>           child: Container(
>               child: InAppWebView(
>                 initialUrl: "https://www.w3schools.com/xml/note.xml",
>                 initialOptions: InAppWebViewGroupOptions(
>                     crossPlatform: InAppWebViewOptions(
>                       debuggingEnabled: true,
>                       useOnDownloadStart: true,
>                       useShouldOverrideUrlLoading: true
>                     ),
>                 ),
>                 onWebViewCreated: (InAppWebViewController controller) {
>                   _webViewController = controller;
>                 },
>                 shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
>                   // use shouldOverrideUrlLoading to intercept requests after the first one and check if it is an XML file
>                   var url = shouldOverrideUrlLoadingRequest.url;
>                   if (url.endsWith(".xml")) {
>                     // it's an xml file, then cancel the request and download the file
>                     download(url);
>                     return ShouldOverrideUrlLoadingAction.CANCEL;
>                   }
>                   return ShouldOverrideUrlLoadingAction.ALLOW;
>                 },
>                 onLoadStart: (controller, url) {
>                   if (url.endsWith(".xml")) {
>                     // put this check here if the first url contains your xml file.
>                     // Instead, for subsequent requests, you can use shouldOverrideUrlLoading event.
>                     download(url);
>                   }
>                 },
>                 onDownloadStart: (controller, url) async {
>                   download(url);
>                 },
>               ),
>             ),
>           ),
>       ),
>     );
>   }
> 
>   void download(String url) async {
>     final taskId = await FlutterDownloader.enqueue(
>       url: url,
>       savedDir: (await getApplicationDocumentsDirectory()).path,
>       showNotification: true, // show download progress in status bar (for Android)
>       openFileFromNotification: true, // click on notification to open downloaded file (for Android)
>     );
>   }
> }
> ```
Works (y)
