### ISSUE TITLE
Facebook Login and Google Login Issue

### ISSUE THREAD

**Issue by limsocheat** [pichillilorenzo/flutter_inappwebview#431]
Trying to login to embedded website with Google and Facebook. 
**Google:**
Stuck on **"One moment please..."** screen
![image](https://user-images.githubusercontent.com/6656644/86467554-c6054b80-bd5f-11ea-9796-883a63f9dba9.png)

**Facebook:** 
Stuck on "**Please close this tab**" screen
![image](https://user-images.githubusercontent.com/6656644/86467492-aa9a4080-bd5f-11ea-970f-e25b80c67a2f.png)

My Code: 
```
body: InAppWebView(
            initialUrl: "https://drrabbittutor.com/",
            initialHeaders: {},
            initialOptions: InAppWebViewGroupOptions(
              android: AndroidInAppWebViewOptions(
                allowContentAccess: true,
                builtInZoomControls: true,
                thirdPartyCookiesEnabled: true,
                allowFileAccess: true,
              ),
              crossPlatform: InAppWebViewOptions(
                verticalScrollBarEnabled: true,
                useShouldInterceptAjaxRequest: true,
                clearCache: false,
                disableContextMenu: false,
                cacheEnabled: true,
                javaScriptEnabled: true,
                javaScriptCanOpenWindowsAutomatically: true,
                debuggingEnabled: true,
                transparentBackground: true,
                useShouldInterceptFetchRequest: true,
                applicationNameForUserAgent: 'DR RABBIT',
                userAgent:
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36',
              ),
            ),
            onWebViewCreated: (InAppWebViewController controller) {
              webView = controller;
            },
          ),
```

**Comment by pichillilorenzo** [comment]
There aren't any issues. You need to use the `onCreateWindow` event to intercept `window.open()` JavaScript requests.
On Android, you need also add `supportMultipleWindows: true` option.

Here is a full code example that opens a popup window when you try to login with Google or Facebook:
```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:path_provider/path_provider.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await FlutterDownloader.initialize(
      debug: true // optional: set false to disable printing logs to console
  );

  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: InAppWebViewPage()
    );
  }
}

class InAppWebViewPage extends StatefulWidget {
  @override
  _InAppWebViewPageState createState() => new _InAppWebViewPageState();
}

class _InAppWebViewPageState extends State<InAppWebViewPage> {
  InAppWebViewController _webViewController;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('InAppWebView Example'),
        ),
        body: SafeArea(
          child: Container(
              child: InAppWebView(
                initialUrl: "https://drrabbittutor.com/",
                initialOptions: InAppWebViewGroupOptions(
                  android: AndroidInAppWebViewOptions(
                    allowContentAccess: true,
                    builtInZoomControls: true,
                    thirdPartyCookiesEnabled: true,
                    allowFileAccess: true,
                    supportMultipleWindows: true
                  ),
                  crossPlatform: InAppWebViewOptions(
                    verticalScrollBarEnabled: true,
                    clearCache: true,
                    disableContextMenu: false,
                    cacheEnabled: true,
                    javaScriptEnabled: true,
                    javaScriptCanOpenWindowsAutomatically: true,
                    debuggingEnabled: true,
                    transparentBackground: true,
                  ),
                ),
                onWebViewCreated: (InAppWebViewController controller) {
                  _webViewController = controller;
                },
                onCreateWindow: (controller, createWindowRequest) async {
                  showDialog(
                    context: context,
                    builder: (context) {
                      return AlertDialog(
                        content: Container(
                          width: MediaQuery.of(context).size.width,
                          height: 400,
                          child: InAppWebView(
                            // Setting the windowId property is important here!
                            windowId: createWindowRequest.windowId,
                            initialOptions: InAppWebViewGroupOptions(
                              android: AndroidInAppWebViewOptions(
                                  builtInZoomControls: true,
                                  thirdPartyCookiesEnabled: true,
                              ),
                              crossPlatform: InAppWebViewOptions(
                                cacheEnabled: true,
                                javaScriptEnabled: true,
                                debuggingEnabled: true,
                                userAgent: "Mozilla/5.0 (Linux; Android 9; LG-H870 Build/PKQ1.190522.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36"
                              ),
                            ),
                            onWebViewCreated: (InAppWebViewController controller) {

                            },
                            onLoadStart: (InAppWebViewController controller, String url) {
                              print("onLoadStart popup $url");
                            },
                            onLoadStop: (InAppWebViewController controller, String url) async {
                              print("onLoadStop popup $url");
                            },
                            onCloseWindow: (controller) {
                              // On Facebook Login, this event is called twice,
                              // so here we check if we already popped the alert dialog context
                              if (Navigator.canPop(context)) {
                                Navigator.pop(context);
                              }
                            },
                          ),
                        ),
                      );
                    },
                  );

                  return true;
                },
              ),
            ),
          ),
      ),
    );
  }

  void download(String url) async {
    final taskId = await FlutterDownloader.enqueue(
      url: url,
      savedDir: (await getApplicationDocumentsDirectory()).path,
      showNotification: true, // show download progress in status bar (for Android)
      openFileFromNotification: true, // click on notification to open downloaded file (for Android)
    );
  }
}
```

Check out how `onCreateWindow` event works here:
[InAppWebView: The Real Power of WebViews in Flutter](https://medium.com/flutter-community/inappwebview-the-real-power-of-webviews-in-flutter-c6d52374209d?source=friends_link&sk=cb74487219bcd85e610a670ee0b447d0), under the "How to manage popup windows opened with target=”_blank” or “window.open”" Section.

Also, to open the popup webview, I used this user agent to make the Google Login work:
```
"Mozilla/5.0 (Linux; Android 9; LG-H870 Build/PKQ1.190522.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36"
```
as said [here](https://stackoverflow.com/a/52831327/4637638), removing the `; wv` chars from the original user agent.

**Comment by limsocheat** [comment]
> There aren't any issues. You need to use the `onCreateWindow` event to intercept `window.open()` JavaScript requests.
> On Android, you need also add `supportMultipleWindows: true` option.
> 
> Here is a full code example that opens a popup window when you try to login with Google or Facebook:
> 
> ```dart
> import 'dart:async';
> import 'package:flutter/material.dart';
> import 'package:flutter_inappwebview/flutter_inappwebview.dart';
> import 'package:path_provider/path_provider.dart';
> 
> Future main() async {
>   WidgetsFlutterBinding.ensureInitialized();
> 
>   runApp(new MyApp());
> }
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => new _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>         home: InAppWebViewPage()
>     );
>   }
> }
> 
> class InAppWebViewPage extends StatefulWidget {
>   @override
>   _InAppWebViewPageState createState() => new _InAppWebViewPageState();
> }
> 
> class _InAppWebViewPageState extends State<InAppWebViewPage> {
>   InAppWebViewController _webViewController;
> 
>   @override
>   void initState() {
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         appBar: AppBar(
>           title: const Text('InAppWebView Example'),
>         ),
>         body: SafeArea(
>           child: Container(
>               child: InAppWebView(
>                 initialUrl: "https://drrabbittutor.com/",
>                 initialOptions: InAppWebViewGroupOptions(
>                   android: AndroidInAppWebViewOptions(
>                     allowContentAccess: true,
>                     builtInZoomControls: true,
>                     thirdPartyCookiesEnabled: true,
>                     allowFileAccess: true,
>                     supportMultipleWindows: true
>                   ),
>                   crossPlatform: InAppWebViewOptions(
>                     verticalScrollBarEnabled: true,
>                     clearCache: true,
>                     disableContextMenu: false,
>                     cacheEnabled: true,
>                     javaScriptEnabled: true,
>                     javaScriptCanOpenWindowsAutomatically: true,
>                     debuggingEnabled: true,
>                     transparentBackground: true,
>                   ),
>                 ),
>                 onWebViewCreated: (InAppWebViewController controller) {
>                   _webViewController = controller;
>                 },
>                 onCreateWindow: (controller, createWindowRequest) async {
>                   showDialog(
>                     context: context,
>                     builder: (context) {
>                       return AlertDialog(
>                         content: Container(
>                           width: MediaQuery.of(context).size.width,
>                           height: 400,
>                           child: InAppWebView(
>                             // Setting the windowId property is important here!
>                             windowId: createWindowRequest.windowId,
>                             initialOptions: InAppWebViewGroupOptions(
>                               android: AndroidInAppWebViewOptions(
>                                   builtInZoomControls: true,
>                                   thirdPartyCookiesEnabled: true,
>                               ),
>                               crossPlatform: InAppWebViewOptions(
>                                 cacheEnabled: true,
>                                 javaScriptEnabled: true,
>                                 debuggingEnabled: true,
>                                 userAgent: "Mozilla/5.0 (Linux; Android 9; LG-H870 Build/PKQ1.190522.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36"
>                               ),
>                             ),
>                             onWebViewCreated: (InAppWebViewController controller) {
> 
>                             },
>                             onLoadStart: (InAppWebViewController controller, String url) {
>                               print("onLoadStart popup $url");
>                             },
>                             onLoadStop: (InAppWebViewController controller, String url) async {
>                               print("onLoadStop popup $url");
>                             },
>                             onCloseWindow: (controller) {
>                               // On Facebook Login, this event is called twice,
>                               // so here we check if we already popped the alert dialog context
>                               if (Navigator.canPop(context)) {
>                                 Navigator.pop(context);
>                               }
>                             },
>                           ),
>                         ),
>                       );
>                     },
>                   );
> 
>                   return true;
>                 },
>               ),
>             ),
>           ),
>       ),
>     );
>   }
> }
> ```
> 
> Check out how `onCreateWindow` event works here:
> [InAppWebView: The Real Power of WebViews in Flutter](https://medium.com/flutter-community/inappwebview-the-real-power-of-webviews-in-flutter-c6d52374209d?source=friends_link&sk=cb74487219bcd85e610a670ee0b447d0), under the "How to manage popup windows opened with target=”_blank” or “window.open”" Section.
> 
> Also, to open the popup webview, I used this user agent to make the Google Login work:
> 
> ```
> "Mozilla/5.0 (Linux; Android 9; LG-H870 Build/PKQ1.190522.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36"
> ```
> 
> as said [here](https://stackoverflow.com/a/52831327/4637638), removing the `; wv` chars from the original user agent.

Hi @pichillilorenzo,
Thanks for your detail answer.
I got an issue: **windowId** and **onCloseWindow** is not defined. 

![image](https://user-images.githubusercontent.com/6656644/86502793-5465e580-bdd1-11ea-8c75-2551b99acda2.png)

**Comment by limsocheat** [comment]
Hi Thanks for you detail answer. 
It works as expected now.

**Comment by khairulanas** [comment]
thanks, very usefull ♥♥♥

**Comment by trithien98** [comment]
Hi @pichillilorenzo  , what do you think is the main reason to show the issue in Stuck on the "One moment please..." screen in google sign in and Facebook screen "Please close this tab" like @limsocheat  ? . I'm facing it but not in flutter  , it react-native, I'm using react-native-webview but walk around with this. and i trying to fixing this with react-native
