### ISSUE TITLE
Webview content default size is too small

### ISSUE THREAD

**Issue by GIfatahTH** [pichillilorenzo/flutter_inappwebview#433]
Thanks for the great plugging. I tried with the official plugging and switched to your plugging which I found far away better.

I have a little problem, I load a static HTML data and the content default size is too small. 

Try this :

```dart
initialData: InAppWebViewInitialData(
                    data: '<h1>hello world</h1>',
                 ),
```

**Comment by taej0127** [comment]
I have same issue when using inapplocalhostserver and asset html

**Comment by GIfatahTH** [comment]
I got it, just set `useWideViewPort` parameter of `AndroidInAppWebViewOptions` to false

I think it should default to false

**Comment by Chanjinger** [comment]
It doesn't work

**Comment by callmejm** [comment]
This is how I solve, set `textZoom: 110`  from `AndroidInAppWebViewOptions` or you can wrap the html code with meta initial scale instead of direct load html code, for better html content.

	    getHtmlContent(){
	      	return '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="padding:0 1rem;">${myhtmlcode}</body></html>';
	    }

	    InAppWebView(
		    initialData: InAppWebViewInitialData(
		      data: getHtmlContent()
		    ) : null,
		    initialOptions: InAppWebViewGroupOptions(
		      crossPlatform: InAppWebViewOptions(
		          debuggingEnabled: false,
		          javaScriptEnabled: true,
		          supportZoom: false,
		      ),
		      android: AndroidInAppWebViewOptions(
		        useWideViewPort:false,
		        initialScale:0,
		        textZoom: 110
		      ),
		      ios: IOSInAppWebViewOptions(
		        allowsBackForwardNavigationGestures:false
		      ),
		    ),
		)
