### ISSUE TITLE
Authorization Error, Error 403: disallowed_useragent

### ISSUE THREAD

**Issue by pengw00** [pichillilorenzo/flutter_inappwebview#434]
I am using inAppBrowser, but when login use google auth, it throws this error. Any idea?
![Screen Shot 2020-07-05 at 12 55 48 PM](https://user-images.githubusercontent.com/6376970/86538970-e39cf700-bebe-11ea-97c1-238d59bc1ffd.png)

**Comment by pichillilorenzo** [comment]
As said in this [StackOverflow issue](https://stackoverflow.com/a/52831327/4637638), you can set, for example, this user agent `Mozilla/5.0 (Linux; Android 9; LG-H870 Build/PKQ1.190522.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36`.

However, you probably need to check this issue https://github.com/pichillilorenzo/flutter_inappwebview/issues/431 if you need to open a new "browser tab" to make the login. Probably, you need to use `onCreateWindow` event and open a new InAppBrowser instance using `createWindowRequest.windowId`.
