### ISSUE TITLE
Webview is not loading

### ISSUE THREAD

**Issue by devraj-kumar** [pichillilorenzo/flutter_inappwebview#435]
I AM JUST COPYING DOWN THE EXACT CODE, BUT WITHIN THE WEB VIEW CONTAINER NOTHING IS APPEARING, THE CONTAINER FOR WEB VIEW IS APPEARING AS AN EMPTY BOX

**Comment by pichillilorenzo** [comment]
Please, don't delete the ISSUE TEMPLATE when you open an issue. **It's there for a reason**.

If you don't give me some info, how could you think that I could solve your problem without it?

Post any error logs you are receiving. Also, if you use HTTP (non-HTTPS) protocol, you need to enable HTTP support (check the README.md to see how to do it).

Use this template to give more info:

```
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: <!-- Manufacturer and model -->

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

<!-- Optionally provide the least amount of code that shows this behaviour. -->

1. This
2. Than that
3. Then

## Images <!-- if available, else delete -->  

## Stacktrace/Logcat <!-- if available, else delete -->  
```

Thanks
