### ISSUE TITLE
ITMS-90809: Deprecated API Usage - existing app that use UIWebView are no longer accepted

### ISSUE THREAD

**Issue by DjangoOverloard** [pichillilorenzo/flutter_inappwebview#436]
When uploading the app to the App Store Connect, this error gets delivered to my email after their verification.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

As this is the only plugin that uses the WebView in my project, I think that the source of the error is here.

**Comment by pichillilorenzo** [comment]
I don't use `UIWebView` in any parts of my code. I only use `WKWebView`.
Just search for `UIWebView` and you won't find any reference in my code.
Maybe you have a plugin that, for some reason, uses `UIWebView` in background. Check

**Comment by DjangoOverloard** [comment]
Sorry for my accusation, I really should've done some research prior to opening this issue.

My issue in fact was in flutter_qr_barcode_scanner plugin, that was using the GoogleMobileVision extension. I found it using the recursive search like so: `grep -r "UIWebView" .`, and it did the job. Maybe someone reading this will be helped too.

**Comment by pichillilorenzo** [comment]
No problem! Thanks!
