### ISSUE TITLE
HeadlessInAppWebView sometimes the rendered page cannot be obtained correctly

### ISSUE THREAD

**Issue by hahafather007** [pichillilorenzo/flutter_inappwebview#437]
```
    _webView = HeadlessInAppWebView(
      initialUrl: _getUrl(),
      onLoadStart: (_, __) {
        _isWebLoading = true;
      },
      onLoadStop: (controller, _) async {
        final html = await controller.getHtml();

        _autoGetUrlFromHtml(html);
        _isWebLoading = false;
      },
    );
```
version: `flutter_inappwebview: 4.0.0`

In the case of the same URL, after the loading is completed, sometimes the HTML code of the rendered page can be correctly obtained, but sometimes only the source code can be obtained.

**Comment by pichillilorenzo** [comment]
What do you mean with "correctly"? `await controller.getHtml()` returns the HTML source code available at the moment of the method call. If the page uses JavaScript with frameworks such as Angular or React, probably there could be some delay when they load HTML elements after the webpage is loaded (when `onLoadStop` is triggered).

**Comment by hahafather007** [comment]
Sorry, that may be my misunderstanding. Is there any way to monitor the page js loading, because I want to get the rendered page accurately

**Comment by hahafather007** [comment]
![0F5AC129-944B-4A47-A5C8-100C35A88FF6](https://user-images.githubusercontent.com/23414420/86573527-16221f00-bfa7-11ea-863f-270749961d35.png)
This method, sometimes returns the page code that has been rendered after the JavaScript is completed, and sometimes returns the page source code. And there seems to be no regularity.

url: `https://m.douyu.com/74960`

**Comment by hahafather007** [comment]
anyone?

**Comment by eduardusnico** [comment]
yeah i got some AAAAAAAAAA in my getHtml().
