### ISSUE TITLE
InAppWebview causes Chewie video controls to blur out

### ISSUE THREAD

**Issue by nimisis** [pichillilorenzo/flutter_inappwebview#444]
## Description
I have a video playing with a webview below it. Weirdly, when the webview loads, the video controls blur out.

**Expected behavior:** 
For video controls not to blur.

**Current behavior:** 
Video controls get blurred.

## Steps to reproduce
Sample app here - https://github.com/nimisis/videobug

## Images 
![image](https://user-images.githubusercontent.com/385121/86937994-ce7ecd00-c137-11ea-8d6a-7182f6afb6a1.png)

**Comment by SunFoxx** [comment]
I have a same problem, usage of InAppWebview causing BackdropFilter with ImageFilter.blur to blur through the all widgets on Z-axis

Here is an example. First screenshot shows correctly working blur on the appbar - it is slightly bluring background image
![image](https://user-images.githubusercontent.com/22888206/87078383-36630f80-c22d-11ea-8de9-1e765d215955.png)
Once youtube player appears (it is using InAppWebview under-hood) blur is starting to pass through the all widgets
![image](https://user-images.githubusercontent.com/22888206/87078405-3e22b400-c22d-11ea-8cf4-f86b441196cc.png)

**Comment by nimisis** [comment]
Getting rid of sigmaX and sigmaY values in chewie / cupertino_controls.dart fixes this for me.

**Comment by tanlianghao** [comment]
> I have a same problem, usage of InAppWebview causing BackdropFilter with ImageFilter.blur to blur through the all widgets on Z-axis
> 
> Here is an example. First screenshot shows correctly working blur on the appbar - it is slightly bluring background image
> ![image](https://user-images.githubusercontent.com/22888206/87078383-36630f80-c22d-11ea-8de9-1e765d215955.png)
> Once youtube player appears (it is using InAppWebview under-hood) blur is starting to pass through the all widgets
> ![image](https://user-images.githubusercontent.com/22888206/87078405-3e22b400-c22d-11ea-8cf4-f86b441196cc.png)
> 
> It seems like this bug only appears on iOS platform

I have the same problem, have you solved it
