### ISSUE TITLE
Question: Can i preload a webview in headless mode and then attach to InAppWebview Widget

### ISSUE THREAD

**Issue by rajeshzmoke** [pichillilorenzo/flutter_inappwebview#447]
this question may sound silly but this is what I'm looking for, my app uses webviews to show most of the features that my website has until i can build them in Flutter.

But the issue is webviews are slow and also my website need cookies to be set.

So is there a way i can preload a webview when app starts up and show it when required ?

**Comment by pichillilorenzo** [comment]
You can use for example the `Stack` widget or `IndexedStack` widget and, then, show the `InAppWebView` widget child when you need it.
