### ISSUE TITLE
Cookies disable in for iOS

### ISSUE THREAD

**Issue by mayuriruparel** [pichillilorenzo/flutter_inappwebview#449]
I am using webview for payment gateway for one of my client. flutter_inappwebview 4.0.0+4

It is working perfectly for android in this plugin but when I run on iOS it is not working. Payment gateway error shows that cookies are disable in your browswer.

Here is the code.

body: InAppWebView( initialUrl: weburl, initialOptions: InAppWebViewGroupOptions(

      ios: IOSInAppWebViewOptions(
        sharedCookiesEnabled: true,
      ),

      crossPlatform: InAppWebViewOptions(
        debuggingEnabled: true,
        javaScriptEnabled: true,

      )
  ),
  onWebViewCreated: (InAppWebViewController controller) {
    webView = controller;

  },
  onLoadStart: (InAppWebViewController controller, String url) {
    if (url == successURL) {
      Navigator.of(context).pushReplacementNamed('/NormalOrderSuccess',
          arguments: RouteArgument(
              heroTag: widget.routeArgument.heroTag, param: order));
    } else if (url == failURL) {
        Payment payment = order.payment;
        payment.status = 'fail';
        order.payment = payment;
        Navigator.of(context).pushReplacementNamed(
            '/NormalOrderSuccess',
            arguments: RouteArgument(
                heroTag: widget.routeArgument.heroTag, param: order));
    }

  },
  onLoadStop: (InAppWebViewController controller, String url) async {
    List<Cookie> cookies = await _cookieManager.getCookies(url: url);
    cookies.forEach((cookie) {
      print(cookie.name + " " + cookie.value);
    });
  },
  onProgressChanged: (InAppWebViewController controller, int progress) {

  },
),

)), );

**Comment by blasko** [comment]
Running into this as well. Works fine on Android, however on iOS, cookies do not get set.

**Comment by corcoran** [comment]
Also running into this -- cannot get cookies in iOS using CookieManager. Using javascript as a workaround:
```js
  Future<String> getCookieWithJs(
      String key, InAppWebViewController controller) async {
    String cookie = await controller.evaluateJavascript(source: '''
    document.cookie
        .split('; ')
        .find(row => row.startsWith('$key'));
      ''');

    if (cookie.isNotEmpty) {
      return cookie.split('=')[1];
    }
    return null;
  }
```
