### ISSUE TITLE
Autofill is disabled on Android

### ISSUE THREAD

**Issue by gjaber** [pichillilorenzo/flutter_inappwebview#453]
I'm loading a form that has a autofill field, but on Android isn't working. 
On console is showing:

W/cr_AwAutofillManager(28324): Autofill is disabled: AutofillManager isn't available in given Context.
W/IInputConnectionWrapper(28324): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(28324): getTextAfterCursor on inactive InputConnection

**Comment by iaexc** [comment]
Hi, I am also having the same issue. Any update on this? Thanks!

**Comment by 94wogus** [comment]
same here!

**Comment by NguyenPhatBG** [comment]
Solution for this? Anyone known that?
