### ISSUE TITLE
cant see the highlight pointers

### ISSUE THREAD

**Issue by mrifni** [pichillilorenzo/flutter_inappwebview#455]
using the latest version.
please see the attached screenshot. When I highlight the text i cant see the pointers but this is working on IOS.
<img width="459" alt="Screenshot 2020-07-16 at 16 03 40" src="https://user-images.githubusercontent.com/1643992/87687694-f09ecd80-c77d-11ea-9947-dfac4844ecd8.png">

**Comment by pichillilorenzo** [comment]
Duplicate of https://github.com/pichillilorenzo/flutter_inappwebview/issues/380
