### ISSUE TITLE
HeadlessInAppWebView  怎么动态改变url？

### ISSUE THREAD

**Issue by songguowei** [pichillilorenzo/flutter_inappwebview#456]
HeadlessInAppWebView  怎么动态改变url？

**Comment by comingdemon** [comment]
controller.loadUrl(url:'');

**Comment by pichillilorenzo** [comment]
You can load an URL dynamically calling the `InAppWebViewController.loadUrl` method.
In general, `HeadlessInAppWebView` uses the same `InAppWebViewController` class of `InAppWebView` widget to control the webview, so you can use the same methods.
