### ISSUE TITLE
Multiple webviews blank out

### ISSUE THREAD

**Issue by owenkealey** [pichillilorenzo/flutter_inappwebview#459]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |1.17               |
| Plugin version       |   4.0.0+4            |
| Android version      |           n/a    |
| iOS version          |    13.6           |
| Xcode version        |  11.6             |

Device information: 
iPhone XS Max
## Description
I have an iOS only app that basically is a browser app and thus has "tabs" which on the code side are just multiple InAppWebView instances. They are all arranged as children of an IndexedStack so that the user can control which tab is showing on the screen. The problem arises when the user creates many tabs, maybe ten or more. After a while, when the user flips to a different tab, the tab's webview does not load -- it's loading progress goes to 0 and fails to render any content leaving a blank screen. Some users can reproduce this with just two tabs. 

I Suspect this probably has something to do with memory usage and this issue: https://stackoverflow.com/questions/27565301/wkwebview-goes-blank-after-memory-warning especially since the accepted answer there(reloading the webview) usually works in bringing back the webview in my app. Not optimal though. 

**Expected behavior:** 
All tabs show when clicked on.

**Current behavior:** 
Some tabs stop rendering some time into using the app. Usually with lots of tabs, usually after a couple minutes. 

## Steps to reproduce

Run this on a iPhone:

```
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Buggy Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _tab = 0;

  void _changeTab() {
    setState(() {
      _tab == 10 ? _tab = 0 : _tab ++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: IndexedStack(
          index: _tab,
          /// These are the "tabs"
          children: <Widget>[
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
            InAppWebView(initialUrl: "https://footlocker.com",initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(incognito: true)),),
          ],
        )
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _changeTab,
        tooltip: 'Switch Webview',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

Note that this is NOT reproducible on the simulator(I suspect because as part of the desktop the simulator has access to much more ram than a physical device).

As for the xcode logs, people implementing WKWebview directly with Swift seems to have come upon this issue and fix it with this: https://stackoverflow.com/questions/44585980/com-apple-webkit-webcontent-drops-113-error-could-not-find-specified-service

## Stacktrace/Logcat   
No logs or errors reported by the plugin, flutter but when run through Xcode there is this:

Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-18 23:19:54.859978-0400 Runner[2014:211313] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-18 23:19:54.860171-0400 Runner[2014:211313] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-18 23:19:54.860597-0400 Runner[2014:211313] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-18 23:19:54.863622-0400 Runner[2014:211313] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-18 23:19:54.866389-0400 Runner[2014:211313] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-18 23:19:54.871491-0400 Runner[2014:211313] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-18 23:19:54.871776-0400 Runner[2014:211313] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by virskor** [comment]
same

**Comment by manojdvs123** [comment]
yeah for me 
webview is in pageview , after scrolling 4 or 5 pages it stops loading one page.
don't know why it happens.

**Comment by owenkealey** [comment]
Caused by this https://github.com/flutter/flutter/issues/61795

**Comment by owenkealey** [comment]
Upvote for visibility please!

**Comment by rodruiz** [comment]
Experiencing the same issue on Android.

**Comment by manojdvs123** [comment]
> Caused by this [flutter/flutter#61795](https://github.com/flutter/flutter/issues/61795)

so refreshing the webview is the only way to overcome this as of now ?
any other solutions ?

**Comment by rodruiz** [comment]
I can see those InAppWebViews are stuck around 70% or 80% of the progress. Sometimes switching the bottom navigation bar re-render the webview.
Experiencing this with only 3 InAppWebView (first webview is loading fine, the issue is 2nd and 3rd).
Using PageView with BottomNavigation bar.

**Comment by manojdvs123** [comment]
> Experiencing the same issue on Android

> I can see those InAppWebViews are stuck around 70% or 80% of the progress. Sometimes switching the bottom navigation bar re-render the webview.
> Experiencing this with only 3 InAppWebView (first webview is loading fine, the issue is 2nd and 3rd).
> Using PageView with BottomNavigation bar.

i switched to this webview because it loads html content much quicker that the official webview_flutter plugin , but im struck here.

**Comment by rodruiz** [comment]
> > Experiencing the same issue on Android
> 
> > I can see those InAppWebViews are stuck around 70% or 80% of the progress. Sometimes switching the bottom navigation bar re-render the webview.
> > Experiencing this with only 3 InAppWebView (first webview is loading fine, the issue is 2nd and 3rd).
> > Using PageView with BottomNavigation bar.
> 
> i switched to this webview because it loads html content much quicker that the official webview_flutter plugin , but im struck here.

In my opinion this plugin is much better than the official webview_flutter plugin. The support is even better. You can submit a PR to the official plugin and will be stuck there for months.
Very impressed with this plugin, main features I'm using:
- cookies manager. (NO ISSUES SO FAR)
- Pause/resume the webview. For me this is very IMPORTANT when using bottom navigation and switching webviews. Have to use this when the app is paused too.

**Comment by owenkealey** [comment]
This is caused by Flitters mishandling of PlatformViews which is why the same problems happen with other web view plugins. Please relocate here https://github.com/flutter/flutter/issues/61795

**Comment by pichillilorenzo** [comment]
@owenkealey So, if I have not misunderstood, Flutter doesn't remove the hidden WebViews from memory, as if they were always visible. This way they waste RAM, right?

**Comment by owenkealey** [comment]
@pichillilorenzo Thats the most likely explanation

**Comment by owenkealey** [comment]
@rodruiz for sure, flutter_inappwebview is much much much better than webview_flutter

**Comment by manojdvs123** [comment]
Is there any way to delete the webhistory. Please let me know if any.
