### ISSUE TITLE
On some Android models, full-screen video programs crash.

### ISSUE THREAD

**Issue by zhangxiaoga** [pichillilorenzo/flutter_inappwebview#461]
NullPointerException Error log:

E/AndroidRuntime(28480): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
E/AndroidRuntime(28480):  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1900)
E/AndroidRuntime(28480):  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
E/AndroidRuntime(28480):  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
E/AndroidRuntime(28480):  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
E/AndroidRuntime(28480):  at android.view.Choreographer.doCallbacks(Choreographer.java:893)
E/AndroidRuntime(28480):  at android.view.Choreographer.doFrame(Choreographer.java:812)
E/AndroidRuntime(28480):  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
E/AndroidRuntime(28480):  at android.os.Handler.handleCallback(Handler.java:907)
E/AndroidRuntime(28480):  at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(28480):  at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(28480):  at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(28480):  at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28480):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(28480):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
I/Process (28480): Sending signal. PID: 28480 SIG: 9

**Comment by lijing89** [comment]
similar problem！
error log：
W/InputMethodManager(32237): startInputReason = 4
W/libEGL  (32237): EGLNativeWindowType 0x7618f47010 disconnect failed
D/mali_winsys(32237): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/HwCust  (32237): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
D/HwRTBlurUtils(32237): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@2402fd9, Nhwext : 0, get Blur : disable with , null
D/HwRTBlurUtils(32237): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@2402fd9, Nhwext : 0, get Blur : disable with , null
D/OpenGLRenderer(32237):   HWUI Binary is  enabled
I/PressGestureDetector(32237): onAttached begin
I/PressGestureDetector(32237): onAttached end
I/PressGestureDetector(32237): HiTouch restricted: Sub windows restricted.
D/mali_winsys(32237): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/AndroidRuntime(32237): Shutting down VM
E/AndroidRuntime(32237): FATAL EXCEPTION: main
E/AndroidRuntime(32237): Process: app.naotianshi.cn, PID: 32237
E/AndroidRuntime(32237): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
E/AndroidRuntime(32237):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1753)
E/AndroidRuntime(32237):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
E/AndroidRuntime(32237):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7292)
E/AndroidRuntime(32237):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
E/AndroidRuntime(32237):     at android.view.Choreographer.doCallbacks(Choreographer.java:790)
E/AndroidRuntime(32237):     at android.view.Choreographer.doFrame(Choreographer.java:721)
E/AndroidRuntime(32237):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
E/AndroidRuntime(32237):     at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(32237):     at android.os.Handler.dispatchMessage(Handler.java:101)
E/AndroidRuntime(32237):     at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(32237):     at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AndroidRuntime(32237):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32237):     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(32237):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
D/JIGUANG-JCore-IMPL(32237): [JCommonInterface] onEvent action:deviceinfo
D/JIGUANG-JCore(32237): [HttpHelper] status code:200 retry left:2
I/Process (32237): Sending signal. PID: 32237 SIG: 9
