### ISSUE TITLE
Accessing gallery and camera

### ISSUE THREAD

**Issue by deenadayalanr** [pichillilorenzo/flutter_inappwebview#464]
How to access the camera and files from storage

**Comment by ycv005** [comment]
Here is the answer- https://github.com/pichillilorenzo/flutter_inappwebview#how-to-enable-the-usage-of-camera-for-html-inputs-such-as-input-typefile-acceptimage-capture

**Comment by Kamoba** [comment]
> 
> 
> Here is the answer- https://github.com/pichillilorenzo/flutter_inappwebview#how-to-enable-the-usage-of-camera-for-html-inputs-such-as-input-typefile-acceptimage-capture

Already use recommendation from that link.
But something prevent to have direct access to the camera.
This [link ](https://jsfiddle.net/4WHw5/show)can test the tag `<input type="file" accept="image/*" capture>` and work in my mobile browser, Brave or Chrome.
But if used on flutter_inappwebview will show:
![upload](https://user-images.githubusercontent.com/35287463/110637680-e7c69600-816a-11eb-8ab5-8f8344b6e130.png)

I tryed as well userAgent option to match with my device but still.
I even test it in iframe but still asking to select without going direct to camera.

**Comment by pichillilorenzo** [comment]
@Kamoba Feature added starting from version `5.5.0`
