### ISSUE TITLE
Not able to add splash screen

### ISSUE THREAD

**Issue by deenadayalanr** [pichillilorenzo/flutter_inappwebview#467]
Have converted a website to app using flutter_inappwebview...reied adding the splash screen but not able to add it

**Comment by lcsvcn** [comment]
Yes, I am facing this issue too.

I have added a splash screen to show progress indicator of Webview.

The widget shows the loading indicator shows fine in debug. In release it does not show at all.

I have tried using Stack and AnimatedCrossFade.

It seems to be a bug that does not allow overflow widget.

**Comment by lcsvcn** [comment]
Link to expected behavior recorded from simulator:
https://imgur.com/a/BUkdxKR

Link to the release app with the existing bug:
https://play.google.com/store/apps/details?id=tk.draft5community

I will add more info to reproduce this issue.

**Comment by lcsvcn** [comment]
loading.dart

> Center(
      child: Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage("assets/loading/background.png"),
            fit: BoxFit.cover,
          ),
        ),
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: Transform.scale(
          scale: 3.0,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Positioned(
                top: -30,
                child: Image.asset(
                  "assets/loading/icon.png",
                  height: 120,
                  width: 120,
                ),
              ),
              SizedBox(
                width: 100.0,
                child: LinearProgressIndicator(
                  backgroundColor: Colors.white,
                ),
              ),
              SizedBox(height: 10),
            ],
          ),
        ),
      ),
    );

**Comment by ccfiel** [comment]
any update on this?
