### ISSUE TITLE
#Handling back action in flutter_inappwebview without using any buttons

### ISSUE THREAD

**Issue by deenadayalanr** [pichillilorenzo/flutter_inappwebview#469]
Have implemented inappwebview in my project..trying to access goBack() without a button...tried doing it using a function....but not able to do it

**Comment by ycv005** [comment]
Waiting for the support. Thanks in advance.

**Comment by ycv005** [comment]
@pichillilorenzo Will you add this feature in upcoming update? Thanks

**Comment by varunkumarmedam** [comment]
If your app doesnt depend on cookie management, you can try flutter_webview_plugin thats works as you expected and its performance is damn smooth

**Comment by ycv005** [comment]
flutter_webview_plugin also doesn't support Error handling and GeoLocation ? Does it @varunkumarmedam . Thank you.

**Comment by varunkumarmedam** [comment]
I havent checked these..please let us know if you tried
