### ISSUE TITLE
Error: cannot find symbol

### ISSUE THREAD

**Issue by huiwen0212** [pichillilorenzo/flutter_inappwebview#470]
Hi, I am having some error when building the app on android phone

- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        1.7.5       |
| Plugin version       |   4.0.0            |
| Android version      |       10        |
| iOS version          |     13          |
| Xcode version        |      12         |

Device information: 

error: cannot find symbol
    flutterEngine.getPlugins().add(new io.flutter.plugins.webviewflutter.WebViewFlutterPlugin());
                                                                        ^
  symbol:   class WebViewFlutterPlugin                                  
  location: package io.flutter.plugins.webviewflutter                   
1 error                                                                 
                                                                        
FAILURE: Build failed with an exception.    

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G103, locale en-MY)
    • Flutter version 1.17.5 at /Users/macbook/Sites/flutter/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/macbook/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (1 available)
    • LDN LX2 • RBDBB18C27505513 • android-arm64 • Android 8.0.0 (API 26)

**Comment by pichillilorenzo** [comment]
As you can see from the error log, the problem is about the official flutter plugin (`io.flutter.plugins.webviewflutter`) and not mine.
Try to clear your project!
