### ISSUE TITLE
iPad browser unknown

### ISSUE THREAD

**Issue by ananthpranav** [pichillilorenzo/flutter_inappwebview#474]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         1.19.0      |
| Plugin version       |        4.0.0+4       | 
| iOS version          |       13.6        |
| Xcode version        |        11.6       |

Device information: 
iPad 12.9 Inch 
iOS Version - 13.6

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. Initialize webview with the url -  "https://browser-update.org/update.html"

2. ios options
  ios: IOSInAppWebViewOptions(
                                        enableViewportScale: true,
                                        minimumZoomScale: 1
                                    ),

## Images   
 
![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-08-07 at 14 27 30](https://user-images.githubusercontent.com/35189753/89629233-191c7200-d8bb-11ea-9ce9-f9a5ad318bfb.png)
# iPad doesn't have a browser version 

![Simulator Screen Shot - iPhone 8 Plus - 2020-08-07 at 14 27 26](https://user-images.githubusercontent.com/35189753/89629181-073acf00-d8bb-11ea-853f-a0b5b1e24baa.png)
# iPhone Does! 

# Stacktrace/Logcat

**Comment by pichillilorenzo** [comment]
That's not a plugin issue. Probably the website cannot recognize the iPad from its User-Agent.

However, you can set manually the WebView User-Agent, for example:
```dart
crossPlatform: InAppWebViewOptions(
  userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
),
```
This way, the website will always recognize it as an iPhone using "iOS Browser 13.7".
