### ISSUE TITLE
[Question] about onReceivedServerTrustAuthRequest in IOS

### ISSUE THREAD

**Issue by marcqtan** [pichillilorenzo/flutter_inappwebview#479]
Hi,

I'm using this package to open https site. I want to ignore the ssl for now and I've done it successfully in Android with code below:

InAppWebView(
                initialUrl: "https://localhost:8080/test/registration",
                onReceivedServerTrustAuthRequest: (_, __) async {
                  return ServerTrustAuthResponse(
                      action: ServerTrustAuthResponseAction.PROCEED);
                },
              )

But In IOS, it's just showing a blank white screen. How can i ignore the ssl in IOS?

Thanks!

**Comment by pichillilorenzo** [comment]
Check the [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios) section.

Probably you need to add some configuration into your `Info.plist` file, such as:
```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key><true/>
</dict>
```
or maybe `NSAllowsLocalNetworking`.
Check the official iOS Wiki.
