### ISSUE TITLE
Cannot delete webhistory for the webview.

### ISSUE THREAD

**Issue by manojdvs123** [pichillilorenzo/flutter_inappwebview#480]
Is there any way to delete the webhistory for inappwebview.
If there is any,please let me know.

**Comment by pichillilorenzo** [comment]
On Android, to clear the webview history, you can use the `InAppWebViewController.android.clearHistory` method that will be available in the next version 5.0.0.

For iOS, unfortunately, doesn't exist an official method to clear the webview (WKWebView) history such as on Android! I don't know why Apple didn't want to make public the method. So, if you need it on iOS, you need to implement the logic yourself on the Dart side.
