### ISSUE TITLE
iOS onLoadStart doesn't catch the header(Location)

### ISSUE THREAD

**Issue by EdoardoVignati** [pichillilorenzo/flutter_inappwebview#482]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      1.17.5         |
| Plugin version       |       4.0.0        |
| iOS version          |   10.15.6         |
| Xcode version        |     11.5   |

Device information: IPhone SE 2nd gen (13.5)

## Description

**Expected behavior:** 

When a webpage is redirected with _header("Location: ...")_ , the handler onLoadStart() should catch the redirection.

**Current behavior:** 

The redirection is done but the handler cannot catch it, so the only way to retrieve the url is to reload the target page.

Please note that in Android this works correctly.

Thanks

**Comment by bsp003** [comment]
@EdoardoVignati did you find any solution to this? I am facing the same issue

**Comment by EdoardoVignati** [comment]
Not at the moment, I'm sorry
