### ISSUE TITLE
When the keyboard pops up on Xiaomi's mobile phone, the screen will be black

### ISSUE THREAD

**Issue by jethroHuang** [pichillilorenzo/flutter_inappwebview#483]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        1.20.1 • channel stable        |
| Plugin version       |        4.0.0+4       |
| Android version      |         android 10      |
| iOS version          |         11      |
| Xcode version        |        11       |

Device information:  Xiao Mi 8 UD

## Description

**Expected behavior:** Pop-up keyboard

**Current behavior:** Black screen 0.5 seconds after the keyboard pops up

## Steps to reproduce

1. click input
2. Pop-up keyboard
3. Black screen for 0.5 second

**Comment by ykrank** [comment]
I catch same bug, log is
`
W/ContentCatcher(27604): Failed to notify a WebView
E/InputMethodManager(27604): b/117267690: Failed to get fallback IMM with expected displayId=92 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{f033022 VFEDHVCL. .F...... 0,0-1080,1370}
E/InputMethodManager(27604): b/117267690: Failed to get fallback IMM with expected displayId=92 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{f033022 VFEDHVCL. .F...... 0,0-1080,1370}
E/InputMethodManager(27604): b/117267690: Failed to get fallback IMM with expected displayId=92 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{f033022 VFEDHVCL. .F...... 0,0-1080,1370}
`

**Comment by heshaShawky** [comment]
I have this same issue too 😞

**Comment by rahuldange09** [comment]
You can add following line inside Scaffold. This solved issue for me on keyboard open/close when there is platform view .   
 `resizeToAvoidBottomInset: false`

**Comment by jethroHuang** [comment]
> You can add following line inside Scaffold. This solved issue for me on keyboard open/close when there is platform view .
> `resizeToAvoidBottomInset: false`

Thank you, but if you do, the keyboard will block the textarea. My textarea is full screen.

**Comment by rahuldange09** [comment]
> > You can add following line inside Scaffold. This solved issue for me on keyboard open/close when there is platform view .
> > `resizeToAvoidBottomInset: false`
> 
> Thank you, but if you do, the keyboard will block the textarea. My textarea is full screen.

Yeah. Somewhat i'm also facing same. Either flutter fixes this issue or this plugin adds some inner scroll can fix that issue.
If you find some workaround, please let us know. Meanwhile i'll also try.

**Comment by vov4ik08** [comment]
I have same problem. Reproduce on xiaomi with miui , but on clear android (xiaomi mi a2 android 10) not reproduce

**Comment by Trend74X** [comment]
> You can add following line inside Scaffold. This solved issue for me on keyboard open/close when there is platform view .
> `resizeToAvoidBottomInset: false`

It worked for me, does block some of the content at the bottom, but black screen doesnt flickers anymore

**Comment by rahuldange09** [comment]
All these issues has been fixed by hybrid composition. Until @pichillilorenzo update in_appwebview to version 5 to you can go ahead with 
```ruby
  flutter_inappwebview: 
   git:
    url: https://github.com/pichillilorenzo/flutter_inappwebview.git
    ref: eaad17eb4fa8f3f3c575127a27c39b0a54abba8b
`

**Comment by RohithKilaparthi** [comment]
@rahuldange09 When would you be publishing the new version of the package.

**Comment by pichillilorenzo** [comment]
new version 5.0.0 published with android-specific option `useHybridComposition`!
