### ISSUE TITLE
Not able to use ChromeSafariBrowser Page Navigation Event

### ISSUE THREAD

**Issue by runaliA** [pichillilorenzo/flutter_inappwebview#485]
Hi,

I am not able to use Page Navigation Events for ChromeSafari Browser As 
I know that for the fallback class (InAppBrowser) I have these kind of events, but no for the ChromeSafariBrowser implementation, I don't have any callbacks for the navigation events. 

Thank you very much.Please any Suggestions and help for this is acceptable?

**Comment by pavooo** [comment]
I would need this feature as well, something like a `NavigationDelegate`. 
Did you find any solution for the ChromeSafariBrowser?

**Comment by renanmgs** [comment]
up
