### ISSUE TITLE
black screen with android 10 and FLAG_SECURE

### ISSUE THREAD

**Issue by Joseph-Nathan** [pichillilorenzo/flutter_inappwebview#486]
webView show as black screen with FLAG_SECURE in all device not support Chrome as Android system WebView Provider 

in android 10 ,
and Huawei modern devices ,
can you supply any code to pass this issues

**Comment by prashantspandey** [comment]
Any solution to this one? Please help as this is a big issue.

**Comment by DowsingUK** [comment]
Same here

**Comment by zakimuhammad** [comment]
any solution?

**Comment by ahmadkhedr** [comment]
any solution?

**Comment by Deanwfy** [comment]
Same Here.
And #534
