### ISSUE TITLE
camera picker crash

### ISSUE THREAD

**Issue by kkn1380** [pichillilorenzo/flutter_inappwebview#487]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   1.17.3         |
| Plugin version       |    4.0.0       |
| Android version      |   10   |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
no error
**Current behavior:** 
crash

## Steps to reproduce
I use 2-3 webViews with flutter_inappwebview in my application.
And when one webView takes a picture and tries to get a picture and takes a picture and goes back to the webView it crashes.
onActivityResult is called on an instance other than the one that called startActivityForResult and a crash occurs.
I think onActivityResult is called on first created instance. 
I don't think you can guarantee on which instance onActivityResult is called, so why not make the outputFileUri static?
private static Uri outputFileUri;

## Stacktrace/Logcat   
08-14 21:02:13.617 31228 31228 E AndroidRuntime: FATAL EXCEPTION: main 
08-14 21:02:13.617 31228 31228 E AndroidRuntime: Process: com.iconloop.zzeung, PID: 31228 
08-14 21:02:13.617 31228 31228 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.iconloop.zzeung/com.iconloop.zzeung.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null objec      t reference 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.ActivityThread.deliverResults(ActivityThread.java:5237) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5278) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:107) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:237) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:8016) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at re.onReceiveValue(chromium-TrichromeWebViewGoogle.aab-stable-1:6) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebViewChromeClient.onActivityResult(InAppWebViewChromeClient.java:822) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:206) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:127) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at io.flutter.app.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:137) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at com.iconloop.zzeung.MainActivity.onActivityResult(MainActivity.java:120) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.Activity.dispatchActivityResult(Activity.java:8294) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    at android.app.ActivityThread.deliverResults(ActivityThread.java:5230) 
08-14 21:02:13.617 31228 31228 E AndroidRuntime:    ... 11 more

**Comment by gfviegas** [comment]
I have this issue as well. Simple `<input type="file" capture/>` click and the app crashes.
