### ISSUE TITLE
Media notification not showing in webview..i am running site that show media notification on browser but in webview media notification not appear.

### ISSUE THREAD

**Issue by HetalGohil** [pichillilorenzo/flutter_inappwebview#493]

**Comment by pichillilorenzo** [comment]
Media notification API is not available on Android WebView. See:
- https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API
- https://stackoverflow.com/a/61524847/4637638
- https://developer.mozilla.org/en-US/docs/Web/API/Navigator#Browser_compatibility (`mediaSession` is not supported)
