### ISSUE TITLE
iOS Disabling useShouldInterceptAjaxRequest via controller.setOptions does not affect 

### ISSUE THREAD

**Issue by ariefap** [pichillilorenzo/flutter_inappwebview#495]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       1.21.0-9.1.pre        |
| Plugin version       |       4.0.0+4        |
| Android version      |       n/a        |
| iOS version          |       iOS-13-3        |
| Xcode version        |        11.3.1       |

Device information: iPhone 11 Pro Max

## Description

I'm not able to disable ajax interceptor when re-setting up controller. I have initial setting with `useShouldInterceptAjaxRequest: true,`, its running as expected, then I reset the controller to disable it programmatically (I reset the controller with option `useShouldInterceptAjaxRequest: false,`), it did not affect.

**Expected behavior:** Ajax interceptor is disabled

**Current behavior:** Ajax interceptor still running

## Steps to reproduce

1. Create initial configuration with `useShouldInterceptAjaxRequest: true`
2. Change the controller config from onUpdateVisitedHistory with `useShouldInterceptAjaxRequest: false`

**Comment by Manuito83** [comment]
I'm encountering the same problem. Works for Android.
