### ISSUE TITLE
Very Low Performance

### ISSUE THREAD

**Issue by varunkumarmedam** [pichillilorenzo/flutter_inappwebview#496]
This plugin performs really bad when compared with flutter_webview_plugin. But flutter_webview_plugin doesn't store cookies this makes me choose other plugins. Please compare the performance of both plugins and try to improve this plugin performance too

**Comment by StepanMynarik** [comment]
Same problem here. Scrolling feels sluggish.
Both on lower and higher end devices :(

**Comment by varunkumarmedam** [comment]
_From the Author,_
The performance problem is not related to the plugin itself, but on how Flutter manages/renders native widgets. My plugin just uses the native WebView widget that Android and iOS offer.
With the next release (v5.0.0) of the plugin, you will be able to enable Android Hybrid Composition which will improve a lot the performance (Flutter version needs to be 1.20+), but there are some performance drawbacks on < Android 10  (see official flutter wiki page here: https://github.com/flutter/flutter/wiki/Hybrid-Composition#performance).
Keyboard problems will be solved very soon.

**Comment by StepanMynarik** [comment]
Lovely news! Thanks for letting me know!

**Comment by mjablecnik** [comment]
@pichillilorenzo And when will be released v5.0.0 version of this plugin?
