### ISSUE TITLE
Not able to get parameter from URL after success, Browser works  

### ISSUE THREAD

**Issue by pmrajani** [pichillilorenzo/flutter_inappwebview#497]
How can i read paymentResult from url

![Annotation 2020-08-24 135444](https://user-images.githubusercontent.com/4957175/91021458-73366a80-e611-11ea-859b-4c46442b787a.jpg)

i set onLoadStart and onLoadStop to check URL but webview is not trigger that method while url is like this.
**How can i achieve this?**

NOTE, if i try on mobile browser it's showing in url.

**Comment by pichillilorenzo** [comment]
Have you tried using the `shouldOverrideUrlLoading` event?
You need to enable the `InAppWebViewOptions` option `useShouldOverrideUrlLoading: true` and then check the URL:

```dart
shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
  var url = shouldOverrideUrlLoadingRequest.url;
  var uri = Uri.parse(url);

  print(uri);

  return ShouldOverrideUrlLoadingAction.ALLOW;
},
```
