### ISSUE TITLE
InAppWebView is getting scaled

### ISSUE THREAD

**Issue by ariona** [pichillilorenzo/flutter_inappwebview#498]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 1.20.2 |
| Plugin version       | 4.0.0+4|
| Android version      | 10 |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Device name: Pocophone F1
MIUI Version: MIUI Global 11.0.9

## Description

**Expected behavior:** 
InAppWebview has fullwidth and height, not scaled down.

**Current behavior:** 
InAppWebview is getting scaled down but the touch area of the webview is in right size.

## Steps to reproduce

I just using example code from https://github.com/pichillilorenzo/flutter_inappwebview#inappwebview-class

## Images   
![WhatsApp Image 2020-08-27 at 11 02 47](https://user-images.githubusercontent.com/752483/91382873-eb40a280-e854-11ea-856b-34d886a54324.jpeg)

## Stacktrace/Logcat   
```
I/flutter (12701): [GETX] GOING TO ROUTE /Webview
D/EgretLoader(12701): EgretLoader(Context context)
D/EgretLoader(12701): The context is not activity
W/ContentCatcher(12701): Failed to notify a WebView
E/InputMethodManager(12701): b/117267690: Failed to get fallback IMM with expected displayId=41 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{2c4f526 VFEDHVCL. .F...... 0,0-1080,2003}
```

**Comment by pichillilorenzo** [comment]
I cannot reproduce your error. It could be a bug related to how Flutter manages native widgets (platform views).

**Comment by ariona** [comment]
I think it's related to the android version of MIUI i am using. I tested on emulator, on other MIUI devices and other seem to be working properly, no scale issue.
