### ISSUE TITLE
Frame drop is severe when scrolling

### ISSUE THREAD

**Issue by violet-dev** [pichillilorenzo/flutter_inappwebview#499]
This is my full source code.
It is an app that only uses the `flutter_inappwebview`.

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: InAppWebView(
      initialUrl:
          'http://web.humoruniv.com/board/humor/read.html?table=pds&pg=0&number=991460',
    ));
  }
}
```

I've tried two difference webviews, but the one with the best performance doesn't match the flutter ui, and the other one have very bad performance. This is also slow in performance.
How can I fix it?
I can't find a way to improve the scrolling performance in anywhere.

**Comment by tneotia** [comment]
Once the 5.0.0 update releases for this plugin, please set 
```
initialOptions: InAppWebViewGroupOptions(
    android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
     )
 ),
```
inside the InAppWebView constructor.

**Comment by violet-dev** [comment]
Thank you! I encountered a little ui problem, but it is very nice to use!

**Comment by kustraslawomir** [comment]
When can we expect the next version? Thank you
@tneotia

**Comment by tneotia** [comment]
> When can we expect the next version? Thank you

Don't know... this is a question for @pichillilorenzo 
If you need this now you can use this in `pubspec.yaml`:
```
flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
```
Just beware if you have native animations on webView page and running Android <10, there will be some lag even though webView is buttery smooth. That's a Flutter issue.

**Comment by markosole** [comment]
> Once the 5.0.0 update releases for this plugin, please set
> 
> ```
> initialOptions: InAppWebViewGroupOptions(
>     android: AndroidInAppWebViewOptions(
>         useHybridComposition: true,
>      )
>  ),
> ```
> 
> inside the InAppWebView constructor.

You have saved my day, thank you!
