### ISSUE TITLE
When I focus on a Input Text, the keyboard appears in front of Input Text

### ISSUE THREAD

**Issue by brnyza** [pichillilorenzo/flutter_inappwebview#500]
The error is similar to this, but in webview:
https://stackoverflow.com/questions/53586892/flutter-textformfield-hidden-by-keyboard

Could you help me please?

*flutter_inappwebview: ^4.0.0+4
*Flutter 1.20.2

**Comment by neuos** [comment]
I have the same problem. Is there any update or workaround to auto scroll the input field into view?

**Comment by gc986** [comment]
It helped me https://stackoverflow.com/a/53605734

**Comment by pichillilorenzo** [comment]
Also, try the latest version `5.0.5+3` and use the Android-specific webview option: `useHybridComposition: true`.
