### ISSUE TITLE
Support native android

### ISSUE THREAD

**Issue by James4Deutschland** [pichillilorenzo/flutter_inappwebview#501]
headless inappwebview  and browser do not support android service. please consider rewrite this module to support native android with background service and workmanager to do web scraping.

**Comment by pichillilorenzo** [comment]
You can already use the headless inappwebview to do web scraping. Just create and run an instance of a `HeadlessInAppWebView` class in your code wherever you want (`HeadlessInAppWebView` is not a widget!) and use the webview controller to control it, such as to execute `evaluateJavascript`method, etc.
