### ISSUE TITLE
Webdriver (automate web pages)

### ISSUE THREAD

**Issue by FRsyesCD** [pichillilorenzo/flutter_inappwebview#503]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 
Hi Lorenzo Pichilli 
Thanks for your awesome plugin first 
I just wanna ask you when your gonna make a webdriver for it or is it there already or is it possible at least.
Because evaluate javascript is executing javascript on low level so i can't access a video inside an iframe, is there a way to do that ?!
**Alternatives you've considered:**   

**Images:**

**Comment by vioao** [comment]
Got the same problem too.
