### ISSUE TITLE
Failed to Play YouTube Video in iOS

### ISSUE THREAD

**Issue by Kimhak-Loem** [pichillilorenzo/flutter_inappwebview#504]
I'm trying to play YouTube Video that embedded  in html in iOS. Example a video in this link: https://developers.google.com/youtube/youtube_player_demo. The YouTube video display perfectly, but when I play the video I got this message on the video "Your browser does not currently recognize any of the video formats available. Click here to visit our frequently asked question about HTML5 video". 

In android it works fine, only in iOS it doesn't work. 

```
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

class WebviewDisplay extends StatefulWidget {
  @override
  _WebviewDisplayState createState() => _WebviewDisplayState();
}

class _WebviewDisplayState extends State<WebviewDisplay> {
  InAppWebViewController webview;
  
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: Container(
        child: InAppWebView(
          initialUrl: "https://developers.google.com/youtube/youtube_player_demo",
          initialHeaders: {},
          initialOptions: InAppWebViewGroupOptions(crossPlatform: InAppWebViewOptions(debuggingEnabled: true)),
          onWebViewCreated: (InAppWebViewController controller) {
            webview = controller;
          },
          onLoadStart: (InAppWebViewController controller, String url) {},
          onLoadStop: (InAppWebViewController controller, String url) async {},
          onProgressChanged: (InAppWebViewController controller, int progress) {},
        ),
      ),
    );
  }
}
```

**Comment by delay** [comment]
I tested the demo and it works fine for me on an ios device. Did you make sure you enabled all the recommended options in info.plist.  My guess is this one is missing. NSAllowsArbitraryLoadsInWebContent

**Comment by Kimhak-Loem** [comment]
It works now. Adding to above, the problem because of I set the user-agent. In case someone also face the problem like me, here is the user-agent that I set:

```userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36```

Anyway, thank you @delay for your support.
