### ISSUE TITLE
Issue in Flutter web: "Unsupported operation: Platform._operatingSystem"

### ISSUE THREAD

**Issue by SebastienBtr** [pichillilorenzo/flutter_inappwebview#507]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         1.21.0-9.1.pre      |
| Plugin version       |       ^4.0.0+4        |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

Ussing flutter run -d chrome

## Description

**Expected behavior:** 

The plugin should work on web

**Current behavior:** 

An exception is thrown: Unsupported operation: Platform._operatingSystem

See the related flutter issue: https://github.com/flutter/flutter/issues/36126

## Steps to reproduce

1. Add inAppWebView in a statefull widget
2. Run with: flutter run -d chrome
3. See exception

**Comment by pichillilorenzo** [comment]
The fix about this error will be available in the next version 5.0.0. However, `flutter_inappwebview` doesn't support Flutter Web and will not work on the Web.
