### ISSUE TITLE
[!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (xxxlib.a andxxb.a)

### ISSUE THREAD

**Issue by pandakingli** [pichillilorenzo/flutter_inappwebview#51]
i use flutter_inappbrowser and flutter_wechat,in podfile i use use_frameworks!

when i pod install,come with this error 
`[!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (xxxlib.a andxxb.a)`

**Comment by biubiublue** [comment]
does anyone have any idea about this?

**Comment by peanut-flutter** [comment]
Oh my gosh @biubiublue, same exact nightmare but with a different library! I raised an issue here:

https://github.com/aloisdeniel/flutter_plugin_appcenter/issues/3

In case you haven't, try removing or commenting `use_frameworks!` in your `ios\Podfile`! If you're the same as me this will make your `flutter_wechat` work but `flutter_inappbrowser` will break.

Also people are reporting similar here:
https://github.com/flutter/flutter/issues/9694#issuecomment-459071953

Let me know if you find anything please! @pichillilorenzo do you have any thoughts on this? Thanks so much.
