### ISSUE TITLE
Button click is propagated through Flutter button to Webview (only on iOS)

### ISSUE THREAD

**Issue by LukasP94** [pichillilorenzo/flutter_inappwebview#515]
Hi, 

I have a very strange bug. If I click on some floating button on map (WebView) click is somehow propagated to WebView and there is called Javascript on Map. And also on JS side is called only "pointerDown", "pointerUp" is never called (I have to reset whole WebView).

![ezgif com-gif-maker](https://user-images.githubusercontent.com/66218871/92591274-e391ec80-f29d-11ea-80d2-3f175b7a1275.gif)
 

- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   1.20.1 • channel stable |
| Plugin version       |   4.0.0+4  |
| iOS version          |  13.7 |
| Xcode version        | Version 11.7 (11E801a) |

Device information: 

## Description

**Expected behavior:** 
Flutter Button is clicked and map (Webviev) is not triggered
**Current behavior:** 
Flutter button propagate click to webview and pointer is freezed.

I am fighting with this issue over one month.
Thank you for any help!

**Comment by JohnnyNguyen01** [comment]
We're running into this issue as well, has there been a fix or a find on what was causing this?
@LukasP94  

We experienced it on 5.3.2
