### ISSUE TITLE
getting this error while adding this plugin in my flutter project kindly help

### ISSUE THREAD

**Issue by ganeshkgp** [pichillilorenzo/flutter_inappwebview#516]
The plugin `flutter_inappwebview` doesn't have a main class defined in C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-4.0.0+4\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\InAppWebViewFlutterPlugin.java or C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-4.0.0+4\android\src\main\kotlin\com\pichillilorenzo\flutter_inappwebview\InAppWebViewFlutterPlugin.kt. This is likely to due to an incorrect `androidPackage: com.pichillilorenzo.flutter_inappwebview` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 
exit code 1

**Comment by ganeshr848** [comment]
I am using flutter version 1.20.3 latest stable verison

**Comment by ganeshr848** [comment]
I upgradeed it using flutter upgrade
