### ISSUE TITLE
How to use onReceivedHttpAuthRequest

### ISSUE THREAD

**Issue by namdroid** [pichillilorenzo/flutter_inappwebview#519]
## Description
I need to set username and password like this on Android.
```
  override fun onReceivedHttpAuthRequest(
      view: WebView?,
      handler: HttpAuthHandler?,
      host: String?,
      realm: String?
    ) {
      handler?.proceed("username", "password")
    }
```
How can i do this with inappwebview. Thanks

**Comment by pichillilorenzo** [comment]
As you can read in the documentation, you can use the `onReceivedHttpAuthRequest` webview event.

For example:
```dart
onReceivedHttpAuthRequest: (InAppWebViewController controller, HttpAuthChallenge challenge) async {
  return new HttpAuthResponse(
    username: "USERNAME",
    password: "PASSWORD",
    action: HttpAuthResponseAction.PROCEED,
    permanentPersistence: true);
},
```

**Comment by markusstoll** [comment]
Hi @pichillilorenzo 

I integrated flutter_inappwebview  for showing a webpage that needs HTTP Basic Authentication.

For iOS I succeeded using HttpAuthCredentialDatabase, but for Android I had to supply the Authentication in this onReceivedHttpAuthRequest response.
How should I have known this from the documentation? I do not get it

However thanks for the good work!
