### ISSUE TITLE
applicationNameForUserAgent is not work in ios

### ISSUE THREAD

**Issue by dashixiong91** [pichillilorenzo/flutter_inappwebview#525]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      1.20.2         |
| Plugin version       |        master branch eaad17eb4fa8f3f3c575127a27c39b0a54abba8b       |
| Android version      |      29         |
| iOS version          |      13.1         |
| Xcode version        |      11.1         |

Device information: 

## Description

**Expected behavior:** 
set applicationNameForUserAgent will be get with eval `navigator.userAgent`
**Current behavior:** 
navigator.userAgent is wkwebiew default userAgent
## Steps to reproduce

```
InAppWebView(
      initialUrl: widget.initialUrl,
      initialOptions: InAppWebViewGroupOptions(
          crossPlatform: InAppWebViewOptions(
              debuggingEnabled: true,
              applicationNameForUserAgent:
                  'myApp'),
          ios: IOSInAppWebViewOptions(
              allowsBackForwardNavigationGestures:
                  widget.iosGesturesNavigation)),
      onWebViewCreated: (InAppWebViewController controller) {
        _webviewController = controller;
      });
```

**Comment by EastLee** [comment]
I have the same problem
