### ISSUE TITLE
Debug console reports "Renderer process (11630) crash detected (code -1)."

### ISSUE THREAD

**Issue by ghowen** [pichillilorenzo/flutter_inappwebview#528]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       1.20.4        |
| Plugin version       |         4.0.0+4      |
| Android version      |       11        |
| iOS version          |        14       |
| Xcode version        |      12.0         |

Device information: Pixel 3a API 30 (android-x86 emulator)

## Description

I have a stateless widget with an app bar and a body container that contains an InAppWebView. I am loading a webpage into the webview from local assets using a InAppLocalhostServer. All works well, but on Android the debug console is reporting some strange errors:

The app bar contains a close-button that uses this code in the `onPressed`method:
```
              Navigator.popUntil(
                  context, (Route<dynamic> route) => route.isFirst);

```
When or right after popping, the debug console reports

```
V/InputMethodManager(12586): b/117267690: Failed to get fallback IMM with expected displayId=41 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{bf3be60 VFEDHVCL. ........ 0,0-1075,1863}
E/chromium(12586): [ERROR:aw_browser_terminator.cc(125)] Renderer process (12845) crash detected (code -1).

```
The same happens when pressing the "back" button in the app bar. No error messages whatsoever on iOS.

**Expected behavior:** 

No expectation but I wanted to report the crash of chromium.

**Current behavior:** 

See console reports.

**Comment by pichillilorenzo** [comment]
If it happens when you are disposing that widget, I think you can just ignore it.
For some reason, when I’m destroying the WebView voluntarily (because it has been disposed from the Flutter widget tree), it “throws” this error, but however it works.
However you can try the latest release.
