### ISSUE TITLE
WebView taking Gesture events that don't belong to it

### ISSUE THREAD

**Issue by Flucadetena** [pichillilorenzo/flutter_inappwebview#530]
- [YES] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [YES] I have already searched for the same problem
- [YES] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [YES] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version    | Flutter 1.20.4 |
| Plugin version       |^4.0.0+4|
| Android version     |  23 - 29|
| iOS version          |     9.0 or higher          |
| Xcode version        |       11.7        |

Device information:  IOS Emulator Iphone 11 with 13.5 / Samsung Note 8 - latest stable android version

## Description

**Expected behavior:**  Not reacting to click/tap events

**Current behavior:** Takes click/tap events that don't belong to it

My problem is that I have a bunch of widgets on top of the webview, inside of a “Stack” widget. When I tap on the widget right above the webView, the Webview recives the click too. I have a GestureDetector on top of my widgets to claim Focus, but it doesn’t seam to stop the “tap” from passing through. The structure is this:

```
Scaffold (
 body: Stack(
  children:[
     WebView
     SlidingUpPanel(
        child: GestureDetector(
            onTap: () => FocusScope.of(context).unfocus(),
            child: Container(),
       ),),
  ]),
)
```

Thanks a lot in Advance!

After a lot of investigation I'm suspecting that the webs where this happens are capturing the click event and acting on it even when it is not supposed to. For example if you do this on "Google.com", when you click on top of the searchBar it will act as if you clicked the searchBar. This happens also in some webs that I know do some things like this, like "Zara.es"

Could this be the problem? Is there a way to stop it?

**Comment by Lemonreds** [comment]
the same, any solution?
