### ISSUE TITLE
Android Q, Appears black screen when keyboard pops up on webview

### ISSUE THREAD

**Issue by prabhu73** [pichillilorenzo/flutter_inappwebview#536]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        Channel beta, 1.22.0-12.1.pre       |
| Plugin version       |               |
| Android version      |      29.03         |
| iOS version          |               |
| Xcode version        |      11.5         |

Device information: 

## Description

**Expected behavior:** 
Should able to edit the text fields which are present in webview page

**Current behavior:** 
Unable to edit/enter text fields on webview pages and webview is not functioning properly.

## Steps to reproduce

1. Open android app which contains flutter pages also,
2. Than open an URL on flutter webview and try to edit/enter text on text filed which appears on webview page 
3. Then when keyboard pops up the complete screen turns to black color and unable to go back also.

## Images  
![Screenshot_1601023165](https://user-images.githubusercontent.com/22490455/94252139-23fd9580-ff41-11ea-92d3-13c4abf24fd5.png)
![Screenshot_1601023172](https://user-images.githubusercontent.com/22490455/94252153-2829b300-ff41-11ea-8162-3653436df817.png)
<img width="642" alt="Screenshot 2020-09-25 at 2 16 57 PM" src="https://user-images.githubusercontent.com/22490455/94252155-28c24980-ff41-11ea-868e-95202b492a6e.png">

## Stacktrace/Logcat 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] VS Code (version 1.47.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by pichillilorenzo** [comment]
Try the latest version `5.0.5+3` and use the Android-specific webview option: `useHybridComposition: true`.
