### ISSUE TITLE
On some devices, "flutterInAppWebViewPlatformReady" won't be fired.

### ISSUE THREAD

**Issue by cascopia** [pichillilorenzo/flutter_inappwebview#541]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    1.20.4           |
| Plugin version       |  4.0.0+4             |
| Android version      |   7.0      |
| iOS version          |               |
| Xcode version        |               |

Device information: Samsung Galaxy A5

## Description

**Expected behavior:** 

As I successfully added Javascript handler to the WebView, and the `window.addEventListener()` to the webpage, `window.addEventListener()` callback should be fired for the application to communicate through the Javascript handler.

**Current behavior:** 

The function, `window.addEventListener("flutterInAppWebViewPlatformReady", function (event) { console.log('done');  });` is not fired. Thus, 'finished' won't be printed out on the javascript console. Therefore, `window.flutter_inappwebview.callHandler `is not fired at all.

**Please note** that the html and dart code seems impeccable because this does work in other devices while it does not work on the device written above and another Galaxy device.

## Steps to reproduce

On the webpage (server-side),
the script has been inserted in various positions: middle of `<head>`, below `<body>`, just before `</body>`, and just after `</body>`.

```
window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
    console.log('added'); // never printed
    window.flutter_inappwebview.callHandler('handlerFoo', 'hello', 'world').then(function(result) {
        console.log('finished');
    });
});
```

On the dart (client),
```
onWebViewCreated: (InAppWebViewController controller) {
                          webView = controller;
                          webView.addJavaScriptHandler(handlerName: 'handlerFoo', callback: handlerFoo);
                        },
```
with setting of` javaScriptEnabled: true,`

```
Future<bool> handlerFoo(args) async {
// Never reached
print("${args[0]| ${args[1]}");

return Future<bool>.value(true);
}
```

Again, the weird behavior is that it works fine in some devices (Sony, LG and Samsung) while does not work on some others.

**Comment by pichillilorenzo** [comment]
It should be fixed with version 5+. Have you tried it?

**Comment by juliancesar** [comment]
I have the same issue in same conditions.

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.1
  intl: ^0.17.0
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.0-nullsafety.4
```

**Comment by juliancesar** [comment]
Make sense! I remove the listener of `flutterInAppWebViewPlatformReady` and works! Tks!

**Comment by pichillilorenzo** [comment]
You are welcome! 😄

**Comment by ShehabSherbiny** [comment]
Hello,
i am aware that this is an old issue, but i have been experiencing the same behaviour described in this thread.
The only difference is that it does not happen consistently.
What i mean by this, is that sometimes the event is fired and sometimes it is not; and i cannot figure out why it sometimes does not fire.
JS side:
` window.addEventListener("flutterInAppWebViewPlatformReady", function (event) {
        dib.server = getParameterByName("server");
        ...
        isFlutterInAppWebViewReady = true;
    });`

# environment:

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.8.0
  yaml_edit: ^2.1.1
  path_provider: ^2.0.15
  http: ^1.1.0
  device_info_plus: ^9.0.2
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_router: ^1.1.4
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_archive: ^5.0.0
  archive: ^3.3.7
  dio: ^5.3.0
  easy_localization: ^3.0.2
  country_flags: ^2.1.0
  mobile_scanner: ^3.3.0
  settings_ui: ^2.0.2
  apple_product_name: ^2.1.0
  shared_preferences: ^2.2.0
  equatable: ^2.0.5
  mockito: ^5.4.2
  http_mock_adapter: ^0.4.4
  integration_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.1
  info_popup: ^3.0.5
  connectivity_plus: ^4.0.2
  loader_overlay: ^2.3.2
  flutter_spinkit: ^5.2.0
`

**Comment by thanhnd10kn** [comment]
I have same issue with Flutter web.  `flutter_inappwebview: ^6.0.0-beta.22`
This is my HTML code:
````
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>
    $(function() {
        var isFlutterInAppWebViewReady = false;
        window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
            isFlutterInAppWebViewReady = true;
            console.log('isFlutterInAppWebViewReady');
        });
        $('.syncer-acdn-28').click(function() {
            console.log('syncer-acdn-28');
            console.log(isFlutterInAppWebViewReady);
            window.flutter_inappwebview.callHandler('cancel_subscriptions');
        })
    });
</script>
````
This is Dart side:
```
onWebViewCreated: (controller) async {
            controller.addJavaScriptHandler(
              handlerName: 'cancel_subscriptions',
              callback: (args) {
                //I want to get the args here but it is always an empty list
                logger.d('=>>>>>>>>>>>>>>>>>> kakak');
              },
            );
          },
```
Please help me. Thanks
