### ISSUE TITLE
Upgrade InAppWebView to 5.0 (Hybrid Composition-Android)

### ISSUE THREAD

**Issue by rahuldange09** [pichillilorenzo/flutter_inappwebview#544]
As Flutter v1.22 released on stable branch. 
Which made webview production ready as hybrid composition is added for android.
So I think it is right time to upgrade InAppWebView to 5.0.
So can you please merge changes into stable branch?

**Comment by rahuldange09** [comment]
Please upgrade it as soon as possible as this will fix so many pending issues.

**Comment by ycv005** [comment]
You can use it, check the following answer-

https://github.com/pichillilorenzo/flutter_inappwebview/issues/521#issuecomment-691066414

**Comment by rahuldange09** [comment]
@ycv005 I'm already using that (master). It's just I have no idea whether master is without bugs or not. So it's always better to have stable version and plus solves problem for everyone who faces it.

**Comment by ycv005** [comment]
Read this - https://github.com/flutter/flutter/issues/67863

**Comment by rahuldange09** [comment]
@pichillilorenzo Any updates on this?

**Comment by pichillilorenzo** [comment]
new version 5.0.0 published!
