### ISSUE TITLE
How do I listen to parent.postMessage(result, "*"); after onLoadStop?

### ISSUE THREAD

**Issue by yashwp** [pichillilorenzo/flutter_inappwebview#545]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have run the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       1.22        |
| Plugin version       |    4.0.0+4    |
| Android version      |      10       |
| iOS version          |        NA       |
| Xcode version        |      NA         |

Device information: 

## Description

I have a link(iframe link in terms of the web app) which emits various event on steps while interacting with it. I've to open this link into my Flutter mobile app in a Webview and listen to those messages.  

The link I'm including is our partner's widget(iframe/link that needs to be opened in Webview), their document says:
> The widget communicates messages to the parent by calling below javascript function. It is recommended to handle these messages and provide suitable transitions in the user interface.
`parent.postMessage(result, "*");` where `result["event"]` depicts the name of the event. Below are the type of events and data supplied in each case: `siteLinkWidgetCancelled`, `siteLinkWidgetAutoUpdateInitiated:`, etc.

Here is what I have implemented:
```
InAppWebView(
     initialUrl: widgetUrl,
     initialOptions: InAppWebViewGroupOptions(
          crossPlatform: InAppWebViewOptions(
              debuggingEnabled: true,
               javaScriptEnabled: true,
           ),
      ),
     onWebViewCreated: (InAppWebViewController webViewController) {
         _controller = webViewController;
         _controller.addJavaScriptHandler(
              handlerName: 'message',
              callback: (args) {
                  print('Message from webview $args'); 
               },
          );
      },
      onLoadStop: (InAppWebViewController ctrl, String url) {
          ctrl.evaluateJavascript(source: '''
              window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
                 window.flutter_inappwebview.callHandler('message').then(function(result) {
                     return result;
                 });
              });
         ''');
        },
    ),
```
**Expected behavior:** 
`print('Message from webview $args'); ` Should have logged with the result of 'message' event.
I have also tried passing event listed above i.e. `siteLinkWidgetAutoUpdateInitiated`. 

**Current behavior:** 
But again no response there as well. No error messages

**Comment by ycv005** [comment]
Hey, evaluateJavascript return data back as Future<dynamic> (which is basically `the result of the evaluation.`). (Note- I am not developer of this plugin). With the below code, you might get a response that you needed. Try this-
```
      onLoadStop: (InAppWebViewController ctrl, String url) async {
          final resultGot = await ctrl.evaluateJavascript(source: '''
              window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
                 window.flutter_inappwebview.callHandler('message').then(function(result) {
                     return result;
                 });
              });
         ''');
        print("here is the result- $resultGot");
        },
```

**Comment by ycv005** [comment]
Hey, evaluateJavascript return data back as Future<dynamic> (which is basically `the result of the evaluation.`). (Note- I am not developer of this plugin). With the below code, you might get a response that you needed. Try this-
```
      onLoadStop: (InAppWebViewController ctrl, String url) async {
          final resultGot = await ctrl.evaluateJavascript(source: '''
              window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
                 window.flutter_inappwebview.callHandler('message').then(function(result) {
                     return result;
                 });
              });
         ''');
        print("here is the result- $resultGot");
        },
```

**Comment by yashwp** [comment]
Nope. Not working.

**Comment by krishnakumarcn** [comment]
Any updates on this issue? @ycv005

**Comment by ycv005** [comment]
I am not the developer.

**Comment by lukicenturi** [comment]
> callHandler

replace `callHandler` with `_callHandler`

**Comment by pichillilorenzo** [comment]
registering `flutterInAppWebViewPlatformReady` on `onLoadStop` event doesn't make any sense.
Using your code that way, the `flutterInAppWebViewPlatformReady` won't be fire because, well, it has been already fired.
On the `onLoadStop` event, you don't need to listen to the `flutterInAppWebViewPlatformReady` javascript event.
Instead, you can just use `window.flutter_inappwebview.callHandler` because, at that time, the platform is already ready.

@lukicenturi And no, `_callHandler` is a sort of "private" API of the plugin that can change anytime.

With the latest version of the plugin, there is no need for some workarounds.

If you need to listen to post messages, you can simply use JavaScript as you would do normally (see [MDN - postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)).
For example:
```javascript
window.addEventListener("myCustomEventMessage", (event) => {
  if (event.origin !== "http://example.org:8080")
    return;
  
  const args = ['myValue1', 'myValue2'];
  window.flutter_inappwebview.callHandler('message', ...args);
}, false);
```
And on the Flutter side, in the `onWebViewCreated` event, you register every JavaScript handler you want to manage like you already did.

Also, the `.then()` javascript part is useful for you if your Flutter JavaScript handler returns something (in your case you are not returning anything), otherwise the `result` variable will be `undefined`.

**Comment by tazik561** [comment]
you can do something like that:

      onLoadStop: (controller, url) async {
                  // Inject JavaScript code to set up a listener for post messages

        await controller.evaluateJavascript(source: '''
            window.addEventListener('message', function(event) {
              if (event.data && event.data.status === 'OK') {
                var result = event.data.result;
                // Handle the result here in Flutter
                window.flutter_inappwebview.callHandler('onMessageReceived', result);
              }
            });
          ''');

  // Register a JavaScript handler to receive messages from the WebView
        controller.addJavaScriptHandler(
          handlerName: 'onMessageReceived',
          callback: (result) {
            print('Message received from JavaScript: $result');
            // Handle the result from JavaScript here
          },
        );
      },
