### ISSUE TITLE
initialOptions not working InAppWebView 4.0.0+

### ISSUE THREAD

**Issue by IZZsER** [pichillilorenzo/flutter_inappwebview#549]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md) yes
- [x] I have already searched for the same problem yes
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS] yes (https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        1.20.3       |
| Plugin version       |     4.0.0+          |
| Android version      |      4.0         |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
 I am stuck on this for last few days. I have worked around in the following ways:

1. I tried using git link in dependencies in .ymal file but it did not exeute at all.
2. i tried a fixed versions 3.1.0,3.0.0,4.0.0+ the basic InAppWebview works fine but when i put initialOptions it doesnt load and give the error 
     Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference, null)
E/flutter ( 7372): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter ( 7372): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter ( 7372): <asynchronous suspension>
E/flutter ( 7372): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 7372): #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
E/flutter ( 7372): #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:746:11)
E/flutter ( 7372): #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1017:34)
E/flutter ( 7372): #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1001:14)
E/flutter ( 7372): #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:176:29)
E/flutter ( 7372): #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:157:5)
E/flutter ( 7372): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1748:9)
E/flutter ( 7372): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #12     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:396:13)
E/flutter ( 7372): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
E/flutter ( 7372): #15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:495:7)
E/flutter ( 7372): #16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
E/flutter ( 7372): #17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
E/flutter ( 7372): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
E/flutter ( 7372): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #38     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3226:14)
E/flutter ( 7372): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
E/flutter ( 7372): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
E/flutter ( 7372): #41     RenderObject.layout (package:flutter/src/rendering/object.dart

==============

3. i downloaded your sourcecode and local InAppWebView works fine with my camera application . I want to know why initialOptions are not working in your lates 4.0.0+ that you uploaded on July. please give the working online version. as it is dfficult to integrate in big applications already written using default plugins.
**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by IZZsER** [comment]
No field initialScale in class Lcom/pichillilorenzo/flutter_inappbrowser/InAppWebView/InAppWebViewOptions; (declaration of 'com.pichillilorenzo.flutter_inappbrowser.InAppWebView.InAppWebViewOptions' appears in /data/app/com.example.flutter_cwe_final-x3rvBhEQjmbkzE6WiC0dzg==/base.apk!classes17.dex)


also see this please

**Comment by getgizmo** [comment]
I have this issue as well
