### ISSUE TITLE
Not able to upload a file.

### ISSUE THREAD

**Issue by Sunsiha** [pichillilorenzo/flutter_inappwebview#555]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       1.17.5        |
| Plugin version       |       4.0.0+4        |
| Android version      |      10         |
| iOS version          |        NA       |
| Xcode version        |          NA     |

Device information: 

## Description

Am trying to upload a file in my webview. It's working fine in iOS. It's not working in Android device. When I click on **Choose file** button first time it will open gallery and I can select an Image but it won't display in my view. Again if I click on **Choose file** button it won't open gallery itself. And am not getting any error or crash. The following code snippet you can use for reference. I tried the following link [duplicate](https://github.com/pichillilorenzo/flutter_inappwebview/issues/413)) But it doesn't work. Let me know where am doing mistake.
```
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:permission_handler/permission_handler.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await  PermissionHandler().requestPermissions(<PermissionGroup>[
    PermissionGroup.storage,
    PermissionGroup.camera,
    PermissionGroup.photos
  ]);
  runApp(new FAQsWebView());
}

var isFeedBackTouched;

class FAQsWebView extends StatefulWidget {
  @override
  FAQsWebViewState createState() => FAQsWebViewState();
}

class FAQsWebViewState extends State<FAQsWebView> {
  final GlobalKey previewContainer = new GlobalKey();
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();
  InAppWebViewController webView;
  int _page = 1;
  String initialUrl = 'https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file';

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    isFeedBackTouched = true;
  }

// ADD THIS LINE
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(accentColor: Colors.black),
        home: RepaintBoundary(
            key: previewContainer,
            child: Scaffold(
              resizeToAvoidBottomPadding: false,
              floatingActionButtonLocation:
                  FloatingActionButtonLocation.endFloat,
              key: _scaffoldKey,
              appBar: AppBar(
                brightness: Platform.isIOS ? Brightness.light : Brightness.dark,
                leading: IconButton(
                    icon: backImageStyle,
                    onPressed: () {
                      Navigator.pop(context);
                    }),
                backgroundColor: MoonlyteColors.actionBarColor,
                centerTitle: false,
                title: Text(
                  "File Upload",
                  style: appBarTextStyleEd,
                ),
              ),
              body: IndexedStack(
                index: _page,
                children: <Widget>[
                  InAppWebView(
                    initialUrl: initialUrl,
                    initialHeaders: {},
                    initialOptions: InAppWebViewGroupOptions(
                      crossPlatform: InAppWebViewOptions(
                        debuggingEnabled: true,
                        javaScriptEnabled: true,
                        javaScriptCanOpenWindowsAutomatically: true,
                        useOnDownloadStart: true,
                      ),
                      ios: IOSInAppWebViewOptions(),
                      android: AndroidInAppWebViewOptions(
                          domStorageEnabled: true,
                          databaseEnabled: true,
                          clearSessionCache: true,
                          thirdPartyCookiesEnabled: true,
                          allowUniversalAccessFromFileURLs: true,
                          allowFileAccess: true,
                          allowContentAccess: true),
                    ),
                    onWebViewCreated: (InAppWebViewController controller) {
                      webView = controller;
                    },

                    onLoadStop:
                        (InAppWebViewController controller, String url) {
                      setState(() {
                        _page = 0;
                      });
                    },
                  ),
                  Container(
                    child: const Center(
                      child: CircularProgressIndicator(),
                    ),
                  ),
                ],
              ),
            )));
  }
}
```
Using the version of  `flutter_inappwebview: ^4.0.0+4`.

Added the following code in AndroidManifest file,

```
 <provider
            android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
            android:authorities="com.abc.sample.flutter_inappwebview.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
```

provider_paths.xml

```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="external-path"
        path="."/>
    <external-cache-path
        name="external-cache-path"
        path="."/>
    <external-files-path
        name="external-files-path"
        path="."/>
    <files-path
        name="files_path"
        path="."/>
    <cache-path
        name="cache-path"
        path="."/>
    <root-path
        name="name"
        path="."/>
</paths>
```

**Expected behavior:** 
Able to choose a file from the gallery.
**Current behavior:** 

When I click on **Choose file** button first time it will open gallery and I can select an Image but it won't display in my view. Again if I click on **Choose file** button it won't open gallery itself. And am not getting any error or crash.

## Steps to reproduce
1. Copy the snippet of code.
2. Run the application and click on choose a file button. It will open a gallery, select a file.
3. You won't get any file.
4. Click again on choose file button. It won't open a gallery itself.  

1. This
2. Than that
3. Then

**Comment by msarkrish** [comment]
I tried your code, It's working fine for me.  
In AndroidManifest file replace authorities line by this line inside provider tag.

    android:authorities="${applicationId}.flutter_inappwebview.fileprovider"

**Comment by Sunsiha** [comment]
> I tried your code, It's working fine for me.
> In AndroidManifest file replace authorities line by this line inside provider tag.
> 
> ```
> android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
> ```
Hi @msarkrish I have tried like that also..it's not working for me...

**Comment by msarkrish** [comment]
@Sunsiha I created new flutter project and added your code, it works fine. I try to upload files many time, it works correctly everytime.
I created new Flutter Project and added flutter_inappwebview plugin in pubspec.yaml file

    flutter_inappwebview: ^4.0.0+4

I modified App minimum SDK to 17
Added this Provider tag inside manifest file

                 <provider
                       android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
                       android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
                       android:exported="false"
                       android:grantUriPermissions="true">
                       <meta-data
                            android:name="android.support.FILE_PROVIDER_PATHS"
                            android:resource="@xml/provider_paths" />
                  </provider>


See my screenshot it app shows selected file.

![Screenshot_2020-10-15-15-58-24-061_com example flutter_abstraction_example](https://user-images.githubusercontent.com/45334931/96112205-e8cb0280-0eff-11eb-910f-6a9b96ac351c.jpg)

**Comment by Sunsiha** [comment]
which version of flutter and device @msarkrish

**Comment by msarkrish** [comment]
@Sunsiha I'm using Flutter 1.22.1 and My Device is Redmi Note 4(Nougat)

**Comment by Sunsiha** [comment]
> @Sunsiha I'm using Flutter 1.22.1 and My Device is Redmi Note 4(Nougat)

@msarkrish  I really don't understand then why it is not working for me..just now I upgraded my flutter version also. 
`Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (5 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
`

**Comment by Sunsiha** [comment]
Hi,
Finally I got a solution.

In manifest file added the following,
`  <meta-data
            android:name="flutterEmbedding"
            android:value="2" />`

And in MainActivity.kt changed into the following,

````
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
````

**Comment by yfming93** [comment]
> @Sunsiha I created new flutter project and added your code, it works fine. I try to upload files many time, it works correctly everytime.
> I created new Flutter Project and added flutter_inappwebview plugin in pubspec.yaml file
> 
> ```
> flutter_inappwebview: ^4.0.0+4
> ```
> 
> I modified App minimum SDK to 17
> Added this Provider tag inside manifest file
> 
> ```
>              <provider
>                    android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
>                    android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
>                    android:exported="false"
>                    android:grantUriPermissions="true">
>                    <meta-data
>                         android:name="android.support.FILE_PROVIDER_PATHS"
>                         android:resource="@xml/provider_paths" />
>               </provider>
> ```
> 
> See my screenshot it app shows selected file.
> 
> ![Screenshot_2020-10-15-15-58-24-061_com example flutter_abstraction_example](https://user-images.githubusercontent.com/45334931/96112205-e8cb0280-0eff-11eb-910f-6a9b96ac351c.jpg)

It`s work well for me

**Comment by ArvindMewada** [comment]
android:resource="@xml/provider_paths" 
Please give me this file location i set the res folder inside create a file xml then set provider_paths it's wrong ? 
@yfming93

**Comment by jaroslawdabrowski** [comment]
Important note here about Redmi Phones. I am using Redmi Note 11 to debug my app. To do wireless debugging I had to disable MIUI optimalizations. This is causing some issues, e.g. the file picker opens but when you choose a file, nothing happens. I realised that this is not an issue of my app after I have tried to choose file in chrome and same issue happened. After enabling MIUI optimiazation file selection works fine.

**Comment by xfy6238** [comment]
> Important note here about Redmi Phones. I am using Redmi Note 11 to debug my app. To do wireless debugging I had to disable MIUI optimalizations. This is causing some issues, e.g. the file picker opens but when you choose a file, nothing happens. I realised that this is not an issue of my app after I have tried to choose file in chrome and same issue happened. After enabling MIUI optimiazation file selection works fine.


Just like you; Redmi Note  Android 10； After enabling MIUI optimiazation file selection works fine. But note only this package,  I use this flutter_webview_pro ，This is also the situation. so I think this is not the problem of plug -in；

**Comment by anandStratBeans** [comment]
InAppWebview after select file not it's not transfer on server.

**Comment by FatihBaycu** [comment]
https://stackoverflow.com/a/71968030/16504129
This worked for me. I used the code as is, I did not make any changes.

I have used [flutter_inappwebveiew](https://pub.dev/packages/flutter_inappwebview)

Make sure you have added permission for Uploads.

<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.VIDEO_CAPTURE" />
<uses-permission android:name="android.permission.AUDIO_CAPTURE" />
In Manifest

 <provider
        android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
        android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/provider_paths" />
    </provider>
