### ISSUE TITLE
forgotten "print" is crashing iOS builds

### ISSUE THREAD

**Issue by phackwer** [pichillilorenzo/flutter_inappwebview#556]
The following error started showing up when building locally as we were investigating out pipelines crashes from this Monday, 12th of October.

    Command CompileSwift failed with a nonzero exit code
    /Users/phackwer/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: warning: coercion of implicitly unwrappable value of type 'InAppWebView_IBWrapper?' to
    'Any' does not unwrap optional
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
    /Users/phackwer/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:26:19: note: implicitly unwrapped property 'containerWebView' declared here
        @IBOutlet var containerWebView: InAppWebView_IBWrapper!
                      ^
    /Users/phackwer/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: note: provide a default value to avoid this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                       ?? <#default value#>
    /Users/phackwer/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: note: force-unwrap the value to avoid this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                      !
    /Users/phackwer/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: note: explicitly cast to 'Any' with 'as Any' to silence this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                       as Any

**Comment by abdullah-almasry** [comment]
i have this error

**Comment by dhara6894** [comment]
I am also facing this same error.

**Comment by Gperez88** [comment]
have  same error after set 
```
     initialOptions: InAppWebViewGroupOptions(
                crossPlatform: InAppWebViewOptions(
                  useOnDownloadStart: true,
                ),
              ),
```
