### ISSUE TITLE
Typing Korean won't properly work in the InAppWebview input text field.

### ISSUE THREAD

**Issue by cascopia** [pichillilorenzo/flutter_inappwebview#560]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     1.22          |
| Plugin version       |  4.0.0+4              |
| Android version      |   5,7,9,10            |
| iOS version          |               |
| Xcode version        |               |

Device information: 
*not working devices*
Samsung Galaxy S5 Android 7
Samsung Galaxy S8 Android 9
Samsung Galaxy S10 Android 10

*working devices*
Samsung Galaxy S9 Android 10
LG Optimus G Pro Android 5
Sony Xperia Android 9

## Description

**Expected behavior:** 
Korean characters should be typed properly without 'breaking' consonants and vowels.

**Current behavior:** 
The first character itself is broken into subcharacters as consonants and vowels.
For example, (Flutter)플러터 -> ㅍㅡㄹ러터. 하이 -> ㅎㅏ이. 이 -> ㅇㅣ

(Official webview_flutter and native WebView for Android Java are working fine. Of course, flutter InputTextField works fine too.)

## Steps to reproduce

When there is *Input* tags on websites, a software keyboard will popup to wait for the user's interaction.
At this very moment, when the user tries to type any 'first' Korean character always be broken into consonants and vowels.
After hiding and re-showing the keyboard by tapping the input text field, then, the problem no longer exists.

It might be due to Samsung keyboard in Samsung Galaxy series devices. In official Flutter GitHub, those low level 'bugs' related to Samsung keyboard had been widely reported and discussed, finally solved recently.

There is no special modification. The only 'InAppWebview'-implemented simple app also reproduces the same problem as in the screenshot.

## Images   

![1](https://user-images.githubusercontent.com/41274307/96001037-90015880-0e72-11eb-9340-14090ec150e1.jpeg)
![2](https://user-images.githubusercontent.com/41274307/96001059-95f73980-0e72-11eb-8597-45621b44ae2e.jpeg)
![5](https://user-images.githubusercontent.com/41274307/96001063-968fd000-0e72-11eb-8047-ff39c335c3f4.jpeg)

## Stacktrace/Logcat   

There is no output at all while showing/hiding keyboard or typing text.

**Comment by plateaukao** [comment]
Hi, @inixryu 
You can try to use `useHybridComposition: true` in `AndroidInAppWebViewOptions`.

**Comment by inixryu** [comment]
> Hi, @inixryu
> You can try to use `useHybridComposition: true` in `AndroidInAppWebViewOptions`.

Couldn't find `useHybridComposition` parameter in `AndroidInAppWebViewOptions`. Is it available in 4.0.0+4?

If the newer one supports that thing, it would be great as in the official `webview_flutter`, setting `WebView.platform = SurfaceAndroidWebView();` makes those problems gone.

**Comment by wangxingxing123654** [comment]
> > 嗨，@inixryu
> > 你可以尝试使用`useHybridComposition: true`在`AndroidInAppWebViewOptions`。
> 
> `useHybridComposition`在中找不到参数`AndroidInAppWebViewOptions`。在4.0.0 + 4中可用吗？
> 
> 如果更新的人支持该功能，那将和官方一样好`webview_flutter`，设置`WebView.platform = SurfaceAndroidWebView();`可以解决这些问题。

has the same problem, useHybridComposition not defined

**Comment by inixryu** [comment]
> Hi, @inixryu
> You can try to use `useHybridComposition: true` in `AndroidInAppWebViewOptions`.

This approach seems to solve the issue, while the solution is only possible in the master version, not the stable released one.

**Comment by pichillilorenzo** [comment]
Fixed with version 5.0.0! Use the latest build with `useHybridComposition: true` the android-specific option!

**Comment by muhammadarslannasr** [comment]
I am facing this issue in textForm field korean text is getting space on each letter how can fix it in textformField?

@pichillilorenzo 

thanks
