### ISSUE TITLE
Cache "initialURL" for offlineview or PWA support

### ISSUE THREAD

**Issue by rebootcode** [pichillilorenzo/flutter_inappwebview#561]
## Environment

**Flutter version:** 1,20

## Description

**What you'd like to happen:** 
Is it possible to cache "intialURL" so that if there is no internet, InitialURL always opens the page from the local cache if the app has been opened at least once and the cache is not cleared.

Thanks

**Comment by rebootcode** [comment]
@pichillilorenzo - can progressive web app code be injected to cache initial URL and following URL, so that if the device is offline, App can still open all opened pages?

**Comment by rebootcode** [comment]
@pichillilorenzo - please share some insight

**Comment by easazade** [comment]
@rebootcode  this is very useful feature being able to load the page from disk when offline.
if your reading this issue you should also check [issue 366](https://github.com/pichillilorenzo/flutter_inappwebview/issues/366)

**Comment by ycv005** [comment]
@pichillilorenzo any update on this ? Caching inital url would be good.

**Comment by marcelomoresco** [comment]
any update?
