### ISSUE TITLE
How to use a proxy with webview? Is it possible?

### ISSUE THREAD

**Issue by purplecandy** [pichillilorenzo/flutter_inappwebview#564]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |           1.22    |
| Plugin version       |           any    |
| Android version      |          10     |
| iOS version          |               |
| Xcode version        |               |

Device information:

**Comment by cipchk** [comment]
Any procressing? @pichillilorenzo
