### ISSUE TITLE
There is the possibility of activating Third-party cookies on iOS?

### ISSUE THREAD

**Issue by davidEmutation** [pichillilorenzo/flutter_inappwebview#565]
There is the possibility of activating Third-party cookies on iOS?  And how could I do it?
In Android-specific options if you have it and it works correctly, but in iOS it does not work.

thirdPartyCookiesEnabled: Boolean value to enable third party cookies in the WebView.

**Comment by kamranbekirovyz** [comment]
would be nice to see that feature
