### ISSUE TITLE
The InAppWebView display empty

### ISSUE THREAD

**Issue by yhdjy025** [pichillilorenzo/flutter_inappwebview#57]
I've use the InAppWebView in my page,,the device show empty on the screen,but I the website is loaded from the log， I click the empty page,I can see the log that the website is jump to another url. and it load success.but the screen is display none too

My code is:

```dart
Widget _content(context) {
    return Container(
      width: 300,
      height: 500,
      child: InAppWebView(
          initialUrl: "https://baidu.com/",
          initialHeaders: {},
          initialOptions: {},
          onWebViewCreated: (InAppWebViewController controller) {
            webView = controller;
          },
          onLoadStart: (InAppWebViewController controller, String url) {
            print("started $url");
            setState(() {
              this.url = url;
            });
          },
          onProgressChanged: (InAppWebViewController controller, int progress) {
            print('---------progress ' + (progress / 100).toString());
            setState(() {
              this.progress = progress / 100;
            });
          }),
    );
  }
```

![企业微信截图_15523056336748](https://user-images.githubusercontent.com/11054900/54122564-5bc4eb00-4438-11e9-90fc-33bef5e6d102.png)

**Comment by yhdjy025** [comment]
I know the website has loaded, but it not show,   Please tell me how to solve it thanks!

**Comment by danielcosta27** [comment]
you can implement the `onLoadError` callback in order to see what's going on:

`              onLoadError: (InAppWebViewController controller, String url, int code, String message) {
                      print("url $url");
                      print("code $code");
                      print("message $message");
                },`

**Comment by pichillilorenzo** [comment]
@yhdjy025 I cannot reproduce your problem! Do you have the latest version (**1.0.1**) of my plugin?? However, using my [example](https://github.com/pichillilorenzo/flutter_inappbrowser/tree/master/example) and changing `initialUrl`: https://github.com/pichillilorenzo/flutter_inappbrowser/blob/f3f0876f285c46b7e4357a03a978f6b4db2bb8fa/example/lib/inline_example.screen.dart#L43
with `"https://baidu.com/"`, it works as expected on my Android phone:

![rsz_photo_2019-03-14_00-22-19](https://user-images.githubusercontent.com/5956938/54321012-71304580-45ef-11e9-860c-32577f975879.jpg)

**Comment by yhdjy025** [comment]
Maybe the simulator incompatible，I  use another  simulator is ok

**Comment by phuchuynhStrong** [comment]
Some website might need you to enable domStorage

**Comment by virskor** [comment]
my phone using nexus 5x  android 8.1.0 all show empty page when using initial local file. but ios is ok!

**Comment by virskor** [comment]
E/eglCodecCommon(15021): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon(15021): glUtilsParamSize: unknow param 0x000088ef
D/eglCodecCommon(15021): setVertexArrayObject: set vao to 50 (50) 0 0
D/EGL_emulation(15021): eglMakeCurrent: 0xebb353a0: ver 3 0 (tinfo 0xdb2c15e0)
D/eglCodecCommon(15021): setVertexArrayObject: set vao to 4 (4) 1 29

**Comment by huangweigan** [comment]
问题同上，重现。

**Comment by huangweigan** [comment]
Same issues
