### ISSUE TITLE
Execution failed for task ':flutter_inappwebview:parseReleaseLocalResources'.                                      

### ISSUE THREAD

**Issue by princeMing** [pichillilorenzo/flutter_inappwebview#577]
![image](https://user-images.githubusercontent.com/19681693/98063247-8fb11780-1e8a-11eb-8945-998e3f377922.png)

**Comment by pichillilorenzo** [comment]
Try to upgrade your flutter version, plugin version and be sure to setup it correctly on Android: https://inappwebview.dev/docs/get-started/setup-android/
