### ISSUE TITLE
flutter_inappwebview

### ISSUE THREAD

**Issue by mohammadhassan1497** [pichillilorenzo/flutter_inappwebview#580]
How to prevent navigation to other screens in case they accidentally click on those ads

**Comment by narayanansampath** [comment]
you cant try something like this if you use only one link

onLoadStart: (InAppWebViewController controller, String url) {
          if(url != '$YOUR_LINK') {
            launch(url);
            controller.goBack();
          }
        },
        
this will open the link in a separate browser instead of opening within the app.

**Comment by pichillilorenzo** [comment]
You can use the [shouldOverrideUrlLoading](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/WebView/shouldOverrideUrlLoading.html) event to prevent navigation returning `NavigationActionPolicy.CANCEL` for your specific URLs.
You can also use the `ContentBlocker` feature to block ads.
