### ISSUE TITLE
serviceworker support for offline storage?

### ISSUE THREAD

**Issue by rebootcode** [pichillilorenzo/flutter_inappwebview#581]
## Environment

Flutter version: 1,20

## Description

Offline access and Offline Storage of webpages using serviceworker support

**Comment by StarMonk** [comment]
+1 - any chance of supporting "cache for offline view"?

**Comment by pichillilorenzo** [comment]
For Service Worker API, please refer to https://inappwebview.dev/docs/service-worker-api/
