### ISSUE TITLE
Unable to set local storage variables on ios webview onLoadStart, have to wait for onloadStop 

### ISSUE THREAD

**Issue by jalpesh** [pichillilorenzo/flutter_inappwebview#582]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      1.22.3         |
| Plugin version       |        ^4.0.0+4       |
| Android version      |      Android SDK version 30.0.2         |
| iOS version          |       Mac OS X 10.15.7        |
| Xcode version        |       Xcode 12.1        |

Device information: 

## Description

**Expected behavior:** Want to set window.localStorage variables on URL load start in ios in app webview. Works perfectly well in Android.

**Current behavior:** Setting JS variables onLoadStart method does not set any values in the browser.

## Steps to reproduce

1. This

onLoadStart:
                    (InAppWebViewController controller, String url) async {
                  //onload start never got executed in ios
                  aToken = await UserDataStore.getToken();
                  await setJsVars(controller);
                  // print("web view loading ${url}");
                },

setJsVars(InAppWebViewController controller) async {
    try {
      await controller.evaluateJavascript(
          source: "(function() { try { "
              "localStorage.setItem('Token', JSON.stringify('$localToken'));"
              "} catch (err) {  } })();");
    } on Exception catch (_) {
      // print('never reached 1');
    }
}

However the same works well when called on onLoadStop

**Comment by pichillilorenzo** [comment]
Injecting JavaScript before the `onLoadStop`, as written in the API Reference docs, should be avoided because it could not work. This is not something about this plugin but on how native WebViews work.
If you need to inject JavaScript, you should use the `evaluateJavascript` method only on `onLoadStop` event or after that.
Another way is to try to use the new feature `UserScript`.
