### ISSUE TITLE
can localStorage be injected before webview opened ?

### ISSUE THREAD

**Issue by wangxingxing123654** [pichillilorenzo/flutter_inappwebview#585]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by CoolBerry** [comment]
Same issue. Have you fixed it now?

**Comment by pichillilorenzo** [comment]
No, you can’t do that because there is no official native API that allows injecting local storage data before the page is loaded.
For example, one way could be to use cookies through the `CookieManager` class, setting a cookie that is available on the client side without the `HttpOnly` flag.
