### ISSUE TITLE
HeadlessInAppWebView fails to work when using initialFile instead of initialUrl

### ISSUE THREAD

**Issue by toyssamurai** [pichillilorenzo/flutter_inappwebview#586]
- [Y] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [Y] I have already searched for the same problem
- [Y] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [Y] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      1.22.3         |
| Plugin version       |     4.0.0+4          |
| Android version      |      10         |

Device information: 

Google Pixel

**Expected behavior:** 
HeadlessInAppWebView runs without error.

**Current behavior:** 
HeadlessInAppWebView throws an error as soon as it runs.

## Steps to reproduce
I use the example under HeadlessInAppWebView in the read me to test. The codes work without any problem as long as the headless webview is initialized using an url. However, whenever I tried to use initialFile instead of initialUrl, the following error is thrown:

```
E/flutter ( 9631): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
E/flutter ( 9631): Receiver: null
E/flutter ( 9631): Tried calling: length
```

NOTE: I made sure that the assets are made accessible in pubspec.yaml. Also, I switched from the headless webview to a regular InAppWebView with the same initialFile, and the codes work.

**Comment by toyssamurai** [comment]
More observations:

1. If I leave the **initialUrl** as is, then inside **onWebViewCreated** to load the same file using the controller's **loadFile** method, the codes work. Even if the **initialUrl** is just "about:blank", it still works.
2. If I set the initialUrl to a **file:///** url _(totally not cross-platform, but I was just testing_), the codes work as well. 

My feeling is that the problem has to do with how the constructor handles the initialFile parameter only, not the actual file loading routine.

**Comment by pichillilorenzo** [comment]
Have you tried with latest version?
