### ISSUE TITLE
is there any event fired before close the webview to get the controller? 

### ISSUE THREAD

**Issue by wangxingxing123654** [pichillilorenzo/flutter_inappwebview#589]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    
because when get contoller in dispose function sometimes it may be null
## Description

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by pichillilorenzo** [comment]
What do you mean? Are talking about `InAppBrowser` or `InAppWebView`?
However, there is no such event.
