### ISSUE TITLE
How to show push notif from notification webview?

### ISSUE THREAD

**Issue by Thomaslay7** [pichillilorenzo/flutter_inappwebview#591]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by pichillilorenzo** [comment]
What do you mean with “notification webview”? Could you explain more?
