### ISSUE TITLE
Help needed:

### ISSUE THREAD

**Issue by albatrosify** [pichillilorenzo/flutter_inappwebview#592]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  1.22.4 |
| Plugin version       | 4.0.0+4 |
| Android version      |               |
| iOS version          |14.2|
| Xcode version        |               |

Device information: iPhone 11 Max Pro

## Description

**Expected behavior:** 
When starting the App, the instance of WebView should be similar to the one in a previous version.
I am saving my cookies, give them to the initialHeaders field.
I expect that when I re-open the app after closing it, that my login still stays valid.

**Current behavior:** 
I can use as many instances of webview in a flutter app while running, and use the saved cookies to access the current valid session.
However when I close the app, and re-open, with the exact same cookies, I am unable to use the previous session.
I am getting an error, that "It seems you are using this page already in another tab".
Is there any way I can re-create the environment I had before the app was closed, so I can resume the same session?

**Additional Information**
With a simple dart http get request, with the same cookies and url for InAppWebView and http.get(), I am getting the correct response with http.get(), but with InAppWebView the error, that the session is being used in another window.

**Comment by pichillilorenzo** [comment]
To save cookies, you need to use the `CookieManager` and not the `initialHeaders`.
It doesn’t make any sense put the cookie header in it because cookies are set by the server responses and not by the client requests.
You need to access and manage cookies, you need to use the `CookieManager` class.
