### ISSUE TITLE
Some code will be checked by google play store and report a issue that your app(s) are using an unsafe implementation of the HostnameVerifier interface.

### ISSUE THREAD

**Issue by windows7lake** [pichillilorenzo/flutter_inappwebview#593]
The code below will be checked by google play store and report a issue:

> Your app(s) are using an unsafe implementation of the HostnameVerifier interface.

**android/src/main/java/com/pichillilorenzo/flutter_inappwebview/Util.java**
``` java
      builder.hostnameVerifier(new HostnameVerifier() {
        @Override
        public boolean verify(String hostname, SSLSession session) {
          return true;
        }
      });
```

**Comment by xSILENCEx** [comment]
有进展吗？

**Comment by josh-burton** [comment]
I'm now able to publish an update of my app due to this issue. Google is rejecting any binary that has this security vulnerability.

**Comment by josh-burton** [comment]
@pichillilorenzo do you have any thoughts on this? Seems like quite a major issue for a popular library. What was the initial intention of accepting all ssl certs?

**Comment by pichillilorenzo** [comment]
Have you experienced again this issue? This is used by the `ContentBlocker` Android implementation to convert any http request to https.
In simple terms, to implement the `make-https` Content blocker action as on iOS https://developer.apple.com/documentation/safariservices/creating_a_content_blocker
