### ISSUE TITLE
Touch event & rendering issue on Samsung devices

### ISSUE THREAD

**Issue by PankajKumar-htp** [pichillilorenzo/flutter_inappwebview#594]
Using `inappwebview(v4.0.0)`, on few specific Samsung touch event behave strangely while interacting with web pages. 

Also noticed that this issue only occur when application is of **game category** and it is in **Samsung Galaxy game launcher** application.
This issue was previously present in the `webview_flutter` but it got fixed in the latest version ie `v1.0.7`.

### Issue and Screenshots:
Touch is not calibrated and you need to tap above the actual button. As you go towards bottom of the webpage, this offset keeps increasing.
There is an issue with webpage rendering also. Fonts get bigger than the actual size and whole page is zoomed in.

The Web Page is working fine in other web view like `webview_flutter`

`flutter_inappwebview` screenshot : 
 
![Screenshot_20201120-144225](https://user-images.githubusercontent.com/74595114/99783350-5510d580-2b40-11eb-8272-8a316a37daf9.jpg)

`webview_flutter` screenshot:

![Screenshot_20201120-150412](https://user-images.githubusercontent.com/74595114/99784619-15e38400-2b42-11eb-844d-79c7485b1126.jpg)

### Steps to Reproduce

- Create new application and add `flutter_inappwebview: ^4.0.0` in it.

-  Open any url in InAppWebView Widget.
```
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

class InAppWebViewScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("In App WebView")),
      body: Container(
        child: InAppWebView(
          initialUrl: "https://pub.dev/",
        ),
      ),
    );
  }
}
```

-  Run the app in release mode.

- Open **Samsung Game Launcher** app and add your app to it.

- Now Open the flutter app again (You will see some gaming option in the bottom portion  of app [see first screenshot below] only if your app is successfully added as game in samsung game launcher as game type).

**Comment by pichillilorenzo** [comment]
Have you tried latest version?
