### ISSUE TITLE
Can't wait the new release.

### ISSUE THREAD

**Issue by cascopia** [pichillilorenzo/flutter_inappwebview#595]
I believe that this Flutter package is far advanced from the official one, which barely supports essential things. (even doesn't provide an in-depth Cookie manager)
While I am mostly satisfied with the current release, there seem many pending features in the next versions, for example, supporting the hybrid-mode.
Sadly, however, there hasn't been any news or update been a while.  It would be really great for @pichillilorenzo to come back and show us the new future of the WebView widget.

**Comment by ycv005** [comment]
I am waiting for the same. By the way, if you want to use the Hybrid-mode, you get by using this pub package from github.

**Comment by cascopia** [comment]
He's back!

> I am waiting for the same. By the way, if you want to use the Hybrid-mode, you get by using this pub package from github.

**Comment by pichillilorenzo** [comment]
I hope to release the new version as soon as possible! Maybe these days or the next week.
I'm working on it to fix bugs and adding new features and support for Dart null safety!
