### ISSUE TITLE
InAppWebViewChromeClient ChooserActivity bug

### ISSUE THREAD

**Issue by wurstnudl** [pichillilorenzo/flutter_inappwebview#596]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      1.22.2         |
| Plugin version       |     master          |
| Android version      |    10.0           |
| iOS version          |               |
| Xcode version        |               |

**Expected behavior:** 
input/ capture tags should lead to a ChooserActivity, not only a filepicker.

**Current behavior:** 
Filepicker is being displayed immediately.

I think i found a bug in "InAppWebViewChromeClient" line 894: The acceptTypes array is NOT empty in my case, it contains one element with an empty string. This leads to the photo and video capture dialogs never being shown, regardless of the usual permission struggles.

**Comment by wurstnudl** [comment]
On master, testing for wildcard mimetype in lines "984"  and "997" in "nAppWebViewChromeClient.java" fix the problem:

`return isArrayEmpty(mimeTypes) || arrayContainsString(mimeTypes, "image") || Arrays.asList(mimeTypes).contains("*/*");`

@pichillilorenzo Are you still working on the plugin? Would you be interested in a pullrequest for that?

**Comment by wurstnudl** [comment]
I don't think the author will continue this plugin, which is a pity beause it's the best working webview plugin.
Should anybody else have the same problem, the change described above is not enough. There's quite some stuff that needs to be fixed to get everything working.
I'm living with a fork so far and hope @pichillilorenzo will pick up the plugin again later.

**Comment by pichillilorenzo** [comment]
@wurstnudl I'm sorry for that but I'm very busy with my work! I can work on this plugin only on my free time.
I hope to update it as soon as possible!
Thanks

**Comment by cbodin** [comment]
@wurstnudl Adding a check for wildcard mimetypes in both the images/videos method will force the returned file to always be an mp4 as they both use the same outputFileUri and the video is created last.

That'll probably be the case on the master release for input's with an accept of both image/* and video/*.

**Comment by cbodin** [comment]
@pichillilorenzo @wurstnudl I have a WIP pull request that fixes the issue. Some more testing is needed and the example app should probably request camera permission so this can be easily tested.

**Comment by wurstnudl** [comment]
Cool, @cbodin !

If I remember correctly I took a similar approach. 2 different urls for video and photo and testing for the mimetype of the captured file via fileprovder(?, I forgot) or so. In the meantime I'm living with my fork until I can be sure what will happen with this plugin.
