### ISSUE TITLE
IOS Interceptor and replace with local assets

### ISSUE THREAD

**Issue by gayatri2610** [pichillilorenzo/flutter_inappwebview#600]
Please mention feature IOS http request interceptor and replace with local assets files.
Like js, css , images etc.

**Comment by pichillilorenzo** [comment]
There is no way or official API on iOS to intercept http or https request like on Android unfortunately.
On iOS, you can intercept them only if they use custom schemes. In this case you need to register your custom schemes using `resourceCustomSchemes` WebView option and listen for them with the `onLoadResourceCustomScheme` event.
