### ISSUE TITLE
Webview audio keeps playing in background when i minimize the app (external website audio keep playing when I minimize or go to the homescreen)

### ISSUE THREAD

**Issue by tusharnikam-htp** [pichillilorenzo/flutter_inappwebview#601]
- [x] I have read the [README]
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android
- [x] I have read and done the setup for Android:
- [x] I have run the sample app and it does not work there

I have one app in which I am using [inappwebview ](https://pub.dev/packages/flutter_inappwebview) flutter package. My website is a one poker game website which plays music. Problem is that when  I put the app in the background my audio keeps playing, The audio keeps playing onresume, or when I minimize the app,

### Source Code

![alt text](https://i.ibb.co/vmgnwmp/flutter-webview.png)

dependencies:
  flutter_inappwebview: ^4.0.0+4

**Flutter doctor -v** 

_PS C:\Users\Tushar Nikam\Documents\GitHub\htp-mobile> flutter doctor -v_

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Tushar Nikam\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\Tushar Nikam\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\Tushar Nikam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Redmi 8A (mobile) • 1f8597040606 • android-arm • Android 10 (API 29)

**Comment by ycv005** [comment]
Try with the updated version- 5.0.0, only available on github repo.
```
  flutter_inappwebview:
      git:
        url: https://github.com/pichillilorenzo/flutter_inappwebview.git
        ref: master
```

**Comment by tusharnikam-htp** [comment]
@ycv005 Thanks for your response, but we are not using anymore this plugin

**Comment by sleepinglion-dev** [comment]
> Try with the updated version- 5.0.0, only available on github repo.
> 
> ```
>   flutter_inappwebview:
>       git:
>         url: https://github.com/pichillilorenzo/flutter_inappwebview.git
>         ref: master
> ```

Not working.

I want to play the audio in web view in the background. 

Give me a hint.

**Comment by pichillilorenzo** [comment]
You should call the android-specific pause/resume methods when your app goes background or resume.
Also, it seems that on Android and latest versions of Flutter, it is automatically managed by Flutter itself.

**Comment by guotao** [comment]
> in InAppWebView plugin, if app is in background then audio breaks after 5 minutes

Is it possible to config the "5 minutes"?

**Comment by Scottlexium** [comment]
Please I am actually wishing my webview plays in background because mine isn't working

**Comment by pawangjain** [comment]
In version  ^4.0.0+4,  the audio of a youtube video used to play in backgroud when the device was locked. But in version ^5.3.2 the audio pauses when the device is locked. Is there any way we can enable backgroud audio when the device is locked?

**Comment by pawangjain** [comment]
> In version ^4.0.0+4, the audio of a youtube video used to play in background when the device was locked. But in version ^5.3.2 the audio pauses when the device is locked. Is there any way we can enable background audio when the device is locked?

Any updates or workaround is available?

**Comment by gauravparvadiya** [comment]
> in InAppWebView plugin, if app is in background then audio breaks after 5 minutes

I am having the same issue. Dod you get any fix for that?

**Comment by Scottlexium** [comment]
No got no fix

**Comment by azizur-rahaman** [comment]
1 add WidgetsBindingObserver to your class

class AnyClass extends StatefulWidgets {
  _AnyClassState createState() => _AnyClassState();
}

class _AnyClassState extends State<AnyClass> with 
WidgetsBindingObserver {
  Widget build(BuildContext context) {
    return ...
  }
}
2 Now it will work, we can added the methods inside class

class _AnyClassState extends State<AnyClass> with 
WidgetsBindingObserver {

  // ADD THIS AppLifecycleState VARIABLE 
  late AppLifecycleState appLifecycle;

  // ADD THIS FUNCTION WITH A AppLifecycleState PARAMETER
  didChangeAppLifecycleState(AppLifecycleState state) {
    appLifecycle = state;
    setStae(() {});
    
    if(state == AppLifecycle.paused) {
      // IF YOUT APP IS IN BACKGROUND...
      // YOU CAN ADDED THE ACTION HERE
      print('My app is in background');
    }
  }
  
  // CREATE INITSTATE AND DISPOSE METHODS
  initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
  
  Widget build(BuildContext context) {
    return ...
  }
}
NOW IT WILL WORK FINE!

**Comment by DaveTolulope22** [comment]
One other  work around   is that you  pause the media on navigation to the new route using javascript . implementation done in webview_flutter 4.4.2, here is my example : 

..addJavaScriptChannel(
  ‘PageOpen',
  onMessageReceived: (JavaScriptMessage message) async {
    // Pause all videos and audios before starting the navigation
    _controller?.runJavaScript(
      'document.querySelectorAll("video, audio").forEach(media => media.pause());'
    );

    final int pageId = int.parse(message.message);
    Navigator.of(context)
        .push(MaterialPageRoute(
          builder: (context) => pageview(pageId: pageId),
        ))
        .then((_) {
          // executed after returning back to this page
          // You can add use case here if you need to perform any action when returning back
        });
  },
);

**Comment by Mr-Programmar** [comment]
> in InAppWebView plugin, if app is in background then audio breaks after 5 minutes

Did you find the solution to it? the same issue is coming with me even though I am using version 6.0.0

**Comment by pichillilorenzo** [comment]
@Mr-Programmar for Android, you can try the WebView setting `allowBackgroundAudioPlaying`. Check https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebViewSettings/allowBackgroundAudioPlaying.html for more info about it.

**Comment by Mr-Programmar** [comment]
@pichillilorenzo The problem is audio stops after 4-5 minutes when the app is in the background or the screen is locked.
I have Tested this issue  in 4 different devices but same issue.

(My website is a radio website and I spent 15 days to make this app but it's going to waste now just because of that.)

**Comment by Mr-Programmar** [comment]
My setting>>>>>>


InAppWebViewSettings? initialSettings=  InAppWebViewSettings(
    
  mediaPlaybackRequiresUserGesture: false,
  webViewAssetLoader:WebViewAssetLoader( httpAllowed: true,domain: "https://app.sensimedia.net/danc/index.php") ,
  useHybridComposition: true,
  allowsInlineMediaPlayback: true,
    networkAvailable: true,
    mediaType: null,
    allowBackgroundAudioPlaying: true,
    applicationNameForUserAgent: "Sensimedia Radio",
    disableDefaultErrorPage: true,
   disableVerticalScroll: true,


  );

**Comment by pichillilorenzo** [comment]
@Mr-Programmar probably, using a WebView for such kind of app is not the correct implementation.
There could be a lot of reasons and could depend on the Android OS itself, such as to save battery life or something else, as WebView (in general) is not made for such things like playing audio in background as you may have on apps like Spotify.
Here is a Reddit post: https://www.reddit.com/r/androiddev/comments/12fn6r4/android_webview_play_audio_in_background/?rdt=39396
For playing audio in background, you would use something like: https://pub.dev/packages/audio_service

**Comment by Mr-Programmar** [comment]
Thank you! My last question is how to keep running flutter webview app in background.
When the app is in the background it closes after almost 12 minutes .  it show the message on console   <Lost connection to device.>

**Comment by pichillilorenzo** [comment]
@Mr-Programmar As said before, this is something that depends on the OS. It’s not just the audio, but the whole WebView.
If you need to run background tasks, maybe you can use the workmanager plugin https://pub.dev/packages/workmanager, register a task and run an HeadlessInAppWebView, but that’s it.
You can’t be sure how the OS is managing resources for such background functionality.
If you need specific features that should run on background for long time, use something else. 
A WebView is not what you are looking to create such functionality.
Use the WebView for displaying your website and to interact with web contents, use other packages or implement your custom plugin to implement other features, such as audio_service plugin.
