### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method HtmlToString on channel htmlView)

### ISSUE THREAD

**Issue by jigarparmar21** [pichillilorenzo/flutter_inappwebview#602]
I am getting this exception error in android only, in ios it works fine. When i select on the product in my app the next screen does not appear and only loader shows. And shows this exception in debug console.

**Comment by pichillilorenzo** [comment]
This is something not related to this plugin. I don’t have any method called HtmlToString
