### ISSUE TITLE
Is there an option or method to set the background color before inAppWebView is fully loaded?

### ISSUE THREAD

**Issue by Wujidadi** [pichillilorenzo/flutter_inappwebview#603]
Even the splash screen is correctly set (in `android/app/src/main/res/drawable`) and runs normally, there is still a time span of several seconds that the screen is just totally white before the web page is fully loaded.

I also defined the background color (except white) of `<body>`, but the white screen keeps existing.

Could I have the solution? Thank for help.

**Comment by mxmihai** [comment]
on Android:
play with:
\android\app\src\main\res\drawable\launch_background.xml
and, if needed:
\android\app\src\main\AndroidManifest.xml
in your project folder. you can customize a native splash screen and background too.
see documentation.

on IOS:
\ios\Runner\Base.lproj\LaunchScreen.storyboard
\ios\Runner\Assets.xcassets\Launch Image.imageset\...

as far as I remember, you can also create custom splash screen, maybe you have to check the flutter.dev docs.
