### ISSUE TITLE
A url is opened with the "System Browser" and "Chrome Safari Browser", but not opened in the webview

### ISSUE THREAD

**Issue by vickywu23** [pichillilorenzo/flutter_inappwebview#604]
https://pay.testwyre.com/purchase?accountId=AC_XW9HVYDM3VG&country=US&amountIncludeFees=false&utm_campaign=AC_XW9HVYDM3VG&destCurrency=ETH&paymentMethod=debit-card&reservation=C6JQ6EQ9CB24CDVFD77C&sourceCurrency=USD&sourceAmount=200&dest=ethereum%3A0xC617889dCF27F8e095D1F22Bf66789Ecd4d6Ac52&referenceId=b8f4a731-eac4-41b7-9ab4-b81e16991cc2&quoteId=82FMG6FJ7GJ

This URL is opened with the "System Browser" and "Chrome Safari Browser", but not opened in the webview in the demo code. And this URL is opened with the "flutter_webview_plugin". But I want to use the "flutter_inappwebview" due to it has the "androidOnPermissionRequest".

**Comment by vickywu23** [comment]
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-27 at 15 19 33](https://user-images.githubusercontent.com/10335343/100422521-72581d80-30c5-11eb-9e46-c492f7cea75f.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-27 at 15 19 47](https://user-images.githubusercontent.com/10335343/100422615-9d427180-30c5-11eb-9160-727359418538.png)

The first pic is the wrong action, the webview 
hasn't response. the second pic is the right action.

**Comment by ycv005** [comment]
Try with the latest- 5.0.0 (only avaible on the github)
```
  flutter_inappwebview:
      git:
        url: https://github.com/pichillilorenzo/flutter_inappwebview.git
        ref: master
```

**Comment by vickywu23** [comment]
Hi, I try the  latest- 5.0.0, but the webview still doesn't work.
![image](https://user-images.githubusercontent.com/10335343/100493333-e56a9e00-3170-11eb-8678-ffe7d236026b.png)
above is the log, I am not sure if it is useful.

**Comment by vickywu23** [comment]
![image](https://user-images.githubusercontent.com/10335343/100493372-34b0ce80-3171-11eb-85b4-e2dc1ef04bd5.png)

Sorry, the pic isn't uploaded, below is the log infomation.


flutter: onWebViewCreated
flutter: onLoadStart https://pay.testwyre.com/purchase?accountId=AC_XW9HVYDM3VG&country=US&amountIncludeFees=false&utm_campaign=AC_XW9HVYDM3VG&destCurrency=ETH&paymentMethod=debit-card&reservation=C6JQ6EQ9CB24CDVFD77C&sourceCurrency=USD&sourceAmount=200&dest=ethereum%3A0xC617889dCF27F8e095D1F22Bf66789Ecd4d6Ac52&referenceId=b8f4a731-eac4-41b7-9ab4-b81e16991cc2&quoteId=82FMG6FJ7GJ
flutter: onLoadStop https://pay.testwyre.com/purchase?accountId=AC_XW9HVYDM3VG&country=US&amountIncludeFees=false&utm_campaign=AC_XW9HVYDM3VG&destCurrency=ETH&paymentMethod=debit-card&reservation=C6JQ6EQ9CB24CDVFD77C&sourceCurrency=USD&sourceAmount=200&dest=ethereum%3A0xC617889dCF27F8e095D1F22Bf66789Ecd4d6Ac52&referenceId=b8f4a731-eac4-41b7-9ab4-b81e16991cc2&quoteId=82FMG6FJ7GJ
flutter: {message: [object Object], messageLevel: 1}
flutter: {message: [object Object], messageLevel: 1}
flutter: {message: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object], messageLevel: 1}
flutter: {message: [object Object], messageLevel: 1}
flutter: {message: session.set,config,{"exchangeRatePusherChannel":"rates","featureAvailability":{},"currencies":[{"name":"Aave","ticker":"AAVE","displayTicker":"AAVE","digitalCurrency":true,"erc20Token":true,"symbol":"","numberOfDecimalPlaces":18,"displayDecimalPlaces":8,"shortSymbol":""},{"name":"Australian Dollar","ticker":"AUD","displayTicker":"AUD","digitalCurrency":false,"erc20Token":false,"symbol":"A$","numberOfDecimalPlaces":2,"displayDecimalPlaces":2,"shortSymbol":"$"},{"name":"Basic Attention Token","ticker":"BAT","displayTicker":"BAT","digitalCurrency":true,"erc20Token":true,"symbol":"","numberOfDecimalPlaces":18,"displayDecimalPlaces":8,"shortSymbol":""},{"name":"Brazilian Real","ticker":"BRL","displayTicker":"BRL","digitalCurrency":false,"erc20Token":false,"symbol":"R$","numberOfDecimalPlaces":2,"displayDecimalPlaces":2,"shortSymbol":"$"},{"name":"bitcoin","ticker":"BTC","displayTicker":"BTC","digitalCurrency":true,"erc20Token":false,"symbol":"฿","numberOfDecimalPlaces":8,"displa<…>
flutter: {message: session.set,countries,[{"name":"Algeria","code":"DZ","phonePrefix":"213"},{"name":"Argentina","code":"AR","phonePrefix":"54"},{"name":"Australia)","code":"AU","phonePrefix":"61"},{"name":"Austria (Österreich)","code":"AT","phonePrefix":"43"},{"name":"Belarus","code":"BY","phonePrefix":"375"},{"name":"Belgium (België)","code":"BE","phonePrefix":"32"},{"name":"Bolivia","code":"BO","phonePrefix":"591"},{"name":"Brazil","code":"BR","phonePrefix":"55"},{"name":"Canada","code":"CA","phonePrefix":"1"},{"name":"Chile","code":"CL","phonePrefix":"56"},{"name":"Colombia","code":"CO","phonePrefix":"57"},{"name":"Costa Rica","code":"CR","phonePrefix":"506"},{"name":"Cyprus","code":"CY","phonePrefix":"357"},{"name":"Czech Republic","code":"CZ","phonePrefix":"420"},{"name":"Denmark","code":"DK","phonePrefix":"45"},{"name":"Dominican Republic","code":"DO","phonePrefix":"1"},{"name":"Estonia","code":"EE","phonePrefix":"372"},{"name":"Finland","code":"FI","phonePrefix":"358"},{"name":"France<…>
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: session.get,wyreSessionId,, messageLevel: 1}
flutter: {message: session.set,wyreSessionId,04c11fae-2a7c-4c26-ac5d-e9f3fae73031, messageLevel: 1}
flutter: {message: session.get,wyreSessionId,04c11fae-2a7c-4c26-ac5d-e9f3fae73031, messageLevel: 1}
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: Configuration loaded,[object Object], messageLevel: 1}
flutter: {message: session.get,params,, messageLevel: 1}
flutter: {message: Initial stored params,[object Object], messageLevel: 1}
flutter: {message: session.get,params,, messageLevel: 1}
flutter: {message: session.get,reservation,, messageLevel: 1}
flutter: {message: session.get,params,, messageLevel: 1}
flutter: onUpdateVisitedHistory about:blank
flutter: onLoadStart about:blank
flutter: onLoadStop about:blank
flutter: onLoadStart about:blank
flutter: onLoadStop about:blank
flutter: onLoadStart about:blank
flutter: onLoadStop about:blank
flutter: onWebViewCreated
flutter: onLoadStart https://pay.testwyre.com/purchase?accountId=AC_XW9HVYDM3VG&country=US&amountIncludeFees=false&utm_campaign=AC_XW9HVYDM3VG&destCurrency=ETH&paymentMethod=debit-card&reservation=C6JQ6EQ9CB24CDVFD77C&sourceCurrency=USD&sourceAmount=200&dest=ethereum%3A0xC617889dCF27F8e095D1F22Bf66789Ecd4d6Ac52&referenceId=b8f4a731-eac4-41b7-9ab4-b81e16991cc2&quoteId=82FMG6FJ7GJ
flutter: onLoadStop https://pay.testwyre.com/purchase?accountId=AC_XW9HVYDM3VG&country=US&amountIncludeFees=false&utm_campaign=AC_XW9HVYDM3VG&destCurrency=ETH&paymentMethod=debit-card&reservation=C6JQ6EQ9CB24CDVFD77C&sourceCurrency=USD&sourceAmount=200&dest=ethereum%3A0xC617889dCF27F8e095D1F22Bf66789Ecd4d6Ac52&referenceId=b8f4a731-eac4-41b7-9ab4-b81e16991cc2&quoteId=82FMG6FJ7GJ
flutter: {message: [object Object], messageLevel: 1}
flutter: {message: [object Object], messageLevel: 1}
flutter: {message: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object], messageLevel: 1}
flutter: {message: [object Object], messageLevel: 1}
flutter: {message: session.set,config,{"exchangeRatePusherChannel":"rates","featureAvailability":{},"currencies":[{"name":"Aave","ticker":"AAVE","displayTicker":"AAVE","digitalCurrency":true,"erc20Token":true,"symbol":"","numberOfDecimalPlaces":18,"displayDecimalPlaces":8,"shortSymbol":""},{"name":"Australian Dollar","ticker":"AUD","displayTicker":"AUD","digitalCurrency":false,"erc20Token":false,"symbol":"A$","numberOfDecimalPlaces":2,"displayDecimalPlaces":2,"shortSymbol":"$"},{"name":"Basic Attention Token","ticker":"BAT","displayTicker":"BAT","digitalCurrency":true,"erc20Token":true,"symbol":"","numberOfDecimalPlaces":18,"displayDecimalPlaces":8,"shortSymbol":""},{"name":"Brazilian Real","ticker":"BRL","displayTicker":"BRL","digitalCurrency":false,"erc20Token":false,"symbol":"R$","numberOfDecimalPlaces":2,"displayDecimalPlaces":2,"shortSymbol":"$"},{"name":"bitcoin","ticker":"BTC","displayTicker":"BTC","digitalCurrency":true,"erc20Token":false,"symbol":"฿","numberOfDecimalPlaces":8,"displa<…>
flutter: {message: session.set,countries,[{"name":"Algeria","code":"DZ","phonePrefix":"213"},{"name":"Argentina","code":"AR","phonePrefix":"54"},{"name":"Australia)","code":"AU","phonePrefix":"61"},{"name":"Austria (Österreich)","code":"AT","phonePrefix":"43"},{"name":"Belarus","code":"BY","phonePrefix":"375"},{"name":"Belgium (België)","code":"BE","phonePrefix":"32"},{"name":"Bolivia","code":"BO","phonePrefix":"591"},{"name":"Brazil","code":"BR","phonePrefix":"55"},{"name":"Canada","code":"CA","phonePrefix":"1"},{"name":"Chile","code":"CL","phonePrefix":"56"},{"name":"Colombia","code":"CO","phonePrefix":"57"},{"name":"Costa Rica","code":"CR","phonePrefix":"506"},{"name":"Cyprus","code":"CY","phonePrefix":"357"},{"name":"Czech Republic","code":"CZ","phonePrefix":"420"},{"name":"Denmark","code":"DK","phonePrefix":"45"},{"name":"Dominican Republic","code":"DO","phonePrefix":"1"},{"name":"Estonia","code":"EE","phonePrefix":"372"},{"name":"Finland","code":"FI","phonePrefix":"358"},{"name":"France<…>
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: session.get,wyreSessionId,, messageLevel: 1}
flutter: {message: session.set,wyreSessionId,950fa32d-83b4-482f-b0d2-f91522eb105a, messageLevel: 1}
flutter: {message: session.get,wyreSessionId,950fa32d-83b4-482f-b0d2-f91522eb105a, messageLevel: 1}
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: session.get,config,[object Object], messageLevel: 1}
flutter: {message: Configuration loaded,[object Object], messageLevel: 1}
flutter: {message: session.get,params,, messageLevel: 1}
flutter: {message: Initial stored params,[object Object], messageLevel: 1}

**Comment by noyon04** [comment]
I have the same problem too. Gpay page is not opening, shows "Unexpected Developer Error, Please Try again later. But ChromeSafariBrowser works fine. So, is there any solution for that? or not showing the heading of chromesafariBrowser.

**Comment by gitsofkhaleel** [comment]
any update on this
