### ISSUE TITLE
Whether the flutter_inappwebview support the Apple pay? there is the Apple pay option with "System Browser".

### ISSUE THREAD

**Issue by vickywu23** [pichillilorenzo/flutter_inappwebview#605]
In the flutter_inappwebview demo, there is the Apple pay option with "System Browser", the same URL, there is NOT the Apple pay option with "InAppWebView". Do I need to set up some additional configurations?

**Comment by pichillilorenzo** [comment]
It will possible with the next release using the `applePayAPIEnabled` iOS-specific WebView option.

**IMPORTANT NOTE**: As written in the official [Safari 13 Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes#Payment-Request-API), it won't work if any script injection APIs is used (such as `InAppWebViewController.evaluateJavascript` or `UserScript`).
So, when this attribute is `true`, all the methods, options, and events implemented using JavaScript won't be called or won't do anything and the result will always be `null`.
See the documentation for more info and to know the cons of enabling this option.
