### ISSUE TITLE
How to send data from js to dart, or dart to js

### ISSUE THREAD

**Issue by callmejm** [pichillilorenzo/flutter_inappwebview#611]
First of all , great library , great job.
I know there is doc about this https://github.com/pichillilorenzo/flutter_inappwebview#about-the-javascript-handler , but I try and it didn't work. 

I also follow the example from https://github.com/pichillilorenzo/flutter_inappwebview/issues/370#issuecomment-635830655

1. How to receive data `args` from `addJavaScriptHandler`
2. In web do we need to call like `<button onclick"handlerFoo(myargs);">click</button>` to pass `args` back to flutter 
3. `flutterInAppWebViewPlatformReady` , I put `console.log("flutter ready");` , but it didn't show in vscode debug console

        <script>
            window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
                console.log("flutter ready");
            window.flutter_inappwebview.callHandler('handlerFoo').then(function(result) {
                console.log(result);
            });
        
            window.flutter_inappwebview.callHandler('handlerFooWithArgs', 1, true, ['bar', 5], {foo: 'baz'}).then(function(result) {
                console.log(result);
            });
            });

        </script>

**Comment by MrEliasen** [comment]
```dart
InAppWebView(
  initialUrl: 'https://...',
  onWebViewCreated: (InAppWebViewController controller) {

    /// define our "ping" event
    controller.addJavaScriptHandler(
      handlerName: "ping",
      callback: (List<dynamic> payload) {
        print(payload);
      },
    );
  },
);
```

```js
<script>
    // listen for when the flutter app is ready to receive events
    window.addEventListener('flutterInAppWebViewPlatformReady', function() {
        // ping an event back to the app
        window.flutter_inappwebview.callHandler('ping', 'Ready!');
    });
</script>
```

Maybe your event handler in the app is not setup properly?

**Comment by sebastianbuechler** [comment]
@MrEliasen Thank you for the example, it works for js to dart communication. But what about dart to js? For example, how could I send a variable to the rendered webview from dart?

**Comment by pichillilorenzo** [comment]
I added a new [JavaScript Communication](https://inappwebview.dev/docs/in-app-webview/javascript-communication/) section to the [Official docs](https://inappwebview.dev/docs/) of the plugin with code examples to help you understand better how to communicate with Dart - JS and vice-versa! Hope it helps.

**Comment by msutharworkspace** [comment]
Hello @callmejm  I have did same thing but its not working in flutter web its working proper in mobile flutter app.

**Comment by msutharworkspace** [comment]
Why **flutter_inappwebview** not available in **window**?
