### ISSUE TITLE
How to have a browser with search bar inside the widget tree (not in full screen over the app) ?

### ISSUE THREAD

**Issue by samulefevre** [pichillilorenzo/flutter_inappwebview#612]
Hello pichillilorenzo, great job ! I want to have a browser with search bar inside my app(integrated into the flutter widget tree).
What shoud I use ?

InAppWebView: not a browser
InAppBrowser: search bar and full screen
ChromeSafariBrowser:  no searchbar and full screen

Is it possible to have InAppBrowser not full screen ?

**Comment by pichillilorenzo** [comment]
You need to implement it by yourself using the `InAppWebView` widget.
You can take as an example my [Flutter Browser App](https://github.com/pichillilorenzo/flutter_browser_app).
