### ISSUE TITLE
ChromeSafariBrowser crashes on iOS when '\' - Backslash character is present in the URL

### ISSUE THREAD

**Issue by BunnyMan1** [pichillilorenzo/flutter_inappwebview#613]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [ ] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        1.22.4 Stable       |
| Plugin version       |       ^4.0.0+4        |
| Android version      |       -        |
| iOS version          |        14.0.1       |
| Xcode version        |        12.2       |

Device information:  iPhone 11 Pro Max Simulator AND iPhone 7 Plus Real Device

## Description

**Expected behavior:** When '\\' or '\\\\' is contained in the URL, it either opens the webview or throws an error messsage.

**Current behavior:** App crashes in an instant without any useful error message.

## Steps to reproduce

1. Use ChromeSafariBrowser on an iOS device.
2. Pass url String containing a double backslash '\\\\' in it.
3. Logically open the Browser now. See the app crash. 

Of course this was easy to solve by using `string.replaceAll("\\", "/")` but wanted to bring it to everyone's notice as there wasn't a relevant error message pointing to the issue.

This is an amazing package by the way! Thank you for making it available.

**Comment by pichillilorenzo** [comment]
Have you tried with latest version? Thanks!
