### ISSUE TITLE
Header Field are too long for server to interpret

### ISSUE THREAD

**Issue by izzabellerina** [pichillilorenzo/flutter_inappwebview#615]
- [✓] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [✓] I have already searched for the same problem
- [✓] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [ ] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [✓] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |1.24.0-10.2.pre |
| Plugin version       | ^4.0.0+4|
| Android version      |29.0.3|
| iOS version          |       -        |
| Xcode version        |  12.2  |

Device information: SM G925F (mobile) • 1215fca2b83e0704 • android-arm64 • Android 7.0 (API 24)

## Description
Hello everyone, when I open the URL from the esp32 server sending the stream camera and show it on the smartphone inside webview. Then, the problem is the webview showed some text  as follow 
"Header Field are too long for server to interpret".
However, when I use the tablet instead of the smartphone, it works well.
I don't know what to do, maybe the problem must solve at esp32 gadget or the setting of webview option. Please, guide me.
Thank you in advance, everyone.
ps1 . the URL that I use is "http://192.168.0.23:81/stream"
ps2. the size of the camera video of esp32 is 1200X1600 pix
ps3. the tablet device is 
• SM T815Y (mobile) • 33003757367613a1 • android-arm • Android 7.0 (API 24) (emulator)
ps4. the smartphone device is 
• SM G925F (mobile) • 1215fca2b83e0704 • android-arm64 • Android 7.0 (API 24)
ps5. the webview code which I used is 
InAppWebView(
          initialUrl: "http://192.168.0.23:81/stream",
          initialOptions: InAppWebViewGroupOptions(
              android: AndroidInAppWebViewOptions(
                  displayZoomControls: true, allowContentAccess: true, builtInZoomControls: true),
              crossPlatform: InAppWebViewOptions(clearCache: true, debuggingEnabled: true)),
        );

**Comment by jorgesalgado33** [comment]
Hello, i have the same problem, and i'm looking for the solution, nothing until now, but you can try this:
(Flutter get the browser of the device if i understood)
-In your tablet /parameter/application/Browser look for the "default browser", tell us wich one it is. 
-in your smartphone/parameter/application/browser, tell us which one it is. 
**so you can try to change the default browser in your smartphone** and test it please. 
i'm looking forward to hearing from you

**Comment by Lipyoung0721** [comment]
What's the result

**Comment by pichillilorenzo** [comment]
This is not an issue with the plugin but with the esp32.
Just search for that error online and you will find it, for example:
- https://rntlab.com/question/esp32-camera-headers-and-browser/

**Comment by dhaval-parmar-1108** [comment]
I am facing the same issue. Do not know any solution yet.

**Comment by Lipyoung0721** [comment]
Sorry&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pichillilorenzo/flutter_inappwebview"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月18日(星期一) 晚上7:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pichillilorenzo/flutter_inappwebview] Header Field are too long for server to interpret (#615)





 
I am facing the same issue. Do not know any solution yet.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
