### ISSUE TITLE
How to use ContentBlocker to block ads?

### ISSUE THREAD

**Issue by CarmenLexa** [pichillilorenzo/flutter_inappwebview#616]
I'm trying to use ContentBlocker to block ads but it doesn't work, I try to use onLoadResource but I don't know how to lock the resource before it loads, any ideas?

**Comment by arcanebrownie** [comment]
I could use some help with this as well, if someone could give an example on how to use contentBlocker, it would be appreciated!

**Comment by Vanilo** [comment]
Try this:

`
            contentBlockers: [
              ContentBlocker(
                trigger: ContentBlockerTrigger(
                  urlFilter: '.*',
                  resourceType: [ContentBlockerTriggerResourceType.IMAGE],
                ),
                action: ContentBlockerAction(
                  type: ContentBlockerActionType.BLOCK,
                ),
              ),
            ],
`

Change the urlFilter and resoureType as you need.

**Comment by arcanebrownie** [comment]
> Try this:
> 
> `contentBlockers: [ ContentBlocker( trigger: ContentBlockerTrigger( urlFilter: '.*', resourceType: [ContentBlockerTriggerResourceType.IMAGE], ), action: ContentBlockerAction( type: ContentBlockerActionType.BLOCK, ), ), ],`
> 
> Change the urlFilter and resoureType as you need.

This doesn't really work since I am trying to load normal images. Also, there are certain ads that are "overlays"? I'm not sure how else to explain it. I was thinking what if I inject a javascript adblocker into the webview? Do you have any thoughts on that @Vanilo?

**Comment by oiolong** [comment]
> > Try this:
> > `contentBlockers: [ ContentBlocker( trigger: ContentBlockerTrigger( urlFilter: '.*', resourceType: [ContentBlockerTriggerResourceType.IMAGE], ), action: ContentBlockerAction( type: ContentBlockerActionType.BLOCK, ), ), ],`
> > Change the urlFilter and resoureType as you need.
> 
> This doesn't really work since I am trying to load normal images. Also, there are certain ads that are "overlays"? I'm not sure how else to explain it. I was thinking what if I inject a javascript adblocker into the webview? Do you have any thoughts on that @Vanilo?

It's working .

Try this:

(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,

        contentBlockers: [
            ContentBlocker(
                            trigger: ContentBlockerTrigger( urlFilter: "http://.*aaa.*", resourceType: [ContentBlockerTriggerResourceType.SCRIPT], ),
                            action: ContentBlockerAction( type: ContentBlockerActionType.BLOCK, ), ),
        ],

        /*
        * contentBlockers: [ ContentBlocker( trigger: ContentBlockerTrigger( urlFilter: '.*', resourceType: [ContentBlockerTriggerResourceType.IMAGE], ), action: ContentBlockerAction( type: ContentBlockerActionType.BLOCK, ), ), ],
        * */
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      ));

Change the urlFilter and resoureType as you need. 

urlFilter ↔ String
A regular expression pattern to match the URL against.
read / write

If you wanna filter some js named aaa.js

u can try this :

http://.*aaa.*

**Comment by SamoilovEA** [comment]
@oiolong Hello. How to put LIST from web sites into urlFilter method? "http://.*aaa.*", "http://.*bbb.*", "http://.*ccc.*" ?
