### ISSUE TITLE
postURL does not redirect, just shows white blank page

### ISSUE THREAD

**Issue by MihailovDev** [pichillilorenzo/flutter_inappwebview#618]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     1.24.0-10.2.pre          |
| Plugin version       |    4.0.0           |
| Android version      |      Android SDK version 30.0.2         |

I need to implement payment and it needs to do the following:
1. make post request to a url, the url than redirects to a payment screen.

When i use postUrl with postData it should then redirect to a payment screen provided by my payment provider.

It shows a blank white page

## Steps to reproduce

` 
import 'dart:convert';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app/util/globals.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:url_launcher/url_launcher.dart';

Future main() async {
  runApp(new PaymentScreen());
}
class PaymentScreen extends StatefulWidget {
  @override
  _MyPaymentWidgetState createState() => new _MyPaymentWidgetState();
}
class _MyPaymentWidgetState extends State<PaymentScreen> {
  InAppWebViewController webView;
  String url = "";
  Uint8List postData;
  double progress = 0;
  @override
  void initState() {
    super.initState();
  }
  @override
  void dispose() {
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
          title: Text(
            "title",
            style: Theme.of(context).textTheme.title.merge(TextStyle(letterSpacing: 1.3)),
          ),
        ),
        body: Container(
            child: Column(children: <Widget>[
          Container(
              padding: EdgeInsets.all(10.0),
              child: progress < 1.0 ? LinearProgressIndicator(value: progress) : Container()),
          Expanded(
            child: Container(
              margin: const EdgeInsets.all(10.0),
              decoration: BoxDecoration(border: Border.all(color: Colors.blueAccent)),
              child: InAppWebView(
                initialUrl: "https://epay.halkbank.mk/fim/est3Dgate",
                initialHeaders: {},
                initialOptions: InAppWebViewGroupOptions(
                    crossPlatform: InAppWebViewOptions(
                        javaScriptEnabled: true,
                        javaScriptCanOpenWindowsAutomatically: true,
                        useShouldOverrideUrlLoading: true,
                        debuggingEnabled: true
                        )),
                onWebViewCreated: (InAppWebViewController controller) {
                  const url = "https://epay.halkbank.mk/fim/est3Dgate";
                  const orderID = "1111111111111111111"; //generated chatID
                  const rnd = "1111"
                  var stringToHash = CLIENT_ID +
                      orderID +
                      "20" +
                      OKURL +
                      FAILURL +
                      TRANSACTION_TYPE_AUTHORIZATION +
                      rnd +
                      STOREKEY;
                  print(stringToHash);
                  var bytes = utf8.encode(stringToHash); // data being hashed
                  print("bytes: $bytes");
                  var hashedBytes = sha1.convert(bytes).bytes;
                  var st = base64Encode(hashedBytes);
                  var postData = "clientId=" +
                      utf8.encode(CLIENT_ID).toString() +
                      "&storetype=" +
                      utf8.encode(STORETYPE).toString() +
                      "&hash=" +
                      utf8.encode(st).toString() +
                      "&trantype=" +
                      utf8.encode(TRANSACTION_TYPE_AUTHORIZATION).toString() +
                      "&amount=" +
                      utf8.encode("20").toString() +
                      "&currency=" +
                      utf8.encode(CURRENCY).toString() +
                      "&oid=" +
                      utf8.encode(orderID).toString() +
                      "&okUrl=" +
                      utf8.encode(OKURL).toString() +
                      "&failUrl=" +
                      utf8.encode(FAILURL).toString() +
                      "&lang=" +
                      utf8.encode(LANGUAGE).toString() +
                      "&rnd=" +
                      utf8.encode(rnd).toString() +
                      "&encoding=" +
                      utf8.encode(ENCODING).toString() +
                      "&refreshtime=10" +
                      "&Id1=useridtest" +
                      "&ProductCode1=chatID" +
                      "&Fismi=a";
                  webView = controller;
                  webView.postUrl(url: url, postData: utf8.encode(postData));
                },
                onLoadStart: (InAppWebViewController controller, String url) {
                  setState(() {
                    this.url = url;
                  });
                },
                onLoadStop: (InAppWebViewController controller, String url) async {
                  setState(() {
                    this.url = url;
                  });
                },
                shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
                  var url = shouldOverrideUrlLoadingRequest.url;
                  var uri = Uri.parse(url);
                  if (!["http", "https", "file",
                    "chrome", "data", "javascript",
                    "about"].contains(uri.scheme)) {
                    if (await canLaunch(url)) {
                      // Launch the App
                      await launch(
                        url,
                      );
                      // and cancel the request
                      return ShouldOverrideUrlLoadingAction.CANCEL;
                    }
                  }
                  return ShouldOverrideUrlLoadingAction.ALLOW;
                },
                onLoadError: (InAppWebViewController controller, String url, int code,
                    String message) async {
                  print("errorMessage $message");
                  print("errorCode => $code");
                  print("errorString => $url");
                },
                onProgressChanged: (InAppWebViewController controller, int progress) {
                  setState(() {
                    this.progress = progress / 100;
                  });
                },
              ),
            ),
          ),
          ButtonBar(
            alignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Icon(Icons.arrow_back),
                onPressed: () {
                  if (webView != null) {
                    webView.goBack();
                  }
                },
              ),
              RaisedButton(
                child: Icon(Icons.arrow_forward),
                onPressed: () {
                  if (webView != null) {
                    webView.goForward();
                  }
                },
              ),
              RaisedButton(
                child: Icon(Icons.refresh),
                onPressed: () {
                  if (webView != null) {
                    webView.reload();
                  }
                },
              ),
            ],
          ),
        ])),
      ),
    );
  }
}`

`

**Comment by MihailovDev** [comment]
My bad =)

**Comment by john990** [comment]
We also encountered this problem, can anyone solve it?

**Comment by leononly** [comment]
@MihailovDev i have this problem too, please do tell how to solve this??

**Comment by skustra** [comment]
> My bad =)

??????????????????????????
