### ISSUE TITLE
equivalent of androidOnPermissionRequest for iOS

### ISSUE THREAD

**Issue by touficzayed** [pichillilorenzo/flutter_inappwebview#621]
## Environment

**Flutter version: 1.24.0-10.2.pre
**Plugin version: 4.0.0+4
**Android version: Android SDK version 30.0.0
**iOS version: 14.3
**Xcode version: 12.3 beta
**Device information: iPhone 12 simulator

## Description

Hello.

I launch a local web page from assets using a local web server serving on localhost address. This page uses WebRTC. 

When I call getUserMedia on iOS, a dialog systematically appears asking to give localhost the permission to access microphone.

On Android we have the method androidOnPermissionRequest that intercepts the permission request, so the annoying popup doesn't appear. 

I would like to have a similar method on iOS, otherwise the user will have to see the dialog and accept it any time getUserMedia is called.

Thank you very much!

**Comment by pichillilorenzo** [comment]
There is no equivalent official native API for iOS unfortunately.
However, it seems that native iOS WKWebView is having this problem, check:
- https://developer.apple.com/forums/thread/669011
- https://bugs.webkit.org/show_bug.cgi?id=220416

So, it’s the Apple iOS team that should fix this problem.
