### ISSUE TITLE
Flutter InAppWebView Plugin Crashing Issue

### ISSUE THREAD

**Issue by umerbutt03** [pichillilorenzo/flutter_inappwebview#623]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         1.22.5      |
| Plugin version       |          ^4.0.0+4     |
| Android version      |         10      |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
Hi, I’m using your Flutter InAppWebView Plugin. I integrate this plugin in my app, to show reports in web view. When I use edit text field in web view, keyboard opens and, than web view is not to be closed.
**Current behavior:** 
Hi, I’m using your Flutter InAppWebView Plugin. I integrate this plugin in my app, to show reports in web view. When I use edit text field in web view, keyboard opens and, than web view closed. This issue isn't happening only in the separate web view project. Please kindly check this issue.
## Steps to reproduce

Container(
          height: double.infinity,
          child: Column(children: <Widget>[
            Expanded(
                child: InAppWebView(
              initialUrl: reportUrl,
              initialOptions: InAppWebViewGroupOptions(
                crossPlatform: InAppWebViewOptions(
                  debuggingEnabled: true,
                  useOnDownloadStart: true,
                ),
              ),
              onWebViewCreated: (InAppWebViewController controller) {
                _webViewController = controller;
              },
              onDownloadStart: (controller, url) async {
                print("onDownloadStart $url");
                Downloader.download(url, "Report", ".pdf");
                Toast.show("Report Downloading Starts!", context,
                    duration: Toast.LENGTH_LONG, gravity: Toast.BOTTOM);
              },
            ))
          ])),

## Stacktrace/Logcat   
E/InputMethodManager(22808): b/117267690: Failed to get fallback IMM with expected displayId=103 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{37dba2d VFEDHVCL. .F...... 0,0-1080,1812}

**Comment by ycv005** [comment]
Try with the updated version- 5.0.0, only available on github repo.
```
  flutter_inappwebview:
      git:
        url: https://github.com/pichillilorenzo/flutter_inappwebview.git
        ref: master
```

**Comment by umerbutt03** [comment]
>         url: https://github.com/pichillilorenzo/flutter_inappwebview.git
>         ref: master

Issue resolved, when i called webviewer screen in setState() then issue occurs

**Comment by MathiasTP** [comment]
My webview still crashes when calling close() function. 

Im using 
flutter_inappwebview:
      git:
        url: https://github.com/pichillilorenzo/flutter_inappwebview.git
        ref: master

**Comment by umerbutt03** [comment]
> My webview still crashes when calling close() function.
> 
> Im using
> flutter_inappwebview:
> git:
> url: https://github.com/pichillilorenzo/flutter_inappwebview.git
> ref: master

after close() which thing want yo to do next. 
Otherwise use 'Navigator.of(context).pop();' instead of close()
