### ISSUE TITLE
Loading local asset

### ISSUE THREAD

**Issue by gfiury** [pichillilorenzo/flutter_inappwebview#625]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      1.22.4         |
| Plugin version       |      4.0.0+4         |
| Android version      |    10           |
| iOS version          |               |
| Xcode version        |               |

## Description

**Expected behavior:** 
The image is in the assets folder, the image should be loaded from the path `img/ralph.jpg`.

```
assets:
 -assets/img/ralph.jpg

<img src="img/ralph.jpg" width="300px" />
```

**Current behavior:** 
I'm trying to load an image from the assets folder but I can't make it work. I checked the other issue https://github.com/pichillilorenzo/flutter_inappwebview/issues/425 but no result.
I have another image with a src referencing a link and it works.

What am I missing?

## Steps to reproduce

I made an example on my git [weblocalassets](https://github.com/gfiury/weblocalassets)

I've been testing and it seems (I do not for sure), the assets are loaded if you use the `InitialFile `and not for `InitialData` property.

Is there a way to load the assets using InitialData? perhaps using a keyword?

Thanks

**Comment by nietsmmar** [comment]
I am having the same problem. Has anyone a solution for this?
