### ISSUE TITLE
WebRTC in iOS 14.3 is not working

### ISSUE THREAD

**Issue by Faiizii** [pichillilorenzo/flutter_inappwebview#627]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 1.22.5 stable channel              |
| Plugin version       |       4.0.0+4        |
| Android version      |               |
| iOS version          |       14.3        |
| Xcode version        |      12.3         |

Device information: 

## Description

**Expected behavior:** 
Create the call as it is doing in https://webrtc.github.io/test-pages/src/iframe-apprtc/ and the app is perfectly working in android as expected. 
**Current behavior:** 
But the web view is saying the unable to get access of user media and unable to create RTC peer connection.  
## Steps to reproduce

```
InAppWebView( 
                initialUrl: callUrl,
                initialOptions: InAppWebViewGroupOptions(
                  crossPlatform: InAppWebViewOptions(
                      mediaPlaybackRequiresUserGesture: false,
                      debuggingEnabled: true,
                      clearCache: true,
                      javaScriptEnabled: true,
                      preferredContentMode: UserPreferredContentMode.MOBILE
                  ),
                ),
                onWebViewCreated: (InAppWebViewController controller) {
                  //web view created
                },
                androidOnPermissionRequest: (InAppWebViewController controller, String origin, List<String> resources) async {
                  print('resource list : ${resources.toString()}'); // allready allowed the camera and microphone permission
                  return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
                }
            )
```

**Comment by pichillilorenzo** [comment]
Please see my comment here on how to setup WebRTC on iOS 14.3+ https://github.com/pichillilorenzo/flutter_inappwebview/issues/200#issuecomment-772393262
