### ISSUE TITLE
Support Web ServiceWorker Cache

### ISSUE THREAD

**Issue by chavesgu** [pichillilorenzo/flutter_inappwebview#629]
## Environment

**Flutter version:1.22
**Plugin version:**  4.0.0  
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** Support Web ServiceWorker Cache

**Comment by StarMonk** [comment]
+1

**Comment by pichillilorenzo** [comment]
For Service Worker API, please refer to https://inappwebview.dev/docs/service-worker-api/
