### ISSUE TITLE
Failed to find Platform SDK with path: platforms;android-30

### ISSUE THREAD

**Issue by miladjalalli** [pichillilorenzo/flutter_inappwebview#632]
i gave this error and can't use this library :\

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to find Platform SDK with path: platforms;android-30

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
Exception: Gradle task assembleDebug failed with exit code 1

please help me
thanks

**Comment by miladjalalli** [comment]
solved by download android-30 platform

**Comment by jefferson-guilherme-machado-barreto** [comment]
Hello,

 I need use platform;android-30 and i install the api level 30 in android studio but i have the error:
 
 Failed to find Platform SDK with path: platforms;android-29

**Comment by jefferson-guilherme-machado-barreto** [comment]
I solved, I change android-targetSdkVersion to 30 in my config.xml

**Comment by yassabadr4** [comment]
I solved by download android 31 platform

**Comment by lj5600** [comment]
* What went wrong:
Could not determine the dependencies of task ':cashfree_pg:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-30

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 25s
Exception: Gradle task assembleDebug failed with exit code 1
