### ISSUE TITLE
Help Needed: How to extract an Embedded Resource and save as a file.

### ISSUE THREAD

**Issue by albatrosify** [pichillilorenzo/flutter_inappwebview#635]
Hello,

I need to extract an embedded pdf file, and save it as a local file. This has to be done, because of problems with keeping the session alive, in another client, that could download the resource.
Is there any way to access the Cache and extract the file from there? The filename is known - it can be extracted from the HTML Body where the file is embedded.

**Comment by pichillilorenzo** [comment]
No there is no API to access cached files.
You can probably do this injecting JavaScript code or downloading it from the server itself if you know the file url.
