### ISSUE TITLE
Inappwebview Samsung tablet - When connected using bluetooth mouse webview screen not clickable

### ISSUE THREAD

**Issue by HemantSandbhor** [pichillilorenzo/flutter_inappwebview#636]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        1.22.4  & Dart 2.10.4        |
| Plugin version       |          ^4.0.0+4     |
| Android version      |  Samsung Tablet 10             |
| iOS version          |               |
| Xcode version        |               |

Device information:  Samsung tablet 
Samsung Galaxy Tab S5e
Samsung Galaxy Tab 6S

## Description
InAppWebView screen not listen to click event when connected using bluetooth mouse using Android Samsung Tablet Dex and normal mode.
Same InAppWebView  and impl. listen to click event when screen touch used. 

Device Used  -  Samsung Tablet DEX mode and Normal Mode with Android 10 

**Expected behavior:** 
In App Webview screen should listen to click of mouse connected to Tablet device 

**Current behavior:** 
Screen not allowing to click anywhere in web page rendered in webview

**Comment by HemantSandbhor** [comment]
can some one please suggest solution around this issue

**Comment by pichillilorenzo** [comment]
Please, try to use the new latest version of the plugin and set the `useHybridComposition: true` Android-specific `InAppWebView` option.

**Comment by HemantSandbhor** [comment]
Thanks @pichillilorenzo, We are checking by adding property .

**Comment by HemantSandbhor** [comment]
Thanks, the issue has been resolved.
