### ISSUE TITLE
load webview with local file but not assets

### ISSUE THREAD

**Issue by chavesgu** [pichillilorenzo/flutter_inappwebview#648]
## Environment

**Flutter version:** stable 1.22.5
**Plugin version:** git master
**Android version:**  8
**iOS version:** 14
**Xcode version:**  12.3
**Device information:**  XIAOMI 6

## Description

**What you'd like to happen:** 
load webview with local file but not assets
**Code:** 
```dart
Directory tempDir = Directory.systemTemp ?? await getTemporaryDirectory();
String tempPath = tempDir.path + '/webview/download-demo.html';
try {
  await Service.download("https://www.example.com/demo.html", tempPath);
  print(tempPath);
  // how to use tempPath load webview
} catch (e) {
  print(e);
}
```

**Comment by ggirotto** [comment]
Can't you just use `initialUrl: 'file:///${FILE_URL}',`?

**Comment by chavesgu** [comment]
@chavesgu   thanks,  it's work when i add `file://$tempPath `
