### ISSUE TITLE
cant reload webview when phone come back from offline to online

### ISSUE THREAD

**Issue by PawelSzymanski89** [pichillilorenzo/flutter_inappwebview#650]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  1.22.5              |
| Plugin version       |  4.0.0+4             |
| Android version      |               |
| iOS version          |14.3               |
| Xcode version        |               |

Device information: 
iphone 12 pro max (simulator)
## Description

**Expected behavior:** 
when phone have a break connection after call loadUrl  we have exception with code -1009 in onLoadError method, than i want wait some time and call reload to load url again 

**Current behavior:** 

but even phone come back online, library still return -1009

![Zrzut ekranu 2021-01-21 o 14 51 14](https://user-images.githubusercontent.com/26041449/105359784-21156780-5bf8-11eb-88a4-2a35d56294b1.png)

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by Trend74X** [comment]
so there isnt a solution yet?

**Comment by otopba** [comment]
Same issue
