### ISSUE TITLE
Android app crashes on long press of input field

### ISSUE THREAD

**Issue by mhdshah** [pichillilorenzo/flutter_inappwebview#657]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by mhdshah** [comment]
In order to fix the issue, I have changed the if condition (value != null) to (!value.equalsIgnoreCase("null")).

<img width="974" alt="Screenshot 2021-01-27 at 6 10 29 PM" src="https://user-images.githubusercontent.com/60740880/105992438-20367700-60cb-11eb-98af-3c875516ac6d.png">
<img width="940" alt="Screenshot 2021-01-27 at 6 09 55 PM" src="https://user-images.githubusercontent.com/60740880/105992458-27f61b80-60cb-11eb-9860-fa32fd314aac.png">

**Comment by MrNinja** [comment]
This ticket may be relate to: 'https://github.com/pichillilorenzo/flutter_inappwebview/issues/527'

**Comment by MrNinja** [comment]
I think it's fixed at: https://github.com/pichillilorenzo/flutter_inappwebview/commit/26e63cedee11a5427012955c63e131b61781ef89
