### ISSUE TITLE
"Uncaught ReferenceError: Android is not defined"

### ISSUE THREAD

**Issue by xylim666** [pichillilorenzo/flutter_inappwebview#659]
Hi, 
My web page is using some native function which work fine if i'm using android native with **webView.addJavascriptInterface(this, "Android");**
On the other hand in flutter_inappwebview i understand we can pass in javascript too but so far i'm using below but it's not working still having the "Uncaught ReferenceError: Android is not defined" error
`onLoadStop: (InAppWebViewController controller, String url) {
  webView = controller;
  controller.evaluateJavascript(source: """
  window.flutter_inappwebview.addJavascriptInterface(new WebAppInterface(this),'Android').then(function(result) {
  console.log(result);
  });
  """);
},`
I have tried researching this but to no avail. Am i using the wrong method?

**Comment by xylim666** [comment]
Hi, all i wanted to do is add webView.addJavascriptInterface(this, "Android") to support some of the Android functionality :(

**Comment by dekkaladiwakar** [comment]
@xylim666  I'm facing the same issue right now. Were you able to solve this problem?
