### ISSUE TITLE
shouldOverrideUrlLoading - Android

### ISSUE THREAD

**Issue by wmcshane** [pichillilorenzo/flutter_inappwebview#66]
I can't seem to get shouldOverrideUrlLoading working on android. I have tested the Example app as well, just to be sure it wasn't my projects setup, however, i see the same issue. 

It works fine on IOS, just not Android. 

I see the following in the console whenever the InAppWebView is present:
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/art     (13736): Attempt to remove non-JNI local reference, dumping thread
W/cr_BindingManager(13736): Cannot call determinedVisibility() - never saw a connection for the pid: 13736

Anyone else experiencing this?

**Comment by AlexV525** [comment]
This might cause by calling JavaScript binding before `onPageFinished` too soon on some lower version on Android, e.g. 6 or 7. A possible solution will be make a post delay when loading the custom scripts on lower version of Android.
https://github.com/pichillilorenzo/flutter_inappwebview/blob/f06bcdf695847a0187a31ab607b2bfe236fb0057/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebViewClient.java#L214

**Comment by AlexV525** [comment]
cc @pichillilorenzo

**Comment by mehmetsukrumumbucoglu** [comment]
I'm getting the same problem on my Samsung Galaxy Note 5. Android version is 7.0 and API level 24. Can anyone solve this problem. I ask for your help.

**Comment by mehmetsukrumumbucoglu** [comment]
cc @pichillilorenzo

**Comment by manuel-plavsic** [comment]
cc @pichillilorenzo

**Comment by manuel-plavsic** [comment]
I managed to get it to work. I hadn't thoroughly read the documentation. After setting `useShouldOverrideUrlLoading: true` inside `InAppWebViewSettings`, the callback gets called. However, I think you can leave out this setting: if `shouldOverrideUrlLoading` is set, then  `useShouldOverrideUrlLoading` should be inferred automatically to true in the parts of the plugin where this boolean is needed. Otherwise, `shouldOverrideUrlLoading` is null (and therefore `useShouldOverrideUrlLoading` is false). I think that the same applies for `onCreateWindow` and `supportMultipleWindows`, and other callback-setting pairs.

**Comment by pichillilorenzo** [comment]
@manuel-plavsic thanks for the idea! I will add this logic in the `6.x.x` version.

**Comment by pichillilorenzo** [comment]
@manuel-plavsic Released new version `6.0.0-beta.15` with this "feature":
- Automatically infer `useShouldOverrideUrlLoading`, `useOnLoadResource`, `useOnDownloadStart`, `useShouldInterceptAjaxRequest`, `useShouldInterceptFetchRequest`, `useShouldInterceptRequest`, `useOnRenderProcessGone`, `useOnNavigationResponse` settings if their value is `null` and the corresponding event is implemented by the WebView (`InAppWebView` and `HeadlessInAppWebView`, not `InAppBrowser`) before it's native initialization

The `supportMultipleWindows`, differently from the "use..." settings like above, is mapping the native WebView setting on Android (https://developer.android.com/reference/android/webkit/WebSettings#setSupportMultipleWindows(boolean)), so I will leave it as it is.

**Comment by manuel-plavsic** [comment]
I tried it, and it works! Thank you for the simpler logic!
