### ISSUE TITLE
Previous & Current Url are same always

### ISSUE THREAD

**Issue by ycv005** [pichillilorenzo/flutter_inappwebview#660]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  1.22.6     |
| Plugin version       |   5.0 (from github)   |
| Android version      |   10  |
| iOS version          |      NA     |
| Xcode version        |    NA     |

Device information: Realme 3 Pro

## Description
Unable to get previous url. I was suppose to compare current and previous url.

**Expected behavior:** 
When I am pressing back button, then I am using WillPopScope to handle back button. Now, in My back button handle, I am getting current url before going back, then I am requesting for previous url after going back. These both url should be same, but they aren't.

**Current behavior:** 
Previous & Current Urls must be different. (If there is any other way let me know.)

## Steps to reproduce

```
 WillPopScope(
      onWillPop: () => _handleBack(context, app),
      child: Scaffold(
        key: _scaffoldKey,
        body: SafeArea(
          top: true,
          child: Stack(
            children: [
              Column(
                children: <Widget>[
                  Expanded(
                    child: InAppWebView(
                    ............
                    ........
```

```
  Future<bool> _handleBack(context, App app, {forceExit: false}) async {
    bool status = await controller.canGoBack();
    if (forceExit) {
      Navigator.of(context).pop();
    } else if (status) {
      setState(() {
        isLoading = !isLoading;
      });
 
<!-- Both should be different but are not different -->

      var oldUrl = await controller.getUrl();
      oldUrl = oldUrl.split('?')[0];

      await controller.goBack();

      var newUrl = await controller.getUrl();
      newUrl = newUrl.split('?')[0];
     
      print("here is url old url- $oldUrl");
      print("here is url new url- $newUrl");

      if (oldUrl.length == newUrl.length && oldUrl == newUrl) {
        print("here onback  both url are same");
      } else {
        print("here onback  both url are not same");
      }
    } else if (widget.windowId != null) {
      Navigator.of(context).pop();
    } else {
      if (getExitToast(context, app.name)) {
        Navigator.of(context).pop();
      }
    }
    return false;
  }
```
Any idea why it is happening @pichillilorenzo @tneotia  Thanks in advance.

**Comment by tneotia** [comment]
I don't recommend doing this way, here's how I do it:
```
String currentUrl = await hpc.webView.getUrl();
print("current $currentUrl");
WebHistory history = await hpc.webView.getCopyBackForwardList();
List<WebHistoryItem> historyList = history.list;
int index = history.currentIndex;
String oldUrl = historyList[index-1].url;
//your logic here
```

**Comment by pichillilorenzo** [comment]
`goBack` method doesn't change the current URL of the WebView instantly.
That doesn't depend on the plugin itself but on how WebView works.

If you put a little delay between the two `getUrl` method calls, you will see that it changed, for example:
```dart
print(await controller.getUrl()); // before goBack
await controller.goBack();
await Future.delayed(Duration(seconds: 1));
print(await controller.getUrl()); // after goBack
```

I think the best way to do what you want to do is as suggests by @tneotia. Thanks!
