### ISSUE TITLE
Could flutter provide the future "isDirectionalLockEnabled"

### ISSUE THREAD

**Issue by zhihuitang** [pichillilorenzo/flutter_inappwebview#662]
## Android and iOS

**Flutter version:** 
**Plugin version:**  4.0.0

## Description
In iOS WKWebview there is a property [isDirectionalLockEnabled](https://developer.apple.com/documentation/uikit/uiscrollview/1619390-isdirectionallockenabled), it is a Boolean value that determines whether scrolling is disabled in a particular direction.

>If this property is false, scrolling is permitted in both horizontal and vertical directions. If this property is true and the user begins dragging in one general direction (horizontally or vertically), the scroll view disables scrolling in the other direction. If the drag direction is diagonal, then scrolling will not be locked and the user can drag in any direction until the drag completes. The default value is false

Could flutter have this feature?

**Comment by pichillilorenzo** [comment]
It will be available within the next release using `IOSInAppWebViewOptions. isDirectionalLockEnabled`.
