### ISSUE TITLE
InAppWebView Cross-platform options not has allowUniversalAccessFromFileURLs

### ISSUE THREAD

**Issue by Anima18** [pichillilorenzo/flutter_inappwebview#663]
## Environment

**Flutter version: 1.22.5 • channel stable
**Plugin version: 52.2.1
**Android version: 29
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

in flutter_inappwebview: ^4.0.0+4 
InAppWebView Cross-platform options not has allowUniversalAccessFromFileURLs， but InAppWebView Android-specific options has。

**Comment by pichillilorenzo** [comment]
As you can read here [API Reference](https://github.com/pichillilorenzo/flutter_inappwebview#api-reference), the current `README.md` file shows only a part of the documentation that conforms to the **master branch** only!
If you need the API reference for 4.0.0+4, go to https://pub.dev/packages/flutter_inappwebview or switch the branch of this repository to v4.0.0+4 (that is https://github.com/pichillilorenzo/flutter_inappwebview/tree/v4.0.0+4)

**Comment by Anima18** [comment]
> As you can read here [API Reference](https://github.com/pichillilorenzo/flutter_inappwebview#api-reference), the current `README.md` file shows only a part of the documentation that conforms to the **master branch** only!
> If you need the API reference for 4.0.0+4, go to https://pub.dev/packages/flutter_inappwebview or switch the branch of this repository to v4.0.0+4 (that is https://github.com/pichillilorenzo/flutter_inappwebview/tree/v4.0.0+4)

if i want to use allowUniversalAccessFromFileURLs in Cross-platform, just wait for you to release the new version.
