### ISSUE TITLE
InAppBrowserActivity.onCreate NullPointerException - Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by ycv005** [pichillilorenzo/flutter_inappwebview#665]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  1.22.5  |
| Plugin version       |  5.0 (mater branch from github)   |
| Android version      |  8.1.0 |
| iOS version          |   NA      |
| Xcode version        |    NA     |

Device information: 

## Description
App got crash while running the app.

**Expected behavior:** 
App shouldn't be crash.

**Current behavior:** 

Here is the log from the Firebase Crashlytics- 

**HIGHLIGHTED ERROR**

```
InAppBrowserActivity.java line 16
com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.onCreate
```

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.example.app/com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2778)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.onCreate (InAppBrowserActivity.java:16)
android.app.Activity.performCreate (Activity.java:7009)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
```

```
ChromeCustomTabsActivity.java line 18
com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity.onCreate
```

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.example.app/com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2778)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity.onCreate (ChromeCustomTabsActivity.java:18)
android.app.Activity.performCreate (Activity.java:7009)
android.app.Activity.performCreate (Activity.java:7000)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2731)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2856)
android.app.ActivityThread.-wrap11 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1589)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6494)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
```

If you need more info let me know.

@pichillilorenzo please fix it before next release of the plugin. Highly appreciated for the fix

**Comment by slorop41314** [comment]
Same issue here

**Comment by pichillilorenzo** [comment]
@slorop41314 Are you using the latest version available from pub.dev? could you post the error logs here?

**Comment by ycv005** [comment]
Plugin version- `flutter_inappwebview: ^5.1.0+4`
Flutter version- 2.0.1

@pichillilorenzo Hey, I found again a crash on firebase with latest version of the plugin, pleasee have a look at it, if needed, I will share more info from crashlytics

![image](https://user-images.githubusercontent.com/26734819/110573512-64646f00-8181-11eb-8502-f7684b670fc5.png)

**Comment by pichillilorenzo** [comment]
@ycv005 Ok I checked that line of code but it doesn't make any sense to me. It's very strange.
It refers to the `Bundle` instance used to pass arguments to the `InAppBrowser` Android Activity when it's started/opened.
It's impossible that it's `null` because when the `InAppBrowser` Android Activity it's started, it always contains `Bundle` data (see `InAppBrowserManager.open` method in the Java native code), otherwise the `InAppBrowser` won't work properly.
One thing I can think of is that the `InAppBrowserActivity.onCreate` is called twice, but there is already a check for that.
How do you use `InAppBrowser` on your Application? Do you use `hide` and `show` methods?
Do you have some reproducible steps? Thanks

**Comment by ycv005** [comment]
I have only used `InAppWebView` widget in my tree. I haven't implemented InAppBrowser and either of their methods. No, I am not calling from Java native code or from flutter.

**Comment by pichillilorenzo** [comment]
You can try new version 5.2.0

**Comment by dkunkic** [comment]
@pichillilorenzo Hi, I have a similar crash on firebase.  Upgrading the version didn’t change anything.  Can you please have a look at the issue.
<img width="1247" alt="Screenshot 2021-04-14 at 11 40 09" src="https://user-images.githubusercontent.com/13023358/114691330-d9463e00-9d17-11eb-80ab-a3ad1d1e8990.png">

Plugin version - flutter_inappwebview: 5.3.0
Flutter version - 2.0.3

**Comment by pichillilorenzo** [comment]
@dkunkic This is another issue related to the `ChromeSafariBrowser` class, please open a new issue and don't comment on different issues.
Also, post the full crash logs and not just a screenshot and a code example that can replicate this issue, otherwise it's impossible to me to help you. Thanks

**Comment by ZimmerZhou** [comment]
This can be reproduced by starting InAppBrowserActivity by shell，It may happen in automated testing

**Comment by pichillilorenzo** [comment]
@ZimmerZhou I have automated integration tests and these errors don't occur at all. Could you elaborate more? Make a reproducible example with steps, please.

**Comment by ZimmerZhou** [comment]
> @ZimmerZhou I have automated integration tests and these errors don't occur at all. Could you elaborate more? Make a reproducible example with steps, please.

Simply run "adb shell am start -n YOUR_PACKAGE_NAME/com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity",BTW,You need to set "exported = true" with InAppBrowserActivity，or you will get a permission error.

**Comment by pichillilorenzo** [comment]
Well, that's correct. You cannot simply start that activity like this. You **MUST** use the API of this plugin otherwise it won't work and you will have a null pointer exception, that is the correct behavior because if you start it this way, the `InAppBrowserActivity` will not have the right bundle data to make it work properly.
So, calling the activity in that way is not correct.

**Comment by ZimmerZhou** [comment]
> @ZimmerZhou Well, that's correct. You cannot simply start that activity like this. You **MUST** use the API of this plugin otherwise it won't work and you will have a null pointer exception, that is the correct behavior because if you start it this way, the `InAppBrowserActivity` will not have the right bundle data to make it work properly.
> So, calling the activity in that way is not correct.

I agree, but what if we can prevent exception by just adding a toast and finishing activity?

**Comment by pichillilorenzo** [comment]
Nope, if a null pointer exception is occurring, that's the correct behavior and that means you are doing something that is not correct, such as the example you made above. So, in that case, required bundle data is missing to make that activity work properly.
If you are receiving this error from your Dart/Flutter code, please post the code you are using, otherwise, I cannot help you more than this.

**Comment by niypoo** [comment]
Same issue with me , 
happened many times with different users ,

<img width="1038" alt="Screen Shot 2021-05-16 at 7 53 08 PM" src="https://user-images.githubusercontent.com/13227239/118407269-57cc2d80-b680-11eb-8c2a-49a36c53d134.png">

**Comment by Super-Bin** [comment]
Plugin version- flutter_inappwebview: ^5.3.2
Flutter version- 2.0.1
@pichillilorenzo   Hi, I have a similar crash on firebase.  Upgrading the version didn’t change anything.  Can you please have a look at the issue.

![WX20210811-145622](https://user-images.githubusercontent.com/26457469/128984213-fb7c9c98-1a36-4879-85e6-341ef4306925.png)

**Comment by nietsmmar** [comment]
I got the same error! :( With  lib verison ^5.3.2 and flutter 2.5.3.

Why is this issue closed?

**Comment by kamxy** [comment]
same issue

**Comment by macortesn** [comment]
Same issue :(. any update?

**Comment by pansitwattana** [comment]
I also got this crash error

flutter_inappwebview: ^5.3.2
Flutter version: 2.2.0

**Comment by huangsir0** [comment]
same issue

**Comment by nietsmmar** [comment]
same issue

**Comment by mkucharski17** [comment]
Same issue

**Comment by lore-co** [comment]
The issue is still present
