### ISSUE TITLE
在android 10手机上加载会闪屏?请问如何解决

### ISSUE THREAD

**Issue by BoyYangyang** [pichillilorenzo/flutter_inappwebview#666]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by ailiwean** [comment]
Also, especially when the height of the pop-up hidden soft keyboard changes

**Comment by liuhong1happy** [comment]
+1

**Comment by pichillilorenzo** [comment]
It should be fixed with version 5.0.0 on Android and `useHybridComposition: true` option.
