### ISSUE TITLE
Css and JS not working with basic auth

### ISSUE THREAD

**Issue by deathland09** [pichillilorenzo/flutter_inappwebview#667]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology               | Version       |
| -------------------- | ------------- |
| Flutter version           | 1.22.6 |
| Plugin version           | ^4.0.0+4 |
| Android version      | 29.0.3 |
| iOS version          | Iphone 12 Pro Max|
| Xcode version        | 12.4 |

## Description

**Expected behavior:** 
I want using webview with basic auth.
**Current behavior:** 
Now it don't load js and css when i using webview. It working with native code (swift). Even though I used the function onReceivedHttpAuthRequest (same in native code)

**Comment by deathland09** [comment]
So sorry, it was problem with server side.

**Comment by EArminjon** [comment]
@deathland09 Hi, Do you want more information, we have the same issue arround iOS and maybe server side
