### ISSUE TITLE
Flutter InAppWebView how to disable cross origin policy?

### ISSUE THREAD

**Issue by FRsyesCD** [pichillilorenzo/flutter_inappwebview#669]
hello everyone 

I'm using InAppWebView to make a video downloader app by listening to onLoadResource even and grab the video played by the user and ofc the video inside an iframe and because of cross origin policy i can't get the url inside iframe (.mp4,.m3u8......), i did set allowUniversalAccessFromFileURLs and allowFileAccessFromFileURLs to true but no result i can't get the resources the iframe called :/, this is my initialoptions : 

initialOptions: InAppWebViewGroupOptions(
                  android: AndroidInAppWebViewOptions(
                    supportMultipleWindows: true,
                    offscreenPreRaster: true,
                    allowUniversalAccessFromFileURLs: true,
                    allowFileAccessFromFileURLs: true,
                  ),
                  crossPlatform: InAppWebViewOptions(
                    useOnLoadResource: true,
                    debuggingEnabled: true,
                    userAgent:
                        "Mozilla/5.0 (Linux; Android 9; Redmi Note 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Mobile Safari/537.36",
                    javaScriptEnabled: true,
                    javaScriptCanOpenWindowsAutomatically: true,
                  )),

if anyone very familiar with inappwebview or flutter would tell me how to disable the cross origin policy in flutter or how to listen to my app http requests without using a proxy ... , i'll be grateful

**Comment by pichillilorenzo** [comment]
It's not possible to disable the cross origin policy.
Options `allowUniversalAccessFromFileURLs` and `allowFileAccessFromFileURLs` are related to local files.

Probably, to get the resources of an iFrame on Android, you can use the `androidShouldInterceptRequest` event.
To use this event, the `useShouldInterceptRequest` android-specific option must be `true`.
