### ISSUE TITLE
Can't switch Microsoft SwiftKey from alphabet layout to numbers/symbols layout 

### ISSUE THREAD

**Issue by thearaks** [pichillilorenzo/flutter_inappwebview#672]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       1.22.6        |
| Plugin version       |       4.0.0+4        |
| Android version      |       9.0        |
| iOS version          |       -        |
| Xcode version        |       -        |

Honor 9 (Huawei STF-L09)
But any Android phone using Microsoft SwiftKey seems to have this issue.

## Description

Microsoft SwiftKey gets closed and re-opened when tying to switch its layout from alphabet to numbers/symbols.

<img src="https://user-images.githubusercontent.com/5188791/107201617-7ffd1e00-69f9-11eb-987a-ffef11a612aa.gif" width="360">

**Expected behavior:** 

Changing the virtual keyboard layout from alphabet to number/symbols shouldn't close the virtual keyboard.

## Steps to reproduce

1. Configure SwiftKey as your IME
2. Open a web page with a text input field
3. Select the input field, try to switch SwiftKey layout to input some symbols
4. SwiftKey loses the input field focus while changing layout, causing the web view to close the keyboard (since the field has lost focus) making it impossibile to switch keyboard layout, but the field is immediately re-focused and the keyboard gets re-opened on the alphabet layout

**Comment by pichillilorenzo** [comment]
This should be fixed with the new version 5.0.0 using the android-specific option `useHybridComposition: true` (see [Hybrid-Composition#performance](https://github.com/flutter/flutter/wiki/Hybrid-Composition#performance)).

**Comment by thearaks** [comment]
Grazie Lorenzo,
The new version 5.0.0 requires null safety?
This means I need to migrate my app first to null safety to be able to use the new version, right?

Thank you for you work and your support!

**Comment by pichillilorenzo** [comment]
Ciao Mattia!
Yes, it requires null safety.
You can change the flutter channel, for example, to dev channel and run `flutter upgrade`.
You don't need to migrate your app to null safety because you can build and run it using the flag `--no-sound-null-safety`, but I recommend you migrate it 👍

**Comment by ModernChocolate** [comment]
It is still not working... (using in_app_webview 5.3.2)

**Comment by pichillilorenzo** [comment]
@ModernChocolate if you need help, post the code you are using and don’t add comments that aren’t useful.

**Comment by ModernChocolate** [comment]
Yes, sorry I just needed to restart my app.
