### ISSUE TITLE
Detect Scrolling and Hide Bottom Navigation widget 

### ISSUE THREAD

**Issue by ycv005** [pichillilorenzo/flutter_inappwebview#673]
## Environment

**Flutter version: 1.22.6** 
**Plugin version: 5.0.0 (from github master)**    
**Android version: 10**    
**iOS version: NA**
**Xcode version: NA**  
**Device information: Realme 3 pro**    

## Description

**What you'd like to happen:** 
To Detect the scrolling of the webview by the user to trigger some events like hiding Bottom Navigation widget or fire some event.

**Alternatives you've considered: Didn't have any into my knowledge**   

**Images: NA**   

@pichillilorenzo @tneotia Any suggestions ? Thanks for the response.

**Comment by tneotia** [comment]
https://stackoverflow.com/questions/54219987/webview-customscrollview-floating-appbar

It's possible but doesn't work very well

**Comment by ycv005** [comment]
Hey buddy, thanks for sharing. I have tried this, but didn't happy with result.

**Comment by tneotia** [comment]
Yeah it's not very good, the other solution is to use JS onScroll function and then console.log when that happens so you know the webview was scrolled. 

I did it before and it works but I don't have any example.
