### ISSUE TITLE
Can not run example on latest stable channel

### ISSUE THREAD

**Issue by vankhoa01** [pichillilorenzo/flutter_inappwebview#674]
Hi my friends, I can not run example on latest stable channel.
Please help me if you have nay solution for this issue
Thank a lot
<img width="543" alt="Screen Shot 2021-02-09 at 16 24 09" src="https://user-images.githubusercontent.com/8953129/107342795-3e509e00-6af3-11eb-94ea-35004c3e8f02.png">

**Comment by pichillilorenzo** [comment]
It requires dart null safety support that stable channel doesn't have yet.
Use for example the dev channel
