### ISSUE TITLE
I got this error when clicking the download link, tell me how to fix this, please!!!!

### ISSUE THREAD

**Issue by harshasuraweera** [pichillilorenzo/flutter_inappwebview#676]
**I got this error when clicking the download link, tell me how to fix this, please!!!!**

**Here is the console log**

I/flutter ( 9448): onDownloadStart https://courseweb.sliit.lk/pluginfile.php/49/mod_forum/attachment/32848/SLIIT%20Covid19%20Reminder%20Students%20-%20Jan%202021.pdf
E/flutter ( 9448): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 73 pos 12: '_initialized': FlutterDownloader.initialize() must be called first
E/flutter ( 9448): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 9448): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 9448): #2      FlutterDownloader.enqueue (package:flutter_downloader/src/downloader.dart:73:12)
E/flutter ( 9448): #3      _MyIndexPage.build.<anonymous closure> (package:am_sliit/index.dart:366:61)

**Comment by pichillilorenzo** [comment]
This is not related to my plugin.. As you can see it is related to `flutter_downloader` plugin.
However, as you can see from the error, you should call `FlutterDownloader.initialize()` before you use it. Probably in your `main` function (see https://pub.dev/packages/flutter_downloader#usage).

**Comment by harshasuraweera** [comment]
> This is not related to my plugin.. As you can see it is related to `flutter_downloader` plugin.
> However, as you can see from the error, you should call `FlutterDownloader.initialize()` before you use it. Probably in your `main` function (see https://pub.dev/packages/flutter_downloader#usage).

I did that already. But did not working. thanks for the quick response 😊

**Comment by beevekmgr** [comment]
> > This is not related to my plugin.. As you can see it is related to `flutter_downloader` plugin.
> > However, as you can see from the error, you should call `FlutterDownloader.initialize()` before you use it. Probably in your `main` function (see https://pub.dev/packages/flutter_downloader#usage).
> 
> I did that already. But did not working. thanks for the quick response 😊

how you solve it.. I am getting same error though this is not related to this package.. just asking quick question
