### ISSUE TITLE
Android 10 clipboard not working properly

### ISSUE THREAD

**Issue by armadastate** [pichillilorenzo/flutter_inappwebview#678]
## Environment

| Technology           | Version       |
| -------------------- | -------------|
| Flutter version       |        1.22.6   |
| Plugin version       |      4.0.0+4   |
| Android version    |       10          |

Device information: Pixel 2

## Description

Try run simple code and check next steps:
 1. Run app, wait for google.com is loaded
 2. Go to other app where you can copy some text to your clipboard
 3. Try paste it to test app in google search
 In this flow you will have nothing(

Check 2:
 1. Open some app and copy some text to clipboard
 2. Run test app, and try paste text from clipboard to goole search - yeah, this working fine
 3. Switch by RecentApps to app with text, copy some other text to clipboard
 4. Switch back to test app, try paste = you will see old text (clipboard is not updating on android 10)

After few hours spend to research module I found a little bit "hacky" way to fix this:
in file
{FLUTTER_SDK}\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-4.0.0+4\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\InAppWebView\InAppWebView.java

add 
onWindowFocusChanged(true); 
at rebuildActionMode() function begin:

like this:
```
  public ActionMode rebuildActionMode(
          final ActionMode actionMode,
          final ActionMode.Callback callback
  ) {
    onWindowFocusChanged(true);
    boolean hasBeenRemovedAndRebuilt = false;
```

so chrome WebView will be notified for FocusChanged and will update data from clipboard

P.S. this is fast solution and not pretty good for use, but I need working WebView, maybe someone need too |\./|

**Comment by pichillilorenzo** [comment]
Thanks, this way it will resolve the problem!
Maybe it could be this:
```java
onWindowFocusChanged(isFocused());
```
I'm going to add this fix with the next commit.

**Comment by armadastate** [comment]
I'm newbie in flutter, and not fully understand view managment. But I see  containerView, and I think this can be a solution:
`onWindowFocusChanged( (containerView!=null)?containerView.isFocused() : true);`

**Comment by pichillilorenzo** [comment]
yeah it seems good! thanks!

**Comment by callmejm** [comment]
version 5.3.2, I still facing this issue

**Comment by DurgeshSawantWYLD** [comment]
Currently using flutter_inappwebview: ^5.7.2+3 
it threw the following exception
{message: Uncaught (in promise) NotAllowedError: Write permission denied., messageLevel: 3}

Please help
