### ISSUE TITLE
Problem when informing time in the form of a website through webview in the flutter

### ISSUE THREAD

**Issue by lucas-livingnet** [pichillilorenzo/flutter_inappwebview#680]
Accessing a form via webview flutter I have problems when making an appointment in a field.
By clicking on the hour field the window below is shown:
enter image description here
![Captura de Tela 2021-02-12 às 11 29 39](https://user-images.githubusercontent.com/62895141/107800849-13a65580-6d3e-11eb-98ed-61041bfddc36.png)

If you modify the hours using the plus or minus buttons and then click on set everything works.
Now if I try to change the time using the keyboard, the time is lost.
I tried with the plugin below and I have the same behavior:
flutter_inappwebview: ^ 4.0.0 + 4
I thought about defining only material or cupertino to see if the behavior changes, but I'm still not sure of the result.
Does anyone have a suggestion?

**Comment by pichillilorenzo** [comment]
Here is my answer on StackOverflow https://stackoverflow.com/a/66447271/4637638.
You should try the latest version of the plugin
