### ISSUE TITLE
webview long press event is fired when I tap flutter widget on Webview 

### ISSUE THREAD

**Issue by hwikang** [pichillilorenzo/flutter_inappwebview#684]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        1.22.5       |
| Plugin version       |        ^4.0.0+4       |
| Android version      |               |
| iOS version          |        14.4       |
| Xcode version        |        12.4       |

Device information: 

## Description

**Expected behavior:** 

I am using a stack for showing buttons on webview.
and there is a function when user longpress webview.
But the longpress event is fired when I click button(or whatever flutter widget) 

I want nothing happen when I click flutter widget on webview
**Current behavior:** 

 long press event is fired when I click Flutter widget on webview

## Steps to reproduce

```dart
 Stack(
            children: [
              InAppWebView(
                    initialUrl: "https://dev-codesketch.luxrobo.com",
              ),
              Container(
                child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      _buildOutButtons(context),
                      _buildFunctionButtons(context),
                    ]),
              ),
             
            ],
          ),
```

**Comment by pichillilorenzo** [comment]
I tried to debug it but I cannot resolve it. It seems there are issues with Flutter PlatformView and iOS WKWebView.
See:
- https://github.com/flutter/flutter/issues/50420
- https://github.com/flutter/flutter/issues/53490
