### ISSUE TITLE
issue on xcode 12.x

### ISSUE THREAD

**Issue by lyf571321556** [pichillilorenzo/flutter_inappwebview#686]
compile in xcode 12.x post a issue:

 /Users/liuyanfeng/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: warning: coercion of implicitly unwrappable value of type 'InAppWebView_IBWrapper?' to 'Any' does not unwrap optional
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
    /Users/liuyanfeng/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:26:19: note: implicitly unwrapped property 'containerWebView' declared here
        @IBOutlet var containerWebView: InAppWebView_IBWrapper!
                      ^
    /Users/liuyanfeng/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: note: provide a default value to avoid this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                       ?? <#default value#>
    /Users/liuyanfeng/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: note: force-unwrap the value to avoid this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                      !
    /Users/liuyanfeng/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-4.0.0+4/ios/Classes/InAppBrowserWebViewController.swift:388:19: note: explicitly cast to 'Any' with 'as Any' to silence this warning
                print(containerWebView)
                      ^~~~~~~~~~~~~~~~
                                       as Any
    ../../.pub-cache/hosted/pub.flutter-io.cn/extended_nested_scroll_view-0.4.0/lib/src/old_extended_nested_scroll_view.dart:1069:7: Error: The non-abstract class '_NestedScrollPosition' is missing implementations for these members:
     - ScrollPosition.pointerScroll

**Comment by pichillilorenzo** [comment]
They are all warnings, not errors. You can just ignore them.

Instead, the error `Error: The non-abstract class '_NestedScrollPosition' is missing implementations for these members`, as you can see, is not related to my plugin, but to the `extended_nested_scroll_view` package.
