### ISSUE TITLE
Master version: Getting unexpected log which is repeatly so long

### ISSUE THREAD

**Issue by ycv005** [pichillilorenzo/flutter_inappwebview#687]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    1.22.6    |
| Plugin version       |   Master Version  |
| Android version      |   10      |
| iOS version          |       NA        |
| Xcode version        |         NA    |

Device information: 
Realme 3 Pro

## Description

I am geting unexpected log after geting the latest master version (this log is repeatly so long)

```
E/BufferQueueProducer( 1198): [SurfaceTexture-0-1198-3] dequeueBuffer: BufferQueue has been abandoned
```

@pichillilorenzo Please have a look.

**Comment by pichillilorenzo** [comment]
I cannot reproduce these logs with my example code.
However, I think it's related to flutter PlatformView itself and not my plugin.
Try to update your flutter version to master, dev, or beta channels.
Also, could you post here code that causes these logs? Thanks

**Comment by ycv005** [comment]
What flutter version you are using, as I am using latest stable version. (Overview- I was also using this plugin on same page- https://github.com/duyduong/flutter_native_admob)Will you share your mail, I would share private gist.

**Comment by pichillilorenzo** [comment]
I'm using master channel. That's my flutter doctor:
```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.90, on macOS 11.1 20C69 darwin-x64, locale it-IT)
    • Flutter version 1.27.0-5.0.pre.90 at /Users/lorenzopichilli/flutter
    • Framework revision 371dd87aa0 (2 days ago), 2021-02-20 13:11:58 +0100
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lorenzopichilli/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/lorenzopichilli/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/lorenzopichilli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • iPhone di Lorenzo (mobile)         • 00008101-00025D9911B8001E • ios            • iOS 14.4
    • macOS (desktop)                    • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```

You can find my email on my profile page https://github.com/pichillilorenzo 👍

**Comment by Kamoba** [comment]
i got same thing after a long job then when i reload the webView:
```
D/        (26062): Gralloc UnRegister  w:800, h:1136, f:0x1, usage:0xb00, ui64Stamp:81641 line = 2218
D/        (26062): Gralloc UnRegister  w:800, h:1136, f:0x1, usage:0xb00, ui64Stamp:81627 line = 2218
D/        (26062): Gralloc UnRegister  w:800, h:1136, f:0x1, usage:0xb00, ui64Stamp:81609 line = 2218
D/        (26062): Gralloc UnRegister  w:800, h:1136, f:0x1, usage:0x300, ui64Stamp:81765 line = 2218
D/        (26062): Gralloc UnRegister  w:800, h:1136, f:0x1, usage:0x300, ui64Stamp:81599 line = 2218
E/BufferQueueProducer(26062): [SurfaceTexture-0-26062-1] query: BufferQueue has been abandoned
D/        (26062): Gralloc UnRegister  w:800, h:1136, f:0x1, usage:0x300, ui64Stamp:81597 line = 2218
E/BufferQueueProducer(26062): [SurfaceTexture-0-26062-1] cancelBuffer: BufferQueue has been abandoned
```
And this come with black screen, so i have to close the app then reopen.
This is with last Flutter version  2.5.3.

Before update i was geting instead:
```
[ImageReader-1080x1620f1m3-17818-0] Failed to release buffer: Unknown error -1 (1)
```
If coming from PlatformView i do not know how to catch that.
