### ISSUE TITLE
flutter version error: the latest flutter version use dart verion is 2.10.5, but project require dart version is higher

### ISSUE THREAD

**Issue by Refkay** [pichillilorenzo/flutter_inappwebview#689]
![image](https://user-images.githubusercontent.com/19565146/108986730-69c7b100-76cd-11eb-90d3-f766c55d3e44.png)

![image](https://user-images.githubusercontent.com/19565146/108986615-4c92e280-76cd-11eb-9ca2-59d7a2c4ca29.png)

- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
To use the new version 5.0.0 with dart null safety, you need to upgrade your flutter version.
For example, you can use the flutter dev channel.

**Comment by Refkay** [comment]
But the stable Flutter SDK use  2.10.5 version Dart SDK，so I can't compile successfully when use the stable Flutter SDK.

**Comment by pichillilorenzo** [comment]
That's why I'm saying to you that you need to upgrade your flutter version because the stable channel doesn't support dart null safety yet. That's doesn't depend on me but on the Flutter team.
if you want to use the new version 5.0.0, you need to do it, otherwise, you need to use the older version 4.0.0+4.

You can use the dev channel (I don't know if the beta channel support it): `flutter channel dev` and, after that, run `flutter upgrade` (https://flutter.dev/docs/development/tools/sdk/upgrading#switching-flutter-channels).

**Comment by Refkay** [comment]
Thank you very much for your help.
