### ISSUE TITLE
In iOS14， WebViews stop working in some case 。

### ISSUE THREAD

**Issue by Anima18** [pichillilorenzo/flutter_inappwebview#690]
- [√] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [√] I have already searched for the same problem
- [√] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [√] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [√] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  1.27.0-4.0.pre • channel dev             |
| Plugin version       |               |
| Android version      |               |
| iOS version          |      14.5         |
| Xcode version        |   12.5 beta 2            |
| flutter_inappwebview version |   5.0.0-nullsafety.0**            |

## Description
```dart
InAppWebView(
  initialFile: "assets/test.html",
  initialHeaders: {
  },
  onConsoleMessage: (controller, consoleMessage) {
    print(consoleMessage);
  },
  initialOptions: InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
    allowUniversalAccessFromFileURLs: true,
    javaScriptCanOpenWindowsAutomatically: true,
    javaScriptEnabled: true,
    transparentBackground: true,
    horizontalScrollBarEnabled: false,
    verticalScrollBarEnabled: false,
  ),
)
```
**test.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1 style="color: white">Hello World</h1>
</body>
</html>
```

On iOS14 (real machine or emulator), first zoom in on the page, click on an empty space, wait 3 seconds, and then double-click on the space.The WebView has stopped working and cannot scale or receive any interactions.

This problem doesn't exist on Android or iOS12.

## Steps to reproduce

1. Enlarge the test.html page
2. Click elsewhere on the page and wait 3 seconds
3. Double-click anywhere else on the page and the page stops working

## Stacktrace/Logcat   

When the problem occurs, no logs are displayed

**Comment by McPorkChop** [comment]
I have the same issues in my production app。
the reproduce step is easy, just scroll  forth and back。
i try to use WKWebView to present the situation, but WKWebView seems work well.
Use native WkWebView:


https://user-images.githubusercontent.com/10668305/116667960-643d5e80-a9cf-11eb-9e57-df3dd388b884.mp4

**Comment by McPorkChop** [comment]
> I have the same issues in my production app。
> the reproduce step is easy, just scroll forth and back。
> i try to use WKWebView to present the situation, but WKWebView seems work well.
> Use native WkWebView:
> 
>  wkwebview.mp4

in InAppWebView, it's just suddenly not response any gestures in the widget areas.

https://user-images.githubusercontent.com/10668305/117239364-363d9b80-ae61-11eb-9de8-b433523e5d2e.MP4


it's seems like is flutter‘s problem。it reproducted in flutter_webview
