### ISSUE TITLE
[Android] <input type="file"> - no choice: always uses gallery images, no camera

### ISSUE THREAD

**Issue by marcoheine** [pichillilorenzo/flutter_inappwebview#691]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     1.22.6        |
| Plugin version       |     4.0.0+4          |
| Android version      |      10.0         |

## Description

**Expected behavior:** 

`<input type="file"> `
lets me choose between Camera and Gallery.

**Current behavior:** 

Gallery opens always. iOS is working, Android not.

## Steps to reproduce

My input:
`<input type="file" name="photos[]" accept="image/*;capture=camera" id="photoUploader" multiple>`

**Comment by marcoheine** [comment]
worked:

`<input type="file" accept="image/*" capture>`

**Comment by DongNQFinizy** [comment]
@marcoheine how did you enable gallery option on android ? I'm currently use vue input component to open on android webview. It showed 3 options, camera, camera record, and file. How did you have gallery option ? And can i hide camera, and camera record options, and just show file and gallery options ? Thanks you
