### ISSUE TITLE
IProducerListener: malformed binder reply.   !!!!!!!

### ISSUE THREAD

**Issue by 2803404074** [pichillilorenzo/flutter_inappwebview#692]
problem：
（english）
It can load web pages and display them, but it will report an error in the loading process, and then it can't respond to the JavaScript callback method.

（中文）
能够加载网页并且显示，但是加载过程中报错，之后无法响应javascript回调的方法。

设备：vivo X21
targetSdkVersion ：29
minSdkVersion：19

remarks（备注）：这个问题目前只在vivoX21设备上出现，其他手机能正常显示没有错误日志，能够回调javascript的方法。

log:
E/        ( 6265): IProducerListener: malformed binder reply
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden field Landroid/view/View;->mContext:Landroid/content/Context; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
W/utter_build_io( 6265): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
W/cr_media( 6265): Requires BLUETOOTH permission
E/BackgroundFallback( 6265): initVivoBgFallback callstackcom.android.internal.policy.DecorView.<init>:378 com.android.internal.policy.PhoneWindow.generateDecor:2421 com.android.internal.policy.PhoneWindow.installDecor:2800 com.android.internal.policy.PhoneWindow.setContentView:487 com.android.internal.policy.PhoneWindow.setContentView:478 android.app.Dialog.setContentView:603 io.flutter.plugin.platform.SingleViewPresentation.onCreate:204 android.app.Dialog.dispatchOnCreate:442 android.app.Dialog.show:337 android.app.Presentation.show:249 
W/AudioCapabilities( 6265): Unsupported mime audio/adpcm
W/AudioCapabilities( 6265): Unsupported mime audio/x-ms-adpcm
W/AudioCapabilities( 6265): Unsupported mime audio/alac
W/AudioCapabilities( 6265): Unsupported mime audio/ape
W/AudioCapabilities( 6265): Unsupported mime audio/dsd
W/AudioCapabilities( 6265): Unsupported mime audio/mpeg-L1
W/AudioCapabilities( 6265): Unsupported mime audio/mpeg-L2
W/AudioCapabilities( 6265): Unsupported mime audio/pcm
W/AudioCapabilities( 6265): Unsupported mime audio/ra
W/AudioCapabilities( 6265): Unsupported mime audio/x-ms-wma
W/VideoCapabilities( 6265): Unsupported mime video/divx
W/VideoCapabilities( 6265): Unsupported mime video/divx3
W/VideoCapabilities( 6265): Unsupported mime video/divx311
W/VideoCapabilities( 6265): Unsupported mime video/divx4
W/VideoCapabilities( 6265): Unsupported mime video/flv1
W/VideoCapabilities( 6265): Unsupported mime video/x-flv
W/VideoCapabilities( 6265): Unrecognized profile 4 for video/hevc
W/VideoCapabilities( 6265): Unsupported mime video/mjpeg
W/VideoCapabilities( 6265): Unsupported mime video/x-motion-jpeg
W/VideoCapabilities( 6265): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 6265): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 6265): Unsupported mime video/rv

Who can help me find the root of the problem? thank you！

**Comment by pichillilorenzo** [comment]
Can you post here the URL?

**Comment by 2803404074** [comment]
> 您可以在此处发布网址吗？
只是一个普通的网址：https://www.baidu.com
