### ISSUE TITLE
Can this plugin add Cordova webview?

### ISSUE THREAD

**Issue by creativeandresearch** [pichillilorenzo/flutter_inappwebview#694]
Can this plugin add Cordova webview?

**Comment by pichillilorenzo** [comment]
Sorry, I don't understand. What do you mean?
The Android and iOS WebViews used by Cordova are the same native class used by my plugin:
- Android WebView: https://developer.android.com/reference/android/webkit/WebView
- iOS WKWebView: https://developer.apple.com/documentation/webkit/wkwebview
