### ISSUE TITLE
HTML code used in initialData cannot load scripts and CSS from assets

### ISSUE THREAD

**Issue by tneotia** [pichillilorenzo/flutter_inappwebview#695]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  1.26             |
| Plugin version       |        4.0.0+4       |
| Android version      |        11       |
| iOS version          |           N/A    |
| Xcode version        |          N/A     |

Device information: Galaxy S8

## Description

**Expected behavior:** 

Scripts and CSS loaded from assets

**Current behavior:** 

Scripts and CSS not loaded, and even with `debuggingEnabled` I do not see anything in logs

## Steps to reproduce

```
InAppWebView(
                initialData: InAppWebViewInitialData(
                  data: """
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<link href=\"assets/css-file.css\" rel=\"stylesheet\">
    </head>
    <body>
        <h1>TEST</h1>
    </body>
</html>
                  """
                ),
                initialOptions: InAppWebViewGroupOptions(
                    crossPlatform: InAppWebViewOptions(
                      debuggingEnabled: true,
                    )
                ),
              ),
```
and make some random CSS file in assets that modifes the h1.

Observe that the css will not be applied to the h1.

Maybe I'm doing something wrong?

**Comment by dominikilijevicz** [comment]
If you  are using InAppWebViewInitialData you also need to pass baseUrl to load stuff in like this 
initialData: InAppWebViewInitialData(data: "your html", baseUrl: yourUrl).
If you are hoping to load your local css or asset into that html I think the best way to do so is by using the InAppWebViewController.loadFile() function

**Comment by tneotia** [comment]
Oh wow I didn't even know that was a method on the controller. I will try that and close this if it works. Thanks!

**Comment by ritterdn** [comment]
We're struggling with this same issue, we can't use loadFile(). We're building a document viewer that gets the document html remotely, but has the css, js and images locally (that stuff is always the same and the server expects us to have it locally). We need a way to integrate the assets "on the fly" and it worked perfectly in earlier versions using loadData().

**Comment by pichillilorenzo** [comment]
@tneotia with `initialData` you don't have a base href as you would have in a normal website loaded from a domain or using the localhost server. So, you need to specify in that case the full file path.
For example, on Android, using your file path, it should to be `file:///android_asset/flutter_assets/assets/css-file.css`, that is
```html
<link href="file:///android_asset/flutter_assets/assets/css-file.css" rel="stylesheet">
```
Or you can create and start a localhost server, so the path to your css file would be `http://localhost:8080/assets/css-file.css`, or you can use the `initialFile` to load an HTML file inside your assets directory (in this case, `css-file.css` would be ok if the HTML file is at the same folder level)

**Comment by tneotia** [comment]
I'm fairly certain I tried the full asset path like that but I will try it again. Thanks!

**Comment by pichillilorenzo** [comment]
I tested it on the plugin example project and it worked. Be sure that is the right path of your file

**Comment by sunnyAuto** [comment]
> @tneotia with `initialData` you don't have a base href as you would have in a normal website loaded from a domain or using the localhost server. So, you need to specify in that case the full file path.
> For example, on Android, using your file path, it should to be `file:///android_asset/flutter_assets/assets/css-file.css`, that is
> 
> ```
> <link href="file:///android_asset/flutter_assets/assets/css-file.css" rel="stylesheet">
> ```
> 
> Or you can create and start a localhost server, so the path to your css file would be `http://localhost:8080/assets/css-file.css`, or you can use the `initialFile` to load an HTML file inside your assets directory (in this case, `css-file.css` would be ok if the HTML file is at the same folder level)
How to use in iOS

**Comment by tneotia** [comment]
@pichillilorenzo just got around to testing this and it does work correctly, thanks. How should I approach the file path for iOS? The `android_asset` directory surely doesn't apply for iOS, correct?

**Comment by Huanxin1997** [comment]
![image](https://user-images.githubusercontent.com/42678103/142805001-8d915147-f1a1-4bd0-8992-f52b25ff633e.png)
iOS still not work current. 
This is my request issue: [https://github.com/tneotia/html-editor-enhanced/issues/169](url)

**Comment by yaizudamashii** [comment]
Is there a way to load remote css and javascript files from loadData other than from localhost?
