### ISSUE TITLE
No bounce in inappwebview iOS

### ISSUE THREAD

**Issue by delay** [pichillilorenzo/flutter_inappwebview#696]
I really like your packages flutter_inappwebview and your flutter_browser_app. It seems to have a lot more features than the flutter_webview package from the flutter team.  The one feature I can't seem to make work is there is no bounce when scrolling to the top or bottom of webviews like on flutter_webview or default ios views, flutter_webview does have this but is missing all the other features that make your package so great.  Without the bounce it is very jarring for iOS users who are expecting the bounce behavior.  Is there any way to make this active in your package?  

I have included the minimal code to reproduce the issue.  To reproduce: Just scroll to the bottom of the Webview and notice there is no bounce.  Normally on iOS there is a bounce similar to the default bounce in a flutter Listview.  Thanks for any info on how I might solve this or whether it can be included in your package.  Thanks for making such a great package!

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(new Browser());
}

class Browser extends StatefulWidget {
  @override
  _BrowserState createState() => new _BrowserState();
}

class _BrowserState extends State<Browser> {
  InAppWebViewController _webViewController;
  String url = "";
  double progress = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title:
              Text("${(url.length > 50) ? url.substring(0, 50) + "..." : url}"),
        ),
        body: InAppWebView(
          initialUrl: "https://google.com",
          initialOptions: InAppWebViewGroupOptions(
              ios: IOSInAppWebViewOptions(
                  alwaysBounceVertical: true, disallowOverScroll: false),
              crossPlatform: InAppWebViewOptions(
                debuggingEnabled: true,
              )),
          onWebViewCreated: (InAppWebViewController controller) {
            _webViewController = controller;
          },
          onLoadStart: (InAppWebViewController controller, String url) {
            setState(() {
              this.url = url;
            });
          },
          onLoadStop: (InAppWebViewController controller, String url) async {
            setState(() {
              this.url = url;
            });
          },
          onProgressChanged: (InAppWebViewController controller, int progress) {
            setState(() {
              this.progress = progress / 100;
            });
          },
        ),
      ),
    );
  }
}
```

**Comment by pichillilorenzo** [comment]
Wow, that's a bug!
Thanks for reporting!
I'm working on it

**Comment by pichillilorenzo** [comment]
fixed with the latest release 5.0.5+1

**Comment by pichillilorenzo** [comment]
Thanks a lot for your support @delay!

If you want, you can submit your app to the new website of this plugin, which is [inappwebview.dev](https://inappwebview.dev/), using the [Submit App](https://inappwebview.dev/submit-app/) page!

Your app will be visible to the [Showcase](https://inappwebview.dev/showcase/) page that contains an open list of apps built with Flutter and Flutter InAppWebView!

The website is new (I published it just some days ago), so there is only my Flutter Browser App at the moment.
I hope other people add their apps using the inappwebview plugin! 😄

**Comment by delay** [comment]
I will definitely submit my app!  It will be a while as I am just starting it but once I complete it I will submit it for sure.  Your package should save me a lot of time!

**Comment by pichillilorenzo** [comment]
Ok! Thanks a lot again for the support! It is people like you who give so much satisfaction to the work done 😄

**Comment by delay** [comment]
No problem, it was the least I could do.  I ran into another issue https://github.com/pichillilorenzo/flutter_inappwebview/issues/702#issue-822635682
Not sure if this is fixable or not.  I do need this feature for my own app as I am trying to use gestures to open and close a custom drawer.  Anyway thanks for taking a look.  Keep up the good work!
