### ISSUE TITLE
Updating to Latest Version 5.0.5

### ISSUE THREAD

**Issue by aseef17** [pichillilorenzo/flutter_inappwebview#697]
I have been meaning to use Hybrid Composition on Android to improve the performance of WebViews on Android and was closely following the progress made by this package. 

However, to use the latest version of the package, I would need to switch the beta branch of Flutter. Is there any way that can be avoided?
Using this package on the latest Stable version of Flutter is what would be ideal

**Comment by pichillilorenzo** [comment]
Nope, null-safety requires environment `sdk: ">=2.12.0-0 <3.0.0"`
