### ISSUE TITLE
[onLoadResourceEnd] Support embed

### ISSUE THREAD

**Issue by EArminjon** [pichillilorenzo/flutter_inappwebview#700]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter | 2.0.0 |
| Plugin | 4.0.0+4 |

## Description

**What you'd like to happen:** 
There is a feature called onLoadResource, with it i can see all requests send by the current page. But their is no onLoadResourceEnd wich can be used to got response of these requests or just a progress indicator like : ended / 100%...

**Why should i ask for that ?**
I worked on embed (twitter / insta / facebook) when embed are displayed some externals scripts are loaded and executed to display a specific design (jss / css). With this new listener feature I could add a small piece of code to get the new height of the webview after all script are loaded and ended. With that, I could display my webview like a simple widget in flutter without any scroll issue or strange appearance :) !!

**Alternatives you've considered:**   
Actually, i put a default size around my webview and enabled scroll inside. I need keep space around the webview to let user scroll my flutter page when webview is too big and take too much place (to let user scroll under the webview).

** The final result**
Actually my code : 

```dart
// some widgets
Container(
  margin: EdgeInsets.only(bottom: 8),
  height: height,
  child: InAppWebView(
    initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      supportZoom: false,
      useOnLoadResource: true,
      javaScriptEnabled: true,
    ),
  ),
  // My suggestion
  onLoadResourceEnd: (InAppWebViewController controller, String url) async {
    // In my case what I will do
    final height = await controller.getContentHeight();
    setState(() => this.height = height.toDouble());
  },
  initialUrl: tweetUrl,
),
// some widgets
```

**Comment by pichillilorenzo** [comment]
The `onLoadResource` is called when the resource is loaded, not when it is starting to load.
In fact, if you check the `LoadedResource` class, that is the type of `resource` argument of `onLoadResource` event, it has `startTime` and `duration` values.

However, the `onLoadResource` event is implemented on this plugin by injecting some JavaScript code inside the webpage using the [PerformanceObserver JavaScript API](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe) and listening `observer.observe({entryTypes: ['resource']});`.
So, in this case, the `startTime` and `duration` values are coming from the [PerformanceResourceTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming) JavaScript Interface

You cannot get the response of these requests because there isn't any API from native WebViews that allows that.
This is a limitation not only of this plugin but of all WebViews in general (not only in Flutter but also in the native ones!).

**Comment by EArminjon** [comment]
Thanks for your answer, hum, is their a way to listen webview content height @pichillilorenzo ?

**Comment by EArminjon** [comment]
I found a solution : ) !!

I wrap embed around a div my html (got from api) with an id :

```html
<html lang="fr">
<meta name="viewport" content="width=device-width user-scalable=no zoom=1.1">
<style>img {max-width: 100%; height: auto}</style>
<body>
  <div class="container" id="_flutter_target_do_not_delete">$html_with_embed</div>
  <script>
     function outputsize() {
       window.flutter_inappwebview.callHandler('newHeight');
     }
     new ResizeObserver(outputsize).observe(_flutter_target_do_not_delete)
   </script>
</body>
</html>
```

With your feature "handler" :

```dart
 onWebViewCreated: (InAppWebViewController controller) {
   controller.addJavaScriptHandler(
     handlerName: "newHeight",
     callback: (List<dynamic> arguments) async {
       final int height = await controller.getContentHeight();
       setState(() => this.height = height.toDouble());
     });
},
```

**Comment by pichillilorenzo** [comment]
You can use JavaScript for that. Check for example this issue on StackOverflow: https://stackoverflow.com/questions/14866775/detect-document-height-change.
It uses the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) API on the `document.body` element.
You can set a JavaScript handler/channel on that Flutter/Dart side, inside the `onWebViewCreated` event and, on the JavaScript side, when the height changes, you call the `window.flutter_inappwebview.callHandler('myHandlerName', myJsVarWithBodyHeight)` javascript method.

For JavaScript handlers/channels, you can read this [article](https://medium.com/flutter-community/inappwebview-the-real-power-of-webviews-in-flutter-c6d52374209d?source=friends_link&sk=cb74487219bcd85e610a670ee0b447d0), under the `JavaScript Handlers (Channels)` section.

I think in your case, you don't need to listen to `window.addEventListener("flutterInAppWebViewPlatformReady")` javascript event to call your Flutter/Dart js handler.

If you need, you can set a global flag variable that you set to `true` when `window.addEventListener("flutterInAppWebViewPlatformReady")` happens, and inside the ResizeObserver `observe` callback you check if that flag is `true` or not before calling `window.flutter_inappwebview.callHandler` javascript method

**Comment by pichillilorenzo** [comment]
Ok! I just show your answer now! Glad you have already solved it :)

**Comment by EArminjon** [comment]
Ahaha thanks you ! You would have saved me!

**Comment by pichillilorenzo** [comment]
👍 👍

**Comment by wilz05** [comment]
@EArminjon  thank you for the above solution  
it works very well, at one time, Have you tried if the html string is loaded in webview correctly and the app Orientation changes from portrait/landscape mode ?  Container height doesn't get update...
I am unable to get the updated height.

**Comment by EArminjon** [comment]
> @EArminjon @pichillilorenzo thank you for the above solution
> it works very well, at one time, Have you tried if the html string is loaded in webview correctly and the app Orientation changes from portrait/landscape mode ? Container height doesn't get update...
> I am unable to get the updated height.

I've some trouble to well identify what do you want achieve. Can you provide 2 screenshots : one for what currently happen an one for the one you want to have.

**Comment by wilz05** [comment]
please look into the below sample code

```
double wvHeight = 100; 
final htmlFromApi= "some html data with images and iframes";
final html = InAppWebViewInitialData(data: '''
                        <html lang="ar">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                            <style>img {max-width: 100%; height: auto} .container {direction:rtl;}</style>
                           <body>
                            <div class="container" id="_flutter_target_do_not_delete">$htmlFromApi</div>
                            <script>
                            function outputsize() {
                                 window.flutter_inappwebview.callHandler('newHeight');
                            }
                            new ResizeObserver(outputsize).observe(_flutter_target_do_not_delete)
                            </script>
                          </body>
                        </html>
                      ''');
```

 ```
Widget _fetchWebView(InAppWebViewInitialData data) {
        return InAppWebView(
          initialOptions: InAppWebViewGroupOptions(
            crossPlatform: InAppWebViewOptions(
              supportZoom: true,
              javaScriptEnabled: true,
              disableHorizontalScroll: true,
              disableVerticalScroll: true,
            ),
            android: AndroidInAppWebViewOptions(
              useHybridComposition: true,
            ),
            ios: IOSInAppWebViewOptions(
              allowsInlineMediaPlayback: true,
            ),
          ),
          onWebViewCreated: (InAppWebViewController controller) {
            // controller.reload();
            controller.addJavaScriptHandler(
                handlerName: "newHeight",
                callback: (List<dynamic> arguments) async {
                  final int? vwHeight2 = await controller.getContentHeight();
                  print(vwHeight2);
                  print(await controller.getContentHeight());
                  setState(() => this.wvHeight =
                      vwHeight2 == null ? 100 : vwHeight2.toDouble());
                });
          },
          onLoadStop: (InAppWebViewController controller, Uri? url) {
            controller.evaluateJavascript(
                source:
                    '''(() => { return document.body.scrollHeight;})()''').then(
                (value) {
              if (value == null || value == '') {
                return;
              }
              print(double.parse('$value')); // this is correct height once the webView loads completely 
               
              setState(() {
                this.wvHeight = double.parse('$value'); 
              });
            });
          },
          initialData: data,
        );
      }
```
Below will be the container 
  ```
Container(
                      height: wvHeight,
                      child: Column(
                        children: [
                          Expanded(
                            child: _fetchWebView(html),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      height: 600,
                      width: MediaQuery.of(context).size.width,
                      color: Colors.red,
                    ),
```
whenever you load the screen with portrait mode you will get the correct result. 
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-17 at 18 33 35](https://user-images.githubusercontent.com/19764167/122428594-b5fb7180-cf9a-11eb-9be4-84d285cfff46.png)

then whenever Orientation changes unable to refresh the webview & the correct height for the container. 
                      
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-17 at 18 33 55](https://user-images.githubusercontent.com/19764167/122428786-e6431000-cf9a-11eb-9f2f-2f1bf0ba09dc.png)

**Comment by EArminjon** [comment]
Forgot to update this post, try this code : 

In your HTML part : 
```dart
<div class="container" id="_flutter_target_do_not_delete">$cleanHtml</div>
<script>
  function outputsize() {
    if (typeof window.flutter_inappwebview !== "undefined" && typeof window.flutter_inappwebview.callHandler !== "undefined")
       window.flutter_inappwebview.callHandler('newHeight', document.getElementById("_flutter_target_do_not_delete").offsetHeight);
    }
  new ResizeObserver(outputsize).observe(_flutter_target_do_not_delete)
</script>
```

Updated callback : We use the arguments which contain the window size.
```dart
(InAppWebViewController controller) {
    controller.addJavaScriptHandler(
      handlerName: "newHeight",
      callback: (List<dynamic> arguments) async {
        int? height = arguments.isNotEmpty ? arguments[0] : await controller.getContentHeight();
        if (mounted) setState(() => this.height = height!.toDouble());
      },
    );
},
```

**Comment by wilz05** [comment]
@EArminjon  Thank you for the quick response & for the above code, it seems like no luck still. it works on the first load, whenever the Orientation changes height breaks. FYI I have added call back code in  onWebViewCreated method.

**Comment by EArminjon** [comment]
@wilz05 Can you try in an other widget three context ? Without column and Expanded. In a scaffold with just a column and one container above and under with a height of maybe 400 ?

**Comment by wilz05** [comment]
@EArminjon  I tried with the above suggested, created new screen removed onLoadStop method , no luck still !. I will add   some sample html data to test. I think we need use onLoadStop method as well to get the final height size. 

` final htmlFromApi = """"<div>\n
        <div>\n
    <div>&nbsp;</div>
    \n</div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra, est sed accumsan posuere, elit magna aliquam quam, molestie laoreet risus purus at metus. Proin eget interdum magna, a tristique arcu. In vitae sem efficitur, finibus mauris ut, sollicitudin leo. Suspendisse rhoncus lacinia tortor, non condimentum leo porta quis. Curabitur pellentesque urna et erat varius blandit. Quisque vitae mauris blandit diam laoreet tristique dapibus ac justo. Vivamus sodales odio eget felis commodo, et semper augue dictum. Curabitur hendrerit nulla dolor, ut facilisis quam sagittis vitae. Etiam at sapien pretium, vulputate dolor non, pharetra leo.Nullam faucibus fermentum dui id mollis. Sed mattis vel urna a euismod. Nam mauris velit, consectetur sit amet molestie vitae, sollicitudin in ante. Sed tempor aliquam neque. Suspendisse dictum purus vitae felis fermentum eleifend. Sed finibus posuere placerat. Etiam tristique orci lacus, eu vestibulum enim molestie in. Quisque hendrerit, nisi sed sodales laoreet, libero mi luctus velit, vel egestas nulla nisl a ante. Maecenas viverra eleifend tristique. Etiam enim nunc, pellentesque a malesuada mattis, sodales vel erat. Nam venenatis mauris nec arcu fringilla rutrum. Integer pellentesque laoreet dictum. Morbi eleifend diam sem, sit amet auctor augue facilisis vitae. Nam vitae rhoncus ligula. Donec placerat magna vel purus consectetur, a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci..</div>
    <p>\n\n</p>
    <div>&nbsp;</div>
    <p>\n\n</p>
    <div><img src="https://images.indianexpress.com/2021/06/Delhi-riots-1-1.jpg" alt="\&quot;\&quot;" width="\&quot;1811\&quot;" height="\&quot;1811\&quot;" /></div>
    <p>\n\n</p>
    <div>&nbsp;</div>
    <p>\n\nة \n\n</p>
    <div>&nbsp;</div>
    <p>\n\n</p>
    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra, est sed accumsan posuere, elit magna aliquam quam, molestie laoreet risus purus at metus. Proin eget interdum magna, a tristique arcu. In vitae sem efficitur, finibus mauris ut, sollicitudin leo. Suspendisse rhoncus lacinia tortor, non condimentum leo porta quis. Curabitur pellentesque urna et erat varius blandit. Quisque vitae mauris blandit diam laoreet tristique dapibus ac justo. Vivamus sodales odio eget felis commodo, et semper augue dictum. Curabitur hendrerit nulla dolor, ut facilisis quam sagittis vitae. Etiam at sapien pretium, vulputate dolor non, pharetra leo.Nullam faucibus fermentum dui id mollis. Sed mattis vel urna a euismod. Nam mauris velit, consectetur sit amet molestie vitae, sollicitudin in ante. Sed tempor aliquam neque. Suspendisse dictum purus vitae felis fermentum eleifend. Sed finibus posuere placerat. Etiam tristique orci lacus, eu vestibulum enim molestie in. Quisque hendrerit, nisi sed sodales laoreet, libero mi luctus velit, vel egestas nulla nisl a ante. Maecenas viverra eleifend tristique. Etiam enim nunc, pellentesque a malesuada mattis, sodales vel erat. Nam venenatis mauris nec arcu fringilla rutrum. Integer pellentesque laoreet dictum. Morbi eleifend diam sem, sit amet auctor augue facilisis vitae. Nam vitae rhoncus ligula. Donec placerat magna vel purus consectetur, a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci..</div>
    <p>\n\n</p>
    <div>&nbsp;</div>
    <p>\n\n</p>
    <div>a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci.</div>
    <p>\n\n</p>
    <div>&nbsp;</div>
    <p>\n\n</p>
    <div><img src="https://images.indianexpress.com/2020/11/nadal-atp-finals.jpg" width="1811" height="1811" /></div>
    <p>\n\n</p>
    <div><img src="https://www.foleon.com/hubfs/Blogs/5%20sites%20for%20free%20stock%20photos/stockfoto.jpg" width="1811" height="1811" /> </div>
    <p>\n\n</p>
    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra, est sed accumsan posuere, elit magna aliquam quam, molestie laoreet risus purus at metus. Proin eget interdum magna, a tristique arcu. In vitae sem efficitur, finibus mauris ut, sollicitudin leo. Suspendisse rhoncus lacinia tortor, non condimentum leo porta quis. Curabitur pellentesque urna et erat varius blandit. Quisque vitae mauris blandit diam laoreet tristique dapibus ac justo. Vivamus sodales odio eget felis commodo, et semper augue dictum. Curabitur hendrerit nulla dolor, ut facilisis quam sagittis vitae. Etiam at sapien pretium, vulputate dolor non, pharetra leo.Nullam faucibus fermentum dui id mollis. Sed mattis vel urna a euismod. Nam mauris velit, consectetur sit amet molestie vitae, sollicitudin in ante. Sed tempor aliquam neque. Suspendisse dictum purus vitae felis fermentum eleifend. Sed finibus posuere placerat. Etiam tristique orci lacus, eu vestibulum enim molestie in. Quisque hendrerit, nisi sed sodales laoreet, libero mi luctus velit, vel egestas nulla nisl a ante. Maecenas viverra eleifend tristique. Etiam enim nunc, pellentesque a malesuada mattis, sodales vel erat. Nam venenatis mauris nec arcu fringilla rutrum. Integer pellentesque laoreet dictum. Morbi eleifend diam sem, sit amet auctor augue facilisis vitae. Nam vitae rhoncus ligula. Donec placerat magna vel purus consectetur, a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci..</div>
    """;`

once you finish loading above string in webview. please do keep changing the screen orientation.

**Comment by EArminjon** [comment]
@wilz05 

It work well for me with this : 
My homepage
```dart
class HomePage extends StatelessWidget {
  static const pageName = "home";

  @override
  Widget build(BuildContext context) {
    var html =
        """"<div>\n <div>\n <div>&nbsp;</div> \n</div> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra, est sed accumsan posuere, elit magna aliquam quam, molestie laoreet risus purus at metus. Proin eget interdum magna, a tristique arcu. In vitae sem efficitur, finibus mauris ut, sollicitudin leo. Suspendisse rhoncus lacinia tortor, non condimentum leo porta quis. Curabitur pellentesque urna et erat varius blandit. Quisque vitae mauris blandit diam laoreet tristique dapibus ac justo. Vivamus sodales odio eget felis commodo, et semper augue dictum. Curabitur hendrerit nulla dolor, ut facilisis quam sagittis vitae. Etiam at sapien pretium, vulputate dolor non, pharetra leo.Nullam faucibus fermentum dui id mollis. Sed mattis vel urna a euismod. Nam mauris velit, consectetur sit amet molestie vitae, sollicitudin in ante. Sed tempor aliquam neque. Suspendisse dictum purus vitae felis fermentum eleifend. Sed finibus posuere placerat. Etiam tristique orci lacus, eu vestibulum enim molestie in. Quisque hendrerit, nisi sed sodales laoreet, libero mi luctus velit, vel egestas nulla nisl a ante. Maecenas viverra eleifend tristique. Etiam enim nunc, pellentesque a malesuada mattis, sodales vel erat. Nam venenatis mauris nec arcu fringilla rutrum. Integer pellentesque laoreet dictum. Morbi eleifend diam sem, sit amet auctor augue facilisis vitae. Nam vitae rhoncus ligula. Donec placerat magna vel purus consectetur, a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci..</div> <p>\n\n</p> <div>&nbsp;</div> <p>\n\n</p> <div><img src="https://images.indianexpress.com/2021/06/Delhi-riots-1-1.jpg" alt="\&quot;\&quot;" width="\&quot;1811\&quot;" height="\&quot;1811\&quot;" /></div> <p>\n\n</p> <div>&nbsp;</div> <p>\n\nة \n\n</p> <div>&nbsp;</div> <p>\n\n</p> <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra, est sed accumsan posuere, elit magna aliquam quam, molestie laoreet risus purus at metus. Proin eget interdum magna, a tristique arcu. In vitae sem efficitur, finibus mauris ut, sollicitudin leo. Suspendisse rhoncus lacinia tortor, non condimentum leo porta quis. Curabitur pellentesque urna et erat varius blandit. Quisque vitae mauris blandit diam laoreet tristique dapibus ac justo. Vivamus sodales odio eget felis commodo, et semper augue dictum. Curabitur hendrerit nulla dolor, ut facilisis quam sagittis vitae. Etiam at sapien pretium, vulputate dolor non, pharetra leo.Nullam faucibus fermentum dui id mollis. Sed mattis vel urna a euismod. Nam mauris velit, consectetur sit amet molestie vitae, sollicitudin in ante. Sed tempor aliquam neque. Suspendisse dictum purus vitae felis fermentum eleifend. Sed finibus posuere placerat. Etiam tristique orci lacus, eu vestibulum enim molestie in. Quisque hendrerit, nisi sed sodales laoreet, libero mi luctus velit, vel egestas nulla nisl a ante. Maecenas viverra eleifend tristique. Etiam enim nunc, pellentesque a malesuada mattis, sodales vel erat. Nam venenatis mauris nec arcu fringilla rutrum. Integer pellentesque laoreet dictum. Morbi eleifend diam sem, sit amet auctor augue facilisis vitae. Nam vitae rhoncus ligula. Donec placerat magna vel purus consectetur, a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci..</div> <p>\n\n</p> <div>&nbsp;</div> <p>\n\n</p> <div>a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci.</div> <p>\n\n</p> <div>&nbsp;</div> <p>\n\n</p> <div><img src="https://images.indianexpress.com/2020/11/nadal-atp-finals.jpg" width="1811" height="1811" /></div> <p>\n\n</p> <div><img src="https://www.foleon.com/hubfs/Blogs/5%20sites%20for%20free%20stock%20photos/stockfoto.jpg" width="1811" height="1811" /> </div> <p>\n\n</p> <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra, est sed accumsan posuere, elit magna aliquam quam, molestie laoreet risus purus at metus. Proin eget interdum magna, a tristique arcu. In vitae sem efficitur, finibus mauris ut, sollicitudin leo. Suspendisse rhoncus lacinia tortor, non condimentum leo porta quis. Curabitur pellentesque urna et erat varius blandit. Quisque vitae mauris blandit diam laoreet tristique dapibus ac justo. Vivamus sodales odio eget felis commodo, et semper augue dictum. Curabitur hendrerit nulla dolor, ut facilisis quam sagittis vitae. Etiam at sapien pretium, vulputate dolor non, pharetra leo.Nullam faucibus fermentum dui id mollis. Sed mattis vel urna a euismod. Nam mauris velit, consectetur sit amet molestie vitae, sollicitudin in ante. Sed tempor aliquam neque. Suspendisse dictum purus vitae felis fermentum eleifend. Sed finibus posuere placerat. Etiam tristique orci lacus, eu vestibulum enim molestie in. Quisque hendrerit, nisi sed sodales laoreet, libero mi luctus velit, vel egestas nulla nisl a ante. Maecenas viverra eleifend tristique. Etiam enim nunc, pellentesque a malesuada mattis, sodales vel erat. Nam venenatis mauris nec arcu fringilla rutrum. Integer pellentesque laoreet dictum. Morbi eleifend diam sem, sit amet auctor augue facilisis vitae. Nam vitae rhoncus ligula. Donec placerat magna vel purus consectetur, a posuere est tempor. Sed in molestie mi. Nam faucibus nulla ut orci gravida consequat. Nulla pharetra ornare nisl id malesuada. Proin laoreet id augue eu faucibus. Mauris non blandit tortor, a aliquam orci..</div> """;
    final embedUrl = '''
                        <html lang="fr">
                           <meta name="viewport" content="width=device-width user-scalable=no zoom=1.1">
                           <head>
                            <style>
                              img {max-width: 100%; height: auto}
                            </style>
                           </head>
                           <body>
                            <div class="container" id="_flutter_target_do_not_delete">$html</div>
                            <script>
                              function outputsize() {
                                if (typeof window.flutter_inappwebview !== "undefined" && typeof window.flutter_inappwebview.callHandler !== "undefined")
                                   window.flutter_inappwebview.callHandler('newHeight', document.getElementById("_flutter_target_do_not_delete").offsetHeight);
                                }
                              new ResizeObserver(outputsize).observe(_flutter_target_do_not_delete)
                            </script>
                          </body>
                        </html>
                      ''';

    /// Lancement du tweet dans un navigateur pour éviter les bugs de sous interractions
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(height: 400, width: MediaQuery.of(context).size.width, color: Colors.red),
            AppWebview(
              autoResize: true,
              data: embedUrl,
              launchUrl: LaunchUrl.launchURL,
            ),
            Container(height: 400, width: MediaQuery.of(context).size.width, color: Colors.red),
          ],
        ),
      ),
    );
  }
}
```

My webview implementation, you can see many additional code useful in my app, maybe in yours too.
```dart
import 'dart:io';
import 'dart:math';

import 'package:device_info/device_info.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:mobile_app_factory/presentation/utils/webview_options.dart';

class AppWebview extends StatefulWidget {
  final String? url;
  final bool autoResize, scrollable;
  final String? data;
  final Function? launchUrl;
  final double? maxHeight;

  const AppWebview({Key? key, this.autoResize = false, this.launchUrl, this.url, this.data, this.scrollable = false, this.maxHeight}) : super(key: key);

  @override
  _AppWebview createState() => _AppWebview();
}

class _AppWebview extends State<AppWebview> {
  double height = 1;
  AndroidDeviceInfo? info;
  bool ready = false;
  InAppWebViewController? controller;

  Future initWebviewOption() async {
    try {
      if (Platform.isAndroid) {
        AndroidDeviceInfo info = await DeviceInfoPlugin().androidInfo;
        setState(() => this.info = info);
      }
    } catch (e) {
      print(e);
    } finally {
      setState(() => ready = true);
    }
  }

  @override
  void initState() {
    super.initState();

    initWebviewOption();
  }

  @override
  Widget build(BuildContext context) {
    if (!ready) return Container();
    final Set<Factory<OneSequenceGestureRecognizer>> gestures = Set()..add(Factory<VerticalDragGestureRecognizer>(() => VerticalDragGestureRecognizer()));

    /// Lancement du tweet dans un navigateur pour éviter les bugs de sous interractions
    return Container(
      height: widget.autoResize ? (widget.maxHeight != null ? min(height, widget.maxHeight!) : height) : null,
      child: InAppWebView(
        gestureRecognizers: widget.scrollable ? gestures : null,
        initialOptions: InAppWebViewGroupOptions(
          android: info == null ? null : AppWebViewOption().getAndroidOption(info!),
          crossPlatform: InAppWebViewOptions(
            transparentBackground: true,
            useShouldOverrideUrlLoading: true,
            supportZoom: false,
            javaScriptEnabled: true,
            disableHorizontalScroll: true,
            disableVerticalScroll: !widget.scrollable,
          ),
        ),
        onWebViewCreated: !widget.autoResize
            ? null
            : (InAppWebViewController controller) {
                controller.addJavaScriptHandler(
                  handlerName: "newHeight",
                  callback: (List<dynamic> arguments) async {
                    int? height = arguments.isNotEmpty ? arguments[0] : await controller.getContentHeight();
                    if (mounted) setState(() => this.height = height!.toDouble());
                  },
                );
              },
        shouldOverrideUrlLoading: (InAppWebViewController controller, NavigationAction navigationAction) async {
          if (navigationAction.request.url.toString().contains("/embed/") || navigationAction.request.url.toString() == "about:blank" || navigationAction.request.url.toString().contains("https://www.facebook.com/plugins/post.php")) return NavigationActionPolicy.ALLOW;
          print(navigationAction.request.url.toString());
          if (widget.launchUrl != null) widget.launchUrl!(navigationAction.request.url.toString());
          return NavigationActionPolicy.CANCEL;
        },
        initialUrlRequest: widget.url != null ? URLRequest(url: Uri.parse(widget.url!)) : null,
        initialData: widget.data != null ? InAppWebViewInitialData(data: widget.data!) : null,
      ),
    );
  }
}
```

**Comment by wilz05** [comment]
@EArminjon  Thank you for the above code, Still confused got no luck so far only changes I made in ur code is 
```
 AppWebview(
              autoResize: true,
              data: embedUrl,
              launchUrl: () {},  // passed empty call back 
            ),
            
```
  And commented 2 lines of code related android device  since I do not have that class 

 ```
child: InAppWebView(
        gestureRecognizers: widget.scrollable ? gestures : null,
        initialOptions: InAppWebViewGroupOptions(
          // android:
          //     info == null ? null : AppWebViewOption().getAndroidOption(info!),
          crossPlatform: InAppWebViewOptions(
            transparentBackground: true,
            useShouldOverrideUrlLoading: true,
            supportZoom: false,
            javaScriptEnabled: true,
            disableHorizontalScroll: true,
            disableVerticalScroll: !widget.scrollable,
          ),
        ),
```

And getting the below results 
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-17 at 22 42 59](https://user-images.githubusercontent.com/19764167/122463131-e6a0d280-cfbd-11eb-8612-5a545e3df1b2.png)

**Comment by EArminjon** [comment]
```
// android:  info == null ? null : AppWebViewOption().getAndroidOption(info!),
```
Oups, just a check to enable hybrid webview on android >10 .

I don't know about refreshing webview on orientation change. Is it working for you ? I've no issue about orientation, height / width are correct.

**Comment by wilz05** [comment]
@EArminjon still having problem with the height on iOS(simulator) 12 max pro. never tried on android.. it doesn't give the proper height whenever I change the orientation. in which device did you try to run the above ?

**Comment by EArminjon** [comment]
I've tried your issue on Android simulator.

**Comment by wilz05** [comment]
@EArminjon I'm sorry haven't told you earlier, could you please try to run it on iOS simulator if possible.!  I think you would be able to reproduce it.

**Comment by wilz05** [comment]
@EArminjon I've tried even on android simulator.  I am facing same issue. I am getting proper height only on onLoadStop method (once the webview loads completely with images and other resources. may be you're getting proper height same time coz of speed internet  connection just suspecting :)  ). but when the screen orientation changes unable to get the new height. 
Even tried with new screen with your code sample. same result.
