### ISSUE TITLE
headers are not readed

### ISSUE THREAD

**Issue by sante85** [pichillilorenzo/flutter_inappwebview#701]
Simple nodejs server
var http = require('http'),
  fs = require('fs');

fs.readFile('./test.html', function (err, html) {
  if (err) {
    throw err;
  }
  http.createServer(function(request, response) {
    response.writeHeader(200, {"Content-Type": "text/html", "uudi": "eeee"});
    response.writeHead(302, {
      'Location': 'test2.html',
      headers: {"uuid":"2324354654"}
    });
    response.end()
  }).listen(8000);
});

------------------------------------------------------

  shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
                      print("URL: ${shouldOverrideUrlLoadingRequest.url}");
                      print("HEADER: ${shouldOverrideUrlLoadingRequest.headers}");

output: HEADER: null

**Comment by sante85** [comment]
I/flutter ( 8168): URL: http://192.168.1.16:8000/test2.html
I/flutter ( 8168): HEADER: null

**Comment by pichillilorenzo** [comment]
The `shouldOverrideUrlLoading` event is for requests, not responses.
If you are asking to be able to read responses, well, it's not possible. At least, on Android it's impossible.
On iOS, using the new plugin version, you have the `iosOnNavigationResponse` event (you need to enable it with `useOnNavigationResponse: true` iOS-specific webview option), where you can read the request with headers but you don't have the response body.
Just to be clear, this is not a limitation of this plugin but of native WebViews in general.
