### ISSUE TITLE
Flutter page opened from InAppWebView not working (Android)

### ISSUE THREAD

**Issue by Manuito83** [pichillilorenzo/flutter_inappwebview#704]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |1.27.0-8.0.pre|
| Plugin version       |5.1.0|
| Android version      |API 30|
| iOS version          | 14.3 |
| Xcode version        | 12.3 |

Device information: Emulator (Android + iOS) + OnePlus 6T

## Description

Note: it works in iOS as expected, but does not work in Android.

**Expected behavior:** when navigating to a second Flutter page from an InAppWebView (e.g. after pressing an "options" button  placed in the appBar), this second page was working as expected before version 5.0.0

**Current behavior:** second page gets stuck (does not scroll and/or widgets cannot be interacted with)

## Steps to reproduce

1. Use current version 5.1.0 example
2. Add IconButton in appBar, that navigates to a second page as per [this example](https://flutter.dev/docs/cookbook/navigation/navigation-basics)
3. In the second page, add a Scaffold with a single ListView with 300 items
4. Run the app, press the button, navigate to the second page -> second page gets stuck when scrolling

Not sure if related, the emulator also complaints about "W/ImageReader_JNI(27506): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers"

** Note: edited after testing in iOS (works fine)

**Comment by pichillilorenzo** [comment]
I tested it and it seems it happens when Android Hybrid Composition is enabled. If I set `useHybridComposition: false`, it works correctly

**Comment by Manuito83** [comment]
I confirm it works for me as well by setting `usedHybridComposition: false`. 

I had this running for a long time with v4.0.0+4 and Hybrid Composition (after is was added to the master branch a few months ago) with no issues at all, though.

**Comment by pichillilorenzo** [comment]
Tested also with Official webview flutter plugin, and it happens there for the same reason, hybrid composition

**Comment by pichillilorenzo** [comment]
I think there is something going on with flutter itself!
I tested one of my App, that is Flutter Browser, and it happens also there.
I didn't even touch the code from the last update.
I have just updated my flutter version: Flutter 2.1.0-10.0.pre • channel dev, and when I build it, I have the same problem in one of my app routes

**Comment by pichillilorenzo** [comment]
I think we should open an issue to the Flutter repository itself

**Comment by Manuito83** [comment]
Yep, I tested the same, same results. I will open an issue, thanks a lot!

**Comment by pichillilorenzo** [comment]
This is my test code:
```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
// import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:webview_flutter/webview_flutter.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    // await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }
  debugPrintGestureArenaDiagnostics = true;
  WebView.platform = SurfaceAndroidWebView();

  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => FirstRoute(),
        '/second': (context) => SecondRoute()
      },
    );
  }
}

class FirstRoute extends StatelessWidget {

  // final InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
  //     android: AndroidInAppWebViewOptions(
  //       useHybridComposition: true,
  //     ),);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
        actions: [
          ElevatedButton(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => SecondRoute()),
              );
            },
            child: Text('Open route!'),
          ),
        ],
      ),
      // body: InAppWebView(
      //   initialUrlRequest: URLRequest(url: Uri.parse("https://github.com/flutter")),
      //   initialOptions: options,
      // ),
      body: WebView(
        initialUrl: "https://github.com/flutter",
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
        actions: [
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
            },
            child: Text('Go back!'),
          ),
        ]
      ),
      body: ListView.builder(
        itemCount: 100,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text("Item " + index.toString()),
          );
        },
      )
    );
  }
}
```
Just comment/uncomment the 2 webview plugins to test each other

**Comment by Manuito83** [comment]
Thanks, submitted https://github.com/flutter/flutter/issues/77488#issue-823746209

**Comment by pichillilorenzo** [comment]
I can confirm that this problem happens from Flutter version `1.27.0-8.0.pre` and higher (also `2.1.0-10.0.pre`).
If you install Flutter version `1.27.0-4.0.pre` or lower, it works as expected.
I tested using [`fvm`](https://pub.dev/packages/fvm) in order to be able to install multiple versions of Flutter on my computer.

**Comment by pichillilorenzo** [comment]
@Manuito83 so, the current workaround is to use Flutter version `1.27.0-4.0.pre` or lower, unfortunately.

**Comment by Manuito83** [comment]
@pichillilorenzo this seems now to be working with 2.3.0-0.1.pre (dev channel). Haven't tested with the example or with Flutter Browser.

**Comment by ManuelOrtega** [comment]
I also have this issue with version 2.5.0-5.0.pre, any news about it?

**Comment by Manuito83** [comment]
This is fixed already in the current Stable channel.
