### ISSUE TITLE
Can you pass JWT access token from app to the web view?

### ISSUE THREAD

**Issue by wellbranding** [pichillilorenzo/flutter_inappwebview#705]
Hello, is it possible to pass JWT access token to the webview headers and immediately login user without navigating to login page in the web? If so, how should I present web view ?

**Comment by pichillilorenzo** [comment]
As said in the other issue, you can use the property headers of the URLRequest class

**Comment by wellbranding** [comment]
How can I retrieve that JWT token in the React/Angular or any other web framework? Would this JWT token received from Flutter will be stored in cockies or in local storage?

**Comment by pichillilorenzo** [comment]
That depends on the logic of your website.
If you save it in the cookies, you will find it in the cookies using the Cookie Manager class.
Otherwise you can get it using the local storage with JavaScript or using the webStorage property of InAppWebViewController.

**Comment by wellbranding** [comment]
Thanks! So If I understood correctly, the inappwebview passes a JWT token to both cookies and local storage? And I can access that passed JWT token with Cookie Manager  inside if my react js web app?

**Comment by pichillilorenzo** [comment]
No, the plugin offers API to access both.
If the token is inside a cookie or in the local storage, that is up to you.
Like any other web app.
If you want to save the token somewhere in the user phone storage, you can use for example shared_preferences plugin or whatever you want.
The app logic depends on you.
