### ISSUE TITLE
Header  - Authorization Bearer + Token

### ISSUE THREAD

**Issue by Artespecialist** [pichillilorenzo/flutter_inappwebview#706]
Hello. I went through your documentation, but could not find or missed this information. I have a flutter app and a web version. Some functionality of the app will be linked with the web version(will use the web version inside the app)
I need to send a request from a flutter app, that will open a webview so that i can show the data from the web, but in order to access it I need to send the token in the header in the form of : Authorization: Bearer + token.
Can I do that with your library? If that is the case can you tell me how to do it or point me to the docs where i could find this answer?  Thanks a lot.

**Comment by wellbranding** [comment]
I need the same functionality! How to achieve it?

**Comment by pichillilorenzo** [comment]
You can set headers using the URLRequest class.
