### ISSUE TITLE
IOS scrolling crash the application

### ISSUE THREAD

**Issue by Alexays** [pichillilorenzo/flutter_inappwebview#707]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.0.1          |
| Plugin version       |         5.1.0+3      |
| Android version      |               |
| iOS version          |      14.4         |
| Xcode version        |      12.4         |

Device information: 

## Description

With #703 fix, webview is not scrolling anymore and crash after 1-2s 

**Expected behavior:** 
Scrolling and not crashing

**Current behavior:** 
Not scrolling and crashing

## Steps to reproduce

Open a webview and scrolling

**Comment by pichillilorenzo** [comment]
I tested the example code in the README.md with a real iPhone 12 Pro (iOS 14.4) and it works as expected.

Here is the screen recording:

https://user-images.githubusercontent.com/5956938/110313514-cf3d6b00-8006-11eb-8789-6927a269bbcf.mov

I'm using Flutter version `2.1.0-10.0.pre`.

Please, post an example code that causes this issue and the error logs you receive.

**Comment by Alexays** [comment]
By setting `disableHorizontalScroll: true`, the app crash on scroll without any error logs.

**Comment by pichillilorenzo** [comment]
fixed with new version `5.1.0+4`

**Comment by callmejm** [comment]
@pichillilorenzo hi, not sure can you create a fixed version without null safety ?
