### ISSUE TITLE
App closes without warnings or error messages or crash reports when invalid path is provided or when Uri passed to url is incorrect.

### ISSUE THREAD

**Issue by ruthvik-github** [pichillilorenzo/flutter_inappwebview#709]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.0.1   |
| Plugin version       |       5.1.0+2        |
| Android version      |       any        |
| iOS version          |       any        |
| Xcode version        |       12.4        |

Device information: 
android simulator pixel 3 XL API 30 - android x86
## Description

when url (URI) is passed incorrectly to [ChromeSafariBrowser] in a funcation call 
```
await MyChromeSafariBrowser().open(
  url:Uri(path:pathFromApi),
)
```
here passed path is received through api, how ever when a url is passed to path like https://example.com/xxx, 
the app is closed when ever the function is called.

**Expected behavior:** 
Throw error, stop opening the chrome Safari Browser and a callback to show error message saying something went wrong.
or any usual way of showing an error and mistake.

**Current behavior:** 
App is closed without showing an error or throwing an exception.
It is crashed without even triggering crash and generating crash report.
App is completely closed as if user has pressed back button.

## Steps to reproduce

1. create a button which call async function 
```
await MyChromeSafariBrowser().open(
  url:Uri(path:pathFromApi),
)
```
However here the pathFromApi is full url like https://www.example.com/xxxxxxs/xxx/

2. when app is running click on button.

There is no stack trace.
LogCat shows "Application Exited".

**Comment by pichillilorenzo** [comment]
If you want to use the `ChromeSafariBrowser` class on Android 11+ you need to specify your app querying for `android.support.customtabs.action.CustomTabsService` in your `AndroidManifest.xml` (you can read more about it here: https://developers.google.com/web/android/custom-tabs/best-practices#applications_targeting_android_11_api_level_30_or_above).

If you already added the `queries` section in your `AndroidManifest.xml`, could you provide the URL that causes this issue?
Using, for example, `Uri.parse("https://github.com/pichillilorenzo/flutter_inappwebview")`, it works correctly.
If you can't provide me an URL to test, well, I cannot test and do anything.

**Comment by ruthvik-github** [comment]
> if the problem is related to the URL itself, then it's up to you to manage the URL correctly and, then, pass it to the `ChromeSafariBrowser.open` method.
> What can I say is that the `open` method expects an `Uri`, so when you call `Uri.parse`, it's up to you to check for any error during parsing.

Yes it needs to be corrected at passed to the chrome safari browser.
and it works fine after making corrections, 
however i think there must be a method to handle these problems,
Current behaviour is closing the app entirely.
where it should throw an exception.

**Comment by pichillilorenzo** [comment]
`Uri` is not a custom type of my plugin. It's a Dart type.
So, if the app crashes because of `Uri.parse`, then it's not related to my plugin, but on Flutter/Dart itself.

**Comment by pichillilorenzo** [comment]
As you can read from the official Dart documentation [here](https://api.dart.dev/stable/2.12.0/dart-core/Uri/parse.html), if the `uri` string is not valid as a URI or URI reference, `Uri.parse` will throw a `FormatException`.

**Comment by ruthvik-github** [comment]
But when Url is used in the plugin and if it is not properly formatted plugin is closing the app.
I did not see Format Exception in the stackTrace.
I have noticed this problem even before the url is still string in the earlier stage of the plugin. 
plugin is closing  the app when url passed to it not a proper url.
