### ISSUE TITLE
can you add placeholder:CircularProgressIndicator() for InAppWebView

### ISSUE THREAD

**Issue by ushang000** [pichillilorenzo/flutter_inappwebview#71]
example used LinearProgressIndicator(),but i want to use CircularProgressIndicator() and location at Center, such as placeholder of InAppWebView,
can you add it? or hava any idea.
3Q

**Comment by pichillilorenzo** [comment]
Created an example project using both progress indicator at: https://github.com/pichillilorenzo/flutter_inappwebview_examples/tree/main/progress_indicator
