### ISSUE TITLE
当遇到重定向网页的时候，无法回退，反复刷新

### ISSUE THREAD

**Issue by whysoseriousjoker** [pichillilorenzo/flutter_inappwebview#712]
测试这个url：
http://m.news.baidu.com/news?fr=mohome&$pubpathUnescape

**Comment by pichillilorenzo** [comment]
I tested that URL with real iPhone 12 (iOS 14.4) and Android Emulator API 29 and it's working as expected.
This is my test code:
```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(MaterialApp(
      home: MyApp()
  ));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),);

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          appBar: AppBar(title: Text("InAppWebView example")),
          body: SafeArea(
              child: Column(children: <Widget>[
                Expanded(
                  child: InAppWebView(
                    initialUrlRequest: URLRequest(url: Uri.parse("https://news.baidu.com/news?fr=mohome&\$pubpathUnescape#/")),
                    initialOptions: options,
                  ),
                ),
              ])),
    );
  }
}
```

I think there is something in your code that causes the error.
Could you post a code example?

**Comment by whysoseriousjoker** [comment]
感谢回复
你的测试代码没有添加如下代码：（然后你再试试）
`shouldOverrideUrlLoading: (controller, request) async { 
  var url = request.url; 
  var uri = Uri.parse(url); 
  if (!["http", "https", "file", 
    "chrome", "data", "javascript", 
    "about"].contains(uri.scheme)) { 
    if (await canLaunch(url)) { 
      // Launch the App 
      await launch( 
        url, 
      ); 
      // and cancel the request 
      return ShouldOverrideUrlLoadingAction.CANCEL; 
    } 
  } 
  return ShouldOverrideUrlLoadingAction.ALLOW; 
}, `

**Comment by whysoseriousjoker** [comment]
感谢回复
你的测试代码没有添加如下代码：（然后你再试试）
`shouldOverrideUrlLoading: (controller, request) async { 
  var url = request.url; 
  var uri = Uri.parse(url); 
  if (!["http", "https", "file", 
    "chrome", "data", "javascript", 
    "about"].contains(uri.scheme)) { 
    if (await canLaunch(url)) { 
      // Launch the App 
      await launch( 
        url, 
      ); 
      // and cancel the request 
      return ShouldOverrideUrlLoadingAction.CANCEL; 
    } 
  } 
  return ShouldOverrideUrlLoadingAction.ALLOW; 
}, `

**Comment by whysoseriousjoker** [comment]
感谢回复
你的测试代码没有添加如下代码：（然后你再试试）
`shouldOverrideUrlLoading: (controller, request) async { 
  return ShouldOverrideUrlLoadingAction.ALLOW; 
}, `

**Comment by whysoseriousjoker** [comment]
我录制了一个视频，请看下
http://publicfile.x-colour.cn/c7d95eee34197cb9bf39bcdc557405a3.mp4

**Comment by ioschangnan-github** [comment]
我也遇到了这个问题，在iOS设备上，打开https:www.baidu.com，一直反复刷新，打不开网页。在安卓设备上是可以的。
不过题主这个链接iOS我这边是可以打开的。
