### ISSUE TITLE
Facebook Image Not Loading while clicking on 'view full size'

### ISSUE THREAD

**Issue by nilotpalkapri** [pichillilorenzo/flutter_inappwebview#716]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   2.0.1  |
| Plugin version       |  Dart 2.12.0 |
| Android version      |  SDK 29 (Android 9) |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Redmi Note 5 Pro
## Description
Whenever clicking to see in full size, returning a blank screen with the below error. 
The error location showing is 'flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.1.0+4/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java', line 569
**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat   
 java.lang.IllegalArgumentException: width and height must be > 0
W/System.err( 1891):    at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
W/System.err( 1891):    at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
W/System.err( 1891):    at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
W/System.err( 1891):    at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
W/System.err( 1891):    at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView$8.run(InAppWebView.java:569)
W/System.err( 1891):    at android.os.Handler.handleCallback(Handler.java:873)
W/System.err( 1891):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 1891):    at android.os.Looper.loop(Looper.java:201)
W/System.err( 1891):    at android.app.ActivityThread.main(ActivityThread.java:6810)
W/System.err( 1891):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1891):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err( 1891):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by pichillilorenzo** [comment]
Please, post a code example in order to reproduce this error

**Comment by nilotpalkapri** [comment]
> Please, post a code example in order to reproduce this error. Probably you are taking the screenshot too early from the webview

I have just checked out, the same error persist in your own app also. 'Flutter Browser' . Hope you can reproduce from there easily

**Comment by pichillilorenzo** [comment]
Nope, I'm not able to reproduce that. I can open the image full screen without problems.
Please post steps and code to reproduce that. Also, make a screen recording to better understand your scenario.

However, it seems you want to take a screenshot of the webview (the error/warning is coming from that native Android method).
As the official doc says, the `takeScreenshot` method returns `null` if it wasn't be able to take it.
So, in your case, that method is returning `null` because probably your webview is not drawn yet, so it isn't ready enough to take it.
In fact, from the warning message, we know that the `width` and/or the `height` of the **native** WebView still `0` at that time.
If you need to take a screenshot, you can take it, for example, on the `onLoadStop` event.

If you can't provide any other useful information, then I cannot help you more than that.

**Comment by nilotpalkapri** [comment]
> Nope, I'm not able to reproduce that. I can open the image full screen without problems.
> Please post steps and code to reproduce that. Also, make a screen recording to better understand your scenario.
> 
> However, it seems you want to take a screenshot of the webview (the error/warning is coming from that native Android method).
> As the official doc says, the `takeScreenshot` method returns `null` if it wasn't be able to take it.
> So, in your case, that method is returning `null` because probably your webview is not drawn yet, so it isn't ready enough to take it.
> In fact, from the warning message, we know that the `width` and/or the `height` of the **native** WebView still `0` at that time.
> If you need to take a screenshot, you can take it, for example, on the `onLoadStop` event.
> 
> If you can't provide any other useful information, then I cannot help you more than that.

Yes you got it right, the problem is with loading the page. Actually I was talking the screenshot immediately after loadstop. But this didn't work during onCreateWindow event. So now I am pushing and poping a local page to give some time to load the new page properly, and it is now working.
