### ISSUE TITLE
Specifying port in base url in loaddata() request crashes app

### ISSUE THREAD

**Issue by dougr583r** [pichillilorenzo/flutter_inappwebview#720]
If I set the base url on a loaddata call like this:

baseUrl: Uri.parse('http://localhost:8080/assets/')

I get the following error for each <img tag in the html I'm trying to load:

flutter: Error: type 'List<dynamic>' is not a subtype of type 'List<int>' in type cast #0      InAppLocalhostServer.start.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:flutter_inappwebview/src/in_app_localhost_server.dart:42
#1      InAppLocalhostServer.start.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:flutter_inappwebview/src/in_app_localhost_server.dart:41
#2      _rootRunUnary (dart:async/zone.dart:1362:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#8      _StreamController._add (dart:async/stream_controller.dart:607:7)
#9      _StreamController.add (dart:async/stream_controller.dart:554:5)
#10     _HttpSe<…>

This worked in earlier versions.

**Comment by pichillilorenzo** [comment]
It will be fixed with next release

**Comment by pichillilorenzo** [comment]
New version 5.2.0 with fix released
