### ISSUE TITLE
Need onDownloadFinished event

### ISSUE THREAD

**Issue by nilotpalkapri** [pichillilorenzo/flutter_inappwebview#721]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description
Need onDownloadFinished event so that I can show some dialog when download get completed. Also need the file saved directory so that user can open the file from the alert dialog.
Is there any other way available to deal with this. Because currently it is showing a silent notification.
**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by pichillilorenzo** [comment]
There is no `onDownloadFinished` event.
If you need to download files, as already written in the official API, you can use, for example, the [flutter_downloader](https://pub.dev/packages/flutter_downloader) or any other plugin you want.
If you are searching for the `onDownloadFinished` event or something similar, then you should check that plugin or the one that allows you to download files.

Also, just to be clear, the `onDownloadStart` event doesn't start in any sense the download itself.
In fact, you need to use other plugins, such as [flutter_downloader](https://pub.dev/packages/flutter_downloader), to effectively download files.
So, the `onDownloadStart` event just warns you that there could be a request for a file download.

**Comment by nilotpalkapri** [comment]
> There is no `onDownloadFinished` event.
> If you need to download files, as already written in the official API, you can use, for example, the [flutter_downloader](https://pub.dev/packages/flutter_downloader) or any other plugin you want.
> If you are searching for the `onDownloadFinished` event or something similar, then you should check that plugin or the one that allows you to download files.
> 
> Also, just to be clear, the `onDownloadStart` event doesn't start in any sense the download itself.
> In fact, you need to use other plugins, such as [flutter_downloader](https://pub.dev/packages/flutter_downloader), to effectively download files.
> So, the `onDownloadStart` event just warns you that there could be a request for a file download.

Thanks, you are amazing, very quick response!
Can you please help me with one more feature, like I want to save and autofill login credentials in webview pages, is it possible?
