### ISSUE TITLE
Translating webpages

### ISSUE THREAD

**Issue by nilotpalkapri** [pichillilorenzo/flutter_inappwebview#725]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description
Is it possible to translate webpages in webview. If yes please guide me, I don't have any idea about implementation..

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by EArminjon** [comment]
Actually, InAppWebView on IOS seems use phone system language. Not very cool when translate app because webview stuck in english for example...

**Comment by pichillilorenzo** [comment]
@EArminjon The plugin is not doing any translation. If on iOS "stuck" in english, this depends on how the native WebView works, that is `WKWebView` on iOS.
Also, if the system language is in english, well, I think that is the correct behavior using the english for that WebView. It will be very strange if this don't happen.
If you need translate something, you need to do in other ways and implement it by yourself. Translating webpages is not a feature of WebViews.
Probably you can do this using the Google Translation API https://translate.google.com/intl/en/about/forbusiness/
