### ISSUE TITLE
White Label for callHandler

### ISSUE THREAD

**Issue by UMUTBAYGUT** [pichillilorenzo/flutter_inappwebview#727]
## Environment

**Flutter version: 2.0.2
**Plugin version:- 
**Android version:-
**iOS version:**
**Xcode version:**  
**Device information:-

## Description

```
<script>
   window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
     window.flutter_inappwebview.callHandler('handlerFoo').then(function(result) {
       console.log(result);
     });

     window.flutter_inappwebview.callHandler('handlerFooWithArgs', 1, true, ['bar', 5], {foo: 'baz'}).then(function(result) {
       console.log(result);
     });
   });
</script>
```
can we change the window.flutter_inappwebview.callHandler name ?I mean can I use windows.{custom_name}.callHandler() ?

**Comment by pichillilorenzo** [comment]
`window.flutter_inappwebview` is used also internally.
If you need a custom name, you can simply wrap it inside another javascript function or object.
For example:
```javascript
window.myCustomObj = {
    callHandler: window.flutter_inappwebview.callHandler
};
```
