### ISSUE TITLE
In-line webview on iOS camera permission

### ISSUE THREAD

**Issue by dustincatap** [pichillilorenzo/flutter_inappwebview#729]
I've granted the permissions for camera/microphone access (asked permission, add relevant keys in info.plist), but the webpage I load still doesn't have access to camera.

Here is how I build the widget:

```dart
InAppWebView(
        initialUrl: model.param.url,
        initialOptions: InAppWebViewGroupOptions(
          crossPlatform: InAppWebViewOptions(
            useShouldOverrideUrlLoading: true,
            mediaPlaybackRequiresUserGesture: false,
          ),
          android: AndroidInAppWebViewOptions(
            useShouldInterceptRequest: true,
          ),
          ios: IOSInAppWebViewOptions(
            allowsInlineMediaPlayback: true,
          ),
        ),
        onLoadStart: (controller, url) {
          model.onUrlLoaded(url);
        },
        shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
          return ShouldOverrideUrlLoadingAction.ALLOW;
        },
        androidOnPermissionRequest: (controller, origin, resources) async {
          return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
        },
      );
```

I'm running on iOS 13.3, Flutter 1.22.6. Using the plugin version `flutter_inappwebview: ^4.0.0`

**Comment by pichillilorenzo** [comment]
Check the [WebRTC](https://github.com/pichillilorenzo/flutter_inappwebview#webrtc) and  [WebRTC on iOS](https://github.com/pichillilorenzo/flutter_inappwebview#webrtc-on-ios) sections to be sure you have added all the necessary permissions.
Other than that, there is nothing more to add.

**Comment by JaosnHsieh** [comment]
`iOS v15.5`
`flutter v3.0`

One of the application widgets uses InAppWebView with a page that is using camera/micro.

```dart
return Scaffold(
    appBar: AppBar(
    title: const Text('XPTO'),),
    body: SafeArea(
      child: Column(children: <Widget>[
        Expanded(
          child: Stack(
            children: [
              InAppWebView(
                key: webViewKey,
                initialUrlRequest: URLRequest(url: Uri.parse(app.url.toString())),
                initialOptions: options,
                androidOnPermissionRequest: (InAppWebViewController controller, String origin, List<String> resources) async {
                  return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
                },
                onWebViewCreated: (controller) async  {
                  webViewController = controller;
                },
          )])
        )
      ]
  )
));

```

the options object for the InAppWebView is:

```
InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
  crossPlatform: InAppWebViewOptions(
    mediaPlaybackRequiresUserGesture: false,
    javaScriptEnabled: true
  ),
  ios: IOSInAppWebViewOptions(
    allowsInlineMediaPlayback: true,
    allowsAirPlayForMediaPlayback: true
  ));
On main.dart I've put the permission request

  WidgetsFlutterBinding.ensureInitialized();

  await Permission.camera.request();
  await Permission.microphone.request();
On Inflo.plist

<key>NSCameraUsageDescription</key>
<string>This thing use camera</string>
<key>NSMicrophoneUsageDescription</key>
<string>This thing use the microfone</string>
<key>UILaunchStoryboardName</key>

```
On pod:

```
        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

```
Everything is working fine.

The problem is that every time i open the InAppWebView, the message "Allow ... to use your camera and microphone?" appears.

as the image 

![image](https://user-images.githubusercontent.com/15373520/170409485-b363e9d0-6ac1-4b64-ab6c-e150285d6df4.png)


Do you happen to know how to prevent that permission dialog message to show up?

**Comment by fahmisatrio** [comment]
> `iOS v15.5` `flutter v3.0`
> 
> One of the application widgets uses InAppWebView with a page that is using camera/micro.
> 
> ```dart
> return Scaffold(
>     appBar: AppBar(
>     title: const Text('XPTO'),),
>     body: SafeArea(
>       child: Column(children: <Widget>[
>         Expanded(
>           child: Stack(
>             children: [
>               InAppWebView(
>                 key: webViewKey,
>                 initialUrlRequest: URLRequest(url: Uri.parse(app.url.toString())),
>                 initialOptions: options,
>                 androidOnPermissionRequest: (InAppWebViewController controller, String origin, List<String> resources) async {
>                   return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
>                 },
>                 onWebViewCreated: (controller) async  {
>                   webViewController = controller;
>                 },
>           )])
>         )
>       ]
>   )
> ));
> ```
> 
> the options object for the InAppWebView is:
> 
> ```
> InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
>   crossPlatform: InAppWebViewOptions(
>     mediaPlaybackRequiresUserGesture: false,
>     javaScriptEnabled: true
>   ),
>   ios: IOSInAppWebViewOptions(
>     allowsInlineMediaPlayback: true,
>     allowsAirPlayForMediaPlayback: true
>   ));
> On main.dart I've put the permission request
> 
>   WidgetsFlutterBinding.ensureInitialized();
> 
>   await Permission.camera.request();
>   await Permission.microphone.request();
> On Inflo.plist
> 
> <key>NSCameraUsageDescription</key>
> <string>This thing use camera</string>
> <key>NSMicrophoneUsageDescription</key>
> <string>This thing use the microfone</string>
> <key>UILaunchStoryboardName</key>
> ```
> 
> On pod:
> 
> ```
>         ## dart: PermissionGroup.camera
>         'PERMISSION_CAMERA=1',
> 
>         ## dart: PermissionGroup.microphone
>         'PERMISSION_MICROPHONE=1',
> ```
> 
> Everything is working fine.
> 
> The problem is that every time i open the InAppWebView, the message "Allow ... to use your camera and microphone?" appears.
> 
> as the image
> 
> ![image](https://user-images.githubusercontent.com/15373520/170409485-b363e9d0-6ac1-4b64-ab6c-e150285d6df4.png)
> 
> Do you happen to know how to prevent that permission dialog message to show up?

I followed the docs given, everything works fine in android.
GPS and camera permission works as expected.

but in iOS, they always reprompting the permission for gps and camera everytime the apps want to access that interfaces.
if someone found a solution, really appreciate if you can share it.
Thanks
