### ISSUE TITLE
Flutter 2.0.2 without nullSafety (Version 5.1.0+4)

### ISSUE THREAD

**Issue by mauriceraguseinit** [pichillilorenzo/flutter_inappwebview#730]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   2.0.2            |
| Plugin version       |   5.1.0+4            |

Device information: all androids

## Description

After updating my flutter version to 2.0.2 (from 1.22.6) i get errors while building the app for android (ios works fine)

 `
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/Foo/projects/BAM/energielabel_app/build/app/intermediates/merged_manifests/debug/AndroidManifest.xml:17: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_inappwebview...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Foo/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.1.0+4/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'flutter_inappwebview'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in /Users/Foo/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.1.0+4/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Exception: The plugin flutter_inappwebview could not be built due to the issue above.
`

**Comment by dreamer2q** [comment]
Is this the problem of gradle version?

In my env, this is no build errors

**Comment by UjjwaRaijada** [comment]
The problem seems to be in the package. It seems there is a slight error.

CURRENT SITUATION
/android/gradle/wrapper/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

TO BE CHANGED
/android/gradle/wrapper/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

**Comment by UjjwaRaijada** [comment]
> Is this the problem of gradle version?
> 
> In my env, this is no build errors

have you update your flutter package? Once you migrate to null safety, you might face this problem.

**Comment by dreamer2q** [comment]
> > Is this the problem of gradle version?
> > In my env, this is no build errors
> 
> have you update your flutter package? Once you migrate to null safety, you might face this problem.

I face no build error, but this plugin seems to have bug with latest 5.1.0 versions

see issue #731

**Comment by WieFel** [comment]
+1

**Comment by pichillilorenzo** [comment]
It’s already fixed on master branch. Fix will be available in the next release soon

**Comment by ErikDohmen** [comment]
Is there any ETA on when the next release will come other than soon? Is there anything I can do to help to bring up the next release?

**Comment by pichillilorenzo** [comment]
it should be today!

**Comment by ErikDohmen** [comment]
perfect!

**Comment by pichillilorenzo** [comment]
New version 5.2.0 released
