### ISSUE TITLE
cannot render anything from specified url

### ISSUE THREAD

**Issue by dreamer2q** [pichillilorenzo/flutter_inappwebview#731]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.0.2      |
| Plugin version       | 5.1.0+4 |
| Android version      |   10     |
| iOS version          |        null      |
| Xcode version        |         null    |

Device information: 

## Description

in any version >= 5.0.0 InAppWebview  cannot open url https://www.yuque.com/nieyulin/lunpyu/uus9zb

**Expected behavior:** 

just like the browser, showing the page.

**Current behavior:** 

total full white screen, no content is visible, no reaction.

## Steps to reproduce

```dart
InAppWebView(
            initialUrlRequest: URLRequest(
               url: Uri.parse('https://www.yuque.com/nieyulin/lunpyu/uus9zb'),
           ),
    )
```

**Comment by dreamer2q** [comment]
Its really strange, InApWebview version 4.0.0 can handle this url normally, but version 5 cant.

I wonder what's wrong with it?

**Comment by pichillilorenzo** [comment]
Tested your URL on iOS 14.4 and Android API 30 and it works.

This is my test code:
```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(MaterialApp(
      home: MyApp()
  ));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),);

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("InAppWebView example")),
      body: SafeArea(
          child: Column(children: <Widget>[
            Expanded(
              child: InAppWebView(
                initialOptions: options,
                initialUrlRequest: URLRequest(url: Uri.parse("https://www.yuque.com/nieyulin/lunpyu/uus9zb")),
              ),
            ),
          ])),
    );
  }
}
```

Here is the screenshot:
![Schermata 2021-03-18 alle 17 36 48](https://user-images.githubusercontent.com/5956938/111662943-a5f3ba80-8810-11eb-983d-7818b77a0dfd.png)

**Comment by dreamer2q** [comment]
My goodness.

Let me find what's wrong with me.

Anyway, thank you for your effort .
