### ISSUE TITLE
about keyboard in iphone 12

### ISSUE THREAD

**Issue by jinjilynn** [pichillilorenzo/flutter_inappwebview#733]
when focus on input html tag, the keyboard can't pop up completely

![image](https://user-images.githubusercontent.com/12596042/111823386-dd04c180-891f-11eb-8a7c-1a4c0f80045f.png)

**Comment by pichillilorenzo** [comment]
Please, take a look at https://stackoverflow.com/questions/24420873/xcode-6-keyboard-does-not-show-up-in-simulator

**Comment by jinjilynn** [comment]
> Please, take a look at https://stackoverflow.com/questions/24420873/xcode-6-keyboard-does-not-show-up-in-simulator

thanks
