### ISSUE TITLE
Huawei's unique security keyboard can't  show up when the input type is password 

### ISSUE THREAD

**Issue by jinjilynn** [pichillilorenzo/flutter_inappwebview#734]
W/libEGL  (24717): EGLNativeWindowType 0x7473e2cf90 disconnect failed
I/HiTouch_HiTouchSensor(24717): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(24717): onAttached, package=com.hc_apm_flutter_mobile, windowType=2037, mHiTouchRestricted=true
D/mali_winsys(24717): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(24717): disableOutlineDraw is true
3
E/InputMethodManager(24717): b/117267690: Failed to get fallback IMM with expected displayId=113 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{8dcd207 VFEDHVCL. .F...... 0,0-1080,2034}

**Comment by pichillilorenzo** [comment]
On Android, for keyboard issues, you should set `useHybridComposition: true` to enable Hybrid Composition.
Without it, you will have issues with keyboard. That is a limitation of Flutter PlatformViews and not of the plugin itself

**Comment by HobsonCheng** [comment]
> On Android, for keyboard issues, you should set `useHybridComposition: true` to enable Hybrid Composition. Without it, you will have issues with keyboard. This is a limitation of Flutter PlatformViews and not of the plugin itself

solve my problem,thx
