### ISSUE TITLE
网页内容长度过长,导致系统崩溃

### ISSUE THREAD

**Issue by BoyYangyang** [pichillilorenzo/flutter_inappwebview#735]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.0.2      |
| Plugin version       |         5.1.0+4      |
| Android version      |        android 8.0(华为 荣耀V8,内存4G)       |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
加载的网页内容过多,就会闪退,内容少的话能正常运行
W/libEGL  (26528): dlopen failed: library "libEGL_vr.so" not found
I/flutter (26528): ----onLoadStart-------https://test-m.c5game.com/post/simple/844069457233969152
I/zygote64(26528): Do partial code cache collection, code=59KB, data=58KB
I/zygote64(26528): After code cache collection, code=59KB, data=58KB
I/zygote64(26528): Increasing code cache capacity to 256KB
I/flutter (26528): ----onLoadStop-------https://test-m.c5game.com/post/simple/844069457233969152
I/flutter (26528): cookies 
I/flutter (26528): ----onLoadStop-------https://test-m.c5game.com/post/simple/844069457233969152
I/flutter (26528): ===h5高度=====5348
W/PlatformViewsController(26528): Creating a virtual display of size: [1080, 16074] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 1812].

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
It's a warning coming from Flutter itself when you use an Android `PlatformView` using a virtual display.
On Android, creating a very long webpage without using Android Hybrid Composition will crash your app.
This is a limitation of Flutter itself and not of this plugin.
So, on Android, if you need to do that, you need to set `useHybridComposition: true` Android-specific webview option.
However, if possible, you should avoid doing something like that.
