### ISSUE TITLE
Invitation to travel in time

### ISSUE THREAD

**Issue by gabxap** [pichillilorenzo/flutter_inappwebview#738]
Hii everyone! I just wanted to share with you my latest project made with the flutter_inappwebview package. It is a 90s retro design web browser inspired by Netscape Navigator and Internet Explorer.  I think this can be a really nice showcase example for the package, thanks to the creator for making it possible. I hope you can give it a shot and send me recommendations!

Google Play: [https://play.google.com/store/apps/details?id=com.gabxap.retrobrowser]( https://play.google.com/store/apps/details?id=com.gabxap.retrobrowser)

App Store: [https://apps.apple.com/us/app/retro-browser/id1554974118](https://apps.apple.com/us/app/retro-browser/id1554974118)

**Comment by pichillilorenzo** [comment]
Hello @gabxap! You can add your app to the official [Showcase](https://inappwebview.dev/showcase/) page!
Just follow the instruction on the [Submit App](https://inappwebview.dev/submit-app/) page.
You need to make a PULL REQUEST to the [flutter_inappwebview-showcase-data repository](https://github.com/pichillilorenzo/flutter_inappwebview-showcase-data/blob/master/data.json).

Thanks for using it 😄  👍

**Comment by pichillilorenzo** [comment]
App published correctly! You can see it on the Showcase page or https://inappwebview.dev/flutter-app/retro-browser-90s-nostalgic-web-browser/
