### ISSUE TITLE
Got error when I build example 

### ISSUE THREAD

**Issue by obweix** [pichillilorenzo/flutter_inappwebview#740]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       Flutter 1.22.6 • channel stable        |
| Plugin version       |           flutter_inappwebview: ^5.2.0      |
| Android version      |      11.0         |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:plugin_platform_interface

For solutions, see https://dart.dev/go/unsound-null-safety

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
This is not related to this plugin.
As you see, it's related to the `plugin_platform_interface` plugin or another of yours that uses it.

**Comment by nyck33** [comment]
I can run with 
```
flutter run --no-sound-null-safety
```

**Comment by nyck33** [comment]
I still don't understand why this error occurs though @pichillilorenzo
