### ISSUE TITLE
when InAppWebView is put into a  SingleChildScrollView widget

### ISSUE THREAD

**Issue by jinjilynn** [pichillilorenzo/flutter_inappwebview#741]
E/InputMethodManager(21012): b/117267690: Failed to get fallback IMM with expected displayId=17 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{d5d0fd9 VFEDHVCL. .F...... 0,0-1080,1940}
W/ContentCatcher(21012): Failed to notify a WebView
E/InputMethodManager(21012): b/117267690: Failed to get fallback IMM with expected displayId=17 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{d5d0fd9 VFEDHVCL. ......ID 0,0-1080,1940}
E/WindowManager(21012): BadTokenException or InvalidDisplayException, clean up.

**Comment by pichillilorenzo** [comment]
They are just warnings. If you don't have any problem, just ignore it.
You can also set the Android-specific option `useHybridComposition: true` in order to enable Android Hybrid Composition. This way it will resolve keyboard issues.
However, I don't know what you want to achieve, but using it inside a `SingleChildScrollView` may cause you a lot of trouble.

**Comment by jinjilynn** [comment]
E/MethodChannel#flutter/platform_views(21012): Failed to handle method call
E/MethodChannel#flutter/platform_views(21012): android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.Binder@4924a3 is not valid; is your activity running?

it seems the option useHybridComposition hasn't defined in version 4.0.0+4

**Comment by pichillilorenzo** [comment]
No, you should use the latest version

**Comment by jinjilynn** [comment]
what i want to achieve is  there is some situation that I need to render an area under InAppWebView to lift the InAppWebView area without squeezing InAppWebView.

its ok after i upgrade the os
