### ISSUE TITLE
Howto disable(/intercept url of) back button?

### ISSUE THREAD

**Issue by 6heads** [pichillilorenzo/flutter_inappwebview#743]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.0.3             |
| Plugin version       | 5.2.0               |
| Android version      | 7, 9             |

Device information: Redmi Note 4, Fire HD 8 (10th generation)

## Description
I want to intercept all called urls. That's why I overrode _shouldOverrideUrlLoading_ This works as expected for clicking links, but when I press 'hardware back button' the method isn't hit.

**Expected behavior:** 
_shouldOverrideUrlLoading_ gets called.

**Current behavior:** 
_shouldOverrideUrlLoading_ doesn't get called.

## Steps to reproduce
1. start InAppBrowser

```dart
widget.browser.openUrlRequest(
        urlRequest: URLRequest(url: Uri.parse("https://google.com")),
        options: InAppBrowserClassOptions(
            crossPlatform: InAppBrowserOptions(
                hideUrlBar: true, hideToolbarTop: true, hideProgressBar: true),
            inAppWebViewGroupOptions: InAppWebViewGroupOptions(
                crossPlatform: InAppWebViewOptions(
              useShouldOverrideUrlLoading: true,
              disableContextMenu: true,
              useOnLoadResource: true,
            ))));
```

2. click some links - _shouldOverrideUrlLoading_ gets hit
3. navigate back - nothing happens

**Comment by pichillilorenzo** [comment]
Unfortunately `shouldOverrideUrlLoading` is not fired on Android when you move between history elements.
That's a limitation of the native WebView event and not of this plugin.
However, I'm adding a new InAppBrowser options in the next release named `allowGoBackWithBackButton` that you can set to `false` to block go back when the user uses the Android back button.

**Comment by pichillilorenzo** [comment]
So, you can achieve it using `allowGoBackWithBackButton` this way:
```dart
widget.browser.openUrlRequest(
  urlRequest: URLRequest(url: Uri.parse("https://google.com")),
  options: InAppBrowserClassOptions(
      crossPlatform: InAppBrowserOptions(
          hideUrlBar: true, hideToolbarTop: true, hideProgressBar: true),
      android: AndroidInAppBrowserOptions(
        allowGoBackWithBackButton: false,
      ),
      inAppWebViewGroupOptions: InAppWebViewGroupOptions(
          crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        disableContextMenu: true,
        useOnLoadResource: true,
      ))));
```

**Comment by pichillilorenzo** [comment]
new version 5.2.1 released with this new option!
