### ISSUE TITLE
Managing focus

### ISSUE THREAD

**Issue by hworld** [pichillilorenzo/flutter_inappwebview#744]
## Environment

**Flutter version:** 2.0.2
**Plugin version:**  5.2.0
**Android version:**  9.0
**iOS version:** 14

## Description

**What you'd like to happen:** 
I'm using flutter_inappwebview to load in our text editor on Android and iOS. We need a way to manage the focus state of the text box within the webview. I've tried focusing/blurring within javascript and it's not actually doing anything. I've looked through all the code for the word "focus" and there doesn't seem to be a way to focus the actual window, or an element within it. There is a function to get the text selection and to clear the focus, as well as callbacks to check window focus, but it seems that we can't actually modify that focus state.

I'm not sure what to do, if there's any hacks that can be done to manage the focus state (autofocusing when the webview first renders). I might also be missing something.

**Comment by mohit-chauhan-mi** [comment]
@hworld I'm also getting same issue, did you find any solution?

**Comment by mohit-chauhan-mi** [comment]
@tneotia I also tried to manage the focus but it's not working I think issue is with inapp_webview plugin

**Comment by tneotia** [comment]
@pichillilorenzo do you have any input on this? I'd really like to know if what @hworld said is possible.
