### ISSUE TITLE
Can't open the camera directly

### ISSUE THREAD

**Issue by lolove** [pichillilorenzo/flutter_inappwebview#746]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment
Pixel 2

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |1.26.0|
| Plugin version       | 4.0.1+1              |
| Android version      |  30             |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description
**Expected behavior:** 
I expected to use the input box from HTML to open the native camera directly.
<br/>
**Current behavior:** 
I can open the camera by clicking the input box, but it always shows an alert to choosing open a photo gallery or camera.
(It can open the camera directly in chrome)
## Steps to reproduce

1. Get a camera permission
```
import 'package:permission_handler/permission_handler.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Permission.camera.request();

  runApp(MyApp());
}
```
2. Add additional configurations
```
<provider
    android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
    android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />
</provider>
```

3. HTML
```
<h3>input type="file" accept="video/*" capture="user"</h3>
<input type="file" accept="video/*" capture="user" >
```

## Images   
![image](https://user-images.githubusercontent.com/37701765/112415874-979d2580-8d5f-11eb-8a16-4949baffdd0a.png)

**Comment by pichillilorenzo** [comment]
Unfortunately, this behavior is not implemented yet!
I will work on it!

**Comment by ederluca** [comment]
Good Morning

Has there been any progress in this case?

**Comment by pichillilorenzo** [comment]
@ederluca not yet.

**Comment by Thomaslay7** [comment]
Any progress in this issue?

**Comment by john730** [comment]
Hi @pichillilorenzo, thanks for looking into this. May I ask on when would this be fixed?

**Comment by mimiaopp** [comment]
我flutter1.0的时候就有这个问题,到现在还在,哈哈哈

**Comment by aJIEw** [comment]
I used [rahuldev91](https://github.com/pichillilorenzo/flutter_inappwebview/issues/846#issuecomment-873542917)'s workaround in #846, tested on android, works fine.

**Comment by acalephx** [comment]
Any progress in this issue?

**Comment by sunpulun** [comment]
same issue, is there any solution ? please, @pichillilorenzo

**Comment by DongXuanLei** [comment]
Any progress in this issue?

**Comment by sunpulun** [comment]
this issue only on android, you can do  it in Android file WebChromeClient. for me it worked perfect

**Comment by pichillilorenzo** [comment]
Feature added starting from version `5.5.0`
