### ISSUE TITLE
ContextMenu Not Working

### ISSUE THREAD

**Issue by 94wogus** [pichillilorenzo/flutter_inappwebview#747]
- [o] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [o] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [o] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [o] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git |
| Plugin version       | ^5.2.0 |
| Android version      | 10 |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Manufacturer: LG
model: LM-G900N

## Description

**Expected behavior:** 
i follow contextmenu base usage [ContextMenu](https://inappwebview.dev/docs/context-menu/basic-usage/)
So I thought it would be a copy/paste of text.

**Current behavior:** 
Currently, text cannot be copied/pasted.

## main.dart
```dart
Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  await Permission.camera.request();
  await Permission.microphone.request();

  await Firebase.initializeApp();

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );

  runApp(SaivApp());
}
```

## Webview.dart
```dart
import 'dart:io' show Platform;
import 'package:flutter/material.dart';

import 'package:flutter_inappwebview/flutter_inappwebview.dart';

import 'package:saiv/config/translate.dart';
import 'package:saiv/component/common/pageHeader.dart';

class WebViewPage extends StatefulWidget {
  const WebViewPage({required this.title, required this.url});

  final String title;
  final Uri url;

  @override
  _WebViewPageState createState() => _WebViewPageState();
}

class _WebViewPageState extends State<WebViewPage> {
  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController? webViewController;
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(javaScriptEnabled: true),
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),
  );
  late ContextMenu contextMenu;

  @override
  void initState() {
    super.initState();

    contextMenu = ContextMenu(
        menuItems: [
          ContextMenuItem(
              androidId: 1,
              iosId: "1",
              title: "Special",
              action: () async {
                final snackBar = SnackBar(
                  content: Text("Special clicked!"),
                  duration: Duration(seconds: 1),
                );
                ScaffoldMessenger.of(context).showSnackBar(snackBar);
              })
        ],
        onCreateContextMenu: (hitTestResult) async {
          String selectedText =
              await webViewController?.getSelectedText() ?? "";
          final snackBar = SnackBar(
            content: Text(
                "Selected text: '$selectedText', of type: ${hitTestResult.type.toString()}"),
            duration: Duration(seconds: 1),
          );
          ScaffoldMessenger.of(context).showSnackBar(snackBar);
        },
        onContextMenuActionItemClicked: (menuItem) {
          var id = (Platform.isAndroid) ? menuItem.androidId : menuItem.iosId;

          final snackBar = SnackBar(
            content: Text(
                "Menu item with ID $id and title '${menuItem.title}' clicked!"),
            duration: Duration(seconds: 1),
          );
          ScaffoldMessenger.of(context).showSnackBar(snackBar);
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PageHeader(
          key: UniqueKey(),
          title: Translations.of(context).trans(widget.title)),
      body: Column(children: <Widget>[
        Expanded(
          child: InAppWebView(
            initialUrlRequest: URLRequest(url: widget.url),
            contextMenu: contextMenu,
            initialOptions: options,
            onWebViewCreated: (InAppWebViewController controller) {
              webViewController = controller;
            },
          ),
        ),
      ]),
      backgroundColor: Colors.white,
    );
  }
}

```

**Comment by pichillilorenzo** [comment]
I just test the code example from the [Context Menu - basic usage](https://inappwebview.dev/docs/context-menu/basic-usage/) and it's working as expected:

https://user-images.githubusercontent.com/5956938/112448007-3b7fd480-8d52-11eb-9d28-ae33c925f4f8.mp4

Could you make a screen record of your issue?

**Comment by 94wogus** [comment]
https://user-images.githubusercontent.com/40576978/112564822-4eaca600-8e1f-11eb-9dae-3bdab20e3328.mp4

On the left, the screen was shared with my mobile device.
The right side is the screen where flutter run was executed, and the VS Code window enlarged for debugging.
Currently, the text on the screen is pressed with ACTION_DOWN and ACTION_UP, but the window for copy paste does not appear.

**Comment by pichillilorenzo** [comment]
If you use the exact same code from the code example in ContextMenu basic usage page, does it work? Can you try it please?
Also, if you remove the `contextMenu` property, the default context menu does it work?

**Comment by 94wogus** [comment]
i found what is wrong...
I found out what was wrong with my code.
Currently, the Webview widget was under the GestureDetector widget.
I did the same code as your example, but it seems that the problem was being wrapped in GestureDetector.

Thank you for your kind response.

**Comment by pichillilorenzo** [comment]
Yeah, I think that `GestureDetector`, in your case, is consuming the touch gesture instead of passing it to the WebView.
