### ISSUE TITLE
Android Crash - Failed to get fallback IMM with expected displayId=92

### ISSUE THREAD

**Issue by pushparajakln** [pichillilorenzo/flutter_inappwebview#750]
Android app is crashing when we give more height. 

Code:
Container(
      height: webViewModel.webViewHeight != null ? webViewModel.webViewHeight : 300,
      child: InAppWebView(
        initialUrl: webViewModel.guideUrl,
        onWebViewCreated: (InAppWebViewController webViewController) {
          _webViewController = webViewController;
        },
        onProgressChanged: (controller, progress) async {
          if (_webViewController != null && progress == 100 && isLoaded == false) {
            _webViewController
                .evaluateJavascript(source: "document.body.clientHeight")
                .then((height) {
              setState(() {
                webViewModel.webViewHeight = height is String ? double.parse(height) : height.toDouble();
                isLoaded = true;
              });
            });
          }
        },
      ),
    )

Please find the exception details below,

W/System  (14920): A resource failed to call release. 
W/PlatformViewsController(14920): Creating a virtual display of size: [1300, 19376] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1440, 2392].
V/InputMethodManager(14920): b/117267690: Failed to get fallback IMM with expected displayId=92 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{1d82173 VFEDHVCL. ........ 0,0-1300,1050}
Lost connection to device.

**Comment by pichillilorenzo** [comment]
It's a warning coming from Flutter itself when you use an Android `PlatformView` using a virtual display.
On Android, creating a very long webpage without using Android Hybrid Composition will crash your app.
This is a limitation of Flutter itself and not of this plugin.
So, on Android, if you need to do that, you need to set `useHybridComposition: true` Android-specific webview option.
However, if possible, you should avoid doing something like that.

**Comment by wl1395182472** [comment]
use AnimatedContainer,set its padding like this:
AnimatedContainer(
        duration: Duration(milliseconds: 300),
        curve: Curves.linear,
        padding: EdgeInsets.only(
          top: controller.isShowTopAndBottomBar ? 130.w : 0,
          bottom: controller.isShowTopAndBottomBar ? 150.w : 0,
        ),
        child: inAppWebView(),
      ),

**Comment by danielgomezrico** [comment]
@pichillilorenzo what do you mean by `However, if possible, you should avoid doing something like that.`? avoid doing what? setting hybrid composition?
