### ISSUE TITLE
Target platform macOS is not yet supported by the flutter_inappbrower plugin 

### ISSUE THREAD

**Issue by raghavan-mookiah** [pichillilorenzo/flutter_inappwebview#752]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.0.3         |
| Plugin version       |               |
| Android version      |        30.0.0       |
| iOS version          |           10.15.1    |
| Xcode version        |               |

Device information: 

## Description
Target platform macOS is not yet supported by the flutter_inappbrower plugin 
**Expected behavior:** 
Target platform Ios is working and why it is extended for macOS
**Current behavior:** 
Not working on macOS
## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by pichillilorenzo** [comment]
Well, as the error says, there is no Desktop support at the moment. Only for mobile.
You can track Desktop support here https://github.com/pichillilorenzo/flutter_inappwebview/issues/460
