### ISSUE TITLE
Is there anyway to takeScreenshot without display a WebView on the screen

### ISSUE THREAD

**Issue by kechankrisna** [pichillilorenzo/flutter_inappwebview#754]
I was wondering if you have any solution to screenshot a webview as bitmap without displaying webview on the screen? It can be suggestion for flutter or android native

**Comment by pichillilorenzo** [comment]
It's not possible now. However, I'm working on it.
You will be able to use `HeadlessInAppWebView` (that is a WebView that runs in background) to also take screenshots.

**Comment by pichillilorenzo** [comment]
Published new release `5.3.0`!
Now you can use `HeadlessInAppWebView` to take screenshots without displaying a webview on the screen.
