### ISSUE TITLE
onCreateWindow: onCreateWindowRequest.request.url and all other fields are null on Android when clicking button

### ISSUE THREAD

**Issue by risc98** [pichillilorenzo/flutter_inappwebview#755]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.0.3    |
| Plugin version       |       5.2.1+1        |
| Android version      |        11       |
| iOS version          |          not affected     |
| Xcode version        |         not affected      |

Device information: 
Encountered on Xiaomi Poco F1

## Description
When clicking on a button that has the property target="_blank", the  onCreateWindow-Method is called with a onCreateWindowRequest whose fields are null.
**Expected behavior:** 
onCreateWindowRequest.request.url.toString() should return clicked link

**Current behavior:** 
onCreateWindowRequest.request.url.toString() returns null

## Steps to reproduce
1. InAppWebView with js enabled and supportMultipleWindows: true and  initialUrlRequest:new URLRequest(url: Uri.parse("https://mysebastian.com")),
2. When running the app, click on "Launch on April 12,2021" and then "Launch party registration"
3. Observe onCreateWindowRequest.toString()

**Minimal example:**

import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: InAppWebView(
            initialUrlRequest:
                new URLRequest(url: Uri.parse("https://mysebastian.com")),
            initialOptions: InAppWebViewGroupOptions(
                crossPlatform: InAppWebViewOptions(
                  javaScriptEnabled: true,
                ),
                android:
                    AndroidInAppWebViewOptions(supportMultipleWindows: true)),
            onCreateWindow: (controller, onCreateWindowRequest) async {
              print("DEBUG: " + onCreateWindowRequest.toString());
              return true;
            }));
  }
}

## Stacktrace/Logcat   
DEBUG: {request: {url: null, headers: null, method: GET, body: null, iosAllowsCellularAccess: null, iosAllowsConstrainedNetworkAccess: null, iosAllowsExpensiveNetworkAccess: null, iosCachePolicy: null, iosHttpShouldHandleCookies: null, iosHttpShouldUsePipelining: null, iosNetworkServiceType: null, iosTimeoutInterval: null, iosMainDocumentURL: null}, isForMainFrame: true, androidHasGesture: true, androidIsRedirect: false, iosWKNavigationType: null, iosSourceFrame: null, iosTargetFrame: null, windowId: 1, androidIsDialog: false, iosWindowFeatures: null}

**Comment by risc98** [comment]
I would really appreciate any help you can provide with this issue, thank you in advance!

**Comment by pichillilorenzo** [comment]
That's the correct behavior. You are creating a new window page using javascript `window.open()`.
So, as written in the online API Reference, on Android, the [`request` property](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/NavigationAction/request.html) of the [CreateWindowAction](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/CreateWindowAction-class.html) class (that extends the [NavigationAction](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/NavigationAction-class.html) class) this behavior is the correct one.

Note that this is a limitation of Android WebView itself and not of this plugin. The normal flow would be to create a new instance of a WebView that would manage this new request (because of `window.open()`).

So, on Android, if you need to get the `url` from that request, you need to use some workaround, for example you can create a `HeadlessInAppWebView` using the `windowId` property of the `CreateWindowAction` class and listen for URL change, then grab that URL and load it into your main webview.

Here is a simple code example:
```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(MaterialApp(home: new MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  InAppWebViewController? webViewController;
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    android: AndroidInAppWebViewOptions(
        useHybridComposition: true, supportMultipleWindows: true),
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Android - Create Window Example")),
        body: SafeArea(
          child: Column(children: <Widget>[
            Expanded(
              child: Stack(
                children: [
                  InAppWebView(
                    initialUrlRequest: URLRequest(url: Uri.parse("https://mysebastian.com/")),
                    initialOptions: options,
                    onWebViewCreated: (controller) {
                      webViewController = controller;
                    },
                    onCreateWindow: (controller, createWindowAction) async {
                      print(createWindowAction);

                      var headlessInAppWebView = new HeadlessInAppWebView(windowId: createWindowAction.windowId);
                      headlessInAppWebView.onLoadStart = (headlessController, url) {
                        // wait for the correct URL
                        if (url?.toString() != "about:blank") {
                          print(url);
                          // load it in the main webview
                          controller.loadUrl(urlRequest: URLRequest(url: url));
                          // and dispose the headless webview
                          headlessInAppWebView.dispose();
                        }
                      };
                      headlessInAppWebView.run();
                    },
                  ),
                ],
              ),
            ),
        ])));
  }
}
```

**Comment by risc98** [comment]
You are right! 
Thank you very much, I appreciate it!

**Comment by liuzehnhang** [comment]
headlessInAppWebView.onLoadStart    will be called twice，How to solve
