### ISSUE TITLE
Pull-to-refresh not working in views without scroll

### ISSUE THREAD

**Issue by sgonzalez9450** [pichillilorenzo/flutter_inappwebview#756]
- [V] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [V] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [V] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [V] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | Stav|
| Plugin version       | 5.2.1+1 |
| Android version      | 10 |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Samsung galaxy tab active pro SM-t545
Android 10

## Description
The pull to refresh action, is not working on views that are not scrollable. In the video im attaching below, you can see how the same webview's view, is working or not if you are in portrait or landscape, thats because the landscape's view has an scroll and the portrait one not. 

So, how we can fix this issue? Do we have any workaround or something?

I tried with the gestureRecognizers dragdown and stuff, but its not working as expected, because dragdown refresh all the time.

**Expected behavior:** 
To pull to refresh when u dragdown like when the view is scrollable

**Current behavior:** 
It doesnt do anything, because its not recognizing the action

## Steps to reproduce
Have one view in our webview that its not as big as have an scrollable view, and other view with scroll to confirm that its working. Or just put it on landscape and see that its working in the same view with scroll.

I implement the same code that u provide in the example of the pull to refresh site: https://inappwebview.dev/docs/in-app-webview/basic-usage/

## VIDEO   

At the secons 0:12-0:15 im trying to pull to refresh, but the view doesnt do anything. Then I put the same view in landscape, use the pull to refresh and work perfectly because it has been become in a scrollable view.

https://user-images.githubusercontent.com/80764472/112598584-169d6700-8e0f-11eb-9fd0-298f6fbbbc35.mp4

**Comment by pichillilorenzo** [comment]
That's the expected behavior and not a bug.
Unfortunately, pull-to-refresh will be triggered if the body has no scrollbar but the inner content does, so you will have unexpected behavior in same webpages (read this issue https://github.com/pichillilorenzo/flutter_inappwebview/issues/719).
Also, to match the same behavior as iOS and Google Chrome itself, if the body has no vertical scrollbar, then you cannot pull-to-refresh.

**Comment by yamaha252** [comment]
> A workaround is to implement it by yourself using HTML, CSS and JavaScript. Then you can inject it using `evaluateJavascript`.

I tried to implement a hack as you recommended but it makes no effect :(

```
onLoadStop: (controller, url) async {
  webViewController?.evaluateJavascript(source: "document.body.style.overflow = 'scroll';");
}
```

**Comment by tkieronski** [comment]
Look this is a fudge but may help you - tested on Android, at the end after loading the page add javascript code to increase height by 1 px - something like this

document.documentElement.style.height = document.documentElement.clientHeight + 1 + 'px';
