### ISSUE TITLE
How to use "onEnterFullscreen"? 

### ISSUE THREAD

**Issue by Kevin-Justin** [pichillilorenzo/flutter_inappwebview#758]
I've Tried this _onEnterFullscreen: AutoOrientation.landscapeAutoMode(),_ when the page load, the phone automatic landscape, and i received this error.

![Capture](https://user-images.githubusercontent.com/75354764/112640968-e12f6280-8e7c-11eb-8ec9-303ded9b67f2.PNG)

what i want is, when the user click the fullscreen, the video automatic landscape

**Comment by pichillilorenzo** [comment]
`onEnterFullscreen` is a function of type `void Function(InAppWebViewController controller)`, so your code should be:
```dart
onEnterFullscreen: (controller) async {
  AutoOrientation.landscapeAutoMode();
},

// or

onEnterFullscreen: (controller) => AutoOrientation.landscapeAutoMode(),
```
