### ISSUE TITLE
I came across a very confusing problem,The code in the document was pasted into the editor and an error was reported

### ISSUE THREAD

**Issue by SuperLeven** [pichillilorenzo/flutter_inappwebview#761]
![image](https://user-images.githubusercontent.com/75765099/112756289-12439a80-9017-11eb-95a4-fd81f3c3f4e3.png)
Why is the word late wrong? What does it mean?
How to resolve this error?

**Comment by pichillilorenzo** [comment]
That code example is using dart null-safety.
So probably you need to upgrade Dart at least to `2.12.0-0`.
