### ISSUE TITLE
 cannot find symbol

### ISSUE THREAD

**Issue by DANGTHAIBINH22** [pichillilorenzo/flutter_inappwebview#764]
/Users/dangbinh/JOOVYMOBILE/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:18: error: cannot find symbol
    flutterEngine.getPlugins().add(new com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin());
                                                                               ^
  symbol:   class InAppWebViewFlutterPlugin                             
  location: package com.pichillilorenzo.flutter_inappwebview            
1 error                                                                 
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileReleaseJavaWithJavac'.           
> Compilation failed; see the compiler error output for details.

**Comment by pichillilorenzo** [comment]
Try to clean your project with `flutter clean`

**Comment by DANGTHAIBINH22** [comment]
> Try to clean your project with `flutter clean`

I tried it but it failed

**Comment by pichillilorenzo** [comment]
Then try these other solutions: https://stackoverflow.com/questions/55399209/update-flutter-dependencies-in-pub-cache

**Comment by DANGTHAIBINH22** [comment]
> Then try these other solutions: https://stackoverflow.com/questions/55399209/update-flutter-dependencies-in-pub-cache

My current project uses Flutter 1.22.6 and uses inAppWebView 4.0.0 + 4. I can't upgrade Flutter 2.0 because my project won't work

**Comment by pichillilorenzo** [comment]
I'm not saying you need to upgrade.
Try `flutter pub cache repair` or remove and reinstall the dependency

**Comment by DANGTHAIBINH22** [comment]
> I'm not saying you need to upgrade.
> Try `flutter pub cache repair` or remove and reinstall the dependency

i was try i't  but not working

**Comment by pichillilorenzo** [comment]
If you create a new fresh app and you just add `flutter_inappwebview: 4.0.0+4` as dependency, does it work?
If it was already working, it doesn't make any sense that now stopped working.

Other than repairing your flutter pub cache, you can try to delete manually all the pub cache (`/flutter/.pub-cache`), delete the `pubspec.lock` file and run again `flutter pub get`.
If this doesn't work either, there is no other things that I can say to you.
This isn't an issue with the plugin itself.
Maybe you can try to search online about `GeneratedPluginRegistrant.java error cannot find symbol
flutterEngine.getPlugins()` and try different solutions.

**Comment by DANGTHAIBINH22** [comment]
> If you create a new fresh app and you just add `flutter_inappwebview: 4.0.0+4` as dependency, does it work?
> If it was already working, it doesn't make any sense that now stopped working.
> 
> Other than repairing your flutter pub cache, you can try to delete manually all the pub cache (`/flutter/.pub-cache`), delete the `pubspec.lock` file and run again `flutter pub get`.
> If this doesn't work either, there is no other things that I can say to you.
> This isn't an issue with the plugin itself.
> Maybe you can try to search online about `GeneratedPluginRegistrant.java error cannot find symbol flutterEngine.getPlugins()` and try different solutions.

48 / 5000
Kết quả dịch
It's great for your support, thank you
