### ISSUE TITLE
Android - Pull to refresh triggered when scrolling container inside a website

### ISSUE THREAD

**Issue by Manuito83** [pichillilorenzo/flutter_inappwebview#765]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |1.27.0-4.0.pre|
| Plugin version       |5.3.0|
| Android version      |11|
| iOS version          |14.4|
| Xcode version        |               |

Device information: Emulator + OnePlus 6T

## Description

When trying to scroll a container (e.g. large textview with several lines) inside of a webpage, and if the main website scroll is at the top, the pull to refresh triggers.

**Expected behavior:** only the scrollable container/textview should scroll

**Current behavior:** inAppWebView's pull to refresh triggers.

## Steps to reproduce

1. Use the current example project for inAppWebView
2. Browse to a website with a scrollable container (e.g.: https://javiercbk.github.io/json_to_dart) or even try to edit anything here in GitHub large enough to scroll (README.md, or a comment, etc). 
3. Add as many lines as necessary in the container, so that it can be scrolled
4. **Try to scroll up the container. If the main website scroll is at the top, the pull to refresh will trigger.**
5. (If the main website scroll is not at the top, the container scrolls with no issues)

**Comment by pichillilorenzo** [comment]
Fixed with new release "5.3.0+1"
