### ISSUE TITLE
Downloads in webview not working

### ISSUE THREAD

**Issue by sgonzalez9450** [pichillilorenzo/flutter_inappwebview#767]
- [V] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [V] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [V] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [V] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        STAB       |
| Plugin version       |        5.3.0       |
| Android version      |         10      |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Samsung galaxy tab active pro SM-t545
Android 10

## Description

The webview its not working with the pdf/excel/stuff downloads.
I thought it was my problem but i tried the example of Lorenzo that i found here (https://gist.github.com/pichillilorenzo/ee74e103fdc324f761c5fde7b73bd430) and its not working, the app crash and it doesnt download anything.
The above console log text where showed in the logcat section:

Tried with differents things like the ones i saw in this post: (https://stackoverflow.com/questions/60371760/why-do-my-downloads-fail-sometimes-using-flutter-downloader). 
Apparently in the notification bar its seems to be complete, but if u try to click on hte notification or to search the archive, its not appearing anywhere.

Tried the funcionality in anohter app and the App crashes.

**Expected behavior:** 
Dowload document
**Current behavior:** 
Not downloading anything
## Steps to reproduce
Copy the example, give the permission in the android manifest, and run

## Stacktrace/Logcat   
I/flutter ( 8479): onDownloadStart http://ovh.net/files/1Mio.dat
W/tifications_ap( 8479): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/tifications_ap( 8479): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/tifications_ap( 8479): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/tifications_ap( 8479): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/Gralloc3( 8479): allocator 3.x is not supported
W/WM-WorkSpec( 8479): Backoff delay duration less than minimum value
D/ConnectivityManager( 8479): requestNetwork; CallingUid : 10439, CallingPid : 8479
D/DownloadWorker( 8479): DownloadWorker{url=http://ovh.net/files/1Mio.dat,filename=null,savedDir=/storage/emulated/0/Android/data/com.cedesa.lapsowork_notifications_app/files,header=,isResume=false
D/DownloadWorker( 8479): Update notification: {notificationId: 4, title: http://ovh.net/files/1Mio.dat, status: 2, progress: 0}
D/DownloadWorker( 8479): Open connection to http://ovh.net/files/1Mio.dat
I/System.out( 8479): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 8479): (HTTPLog)-Static: isSBSettingEnabled false
D/DownloadWorker( 8479): Content-Type = application/octet-stream
D/DownloadWorker( 8479): Content-Length = 1048576
D/DownloadWorker( 8479): Charset = null
D/DownloadWorker( 8479): Content-Disposition = null
D/DownloadWorker( 8479): fileName = 1Mio.dat
D/DownloadWorker( 8479): Update too frequently!!!!, this should be dropped
D/DownloadWorker( 8479): Update too frequently!!!!, this should be dropped
D/DownloadWorker( 8479): Update too frequently!!!!, this should be dropped
D/DownloadWorker( 8479): Update too frequently!!!!, this should be dropped
D/DownloadWorker( 8479): Update too frequently!!!!, this should be dropped
D/DownloadWorker( 8479): Update too frequently!!!!, this should be dropped
I/chatty  ( 8479): uid=10439(com.cedesa.lapsowork_notifications_app) pool-10-thread- identical 9 lines
D/DownloadWorker( 8479): Update too frequently!!!!, this should be dropped
I/flutter ( 8479): Fatal: could not find callback
W/tifications_ap( 8479): 0xebadde09 skipped times: 0
F/libc    ( 8479): FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x78c941c000)
F/libc    ( 8479): FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x795621398c)

**Comment by pichillilorenzo** [comment]
That's not related to this plugin. Downloading files it's up to you and how you implement it (using plugins, native code, or something else).
As you can see from the logs the `onDownloadStart` event is called correctly.
If the `flutter_downloader` plugin is not working correctly for you when you actually want to download a file, open an issue to the corresponding repo and not here.
My piece of code was just an example. You can change the download library to the one you want.

**Comment by daniel007enirman** [comment]
this example not working https://gist.github.com/pichillilorenzo/ee74e103fdc324f761c5fde7b73bd430
