### ISSUE TITLE
The camera does not turn on. Only file allows selection.

### ISSUE THREAD

**Issue by omerosmanoglu** [pichillilorenzo/flutter_inappwebview#774]
- [ok] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [ok] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [ok] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [ok] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        >=2.1.0 <3.0.0       |
| Plugin version       |      ^4.0.0+4         |
| Android version      |    10          |
| iOS version          |       x        |
| Xcode version        |        x       |

Device information: Xiomi Mi A2 Lite

When I click inpu type file, the file selection list appears.

I have read version updates and previous messages and changed it this way. "<input type =" file "accept =" image / * "capture>"

It is said that this feature was added in version 3.3.0. (https://github.com/pichillilorenzo/flutter_inappwebview/issues/353)

I don't know if it would be helpful, but the camera actually works. For example, I can open this address "https://webqr.com/"

accept = "image / *" my application crashes and I get the following message on the screen

## Stacktrace/Logcat 
W/System.err( 1393): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.flyWeb.flutter_inappwebview.fileprovider
W/System.err( 1393): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
W/System.err( 1393): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
W/System.err( 1393): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
W/System.err( 1393): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebViewChromeClient.getOutputUri(InAppWebViewChromeClient.java:1052)
W/System.err( 1393): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebViewChromeClient.getPhotoIntent(InAppWebViewChromeClient.java:938)
W/System.err( 1393): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebViewChromeClient.startPhotoPickerIntent(InAppWebViewChromeClient.java:895)
W/System.err( 1393): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebViewChromeClient.onShowFileChooser(InAppWebViewChromeClient.java:799)
W/System.err( 1393): 	at t9.runFileChooser(chromium-TrichromeWebViewGoogle.aab-stable-438910533:11)
W/System.err( 1393): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 1393): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 1393): 	at android.os.Looper.loop(Looper.java:174)
W/System.err( 1393): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
W/System.err( 1393): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1393): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 1393): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
F/chromium( 1393): [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
F/libc    ( 1393): Fatal signal 5 (SIGTRAP), code -6 (SI_TKILL) in tid 1393 (flyWeb), pid 1393 (flyWeb)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/daisy/daisy_sprout:10/QKQ1.191002.002/V11.0.18.0.QDLMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-04-02 00:47:08+0300
pid: 1393, tid: 1393, name: flyWeb  >>> com.flyWeb <<<
uid: 10252
signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
'
    x0  0000000000000000  x1  0000000000000081  x2  000000007fffffff  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7fff7f
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
    x12 00000000ffffff80  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 000000784bc13950  x17 000000784bb9e320  x18 000000784cd20000  x19 0000007fc9da9d68
    x20 0000007fc9da9d80  x21 0000007fc9da9d78  x22 0000007fc9da98b8  x23 000000784bc0d578
    x24 00000077713d1000  x25 000000784c723020  x26 000000000000004f  x27 0000000000000000
    x28 0000000000000000  x29 0000007fc9da9d00
    sp  0000007fc9da98a0  lr  000000776eafb354  pc  000000776eafb4ec
backtrace:
      #00 pc 0000000001c014ec  /data/app/com.google.android.webview-n8mqxrx5WxDo3lUtgDugKA==/base.apk!libmonochrome.so (offset 0x2d3000) (BuildId: fb031827f0ceb43d72d66e4965d246cef566da96)
Lost connection to device.

**android->app->src->main->AndroidManifest.xml** (I added "FILE_PROVIDER_PATHS" here but the problem was not solved.)

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.flyWeb">
    

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        android:exported="false"

        >
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-4730729327706435~5907314797"/>
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/provider_paths" />
    </application>
</manifest>`

main.dart

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await GlobalConfiguration().loadFromAsset("configuration");
  AppLanguage appLanguage = AppLanguage();
  await appLanguage.fetchLocale();


  await Permission.camera.request();
  await Permission.microphone.request();
  await Permission.storage.request();
  await Permission.mediaLibrary.request();



  return runApp(ChangeNotifierProvider<ThemeNotifier>(
    create: (_) => new ThemeNotifier(),
    child: MyApp(
      appLanguage: appLanguage,
    ),
  ));
}
```

**Comment by pichillilorenzo** [comment]
> I added "FILE_PROVIDER_PATHS" here but the problem was not solved.

From what you posted here, you didn't add it correctly. Please, check [Enable camera for HTML inputs - Configure Android](https://inappwebview.dev/docs/enable-camera-for-html-inputs/).
It should be:
```xml
<provider
    android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
    android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />
</provider>
```
and not just:
```xml
<meta-data
    android:name="android.support.FILE_PROVIDER_PATHS"
    android:resource="@xml/provider_paths" />
```

**Comment by JaosnHsieh** [comment]
One of the application widgets uses InAppWebView with a page that is using camera/micro.

```dart
return Scaffold(
    appBar: AppBar(
    title: const Text('XPTO'),),
    body: SafeArea(
      child: Column(children: <Widget>[
        Expanded(
          child: Stack(
            children: [
              InAppWebView(
                key: webViewKey,
                initialUrlRequest: URLRequest(url: Uri.parse(app.url.toString())),
                initialOptions: options,
                androidOnPermissionRequest: (InAppWebViewController controller, String origin, List<String> resources) async {
                  return PermissionRequestResponse(resources: resources, action: PermissionRequestResponseAction.GRANT);
                },
                onWebViewCreated: (controller) async  {
                  webViewController = controller;
                },
          )])
        )
      ]
  )
));

```

the options object for the InAppWebView is:

```
InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
  crossPlatform: InAppWebViewOptions(
    mediaPlaybackRequiresUserGesture: false,
    javaScriptEnabled: true
  ),
  ios: IOSInAppWebViewOptions(
    allowsInlineMediaPlayback: true,
    allowsAirPlayForMediaPlayback: true
  ));
On main.dart I've put the permission request

  WidgetsFlutterBinding.ensureInitialized();

  await Permission.camera.request();
  await Permission.microphone.request();
On Inflo.plist

<key>NSCameraUsageDescription</key>
<string>This thing use camera</string>
<key>NSMicrophoneUsageDescription</key>
<string>This thing use the microfone</string>
<key>UILaunchStoryboardName</key>

```
On pod:

```
        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

```
Everything is working fine.

The problem is that every time i open the InAppWebView, the message "Allow ... to use your camera and microphone?" appears.

as the image 

![image](https://user-images.githubusercontent.com/15373520/170409485-b363e9d0-6ac1-4b64-ab6c-e150285d6df4.png)


Do you happen to know how to prevent that permission dialog message to show up?
