### ISSUE TITLE
iOS webview showing blank page in specific URL

### ISSUE THREAD

**Issue by hwikang** [pichillilorenzo/flutter_inappwebview#776]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       1.22.4        |
| Plugin version       |      4.0.0+4           |
| Android version      |               |
| iOS version          |        14.4       |
| Xcode version        |        12.4       |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 
showing white(blank) page
## Steps to reproduce

InAppWebView showing a blank page when I set initialUrl to "https://dev-codesketch.luxrobo.com/".
Other url works fine in InAppWebView so I thought this url is a problem. 
But this url works fine in Web(chrome) and Android(native code)

**Comment by pichillilorenzo** [comment]
That should be fixed within the next release!

**Comment by pichillilorenzo** [comment]
However, for some reason, the `console.log` is being wrapped also by the web app itself and it's conflicting causing a JavaScript error (also, that is very strange!).

**Comment by pichillilorenzo** [comment]
Released new version `5.3.1`.

**Comment by bartukaan** [comment]
How to handle, previous Flutter version 2.0 ?

**Comment by pichillilorenzo** [comment]
Unfortunately version 4 is not supported anymore

**Comment by Enlacecode** [comment]
Is this issue resolved? I am also facing same issue with latest version of the plugin.

**Comment by atvbasha** [comment]
@snghnishant +1
