### ISSUE TITLE
May be an issue as Android Webview not working

### ISSUE THREAD

**Issue by ycv005** [pichillilorenzo/flutter_inappwebview#780]
Link- https://www.xda-developers.com/google-confirms-webview-issue-crashing-android-apps/ 

and latest webkit version given here is 1.2.0- https://developer.android.com/reference/androidx/webkit/package-summary

**Comment by pichillilorenzo** [comment]
That is about crashing not about app slow or laggy on android.
Also, if you check my build gradle file https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/android/build.gradle, you will see that I'm using the latest version of `androidx.webkit:webkit` that is `1.4.0` and not `1.2.0`.
However, if you are not using it, you should enable the Android Hybrid Composition option `useHybridComposition: true`.
It will improve performance on native views (in this case of the webview).
