### ISSUE TITLE
iOS can't play the video on background

### ISSUE THREAD

**Issue by omerbyrk** [pichillilorenzo/flutter_inappwebview#783]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.0.1        |
| Plugin version       |      [5.2.1+1](url)    |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
The video need to be play on background like safari.
**Current behavior:** 
Webview application opens the video as fullscreen. If I enable the mediaPlaybackRequiresUserGesture feature. It is not open the video on full screen but don't play it on background as well.

The problem does not exist on the Android side or Safari. It only exists on iOS side.

**Please look at the video which I attached. I have show the error on the video** 

https://user-images.githubusercontent.com/23620744/113502572-c8d2de00-9535-11eb-9223-e46104146a9e.mp4

**Comment by pichillilorenzo** [comment]
You need to set `allowsInlineMediaPlayback: true`, instead you are using it with `false`.
Also, check https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1614793-allowsinlinemediaplayback for details.
