### ISSUE TITLE
Is there any way to get response of XHR api req in app webview

### ISSUE THREAD

**Issue by nalinnishant** [pichillilorenzo/flutter_inappwebview#784]
I want to get response from an api get req in appwebview when the given url is being loaded.. is there any way to do this with this plugin...

NOTE - I can't call api directly i need to capture the response when the url is being loaded 

Here is a screenshot that may help you to understand my question - 
![image](https://user-images.githubusercontent.com/20789038/113522854-8951d380-95c1-11eb-967d-3dfc22a57dd6.png)
 
Any help will greatly appreciated

**Comment by pichillilorenzo** [comment]
Unfortunately, on Android there is no way to do it.
Someone could try injecting custom JavaScript code, but there is no native API that lets you inject JavaScript before the page is loaded.
One way I can thing of is to execute the XHR (Ajax) request and send the response “manually” to Dart side using “JavaScript Handlers”. This should be done when the `flutterInAppWebViewPlatformReady` JavaScript event has been fired by this plugin.
See https://inappwebview.dev/docs/in-app-webview/javascript-communication/ to understand how JavaScript Handlers work.

However, this is not a limitation of the plugin but of the Android WebView API itself.
