### ISSUE TITLE
[Mixed content] IOS

### ISSUE THREAD

**Issue by EArminjon** [pichillilorenzo/flutter_inappwebview#785]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    2.0.4           |
| Plugin version       |   5.3.1            |
| iOS version          |           14.4   |
| Xcode version        |       12.4      |

## Description

I would like to allow mixed content on IOS.
Package give a setting to allow that on android : 
```dart
mixedContentMode: AndroidMixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW
````

Here is how I use this package : 

```dart
InAppWebView(
  initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(javaScriptEnabled: true),
    android: AndroidInAppWebViewOptions(
      mixedContentMode: AndroidMixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW,
      useHybridComposition: hybrid,
    ),
    ios: IOSInAppWebViewOptions(
      allowsInlineMediaPlayback: true,
    ),
  ),
  initialUrlRequest: URLRequest(
    headers: "some header",
    url: Uri.parse(https_url),
  ),
),
```
Is that possible for IOS ?

**What you'd like to happen:** 

I would allow my webview to display an https webpage which will load some http scripts / files / images.

**Alternatives you've considered:**   
When enabling debug on InAppWebView on ios I didn't got more information about this problem. 
I tried some rules in info.plist like NSAllowsArbitraryLoadsInWebContent, NSAllowsArbitraryLoads, NSExceptionAllowsInsecureHTTPLoads... But always same behavior.

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoadsInWebContent</key>
    <true/>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsArbitraryLoadsForMedia</key>
    <true/>
</dict>
```

**Images**
IOS 
![image](https://user-images.githubusercontent.com/37028599/113626162-19475a00-9662-11eb-87bb-18428de886f5.png)

Android
![image](https://user-images.githubusercontent.com/37028599/113626246-32500b00-9662-11eb-86dd-06ec8af955da.png)

**Comment by xiaochonzi** [comment]
@EArminjon hello, same issue. did you fix it?

**Comment by EArminjon** [comment]
@xiaochonzi no...

**Comment by EArminjon** [comment]
@xiaochonzi no...
