### ISSUE TITLE
Can we use OAuth with webview

### ISSUE THREAD

**Issue by krissnawat** [pichillilorenzo/flutter_inappwebview#786]
Hi i seek solution about using OAuth with Webview in flutter but not found 

Can this package using with OAuth

**Comment by pichillilorenzo** [comment]
Yes, why not? Just implement your logic to capture the access token from the URL itself or cookies or localStorage or wherever it is.

**Comment by krissnawat** [comment]
@pichillilorenzo  any example here ? can your give some example

**Comment by pichillilorenzo** [comment]
If the access token is set in the redirect URL after the user login, just take the access token from it in the `onLoadStart` or `onLoadStop` event.
If the server sets the access token as a cookie, just use `CookieManager`.
It depends how it is implemented by the server.

**Comment by krissnawat** [comment]
@pichillilorenzo thank I will try

**Comment by nilotpalkapri** [comment]
I have gone through this problem but unable to solve by logic, then found that google disabled OAuth in webView. And able to make it working by removing wv from userAgent in crossPlatform options. So if you are yet to solve can try by replacing '; wv' with ''. And if you already solved by logic please share your logic, I need this.

**Comment by paramsinghvc** [comment]
I'm facing the security error doing the same "Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'."
