### ISSUE TITLE
[Android] Navigation on certain websites in InAppWebView crashes when trying to navigate to x-callback-url

### ISSUE THREAD

**Issue by raols** [pichillilorenzo/flutter_inappwebview#787]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.0.4          |
| Plugin version       |  5.3.1         |
| Android version      |  11            |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Android 11 (API 30) (emulator)
## Description

**Expected behavior:** 
Visit https://www.nike.com/se/en/ through the InAppWebView and navigate to a product and be able to continue navigating on the page.
**Current behavior:** 
Visit https://www.nike.com/se/en/ but after navigation to a product the InAppWebView tries to redirect to for example:  mynike://x-callback-url/product-details?style-color=CU4111-300&link_click_id=907905763154196244 and crashes. See image below.

## Options 
`InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        mediaPlaybackRequiresUserGesture: false,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      ));`

If I use `useShouldOverrideUrlLoading: true` it opens a new window above the running app which is not a behavior I want.

## Images   
![image](https://user-images.githubusercontent.com/26789764/113705092-500e8600-96dd-11eb-89d1-006e14633008.png)

(It works in my iOS environment.)

**Comment by pichillilorenzo** [comment]
That's the correct behavior. It's not a crash, but a load error.
The WebView does know nothing about the `mynike://` scheme. It's not the `http` or `https` scheme as you would normally have on the web.
In general, iOS somehow manages other schemes if it finds other apps that know how to manage them.

However, using `useShouldOverrideUrlLoading: true` without implementing the actual event `shouldOverrideUrlLoading` doesn't make any sense.
If you want to manage custom schemes to open an App that knows how to manage the `mynike` scheme, you need to implement the `shouldOverrideUrlLoading` event, for example, as follow:
```dart
shouldOverrideUrlLoading: (controller, navigationAction) async {
  var uri = navigationAction.request.url;

  if (uri != null && uri.scheme == "mynike") {
    if (await canLaunch(url)) {
      // Launch the App
      await launch(
        url,
      );
      // and cancel the request
      return NavigationActionPolicy.CANCEL;
    }
  }

  return NavigationActionPolicy.ALLOW;
},
```

**Comment by raols** [comment]
Thanks for the response. I did use a similar `shouldOverrideUrlLoading` that you mentioned, but the `launch` method open a new Chrome window above the app but I would like the user to maintain in the app. Is there any way to keep the user inside the InAppWebView?

**Comment by pichillilorenzo** [comment]
I tested that website and it seems that the webpage itself is trying to redirect the user to use the official App.
In this case, to make it work, you can return `NavigationActionPolicy.CANCEL` when the request has the scheme `mynike`.
This works for this website, but the same logic could not work for other websites.

Here is the `shouldOverrideUrlLoading` implementation:
```dart
shouldOverrideUrlLoading: (controller, navigationAction) async {
  var uri = navigationAction.request.url!;

  if (uri.scheme == "mynike") {
    // and cancel the request
    return NavigationActionPolicy.CANCEL;
  }

  return NavigationActionPolicy.ALLOW;
},
```

However, this is something related to the website itself and not to this plugin.

**Comment by raols** [comment]
I see, I'm not that experienced in web development, but thanks a lot for the fast response and the help! I works for that specific site now.
