### ISSUE TITLE
flutter_inappbrowser vs darkMode

### ISSUE THREAD

**Issue by laurent-humbert** [pichillilorenzo/flutter_inappwebview#79]
I'm implementing dark mode in my Android app and flutter_inappbrowser 1.1.1

The InAppWebView flashes a white background first, so things don't look too good.

Is there any way to specify the background colour before the view is displayed ?

Thanks

**Comment by peekpt** [comment]
I was going to report this too, the plugin needs its view to have an initial background color that defaults to context Scaffold background color just before the html renders.

**Comment by laurent-humbert** [comment]
FWIW, I worked around that problem by fading in the webview when onLoadStop is called. Does the trick for me as I load very simple web pages.

My code looks something like that:
....
animationController = AnimationController(duration: const Duration(milliseconds: 100), vsync: this);
animation = CurvedAnimation(parent: animationController, curve: Curves.easeIn)
....
 final web view =  Container(
        child: FadeTransition(
            opacity: animation,
            child: inAppWebView
        )
    );
....
      onLoadStop: (InAppWebViewController wvcontroller, String url) {
        Future.delayed(const Duration(milliseconds: 50), () {
          animationController.forward();
        });
      },

**Comment by peekpt** [comment]
@laurent-humbert  Thanks, It works for finals, but if you are streaming to the web view or set state it's a bit annoying

**Comment by rafaelmaeuer** [comment]
> FWIW, I worked around that problem by fading in the webview when onLoadStop is called. Does the trick for me as I load very simple web pages.
> 
> My code looks something like that: .... animationController = AnimationController(duration: const Duration(milliseconds: 100), vsync: this); animation = CurvedAnimation(parent: animationController, curve: Curves.easeIn) .... final web view = Container( child: FadeTransition( opacity: animation, child: inAppWebView ) ); .... onLoadStop: (InAppWebViewController wvcontroller, String url) { Future.delayed(const Duration(milliseconds: 50), () { animationController.forward(); }); },

Using @laurent-humbert's answer solved it for me, in combination with the following option:
```dart
crossPlatform: InAppWebViewOptions(transparentBackground: true)
```
