### ISSUE TITLE
What is the problem in  5. version ? and how to fix this

### ISSUE THREAD

**Issue by tonmooy** [pichillilorenzo/flutter_inappwebview#791]
Build failed in latest version but 4. version is ok
![inApp](https://user-images.githubusercontent.com/64668179/113973361-05684780-985e-11eb-8631-65ffd4307b70.png)

**Comment by pichillilorenzo** [comment]
Check this answer on StackOverflow: https://stackoverflow.com/a/65857921/4637638
Also, read the [Setup Android](https://inappwebview.dev/docs/get-started/setup-android/#ChromeSafariBrowser-on-Android-11) section.
