### ISSUE TITLE
[ChromeSafariBrowser] Failed to open ChromeCustomTabs even if packageName is provided in the options

### ISSUE THREAD

**Issue by skybur** [pichillilorenzo/flutter_inappwebview#792]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.0.4       |
| Plugin version       |        ^5.3.2       |
| Android version      |       10        |
| iOS version          |       -       |
| Xcode version        |      -         |

Device information: 

## Description

My device didn't have Chrome installed. When I try to open the ChromeSafariBrowser, this exception is thrown even though I provided packageName as a fallback if Chrome is not installed (I provided "org.mozilla.firefox" as packageName)
```dart
PlatformException(ChromeBrowserManager, ChromeCustomTabs is not available!, null, null)
```
This is the options I provide
```dart
final customTabOption = AndroidChromeCustomTabsOptions(
          addDefaultShareMenuItem: true,
          instantAppsEnabled: true,
          showTitle: true,
          enableUrlBarHiding: true,
          packageName: 'org.mozilla.firefox',
        );
```

I think availability checking should also consider packageName provided in the options.

**Expected behavior:** 
Should be able to open Custom Tab if Chrome is not installed but packageName is provided.

**Current behavior:** 
Exception thrown
```dart
PlatformException(ChromeBrowserManager, ChromeCustomTabs is not available!, null, null)
```

## Steps to reproduce

1. Disable/Uninstall Chrome
2. Provide packageName for other custom tab client (e.g. "org.mozilla.firefox") in options
3. Call open with the options above

**Comment by venky9885** [comment]
i am also facing same issue  please solve this

**Comment by ThomasXing** [comment]
> i am also facing same issue please solve this

I am too.

**Comment by TheRedSpy15** [comment]
Issue still persists in 2023
