### ISSUE TITLE
Attempt to read from field InAppBrowserManager.plugin on a null object reference

### ISSUE THREAD

**Issue by shinsenter** [pichillilorenzo/flutter_inappwebview#794]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  Flutter 2.1.0-12.2.pre • channel beta             |
| Plugin version       |  ^5.3.2             |
| Android version      |  Android/10             |
| iOS version          |  -             |
| Xcode version        |  -             |

Device information: 
HUAWEI MAR-LX2J; Android/10; kirin710/HWMAR/MAR-L22J

## Description

**Expected behavior:** 
No crashes

**Current behavior:** 
Ramdomly crashed

## Steps to reproduce

Application ramdomly crashed. I cannot find the way to reproduce crashes.

## Stacktrace/Logcat   
```
E/AndroidRuntime(17199): FATAL EXCEPTION: main
E/AndroidRuntime(17199): Process: com.example.app01, PID: 17199
E/AndroidRuntime(17199): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app01/com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserManager.plugin' on a null object reference
E/AndroidRuntime(17199):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
E/AndroidRuntime(17199):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
E/AndroidRuntime(17199):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
E/AndroidRuntime(17199):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(17199):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/AndroidRuntime(17199):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
E/AndroidRuntime(17199):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17199):        at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(17199):        at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(17199):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17199):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(17199):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(17199): Caused by: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserManager.plugin' on a null object reference
E/AndroidRuntime(17199):        at com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity.onCreate(Unknown Source:51)
E/AndroidRuntime(17199):        at android.app.Activity.performCreate(Activity.java:8086)
E/AndroidRuntime(17199):        at android.app.Activity.performCreate(Activity.java:8074)
E/AndroidRuntime(17199):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
E/AndroidRuntime(17199):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
E/AndroidRuntime(17199):        ... 11 more
```

**Comment by pichillilorenzo** [comment]
Please, could you post the code where you are using the `InAppBrowser` class?

**Comment by pichillilorenzo** [comment]
It seems to happen when `InAppBrowser` is launched. It says that the `manager` variable is `null` (there is no direct reference from your log, but I think that this happens here [#L77](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_browser/InAppBrowserActivity.java#L77)) but it should be impossible because an instance of `InAppBrowserManager` is always created when this plugin is attached to the `FlutterEngine`.
These could only happen when, for some strange reason, you or something else is disposing the `flutter_inappwebview` plugin from the `FlutterEngine`.
Maybe you are doing something wrong in your code. If you can provide how you are using that class, it could help me have a better understanding of it, otherwise, I cannot help you further than this.

**Comment by shinsenter** [comment]
@pichillilorenzo 
```
static InAppBrowser _browser;

/// Launch the URL using in-app browser
static Future<void>  openUrl(Uri uri) async {
  if (_browser != null) {
    if (_browser.isOpened()) {
      _browser.close();
    }
    _browser = null;
  }
  _browser = InAppBrowser();
  await _browser.openUrlRequest(urlRequest: URLRequest(url: uri));
}
```

Here is my code.
I want to close previous WebView when open new one.

**Comment by shinsenter** [comment]
@pichillilorenzo 
I added the source code. Please take a look

**Comment by MagicalWater** [comment]
same problem+1

**Comment by nguyenkin** [comment]
Same my problem
