### ISSUE TITLE
Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.pichillilorenzo/flutter_inappwebview', null)

### ISSUE THREAD

**Issue by ShehanMadushanka** [pichillilorenzo/flutter_inappwebview#795]
This occurs when I'm running the app on iOS, in Android app works fine.

Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.pichillilorenzo/flutter_inappwebview', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:219:41)
#4      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:624:71)
#5      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:574:5)
#6      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:584:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart<…>

**Comment by pichillilorenzo** [comment]
Please, specify what version of Flutter and what version of the plugin you are using. Also, post a code example that can replicates this issue on iOS. Thanks

**Comment by ShehanMadushanka** [comment]
Sample Code: 

InAppWebView(
                  initialUrl: 'www.google.com',
                  gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
                    new Factory<OneSequenceGestureRecognizer>(
                      () => new EagerGestureRecognizer(),
                    ),
                  ].toSet(),
                  initialOptions: InAppWebViewGroupOptions(
                      crossPlatform: InAppWebViewOptions(
                    verticalScrollBarEnabled: true,
                  )),
                  onWebViewCreated: (InAppWebViewController controller) {},
                  onLoadStart: (InAppWebViewController controller, String url) {
                  },
                  onLoadStop: (controller, url) {
                    setState(() {
                      isLoaded = true;
                    });
                  },
                )



Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
    ! Error: EyePorn 11 Pro is not connected. Xcode will continue when EyePorn 11 Pro is connected. (code -13)

• No issues found!

**Comment by pichillilorenzo** [comment]
It should work without any problem. Try to clean your project with `flutter clean`.
However, unfortunately, version 4 is not supported anymore. You should use the latest version.

**Comment by fangkyi03** [comment]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unregistered_view_type, A UIKitView widget is trying to create a PlatformView with an unregistered type: < com.pichillilorenzo/flutter_inappwebview >, If you are the author of the PlatformView, make sure `registerViewFactory` is invoked.
See: https://docs.flutter.dev/development/platform-integration/platform-views#on-the-platform-side-1 for more details.
If you are not the author of the PlatformView, make sure to call `GeneratedPluginRegistrant.register`., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:243:5)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:649:44)
<asynchronous suspension>

ios 16.4 xcode14.3

Running flutter directly is fine but ios embedding is a problem with the project flutter and embedding normal flutter widgets will work

**Comment by followthemoney1** [comment]
for me also this problem is relevant
