### ISSUE TITLE
net::ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by JackZhang1994** [pichillilorenzo/flutter_inappwebview#796]
无法打开http开头的url
在项目中设置 android:usesCleartextTraffic=true 也没有效果

**Comment by ycv005** [comment]
@pichillilorenzo , Ya, I have also set android:usesCleartextTraffic="true" but still get Web Page error saying that net::ERR_CLEARTEXT_NOT_PERMITTED.

**Comment by pichillilorenzo** [comment]
As already written on the [Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) page, see also:
- Check the official [Network security configuration - “Opt out of cleartext traffic”](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted) section.
- Also, check this StackOverflow issue answer: [Cleartext HTTP traffic not permitted](https://stackoverflow.com/a/50834600/4637638).
