### ISSUE TITLE
Slow loading with Basic athorization header.

### ISSUE THREAD

**Issue by madoka3530** [pichillilorenzo/flutter_inappwebview#798]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     Flutter 2.0.4 • Dart 2.12.2    |
| Plugin version       |       5.3.2        |
| Android version      |      8.1.0         |
| iOS version          |       none       |
| Xcode version        |          none     |

Device information: 

## Description
Hi I update InAppWebview.
But newest version loading is so slow with Basic auth.
Old version SDK is work well.

```
authorisedHeader = {
        'Authorization': 'Basic ' + base64Encode(utf8.encode('id:password'))
      };

~~~~~~~~~

InAppWebView(
        initialUrlRequest: URLRequest(
            url: Uri.parse("$baseURL"),
            headers: authorisedHeader))
~~~~~~~~~~
```
**Expected behavior:** 
I want to load in fast with basic authrise headers.

**Current behavior:** 
Newest version SDK loading is so slow with Basic auth.

**Comment by pichillilorenzo** [comment]
Requests made by the native WebView are the same as older versions.
The older `initialUrl` and newer `initialUrlRequest` didn’t change anything on the native side.
Are you sure this is not a server-side problem?
Could you make a comparison of both versions? Also, a screen recording about it? Thanks.
