### ISSUE TITLE
Adding WebViews to IndexedStack and Hybrid Composition not working

### ISSUE THREAD

**Issue by juuliaans** [pichillilorenzo/flutter_inappwebview#799]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.0.4 |
| Plugin version       | 5.3.2 |
| Android version      | 11 |
| iOS version          |  ------ |
| Xcode version        | ------ |

Device information: 

## Description

Hi everyone, I'm having this problem with Stacked Webviews (IndexedStack) and useHybridComposition: true (I need this option enabled since the keyboard has many problems if im not using hybrid composition). 

I have an IndexedStack that contains an array of views that contain an InAppWebView inside, when using hybridComposition and switching/adding new webviews (adding new views to the array) the webview stops working and shows blank screens.

This does not happen when using hybridComposition: false

**Expected behavior:** 

useHybridComposition: false
![zHHfd8SDcH](https://user-images.githubusercontent.com/2467657/114418639-16c89100-9b89-11eb-89cd-625ff5561a00.gif)

**Current behavior:** 

useHybridComposition: true

![gL0w6CSS75](https://user-images.githubusercontent.com/2467657/114418669-1fb96280-9b89-11eb-94b7-fd9bae1c877e.gif)

## Steps to reproduce

I've built a simple app to reproduce this behaviour.

```
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _index = 0;
  final bool useHybrid = true; //change to false and this works fine
  final GlobalKey webViewKey = GlobalKey();
  final GlobalKey webViewKey1 = GlobalKey();

  InAppWebViewController webViewController;

  List<InAppWebView> webviews = <InAppWebView>[];

  @override
  void initState() {
    super.initState();

    webviews = [InAppWebView(
      key: webViewKey,
      initialUrlRequest: URLRequest(url: Uri.parse("")),
      initialOptions: InAppWebViewGroupOptions(
        android: AndroidInAppWebViewOptions(
          useHybridComposition: useHybrid
        )
      ),
      onWebViewCreated: (InAppWebViewController webViewController) {
        webViewController.loadUrl(urlRequest: URLRequest(url: Uri.parse("https://inappwebview.dev/")));
      },
    )];
  }

  void _switchWebview() {
    if (_index == 0) {
      setState(() {
        if (webviews.length == 1) {
          List<InAppWebView> clone = <InAppWebView>[]..addAll(webviews);
          clone.add(InAppWebView(
            key: webViewKey1,
            initialUrlRequest: URLRequest(url: Uri.parse("https://google.com/")),
            initialOptions: InAppWebViewGroupOptions(
              android: AndroidInAppWebViewOptions(
                useHybridComposition: useHybrid
              )
            ),
          ));

          webviews = clone;
        }

        _index = 1;
      });
    } else {
      setState(() {
        _index = 0;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        child: SafeArea(bottom: false, right: true, child: IndexedStack(
          index: _index,
          children: webviews
        ))
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _switchWebview,
        tooltip: 'Switch',
        child: Icon(Icons.switch_left),
      ),
    );
  }
}
```

------

I don't see any errors on the console that could guide me in any directions.

----------

Thanks in advance! Any suggestions or help is welcomed.

**Comment by pichillilorenzo** [comment]
Probably, it's related to https://github.com/pichillilorenzo/flutter_inappwebview/issues/704.
If you try Flutter version `1.27.0-4.0.pre` or lower, does it work?

**Comment by juuliaans** [comment]
> Probably, it's related to #704.
> If you try Flutter version `1.27.0-4.0.pre` or lower, does it work?

Hi Lorenzo, thanks for the quick reply.
I tried switching back to `1.27.0-4.0.pre` but sadly this doesn't seem to fix the issue :(

**Comment by PawanFyers** [comment]
I am also facing the same issue :-(
