### ISSUE TITLE
prevent the webview from being reloaded

### ISSUE THREAD

**Issue by ederluca** [pichillilorenzo/flutter_inappwebview#802]
Good Morning

First I would like to thank you for this wonderful package that was created, I'm starting a new project and I came across the need to share a file using the device's native resources. I implemented a function that downloads the file and after that I use the ShareExtend package. to share the file and I noticed that every time I do this the webview returns to the home screen not staying on the screen that started sharing. My question is there any configuration that I can perform to prevent the webview from updating?

**Comment by pichillilorenzo** [comment]
Could you make a code example that replicates this behavior? Without any code, I cannot understand how you are using the plugin, so, I cannot help you. Thanks!
