### ISSUE TITLE
flutter_inappwebview stable version with hybrid composition

### ISSUE THREAD

**Issue by mohamoha6200** [pichillilorenzo/flutter_inappwebview#803]
## Environment
**Flutter version:** 2.0.2 stable

This plugin was a life saver for our team allowing us to control the Light/Dark mode of the webview according to our needs , the issue we are facing is installing and making use of the later versions of the plugin , since our project has been in development for some time , it doesnt support android embedding api V2 and thats probably why we can't install any of the versions supporting Hybrid Composition on android ie ^5.0.5 + and above , we are currently stuck to ^4.0.0+4 which builds fine on android but crashes on some android phones when we tap into any input field in the webview (not all devices) everything works okay on the Ios side of things. when we go ^5.0.5 and above the app doesnt even build android wise we get build errors such as : 

    C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\pull_to_refresh\PullToRefreshLayout.java:25: error: cannot access NestedScrollingParent3
public class PullToRefreshLayout extends SwipeRefreshLayout implements MethodChannel.MethodCallHandler {​​​​​​​
       ^
  class file for androidx.core.view.NestedScrollingParent3 not found
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\FlutterWebView.java:87: error: cannot find symbol
      pullToRefreshLayout.addView(webView);
                         ^
  symbol:   method addView(InAppWebView)
  location: variable pullToRefreshLayout of type PullToRefreshLayout
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\FlutterWebView.java:99: error: incompatible types: Object cannot be converted to View
    return pullToRefreshLayout != null ? pullToRefreshLayout : webView;
                                       ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:1252: error: cannot find symbol
        pullToRefreshLayout.setEnabled(false);
                           ^
  symbol:   method setEnabled(boolean)
  location: variable pullToRefreshLayout of type PullToRefreshLayout
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:1271: error: cannot find symbol
      pullToRefreshLayout.setEnabled(pullToRefreshLayout.options.enabled);
Execution failed for task ':flutter_inappwebview:compileDebugJavaWithJavac'

We tried switching the flutter channel to dev but the errors persisted.
We tried migrating to the embedding api V2 but other plugins crash in runtime stating : missing plugin implementation ....

the question is , just like you've mentioned here : https://github.com/pichillilorenzo/flutter_inappwebview/issues/643

Is the stable version supporting the hybrid composition coming out of (dev) anytime soon ? would you kindly advise on the issue we're facing ?

Many thanks.

**Comment by pichillilorenzo** [comment]
What do you mean? flutter_inappwebview 5 is already stable starting from `5.0.5+`!
The `class file for androidx.core.view.NestedScrollingParent3 not found` error is related to something wrong with your AndroidX configuration.
Take a look to this similar issue https://github.com/pichillilorenzo/flutter_inappwebview/issues/713, especially to the last comment of the issue author that fixed this error fixing wrong AndroidX configuration in the `build.gradle` file.

**Comment by mohamoha6200** [comment]
Thank you , we managed to fix it , we had the same subprojects stuff that we had comment , sorry for duplicate you can close the issue.
