### ISSUE TITLE
I cant call initialHeaders in last version ?

### ISSUE THREAD

**Issue by pichillilorenzo** [pichillilorenzo/flutter_inappwebview#805]
I cant call initialHeaders in last version ?

_Originally posted by @EslamAbotaleb in https://github.com/pichillilorenzo/flutter_inappwebview/issues/597#issuecomment-820807499_

**Comment by pichillilorenzo** [comment]
@EslamAbotaleb yes you can, just use the headers parameter of `URLRequest`

**Comment by EslamAbotaleb** [comment]
Hi Pichillilorenzo/Flutter_inappwebview,
First thanks for replay , i make that deal with URLRequest to add  header
specific controller.loadurl ,
second intialheaders found in previous version but in last version i
cant call intialheader so send to you this message .

**Comment by pichillilorenzo** [comment]
I mean the `URLRequest` instance of the `initialUrlRequest` property

**Comment by EslamAbotaleb** [comment]
I have another question how to send headers in controller.posturl ? Not
controller.loadurl

**Comment by pichillilorenzo** [comment]
On Android that’s not possible because native `postUrl` method doesn’t support headers.
If you need to load POST requests with headers, you can do it only on iOS and you must use the `loadUrl` method, set method “POST” and the corresponding Headers.
