### ISSUE TITLE
multiple calls to same evaluateJavascript(...) causes SyntaxError

### ISSUE THREAD

**Issue by belveder79** [pichillilorenzo/flutter_inappwebview#809]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.0.0          |
| Plugin version       | 4.0.0+4        |
| Android version      | --              |
| iOS version          |  14.4             |
| Xcode version        |  12.4             |

Device information: iPhone 12 Pro

## Description

I have a function to pass on some data to JS from dart. The function looks like the one found in the documentation:

```
_webViewController.evaluateJavascript(source: """
          const event = new CustomEvent("newFrameReady", {
            detail: {foo: 1, bar: false}
          });
          window.dispatchEvent(event);
        """);
```

Running this for the first time is ok, but the second time it causes a SyntaxError message like this:

`{message: SyntaxError: Can't create duplicate variable: 'event', messageLevel: 3}`

**Expected behavior:** 

Allow-multi-evalution...

**Current behavior:** 

Fires only one time, changing variable to event2 or so would work, but if you fire it a million times you can't just change variables like that.

## Steps to reproduce

Just run [code from docu](https://inappwebview.dev/docs/in-app-webview/javascript-communication/) like this:

```
onLoadStop: (controller, url) async {
  await controller.evaluateJavascript(source: """
    window.addEventListener("myCustomEvent", (event) => {
      console.log(JSON.stringify(event.detail));
    }, false);
  """);

  await Future.delayed(Duration(seconds: 5));

  controller.evaluateJavascript(source: """
    const event = new CustomEvent("myCustomEvent", {
      detail: {foo: 1, bar: false}
    });
    window.dispatchEvent(event);
  """);
  await Future.delayed(Duration(seconds: 1));
  controller.evaluateJavascript(source: """
    const event = new CustomEvent("myCustomEvent", {
      detail: {foo: 1, bar: false}
    });
    window.dispatchEvent(event);
  """);
},
onConsoleMessage: (controller, consoleMessage) {
  print(consoleMessage);
  // it will print: {message: {"foo":1,"bar":false}, messageLevel: 1}
},
```

## Stacktrace/Logcat 

2021-04-17 15:24:26.191042+0200 Runner[25416:3053484] flutter: {message: {"foo":1,"bar":false}, messageLevel: 1}
2021-04-17 15:24:27.206509+0200 Runner[25416:3053484] flutter: {message: SyntaxError: Can't create duplicate variable: 'event', messageLevel: 3}
2021-04-17 15:24:28.205597+0200 Runner[25416:3053484] flutter: {message: SyntaxError: Can't create duplicate variable: 'event', messageLevel: 3}
`

**Comment by belveder79** [comment]
Actually I realized that

```
onLoadStop: (controller, url) async {
  await controller.evaluateJavascript(source: """
    window.addEventListener("myCustomEvent", (event) => {
      console.log(JSON.stringify(event.detail));
    }, false);
  """);

  await Future.delayed(Duration(seconds: 5));

  controller.evaluateJavascript(source: """
    window.dispatchEvent(new CustomEvent("myCustomEvent", {
      detail: {foo: 1, bar: false}
    }));
  """);
  await Future.delayed(Duration(seconds: 1));
  controller.evaluateJavascript(source: """
    window.dispatchEvent(new CustomEvent("myCustomEvent", {
      detail: {foo: 1, bar: false}
    }));
  """);
},
onConsoleMessage: (controller, consoleMessage) {
  print(consoleMessage);
  // it will print: {message: {"foo":1,"bar":false}, messageLevel: 1}
},
```

works fine.

**Comment by pichillilorenzo** [comment]
In JavaScript you cannot create or redefine 2 variables with `const`. Do you know how JavaScript works?

**Comment by belveder79** [comment]
> Do you know how JavaScript works?

kind of, but I was actually thinking about the evaluateJavascript() in a fire-and-forget way rather than something that hangs around in the back forever...

**Comment by pichillilorenzo** [comment]
Well, JavaScript is getting evaluated inside the WebView, so how the webpage could forget it? Doesn’t make much sense to me. However, you know it now. Learn JavaScript if you need to use it.

**Comment by belveder79** [comment]
you are totally right. I was writing quite some JS code in Node Red and demo webpages, but I was never "injecting" JS code that way from the outside. So what I did not think of is that anything defined `const` in the injection code makes it stick to the webpage while the rest is, as I supposed, fire and forget... Good to know... thx...

**Comment by pichillilorenzo** [comment]
You can think of an evaluation as you would append a `<script>` HTML tag with text code inside it to the document.
Changes applied to the document will remain, as the variable you define.
If you need a different scope, you can always write the code as you would do in JavaScript, for example wrapping your code inside an anonymous JavaScript function that call itself: `(function(){ MY CODE HERE })();`

**Comment by belveder79** [comment]
Right... btw. I have to say that you did an amazing job - I start to get my head around all the nifty details :-)

just a last question. I got it to work with simple data types, but can you probably point me to the most elegant way to transfer some Uint8List/TypedArray of binary data from dart to the WebView to fill a canvas?
