### ISSUE TITLE
Black screen before inappwebview loads

### ISSUE THREAD

**Issue by Trend74X** [pichillilorenzo/flutter_inappwebview#811]
I wasn't aware until someone pointed it out. I simply loaded a webview after a splash screen, the dark screen appears for a brief second before the webview kicks in.

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.0.4 |
| Plugin version       | 5.3.2 |

Device information: 

## Description

**Expected behavior:** 
Load white screen before webview loads

**Current behavior:** 
Loads black screen for a brief moment

**Comment by pichillilorenzo** [comment]
This is the expected behavior. If you need, you can simply set a Flutter widget loader before the very first load, and then show the WebView widget, or set the `transparentBackground: true` WebView option.

**Comment by VirtualAstronaut** [comment]
transparentBackground is property of InAppWebViewOptions not InAppWebView

```
  initialOptions: InAppWebViewGroupOptions(
                              crossPlatform: InAppWebViewOptions(
                                  transparentBackground: true))
```

**Comment by ttzein6** [comment]
settings : InAppWebViewSettings(
      transparentBackground: true,),
