### ISSUE TITLE
PlatformException when run release build only

### ISSUE THREAD

**Issue by CarloDotLog** [pichillilorenzo/flutter_inappwebview#813]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    2.0.5           |
| Plugin version       |    ^5.3.2           |
| Android version      |    Android 11 (API 30)           |
| iOS version          |               |
| Xcode version        |               |

Device information: 
Tested with different physical devices. 

## Description
I have a PlatformException when run the app with --release mode. In debug or profile mode there are no problems. 
 
**Expected behavior:** 
Run as in debug and profile mode. 

**Current behavior:** 
Black screen with exception in console. 

## Steps to reproduce

1. Create a "InAppWebView" widget that points to any url.  
2. flutter run --release
3. PlatformException

## Images   
![device-2021-04-19-182711](https://user-images.githubusercontent.com/13763473/115270801-fbd3bf00-a13c-11eb-8931-a572a728d488.png)

## Stacktrace/Logcat   
E/flutter (31616): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: com.pichillilorenzo/flutter_inappwebview
E/flutter (31616):      at io.flutter.plugin.platform.j$a.d(Unknown Source:229)
E/flutter (31616):      at io.flutter.embedding.engine.i.j$a.b(Unknown Source:152)
E/flutter (31616):      at io.flutter.embedding.engine.i.j$a.onMethodCall(Unknown Source:144)
E/flutter (31616):      at f.a.d.a.j$a.a(Unknown Source:17)
E/flutter (31616):      at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/flutter (31616):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (31616):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31616):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (31616):      at android.os.Looper.loop(Looper.java:206)
E/flutter (31616):      at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (31616):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31616):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (31616):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/flutter (31616): , null, null)
E/flutter (31616): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
E/flutter (31616): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (31616): <asynchronous suspension>
E/flutter (31616): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1036)
E/flutter (31616): <asynchronous suspension>
E/flutter (31616): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:742)
E/flutter (31616): <asynchronous suspension>
E/flutter (31616): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:195)
E/flutter (31616): <asynchronous suspension>
E/flutter (31616):

**Comment by CarloDotlog** [comment]
Ciao Lorenzo, 
I found a conflict with the flutter_barcode_scanner package.
With the new version flutter_barcode_scanner:2.0.0 the PlatformException is not triggered.
