### ISSUE TITLE
addDefaultShareMenuItem on making false still show share icon in android.

### ISSUE THREAD

**Issue by prashant-sreyah** [pichillilorenzo/flutter_inappwebview#816]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |               |
| Plugin version       |               |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
share should hide

**Current behavior:** 
still show there
## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by jaiswalshubham84** [comment]
@prashant-sreyah

Did u able to resolve the issue. If yes can u please share ur solution.
Thanks in advance
