### ISSUE TITLE
I have issue when the widget's height more than device screen height

### ISSUE THREAD

**Issue by FatmaMM** [pichillilorenzo/flutter_inappwebview#817]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        1.22.4       |
| Plugin version       |     4.0.0+4          |
| Android version      |       30.0.1        |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
if the inappwbview widget height is more than screen height it works well
**Current behavior:** 
when the widget's height more than device screen height

**Comment by pichillilorenzo** [comment]
Without Android Hybrid Composition, this is not possible. This is a limitation of the Flutter Platform View implementation and not of this plugin. Check https://github.com/pichillilorenzo/flutter_inappwebview/issues/314.

Also, version 4 is not supported anymore.
