### ISSUE TITLE
Hi, is this plugin supported webp image in H5 on IOS ?

### ISSUE THREAD

**Issue by bladeofgod** [pichillilorenzo/flutter_inappwebview#818]
i used webp image in my app , and image can not display in h5 page on ios 13 (safari). 

thanks for help :)

**Comment by pichillilorenzo** [comment]
As you can see from here https://stackoverflow.com/questions/58487035/how-to-add-webp-support-in-safari-browser, webp format is supported on iOS 14+

**Comment by bladeofgod** [comment]
> As you can see from here https://stackoverflow.com/questions/58487035/how-to-add-webp-support-in-safari-browser, webp format is supported on iOS 14+

thanks a lot
