### ISSUE TITLE
iOS cookie session not save when closing the app (http website)

### ISSUE THREAD

**Issue by nongtiny** [pichillilorenzo/flutter_inappwebview#824]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   2.0.3          |
| Plugin version       |    5.3.0           |
| Android version      |               |
| iOS version          |     14.4          |
| Xcode version        |       2373        |

Device information: Iphone 11

## Description

Test URL: http://188.34.156.6:37892/login/

**Expected behavior:** 

When the user log in successfully, the website will set the login session cookie, and when the user closes the app. The user doesn't need to log in again. The session should still be there.

**Current behavior:** 

When the user does login successfully, the website will set the login session cookie, and when the user closes the app. The user needs to log in again. The session is gone.

## Steps to reproduce

1. Open the app with InAppWebView widget with `initialUrl` =  http://188.34.156.6:37892/login/
2. Log in ( Sorry.  I can't give you the credential )
3. Terminate the app and open it again

**Comment by nongtiny** [comment]
I already searched and found it, but I still can't solve it.

Is it because the website is `http`? I tried on `https` website. It works.

Can we do something to handle the website that has only `http`?

Thanks in advance.

**Comment by nongtiny** [comment]
I found the issue now. If the website cookie is not set the expiration date the cookie will be lost when terminating the app.

This happens only in iOS. Now, I'm just a newbie in mobile application development. I don't know the real problem, but this works for me. If you have an answer to this. I would like to hear it. 

Anyway, thanks for developing this brilliant package.

**Comment by unnamedw** [comment]
> I already searched and found it, but I still can't solve it.
> 
> Is it because the website is `http`? I tried on `https` website. It works.
> 
> Can we do something to handle the website that has only `http`?
> 
> Thanks in advance.

I think it is not the issue, because I loaded https url and all the stuffs were going on the same way.
But, in android, there is any problem with it... it's a quite tricky.

**Comment by NickB23** [comment]
@nongtiny Thank you so much for this mention. I was searching for hours until I stumbled upon your comment. Saved my day!
