### ISSUE TITLE
Popup inappwebview not showing up.

### ISSUE THREAD

**Issue by anas790** [pichillilorenzo/flutter_inappwebview#834]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |    2.06   |
| Plugin version       |    5.3.2    |
| Android version      |     29sdk      |

Device information: Tested on google pixel and xiaomi poco F1

## Description
I am trying to create a popup window when someone clicks on an external link, I implemented onCreateWindow method to handle the popup creation but the popup seems to be becoming kind of invisible not sure how to explain that but for reference I have uploaded an image which shows the error.
video link : - [https://drive.google.com/file/d/1GBCzZpddc-x7xmUVHQcDoGQim5ebfTbd/view?usp=sharing](https://drive.google.com/file/d/1GBCzZpddc-x7xmUVHQcDoGQim5ebfTbd/view?usp=sharing)

I am not sure why this is happening but  i need to have a fix for this as soon as possible please.

## Steps to reproduce

Here is my inappwebview code to reproduce the given behavior of the app.

import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:collection';
import 'package:fluttertoast/fluttertoast.dart';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:path_provider/path_provider.dart';
import 'package:gallery_saver/gallery_saver.dart';

class WebView extends StatefulWidget {
  @override
  _WebViewState createState() => new _WebViewState();
}
class _WebViewState extends State<WebView> {
  InAppWebViewController? _webViewController;
  InAppWebViewController? _webViewPopupController;
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      useShouldOverrideUrlLoading: true,
      javaScriptCanOpenWindowsAutomatically: true,
      mediaPlaybackRequiresUserGesture: false,
      useOnDownloadStart: true,
    ),
    android: AndroidInAppWebViewOptions(
      supportMultipleWindows: true,
      
      useHybridComposition: true,
    ),
    
    ios: IOSInAppWebViewOptions(
      allowsInlineMediaPlayback: true,
    )
  );
  

  late PullToRefreshController pullToRefreshController;
  late ContextMenu contextMenu;
  String url = "";
  double progress = 0;
  bool isLoading=true;
  final urlController = TextEditingController();

  @override
  void initState() {
    super.initState();
    pullToRefreshController = PullToRefreshController(
      options: PullToRefreshOptions(
        color: Colors.blue,
      ),
      onRefresh: () async {
        if (Platform.isAndroid) {
          _webViewController?.reload();
        } else if (Platform.isIOS) {
          _webViewController?.loadUrl(
              urlRequest: URLRequest(url: await _webViewController?.getUrl()));
        }
      },
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _buildWebView();
  }
  Future<bool> _confirmDialog() async {
    return await showDialog(
      context: context,
      builder: (context) => new AlertDialog(
        title: new Text('Are you sure?'),
        content: new Text('Do you want to exit an App'),
        actions: <Widget>[
          TextButton(
            onPressed: () {
              Navigator.of(context).pop(true);
            },
            style: TextButton.styleFrom(
              primary: Colors.red,
            ),
            child: Text("Yes"),
          ),
          TextButton(
            onPressed: () {
              Navigator.of(context).pop(false);
            },
            child: Text("No"),
          ),
        ],
      ),
    )??false;
  }

  Widget _buildWebView(){
    return MaterialApp(
      home: new WillPopScope(
        onWillPop: () async {
          if(_webViewController !=null){
            if (await _webViewController!.canGoBack()){
              _webViewController?.goBack();
              return false;
            }
            else{
              return _confirmDialog();
            }
          }
          return true;
        },
        child: Scaffold(
          body: Stack(
            children: [
              InAppWebView(
                initialUrlRequest: URLRequest(url: Uri.parse("https://fabric.tri3d.in")),
                initialUserScripts: UnmodifiableListView<UserScript>([]),
                initialOptions: options,
                pullToRefreshController: pullToRefreshController,
                onWebViewCreated: (InAppWebViewController controller){ _webViewController = controller;},
                onLoadStart: (controller, url) {
                  setState(() {
                    this.url = url.toString();
                    urlController.text = this.url;
                  });
                },
                androidOnPermissionRequest: (controller, origin, resources) async {
                  return PermissionRequestResponse(
                      resources: resources,
                      action: PermissionRequestResponseAction.GRANT);
                },
                onCreateWindow: (controller, createWindowRequest) async {
                  print("onCreateWindow");
                  print(createWindowRequest);
                  print(controller);
                  showDialog(
                    context: context,
                    builder: (context) {
                      return AlertDialog(
                        insetPadding: const EdgeInsets.all(0.0),
                        content: Container(
                          padding: const EdgeInsets.all(0.0),
                          width: MediaQuery. of(context). size. width,
                          height: MediaQuery. of(context). size. height/1.5,
                          child: Scaffold(
                          body: Stack(
                            children: [
                              InAppWebView(
                                windowId: createWindowRequest.windowId,
                                initialOptions: InAppWebViewGroupOptions(
                                  crossPlatform: InAppWebViewOptions()
                                ),
                                onCloseWindow: (controller) {
                                },
                                onUpdateVisitedHistory: (controller,url,status){
                                  print(url);
                                  print(status);
                                },
                                onWebViewCreated: (InAppWebViewController controller) {
                                  _webViewPopupController = controller;
                                },
                                onLoadStart: ( controller, url) async{
                                  print("onLoadStart popup $url");
                                },
                                onLoadStop: (controller, url) async {
                                  print("onLoadStop popup $url");
                                },
                              ),
                            ]
                          ),
                        ),
                      ));
                    },
                  );
                  return true;
                },
                shouldOverrideUrlLoading: (controller, navigationAction) async{
                  var uri = navigationAction.request.url!;
                  if(["https"].contains(uri.scheme)){
                    if(await canLaunch(uri.toString())){
                      await launch(uri.toString());
                    }
                  }
                  return NavigationActionPolicy.CANCEL;
                },
                onDownloadStart: (controller, url) async {
                  Fluttertoast.showToast(
                    msg: "Image Downloading Started...",
                    toastLength: Toast.LENGTH_LONG,
                    gravity: ToastGravity.BOTTOM,
                    timeInSecForIosWeb: 1,
                    backgroundColor: Colors.grey,
                    textColor: Colors.white,
                    fontSize: 16.0
                  );
                  String imageBas64Data = url.toString();
                  var imageType='';
                  if(imageBas64Data.contains('jpeg')==true){
                    imageType="jpeg";
                  }
                  else{
                    imageType='png';
                  }
                  var bStr = imageBas64Data.split(',').last;
                  Uint8List bytes = base64.decode(bStr);
                  String dir = (await getExternalStorageDirectory())!.path;
                  await new Directory('$dir/TRI3D/').create();
                  String imgName = 'Tri3dImage_'+(DateTime.now().millisecondsSinceEpoch).toString();
                  final fullPath = '$dir/TRI3D/'+imgName+'.'+imageType;
                  print("onDownloadStart" +bStr);
                  File file = File(fullPath);
                  await file.writeAsBytes(bytes);
                  print(file.path);
                  var sus;
                  String direct = "/storage/emulated/0";
                  bool exists = await Directory(direct+'/TRI3D/').exists();
                  if(!exists){
                    await new Directory('$direct/TRI3D/').create(); 
                  }
                  await GallerySaver.saveImage(file.path,albumName: 'TRI3D').then((success) {sus = success;});
                  if(sus==true){
                    Fluttertoast.showToast(
                    msg: "Image Saved in Gallery in Tri3D Folder",
                    toastLength: Toast.LENGTH_SHORT,
                    gravity: ToastGravity.BOTTOM,
                    timeInSecForIosWeb: 1,
                    backgroundColor: Colors.green,
                    textColor: Colors.white,
                    fontSize: 16.0
                  );
                  }
                  else{
                    Fluttertoast.showToast(
                      msg: "Image Save Failed!",
                      toastLength: Toast.LENGTH_SHORT,
                      gravity: ToastGravity.BOTTOM,
                      timeInSecForIosWeb: 1,
                      backgroundColor: Colors.red,
                      textColor: Colors.white,
                      fontSize: 16.0
                    );
                  }
                },
                onLoadStop: (controller, url) async {
                  print("UOOOOOO");
                  pullToRefreshController.endRefreshing();
                  setState(() {
                    this.url = url.toString();
                    urlController.text = this.url;
                    isLoading = false;
                  });
                },
                onLoadError: (controller, url, code, message) {
                  pullToRefreshController.endRefreshing();
                },
                onProgressChanged: (controller, progress) {
                  if (progress == 100) {
                    pullToRefreshController.endRefreshing();
                  }
                  setState(() {
                    this.progress = progress / 100;
                    urlController.text = this.url;
                  });
                },
                onUpdateVisitedHistory: (controller, url, androidIsReload) {
                  setState(() {
                    this.url = url.toString();
                    urlController.text = this.url;
                  });
                },
                onConsoleMessage: (controller, consoleMessage) {
                  print("console:"+ consoleMessage.toString());
                },
              ),
              isLoading
                ? Center( child: CircularProgressIndicator(),)
                : Stack(),
            ],
          ), resizeToAvoidBottomInset: false,
        ),
      ),
    );
  }
}

**Comment by tri3d** [comment]
I Have tried searching for the same issue as mentioned in the above steps but found no such thing.
