### ISSUE TITLE
sdk location not found. define location with an ANDROID_SDK_ROOT environment variable 

### ISSUE THREAD

**Issue by avinashk369** [pichillilorenzo/flutter_inappwebview#835]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.0.6          |
| Plugin version       |       5.3.2        |
| Android version      |      4.1         |
| iOS version          |               |
| Xcode version        |     12.4          |

## Description

**Expected behavior:** 

**Current behavior:** FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/avinashdhiraj/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/android/local.properties'.

## Stacktrace/Logcat   

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/avinashdhiraj/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin flutter_inappwebview could not be built due to the issue above.

**Comment by ch-muhammad-adil** [comment]
Getting same error 
```


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/adil/Development/Mob/cross-platform/ClientsWork/timerabbit/build/flutter_inappwebview/intermediates/library_manifest/debug/AndroidManifest.xml:7:5-11:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_inappwebview...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/adil/fvm/stable/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


Exception: The plugin flutter_inappwebview could not be built due to the issue above.
```

**Comment by apetroaeiandrei** [comment]
Open the android folder as a separate project in Android studio -> upgrade your gradle version. Worked for me
