### ISSUE TITLE
Not performing tawk.to call action in webview on click

### ISSUE THREAD

**Issue by Arxlan40** [pichillilorenzo/flutter_inappwebview#837]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.0       |
| Plugin version       |          5.3.2     |
| Android version      |      11         |

Device information: 

Test on several devices gives the same result

## Description

I have webview in which my website has tawk.to chat and call service. When I click on the call or video call button it perform no action. Even I have put the camera and microphone and other required permissions. 

**Expected behavior:** 
To create voice or video call on click

**Current behavior:** 
No action is performed on click.

##error
Failed to get fallback IMM with expected displayId=8 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView{7cca0dd VFEDHVCL. .F...... 0,0-1080,2130}

[AUX]GuiExtAuxCheckAuxPath:630: Null anb

## webview Link
https://farnek.org/

##code

        Expanded(
              child: Container(
                child: InAppWebView(
                    initialUrlRequest: URLRequest(
                        url: Uri.parse("https://farnek.org/")
                    ),
                    initialOptions: InAppWebViewGroupOptions(
                      crossPlatform: InAppWebViewOptions(
                        javaScriptEnabled: true,
                        useShouldOverrideUrlLoading: true,

                        mediaPlaybackRequiresUserGesture: false,
                      ),
                      android: AndroidInAppWebViewOptions(
                        useHybridComposition: true,
                      ),
                    ),
                    onWebViewCreated: (InAppWebViewController controller) {
                      webView = controller;
                    },

                    androidOnPermissionRequest: (controller, origin, resources) async {
                      return PermissionRequestResponse(
                          resources: resources,
                          action: PermissionRequestResponseAction.GRANT);
                    },
                    onProgressChanged:
                        (InAppWebViewController controller, int progress) {
                      setState(() {
                        this.progress = progress / 100;
                      });
                    },

              ),
            ))

**Comment by dharmeshapptrait** [comment]
Were you able to fix the issue? We are having the same issue.

**Comment by Arxlan40** [comment]
> Were you able to fix the issue? We are having the same issue.

Yes, I solved the issue by using multi-windows.

**Comment by dharmeshapptrait** [comment]
> > Were you able to fix the issue? We are having the same issue.
> 
> Yes, I solved the issue by using multi-windows.

ok, please can you share me how to use multi-windows.

**Comment by Arxlan40** [comment]
https://inappwebview.dev/

Study the official documentation you will get the understanding.

or check this 
https://stackoverflow.com/questions/57067046/how-do-i-open-multiple-webviews-on-flutter

**Comment by dharmeshapptrait** [comment]
> https://inappwebview.dev/
> 
> Study the official documentation you will get the understanding.
> 
> or check this
> https://stackoverflow.com/questions/57067046/how-do-i-open-multiple-webviews-on-flutter

OK, thanks
