### ISSUE TITLE
Android bugs

### ISSUE THREAD

**Issue by pratima369** [pichillilorenzo/flutter_inappwebview#840]
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_plugin_android_lifecycle...
Running Gradle task 'assembleAarRelease'...

**Comment by pratima369** [comment]
yes i have search lots of time but I didn't get my problem solution

**Comment by naccio8** [comment]
me to
