### ISSUE TITLE
Fatal Crash "No views in hierarchy found matching"

### ISSUE THREAD

**Issue by nietsmmar** [pichillilorenzo/flutter_inappwebview#841]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   2.2.0-10.3.pre • channel beta             |
| Plugin version       |  5.3.2             |
| Android version      |  8.0.0              |
| iOS version          |   --            |
| Xcode version        | --              |

Device information: Samsung Galaxy S9  |  Google Pixel 5 

## Description

I couldn't reproduce the crash on my own. I just got the Crashreports from the app in the playstore.

## Images   
![image](https://user-images.githubusercontent.com/9265181/117946384-8d36eb00-b30f-11eb-85ae-69f94584beb8.png)

## Stacktrace/Logcat   
```
Fatal Exception: androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (view.getClass().getName() matches: is "com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "com.pichillilorenzo.flutter_inappwebview.pull_to_refresh.PullToRefreshLayout" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "io.flutter.embedding.engine.mutatorsstack.a" and view.getId() is <-1 (resource name not found)> and is a child at 3th index of the matching parent: (view.getClass().getName() matches: is "io.flutter.embedding.android.k" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "io.flutter.embedding.android.FlutterSplashView" and view.getId() is <1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "android.widget.FrameLayout" and view.getId() is <16908290/android:id/content> and is a child at 1th index of the matching parent: (view.getClass().getName() matches: is "android.widget.LinearLayout" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "com.android.internal.policy.DecorView" and view.getId() is <-1 (resource name not found)> and view.getRootView() to equal view))))))))

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=2220, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) sim=#10 ty=1 fl=#81810100 pfl=0x1020000 fmt=-3 wanim=0x1030001 vsysui=0x510 needsMenuKey=2 colorMode=0 naviIconColor=0}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, <truncated: 6197 chars>
       at androidx.test.espresso.NoMatchingViewException$Builder.build(NoMatchingViewException.java:5)
       at androidx.test.espresso.base.ViewFinderImpl.getView(ViewFinderImpl.java:21)
       at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:4)
       at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by Gabanelli** [comment]
Same issue here, but I realized that this error doesn't happen when my users install the app with APK, just when I publish in internal test track in Google Play with ABB.

**Comment by bigslider** [comment]
same there,  found in android 10. 

> No views in hierarchy found matching: (view.getClass().getName() matches: is "com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "com.pichillilorenzo.flutter_inappwebview.pull_to_refresh.PullToRefreshLayout" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "io.flutter.embedding.engine.mutatorsstack.FlutterMutatorView" and view.getId() is <-1 (resource name not found)> and is a child at 2th index of the matching parent: (view.getClass().getName() matches: is "io.flutter.embedding.android.FlutterView" and view.getId() is <1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "io.flutter.embedding.android.FlutterSplashView" and view.getId() is <2 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "android.widget.FrameLayout" and view.getId() is <609893468 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "android.widget.FrameLayout" and view.getId() is <16908290/android:id/content> and is a child at 1th index of the matching parent: (view.getClass().getName() matches: is "android.widget.LinearLayout" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "com.android.internal.policy.DecorView" and view.getId() is <-1 (resource name not found)> and view.getRootView() to equal view)))))))))
