### ISSUE TITLE
OnDownloadStart event not starting

### ISSUE THREAD

**Issue by ederluca** [pichillilorenzo/flutter_inappwebview#842]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |2.0.6|
| Plugin version       |5.3.2|
| Android version      |10|
| iOS version          |14.0.1|
| Xcode version        |Version 12.5 (12E262)|

Device information: 

## Description
I am facing a problem where I am using useOnDownloadStart: true:

On Android, the onDownloadStart event is working perfectly;
In IOS, instead of starting the event and downloading the image, it is opening the image. I have already made several settings on my backend, but until now, nothing in the image has started to download.

Would you have any tips for the case of IOS?

**Expected behavior:** 
My expectation is that the download will start automatically just like what happens on Android.

**Current behavior:** 
The download of the file is not starting as it occurs on android.

**Comment by hiashutoshsingh** [comment]
does download works on iOS from webview? when I integrated this in iOS it throws an exception that 'It is supported in Android only'

**Comment by jhomlala** [comment]
I have same error for iOS 12.4 (I know it's old iOS, but anyway it's still supported by this plugin) and with XML files. `onDownloadStart` is not being called and the XML is just being opened.

**Comment by ps-filipefreitas** [comment]
anyone found a fix for this?
with latest versions (both plugin and ios), onDownloadStartRequest doesn't seem to be triggered

**Comment by ggmanuilov** [comment]
Some problem on IOS 16.2. When I click on button download on webview in debug mode I see that downloadCallback is called and progress is up.
