### ISSUE TITLE
html has <input type="color">, when click app crash.

### ISSUE THREAD

**Issue by obf1313** [pichillilorenzo/flutter_inappwebview#843]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.0.6       |
| Plugin version       |         5.3.2      |
| Android version      |      8.0.0         |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
not crash

**Current behavior:** 
when click label to choose color will crash.
## Steps to reproduce

1. This
2. Than that
3. Then

## Images   
![image](https://user-images.githubusercontent.com/36187787/118246423-84dbdd00-b4d4-11eb-95b0-2588b56d3254.png)
![image](https://user-images.githubusercontent.com/36187787/118246455-8e654500-b4d4-11eb-9f49-8c638c6f9b89.png)

## Stacktrace/Logcat   
W/google-breakpad( 3373): ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad( 3373): Chrome build fingerprint:
W/google-breakpad( 3373): 70.0.3538.110
W/google-breakpad( 3373): 353811050
W/google-breakpad( 3373): ### ### ### ### ### ### ### ### ### ### ### ### ###
F/libc    ( 3373): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68 in tid 3373 (m.meehoo.yc_big)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HONOR/AGS2-W09HN/HWAGS2:8.0.0/HUAWEIAGS2-W09HN/182(C00):user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 3373, tid: 3373, name: m.meehoo.yc_big  >>> com.meehoo.yc_big <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x68
Cause: null pointer dereference
    x0   0000007090bde400  x1   00000000ffffffff  x2   0000000000000075  x3   00000000ffffffff
    x4   0000000000000075  x5   000000709bb96a31  x6   0000000000000000  x7   7f7f7f7f7f7f7f7f
    x8   0000000000000000  x9   a2438105a71629a9  x10  0000000000430000  x11  0000000000000001
    x12  0000000000000001  x13  0000000000000074  x14  00000070bd871320  x15  0000000000000000
    x16  0000000000000007  x17  00000070bd85f580  x18  0000000012ef39c0  x19  00000000ffffffff
    x20  000000708322bd68  x21  0000007090bde400  x22  00000070bdabb2a0  x23  0000007fceccf708
    x24  0000007fceccf6f0  x25  00000070c29d9a48  x26  00000070bda94c60  x27  00000070bda94c58
    x28  0000007fceccf740  x29  0000007fceccf4e0  x30  00000070a5a7d9b8
    sp   0000007fceccf4b0  pc   00000070a37fc334  pstate 0000000060000000
backtrace:
    #00 pc 00000000008a5334  /system/app/WebViewGoogle/WebViewGoogle.apk (offset 0x166f000)
    #01 pc 0000000002b269b4  /system/app/WebViewGoogle/WebViewGoogle.apk (offset 0x166f000)
Lost connection to device.

**Comment by tashfeenzaidi** [comment]
im having the same issue on input type email only when keyboard remain open
