### ISSUE TITLE
In iOS 10.0.1, window.flutter_inappWebView is undefined

### ISSUE THREAD

**Issue by tanlianghao** [pichillilorenzo/flutter_inappwebview#844]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.0.4        |
| Plugin version       |       5.3.2        |
| Android version      |               |
| iOS version          |        10.0.1       |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
Windows. flutter_inappWebView works well on lower versions of iOS
**Current behavior:** 
In lower versions of iOS, window.flutter_inappWebView is undefined

**Comment by HuberyYang** [comment]
The problem was also found in iOS 11.0.3
