### ISSUE TITLE
flutter web compatibility

### ISSUE THREAD

**Issue by saguado69** [pichillilorenzo/flutter_inappwebview#849]
## Environment

Will be very nice to make this plugin compatible with flutter web. Do you have any plans on this?

Thanks,

Santi.

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 

**Alternatives you've considered:**   

**Images:**

**Comment by CaptainDario** [comment]
@saguado69 I do not know if it helps you but you could use this [plugin](https://pub.dev/packages/easy_web_view) until inappwebview adds support for web.

**Comment by Katekko** [comment]
> @saguado69 I do not know if it helps you but you could use this [plugin](https://pub.dev/packages/easy_web_view) until inappwebview adds support for web.
> 
> However I would really like to see inappwebview get support for all platforms (mobile, desktop and web)!

Unfourtunally this lib is not null safety yet

**Comment by CaptainDario** [comment]
@Katekko if you require null safety there is [webviewX](https://pub.dev/packages/webviewx).
Have not tried it though...

**Comment by pichillilorenzo** [comment]
New version 6 with web support is out right now!
