### ISSUE TITLE
Could not find module OrderedSet for target x86_64-apple-ios-simulator

### ISSUE THREAD

**Issue by EArminjon** [pichillilorenzo/flutter_inappwebview#851]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.3.0-12.1-pre       |
| Plugin version       |      5.3.2         |
| Android version      |               |
| iOS version          |     14.5          |
| Xcode version        |           12.5    |

Device information: 

## Description

**Expected behavior:** 
I would see a normal build

**Current behavior:** 
![image](https://user-images.githubusercontent.com/37028599/118875831-d1685380-b8ec-11eb-84b7-f784d83e3ff7.png)

## Steps to reproduce

I'm on MAC MINI M1
Create a new flutter project, add your dependencies run with xcode : boom.

1. Create new flutter project
2. Add flutter_inappwebview: ^5.3.2 
3. flutter pub get && cd ios && pod install
4. Open IOs fplder with Xcode and run

Note that, the podfile.lock seems to be ok :

```
 - flutter_inappwebview (0.0.1):
    - Flutter
    - flutter_inappwebview/Core (= 0.0.1)
    - OrderedSet (~> 5.0)
  - flutter_inappwebview/Core (0.0.1):
    - Flutter
    - OrderedSet (~> 5.0)
```

## Images   
Default flutter project settings in xcode : 
![image](https://user-images.githubusercontent.com/37028599/118878070-76842b80-b8ef-11eb-8e0d-6398c561227d.png)

**Comment by EArminjon** [comment]
Already checked :(

**Comment by EArminjon** [comment]
Seems to work when launching Xcode with Rosetta... 
I didn't determine if it's a flutter issue or a flutter_inappwebview issue.

**Comment by hiens** [comment]
I face the same issue after upgrade flutter to v2.2.0

**Comment by dvird** [comment]
?

**Comment by JSBmanD** [comment]
I have the same problem. Works with XCode with Rosetta but performance is degraded.
