### ISSUE TITLE
web is not fullscreen

### ISSUE THREAD

**Issue by EastLee** [pichillilorenzo/flutter_inappwebview#857]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.0.4 |
| Plugin version       |       5.3.2|
| iOS version          |       14.5.1|
| device                  |       ipad|
| Xcode version        |      12.4 |

I find  web is not  fullscreen sometimes.
![image](https://user-images.githubusercontent.com/13636225/119343992-b53c2c00-bcc9-11eb-8988-70945c2c9408.png)

Green area is a web page  and I set its width 3000px and height 2000px，but it still has a blank area.

**Comment by dpatel** [comment]
Were you able to fix the issue? We are having the same issue but it is, in particular, Samsung devices only.

**Comment by sengerts** [comment]
I am having the same problem when using Samsungs Dex desktop mode. The webview is only like a quarter of the full screen. Any ideas on how to fix this?
Note: I think this issue is the same as #871
