### ISSUE TITLE
My app use four InappwebView in the NavigationBar and each use 'Hybrid Composition=true',I use Navigator.push function and back to NavigationBar,then BottomNavigationBar missing

### ISSUE THREAD

**Issue by godfeather** [pichillilorenzo/flutter_inappwebview#859]
step 1 :  bottom navigation bar well
![961621923155_ pic](https://user-images.githubusercontent.com/51359288/119448128-7b1f6880-bd63-11eb-89f1-a873309f5dfd.jpg)
step 2: navigate to second page
![951621923154_ pic](https://user-images.githubusercontent.com/51359288/119448187-8e323880-bd63-11eb-9b5d-0118ebeec209.jpg)
step 3: bottom navigation bar disappeared
![941621923153_ pic](https://user-images.githubusercontent.com/51359288/119448271-a609bc80-bd63-11eb-8b55-35bf0f424747.jpg)

**Comment by godfeather** [comment]
I reproduce it on every flutter Widgets

**Comment by godfeather** [comment]
when I don't using the hybrid composition , the problem will not appear

**Comment by godfeather** [comment]
the problem only reproduce on Android, not on IOS

**Comment by godfeather** [comment]
I upgrade the flutter to newest version ，then It's ok

**Comment by w-kazuyoshi** [comment]
@godfeather 
Can you give me some information about "flutter doctor"?
