### ISSUE TITLE
[Bug] InAppWebView shouldOverrideUrlLoading is called on the initial load of the WebView, iOS only

### ISSUE THREAD

**Issue by rubenferreira97** [pichillilorenzo/flutter_inappwebview#863]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.3.0-13.0.pre.191         |
| Plugin version       |         5.3.2      |
| Android version      |       30        |
| iOS version          |        14.3       |
| Xcode version        |         12.5      |

Device information: iPhone 12 Pro Max - iOS 14.3

## Description

**Expected behavior:**
Quoting from the documentation (https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/HeadlessInAppWebView/shouldOverrideUrlLoading.html):

> Give the host application a chance to take control when a URL is about to be loaded in the current WebView. **This event is not called on the initial load of the WebView.**

**Current behavior:** 
`shouldOverrideUrlLoading` is called on iOS on initial load. In Android everything works as expected.

## Steps to reproduce

1. Set `useShouldOverrideUrlLoading: true` in `initialOptions`
2. Implement `shouldOverrideUrlLoading` in `InAppWebView`
3. Place a breakpoint or print something in `shouldOverrideUrlLoading`

Code:
```
InAppWebView(
            initialData: InAppWebViewInitialData(
                data: html,
                baseUrl: Uri.parse(Config.BASE_URL)),
            initialOptions: InAppWebViewGroupOptions(
              android: AndroidInAppWebViewOptions(
                useHybridComposition: true,
              ),
              crossPlatform: InAppWebViewOptions(
                  supportZoom: false,
                  disableHorizontalScroll: true,
                  useShouldOverrideUrlLoading: true,
                  horizontalScrollBarEnabled: false),
            ),
            onLoadStop: (controller, url) {
              controller.injectJavascriptFileFromAsset(
                  assetFilePath: 'assets/js/all.min.js');
            },
            shouldOverrideUrlLoading: (controller, navigationAction) async {
              print('Hi');
              //launch(navigationAction.request.url.toString());
              return NavigationActionPolicy.CANCEL;
            },
          );
```

**Comment by kaichii** [comment]
> * [x]  I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
> * [x]  I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
> * [x]  I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
> * [x]  I have already searched for the same problem
> 
> ## Environment
> Technology	Version
> Flutter version	2.3.0-13.0.pre.191
> Plugin version	5.3.2
> Android version	30
> iOS version	14.3
> Xcode version	12.5
> Device information: iPhone 12 Pro Max - iOS 14.3
> 
> ## Description
> **Expected behavior:**
> Quoting from the documentation (https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/HeadlessInAppWebView/shouldOverrideUrlLoading.html):
> 
> > Give the host application a chance to take control when a URL is about to be loaded in the current WebView. **This event is not called on the initial load of the WebView.**
> 
> **Current behavior:**
> `shouldOverrideUrlLoading` is called on iOS on initial load. In Android everything works as expected.
> 
> ## Steps to reproduce
> 1. Set `useShouldOverrideUrlLoading: true` in `initialOptions`
> 2. Implement `shouldOverrideUrlLoading` in `InAppWebView`
> 3. Place a breakpoint or print something in `shouldOverrideUrlLoading`
> 
> Code:
> 
> ```
> InAppWebView(
>             initialData: InAppWebViewInitialData(
>                 data: html,
>                 baseUrl: Uri.parse(Config.BASE_URL)),
>             initialOptions: InAppWebViewGroupOptions(
>               android: AndroidInAppWebViewOptions(
>                 useHybridComposition: true,
>               ),
>               crossPlatform: InAppWebViewOptions(
>                   supportZoom: false,
>                   disableHorizontalScroll: true,
>                   useShouldOverrideUrlLoading: true,
>                   horizontalScrollBarEnabled: false),
>             ),
>             onLoadStop: (controller, url) {
>               controller.injectJavascriptFileFromAsset(
>                   assetFilePath: 'assets/js/all.min.js');
>             },
>             shouldOverrideUrlLoading: (controller, navigationAction) async {
>               print('Hi');
>               //launch(navigationAction.request.url.toString());
>               return NavigationActionPolicy.CANCEL;
>             },
>           );
> ```

Any solution?

**Comment by zoltanbalog** [comment]
@rubenferreira97 or @kaichii do you know any solution for this problem?

**Comment by kaichii** [comment]
> @rubenferreira97 or @kaichii do you know any solution for this problem?

I add logic to handle "about:blank" url on ios platform.
