### ISSUE TITLE
 OnLoadStart Not Executed when url changes

### ISSUE THREAD

**Issue by sahad752** [pichillilorenzo/flutter_inappwebview#866]
onLoadStart:
                    (InAppWebViewController controller, String url) async {
                  print("ONloadStart exected $url");
                  if (url.startsWith("https://mySite.com/")) {
                    print("url #####################################$url");

                 
             RegExp regExp = new RegExp("access_token=(.*?)&");
                      this.token = regExp.firstMatch(url)?.group(1);

                      print(
                          "ACCESS TOKEN INAPP WEBVIEW TOKEN #####################################$token ");

**Comment by nikhilmufc7** [comment]
I had a similar issue in your`url.startsWith("https://mySite.com/"` add `www.` before your site it should work, i think in app web view adds that by default to all urls 
Example :  `url.startsWith("https://www.mySite.com/"`

**Comment by sahad752** [comment]
@nikhilmufc7 Thank you!Will try your solution.This issue is currently only on ios,In Android its working perfectly

**Comment by bsp003** [comment]
@sahad752 I too am facing the same issue. Did the @nikhilmufc7 solution solve for you? No luck for me yet.

**Comment by sahad752** [comment]
@bsp003 nop !The above solution didnt work.
