### ISSUE TITLE
webview not show in fullscreen.

### ISSUE THREAD

**Issue by dharmeshapptrait** [pichillilorenzo/flutter_inappwebview#871]
Device: Samsung

![2021-06-03-16-13-03](https://user-images.githubusercontent.com/78532352/120633159-735c7400-c487-11eb-9a30-9b04b8e4ed8e.jpg)

![2021-06-03-16-12-44](https://user-images.githubusercontent.com/78532352/120633185-7b1c1880-c487-11eb-92ac-758a7a0b1354.jpg)

![2021-06-03-16-11-33](https://user-images.githubusercontent.com/78532352/120633244-8a9b6180-c487-11eb-9269-0bed9eee4d83.jpg)

Code:
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

class WebviewTestDemo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _WebviewTestDemo(); 
}

class _WebviewTestDemo extends State<WebviewTestDemo>{
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InAppWebView(
          initialUrlRequest: URLRequest(url: Uri.parse("https://github.com")),
        )
    );
  }
}

**Comment by sengerts** [comment]
I am having the same problem when using Samsungs Dex desktop mode. The webview is only like a quarter of the full screen. Any ideas on how to fix this?
