### ISSUE TITLE
Attempt to read from field 'io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.activityPluginBinding' on a null object reference

### ISSUE THREAD

**Issue by nguyenkin** [pichillilorenzo/flutter_inappwebview#872]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | Flutter (Channel stable, 2.2.1)              |
| Plugin version       | Flutter (Channel stable, 2.2.1              |
| Android version      | Android 8 (67%) - Android 10 (33%)              |
| iOS version          |               |
| Xcode version        |               |

Device information: <LGE V30+ (67%) - AQUOS zero5G basic (33%>

## Description

**Expected behavior:** 
No crashes
**Current behavior:** 
Firebase crashlytics tracked this issue

## Stacktrace/Logcat   
<code>Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.activityPluginBinding' on a null object reference
com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity.dispose (InAppBrowserActivity.java:28)
com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity.close (InAppBrowserActivity.java:12)
com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity.onKeyDown (InAppBrowserActivity.java:15)
android.view.KeyEvent.dispatch (KeyEvent.java:2688)
androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28 (KeyEventDispatcher.java:63)
androidx.core.view.KeyEventDispatcher.dispatchKeyEvent (KeyEventDispatcher.java:21)
androidx.core.app.ComponentActivity.dispatchKeyEvent (ComponentActivity.java:18)
androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent (AppCompatActivity.java:22)
androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent (WindowCallbackWrapper.java:2)
androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent (AppCompatDelegateImpl.java:8)
com.android.internal.policy.DecorView.dispatchKeyEvent (DecorView.java:361)
android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent (ViewRootImpl.java:5093)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4965)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4289)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4342)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4308)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4316)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4289)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4342)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4308)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4451)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4316)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4508)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4289)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4342)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4308)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4316)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4289)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4342)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4308)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4484)
android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent (ViewRootImpl.java:4645)
android.view.inputmethod.InputMethodManager$PendingEvent.run (InputMethodManager.java:2448)
android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback (InputMethodManager.java:2011)
android.view.inputmethod.InputMethodManager.finishedInputEvent (InputMethodManager.java:2002)
android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished (InputMethodManager.java:2425)
android.view.InputEventSender.dispatchInputEventFinished (InputEventSender.java:141)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:325)
android.os.Looper.loop (Looper.java:142)
android.app.ActivityThread.main (ActivityThread.java:6703)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:769)</code>

**Comment by macortesn** [comment]
I have the same issue. Any solution?
