### ISSUE TITLE
In Android it can work ， but in iOS it does not work 。

### ISSUE THREAD

**Issue by sunnyAuto** [pichillilorenzo/flutter_inappwebview#875]
@tneotia with `initialData` you don't have a base href as you would have in a normal website loaded from a domain or using the localhost server. So, you need to specify in that case the full file path.
For example, on Android, using your file path, it should to be `file:///android_asset/flutter_assets/assets/css-file.css`, that is
```html
<link href="file:///android_asset/flutter_assets/assets/css-file.css" rel="stylesheet">
```
Or you can create and start a localhost server, so the path to your css file would be `http://localhost:8080/assets/css-file.css`, or you can use the `initialFile` to load an HTML file inside your assets directory (in this case, `css-file.css` would be ok if the HTML file is at the same folder level)

_Originally posted by @pichillilorenzo in https://github.com/pichillilorenzo/flutter_inappwebview/issues/695#issuecomment-802759412_

**Comment by rakesh0689** [comment]
Any update on this issue?? How to make it work??
