### ISSUE TITLE
Using localstorage or session storage 

### ISSUE THREAD

**Issue by The-Gk** [pichillilorenzo/flutter_inappwebview#876]
Hey first of all I love this package very much more than the official plugin.

 I want to use this plugin to show my website on my Android app. But the problem is now is that my website use session storage and localstorage for storing some data inside the browser but how to store session data from website inside the flutter android app?

Any way to store localstorage data from my website inside android app?

**Comment by AhmedHamdan54** [comment]
Using the method `onLoadStart` you can use `controller.evaluateJavascript()` where you can add any javascript code.
You can add per example ` source:"window.localStorage.store('authenticationToken','some token')`

The full code will be something like this.
```
  onLoadStart:(InAppWebViewController controller, Uri? uri) async{
      await controller.evaluateJavascript(source:"window.localStorage.setItem('authenticationtoken','some token')" );
        },
```
