### ISSUE TITLE
In IOS don't keep the session of wordpress

### ISSUE THREAD

**Issue by Makarov96** [pichillilorenzo/flutter_inappwebview#880]
I'm implementing a session start with wordpress and flutter_inapwebview and manage to implement it, the problem
arises when I want to navigate to another screen, this no longer keeps me the session saved

- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem arises when I want to navigate to another screen, this no longer keeps me the session saved

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |   1.22.4       |
| Plugin version       |       ^4.0.0+4        |
| Android version      |               |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by bbslab** [comment]
I have same problem...
