### ISSUE TITLE
How we can clear goBack history in android or ios

### ISSUE THREAD

**Issue by apt-team-018** [pichillilorenzo/flutter_inappwebview#885]
How we can clear goBack history in android or ios

I am trying to use that  webViewController?.clearHistory()

but it is not working

How we can resolve it

**Comment by robertosw** [comment]
Using and catching `webViewController.clearHistory()` results in:
`MissinPluginException (No implementation found for method clearHistory on channel com.pichillilorenzo/flutter_inappwebview_0)`

**Comment by dheerajbred** [comment]
Any idea about this?

**Comment by dheerajbred** [comment]
webViewController?.android.clearHistory(); is not working either
