### ISSUE TITLE
A problem occurred configuring project ':flutter_inappwebview'. It seen that flutter_inappwebview doesn't work well in Android, what can I do to fix this bug?

### ISSUE THREAD

**Issue by chenxi-lu** [pichillilorenzo/flutter_inappwebview#886]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
A problem occurred configuring project ':flutter_inappwebview'.         
> Could not resolve all artifacts for configuration ':flutter_inappwebview:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.6.3.            
     Required by:                                                       
         project :flutter_inappwebview                                  
      > Could not resolve com.android.tools.build:gradle:3.6.3.         
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.6.3/gradle-3.6.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.6.3/gradle-3.6.3.pom'.
               > Connect to dl.google.com:443 [dl.google.com/180.163.150.33] failed: Read timed out
> Could not get unknown property 'android' for project ':flutter_inappwebview' of type org.gradle.api.Project.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 38s

**Comment by nietsmmar** [comment]
What gradle version are you using? What flutter version etc?

**Comment by fabiancrx** [comment]
@lesliebigfans it seems that the error you are getting is downloading the dependencies itself(HTTP 443). Try using another connection or a VPN, as it should not be related to this package(at least the error shown in the logs)
