### ISSUE TITLE
Adding cookie in InAppWebview problem since I cannot find full example code with cookie

### ISSUE THREAD

**Issue by djks74** [pichillilorenzo/flutter_inappwebview#894]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.2.0      |
| Plugin version       |         5.3.2      |

Device information: <Android Version>

## Description

**Expected behavior:** 
When I open InAppWebview with url from my site, it should loading the page and read cookies as I needed when user logged in.

**Current behavior:** 
Cookie only working after I open flutter_webview from flutter webview plugin in other page, this cookie not working since I might wrong to embeed it? Please help me to fix my code working with cookie?

## Steps to reproduce

import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_cookie_manager/webview_cookie_manager.dart';
import '../../resources/api_provider.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  final String url;
  final String title;
  const MyApp({Key key, this.url, this.title}) : super(key: key);
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey webViewKey = GlobalKey();

  InAppWebViewController webViewController;
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      ));

  PullToRefreshController pullToRefreshController;
  String url = "";
  double progress = 0;
  final urlController = TextEditingController();
  CookieManager _cookieManager = CookieManager.instance();
  InAppWebViewController webView;
  final cookieManager = WebviewCookieManager();
  bool injectCookies = false;
  final expiresDate =
      DateTime.now().add(Duration(days: 3)).millisecondsSinceEpoch;

  @override
  void initState() {
    _seCookies();
    super.initState();

    pullToRefreshController = PullToRefreshController(
      options: PullToRefreshOptions(
        color: Colors.blue,
      ),
      onRefresh: () async {
        if (Platform.isAndroid) {
          webViewController?.reload();
        } else if (Platform.isIOS) {
          webViewController?.loadUrl(
              urlRequest: URLRequest(url: await webViewController?.getUrl()));
        }
      },
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar:
          widget.title != null ? AppBar(title: Text(widget.title)) : AppBar(),
      body: Container(
        child: Stack(
          children: <Widget>[
            injectCookies
                ? InAppWebView(
                    key: webViewKey,
                    initialUrlRequest: URLRequest(
                        url: Uri.parse(
                            "https://mysite.co.id/store-manager/orderslist")),
                    initialOptions: options,
                    pullToRefreshController: pullToRefreshController,
                    onWebViewCreated: (controller) {
                      webViewController = controller;
                    },
                    onLoadStart: (controller, url) {
                      setState(() {
                        this.url = url.toString();
                        urlController.text = this.url;
                      });
                    },
                    androidOnPermissionRequest:
                        (controller, origin, resources) async {
                      return PermissionRequestResponse(
                          resources: resources,
                          action: PermissionRequestResponseAction.GRANT);
                    },
                    shouldOverrideUrlLoading:
                        (controller, navigationAction) async {
                      var uri = navigationAction.request.url;

                      if (![
                        "http",
                        "https",
                        "file",
                        "chrome",
                        "data",
                        "javascript",
                        "about",
                      ].contains(uri.scheme)) {
                        if (await canLaunch(url)) {
                          // Launch the App
                          await launch(
                            url,
                          );
                          // and cancel the request
                          return NavigationActionPolicy.CANCEL;
                        }
                      }

                      return NavigationActionPolicy.ALLOW;
                    },
                    onLoadStop: (controller, url) async {
                      List<Cookie> cookies =
                          await _cookieManager.getCookies(url: url);
                      cookies.forEach((cookie) {
                        print(cookie.name + " " + cookie.value);
                      });
                    },
                    onLoadError: (controller, url, code, message) {
                      pullToRefreshController.endRefreshing();
                    },
                    onProgressChanged: (controller, progress) {
                      if (progress == 100) {
                        pullToRefreshController.endRefreshing();
                      }
                      setState(() {
                        this.progress = progress / 100;
                        urlController.text = this.url;
                      });
                    },
                    onUpdateVisitedHistory: (controller, url, androidIsReload) {
                      setState(() {
                        this.url = url.toString();
                        urlController.text = this.url;
                      });
                    },
                    onConsoleMessage: (controller, consoleMessage) {
                      print(consoleMessage);
                    },
                  )
                : progress < 1.0
                    ? LinearProgressIndicator(value: progress)
                    : Container(),
          ],
        ),
      ),
    );
  }

  _seCookies() async {
    Uri uri = Uri.parse(url);
    String domain = uri.host;
    print('Domain: ' + domain);
    ApiProvider apiProvider = ApiProvider();

    apiProvider.cookieList.forEach((element) async {
      await cookieManager.setCookies([
        //..expires = DateTime.now().add(Duration(days: 10))
        //..httpOnly = true
      ]);
    });
    setState(() {
      injectCookies = true;
    });
  }
}

==============================
I cannot find any example with new version 5.3.2 for cookie embeeded.

Hope you can help me to fix the cookie for this code with InAppWebview.

With older InAppbrowser last time I can manage with webview cookie manager plugin, but with newest InAppwebview update now cookie is messed with webview cookie manager and I confuse to fix the code since I really not coder!

If you think without webview cookie manager is fine, hope you can help me to fix my code.

Please help! Thanks in advance.

with kind regards,
Sandi

**Comment by djks74** [comment]
Yes, I did searching and cannot find full code of example InAppWebview with cookie embeeded.

Please help! Thanks.

**Comment by alectogeek** [comment]
I can't find appropriate di=ocumentation as well.
Neither about how does it work by default nor how to store and reuse cookies manually.
