### ISSUE TITLE
iOS Archive failed - Undefined symbols for architecture arm64 

### ISSUE THREAD

**Issue by weldEnnefzi** [pichillilorenzo/flutter_inappwebview#895]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | stable channel - 2.2.1 |
| Plugin version       | 5.3.2 |
| Android version      |  |
| iOS version          | 14.5 |
| Xcode version        | 12.5 |

Device information: iphone 12 

## Description
My project works fine with Android but crashes with iOS (Failed to build iOS app - ** ARCHIVE FAILED **). 
Error: Undefined symbols for architecture arm64: 
"nominal type descriptor for Swift.FlattenSequence.Iterator", referenced from: libflutter_inappwebview.a(WKUserContentController.o)
And other files.
I attached the log files for more details.

## Stacktrace/Logcat   
[building_ios.log](https://github.com/pichillilorenzo/flutter_inappwebview/files/6694051/building_ios.log)

**Comment by szz-dvl** [comment]
Hi!

Same behaviour here:

```
Undefined symbols for architecture x86_64:
  "Foundation.URLRequest.allowsConstrainedNetworkAccess.getter : Swift.Bool", referenced from:
      (extension in flutter_inappwebview):Foundation.URLRequest.toMap() -> [Swift.String : Any?] in libflutter_inappwebview.a(URLRequest.o)
  "Foundation.URLRequest.allowsExpensiveNetworkAccess.getter : Swift.Bool", referenced from:
      (extension in flutter_inappwebview):Foundation.URLRequest.toMap() -> [Swift.String : Any?] in libflutter_inappwebview.a(URLRequest.o)
  "Foundation.URLRequest.allowsConstrainedNetworkAccess.setter : Swift.Bool", referenced from:
      (extension in flutter_inappwebview):Foundation.URLRequest.init(fromPluginMap: [Swift.String : Any?]) -> Foundation.URLRequest in libflutter_inappwebview.a(URLRequest.o)
  "Foundation.URLRequest.allowsExpensiveNetworkAccess.setter : Swift.Bool", referenced from:
      (extension in flutter_inappwebview):Foundation.URLRequest.init(fromPluginMap: [Swift.String : Any?]) -> Foundation.URLRequest in libflutter_inappwebview.a(URLRequest.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If it can help anyone.

Thanks!

**Comment by winterdl** [comment]
```
Open ios/YourAppName.xcodeproj in Xcode
Right-click on Your App Name in the Project Navigator on the left, and click New File…
Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
This should fix the problem
```

https://github.com/mxcl/PromiseKit/issues/1059
