### ISSUE TITLE
I want to modify the name of JAVASCRIPT_BRIDGE_NAME

### ISSUE THREAD

**Issue by devChengs** [pichillilorenzo/flutter_inappwebview#897]
I want to modify the name of JAVASCRIPT_BRIDGE_NAME, can I update it when I have time

It is   public static final String JAVASCRIPT_BRIDGE_NAME = "flutter_inappwebview";

flutter_inappwebview replace  "app name" or "person name"

**Comment by cipchk** [comment]
@pichillilorenzo +1
