### ISSUE TITLE
Android 12 Chromium WebView package does not exist

### ISSUE THREAD

**Issue by nastaran-mohammadi** [pichillilorenzo/flutter_inappwebview#898]
Flutter version: 2.2.2
flutter_inappwebview: ^5.3.2
Android version:12

Device information:  Google Pixel 3 XL

it crashes on this device with this bug:
06-23 10:17:01.076 22137 22137 E WebViewFactory: Chromium WebView package does not exist
06-23 10:17:01.076 22137 22137 E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:377)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:442)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:297)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.CookieManager.getInstance(CookieManager.java:50)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.getCookieManager(MyCookieManager.java:2)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.<init>(MyCookieManager.java:5)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:15)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:3)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.engine.c.g(FlutterEngineConnectionRegistry.java:5)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:11)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.example.dooneh.MainActivity.i(MainActivity.kt:1)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.android.i.i(FlutterFragment.java:3)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.android.e.k(FlutterActivityAndFragmentDelegate.java:8)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.android.i.B0(FlutterFragment.java:3)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.Fragment.g1(Fragment.java:7)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.u.c(FragmentStateManager.java:17)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.u.m(FragmentStateManager.java:22)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.d0(FragmentManager.java:34)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.d1(FragmentManager.java:10)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.a0(FragmentManager.java:4)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.S(FragmentManager.java:9)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.y(FragmentManager.java:4)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.i.c(FragmentController.java:1)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.e.onStart(FragmentActivity.java:5)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.Activity.performStart(Activity.java:8061)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3633)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.os.Looper.loopOnce(Looper.java:201)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.os.Looper.loop(Looper.java:288)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.ActivityThread.main(ActivityThread.java:7796)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
06-23 10:17:01.076 22137 22137 E WebViewFactory: error instantiating provider
06-23 10:17:01.076 22137 22137 E WebViewFactory: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:481)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:297)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.CookieManager.getInstance(CookieManager.java:50)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.getCookieManager(MyCookieManager.java:2)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.<init>(MyCookieManager.java:5)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:15)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:3)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.engine.c.g(FlutterEngineConnectionRegistry.java:5)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:11)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.example.dooneh.MainActivity.i(MainActivity.kt:1)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.android.i.i(FlutterFragment.java:3)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.android.e.k(FlutterActivityAndFragmentDelegate.java:8)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at io.flutter.embedding.android.i.B0(FlutterFragment.java:3)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.Fragment.g1(Fragment.java:7)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.u.c(FragmentStateManager.java:17)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.u.m(FragmentStateManager.java:22)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.d0(FragmentManager.java:34)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.d1(FragmentManager.java:10)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.a0(FragmentManager.java:4)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.S(FragmentManager.java:9)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.n.y(FragmentManager.java:4)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.i.c(FragmentController.java:1)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at androidx.fragment.app.e.onStart(FragmentActivity.java:5)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.Activity.performStart(Activity.java:8061)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3633)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.os.Looper.loopOnce(Looper.java:201)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.os.Looper.loop(Looper.java:288)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.app.ActivityThread.main(ActivityThread.java:7796)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
06-23 10:17:01.076 22137 22137 E WebViewFactory: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:377)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:442)
06-23 10:17:01.076 22137 22137 E WebViewFactory: 	... 37 more
06-23 10:17:01.078 22137 22137 D AndroidRuntime: Shutting down VM
06-23 10:17:01.078 22137 22137 E AndroidRuntime: FATAL EXCEPTION: main
06-23 10:17:01.078 22137 22137 E AndroidRuntime: Process: com.dooneh, PID: 22137
06-23 10:17:01.078 22137 22137 E AndroidRuntime: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:312)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.webkit.CookieManager.getInstance(CookieManager.java:50)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.getCookieManager(MyCookieManager.java:2)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at com.pichillilorenzo.flutter_inappwebview.MyCookieManager.<init>(MyCookieManager.java:5)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:15)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:3)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at io.flutter.embedding.engine.c.g(FlutterEngineConnectionRegistry.java:5)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:11)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at com.example.dooneh.MainActivity.i(MainActivity.kt:1)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at io.flutter.embedding.android.i.i(FlutterFragment.java:3)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at io.flutter.embedding.android.e.k(FlutterActivityAndFragmentDelegate.java:8)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at io.flutter.embedding.android.i.B0(FlutterFragment.java:3)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.Fragment.g1(Fragment.java:7)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.u.c(FragmentStateManager.java:17)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.u.m(FragmentStateManager.java:22)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.n.d0(FragmentManager.java:34)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.n.d1(FragmentManager.java:10)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.n.a0(FragmentManager.java:4)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.n.S(FragmentManager.java:9)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.n.y(FragmentManager.java:4)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.i.c(FragmentController.java:1)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at androidx.fragment.app.e.onStart(FragmentActivity.java:5)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8061)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3633)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7796)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:481)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:297)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	... 36 more
06-23 10:17:01.078 22137 22137 E AndroidRuntime: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:377)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:442)
06-23 10:17:01.078 22137 22137 E AndroidRuntime: 	... 37 more

**Comment by PieterAelse** [comment]
@Bunny1376  I ran into the same issue after updating my Pixel 5 from Android 11 to Android 12 beta. Turned out that the "Webview" package/app was somehow not working correctly, other apps were also crashing including e.g. Gmail itself.

I was able to fix it by going to the PlayStore, searching for "Webview" and then opening the listing for "Android System WebView" (by GoogleLCC). I pressed Uninstall and later again "Enable"/"Install" and after that the crashed were gone.
