### ISSUE TITLE
takeScreenshot : width and height must be > 0

### ISSUE THREAD

**Issue by juliengit2** [pichillilorenzo/flutter_inappwebview#90]
When calling  **InAppWebViewController.takeScreenshot**

example:

```
webView.loadData(data).then((e) {
  webView.takeScreenshot().then((bytes) {
  ..
 });
});
```
  
we get from time to time :

> Failed to handle method call
> E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_145(20772): java.lang.IllegalArgumentException: width and height must be > 0
> E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_145(20772):    at android.graphics.Bitmap.createBitmap(Bitmap.java:933)
> E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_145(20772):    at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
> E/MethodChannel#com.pichillilorenzo/flutter_inappwebview_145(20772):    at android.graphics.Bitmap.createBitmap(Bitmap.java:879)

and there is also this memory issue from time to time :

> <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> E/Adreno-GSL(20772): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> W/Adreno-GSL(20772): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> E/Adreno-GSL(20772): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> W/Adreno-ES20(20772): <core_glTexImage2D:539>: GL_OUT_OF_MEMORY

Any idea?

**Comment by vladimirmedyannikov** [comment]
Trying call **takeScreenshot** after **onLoadStop** in `InAppWebView`, i get an exception

**Call example:**
`onLoadStop: (InAppWebViewController controller, url) async {
final bytes = await controller.takeScreenshot();
}`

**Exception:**
`java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
at com.pichillilorenzo.flutter_inappwebview.InAppWebView.InAppWebView$4.run(InAppWebView.java:865)`

Maybe need to return null if an image error occurs?

**Comment by pichillilorenzo** [comment]
@juliengit2 can you test using the latest version? However, the plugin name now is `flutter_inappwebview`! Can you share your code?

@vladimirmedyannikov which version of the plugin are you using?? Also, can you share your code?

Thanks!

**Comment by vladimirmedyannikov** [comment]
@pichillilorenzo now test v2.1.0+1
Exception still exists
```dart
InAppWebView(
                                initialUrl: remoteTask.url,
                                initialOptions: InAppWebViewWidgetOptions(
                                  inAppWebViewOptions: InAppWebViewOptions(
                                      useShouldOverrideUrlLoading: true,
                                      useOnLoadResource: true,
                                      javaScriptEnabled: true,
                                      incognito: true,
                                      mediaPlaybackRequiresUserGesture: false,
                                      clearCache: true,
                                      javaScriptCanOpenWindowsAutomatically: false,
                                  ),
                                  androidInAppWebViewOptions: AndroidInAppWebViewOptions(),
                                  iosInAppWebViewOptions: IosInAppWebViewOptions(
                                      allowsAirPlayForMediaPlayback: false,
                                  allowsInlineMediaPlayback: true),
                                ),
                                onLoadStop: (InAppWebViewController controller,
                                    message) async {
                                  final res = await controller.takeScreenshot();
                                })
```

**Comment by pichillilorenzo** [comment]
@vladimirmedyannikov can you also provide the URL to test? thanks!
