### ISSUE TITLE
Webview becomes unresponsive on three finger swipe

### ISSUE THREAD

**Issue by shivangguptaa** [pichillilorenzo/flutter_inappwebview#906]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |           2.2.2    |
| Plugin version       |            5.3.2   |
| Android version      |      10         |

Device information: 

## Description

Webview becomes unresponsive when I try to take screenshot using three finger swipe. Normal screenshots work fine. I have to close the webview and open it again for it to work properly again

**Comment by ycv005** [comment]
Facing same issue, when taking screenshot of the any content of any url, the webview freeze and need to restart the app. @pichillilorenzo any idea ?

**Comment by blisssayyid** [comment]
Yes, I've had this problem, too, and on realme's device, my system is Android 11, and as long as there's a three-finger operation, it freezes right away

**Comment by afdev5** [comment]
I have the same issue, how to fix it?

**Comment by ycv005** [comment]
@pichillilorenzo any update on this ?

**Comment by pichillilorenzo** [comment]
I'm not able to reproduce the issue. I tested the example app in release mode using a real Android 11 device.
This is my screenrecord:
![Record_2022-04-25-13-36-57 mp4](https://user-images.githubusercontent.com/5956938/165081966-c634abbd-ed91-4803-b6f9-84117db0c64e.gif)

Do you have any logs?

**Comment by ycv005** [comment]
Yes, now it's working and could be closed @pichillilorenzo
