### ISSUE TITLE
IOSUIModalPresentationStyle.POPOVER crash on iPad

### ISSUE THREAD

**Issue by singularity-s0** [pichillilorenzo/flutter_inappwebview#911]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.2.3|
| Plugin version       | 5.3.2 |
| Android version      | N/A|
| iOS version          | 14.6|
| Xcode version        |12.5.1|

Device information: 
Apple iPad Pro 11-inch (2020)

## Description
When the iOS presentation style is set to `IOSUIModalPresentationStyle.POPOVER`, calling `openUrlRequest()` crashes the whole app on iPad. (the bug is in native code so flutter wasn't able to catch the error)

**Expected behavior:** 
Open a popover in-app broswer

**Current behavior:** 
Crash on iPad (works on iPhone)

## Steps to reproduce

1. Include this in options
```
ios: IOSInAppBrowserOptions(
        presentationStyle: IOSUIModalPresentationStyle.POPOVER,
      ),
```
2. Call `openUrlRequest()`
3. Then the app crashes.

## Stacktrace/Logcat   
```
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x122e34ab0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
*** First throw call stack:
(0x18c037754 0x1a0afe7a8 0x18e1d8bb8 0x18e1e48d0 0x18e1e2228 0x18ef02c98 0x18ea356c4 0x18ea2403c 0x18ea57f10 0x18bfb05e0 0x18bfaa704 0x18bfaacb0 0x18bfaa360 0x1a35e8734 0x18ea25584 0x18ea2adf4 0x104744034 0x18bc66cf8)
libc++abi: terminating with uncaught exception of type NSException
```

**Comment by Andreas409** [comment]
Experiencing the same. Some more info from the crash from XCode:

```
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x136804580>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
terminating with uncaught exception of type NSException
CoreSimulator 802.6.1 - Device: iPad Pro (11-inch) (3rd generation) (B8A0ED45-3D73-4471-BA80-285F46C6D579) - Runtime: iOS 15.5 (19F70) - DeviceType: iPad Pro (11-inch) (3rd generation)
```

**Comment by panda-zw** [comment]
So what's the solution to this?
