### ISSUE TITLE
goBack header missing and got an error page

### ISSUE THREAD

**Issue by EArminjon** [pichillilorenzo/flutter_inappwebview#913]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.2.2      |
| Plugin version       |          5.3.2     |
| Android version      |           10    |
| iOS version          |        14.6       |
| Xcode version        |           last    |

Device information: 

## Description

**Expected behavior:** 

When called goBack() I would go back to the previous page with the same context as previously.

**Current behavior:** 

I got an unauthorized page because the page is accessed without the right header (no header is provided).

## Steps to reproduce

```dart
InAppWebView(
  initialOptions: InAppWebViewGroupOptions(
  crossPlatform: InAppWebViewOptions(javaScriptEnabled: true),
    android: AndroidInAppWebViewOptions(
      mixedContentMode: AndroidMixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW,
      useHybridComposition: true,
      supportMultipleWindows: true,
    ),
    ios: IOSInAppWebViewOptions(allowsInlineMediaPlayback: true),
  ),
  onCreateWindow: (InAppWebViewController controller, CreateWindowAction createWindowAction) async {
    if (await canLaunch(createWindowAction.request.url.toString())) launch(createWindowAction.request.url.toString(), headers: createWindowAction.request.headers ?? const <String, String>{});
      return true;
  },
  initialUrlRequest: URLRequest(
    headers: MyCustomHeader,
    url: Uri.parse(MyCustomUrl),
  ),
),
```

1. Create a webview
2. Fill the initialRequest property with an url & a header
3. On the webview web page, go to an other website like google.com
4. Call the goBack method somewhere, you can see that you go back to your first page but the header is missing... As my first webpage require header for authentification, I got an error page...

**Comment by always-together12** [comment]
Hi, did you solve this issue?

**Comment by EArminjon** [comment]
@always-together12 I'm not sure. I did some PR and maybe it is fixed today.I need to take time to check if I can reproduce it.

Do you reproduce it ?
