### ISSUE TITLE
incompatibility error with image_picker

### ISSUE THREAD

**Issue by ahmadalghadban** [pichillilorenzo/flutter_inappwebview#918]
I'm getting this error with image_picker plugin
note: when I created the project in android studio, the option 'use androidX' was turned in.
the error message : 

Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_plugin_android_lifecycle'.
> Could not resolve all artifacts for configuration ':flutter_plugin_android_lifecycle:classpath'.
   > Could not find sdk-common-26.5.0.jar (com.android.tools:sdk-common:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.5.0/sdk-common-26.5.0.jar
   > Could not find ddmlib-26.5.0.jar (com.android.tools.ddms:ddmlib:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.5.0/ddmlib-26.5.0.jar
   > Could not find tracker-26.5.0.jar (com.android.tools.analytics-library:tracker:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.5.0/tracker-26.5.0.jar
   > Could not find sdklib-26.5.0.jar (com.android.tools:sdklib:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.5.0/sdklib-26.5.0.jar
   > Could not find layoutlib-api-26.5.0.jar (com.android.tools.layoutlib:layoutlib-api:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.5.0/layoutlib-api-26.5.0.jar
   > Could not find dvlib-26.5.0.jar (com.android.tools:dvlib:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.5.0/dvlib-26.5.0.jar
   > Could not find repository-26.5.0.jar (com.android.tools:repository:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.5.0/repository-26.5.0.jar
   > Could not find shared-26.5.0.jar (com.android.tools.analytics-library:shared:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.5.0/shared-26.5.0.jar
   > Could not find common-26.5.0.jar (com.android.tools:common:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.5.0/common-26.5.0.jar
   > Could not find jetifier-processor-1.0.0-beta04.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-beta04/jetifier-processor-1.0.0-beta04.jar
   > Could not find bundletool-0.9.0.jar (com.android.tools.build:bundletool:0.9.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.9.0/bundletool-0.9.0.jar
   > Could not find jetifier-core-1.0.0-beta04.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta04/jetifier-core-1.0.0-beta04.jar
   > Could not find protos-26.5.0.jar (com.android.tools.analytics-library:protos:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.5.0/protos-26.5.0.jar
   > Could not find apksig-3.5.0.jar (com.android.tools.build:apksig:3.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.5.0/apksig-3.5.0.jar
   > Could not find annotations-26.5.0.jar (com.android.tools:annotations:26.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.5.0/annotations-26.5.0.jar
   > Could not find databinding-common-3.5.0.jar (androidx.databinding:databinding-common:3.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.5.0/databinding-common-3.5.0.jar
   > Could not find baseLibrary-3.5.0.jar (com.android.databinding:baseLibrary:3.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.5.0/baseLibrary-3.5.0.jar
> Could not get unknown property 'android' for project ':flutter_plugin_android_lifecycle' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_plugin_android_lifecycle...
Running Gradle task 'assembleAarRelease'...

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Exception: The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.

**Comment by Gaurav192** [comment]
@ahmadalghadban If you're still facing this issue then either use latest version of image_picker plugin or use gradle version 3.5.4 instead of 4.0.1
