### ISSUE TITLE
isFeatureSupported plugin method not found

### ISSUE THREAD

**Issue by MihaMarkic** [pichillilorenzo/flutter_inappwebview#920]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.2.3          |
| Plugin version       |     5.3.2      |
| Android version      |   7.0      |

Device information: 

Elephone P8 Mini

## Description

I have a sample app (almost from documentation) and screen is just white.

**Expected behavior:** 

App starts and shows flutter ui including webview. Note: it does work on few phones I've tried but not on this specific one.

**Current behavior:** 

Displays just blank screen. From the call stack (logcat) below, it seems a problem with plugin communication.

## Steps to reproduce

Sample app from documentation template

## Stacktrace/Logcat   

E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method isFeatureSupported on channel com.pichillilorenzo/flutter_inappwebview_android_webviewfeature)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
    <asynchronous suspension>
    #1      AndroidWebViewFeature.isFeatureSupported (package:flutter_inappwebview/src/android/webview_feature.dart:257)
    <asynchronous suspension>
    #2      main (package:de_bavarianapps_gshopapp/main.dart:16)
    <asynchronous suspension>

**Comment by MihaMarkic** [comment]
I'm debugging, so more info: constructor of ServiceWorkerManager has problems in my case. Will debug further to see what exactly.

**Comment by AndreTheHunter** [comment]
Make sure `WidgetsFlutterBinding.ensureInitialized();` is called

**Comment by AndreTheHunter** [comment]
I'm having the same issue on iPhone simulator:
```dart
Future<void> onWebViewCreated(InAppWebViewController controller) async {
  if (await WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)) {
    await controller.addWebMessageListener(WebMessageListener(
      jsObjectName: 'MyMessageChannel',
      allowedOriginRules: {'my.host.com'},
      onPostMessage: (message, sourceOrigin, isMainFrame, replyProxy) async {
        print('Received message');
      },
    ));
  }
  await controller.loadUrl( urlRequest: URLRequest( url: WebUri('https://inappwebview.dev/docs/webview/javascript/communication#web-message-listeners')));
}

```

I tried deleting the app, and running `flutter clean`.

`flutter --version`:
```
Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f44110e (5 days ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
```

Using version: `flutter_inappwebview: ^6.0.0-beta.23`


Others are having similar issues:
1. https://github.com/pichillilorenzo/flutter_inappwebview/issues/209
1. https://github.com/pichillilorenzo/flutter_inappwebview/issues/1551

**Comment by jaypathak9460** [comment]
I am facing same issue and tried all the above mention solution but did not help
**flutter_inappwebview: ^6.0.0-beta.23**
**flutter --version**
`Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (4 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0`
