### ISSUE TITLE
[Flutter/iOS] [The camera and microphone permission popup will show every time when page started.]

### ISSUE THREAD

**Issue by FeifanChang** [pichillilorenzo/flutter_inappwebview#924]
## Environment

[✓] Flutter (Channel stable, 2.0.6, on macOS 11.0 20A2411 darwin-arm, locale zh-Hans-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

Plugin version :^5.3.2

## Description

Hi ! There is a question is the permission request dialog will show every time  when I use the inappwebview  and I have already used the 「permission_handler」to apply  camera and microphone permission.

I just want to apply it just one time.Could you help me to solve it?

![image](https://user-images.githubusercontent.com/61955978/126467660-1a9751f2-de5b-4a22-a805-6d55fe52725f.png)

**Comment by edbertvodea** [comment]
I reproduce same result on ios. I think this is browser permission request, which is not the same as the app permission request



Once you grant permission on an app level, the webview will always prompt you with the message you sent a screenshot. This is okay.

**Comment by edbertvodea** [comment]
I reproduce same result on ios. I think this is browser permission request, which is not the same as the app permission request

Once you grant permission on an app level, the webview will always prompt you with the message you sent a screenshot.

Is there any workaround to auto grant web permission request, like implementation androidOnPermissionRequest in android?
