### ISSUE TITLE
Failed to compile with Xcode 13.0 beta 3 (13A5192j)

### ISSUE THREAD

**Issue by HenryQuan** [pichillilorenzo/flutter_inappwebview#925]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | :-------------: |
| Flutter version      |        2.2.3       |
| Plugin version       |        5.3.2       |
| Android version      |    -           |
| iOS version          |       iOS 15 Beta 3        |
| Xcode version        |     13.0 Beta 3 (13A5192j)          |

Device information: Mac mini m1 2020

## Description

**Expected behavior:** 
Xcode should compile

**Current behavior:**
Swift Compile Error
- UserScript.swift:26:21: Overriding 'init' must be as available as declaration it overrides
- InAppWebView.swift:1447:17: Protocol 'WKNavigationDelegate' requires 'webView(_:decidePolicyFor:preferences:decisionHandler:)' to be available in iOS 10.0.0 and newer
- PluginScript.swift

## Steps to reproduce

1. Create a new project using `flutter create xxx`
2. Add `  flutter_inappwebview: ^5.3.2` to pubspec.yaml
3. Run `pod install` under `ios/`
3. Open the workspace with Xcode 13 Beta 3 (13A5192j)
4. The project fails to compile

By removing `flutter_inappwebview`, the project can build successfully.

## Images   
<img width="1063" alt="1" src="https://user-images.githubusercontent.com/6754708/126590443-89d440ec-cd9c-4347-82e8-97e14dd195fc.png">
<img width="1062" alt="2" src="https://user-images.githubusercontent.com/6754708/126590446-3e660dab-20a5-405d-a792-a6038280d697.png">

This is likely due to changes in iOS 15 or Swift 5.5 or Xcode 13. I can compile the same project with Xcode 12.5.1.

**Comment by pichillilorenzo** [comment]
I can compile without any error using XCode Version 13.3.1 (13E500a)
