### ISSUE TITLE
localStorage on iOS is not persistent 

### ISSUE THREAD

**Issue by ArielTM** [pichillilorenzo/flutter_inappwebview#928]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.2.3         |
| Plugin version       |     5.3.2          |
| Android version      |    11           |
| iOS version          |    14.6           |
| Xcode version        |     12.5.1          |

Device information: iPhone 11 Pro / iPhone 12 Pro Max / Samsung Galaxy S21

## Description

**Expected behavior:** 

"window.localStorage" data should be persistent between app launches

**Current behavior:** 

localStorage is being saved on Android. localStorage is cleared in iOS

## Steps to reproduce

1. Open Site that uses localstorage (e.g. http://www.sharonminsuk.com/code/storage-test.html)
2. save something in local storage
3. re run the app

**Comment by otopba** [comment]
Hey, @ArielTM!

I had the same problem until I noticed this: 
https://github.com/pichillilorenzo/flutter_inappwebview/commit/65e06984cb00f3dd3aa4e56a2cdc72ffea1e96ef

Check which `incognito` and `cacheEnabled` values you are using
