### ISSUE TITLE
need headers on ChromeSafariBrowser

### ISSUE THREAD

**Issue by kharisazhar** [pichillilorenzo/flutter_inappwebview#934]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.2.3      |
| Plugin version       |         5.3.2      |
| Android version      |         11      |
| iOS version          |           14.5    |
| Xcode version        |          12.4     |

Device information: Samsung a50s Android 11

## Description

**On version 4.0.0+4 The ChromeSafariBrowser have headersFallback** 

** the latest version  5.3.2 headers parameters has gone, i need to passing data to headers in ChromeSafariBrowser ** 

## Steps to reproduce

````
await browser.open(
        url: url,
        /// this below
        headersFallback: {'x-access-token': _token},
        options: ChromeSafariBrowserClassOptions(
            android:
                AndroidChromeCustomTabsOptions(addDefaultShareMenuItem: false),
            ios: IOSSafariOptions(barCollapsingEnabled: true)));
  }
```

1. I have read the docs & see other related issue, but only solution is use URLRequest class while ChromeSafariBrowser need Uri not URLRequest

Thanks.

**Comment by nikhilmufc7** [comment]
+1 on this, would be really helpful to add this feature
