### ISSUE TITLE
Cannot type when using mac keyboard on ios simulator

### ISSUE THREAD

**Issue by kcqnly** [pichillilorenzo/flutter_inappwebview#939]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         2.0.1      |
| Plugin version       |        5.3.2       |
| Android version      |        11       |
| iOS version          |         14.5      |
| Xcode version        |     12.5          |

Device information: iPhone12 Pro Max Simulator

## Description

**Expected behavior:**  can use mac keyboard typing in webview

**Current behavior:**  cannot type when using mac keyboard on ios simulator, can type when using softward keyboard, and android simulator is ok

## Steps to reproduce

1. open `http://sso.jwc.whut.edu.cn/Certification/login.do` in webview
2. use mac keyboard and then click the input

**Comment by sunjianan9900** [comment]
Same question
你找到解决方案了吗？我发现不仅不能输入文字，也不能弹出虚拟键盘

**Comment by kcqnly** [comment]
没有，这应该不是这个pub库的问题，而是flutter platform view的问题

**Comment by kcqnly** [comment]
> Same question
> 你找到解决方案了吗？我发现不仅不能输入文字，也不能弹出虚拟键盘

没有，这应该不是这个pub库的问题，而是flutter platform view的问题

**Comment by sunjianan9900** [comment]
> > Same question
> > 你找到解决方案了吗？我发现不仅不能输入文字，也不能弹出虚拟键盘
> 
> 没有，这应该不是这个pub库的问题，而是flutter platform view的问题

I/O > Keyboard > Connect Hardware Keyboard
把使用硬件键盘输入关掉，然后就能弹出来虚拟键盘，使用虚拟键盘可以输入
