### ISSUE TITLE
Releasing webview from memory

### ISSUE THREAD

**Issue by wickedman1976** [pichillilorenzo/flutter_inappwebview#94]
Hi,

Is there a dispose function available to kill the webview after use, for instance in a pageview the webview seems to stay in memory (looking at dev tools in safari).

Thanks

Nathan

**Comment by pichillilorenzo** [comment]
The `InAppWebView` widget should act like the other widgets, so the `dispose` function is called automatically when the widget is removed from the widget tree. If you see my example, switching tab from `Inline` and `Chrome/Safari`, the webview is being destroyed/disposed automatically.

**Comment by pichillilorenzo** [comment]
Ok, I see it me too on iOS! I will take a look about that

**Comment by pichillilorenzo** [comment]
I tried also the official plugin but seems to have the same issue!

**Comment by SteadyAction** [comment]
@pichillilorenzo any update on this? have same issue :(

**Comment by emidiao** [comment]
I'm experiencing the same issue on android, any update?

**Comment by pichillilorenzo** [comment]
Fix available starting from the version `3.0.0`.
