### ISSUE TITLE
Headers on Android ignored when using shouldOverrideUrlLoading()

### ISSUE THREAD

**Issue by ma-pe** [pichillilorenzo/flutter_inappwebview#941]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.2.3        |
| Plugin version       |      5.3.2         |
| Android version      |      9.0 (API Version 28)         |

Device information: Google Pixel 2 (Emulator)

## Description

**Expected behavior:** 
Using `shouldOverrideUrlLoading()` does not have any impact on the headers being set on `initialUrlRequest`.

**Current behavior:** 
Once I use `shouldOverrideUrlLoading()` Android does not send the headers anymore. This behaviour is only observed on Android, not on iOS.

## Steps to reproduce
1. Create a working example with headers being set:
```dart
InAppWebView(
  initialUrlRequest: URLRequest(
    url: Uri.parse('https://some.url'),
    headers: {'Some-Header': 'NO_HEADER'},
  ),
)
```
=> This works as expected. Header is sent.

2. Intercept the request, put allow it directly:
```dart
InAppWebView(
  initialUrlRequest: URLRequest(
    url: Uri.parse('https://some.url'),
    headers: {'Some-Header': 'NO_HEADER'},
  ),
  crossPlatform: InAppWebViewOptions(
    useShouldOverrideUrlLoading: true,
  ),
  shouldOverrideUrlLoading: (controller, event) async {
    return NavigationActionPolicy.ALLOW;
  },
)
```
=> Android does not send the Header anymore (iOS does).

**Comment by EArminjon** [comment]
In addition, header set in   initialUrlRequest: URLRequest() disappear in the following scenario :

A page required authentification from header and send an error if missing. I set the header in initialUrlRequest: URLRequest() and so I can access the page. The page contain a form as you can see bellow :
```
<form action="removed_for_github_issue" id="inscription" class="fields" enctype="multipart/form-data" method="post" accept-charset="utf-8">
```

When submitting the form, the error page about missing header appear. I think header aren't sent or aren't maintained on refresh...

**Comment by vishalknishad** [comment]
While intercepting, you need to add the headers again

```
  shouldOverrideUrlLoading: (controller, event) async {
        event.request.headers = {'Some-Header': 'NO_HEADER'};
        controller.loadUrl(urlRequest: event.request);
        return NavigationActionPolicy.CANCEL;
  }
```
