### ISSUE TITLE
a-tag href with absolute http treated a relative (IOS)

### ISSUE THREAD

**Issue by royvangeel** [pichillilorenzo/flutter_inappwebview#943]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.2.3              |
| Plugin version       | 5.3.2              |
| Android version      |               |
| iOS version          | iOS 13.3               |
| Xcode version        | 12.5.1 (12E507)              |

Device information: Emulator iPhone 8

## Description
This issue only applies to IOS, on Android it's working as expected.
An a-tag which contains an absolute http address is treated as relative.

It working as expected when:
- a-tag with relative http address
- a-tag with href which contains javascript: window.location = '{absolute-or-relative-http-address}'

**Expected behavior:** 
Example:
Initial opened url: http://www.initial-url.com
A-tag href: http://www.address-in-href.com/example-file.pdf

When tapping the a-tag I expect to download/open:
http://www.address-in-href.com/example-file.pdf

**Current behavior:** 
Example:
Initial opened url: http://www.initial-url.com
A-tag href: http://www.address-in-href.com/example-file.pdf

When tapping the a-tag it's opening (print url in onLoadStart):
http://www.initial-url.com/http://www.address-in-href.com/example-file.pdf

## Steps to reproduce
I cannot provide the page (because of local development), but it's prettty straightforward.

**Comment by royvangeel** [comment]
Anyone?

**Comment by RomanSoviak** [comment]
Are there updates?
