### ISSUE TITLE
Intercepts requests in network

### ISSUE THREAD

**Issue by Rashid-Khabeer** [pichillilorenzo/flutter_inappwebview#945]
I am building a simple application.

I created a web View and opened a random YouTube video in it. The thing is I want to read all the requests/calls that are called by YouTube's link.

![4xr99](https://user-images.githubusercontent.com/71066995/129669042-37bb7f4a-95e8-49f4-b74a-56c2565b2880.png)

I want to intercept these requests/calls and do something with them.

Need help!

**Comment by sunjianan9900** [comment]
any update ? thanks
