### ISSUE TITLE
In android, when click a href with img returns img src on onCreateWindow

### ISSUE THREAD

**Issue by SimJinwoong** [pichillilorenzo/flutter_inappwebview#951]
- [O] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [O] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [O] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [O] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.2.3             |
| Plugin version       |  5.3.2             |
| Android version      |   10              |
| iOS version          |               |
| Xcode version        |               |

Device information: LG G7, Samsung Galaxy Z flip 

## Description
In android, when click a-tag with img-tag, 
createWindowRequest.request.url returns img-src on onCreateWindow method.
`
    <body>
        <p>Open link in a new window or tab: <a href="https://www.w3schools.com" target="_blank">Visit W3Schools!</a></p>
        <p><a href="http://www.google.com" target="_blank"><img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png"/></a></p>
    </body>
 `

When I modified the following in the onCreateWindow function of the InAppWebViewChromeClient.java class, I was able to get the correct result.
` 
  public boolean onCreateWindow(WebView view, boolean isDialog, boolean isUserGesture, final Message resultMsg) {
    WebView.HitTestResult result = view.getHitTestResult();
    String url = result.getExtra();
    Log.i(LOG_TAG, "onCreateWindow url = "+ result.getExtra() + " , type = " + result.getType());

    //Link with Image
    if(result.getType()==HitTestResult.SRC_IMAGE_ANCHOR_TYPE) {
      Message href = view.getHandler().obtainMessage();
      view.requestFocusNodeHref(href);
      String url2 = href.getData().getString("url");
      Log.i(LOG_TAG, "onCreateWindow url2 = "+ url2);
      if(url2.isEmpty() == false)
        url = url2;
    }
  } 

`

Hopefully it will be improved in the next version.

**Comment by Manuito83** [comment]
Thank you, this is a key fix for Android.

**Comment by pichillilorenzo** [comment]
Merged 6b7e4b856f8c6ec56e8522853a27c84b2d0704b3
