### ISSUE TITLE
bleutooht printer

### ISSUE THREAD

**Issue by bmyc** [pichillilorenzo/flutter_inappwebview#952]
Hi, how can i run bluetooth printer with on Print command inside inappwebview plugin

**Comment by renzorosaz** [comment]
Hello bro! you have to check your versions 
![Screen Shot 2021-09-16 at 8 45 41 AM](https://user-images.githubusercontent.com/43652358/133623513-0788e57d-dd6d-4d42-bd83-66b72415a9a4.png)
![Screen Shot 2021-09-16 at 8 45 48 AM](https://user-images.githubusercontent.com/43652358/133623536-e9ac15bf-90fb-4bed-ba9f-e86ae7a26072.png)

You can use this libraries, there are powerfull!,
