### ISSUE TITLE
Android only issue with pinch zooming/rotating

### ISSUE THREAD

**Issue by lukey78** [pichillilorenzo/flutter_inappwebview#957]
In my App Peaks! (https://play.google.com/store/apps/details?id=com.adventurelog.peaks) I'm embedding a flutter_inappwebview to display a 3D world based on CesiumJs.

Everything works great except for the pinch-to-zoom and pinch-rotate two finger gestures. They both do well on iOs, but not on Android. 

The behaviour is that it works "a little" each time. The zooming is not intuitive. It seems the evens are captured and stopped somewhere, and only a small part of the zoom event reaches CesiumJs inside the webview. Sometimes this also applies to simple horizontal/vertical move gestures.

Can anyone point me into the right direction? I already tried with/without hybrid composition, and setting/unsetting zoom options.

I've uploaded a demonstration of the problem inside an emulator view: https://youtu.be/AGE_H3_66EU

**Comment by RustemMuzafarov** [comment]
Hi @lukey78 ! Have you by any chance found a solution?

**Comment by Sunsiha** [comment]
Any solution?
