### ISSUE TITLE
iOS Disable auto scroll on input focus

### ISSUE THREAD

**Issue by nongtiny** [pichillilorenzo/flutter_inappwebview#971]
## Environment

**Flutter version:**  Flutter (Channel stable, 2.0.6, on macOS 11.5.2 20G95 darwin-x64, locale en-TH)
**Plugin version:**  5.3.0
**Android version:**  
**iOS version:** 14.6
**Xcode version:**  12.5.1
**Device information:**  iPhone 11

## Description

**What you'd like to happen:** 

I have a widget above the WebView widget. When I click on the input field, it scrolls incorrectly. Rendering only WebView in the scaffold works perfectly. I would like to know is there a way to disable this?

Thanks for implementing this wonderful package.

**Comment by nongtiny** [comment]
I fixed it manually with flutter scroll controller.

**Comment by LEHOANGLONG0807** [comment]
@nongtiny 

can you share me how to fix it?
