### ISSUE TITLE
onLoadStart and shouldOverrideUrlLoading not called

### ISSUE THREAD

**Issue by Roee-Tsur** [pichillilorenzo/flutter_inappwebview#974]
Hello,
I am implementing both of the functions and both are called only occasionally.

What function should I use if I want to set a callback every time the URL changes?

Of course, that useShouldOverrideUrlLoading is set to true.

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.2.3         |
| Plugin version       |       5.3.2         |
| Android version      |       10        |
| iOS version          |               |
| Xcode version        |               |

**Comment by alandotic** [comment]
can refers to the doc here
https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebViewOptions/useShouldOverrideUrlLoading.html

**Comment by dayron9110** [comment]
Same issue here with the 5.7.2+3 version
