### ISSUE TITLE
Get the download URL of the current video playing

### ISSUE THREAD

**Issue by itssidhere** [pichillilorenzo/flutter_inappwebview#977]
## Description

I want to get the download URL of the video which is currently playing. What callback is invoked when a video starts playing? Does that also include the video URL argument?

**USE-CASE**
Suppose I want to play the video on this [https://www.videvo.net/video/close-up-shot-rain-drops-falling-on-leaves/783004/](link). I want to get the URL of that video so that I can play the video on any other player like [https://pub.dev/packages/video_player](video_player)

**Comment by shipinbaoku** [comment]
also need
