### ISSUE TITLE
PullToRefreshController - Fail - Does not work repedly - Only once time

### ISSUE THREAD

**Issue by renzorosaz** [pichillilorenzo/flutter_inappwebview#980]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| Flutter | 2.2.0 |
| Flutter version      |     2.2.0          |
| Plugin version       |     flutter_inappwebview: ^5.3.2          |
| Android version      |   21 min.            |
| iOS version          |    -           |
| Xcode version        |   -            |

Device information:  Xiaomi 10s Pro

## Description

I am using InAppWebView in my flutter project, when I use the PullToRefreshController  :

 pullToRefreshController: PullToRefreshController(
                options: PullToRefreshOptions(enabled: true),
                onRefresh: () {
                  webViewController.reload();
                }),

once time it is works, but when i use again does not work, I am not sure why!!!!, I added options like

 InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      android: AndroidInAppWebViewOptions(
    useHybridComposition: true,
  ));

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   
![Screen Shot 2021-09-16 at 8 44 22 AM](https://user-images.githubusercontent.com/43652358/133623284-97708d90-039a-41ec-b396-e431f1e6bab9.png)

**Comment by vijaypareek13** [comment]
I also found the same problem. It refresh only once.

**Comment by keithcwk** [comment]
@renzorosaz @vijaypareek13 

I also encountered the same problem, but I managed to make it work. There are two things to take note of: 
1. Ensure that the InAppWebView is wrapped by a stateful widget. 
	- Instantiate a variable of type `PullToRefreshController`, and assign your `PullToRefreshOptions` to it in `initState`, example: 
	```
		PullToRefreshController? refreshController;

		@override
		  void initState() {
		    refreshController = PullToRefreshController(
				onRefresh: () async {
			      onRefreshFunction();	
			    });
		    super.initState();
		  }
	```

2. Ensure that the `PullToRefreshController`'s `endRefreshing` callback is called in `onLoadStop`
	```
		 Expanded(
            child: InAppWebView(
              pullToRefreshController: refreshController,
              initialOptions: initialOptions,
              initialUrlRequest: URLRequest(
                url: Uri.parse(url)
			 ),
              onLoadStop: (controller, uri) {
				// ***important***
                refreshController!.endRefreshing();
              },
            ),
          ),
	```
