### ISSUE TITLE
Doubt about IOS return behavior

### ISSUE THREAD

**Issue by ederluca** [pichillilorenzo/flutter_inappwebview#981]
## Environment

**Flutter version:2.0.6 
**Plugin version: 5.3.2
**iOS version: 14.7.1
**Xcode version: 12.5.1  
**Device information: Iphone 6S  

## Description
Good Morning

I'm developing an application using the flutter_inappwebview package, I'm using the InAppWebView class and this is wrapped inside a WillPopScope.

On Android, whenever I press the native back button, the application runs a routine inside the onwillpop event, this is working without any problem;

In IOS when I do the back gesture I go back to the previous screen but the onwillpop event is not fired;

My question is the following inside InAppWebview is there any method where I can implement what happens when I do the back gesture? I would like to trigger a function when this occurs.

I even managed to handle this behavior by disabling the allowsBackForwardNavigationGestures option as false and wrapping the InAppWebView in a RawGestureDetector then I did the treatment to capture the gestures horizontally, the same works but I lose the animation of the transition between screens.

**Comment by charlestang** [comment]
Maybe it's not an issue of InAppWebview, instead an issue of Flutter.
https://github.com/flutter/flutter/issues/14203
