### ISSUE TITLE
goggle meet url not opening

### ISSUE THREAD

**Issue by maheshts** [pichillilorenzo/flutter_inappwebview#983]
when i am clicking googlemeet url inside the webview thats not opening.
When i am upload image also not working,
![WhatsApp Image 2021-09-19 at 21 59 35](https://user-images.githubusercontent.com/9674608/133955680-a9ffdbcd-f075-4c29-be29-f47faa312ed8.jpeg)

**Comment by pichillilorenzo** [comment]
To manage URLs with custom schemas, you need to implement your specific logic by yourself, for example, implementing the `shouldOverrideUrlLoading` event.

For example, using it with the `url_launcher` plugin:
```dart
shouldOverrideUrlLoading: (controller, navigationAction) async {
  var uri = navigationAction.request.url!;

  if (![
    "http",
    "https",
    "file",
    "chrome",
    "data",
    "javascript",
    "about"
  ].contains(uri.scheme)) {
    if (await canLaunch(url)) {
      // Launch the App
      await launch(
        url,
      );
      // and cancel the request
      return NavigationActionPolicy.CANCEL;
    }
  }

  return NavigationActionPolicy.ALLOW;
}
```
