### ISSUE TITLE
Unable to start activity ComponentInfo{com.sf.iapp/com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by Super-Bin** [pichillilorenzo/flutter_inappwebview#985]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       2.2.0        |
| Plugin version       |     5.3.2          |
| Android version      |       10        |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
App shouldn't be crash.

**Current behavior:** 
Here is the log from the Firebase Crashlytics-

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   
![inapp_webview](https://user-images.githubusercontent.com/26457469/134321443-743b5a28-dcc9-40a4-814c-c9d5f77bc8b8.png)

## Stacktrace/Logcat   
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
com.pichillilorenzo.flutter_inappwebview.in_app_browser.InAppBrowserActivity.onCreate (InAppBrowserActivity.java:70)
android.app.Activity.performCreate (Activity.java:8085)
android.app.Activity.performCreate (Activity.java:8073)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1320)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3850)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4056)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:91)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:149)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:103)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2464)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8299)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1052)
![inapp_webview](https://user-images.githubusercontent.com/26457469/134321416-c3c5ed42-02f2-4ddc-bf79-bf9bf8221d30.png)

```

reference：https://github.com/pichillilorenzo/flutter_inappwebview/issues/665

**Comment by nietsmmar** [comment]
I got the same issue

**Comment by pansitwattana** [comment]
I also got this crash error

flutter_inappwebview: ^5.3.2
Flutter version: 2.2.0
Android: 8.1.0
Device: Nexus 5X
