### ISSUE TITLE
How to set cookies when I load resource files locally？

### ISSUE THREAD

**Issue by kimmy-wang** [pichillilorenzo/flutter_inappwebview#988]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.5.1          |
| Plugin version       |      5.3.2         |
| Android version      |               |
| iOS version          |      ios15         |
| Xcode version        |      xcode13         |

Device information: 

## Description

How to set cookies when I load resource files locally？

```
InAppWebView(
  initialFile: 'dist/about.html',
  initialOptions: InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      cacheEnabled: false,
      clearCache: true,
    ),
  ),
  onWebViewCreated: (InAppWebViewController controller) async {
    await _initCookieManager();
  },
)
```

```
Future<void> _initCookieManager() async {
  printWarningLog('_initCookieManager');
  String urlStr = await rootBundle.loadString('dist/about.html');
  Uri? url = Uri.tryParse(urlStr);
  final expiresDate =
      DateTime.now().add(Duration(days: 3)).millisecondsSinceEpoch;
  await _cookieManager.setCookie(
    url: url!,
    name: "myCookie",
    value: "myValue",
    expiresDate: expiresDate,
    domain: urlStr,
    isSecure: false,
  );
  Cookie? cookie = await _cookieManager.getCookie(url: url, name: "myCookie");
  printWarningLog('cookie: [$cookie]');
}
```

**Comment by otopba** [comment]
Any updates?

**Comment by ndelanou** [comment]
It would help a lot to be able to set the `baseUrl` while loading from a file
