### ISSUE TITLE
How to Handle (Tel:,Mailto:,Wa:,Sms:) In Flutter Inappwebview?

### ISSUE THREAD

**Issue by dickynh2292** [pichillilorenzo/flutter_inappwebview#989]
excuse me sir, permission to ask,
I'm just learning flutter and am trying to make an application using package _inappwebview & url_launcher,
Well, I'm having trouble trying to handle mailto, tel, etc.

Now when the link is clicked (eg href=tel:), it does exit the application but why does it go to the chrome browser (opens the webview url) instead of going to the phone.
Can anyone help me to tell where is my error?

My full code example can be seen here:
https://stackoverflow.com/questions/69335637/how-to-handle-tel-mailto-wa-sms-in-flutter-inappwebview

```

import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:permission_handler/permission_handler.dart';

void main() async {
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.white, // status bar color
    statusBarIconBrightness: Brightness.dark, // status bar icon color
    systemNavigationBarColor: Colors.white, // navigation bar color
    systemNavigationBarIconBrightness: Brightness.dark, // color of navigation controls
  ));
  WidgetsFlutterBinding.ensureInitialized();
  await Permission.camera.request();
  await Permission.microphone.request();
  await Permission.storage.request();
  await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  await FlutterDownloader.initialize(debug: true);
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late InAppWebViewController webViewController;
  GlobalKey<ScaffoldState>webViewKey=GlobalKey<ScaffoldState>();

  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,
        javaScriptEnabled: true,
        javaScriptCanOpenWindowsAutomatically: true,
        useOnDownloadStart: true,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      )
  );

  late PullToRefreshController pullToRefreshController;
  String url = "";
  double progress = 0;
  final urlController = TextEditingController();

  @override
  void initState() {
    super.initState();
    pullToRefreshController = PullToRefreshController(
      options: PullToRefreshOptions(
        color: Colors.red,
      ),
      onRefresh: () async {
        if (Platform.isAndroid) {
          webViewController.reload();
        } else if (Platform.isIOS) {
          webViewController.loadUrl(
              urlRequest: URLRequest(url: await webViewController.getUrl()));
        }
      },
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: _onBack,
      child: Scaffold(
          key: webViewKey,
          appBar: null,
          body: SafeArea(
              child: Column(children: <Widget>[
                Expanded(
                  child: Stack(
                    children: [
                      InAppWebView(
                        initialUrlRequest: URLRequest(url: Uri.parse("https://ummmah.com/")),
                        initialOptions: options,
                        pullToRefreshController: pullToRefreshController,
                        onWebViewCreated: (controller) {
                          webViewController = controller;
                        },
                        onLoadStart: (controller, url) {
                          setState(() {
                            this.url = url.toString();
                            urlController.text = this.url;
                          });
                        },
                        androidOnPermissionRequest: (controller, origin, resources) async {
                          return PermissionRequestResponse(
                              resources: resources,
                              action: PermissionRequestResponseAction.GRANT);
                        },



                        shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
                          var uri = shouldOverrideUrlLoadingRequest.request.url!;
                          if (uri.scheme.startsWith("tel")) {
                            if (await canLaunch(url)) {
                              await launch(
                                url,
                              );
                              return NavigationActionPolicy.CANCEL;
                            }
                          }
                          return NavigationActionPolicy.ALLOW;
                        },



                        onLoadStop: (controller, url) async {
                          pullToRefreshController.endRefreshing();
                          setState(() {
                            this.url = url.toString();
                            urlController.text = this.url;
                          });
                        },
                        onLoadError: (controller, url, code, message) {
                          pullToRefreshController.endRefreshing();
                        },
                        onProgressChanged: (controller, progress) {
                          if (progress == 100) {
                            pullToRefreshController.endRefreshing();
                          }
                          setState(() {
                            this.progress = progress / 100;
                            urlController.text = this.url;
                          });
                        },
                        onUpdateVisitedHistory: (controller, url, androidIsReload) {
                          setState(() {
                            this.url = url.toString();
                            urlController.text = this.url;
                          });
                        },
                        onConsoleMessage: (controller, consoleMessage) {
                          print(consoleMessage);
                        },
                      ),
                      progress < 1.0
                          ? LinearProgressIndicator(
                              value: progress,
                              minHeight: 2,
                          )
                          : Container(),
                    ],
                  ),
                ),
              ]
              )
          )
      ),
    );
  }

  Future<bool> _onBack() async {
    bool goBack;
    if (await webViewController.canGoBack()) {
      webViewController.goBack();
      return false;
    } else {
      showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Text('Kamu yakin ingin keluar ?'),
            actions: <Widget>[
              FlatButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: Text('Tidak'),
              ),
              FlatButton(
                onPressed: () {
                  SystemNavigator.pop();
                },
                child: Text('Iya'),
              ),
            ],
          ));
      return Future.value(true);
    }
  }

}

```

**Comment by dickynh2292** [comment]
- [ ]

**Comment by Tomspol** [comment]
Have you found solution to this problem?

**Comment by dickynh2292** [comment]
> Have you found solution to this problem?

Yes

**Comment by Tomspol** [comment]
Could you please elaborate on how you resolved it? I'm having similar issue.

**Comment by dickynh2292** [comment]
Sorry to reply now,
Because I'm just back online on github. you can try this code:


**androidmanifest :**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.app4">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_SMS" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />

    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="http" />
            <category android:name="android.intent.category.BROWSABLE" />
        </intent>
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>

    <application
        android:label="app4"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:usesCleartextTraffic="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**main.dart :**
```

import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';

void main() async {
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.white, // status bar color
    statusBarIconBrightness: Brightness.dark, // status bar icon color
    systemNavigationBarColor: Colors.white, // navigation bar color
    systemNavigationBarIconBrightness: Brightness.dark, // color of navigation controls
  ));
  WidgetsFlutterBinding.ensureInitialized();
  await Permission.camera.request();
  await Permission.microphone.request();
  await Permission.storage.request();
  await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  await FlutterDownloader.initialize(debug: true);
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String url = "";
  double progress = 0;
  late PullToRefreshController pullToRefreshController;

  final urlController = TextEditingController();
  late InAppWebViewController webViewController;
  GlobalKey<ScaffoldState>webViewKey=GlobalKey<ScaffoldState>();

  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,
        javaScriptEnabled: true,
        javaScriptCanOpenWindowsAutomatically: true,
        useOnDownloadStart: true,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      )
  );


  @override
  void initState() {
    super.initState();
    pullToRefreshController = PullToRefreshController(
      options: PullToRefreshOptions(
        color: Colors.red,
      ),
      onRefresh: () async {
        if (Platform.isAndroid) {
          webViewController.reload();
        } else if (Platform.isIOS) {
          webViewController.loadUrl(
              urlRequest: URLRequest(url: await webViewController.getUrl()));
        }
      },
    );
  }

  @override
  void dispose() {
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: _onBack,
      child: Scaffold(
          key: webViewKey,
          appBar: null,
          body: SafeArea(
              child: Column(children: <Widget>[
                Expanded(
                  child: Stack(
                    children: [
                      InAppWebView(
                        initialUrlRequest: URLRequest(url: Uri.parse("http://192.168.1.100/m/index")),
                        initialOptions: options,
                        pullToRefreshController: pullToRefreshController,
                        onWebViewCreated: (controller) {
                          webViewController = controller;
                        },
                        onLoadStart: (controller, url) {
                          setState(() {
                            this.url = url.toString();
                            urlController.text = this.url;
                          });
                        },
                        androidOnPermissionRequest: (controller, origin, resources) async {
                          return PermissionRequestResponse(
                              resources: resources,
                              action: PermissionRequestResponseAction.GRANT);
                        },

                        shouldOverrideUrlLoading: (controller, navigationAction) async {
                        var url = navigationAction.request.url;
                        if (url != null && !["http", "file", "chrome", "data", "javascript", "about"].contains(url.scheme)) {
                          if (await canLaunch(url.toString())) {
                            await launch(
                              url.toString(),
                            );
                            return NavigationActionPolicy.CANCEL;
                          }
                        }
                        return NavigationActionPolicy.ALLOW;
                        },


                        onLoadStop: (controller, url) async {
                          pullToRefreshController.endRefreshing();
                          setState(() {
                            this.url = url.toString();
                            urlController.text = this.url;
                          });
                        },
                        onLoadError: (controller, url, code, message) {
                          pullToRefreshController.endRefreshing();
                          webViewController.loadFile(assetFilePath: "assets/error.html");
                        },
                        onProgressChanged: (controller, progress) {
                          if (progress == 100) {
                            pullToRefreshController.endRefreshing();
                          }
                          setState(() {
                            this.progress = progress / 100;
                            urlController.text = this.url;
                          });
                        },
                        onUpdateVisitedHistory: (controller, url, androidIsReload) {
                          setState(() {
                            this.url = url.toString();
                            urlController.text = this.url;
                          });
                        },
                        onConsoleMessage: (controller, consoleMessage) {
                          print(consoleMessage);
                        },
                      ),
                      progress < 1.0
                          ? LinearProgressIndicator(
                              value: progress,
                              minHeight: 2,
                          )
                          : Container(),
                    ],
                  ),
                ),
              ]
              )
          )
      ),
    );
  }

  Future<bool> _onBack() async {
    bool goBack;
    if (await webViewController.canGoBack()) {
      webViewController.goBack();
      return false;
    } else {
      return Future.value(true);
    }
  }
}

```

**Comment by alexeenko-frontend** [comment]
> Sorry to reply now, Because I'm just back online on github. you can try this code:
> 
> **androidmanifest :**
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.app4">
> 
>     <uses-permission android:name="android.permission.INTERNET"/>
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
>     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
>     <uses-permission android:name="android.permission.CALL_PHONE" />
>     <uses-permission android:name="android.permission.READ_PHONE_STATE" />
>     <uses-permission android:name="android.permission.READ_SMS" />
>     <uses-permission android:name="android.permission.SEND_SMS" />
>     <uses-permission android:name="android.permission.VIBRATE" />
>     <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
>     <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
>     <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
>     <uses-permission android:name="android.permission.CAMERA" />
>     <uses-permission android:name="android.permission.RECORD_AUDIO" />
>     <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
>     <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
>     <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
> 
>     <queries>
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="http" />
>             <category android:name="android.intent.category.BROWSABLE" />
>         </intent>
>         <intent>
>             <action android:name="android.intent.action.DIAL" />
>             <data android:scheme="tel" />
>         </intent>
>         <intent>
>             <action android:name="android.intent.action.SEND" />
>             <data android:mimeType="*/*" />
>         </intent>
>     </queries>
> 
>     <application
>         android:label="app4"
>         android:icon="@mipmap/ic_launcher">
>         <activity
>             android:name=".MainActivity"
>             android:usesCleartextTraffic="true"
>             android:launchMode="singleTop"
>             android:theme="@style/LaunchTheme"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:windowSoftInputMode="adjustResize">
>             <meta-data
>               android:name="io.flutter.embedding.android.NormalTheme"
>               android:resource="@style/NormalTheme"
>               />
>             <meta-data
>               android:name="io.flutter.embedding.android.SplashScreenDrawable"
>               android:resource="@drawable/launch_background"
>               />
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN"/>
>                 <category android:name="android.intent.category.LAUNCHER"/>
>             </intent-filter>
>         </activity>
> 
>         <provider
>             android:name="androidx.core.content.FileProvider"
>             android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
>             android:exported="false"
>             android:grantUriPermissions="true">
>             <meta-data
>                 android:name="android.support.FILE_PROVIDER_PATHS"
>                 android:resource="@xml/provider_paths" />
>         </provider>
>         <provider
>             android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
>             android:authorities="${applicationId}.flutter_downloader.provider"
>             android:exported="false"
>             android:grantUriPermissions="true">
>             <meta-data
>                 android:name="android.support.FILE_PROVIDER_PATHS"
>                 android:resource="@xml/provider_paths"/>
>         </provider>
> 
>         <meta-data
>             android:name="flutterEmbedding"
>             android:value="2" />
>     </application>
> </manifest>
> ```
> 
> **main.dart :**
> 
> ```
> 
> import 'dart:async';
> import 'dart:collection';
> import 'dart:convert';
> import 'dart:io';
> import 'dart:typed_data';
> import 'package:flutter/services.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter_inappwebview/flutter_inappwebview.dart';
> import 'package:url_launcher/url_launcher.dart';
> import 'package:flutter_downloader/flutter_downloader.dart';
> import 'package:permission_handler/permission_handler.dart';
> import 'package:path_provider/path_provider.dart';
> import 'package:provider/provider.dart';
> 
> void main() async {
>   SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
>     statusBarColor: Colors.white, // status bar color
>     statusBarIconBrightness: Brightness.dark, // status bar icon color
>     systemNavigationBarColor: Colors.white, // navigation bar color
>     systemNavigationBarIconBrightness: Brightness.dark, // color of navigation controls
>   ));
>   WidgetsFlutterBinding.ensureInitialized();
>   await Permission.camera.request();
>   await Permission.microphone.request();
>   await Permission.storage.request();
>   await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
>   await FlutterDownloader.initialize(debug: true);
>   runApp(MaterialApp(home: MyApp()));
> }
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => new _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   String url = "";
>   double progress = 0;
>   late PullToRefreshController pullToRefreshController;
> 
>   final urlController = TextEditingController();
>   late InAppWebViewController webViewController;
>   GlobalKey<ScaffoldState>webViewKey=GlobalKey<ScaffoldState>();
> 
>   InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
>       crossPlatform: InAppWebViewOptions(
>         useShouldOverrideUrlLoading: true,
>         mediaPlaybackRequiresUserGesture: false,
>         javaScriptEnabled: true,
>         javaScriptCanOpenWindowsAutomatically: true,
>         useOnDownloadStart: true,
>       ),
>       android: AndroidInAppWebViewOptions(
>         useHybridComposition: true,
>       ),
>       ios: IOSInAppWebViewOptions(
>         allowsInlineMediaPlayback: true,
>       )
>   );
> 
> 
>   @override
>   void initState() {
>     super.initState();
>     pullToRefreshController = PullToRefreshController(
>       options: PullToRefreshOptions(
>         color: Colors.red,
>       ),
>       onRefresh: () async {
>         if (Platform.isAndroid) {
>           webViewController.reload();
>         } else if (Platform.isIOS) {
>           webViewController.loadUrl(
>               urlRequest: URLRequest(url: await webViewController.getUrl()));
>         }
>       },
>     );
>   }
> 
>   @override
>   void dispose() {
>     super.dispose();
>   }
> 
> 
>   @override
>   Widget build(BuildContext context) {
>     return WillPopScope(
>       onWillPop: _onBack,
>       child: Scaffold(
>           key: webViewKey,
>           appBar: null,
>           body: SafeArea(
>               child: Column(children: <Widget>[
>                 Expanded(
>                   child: Stack(
>                     children: [
>                       InAppWebView(
>                         initialUrlRequest: URLRequest(url: Uri.parse("http://192.168.1.100/m/index")),
>                         initialOptions: options,
>                         pullToRefreshController: pullToRefreshController,
>                         onWebViewCreated: (controller) {
>                           webViewController = controller;
>                         },
>                         onLoadStart: (controller, url) {
>                           setState(() {
>                             this.url = url.toString();
>                             urlController.text = this.url;
>                           });
>                         },
>                         androidOnPermissionRequest: (controller, origin, resources) async {
>                           return PermissionRequestResponse(
>                               resources: resources,
>                               action: PermissionRequestResponseAction.GRANT);
>                         },
> 
>                         shouldOverrideUrlLoading: (controller, navigationAction) async {
>                         var url = navigationAction.request.url;
>                         if (url != null && !["http", "file", "chrome", "data", "javascript", "about"].contains(url.scheme)) {
>                           if (await canLaunch(url.toString())) {
>                             await launch(
>                               url.toString(),
>                             );
>                             return NavigationActionPolicy.CANCEL;
>                           }
>                         }
>                         return NavigationActionPolicy.ALLOW;
>                         },
> 
> 
>                         onLoadStop: (controller, url) async {
>                           pullToRefreshController.endRefreshing();
>                           setState(() {
>                             this.url = url.toString();
>                             urlController.text = this.url;
>                           });
>                         },
>                         onLoadError: (controller, url, code, message) {
>                           pullToRefreshController.endRefreshing();
>                           webViewController.loadFile(assetFilePath: "assets/error.html");
>                         },
>                         onProgressChanged: (controller, progress) {
>                           if (progress == 100) {
>                             pullToRefreshController.endRefreshing();
>                           }
>                           setState(() {
>                             this.progress = progress / 100;
>                             urlController.text = this.url;
>                           });
>                         },
>                         onUpdateVisitedHistory: (controller, url, androidIsReload) {
>                           setState(() {
>                             this.url = url.toString();
>                             urlController.text = this.url;
>                           });
>                         },
>                         onConsoleMessage: (controller, consoleMessage) {
>                           print(consoleMessage);
>                         },
>                       ),
>                       progress < 1.0
>                           ? LinearProgressIndicator(
>                               value: progress,
>                               minHeight: 2,
>                           )
>                           : Container(),
>                     ],
>                   ),
>                 ),
>               ]
>               )
>           )
>       ),
>     );
>   }
> 
>   Future<bool> _onBack() async {
>     bool goBack;
>     if (await webViewController.canGoBack()) {
>       webViewController.goBack();
>       return false;
>     } else {
>       return Future.value(true);
>     }
>   }
> }
> ```

Thank you very much! You saved my life)
