### ISSUE TITLE
transparentBackground not working on Android 

### ISSUE THREAD

**Issue by peekpt** [pichillilorenzo/flutter_inappwebview#99]
The transparent background on initial options of InAppWebView isn't working on Android. But it works on iOS

![transparent Background issue](https://user-images.githubusercontent.com/222385/58256733-691b2180-7d67-11e9-9660-76e952c18b8b.gif)

**Comment by pichillilorenzo** [comment]
I have played a little with this and it seems that there is a bug with the Flutter engine only on Android (https://github.com/flutter/plugins/pull/1336)
