### ISSUE TITLE
IOSInAppBrowserOptions toolbarTopTranslucent not working

### ISSUE THREAD

**Issue by hazzo** [pichillilorenzo/flutter_inappwebview#997]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |        2.5.1       |
| Plugin version       |        5.3.2       |
| Android version      |               |
| iOS version          |        15       |
| Xcode version        |        13       |

Device information:  iPhone 11 Pro Max

## Description

**Expected behavior:** 
`IOSInAppBrowserOptions` use non translucent top toolbar option.

**Current behavior:** 
Top toolbar is translucent and with `IOSInAppBrowserOptions` is not possible to change it.

## Images
The background color is from the app not the in app browser.
![File](https://user-images.githubusercontent.com/13692810/135810873-3c741810-f6eb-4aa4-8fc7-24f38f648d94.jpg)

**Comment by appcapsergen** [comment]
Did you manage to fix this somehow?
